### ISSUE TITLE
Don't Spam Log with call Outputs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1002]
This is a really really bad idea. Especially for large output :)

**Comment by cjllanwarne** [comment]
Specifically, I'm talking about the line in the logs:

```
2016-06-14 14:31:34,517 cromwell-system-akka.actor.default-dispatcher-50 INFO  - Job Workflow.Task:NA:1 succeeded! Outputs: [..., ..., blah, blah, ...]
```

**Comment by ruchim** [comment]
@cjllanwarne @geoffjentry do we need to keep inputs/outputs in the Cromwell logs?

**Comment by geoffjentry** [comment]
I personally file that in the category of things which aren't useful often enough to warrant the bulk they take up in the logs. And as @cjllanwarne points out, it can actually be deleterious. See #778

**Comment by geoffjentry** [comment]
I'd be ok w/ having it moved to debug level if ppl wanted to keep it
