### ISSUE TITLE
AsyncBackendJobExecutionActor has its own retry

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1004]
yet we have a generic retry system

**Comment by cjllanwarne** [comment]
As I mentioned in the original PR, inside an actor doesn't feel like a philosophically good place for this sort of Future-based retry logic (which has plenty of good uses elsewhere). And that's maybe why the two different `retry`s don't play nicely together

**Comment by geoffjentry** [comment]
@cjllanwarne Really it's just that they were developed simultaneously, and it's probably my fault for not going back and cleaning the other one up. In retrospect I knew it existed, but probably just lost track of it.

I certainly wouldn't disapprove of converting future-based logic in actors into a more actor-y solution but that's because IMO it's easier to reason about multiple actors (and their messages) than composed Futures. My stance isn't one which is universally held, however

**Comment by cjllanwarne** [comment]
@geoffjentry I agree and that was sort of the point of my pushback. Why make all this effort to refactor these retry's into a format which is still kind of horrible and difficult to follow!

**Comment by geoffjentry** [comment]
@cjllanwarne Because not everyone has realized that we're always right about everything ;)
