### ISSUE TITLE
Missing Functionality: WorkflowFailureMode

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1005]
The following workflow options are currently unsupported: 
```
"workflowFailureMode": "ContinueWhilePossible"
```
and 
```
"workflowFailureMode": "NoNewCalls"
```
Ruchi's PR in centaur (PR 69) contains a test for this which should be un-ignored.

**Comment by scottfrazer** [comment]
I believe we call it `workflow_failure_mode` now?

**Comment by gavvvr** [comment]
If i run cromwell with `-Dworkflow-options.workflow-failure-mode="ContinueWhilePossible"` it does not work. Also using `-Dconfig.file=application.conf` does not work. Only **workflow_failure_mode** option in JSON config works.

**Comment by geoffjentry** [comment]
@gavvvr Is this on develop (i.e. 0.21)?

**Comment by gavvvr** [comment]
@geoffjentry latest commit of development branch

**Comment by geoffjentry** [comment]
Thanks! I opened a new ticket #1380 to track
