### ISSUE TITLE
Ctrl-C: Cromwell Doesn't Shut Down

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1007]
Start up a few JES jobs and hit Ctrl-C. The system freezes up but won't shutdown

**Comment by mcovarr** [comment]
So far I haven't been able to reproduce this.  Do you recall more specifically what you were doing when you saw this?

**Comment by cjllanwarne** [comment]
@mcovarr I was running the GotC pipeline x 20. It was scattered quite wide at the time, I believe

**Comment by mcovarr** [comment]
I'm having problems even trying to submit that many workflows concurrently.  Cromwell starts taking a long time to respond to submissions from the Swagger page.

**Comment by mcovarr** [comment]
...but then Control C works instantly.

**Comment by cjllanwarne** [comment]
Unable to recreate this now. Will close and let a subsequent bug report happen if it comes back.
