### ISSUE TITLE
Submitting/Checking Status/Metadata for workflows shouldn't be starved out by running workflows

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1015]
We should have better thread pool separation between the running workflows and all the other REST API endpoints.  Specifically submitting, metadata and status shouldn't be starved out because a lot of workflows are running

**Comment by geoffjentry** [comment]
+💯

**Comment by kcibul** [comment]
@mcovarr -- I think this is part of what you've done addressing #1065.  Can you update here?
