### ISSUE TITLE
Can not run on Windows

### ISSUE THREAD

**Issue by gavvvr** [broadinstitute/cromwell#1016]
Hello.
Is this tool supposed to run on Windows?
i get the following error connected with illegal character in files path:

> [2016-06-17 19:46:12,739] [error] BackendCallExecutionActor [3a480614:testTask]:                                                     Illegal char <:> at index 130:  D:\Cromwell\cromwell-ex                                                    ecutions\test\3a480614-1f47-4101-a869-20b3cd836f38\call-testTask                                                    \D:\Cromwell\other.bam
> java.nio.file.InvalidPathException: Illegal char <:> at index 130:  D:\Cromwell\workflow-engine\cromwell-executions\test\3a480614-1f47-4101-a869-20b3cd836f38\call-testTask\ D:\Cromwell\test.bam
>         at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
>         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
>         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
>         at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
>         at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
>         at java.nio.file.Paths.get(Paths.java:84)
>         at cromwell.engine.backend.local.SharedFileSystem$class.toCallPath$1(Sha                                                    redFileSystem.scala:214)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$15.apply(Shar                                                    edFileSystem.scala:219)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$15.apply(Shar                                                    edFileSystem.scala:219)
>         at cromwell.engine.backend.local.SharedFileSystem$class.adjustFile$1(Sha                                                    redFileSystem.scala:259)
>         at cromwell.engine.backend.local.SharedFileSystem$class.localizeWdlValue                                                    (SharedFileSystem.scala:267)
>         at cromwell.engine.backend.local.LocalBackend.localizeWdlValue(LocalBack                                                    end.scala:94)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$16.apply(Shar                                                    edFileSystem.scala:219)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$16.apply(Shar                                                    edFileSystem.scala:219)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$17.apply(Shar                                                    edFileSystem.scala:221)
>         at cromwell.engine.backend.local.SharedFileSystem$$anonfun$17.apply(Shar                                                    edFileSystem.scala:220)
>         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike                                                    .scala:245)
>         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike                                                    .scala:245)
>         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.                                                    scala:59)
>         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
>         at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
>         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
>         at cromwell.engine.backend.local.SharedFileSystem$class.adjustSharedInpu                                                    tPaths(SharedFileSystem.scala:220)
>         at cromwell.engine.backend.local.LocalBackend.adjustSharedInputPaths(Loc                                                    alBackend.scala:94)
>         at cromwell.engine.backend.local.LocalBackend.adjustInputPaths(LocalBack                                                    end.scala:96)
>         at cromwell.engine.backend.local.LocalBackend.instantiateCommand(LocalBa                                                    ckend.scala:246)
>         at cromwell.engine.backend.BackendCallJobDescriptor.instantiateCommand$l                                                    zycompute(JobDescriptor.scala:52)
>         at cromwell.engine.backend.BackendCallJobDescriptor.instantiateCommand(J                                                    obDescriptor.scala:52)
>         at cromwell.engine.backend.local.LocalBackend$$anonfun$execute$1.apply(L                                                    ocalBackend.scala:115)
>         at cromwell.engine.backend.local.LocalBackend$$anonfun$execute$1.apply(L                                                    ocalBackend.scala:113)
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(                                                    Future.scala:24)
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.sca                                                    la:24)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst                                                    ractDispatcher.scala:397)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool                                                    .java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19                                                    79)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre                                                    ad.java:107)

I tried to use Cygwin, cause it transforms `c:\` into `/cygdrive/c` , but i get the same error.

**Comment by cjllanwarne** [comment]
Reassigning this from Bug to Improvement since AFAIK Cromwell was never originally intended to be Windows compatible

**Comment by cjllanwarne** [comment]
Closing this. I don't foresee it being added in the foreseeable future since, as Jeff said, this was written as a *nix tool.

If running under Windows is a requirement for you, I'd recommend running a virtual machine (virtual box, vmware, ...) and mounting any directories you need into the VM, or perhaps running a Linux box in a hosted environment (we run Cromwell on GCE a lot here at the Broad)
