### ISSUE TITLE
Make Batch Submit API great again

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1017]

**Comment by mcovarr** [comment]
and be sure to document it in the README and Swagger!  😄

**Comment by cjllanwarne** [comment]
Clue: WorkflowBatchSubmitActor.scala

**Comment by kcibul** [comment]
oooh, feels like a mystery adventure now.  Where's shaggy and scooby?

**Comment by cjllanwarne** [comment]
We'd have gotten away without having to do this, if it weren't for those meddling kids!
