### ISSUE TITLE
Bulk query by ID might not return rows for legit IDs

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1021]
The query API is now eventually consistent.  0.19 Cromwell always returned a query result for any legitimate workflow ID, but PBE Cromwell will not if the workflow has not yet been summarized.

This might be "fixed" by making sure Cromwell's clients expectations are properly adjusted.  Alternatively we might think about a more substantial rework of the query and metadata APIs to deal with this and other technical debt we've churned up in this space.

**Comment by mcovarr** [comment]
We discussed this at standup today and wanted to get some feedback from @dvoet before deciding how to proceed.  Currently the query API in PBE Cromwell may lag the engine/raw metadata journal by some amount of time (currently the refresh interval is 2 seconds, plus the time to do the refresh work).  So it's possible that a query soon after a workflow submission will not immediately turn up any results for legitimate workflow IDs.

**Comment by kcibul** [comment]
just talked with @dvoet  -- currently they don't ask for status for at least a minute after launching, and in addition they use the single workflow status API.

**Comment by kcibul** [comment]
...and if there was an error.. they just retry later
