### ISSUE TITLE
Assess/Fix/Implement Ignored Tests in KeyValueServiceActorSpec

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1031]
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

**Comment by Horneth** [comment]
The fate / purpose of the KeyValue service should be discussed first in order to make a decision about its tests.

**Comment by geoffjentry** [comment]
Let's talk after standup. I think we're going to need it - IIRC there's already something incorrectly reading/writing from metadata, and recovery was the use case which informed it in the first place & that's incoming
