### ISSUE TITLE
Assess/Fix/Implement Ignored Tests in WorkflowFailSlowSpec

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1034]
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

**Comment by cjllanwarne** [comment]
Moving to 0.21 to join the WorkflowFailureModes ticket

**Comment by ruchim** [comment]
Depends upon the completion on #1005
