### ISSUE TITLE
Assess/Fix/Implement Ignored Tests in SlickDataAccessSpec

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1040]
The goal here is to look at the tests in the spec, and determine
1. does the test assess something valuable
2. if no, delete it (with an explanation in the PR)
3. if yes, either fix it up so it passes, or reimplement... whatever is more expedient

**Comment by mcovarr** [comment]
These tests are possibly valuable but will depend on having an engine database, so this should really be 0.21 and not 0.20.
