### ISSUE TITLE
Cromwell should retry jobs that fail ( for non-preemptible)

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1042]
We do this for preemptible VMs, when a job fails with certain error codes (13/14 I believe) which indicate that a VM shut down unexpectedly, we retry a certain number of times which is user specified via the WDL task definition

@dvoet has requested this same feature for non-preemptible VMs for FireCloud

**Comment by dvoet** [comment]
we are request that JES detect and terminate VMs that have zombie processes. The associated job should also be retried.

**Comment by cjllanwarne** [comment]
Closing as a duplicate of the newer tickets Jeff just added
