### ISSUE TITLE
Review/Update README/Swagger

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1043]
When PBE is drawing to a close, update the README and Swagger with then-current versions of output from the various endpoints.  Some of this documentation is already very out of date.

**Comment by ruchim** [comment]
@mcovarr is this a PBE Finale ticket potentially?

**Comment by mcovarr** [comment]
If that means what I think it means, yes.  😄

**Comment by kcibul** [comment]
At standup yesterday, it sounded like @scottfrazer was effectively doing this as part of the other documentation ticket.

**Comment by ruchim** [comment]
@kcibul since this is a duplicate, is it okay if we just close this issue?

**Comment by kcibul** [comment]
It's not really a dupe -- one ticket is about the README/swagger and one is
specifically about 0.19->0.20+ upgrade instructions (which could go in the
readme as one option!)

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by ruchim** [comment]
👍 makes sense!
