### ISSUE TITLE
Taskless Workflows

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1063]
These never terminate. They should either be blocked by `MaterializeWorkflowDescriptorActor` (and added to the newly refreshed `MaterializeWorkflowDescriptorActorSpec`)... or else they should be allowed and should terminate properly.

Example:

Foo.wdl

```
workflow foo {
  # No calls
}
```

**Comment by kcibul** [comment]
This shouldn't be a special case.  if this is valid WDL (and I think it is?) then they should be accepted and terminate properly.  If this is invalid WDL, then they should be blocked.

**Comment by kcibul** [comment]
There is a test case for this already that is disabled (MWDActorSpec)

**Comment by cjllanwarne** [comment]
Fixed in 23+
