### ISSUE TITLE
Localization flag is sometimes ignored in the same run of a task

### ISSUE THREAD

**Issue by djhshih** [broadinstitute/cromwell#1072]
I compiled the develop branch (after commit b246001).
(I had previously used the 0.19 release and 0.19_hotfix, but both refused to soft link or hard link.)

When cromwell-0.20-b246001 is invoked with

```
cromwell -jar ~/java/cromwell-0.20-b246001.jar \
  -Dbackend.shared-filesystem.localization.0=soft-link
```

Some of the files are soft linked, while other files are hard-linked in the same run of a task.

The fasta file is soft-linked:
```bash
$ ls -l seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta
lrwxrwxrwx 1 dshih broad 72 Jun 27 10:44 seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta -> /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta*
```

However, the pon file in the same task is hard-linked:
```bash
$ ls -l xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon 
-rw-r--r--+ 3 dshih broad 1020487624 May 10 11:35 xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon

$ ls -i xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon 
14733355 xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon

$ ls -i /xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon 
14733355 /xchip/scarter/dshih/local/opt/gatk4cnv-20160112/pons/ice_female_pd250/create_pon/ice_female_pd250_spark.pon
```

The number of references for this file is 3 (instead of 1), because I ran the workflow twice and both times, the localized file is hard-linked. All 3 files have the same inode number (14733355).

I looked at the log file, but it was not terribly revealing... No error had occurred. No attempt at soft linking was logged. I was able to manually soft link the file in question.

```bash
$ uname -a
Linux cga02 2.6.32-573.26.1.el6.x86_64 #1 SMP Tue Apr 12 01:47:01 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

Both the wdl file and the log file are attached.

[WesCopyNumber.wdl.txt](https://github.com/broadinstitute/cromwell/files/335331/WesCopyNumber.wdl.txt)
[workflow.e9597059-476c-4797-8e8c-fca4382b9ef3.log.txt](https://github.com/broadinstitute/cromwell/files/335332/workflow.e9597059-476c-4797-8e8c-fca4382b9ef3.log.txt)

**Comment by Horneth** [comment]
@djhshih I don't think it fully explains it, but the path to the localization strategies in the config file has changed.
`-Dbackend.shared-filesystem.localization.0=soft-link` won't have any effect.
Each backend now has its own `config` stanza. For local backend that would be 
`-Dbackend.providers.Local.config.filesystems.local.localization.0=soft-link`
Could you try with that and see if you have the same problem ?
I'm still confused as why some of them are soft-linked and some of them aren't. I think logging when a localization strategy fails would also be a good idea.

**Comment by djhshih** [comment]
Sorry. I didn't realize the configuration has changed between 0.19/0.19_hotfix and 0.20.

What happened is that the config flag was ignored (though it would perhaps be preferable to throw an error or at least a warning.) and the cromwell tried each localization strategy until one succeeded, as described in the documentation.

In my run, the files that were hard-linked live on the same storage device.
The files that were soft-linked live on another storage device, presumably because hard-linking failed.

Using the new flag `-Dbackend.providers.Local.config.filesystems.local.localization.0=soft-link` ensures that all files are soft-linked as expected.
