### ISSUE TITLE
Support Local + SGE backends in a single workflow

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1086]
Support a two step workflow where a local backend is used in the first task to generate a random string, and then that string used as an input to a second task running on a different backend (e.g. Google).

**Comment by delocalizer** [comment]
+1; we like to compose WDL workflows using import of many atomic tasks, some of these will be very simple like generating a UUID or calling mkdir, some will be long running computations. Being able to specify the short tasks to run locally and handing the longer ones off to the cluster would be efficient.

**Comment by geoffjentry** [comment]
:+1:  we have a collaborator w/ a strong use case for local + lsf as well, which is basically the same thing here

**Comment by geoffjentry** [comment]
Anyone following this, we have evidence that this already works, at least for some use cases. cc: @delocalizer

**Comment by cjllanwarne** [comment]
This should be working. That should be easy to verify...

Can someone with a working SGE instance double check?

**Comment by kcibul** [comment]
I'll update the issue title... this isn't about SGE per-se, but rather about running local + some other back end in a single workflow.  Google JES is fine for that.

Just to further clarify, this doesn't require being able to schlep files between the two (although it would be great to know if that works!)  but as @delocalizer mentioned, a use case of running something locally that generates a non-file type (e.g. string) that can be passed as input to a task on another backend would be the thing to verify or get working

**Comment by kcibul** [comment]
... but if we want to test SGE... Lee would be a good contact

**Comment by mcovarr** [comment]
There exists a Centaur `local_gcs.test` which creates a file in GCS using the JES backend, then reads it using a GCS-savvy Local backend.  Does that meet the requirements of this ticket?

**Comment by delocalizer** [comment]
This tests as working for me at least with release 24; I can specify "Local" or my custom "PBS" backend in a task `runtime` block and it behaves as expected.

**Comment by katevoss** [comment]
This has been completed, if there are problems feel free to open a new issue.
