### ISSUE TITLE
There are two license files

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/cromwell#1090]
Is that intentional? It's confusing.

**Comment by geoffjentry** [comment]
That's how we were told to license by legal. One is our license, the other is the license for something we include. I'm closing this, but if you can think of a way which you think it'd be more obvious without actually changing the license files, let me know (or submit a PR). My take is that at the moment the README is so long that anything we write on this topic is likely to just be noise no one will see anyways

**Comment by vdauwera** [comment]
Oh ok, thanks for clarifying. I'm writing up a page listing component licenses & got confused re what Cromwell is under.

**Comment by geoffjentry** [comment]
That's the reason for the "Cromwell is open sourced under the BSD 3-Clause license." line right at the top of the README and the BSD badge in between the list of files and the README ... which ties to my point that no matter what we write people won't notice :)

**Comment by vdauwera** [comment]
Ah, oops :D
