### ISSUE TITLE
maximum-polling-interval ignored

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1097]
It don't do nuttin

**Comment by kcibul** [comment]
@geoffjentry can you update the ticket with more info?  Where is this parameter used, and what is the effect of this being ignored?

**Comment by geoffjentry** [comment]
"It don't do nuttin" ain't nuff fer ya? :)

The README claims that this can be used to tweak the maximum time we wait prior to polling JES. However nothing actually uses this value internally, the max value is hardcoded. I discovered this as I was changing the hardcoded value recently and said "this really should be tunable" then discovered that it was intended to be in the first place. 

We could also say that it shouldn't be tunable, in which case the references to this in the README and the hooks in the code reading it from the conf file should be nuked from orbit. It's the only way to be sure.

**Comment by kcibul** [comment]
Thanks.  Let's make this tunable via config as part of this ticket
