### ISSUE TITLE
Release .jar has same name for 0.19 and 0.19.3

### ISSUE THREAD

**Issue by ilovezfs** [broadinstitute/cromwell#1103]
0.19.3:
https://github.com/broadinstitute/cromwell/releases/download/0.19.3/cromwell-0.19.jar

0.19:
https://github.com/broadinstitute/cromwell/releases/download/0.19/cromwell-0.19.jar

I noticed you haven't done a point release before, so I wasn't sure whether the 0.19.jar for 0.19.3 was intentional or a mistake. It tripped up the Homebrew formula because we have `-#{version}` logic in the formula itself, but I can simply update that section if the identical naming was intentional. Or if not, I can leave that section alone if the URL is updated to point to a file named cromwell-0.19.3.jar

Cf. https://github.com/Homebrew/homebrew-core/pull/2511

**Comment by scottfrazer** [comment]
I renamed it to cromwell-0.19.3.jar!

**Comment by ilovezfs** [comment]
@scottfrazer Cool, thanks. I'll remove this hack: https://github.com/Homebrew/homebrew-core/blob/7f064cb409648490c4682d040f8e5252d33103ee/Formula/cromwell.rb#L24
