### ISSUE TITLE
Add Job Store

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1115]
Add a Job Store backed by *filesystem* stuff, which receives the following commands:

```
registerJobComplete(jobKey: JobKey, jobResults: JobResults)
isJobAlreadyCompleted(jobKey: JobKey): JobCompletedYetStatus
notifyWorkflowComplete(workflowId: WorkflowId)
```

with JobCompletedYetStatus being one of:

```
case class JobCompletedAlready(jobResults: JobResults) extends JobCompletedYetStatus
case object JobNotCompletedYet extends JobCompletedYetStatus
```

`registerJobComplete` adds to the database.
`notifyWorkflowComplete` removes all appropriate jobs from the database

(all class names given above are **not** final!)

**Comment by ruchim** [comment]
@mcovarr  from a quick glance at Chris's branch [cjl_job_store_writing] it seems like these things are already added, so if this Acceptance Criteria is already rolled into the same branch you'll be looking at, maybe we can close this ticket?

**Comment by mcovarr** [comment]
That branch is explicitly not writing to the database so I don't see it as satisfying this ticket.  From the PR:

```
A work-in-progress Job Store writer which skirts the problem of databases by not actually ever using one. Instead, every Job has a known filesystem location and we just write to and (not yet) read back from disk.
```

**Comment by geoffjentry** [comment]
Technically a file based storage scheme *is* a database

**Comment by mcovarr** [comment]
A great example of "technically right" not being the best kind of right.  😛

**Comment by geoffjentry** [comment]
I was still technically out $20

**Comment by cjllanwarne** [comment]
@geoffjentry @mcovarr  Made it good with the magic of post-facto acceptance criterea editing. Also added #1172 to make this use a real database
