### ISSUE TITLE
Allow for metadata on outputs and workflow level inputs

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1131]
Chet asked that we also include parameter_metadata capabilities to output parameters (task & workflow) as well as workflow level input.

It is possible that the answer here is to change how the whole system works, but that's a question best handled at implementation time.

**Comment by cbirger** [comment]
The motivation for this is that I would like FireCloud/GAWB method configurations to include brief descriptions of declared input and output parameters.  It would be great if these description fields could be initialized by metadata contained within a workflow's WDL file.  I was thinking we could leverage the parameter_meta sections, but currently that section is only supported in the task definition block, and only for input parameters.  I don't, however, want to request a specific solution....the use and expansion of the parameter_meta section may not be the answer.  My primary goal is to be able to initialize the input/output parameter descriptions with strings drawn from the WDL.

**Comment by cjllanwarne** [comment]
You can now supply `meta` blocks at a workflow level, and those can contain outputs as well as inputs so I think I can safely close this.
