### ISSUE TITLE
JES backend: Clearly indicate if files are missing when a task runs

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1137]
As a user, like @yfarjoun, if I run a workflow against the JES backend and an input file for a task doesn't exist (e.g. gs://foo/bar/baz.txt does not exist).  I would like to get back a clear error message that this is why the task failed.  This is important because currently  "the error is so cryptic one cannot tell
that a file is causing the problem, nor which file it is, even if one had an inkling that it's a missing file problem. so [you] have to resort to divide and conquer in order to identify the missing file...and that's a pain."

**Comment by kcibul** [comment]
@yfarjoun -- can you give a little more context on this?  These jobs will just fail upon localization right?  or does something else happen that you want to avoid?

Completing this sentence "this is important because ..." would be a good formula!

**Comment by geoffjentry** [comment]
He wanted a fail fast behavior, so if a job deep in a workflow was bound to fail he'd know right away

**Comment by kcibul** [comment]
So is this verify all input files to a workflow exist?  or to each call as
they happen?

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by geoffjentry** [comment]
The former. He was looking for a backend-aware validation type behavior

**Comment by yfarjoun** [comment]
Actually, the main problem is that the error is so cryptic one cannot tell
that a file is causing the problem, nor which file it is, even if one had
an inkling that it's a missing file problem. so I have to resort to divide
and conquer in order to identify the missing file...and that's a pain.

**Comment by geoffjentry** [comment]
IIRC the error in question was passing the 403 Forbidden back from Google

**Comment by yfarjoun** [comment]
Indeed. but the problem was that we couldn't tell that a file was missing
and indeed which file it was.

**Comment by yfarjoun** [comment]
...so if the 403 comes back with that information, that's great!

**Comment by geoffjentry** [comment]
@yfarjoun I know, that was info for a potential future implementer, not contesting anything you said :)

**Comment by kcibul** [comment]
This is great -- I'm going to retitle this to describe the underlying problem

**Comment by cjllanwarne** [comment]
Closing since the error message now contains (a) that a file was missing (b) the appropriate file name
