### ISSUE TITLE
Reflect Backend Abort Status more accurately

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1139]
As FireCloud ( @cbirger )  , I often abort workflows.  Although JES currently makes a best effort to abort calls, sometimes those calls fail to abort.  I would like to know through the cromwell call/workflow status the difference between "definitely aborted" and "unknown abort status".

The reason this is important is that if I know the status is "unknown" I know that I might be at risk for being billed for machines I don't want and should take further action.

</end of PO comment>

Technically this might require a little research and specifically work on JES.  Ideally:
1. We change our overall workflow status to aborting
2. When we cancel a JES operation, the status of that operation will reflect reality.
3. We can poll that operation until it reaches a terminal state (e.g. cancelled).  This may actually just be for us to keep running the workflow like normal and just add canceled to the list of terminal states).
4. Once all tasks are in a terminal state, the workflow status is Aborted

Question will be... if JES fails to terminate a job, should we change it's status to something like 'LOST' or 'UNKNOWN' after N minutes, or should we wait indefinitely.  Since it's a best effort cancellation in JES we should handle this case

**Comment by katevoss** [comment]
@kcibul From what I understand, it is still a frequent problem that P.API does not abort workflows even though Cromwell asked. 

@geoffjentry do you have an idea about the effort involved to make this fix? 

@abaumann Do we have any data (from FC) with how often this is happening?

**Comment by geoffjentry** [comment]
This doc predates that "we should fix aborts" google doc and is effectively a subset of that. I say effectively in that the specifics of what this ticket are asking for might be different from that doc, but that doc should be the authoritative one of the two.

**Comment by katevoss** [comment]
In that case I'm closing this in favor of the [Google Doc](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit).
