### ISSUE TITLE
Deforms the path to JNI lib

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/cromwell#1140]
Cromwell deforms the path to JNI library while running wdl workflow.

Printout of the **cromwell-executions/case_gatk_acnv_workflow/2ed49a7f-a6bb-4fac-8516-406eb6416268/call-TumorNormalizeSomaticReadCounts/script** file:
`... -Djava.library.path=/dsde/working/asmirnov/TestCromwell/cromwell-executions/case_gatk_acnv_workflow/2ed49a7f-a6bb-4fac-8516-406eb6416268/call-TumorNormalizeSomaticReadCounts/broad/software/free/Linux/redhat_6_x86_64/pkgs/hdfview_2.9/HDFView/lib/linux ... `

Path that is specified in the json file:
`"case_gatk_acnv_workflow.jni_lib": "/broad/software/free/Linux/redhat_6_x86_64/pkgs/hdfview_2.9/HDFView/lib/linux/`

JSON file path: **/dsde/working/asmirnov/TestCromwell/downsampled-bams.json**
Cromwell output directory: **/dsde/working/asmirnov/TestCromwell/cromwell-executions/case_gatk_acnv_workflow/2ed49a7f-a6bb-4fac-8516-406eb6416268/call-TumorNormalizeSomaticReadCounts/**

**Comment by Horneth** [comment]
Cromwell localizes every input file in the call directory when the task gets run. You can specify how it gets localized (soft-link, hard-link, copy) in the [configuration file](https://github.com/broadinstitute/cromwell/blob/develop/core/src/main/resources/application.conf#L148)

Does this make your workflow / call fail ?

**Comment by asmirnov239** [comment]
Thank you!
The issue was that wdl workflow parameter was of the type File, which worked for the previous version of Cromwell. It worked after I changed the type to String, because it had to represent a folder.
