### ISSUE TITLE
Untag "PostMVP" tests so we can collect metrics on how many ignored, etc.

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1149]
This will be a precursor to then having tickets that un-ignore those tests (either by fixing or removing)

**Comment by katevoss** [comment]
@geoffjentry is this still a useful ticket? Are there still PostMVP tests or have they been cleaned up in the last year?

**Comment by geoffjentry** [comment]
@katevoss I've said that it is not useful for quite some time now. Every time I bring it up other people disagree with removing it.

Yes, there are still ignored tests but I'm using the model of "if you haven't touched it by now it's not useful and you're never going to come back to it". 

I'd suggest we set a TTL for this ticket and anyone who feels strongly about these tests can effort to enable them between now and then.

**Comment by katevoss** [comment]
It sounds like this ticket does not hold much value any longer.

@kcibul with your okay, I will close it. If you disagree, please explain more about what needs to be done and what value it provides.

**Comment by mcovarr** [comment]
If we don't care about those tests then IMHO this ticket should become "delete all that PostMVP stuff you don't care about".

**Comment by geoffjentry** [comment]
My long held stance is that if anyone cared about those tests they'd have unignored them by now. 

Imo the options are "someone who cares fix this immediately" or what @mcovarr said

**Comment by mcovarr** [comment]
Done.
