### ISSUE TITLE
Call caching kicking in when it shouldn't

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1150]
From @yfarjoun 

> I've been playing around with some wdl on the methods cromwell that has caching turned on. I have some results I do not understand. I modified the bwa step in a small way for input that has already run all the way to HaplotypeCaller. Re-running that wdl shows that the upstream steps are fast (as expected), the BWA step is re-done (again, as expected), but the downstream steps have been used from cache...this seems wrong to me, after all, if the BWA has been re-run, all the downstream steps need to be re-run as well...could you explain what's going on?

For example, the "PairedEndSingleSampleWorkflow.MergeBamAlignment" step should have been recomputed as it is downstream of the BWA step.

Here's a [timing diagram](https://cromwell.dsde-
methods.broadinstitute.org/api/workflows/v1/d69172b2-3b5d-44b3-aaec-5ed12dbb771f/timing
) and [metadata](https://cromwell.dsde-
methods.broadinstitute.org/api/workflows/v1/d69172b2-3b5d-44b3-aaec-5ed12dbb771f/metadata
): 

metadata also attached here.

Although we don't have call caching in 0.20+ we should understand this problem (or clarify why it's not a problem) so that we don't replicate the bug (if that's what it is)

**Comment by kcibul** [comment]
[yossi.metadata.txt](https://github.com/broadinstitute/cromwell/files/359657/yossi.metadata.txt)

**Comment by yfarjoun** [comment]
your links aren't working for me:

https://cromwell.dsde-methods.broadinstitute.org/api/workflows/v1/d69172b2-3b5d-44b3-aaec-5ed12dbb771f/timing

**Comment by yfarjoun** [comment]
Jeff explained in person, I no longer think that it's a bug the task I
changed didn't change the main output and thus, since the file contents are
compared via md5, cromwell did the right thing!!

Thanks!!

**Comment by ruchim** [comment]
@kcibul I'm going to close this ticket based on Yossi's response. Thanks @geoffjentry!
