### ISSUE TITLE
Monitoring script doesn't always appear to run

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#1158]
Running 3step workflow on JES with a workflow options file that looks like this

```json
{
   "monitoring_script": "gs://sfrazer-dev/monitor.sh"
}
```

the `monitor.sh` script contains:

```bash
echo this
echo is
echo a
echo test
```

It seems that for my three invocations of this workflow, they all had the correct data in `monitoring.log` for the `ps` sub-command, but not the other two commands.

**Comment by Horneth** [comment]
What are the other 2 commands ? It's a known issue that if the commands are very fast to execute, the monitoring.log is not flushed before it's delocalized and the VM shuts down, and it ends up empty.

**Comment by scottfrazer** [comment]
they're `grep` and `wc` commands.  I'll update the documentation accordingly.

**Comment by kcibul** [comment]
closing -- sounds like this is a documentation update (which is being handled).  Please re-open if there is still a bug here
