### ISSUE TITLE
Remove callbacks from existence check

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1165]

**Comment by cjllanwarne** [comment]
@mcovarr this is a little... tough to interpret... any more details?

**Comment by mcovarr** [comment]
erm yeah sorry about that 😦 

Currently the `withRecognizedWorkflowId` logic in `CromwellApiService` is using a callback to communicate with the service registry actor.  This ticket was meant to suggest that this communication be kept actor-based instead.

**Comment by geoffjentry** [comment]
While it almost sounds joke worthy for me to suggest this I'd ask that this one not be the first bit of crud to be fixed up. Now that I have an idea of how an akka http world would look like it's quite likely that all of that stuff will change a lot so the problem might just akka itself away if I ever complete that project

**Comment by cjllanwarne** [comment]
Closing since this is probably going to be better addressed in the acca stream shake-up

**Comment by geoffjentry** [comment]
akka http, not akka stream but :+1:
