### ISSUE TITLE
continueOnReturnCode doesn't follow naming convention

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#1167]
Cromwell still responds to `continueOnReturnCode` in workflow options whereas everything else is named with underscores, (should be `continue_on_return_code`)

**Comment by mcovarr** [comment]
why did we not fix this??

**Comment by geoffjentry** [comment]
One could make the argument that it'd hose people who don't want to update their options files, but I know that's not really the answer :'(

**Comment by cjllanwarne** [comment]
I'm gonna close this. There's no reason to disrupt this before we undergo the big-scary runtime-attributes-refactor
