### ISSUE TITLE
Handling optional workflow input

### ISSUE THREAD

**Issue by gavvvr** [broadinstitute/cromwell#1176]
Hello. Here is the simple example of workflow with optional input: 

```
workflow wf {
    String? inn
    call tsk_grep { input: input_381012639=inn }
    }

task tsk_grep {
    String? input_381012639
    command { ps aux | grep j${"a" + input_381012639}
    }
}
```
When i do not specify any input for workflow(json file below):
```
{
}
```
i get an the error:
`wdl4s.WdlExpressionException: Could not resolve inn as a scatter variable, namespace, call, or declaration`

But when my workflow looks like this:
```
workflow wf {
    call tsk_grep
    }

task tsk_grep {
    String? input_381012639
    command { ps aux | grep j${"a" + input_381012639}
    }
}
```
Cromwell works as expected executing `ps aux | grep j`.
Is this a bug or i can only use optional variables inside of **task scope**?

**Comment by geoffjentry** [comment]
Hi @gavvvr - 

I was just asked by our support team to redirect questions like this to our support forum:
http://gatkforums.broadinstitute.org/wdl/

Could you try posting this over there? I'll also let them know that this is here. 

Thanks!

**Comment by gavvvr** [comment]
Posted this question on forum

**Comment by geoffjentry** [comment]
@gavvvr Thanks! I let them know yesterday so they should be looking for it
