### ISSUE TITLE
Bug when calling read_objects

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1179]
See user question at: http://gatkforums.broadinstitute.org/wdl/discussion/8015/usage-of-wdl-objects-and-the-read-objects-function#latest

When the user calls read_objects and then correctly (as per the spec) tries to access the value an exception occurs.

**Comment by mcovarr** [comment]
looks like this might be another instance of #615

**Comment by mcovarr** [comment]
Not a dupe of #615 at all, and fixed in 23/24.
