### ISSUE TITLE
Convert Future[Option[_]]s to use a monad transformer

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1212]

**Comment by mcovarr** [comment]
Where are you thinking to apply this?

**Comment by geoffjentry** [comment]
Wherever we have Future[Option[]]. The thought occurred as I was looking at PR full of them

**Comment by mcovarr** [comment]
There might be some spots where it wouldn't make sense if the abstract API is `Future[A]`, but yeah we might benefit from some `OptionT` up in here.

**Comment by geoffjentry** [comment]
Related: The title of this talk always makes me laugh: https://www.youtube.com/watch?v=hGMndafDcc8 (it's really an intro to monad transformers, but ...)
