### ISSUE TITLE
Standardize column names in the various Cromwell tables

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1219]
We're putting in a lot of tables with conceptually identical columns but arbitrarily different names. The purpose of this ticket is to standardize our choices.

**Comment by ruchim** [comment]
@mcovarr So there seems to be some Liquibase issues in terms of synchronizing the column names. If we're going to do this as a part of 0.21, I might have @kshakir refine this ticket in terms of what steps we have to take to successfully change column names without disrupting users too much.

**Comment by kshakir** [comment]
Not sure if you're referring to my "rewrite" of a liquibase change log, but that was already merged to develop.

Besides that fixed issue, there are further technical issues that I'm aware of blocking us from changing column names. Just use [`<renameColumn`](http://www.liquibase.org/documentation/changes/rename_column.html), like we have in a few cases in the changelog history already.
