### ISSUE TITLE
Local backend doesn't write STDOUT/STDERR while process is running

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#1220]
See: https://github.com/broadinstitute/cromwell/blob/40e9b99b9d545e4bf67483af17db94c7bd33421d/supportedBackends/local/src/main/scala/cromwell/backend/impl/local/LocalJobExecutionActor.scala#L185

The subprocess must finish before the stdout/stderr streams are written.  Lee wanted to be able to see stdout/stderr while a process runs to diagnose long-running processes.

**Comment by katevoss** [comment]
This is no longer the case and it is fixed.
