### ISSUE TITLE
Sweep and triage/fix PBE TODOs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1221]
These should all be TODONE by the end of 0.21

**Comment by kcibul** [comment]
update title to include triage.  Just because someone put in a PBE TODO doesn't mean it absolutely has to be done.  Use good judgement ;)

**Comment by kcibul** [comment]
You can find all mentions of PBE by running the following from the root

`find . -name "*.scala" -exec grep -H PBE {} \;`

**Comment by kcibul** [comment]
I find 18 occurrences

`./backend/src/main/scala/cromwell/backend/ExecutionHash.scala:  // TODO: PBE: ideally hashes should be deterministic
./backend/src/test/scala/cromwell/backend/caching/CachingConfigSpec.scala:// TODO PBE Adapt to how new caching works, but the test logic should not need much change
./database/src/test/scala/cromwell/database/slick/SlickDatabaseSpec.scala:        // TODO PBE get rid of this after the migration of #789 has run.
./engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala:      // TODO PBE Is this the right place for startTime ?
./engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala:      // TODO: PBE: some of the x-es have an actually execution & output stores.
./engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala:      // TODO PBE Restart: to be verified after restart is implemented but these WorkflowSucceededResponse/WorkflowFailedResponse seem useless
./engine/src/main/scala/cromwell/webservice/CromwellApiService.scala:          // TODO: PBE: Certainly want to do something for this! But probably not to the WMA
./engine/src/test/scala/cromwell/engine/workflow/MaterializeWorkflowDescriptorActorSpec.scala:    // TODO PBE: this should be done by MWDA (ticket #1076)
./engine/src/test/scala/cromwell/engine/workflow/MaterializeWorkflowDescriptorActorSpec.scala:    // TODO: PBE: Re-enable (ticket #1063)
./engine/src/test/scala/cromwell/engine/WorkflowManagerActorSpec.scala:    // TODO PBE: Restart workflows tests: re-add (but somewhere else?) in 0.21
./project/Settings.scala:    //"-deprecation", // TODO: PBE: Re-enable deprecation warnings
./services/src/main/scala/cromwell/services/metadata/MetadataService.scala:  /* TODO: PBE: No MetadataServiceActor.props until circular dependencies fixed.
./supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala:      // TODO: PBE: Trace callers of "new CallContext()". Seems to be multiple places in JES, etc. For now:
./supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala:      // TODO: PBE: The REST endpoint toggles this value... how/where? Meanwhile, we read it decide to use the cache...
./supportedBackends/jes/src/test/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActorSpec.scala:    // TODO: PBE: This spec may run faster by going back to mocks? Also, building the actor ref is copy/pasted a lot
./supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala:    // TODO: PBE: The REST endpoint toggles this value... how/where? Meanwhile, we read it decide to use the cache...
./supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemJobExecutionActorSpec.scala:    // TODO: PBE: This test needs work. If the abort fires to quickly, it causes a race condition in waitAndPostProcess.
./supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemJobExecutionActorSpec.scala:    // TODO: PBE: abort doesn't actually seem to abort. It runs the full 10 seconsds, then returns the response.`

**Comment by ruchim** [comment]
@geoffjentry once you confirm that the new tickets have been made, we can close this ticket!
