### ISSUE TITLE
Cromwell .20+ workflow wdl, inputs json, options file not stored in database

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1238]
These inputs used to live in the WORKFLOW_EXECUTION_AUX table in .19.  We use this table as kind of a back pocket sanity check if our workflow results are not making sense.  Is it possible to get this table revived in .20?

**Comment by geoffjentry** [comment]
Dupe of #1239 - we will be supporting this via the metadata endpoint
