### ISSUE TITLE
WorkflowStore failures: Make sure WorkflowStore entry is removed before JobStore entry

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1247]

**Comment by cjllanwarne** [comment]
Follow on from #1191

**Comment by cjllanwarne** [comment]
cf: `WorkflowManagerActor`:
```
[190]   jobStoreActor ! RegisterWorkflowCompleted(workflowId)
...
[196]      workflowStore ! WorkflowStoreActor.RemoveWorkflow(workflowId)
```
Ideally these would be performed in order rather than simultaneously.

**Comment by mcovarr** [comment]
Just to clarify, I think the motivation here was to make sure the workflow that went terminal does not get recovered and a job that already ran once re-run.
