### ISSUE TITLE
Docker Hub appears to have removed the v1 enpoint

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1251]
The `SprayDockerRegistryApiClientSpec` check for the v1 docker repositories on the hub.docker.com registry are all returning 404. Tried switching the repository searched on the registry from [`ubuntu`](https://hub.docker.com/r/_/ubuntu/) to [`registry`](https://hub.docker.com/r/_/registry/), but that only worked for a day or two.

Either the handshake for accessing the v1 hub.docker.com needs to be updated, or perhaps the test needs an edit / removal. Perhaps we may also decide to only support v2 registries.

`sbt engine/alltests:test-only *SprayDockerRegistryApiClient` will run the tests including "resolve docker hub image v1 layer ids", that may be marked with "ignore" by the time this ticket is addressed.

Haven't checked GCR (or artifactory, quay, etc.) recently, but perhaps most registries are all using v2 for looking up repositories and we may remove v1 support.

NOTE: Docker Hub, even though it is technically a _docker registry_, did NOT implement the official Docker Registry API for a long time.
- http://dev.hpcloud.com/blog/2016/wrangling-different-docker-apis 

See also:
- https://docs.docker.com/registry/spec/api/
- https://github.com/docker/distribution
- https://docs.docker.com/v1.7/docker/reference/api/docker-io_api/

**Comment by cjllanwarne** [comment]
I believe this was only used for hashes, which are no longer part of Cromwells v21+
