### ISSUE TITLE
Port wdl IntelliJ plugin to pycharm

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1264]
The plugin is really nice when developing in the IDEs.  Unfortunately, pycharm is not supported and evaluation workflows will probably be majority python scripts.

**Comment by cjllanwarne** [comment]
According to the [jetbrains](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html) website, we might just need to add a dependency and hey-presto, it'll be picked up for all other jetbrains IDEs

**Comment by danbills** [comment]
Issue moved to [broadinstitute/winstanley #7](https://github.com/broadinstitute/winstanley/issues/7) via [**ZenHub**](https://www.zenhub.com/)
