### ISSUE TITLE
Centaur, "run a wdl" tests, unit tests, and more

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1269]
Note to @kcibul - this is just a placeholder for now, not a would-be punching bag like "log smarter, not harder" :)

As I'm rewriting CromwellTestKitSpec and thus going through all of the variations of the "run a wdl and check outputs/logs/etc" tests in the codebase, I'm realizing that the extent of overlap with Centaur is even larger than I'd previously thought. We need to bring sanity to this ...
- On one hand, all of these "run a full workflow" type tests belong in Centaur. If not, define what Centaur is for, if anything
- On the other hand, having rapid feedback via sbt test is useful
  - And people find it annoying to write proper "unit" tests on behavior
    - I'd argue this is a code smell, our business logic is too wrapped up with the actor-y stuff. But that's part of what we need to decide

At the very least, we need to hash out WTF _is_ a "unit test" (i.e. running by 'sbt test'), what belongs in Centaur, etc.

**Comment by geoffjentry** [comment]
For now in the code I'm working on, I'm marking tests which I find highly suspect w/ a "FLAGGED" comment w/ some explanation

**Comment by katevoss** [comment]
This is a part of a successful cultural change. Good job team.
