### ISSUE TITLE
JES backend blithely assumes non-empty BackendInitializationData on finalization

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1272]
There seem to be intermittent Centaur failures on `invalid_runtime_attributes`.  I investigated this for a while and found the following:

`WorkflowActor` will always try to run finalization, even if initialization fails.  And if initialization fails there will be no initialization data, which means a `.get` on the optional initialization data will throw.  Unfortunately this is exactly what `toJes` in `JesBackendLifecycleActorFactory` is doing:

```scala
def toJes = genericInitializationData collectFirst { case d: JesBackendInitializationData => d } get
```

My guess is that this doesn't fail 100% of the time because there's already failure metadata generated (intentionally), and there's a race condition as to which failure event shows up first.  If the intentional failure is generated first the test would pass.

**Comment by kcibul** [comment]
The error you see in centaur looks like

> Metadata mismatch for failures.0.message - expected: "Task invalid_runtime_attributes has an invalid runtime attribute continueOnReturnCode = \"oops\"" but got: "None.get"
