### ISSUE TITLE
Turn on -Ywarn-value-discard

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1282]

**Comment by mcovarr** [comment]
See discussion at #1277

**Comment by geoffjentry** [comment]
Apropos: http://blog.threatstack.com/useful-scalac-options-for-better-scala-development-part-1

Although as @mcovarr pointed out, IntelliJ does a good job of flagging this stuff

**Comment by geoffjentry** [comment]
Also:
https://tpolecat.github.io/2014/04/11/scalac-flags.html

The first link I posted covers most of the ones you usually see ppl advocating for though
