### ISSUE TITLE
Are there plans to support AWS or Azure?

### ISSUE THREAD

**Issue by dinvlad** [broadinstitute/cromwell#1288]
Is the Docker back-end relying on Kubernetes?

In that case, I could see a reasonable path towards running it more universally, i.e. independent of the cloud provider.

Of course, we could always use a SGE etc. but would be great to get the benefits of running Docker natively.

**Comment by geoffjentry** [comment]
Hi @dinvlad ...

- The "Docker" backend referenced in application.conf is just using straight docker on the host machine. There's also "JES" backend which is using the google genomics pipelines API, which is effectively docker-as-a-service
- There are indeed plans to support both AWS and Azure. Some (probably crude at first) support for one of the two is expected within a couple of months. Over the course of then ext few quarters we expect to support both as well as other cloud vendors as well

In terms of how they'd be done, the answer is It Depends. There's the budding [GA4GH Task Execution API](https://github.com/ga4gh/task-execution-schemas) which was heavily inspired by the google genomics pipeline API. Our hope is to see other cloud vendors support this API, which would make our lives easier. Assuming that doens't happen, we've experimented a bit with Azure, and the remote docker approach has made the most sense. The actual outcome is not set in stone at the moment.

Does this answer your questions?

**Comment by dinvlad** [comment]
Thank you!

A related question is - could the existing APIs be used to make custom implementations of "task call"?
In particular, AWS ECS offers a very simple way to create custom task schedulers, which could process an API call with relative ease. One could then schedule a task on ECS instead of JES based on that API call.

**Comment by geoffjentry** [comment]
@dinvlad I'm not sure what you're asking. Which existing APIs?

**Comment by dinvlad** [comment]
@geoffjentry I think what I was looking for is defined in the Scala interfaces for backends. I.e. I could create a custom backend to support AWS by implementing those (so it wouldn't be a web API, just an application PI).

**Comment by geoffjentry** [comment]
@dinvlad Yeah, from that perspective it's absolutely possible to roll your own

**Comment by kcibul** [comment]
Agreed with everything here... just as a heads up that we're looking at building out an AWS ECS-based backend potentially in the very near future

**Comment by dinvlad** [comment]
Great! Looking forward to test early builds.

**Comment by EvanTheB** [comment]
Not sure I should revive this dead thread. What is the current status of MS Azure or other Kubernetes backend support?

**Comment by geoffjentry** [comment]
@EvanTheB Without going too far into the details we do hope to see Azure support in the coming quarter or so.

Regarding k8s, you might want to look at the work on the [TESK backend](https://github.com/broadinstitute/cromwell/pull/4008) which supports ELIXIR's [TESK](https://github.com/EMBL-EBI-TSI/TESK) project. It's still early days there (e.g. you are limited to using `FTP` based file transfer, which introduces a host of issues) but I'm sure they'd love more people helping them to move that project towards usability

**Comment by EvanTheB** [comment]
Thanks geoff, I will check those out

**Comment by MattMcL4475** [comment]
Hi everyone, Cromwell on Azure is now available here:

https://github.com/microsoft/CromwellOnAzure

Please let me know if you have any questions or issues.

Thank you!
