### ISSUE TITLE
Add GA4GH Task Execution backend

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1294]
The [GA4GH Task Execution API](https://github.com/ga4gh/task-execution-schemas) is an attempt to standardize on a JES-like API which can then be supported by other vendors. Cromwell should provide a backend to support this API:
- We already support JES, and due to the similarities in API it should be an easy conversion
- Having Cromwell out of the box support this API would provide greater leverage when encouraging cloud vendors to implement it
- Having a large production engine support this API provides more gravitas to the API in the community
- The Broad supporting a GA4GH API provides happiness good cheer in the community

This will require coordinating with @kellrott for his reference implementation of the API

**Comment by geoffjentry** [comment]
@kcibul If possible this should happen sooner than later. I don't think it'd be a huge effort. I'll probably try to poke at it myself on the side as time allows

**Comment by kcibul** [comment]
What's the state of backends that support this API?  Is the RI complete/usable?

**Comment by geoffjentry** [comment]
There's an RI in progress. The hope is to have the whole thing (this interconnect plus perhaps more) in place by the GA4GH meeting in October

**Comment by geoffjentry** [comment]
Although now that I think about the transfer from JES isn't as obvious as I was picturing. While it's pretty close to the same API it's actually totally difference as we're using Google's java based libraries and this would need to be hand rolled.
