### ISSUE TITLE
Clean up Centaur-in-Travis build so someone other than Jeff can do it

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1296]

**Comment by geoffjentry** [comment]
Oops, I forgot about this.

The tricky part is defining *where* the stuff lives. Private dir on broad NFS, private repo, confluence, etc. There's precedence for all of the above.

**Comment by cjllanwarne** [comment]
Closing presumed fixed

**Comment by geoffjentry** [comment]
It is not, it just came up today actually

**Comment by mcovarr** [comment]
The title of the ticket is kind of wrong, it should instead say something like "pull the Centaur Docker from a Broad Docker Hub repo rather than out of Jeff's repo".

**Comment by geoffjentry** [comment]
@mcovarr That's the least of the problem here. You literally can't recreate the travis stuff on your own at the moment.

**Comment by mcovarr** [comment]
💩

**Comment by katevoss** [comment]
Let's resurrect this!

**Comment by geoffjentry** [comment]
As I commented above, the tricky part is determining where to put this stuff such that it a) makes sense and b) people will remember it is there. I don't really care, I lean towards a private repo, but the real bottleneck at the time (as I remember asking in person as well) was getting people to opine, and no one did.

**Comment by katevoss** [comment]
Hey team (@mcovarr @cjllanwarne @kshakir @danbills), who wants to opine?

**Comment by kcibul** [comment]
Could be that @davidbernick has something to offer here for config/secrets management

**Comment by geoffjentry** [comment]
Which reminds me that @kshakir mentioned vault-ifying this, except that the original & unencrypted files are only on the laptop in question

**Comment by davidbernick** [comment]
I have no background in this situation and the issue isn't helping. Talk voices tomorrow.
