### ISSUE TITLE
Review WDL SPEC for accuracy

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1300]
@geoffjentry has found a few inconsistencies in the spec (please add here), and there may be others lurking.  Let's give it a once over

**Comment by katevoss** [comment]
@geoffjentry Could you give me write permissions to the Cromwell repo so that I can assign myself to this ticket?

**Comment by geoffjentry** [comment]
Done

**Comment by katevoss** [comment]
For WDL features that @kshakir marked as "?" on the [spreadsheet](https://docs.google.com/spreadsheets/d/1phWdti3sVNuthFmbIe8bSwyEuEb7r3EbFMxWzG2tgX4/edit#gid=0), I didn't mark as Cromwell supported.

**Comment by katevoss** [comment]
I made two pull requests, [Cromwell](https://github.com/broadinstitute/cromwell/pull/1733) and [WDL](https://github.com/broadinstitute/wdl/pull/76), they are ready for review.

**Comment by katevoss** [comment]
Both PR's are squashed and merged, closing this issue.
