### ISSUE TITLE
Docker image hash field too small

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1301]
@leetl1220 is seeing an issue on 0.19 with a large Docker hash overflowing the DOCKER_IMAGE_HASH.  Expanding from 100 chars to 255 gets him around the problem.

**Comment by kcibul** [comment]
can we confirm that this is not a problem on 0.20+?

**Comment by mcovarr** [comment]
`HASH_VALUE` in `CALL_CACHING_HASH` is `VARCHAR(255)`, so we shouldn't have this particular problem.  But given that the Docker hashes we generate are functions of Docker image names and those seem to have the potential to be very long, we might want to think about an even larger field.

**Comment by LeeTL1220** [comment]
+1 for 1024

**Comment by LeeTL1220** [comment]
We're getting into automatic docker tag generation, so I could see getting
beyond 255.

**Comment by cjllanwarne** [comment]
This is handled differently now. We hash the runtime attribute `docker` value into a fixed-length MD5 string
