### ISSUE TITLE
Spaces and braces in file names

### ISSUE THREAD

**Issue by gavvvr** [broadinstitute/cromwell#1306]
If you have spaces or braces or other symbols which should be escaped in input file names, bash will be sad about this:

> /bin/bash: line 6: syntax error near unexpected token `('

Example input:
{
  "elc.input": "/home/vagrant/example (1).file"
}

because in resulting bash file it will be transformed into:

> /home/vagrant/cromwell/cromwell-executions/elc/5646fba9-3bdc-4c63-aeba-16adf80ae7d2/call-tsk_ELC_/home/vagrant/example (1).file

I think Cromwell should just put paths between single quotation marks.

**Comment by gavvvr** [comment]
I tried to put path between single quotes in json like this:
> key: "'/home/file (2).txt'"

but it did not work because when cromwell makes links, it creates folder with the name: '

I also tried double quites like this:
> key: "\"/home/file (2).txt\""

and it creates folder called: "

I tried to escape symbols in JSON:
>key: "/home/file\ (\2\).txt"

but cromwell creates symlinks with backslashes in its name: `file\ \(1\)` and bash says such files nor found ...

**Comment by gavvvr** [comment]
Managed to resolve this surrounding reference to file in WDL with single quotes:
> INPUT='${input_938281470}'

**Comment by cjllanwarne** [comment]
Great! I'll close this ticket.

**Comment by jason-weirather** [comment]
I have a similar issue to this one, but I don't think OP's solution is a solution.  Just using the hello-world example:

```{wdl}
task hello {
  String name

  command {
    echo 'Hello ${name}!'
  }
  output {
    File response = stdout()
  }
}

workflow test {
  call hello
}
```

with input
```{json}
{
  "test.hello.name": "World"
}
```
I run `$ cromwell run hello.wdl hello.json hello.out`

I get the error message:

> /Users/jasonweirather/Dropbox (Partners HealthCare)/projects/2017_08_FIRECLOUD/cromwell-executions/test/12ed39b6-cf8f-4ea1-a965-193cd89f99e9/call-hello/execution/stderr.background
-bash: syntax error near unexpected token `('

This was done on Mac OS X 10.12.6 in the bash terminal.
Version of cromwell is `cromwell: 28-5fd2237-SNAP`

**Comment by MrCreosote** [comment]
This won't work if there's a single quote in the string, unfortunately.
