### ISSUE TITLE
Change Backend determination to first be workflow option, then default

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1312]
Current scheme:
- If a workflow option is specified, use that
- If a runtime attribute is specified, use that
- If neither are specified, use the default backend (silently, without error)

There are a few things wrong with this.
- If a user specifies a particular backend we should _not_ be silently giving them some other backend. IMO we shouldn't be giving them another backend period.
- The order of workflow option & runtime attribute makes sense in a single backend workflow but in a multi-backend workflow (which apparently _does_ work, at least in some cases) it's wrong. I think the best thing would be to expand workflow option to allow per-call backend specification or something like that.

**Comment by katevoss** [comment]
@geoffjentry can you explain more about the use cases? Is this still the case that it's much yuck?

**Comment by geoffjentry** [comment]
This is indeed still much yuck. IMO it's implemented incorrectly, and even how it is implemented has things in a suboptimal order of determination.

Will explain the second question outside of github

**Comment by katevoss** [comment]
What is the optimal order, and what would the effort be to implement it? Any risks?

Finally, how often do we get questions and complaints about it today? Do you expect that to go up in the near future?

**Comment by geoffjentry** [comment]
@katevoss We get 0 complaints as presumably roughly 0 people know about it. The issues w/ the current scheme are in that blurb - it's just not something that was well thought through, which is understandable as it was a use case that we decided to not support halfway through.

**Comment by geoffjentry** [comment]
Thinking about this more, "backend" is really a Cromwell concept and shouldn't be a WDL concept. I don't think that this shouldn't even find its way into WDL at all.

It should be:

1. Workflow Option
2. Default Backend

**Comment by katevoss** [comment]
As a **user running workflows**, I want to **be able to specify the backend in workflow options**, so that **Cromwell only uses the default backend when no other is specified**.

- Effort: @geoffjentry what do you think the effort will be?
- Risk: Small
- Business value: Small, for now
   - This may change as Cromwell supports more backends and more users operate in a multi-backend environment

**Comment by geoffjentry** [comment]
it's trivial to do.

there's a slight risk involved in that theoretically some WDL would be broken but there's a 100% chance those WDLs become broken in the future anyways.

**Comment by ruchim** [comment]
@geoffjentry -- as of Cromwell 35, `backend` key in the workflow options is honored above the default backend. In case of the workflow option asking for a backend that doesn't exit, Cromwell explicitly fails with:

`Backend for call <call-name> ('<backend-name') not registered in configuration file...`

I believe this issue has been resolved with these changes. Feel free to re-open if something was missed.

**Comment by geoffjentry** [comment]
Works for me for now
