### ISSUE TITLE
Backends should use JobDescriptor runtime attributes

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1314]
The runtime attributes are now included in the JobDescriptor for a task. Backends should use those rather than recalculating them themselves.

* Coercions could still be done by the Backend.
* Definitions of what attributes the backend wants is part of the `BackendXFactory` trait.
* Defaults are calculated automatically. The Backend shouldn't need to fill those in any more.
* Depends on #1307.

**Comment by ruchim** [comment]
Please move the  "assign default runtime attributes" test from MWDAspec to JobPreparationActorSpec (or wherever appropriate).
