### ISSUE TITLE
File hash short-circuiting

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1316]
If call cache writing is disabled and a cache miss is known, we could update the various File Hasher actors and tell them not to bother computing no-longer-required file hashes.

- [X] Depends on #1307

**Comment by katevoss** [comment]
@cjllanwarne any update on this?

**Comment by katevoss** [comment]
@cjllanwarne knock knock. Who's there? It's an old github issue! What? We don't have any of those!

**Comment by cjllanwarne** [comment]
I would check with @Horneth - I know CC is now batching things into some maximum number of hash lookups at a time, but whether it gives up if it finds it can’t continue I’m not sure?

**Comment by Horneth** [comment]
It won't start new lookups but it won't cancel the other hash lookups in the same batch either.
With the current implementation doing that (cancelling lookups for files in the same batch) would be pretty hard.

**Comment by cjllanwarne** [comment]
So I think we can close this ticket @katevoss

**Comment by katevoss** [comment]
Closing!
