### ISSUE TITLE
Test restart capabilities

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1329]
Put in testing for restarts. 

A possible (and preferred by this author) solution would be to seed a database with a known state and make sure a launching cromwell picks things up properly. That sounds like it'd probably be in the Centaur-ish space, but perhaps not.

Another possibility (and not preferred by this author) would be to have a system that submits stuff, shuts down that cromwell, launches another cromwell and goes to town.

**Comment by katevoss** [comment]
From @antonkulaga on #2023:
> It would be nice to have pause/resume in cromwell API. Often you have several jobs running in paralel and when you see that one of them eats too much memory you would like to be able to pause execution for some time, waiting for other workflows to finish and then resume.

>Another usecase is when most of your workflow worked well but fails in the end. You figure out the problem and you do not want to start it from the very beginning as intermediate results are already recorded to the Cromwell-execution folder. You would like to resume after the last successful task

**Comment by katevoss** [comment]
@Horneth Are these the tests you implemented?

**Comment by Horneth** [comment]
The tests implemented are the second version @geoffjentry described (the one he says not preferring 😄 ). The first one has not been done.

**Comment by geoffjentry** [comment]
Which is amusing @Horneth because when we sat down to discuss it a few months ago I had switched to the side of chaos while others were advocating order ;) But really we've got the best of both worlds right now IMO, this is closeable
