### ISSUE TITLE
Enable option to pass a parameter to a set of aliased tasks

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/cromwell#1335]
@geoffjentry 
Here is an example of a situation:

```
workflow wf { 
    String firstname
    String lastname
    call Greeting as GreetingFirstName { input: name=firstname }
    call Greeting as GreetingLastName { input: name=lastname }
}
task Greeting {
  String name
  String greeting
  command {
    echo "${greeting} ${name}"
  }
}
```

The idea is to make it possible to give a value to greetings for all aliased tasks in json like so:

```
{
  "wf.firstname": "Andrey",
  "wf.lastname": "Smirnov",
  "wf.Greeting.greeting": "howdy"
}
```

**Comment by geoffjentry** [comment]
Thanks.

@kcibul Andrey was showing me this - he wants to be able to supply a value as an input to all calls for a task with one statement. At the moment since you need to alias the task for multiple instantiations an input can only refer to one

**Comment by katevoss** [comment]
@geoffjentry or @asmirnov239  can you explain the use case here, what you're trying to do?

**Comment by geoffjentry** [comment]
I don't know why Andrey was asking but the gist is that if you want to call the same task many times in your workflow but suppose for many of the inputs you want them to always be the same, it's a real headache having to supply them multiple times.

**Comment by katevoss** [comment]
@geoffjentry is this something that is often requested? How much effort would it be?

As a **WDL user**, I want **declare a parameter once for many tasks**, so that I **don't have to alias the parameter for each aliased task**.
- Effort: **TBD**
- Risk: **TBD**
- Business value: **Low?**

**Comment by geoffjentry** [comment]
I feel like I've heard it before (@vdauwera?). It seems like a good idea. Technically it should be straightforward to implement

**Comment by geoffjentry** [comment]
This is no longer a Cromwell issue. Interested users should bring it up over at [OpenWDL](http://openwdl.org/#two)
