### ISSUE TITLE
Remove PBE todo in SlickDatabaseAccess after migration is complete

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1336]
The PBE TODO says it can't be done until #789 is complete

**Comment by katevoss** [comment]
@geoffjentry What's PBE? Can it be done yet?

**Comment by mcovarr** [comment]
PBE = Pluggable Back Ends.  Let me investigate your second question.

**Comment by mcovarr** [comment]
Welp I don't see the string "PBE" anywhere in our codebase anymore, and none of our TODOs have even a whiff of this issue about them.  Unless anyone objects I think this is closeable.

**Comment by geoffjentry** [comment]
@katevoss As @mcovarr alludes to, this is a spiritual cousin of that ignored test ticket. A holdover from a time long enough past that the likelihood of any ticket still mattering closely approximates zero.

@mcovarr 
![images](https://user-images.githubusercontent.com/961771/29590873-106c9d7e-876a-11e7-94bc-2fb749479b5e.jpg)
