### ISSUE TITLE
Rework the README

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1343]
Our documentation is a mess. It's a big, giant wall of text. I've been hearing an increasingly large number of complaints that it is so voluminous and hard to navigate that people simply don't bother to read it. We should put some effort to identify what's good, bad and indifferent. Find a better organization scheme. Etc etc etc. If they're up for it, it'd be good to work with @vdauwera and friends when the time comes.

(note to @kcibul - I realize this is currently nearly as amorphous as that other ticket, I just wanted an official placeholder)

**Comment by vdauwera** [comment]
We'd be happy to get involved in this effort.

**Comment by geoffjentry** [comment]
Assigning this to @katevoss - Kate if this is covered by some other ticket that you've got floating around feel free to close this

**Comment by katevoss** [comment]
This task is covered by the DSDE-Comms Epic "[Update Cromwell Documentation](https://github.com/broadinstitute/dsde-docs/issues/1514)", which includes moving most of the content to the WDL website and [slimming down the README](https://github.com/broadinstitute/dsde-docs/issues/1515). Closing this issue.
