### ISSUE TITLE
Centaur Local tests the wrong PR commit in Travis

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1344]
During the PR process, two commits are tested by Travis:

- The actually committed code: aka "push"
- The results of the PR if it were to be merged: aka "pr"

The latter test is currently producing false positives during tests of centaur local.

The way Travis tests the results of the merged PR is by using github's extra `refs/pull/<PR>/merge`. These merge refs are special, and are not pulled down by default during `git fetch`, that only retrieves commits from origin under `refs/heads/*`. One can see Travis doing some of this extra retrieval in this excerpt of a branch that wouldn't build if merged, full log file [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/155209618/log.txt
):

```bash
$ git clone --depth=50 https://github.com/broadinstitute/cromwell.git broadinstitute/cromwell
Cloning into 'broadinstitute/cromwell'...
remote: Counting objects: 2676, done.
remote: Compressing objects: 100% (1294/1294), done.
remote: Total 2676 (delta 879), reused 2196 (delta 632), pack-reused 0
Receiving objects: 100% (2676/2676), 909.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (879/879), done.
Checking connectivity... done.
$ cd broadinstitute/cromwell
$ git fetch origin +refs/pull/1339/merge:
remote: Counting objects: 17809, done.
remote: Compressing objects: 100% (5010/5010), done.
remote: Total 17809 (delta 9885), reused 17612 (delta 9710), pack-reused 0
Receiving objects: 100% (17809/17809), 4.56 MiB | 0 bytes/s, done.
Resolving deltas: 100% (9885/9885), completed with 116 local objects.
From https://github.com/broadinstitute/cromwell
 * branch            refs/pull/1339/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

But later, cromwell passes the wrong commit to centaur:

```bash
cd centaur
./test_cromwell.sh -bdevelop -p5
```

Perhaps centuar local could just use this existing checkout, already provided by Travis. If it didn't want to point to a directory, centaur local could just assemble the jar like centaur jes does and use that.

Alternatively, the various travis variables including [`TRAVIS_PULL_REQUEST`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) should provide enough information for a script to correctly fetch the correct commit from github.

**Comment by geoffjentry** [comment]
Blarg. I'll take a look
