### ISSUE TITLE
Call caching should fall back to running the task if cached files don't exist

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1347]
Call caching should verify that cached files exist before coping, and if they don’t then fall back to running the task.

In FireCloud, users may delete files out of their bucket.  If a cache hit occurs, it should check that the files to be copied exist.  And if they don't Cromwell should fall back to just running the task as if a call cache hit didn't occur.

Bonus points: should we then make that call ineligible for caching going forward?

**Comment by LeeTL1220** [comment]
Can local backend support this as well?  I've already hit this issue.

**Comment by cjllanwarne** [comment]
This is going to be part of the .21 release.
