### ISSUE TITLE
Local backend can use more resources than available on a machine

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1354]
Currently, the local backend will spawn the maximum number of processes to run a workflow.  

Why is this a problem?  
- This can cripple a machine with fewer CPUs than number of tasks that can be executed.
- This can cause all of the RAM to be used running a workflow.  Again, crippling a machine.
- If either of the two above conditions are met, total wall clock time will increase and/or jobs will be killed and/or the cromwell process will be killed.
- This hinders the development of pipelines.

Proposed solution:
- Allow users to specify the maximum number of simultaneous jobs to run for a workflow.  Similar to how it is done in Queue.

Workaround:
- Use JES, if available
- Use SGE, if available

Who?
- Pipeline engineers
- Method developers
- External researchers

**Comment by cjllanwarne** [comment]
This exists in C22+:
```
backend {
  ...
  providers {
    BackendName {
      actor-factory = ...
      config {
        concurrent-job-limit = 5
```
