### ISSUE TITLE
Drmaa support

### ISSUE THREAD

**Issue by ffinfo** [broadinstitute/cromwell#1355]
At this moment there is a way to submit jobs to a HPC with a command line that is executed. With drmaa this is also possible. The only problem is that with drmaa v1 you can only get status of jobs submitted in the same session. This means for recovering after a restart you must rely on command line methods like in the current implementation.

Drmaa v2 have the possibility to track jobs outside it's session but there is almost no support for v2 yet.

Here is the implementation inside queue:
https://github.com/broadgsa/gatk/tree/master/public/gatk-queue/src/main/scala/org/broadinstitute/gatk/queue/engine/drmaa

**Comment by katevoss** [comment]
@mcovarr as our current bug-rotator, what can you tell me about Drmaa? How would it work with Cromwell?

**Comment by geoffjentry** [comment]
drmaa is a generic api for interfacing with things like sge and lsf. we chose not to do this primarily due to reasons of developer speed since supporting HPC has always wound up in the real of developer side projects instead of high priority.

**Comment by katevoss** [comment]
I haven't heard of other requests for drmaa support, is it widely used?

**Comment by geoffjentry** [comment]
@katevoss for HPC interaction it's very heavily used.

**Comment by katevoss** [comment]
Unfortunately this is not something we will be able to prioritize in the near or longer-term future, so I am closing this for now.
