### ISSUE TITLE
JES Backend takes a long time to finish a workflow that fails immediately

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1358]
Ten minutes to finish a workflow hinders debugging greatly.  This is much faster with a local backend, but I am debugging issues specific to JES.

Is this a limitation of JES or can we setup a smaller interval for a polling timer?

**Comment by cjllanwarne** [comment]
- If the job itself fails to start, this can be reported back immediately by Cromwell (although please do raise this as a separate issue with a reproducing WDL if that's what you mean).
 - If Cromwell can start the job but the bash script will fail immediately, then that's out of Cromwell's hands.
 - The overhead of running jobs on JES means that even `echo hello` has a minimum overhead of around 5-10 minutes.
