### ISSUE TITLE
Actor Naming

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1367]
- We have a lot of actors.
- The actor hierarchy can be quite deep in places
- Each actor is given a name, which must make the overall path unique
- Unwieldy actor paths are making debugging awkward. The error lines are often hundreds of characters long!
- We should decide how to name actors, in a way that ensures they have workflow, call and attempt information in the name... but **at most** once.
- We should also retroactively update the actor naming so that all existing actors have appropriate paths.

**Comment by katevoss** [comment]
@cjllanwarne are we still willy-nilly naming our actors? Or have we gotten our actors in line?

**Comment by geoffjentry** [comment]
Closing this as it's nearly 2 years old

@cjllanwarne if you think this is still a problem, be the change you want to see
