### ISSUE TITLE
Un-abstract EngineWorkflowFinalizationActor

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1375]
This is a Trait which has a single implementer, CopyWorkflowOutputsActor. The receive method, among other things are in the trait which is fairly confusing considering nothing else is implementing it.

**Comment by cjllanwarne** [comment]
Not saying this is wrong, but I'd like to get a few extra backends in before we say "this is never going to be used"

**Comment by geoffjentry** [comment]
I'm not saying it'll never be used. I'm saying let's not do this until it needs to be used

**Comment by geoffjentry** [comment]
Closed by #2155
