### ISSUE TITLE
FileHasherWorkerActor needs some love

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1377]
This is currently being built by all implementers of the BackendLifecycleActorFactory, as opposed to props like the trait normally does. @cjllanwarne explained that this is because we want system-wide throttling on this behavior. 

At the moment it's being built as a direct descendent of the root, ie a sibling of CromwellRootActor, and this doesn't seem correct. Also, it appears that all instances of this router will have the same name which should be problematic.

Make this more sane please

**Comment by cjllanwarne** [comment]
This appears to be resolved
