### ISSUE TITLE
Disable metadata summary refresh via config

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1378]
As a user, I would like to be able to disable the metadata summary refresh.  I want to do this because I'd like to be able to stand up a "read only" cromwell that that doesn't write to the database because I can use these to scale out horizontally for read api operations (e.g. status, metadata).  Scaling out these operations is important because it allows my cromwell to remain responsive even under heavy read load.

@geoffjentry -- pls expand/correct

**Comment by geoffjentry** [comment]
Actually now that I think about it this is possible w/o a code change. The service registry stuff is loaded in dynamically by the conf file so you'd just need to not include a metadata service in your conf

**Comment by kcibul** [comment]
This would be excellent if true, let's just confirm that it is!

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by geoffjentry** [comment]
It's true. MetadataServiceActor creates it and MSA is only created if it's in the conf file.

**Comment by geoffjentry** [comment]
I take it all back, I think we need this functionality. The metadata based REST queries will go through the MetadataBuilderActor which in turn pings the MetadataService. Having the MetadataService implies having the summarizer.

Pinging @Horneth just to double check me on this as I believe he's the one who put that stuff together.

**Comment by kcibul** [comment]
Might be nice to disable this by setting the refresh duration (which is already a config value) to zero (or infinite)

**Comment by Horneth** [comment]
@geoffjentry I believe that is correct.
Just to get some clarification on this - why does the summary refresh actor need to be disabled to use cromwell as read-only ? I understand that the refresh actor writes to the database, but in very low amounts (1 line per workflow), and its purpose (as I understand it, @mcovarr ?) is to help relieve the metadata endpoint by avoiding recomputing the current status on every call, which would be useful for a read-only cromwell ?

**Comment by kcibul** [comment]
So if you stand up several cromwells, how do you avoid them all trying to
do the summary stuff and clobber eachother?  That's the purpose of this
ticket.  All the readers would read the summary, but only one should be
writing it

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by mcovarr** [comment]
There should be only one metadata summarizer running per DB.  @geoffjentry can tell you from first hand experience the horrors of having multiple.

**Comment by geoffjentry** [comment]
Right. In theory that could be resolved but it'd be a lot easier for now to just disable them

**Comment by Horneth** [comment]
👍
