### ISSUE TITLE
ContinueWhilePossible not working via Config

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1380]
User @gavvvr  reports:

If i run cromwell with -Dworkflow-options.workflow-failure-mode="ContinueWhilePossible" it does not work. Also using -Dconfig.file=application.conf does not work. Only workflow_failure_mode option in JSON config works.

**Comment by gavvvr** [comment]
config.file is loaded, but 

> workflow-options {
>   workflow-failure-mode: "ContinueWhilePossible"
> }

does not work

**Comment by mcovarr** [comment]
Hi @gavvvr, this should be fixed on develop now.  Thanks for your report!
