### ISSUE TITLE
Standardize shebang and (maybe) make it configurable

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1384]
JES is using the shebang `#!/bin/bash`, and the SharedFileSystem (aka SFS, aka Local/SGE) is using `#!/bin/sh`. This has the side effect that the WDL command may run under [dash instead of bash](https://wiki.ubuntu.com/DashAsBinSh), causing unexpected inconsistencies.

Perhaps the shell of choice, while still defaulting to bash, can be yet another runtime attribute (or similar replacement) related to the other script behaviors:
- contineOnReturnCode
- failOnStderr

This would also allow running even smaller docker images such as [alpine](https://hub.docker.com/r/library/alpine/tags/) or [busybox](https://hub.docker.com/r/library/busybox/tags/), compared to relatively _huge_ [ubuntu](https://hub.docker.com/r/library/ubuntu/tags/).

Relatedly, if we run the instantiated command in a [subshell](1383), a WDL overridden shebang could run any executable, not just sh or bash.

**Comment by katevoss** [comment]
Closed, won't fix (in the near future).
