### ISSUE TITLE
Call caching bug produces ~n^2 copies of data

### ISSUE THREAD

**Issue by dshiga** [broadinstitute/cromwell#1388]
Something seems to be going wrong with how call caching copies data in Cromwell 0.19. For example shard 10 gets copied from a cached call, but all shards matching 10* get copied along with it, e.g. shard 101, 1012, etc.

So we end up with a directory like:
gs://bucket/workflow_id/shard-10/
gs://bucket/workflow_id/shard-10/output.10.txt
gs://bucket/workflow_id/shard-10/shard-101/output.101.txt
gs://bucket/workflow_id/shard-10/shard-1012/output.1012.txt

Where Cromwell should really only have copied output.10.txt.

**Comment by kcibul** [comment]
oh -- really good one.... let's verify this doesn't happen on 0.21!

**Comment by ruchim** [comment]
It's been confirmed that this doesn't happen with the latest version of Call Caching. Ran a 1000 wide workflow and shard-10 only has the necessary files:

<img width="905" alt="screen shot 2016-09-19 at 10 08 45 am" src="https://cloud.githubusercontent.com/assets/14941133/18634944/293b13e4-7e51-11e6-95a9-4d5afeb1101e.png">
