### ISSUE TITLE
JES Globbing should use new glob count to beat eventual consistency

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1395]
Currently, to process a glob on JES, Cromwell does an `ls` of the google cloud storage location.  The problem with this is that ls is eventually consistent, which leads to bugs like #843 

JES has added a feature (#28858407) where they now return the number of files that matched the glob as part of their metadata.  These appear as events of the form

`{Description: "copied 3 file(s) to \"gs://my-bucket/out/\"",
           StartTime:   {Seconds: 1470063955,
                         Nanos:   748725437}},`

In Cromwell, when processing these globs, we should poll (with adjustable maximum timeout) for this number of files to appear via the ls.  If they do not appear after the timeout, the task should fail with an appropriate error message.

If we are processing globs on GCS and NOT using JES, the best we can do is just grab and go via the ls (as we are doing currently for JES).

**Comment by dvoet** [comment]
+1 to fixing - this is a particularly insidious issue that can lead to incorrect scientific findings without a whiff of something wrong. S3 will be like this as well. I don't think we should ever "just grab and go via ls." If we don't have something like JES reporting what is delocalized we need to write it ourselves. Something as easy as a manifest listing the files that were delocalized.

**Comment by geoffjentry** [comment]
@dvoet the reason for not having been done yet was that the primary motivating use case (or problem turner upper as it were) was GOTC who were able to work around it by not globbing in the first place. I believe this will be part of the upcoming 23 release.

re S3, good news there for you, we have to do our own localization so don't need to rely on others to tell us what's going on ;)

**Comment by dvoet** [comment]
A better design (which maybe requires a JES ask) is to have JES report back _exactly_ what was uploaded. Then there will be no uncertainty, no timeouts and no issues with eventual consistency being to eventual.

**Comment by geoffjentry** [comment]
@dvoet Yes, that's why that's what we asked for. It was rejected and we got the count instead.

**Comment by dvoet** [comment]
booo
