### ISSUE TITLE
Better testing of Abort endpoint

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1396]
In the course of responding to a bug report with Abort @mcovarr quickly found several other related bugs in Abort which points to the fact that we should have better testing of the Abort endpoint

**Comment by katevoss** [comment]
Abort is broken, it is true. Closing this issue in favor of tracking all the Abort-related work in the [Google Doc](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit).
