### ISSUE TITLE
Cromwell does not seem to exit after it has completed all possible jobs

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1399]
Reported by Lee on 0.19

When I run a WDL in single-workflow mode from the commandline... it doesn't exit upon workflow completion.

Ensure this is not the case on 0.21+.  When the single-workflow completes, Cromwell should exit cleanly.

**Comment by geoffjentry** [comment]
Can confirm this doesn't happen.

**Comment by kcibul** [comment]
👍  excellent -- there you go @LeeTL1220 !
