### ISSUE TITLE
JES abort claims success on successful abort request, not successful abort

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1409]
Can you add more details?  Is this at the REST endpoint level, or an internal thing?  How would the user experience this issue?

Do you mean/ for example

If you abort a workflow/call running on JES via the REST endpoint, Cromwell will return a 200 OK indicating "yes, I will try to abort this" as opposed to 200 OK "yes, I have aborted this".

If it's at the REST endpoint level the "Request received" sounds right to me.  The user shouldn't have to wait for the abort to occur, and for some backends it's a best-efforts anyway (like JES' cancel operation command)

**Comment by katevoss** [comment]
@mcovarr can you explain more what this issue is? Alternatively, I can close it and you're welcome to  add to the [Abort spec](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit).

**Comment by Horneth** [comment]
Cromwell now claims a workflow is aborted when it has confirmation from JES that all jobs have a terminal status. This does not necessarily mean that JES did successfully abort all of them, but that's an issue we should bring up to Google if it happens. I'm not sure what this ticket is suggesting to do so I won't close :)

**Comment by mcovarr** [comment]
Yeah what we have now is what this ticket was clumsily asking for. 😄
