### ISSUE TITLE
Reduce Scope of EJEA

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1413]
Amorphous ticket - will need to be explored & refined (likely into multiple tickets?) before being acted upon.

With our new suite of actors we still have one spot which seems to be a central hub for all commerce and activity. Multiple people have opined that with all of the incoming messages & state transitions that there are almost certainly pieces which could be peeled out in order to streamline it a bit

**Comment by katevoss** [comment]
@geoffjentry Why do we need to reduce the scope of EJEA? What's the current problem? 
We do have the i/o actor, does that help?

**Comment by geoffjentry** [comment]
It's a code cleanliness & developer sanity issue.

**Comment by katevoss** [comment]
What is the affect of the current EJEA versus a reduced EJEA on Cromwell and the user? What do you mean by developer sanity? What would the effort be to reduce EJEA?

**Comment by geoffjentry** [comment]
There is no impact on the user, that's why it's labeled as technical debt :)

This isn't the sort of ticket which should ever be prioritized by product but rather picked up as desired on cycles devoted to cleaning up tech debt

**Comment by katevoss** [comment]
What impact does it have on Cromwell? Why is this technical debt? I want to understand more about what would be involved, regardless of its impact.

**Comment by katevoss** [comment]
It's hard to say what the impact is, right now it is likely an annoyance.

- Effort: **Medium**
- Risk: **Low**
- Business value: **Low**

**Comment by geoffjentry** [comment]
Closing this as it is nearly 2 years old
