### ISSUE TITLE
Fix-up abort wiring

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1414]
When we traced through the new actor model there was a lot of wonkiness in how an abort request works its way through the system.  There were end runs being made, direct shortcuts to specific things, etc. 

Our thoughts were:
- Make sure that the whole process is async. An abort request returns immediately and the workflow is set to an `aborting` state (as opposed to `aborted` and ??? if it fails to abort)
- Have the abort request work its way through the workflow in a more logical manner, working down from the `WorkflowActor` to the `WorkflowExecutionActor` to the `EJEA`, etc
- Have each stage watch for all of its children (not necessarily in a supervision sense) to complete or not before sending the success/failure response back up

**Comment by geoffjentry** [comment]
Placeholder note that we've got the design doc on our google drive

**Comment by ruchim** [comment]
Another recent example of some strange aborting behavior: http://gatkforums.broadinstitute.org/gatk/discussion/comment/40215

**Comment by katevoss** [comment]
I'm going to add these notes to the [Spec Doc](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit) and close this issue. Aborts need some serious thought and work, to be tracked in the spec doc.
