### ISSUE TITLE
Atomic file copying to avoid partial inputs

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1426]
The zeroth localizers checks to see if a file exists before re-localizing. The copy localizer should therefore copy-to-temp-then-rename.

Current broken behavior:
- Run SGE task with a large `input.bam` and copy localization
- Cromwell starts copying to `<call_root>/input.bam`
- Kill the job during localization
- Restart cromwell
- Cromwell detects the partial `<call_root>/input.bam` exists.
- The job continues without relocalizing.

Better behavior:
- Run SGE task with a large `input.bam` and copy localization
- Cromwell starts copying to `<call_root>/input.bam.tmp`
- Kill the job during localization
- Restart cromwell
- Cromwell doesn't detects the partial `<call_root>/input.bam` exists.
- The job continues with relocalizing.

And when cromwell isn't killed:
- Run SGE task with a large `input.bam` and copy localization
- Cromwell starts copying to `<call_root>/input.bam.tmp`, ensuring to overwrite previous results
- When copying finishes rename `<call_root>/input.bam.tmp` to `<call_root>/input.bam`
- The job continues

NOTE: Most people do not like copying inputs anyway, so this hasn't been a major issue.

**Comment by kcibul** [comment]
Is there a typo in the better behavior?  Should the job continue WITH
relocalizing (since the input.bam file is partially copied?

**Comment by kshakir** [comment]
Edited

**Comment by ruchim** [comment]
@kshakir just confirming, but this implementation already seems present in the SFS Backend?

**Comment by kshakir** [comment]
Yep. Ticket just wasn't closed. For linking purposes, `localizePathViaCopy` was fixed shortly after this ticket was filed, by #1439.
