### ISSUE TITLE
Exceptions thrown in JABJEA <init> not handled, hang workflow

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1435]
We saw during JG testing that a stray non-`lazy` instance variable in `JesAsyncBackendJobExecutionActor` led to an exception being thrown during `<init>`.  This exception wasn't handled by any supervisor nor by JABJEA itself, so the JABJEA (and possibly `JesJobExecutionActor` and other actors) simply crashed.  The net result was the `WorkflowExecutionActor` stayed `Running` forever, waiting for a terminal job message that would never come.

**Comment by geoffjentry** [comment]
"instance variable" .... named ....?

**Comment by mcovarr** [comment]
It was `callContext`, but @ruchim snuck a fix for this specific problem in #1394.  However the general issue of exceptions thrown from JABJEA `<init>` hanging the workflow remains.
