### ISSUE TITLE
GCS storage appears to be created redundantly

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1437]
`JesCallPaths` extends `JesWorkflowPaths` and appears to create a lot of workflow-level data redundantly.  Besides wasting time and possibly money, this causes unnecessary calls to Google APIs which count against our QPS limits.  During 9/16 JG testing we saw an error creating `storage` in `JesWorkflowPaths` (which should have been treated as a transient error per #1436), but it seems that storage should have been created as part of the `JesBackendInitializationData` by the `JesInitializationActor` and then simply passed to the job actors.

**Comment by Horneth** [comment]
I'm pretty sure [this PR](https://github.com/broadinstitute/cromwell/pull/1429) will take care of this problem.

**Comment by cjllanwarne** [comment]
Looks closed by that PR. Reopen if it reappears
