### ISSUE TITLE
Cache read + restart perhaps not ideal

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1441]
This ticket is a reminder to discuss what @cjllanwarne was saying Friday afternoon.  I don't believe this is a release blocker, but noting it for future consideration:

The interplay between restart and caching is possibly not ideal.  When restarting with cache read turned on, Cromwell will begin potentially expensive hash calculations on jobs that may have previously been running.  However, Cromwell currently does this calculation before checking if jobs were actually running and recoverable, which if they were would make hash calculation unnecessary.  

On the other hand, perhaps determining whether a job is running in the backend is more expensive than calculating hashes.  Shrug. 

Anyway, the current scheme is likely more accidental than intentional and would benefit from some discussion.

**Comment by geoffjentry** [comment]
@mcovarr Perhaps it *is*? Can we flesh this out (tagging @cjllanwarne and @kcibul) or close?

**Comment by katevoss** [comment]
@mcovarr is this still the case?

**Comment by mcovarr** [comment]
AFAIK this is still an issue.

**Comment by katevoss** [comment]
@mcovarr still a problem with the restart tests?

**Comment by mcovarr** [comment]
This wasn't a testing problem, this was a problem with the production code.  This issue probably still exists but I'm not 100% sure.

**Comment by katevoss** [comment]
@Horneth was this issue covered by the fixes you made after you implemented the restart tests?

**Comment by Horneth** [comment]
Looking at the code it seems Cromwell first checks if a job was already complete before doing call caching computation. However I don't think I modified it while fixing restart it might have already been like that

**Comment by katevoss** [comment]
@Horneth then it sounds like it's no longer the case that Cromwell doesn't check if a job is complete before calculating the hash when restarting. In that case I'll close it unless there are objections.
