### ISSUE TITLE
Call cache hits sometimes fail while copying outputs

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1444]
When there are a lot (~1800 or as many as 3000) of cache hits in a workflow, timeouts or other errors talking to Google often occur (probably can all be fixed with added retries).

Impact: High. Prevents us from using call caching for 20k sample sets, which in turn requires us to manually stitch together outputs from multiple workflows to gather all the successes together, which is prone to error. When it is feasible to use, this problem still often requires us to repeatedly relaunch the same workflow, duplicating the data many times.

This can be tested by the same WDL used to verify #1185

**Comment by Horneth** [comment]
I believe this is fixed by the I/O Actor
