### ISSUE TITLE
WorkflowExecutionActor bogs down with needless Scope equals

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1457]
There are at least four spots in `WorkflowExecutionActor` where `==` is invoked on `Scope`s.  This is not so good as `==` in Scala does a deep equals, and the `Scope` implementations are case classes with compiler-generated `equals` and `hashCode` implementations.  These implementations invoke `equals`/`hashCode` on their constructor fields, including `Task` which contains a lot of hairy stuff including ASTs.  This is extra bad in `WorkflowExecutionActor` since these `==`s are invoked synchronously with message processing to update the execution store, and all this computation is effectively single-threaded within a workflow.  In practice, for a 20K wide scatter this causes the `WorkflowExecutionActor` to spend upwards of 20 minutes from the time work finishes in (mock) JES to actually succeeding the workflow.

I *think* this might be fixed by chasing down all the spots where `==` is used on `Scope`s and replacing that with call FQN + index + attempt comparisons instead.

**Comment by geoffjentry** [comment]
FWIW (hi @kcibul ) - I just did a big run with single call workflows, which would be the least bothersome workflow shape for this issue. The WEA was a very notable problem child already, and that problem is going to get exacerbated as the WF shape expands

**Comment by mcovarr** [comment]
The original title of this ticket turned out to be incorrect, the actual problem was needless `hashCode` computation when `Scope`s were put in `Set`s or used as `Map` keys.  Thanks to @kshakir for pointing out that Scala should generate case class `equals` correctly and shouldn't have the problem I had claimed.  😄 

PR forthcoming for the `hashCode` issue.
