### ISSUE TITLE
Cromwell will copy symlink rather than underlying file

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1466]
- local backend
- using docker
- pre-0.21 snapshot
- symlink input

The hard-linker in cromwell seems to be silently failing.  When the local backend then moves to the copy localizer, it copies the symlink, rather than the file underneath the symlink.  Within docker, that symlink is invalid.

Desired behavior is to have the hard linker work, not to copy the files.

Discussed with @kshakir 

For now, workaround is to make sure that all input files are actual files (or hard links) and not symlinks.

**Comment by katevoss** [comment]
@LeeTL1220 we are cleaning out the backlog and wanted to check whether this is still happening. Can you reproduce? I know a lot has changed in 4 versions :)

**Comment by LeeTL1220** [comment]
@katevoss I'll re-file if it is still an issue.  I'm pretty sure this is fixed/worked around.
