### ISSUE TITLE
support for multiple workflows in a single WDL/namespace

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1475]
As a WDL author, I would like to be able to write a sub workflow and call it from my main workflow as a subworkflow.  I would like the main workflow to be backwards compatible, so I would like to use a keyword modifier to flag the _other_ workflows as being non-primary.  

E.g. perhaps the keyword `sub` so I would write `sub workflow { //blah }`.  Since these workflows would be callable when they are included via an import I'd prefer to not have a keyword like `private` since that implies visibility/access

**Comment by cjllanwarne** [comment]
Closing this since the spirit of the ticket can be achieved using imports
