### ISSUE TITLE
Determining cache misses (or hits) is slow for jobs with bam file inputs on a local backend

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1483]
- local backend

The slowness is probably driven by calculating a md5 hash on the bam input files.  For jobs that do not have bam files as inputs, the cache determination is fast.

Calculating a md5 on a bam file is too slow for use in call caching on a local backend.  I can provide a time estimate, if necessary.

Does SGE backend has the same issue?

Proposed solution:
- If md5 file is next to input file (e.g. sample1.bam is next to sample1.bam.md5) then read the md5 hash from the *.md5 file.  Otherwise, use the file path.  For bams, the file paths will tend to be static for most local backend environments anyway.  
- Make sure this convention is documented.
- Perhaps have a flag in the conf file so that users can choose which convention they prefer?  IMHO, have the fast method (above) as the default.

**Comment by LeeTL1220** [comment]
@kcibul This one is important.

**Comment by geoffjentry** [comment]
I thought we had an option to just use the file path already although perhaps that didn't make it in. I'll take a look

**Comment by LeeTL1220** [comment]
@geoffjentry That would be great!

**Comment by geoffjentry** [comment]
AFAICT that was left on the cutting room floor. I see no evidence of it in the code or docs but I know it was discussed at some point.

**Comment by LeeTL1220** [comment]
Doh!
