### ISSUE TITLE
Refactor job aborts via EJEA

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1504]
Currently WorkflowActor aborts BJEAs directly.

A whole bunch of much nicerness would occur if it aborted the EJEA and let that ripple down the abort to the BJEA (or something else, depending on its FSM state)

**Comment by katevoss** [comment]
This is included in the Aborts design doc: https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit 

Closing
