### ISSUE TITLE
Aggregate "important-but-annoying" log messages

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1505]
Say you get 4500 "Quota Exceeded" log messages. You don't want to ignore them, but you don't want 4500 entries in the cromwell log either.

Perhaps there's a middle ground where they get aggregated and you only get one summary message every 10 minutes?

**Comment by katevoss** [comment]
This use case may no longer be applicable. If there are other examples, feel free to reopen.
