### ISSUE TITLE
Invalidate calls that fail to be use as a call cache for future cache lookups.

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1510]
If a call hits the cache but fails to use the cached call for whatever reason (output / detritus file not found etc...) , the cached call isn't invalidated so every other similar call will always fail to use the cache.

**Comment by cjllanwarne** [comment]
NB There's already a database column for this, so don't add a new one. Probably easier said than done but it should be as easy as incorporating that boolean into the SQL query (and adding a way to flip it to false)

**Comment by cjllanwarne** [comment]
This is particularly useful since we might have lots of entries for the "same" cache result, so we might be able to find another one that works next time we hit the cache.
