### ISSUE TITLE
Declare variable Array[File] of output from task in scatter

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#1513]
It would be great to be able to declare variables based on output from tasks. In this example WDL I want to use an array of all the shards from TaskA as input to TaskB even though TaskB is in the same scatter.

```
task TaskA {
    File single_input_file

    command {
        #Something happens that takes a single file and returns a single file
    }
    output {
        File output_single_file = "some.file"
    }
}

task TaskB {
    Array[File] array_of_files
    File single_input_file

    command {
        #Something happens that takes an array of files and a single file
    }
}

workflow inputsFromScatter {
    Array[File] list_of_files = ["a.file", "b.file", "c.file"]

    scatter(file in list_of_files) {
        call TaskA {
            input:
                single_input_file = file
        }

        call TaskB {
            input:
                single_input_file = file,
                array_of_files = variable_declared_outside_of_scatter
        }
    }

    Array[File] variable_declared_outside_of_scatter = TaskA.output_single_file
}
```

This workflow currently results in this error: `Workflow input processing failed.
Workflow has invalid declarations: Could not find a value for TaskA`

I may have oversimplified this example because TaskB could be in a separate scatter. If you'd like a real example with actual tasks I'd be happy to provide it.

**Comment by cjllanwarne** [comment]
I think this will come more or less "for free" when we bring in Scott's branch

**Comment by cjllanwarne** [comment]
We should double check this once we have #1577

**Comment by yfarjoun** [comment]
👍

**Comment by kcibul** [comment]
time for that double check...

**Comment by cjllanwarne** [comment]
Should be fixed once https://github.com/broadinstitute/wdl4s/pull/52 is merged and Cromwell brings in that WDL4S update

**Comment by Horneth** [comment]
Double checking now

**Comment by Horneth** [comment]
Also fixed by https://github.com/broadinstitute/cromwell/pull/1711 / https://github.com/broadinstitute/wdl4s/pull/52
