### ISSUE TITLE
REST API submission validation

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1515]
Using release 0.21.
There seems to be a discrepancy between [what the docs say should happen](https://github.com/broadinstitute/cromwell#error-handling) if you submit badly-formed WDL inputs to REST API, and what actually happens: which is that the inputs are accepted (get back a response with "Submitted" status), but later fail. Or am I misunderstanding the docs?

**Comment by delocalizer** [comment]
I can't remember the details but I seem to remember many versions ago that WDL parsing used to be synchronous with API submission, and you'd get a fail status back straight away if the WDL was bad. I think this issue was caused my naive expectation that that would always be the case.

**Comment by geoffjentry** [comment]
@delocalizer Yeah we changed this a while back to help w/ submission performance under load. Those synchronous checks were really bogging things downl.
