### ISSUE TITLE
warnings with "sbt test"

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1516]
Warning: Unknown ScalaCheck args provided: -l DockerTest -l CromwellIntegrationTest -l DbmsTest -l GcsIntegrationTest -l PostMVP

**Comment by mcovarr** [comment]
I messed with this for a while but unfortunately my sbt fu is too weak.  😢 

The fastest way I found to reproduce the problem was 

```
sbt "project core" test
```

All the possible modifiers in `sbt foo:test` appear to reproduce the problem with the exception of `alltests`.

**Comment by kshakir** [comment]
FYI if ScalaCheck sneaks back into our dependencies again, and someone wants to regression test this, `sbt "project <project>" test` can be shortened to `sbt <project>/test`, for example:

- `sbt root/test` (same as `sbt test`)
- `sbt core/test`
- `sbt gcsFileSystem/test`
- `sbt root/test:test` (also same as `sbt test`)
- `sbt engine/docker:test`
- `sbt services/alltests:test`
- etc.
