### ISSUE TITLE
Race conditions aborting

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1521]
These race conditions can leave Cromwell in an inconsistent state:
- The `WEA` might receive an `AbortedResponse` outside of the `Aborting` state. It should do something appropriate
- The `WEA` might receive something other than `AbortedResponse` while in the `Aborting` state. It should do something appropriate

**Comment by katevoss** [comment]
@cjllanwarne what's the WEA? Sounds like another one for the [Aborts google doc](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit).

**Comment by geoffjentry** [comment]
`WorkflowExecutionActor`

**Comment by mcovarr** [comment]
You've probably heard its rap name pronounced as "we-uh".

**Comment by katevoss** [comment]
@cjllanwarne does the WEA still function as you originally wrote in the issue, almost a year ago?

**Comment by Horneth** [comment]
Both of those are now covered in https://github.com/broadinstitute/cromwell/pull/2808
