### ISSUE TITLE
Successfully Run a 20K wide scatter 

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1534]

**Comment by geoffjentry** [comment]
Step 1 - a generic 20k wide scatter w/o call caching using mock-jes.  Scored 💯  / 💯

**Comment by geoffjentry** [comment]
Disregard above. 2 jobs are in a stuck state somehow and the workflow didn't complete.

**Comment by ruchim** [comment]
@geoffjentry is this still in progress?

**Comment by geoffjentry** [comment]
Not at the moment.  This is currently blocked by #1777 although @jsotobroad indicated that perhaps I was not giving it *quite* enough memory (IIRC I was giving 24G and he said it might need ~30GB)

**Comment by katevoss** [comment]
Closing this as it has become stale.
