### ISSUE TITLE
Bonus: Implement (control flow) 'else's

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1550]

**Comment by geoffjentry** [comment]
@cjllanwarne This looks like it could be the infamous `esled`?

**Comment by mcovarr** [comment]
isn't this done?

**Comment by cjllanwarne** [comment]
Alas, no. We have `String s = if true then "x" else "y"`, but this ticket is for flow control style `else`s:
```
if (true) {
 call x
} else {
 call y
}
```

**Comment by katevoss** [comment]
@cjllanwarne it's still not done, right? What effort would it take to implement?
@ruchim can you explain what the "else" would do and why?

**Comment by geoffjentry** [comment]
Closing this as it is more or less a dupe of #2436
