### ISSUE TITLE
A beginners guide to making a Cromwell backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1553]
Might be nice to make some docs or notes next time we make a backend. E.g.:
- What steps are required for a MVP backend
- What can we add on to make it better
- What does the engine do for us
- What does the backend have to implement
- Which existing backend is the best to copy/paste to get 99% of the way there?

**Comment by mcovarr** [comment]
@geoffjentry do you have a link to the doc you wrote up before?

**Comment by cjllanwarne** [comment]
@mcovarr I've started an informal blog-style MD file at https://github.com/broadinstitute/cromwell/blob/develop/MakingABackend.MD

I'm hoping that it can become a useful starting point for someone looking to make a backend that's actually far more useful than a dry document.

**Comment by geoffjentry** [comment]
@mcovarr It's going to be out of date but https://docs.google.com/document/d/1VdzsNX1jNII387fn9GxFXctY9o69Xnq7ALegvmLiVzA/edit#heading=h.yf7dpcz6tvjw

@cjllanwarne Perhaps this would be a good use for https://github.com/broadinstitute/cromwell/wiki ?

**Comment by katevoss** [comment]
I discussed this with @kshakir, we're going to turn this into a blog post (#2017) for the new WDL blog. Unless anyone objects, I'll close this ticket and interested parties can follow the new ticket.
