### ISSUE TITLE
Tried to pass string to wdl input of type "File", got no error and workflow failed. 

### ISSUE THREAD

**Issue by dlivitz** [broadinstitute/cromwell#1561]
Tried to pass string to wdl input of type "File", got no error and workflow failed. 

I ran this in firecloud, and my expression for "id" evaluated as a string.

Here's my wdl:

```
task get_mutations_across_intervals {
  File id
  File orignal_maf
  Array[File] mafs

  command {
    python /opt/make_intervals_v2.py ${id} ${orignal_maf} ${sep=" " mafs}
}

  runtime {
    docker: "gcr.io/broad-firecloud-itools/pysam"
  }

  output {
    File interval_maf = "${id}.forecallready.maf"
  }
}

workflow get_mutations_across_intervals_wkfl {
  call get_mutations_across_intervals
}

```

**Comment by katevoss** [comment]
@dlivitz cleaning out old issues and we came up with this one, are you still experiencing a problem? If so I invite you to add a forum question. Closing this out for now.
