### ISSUE TITLE
Prioritize submitted workflows

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1566]
As a high volume production user, I'm glad that Cromwell now has a decoupled mechanism for submitting workflows versus running them.  I often will submit more workflows than my server or google quotas can handle and so I keep the maximum running workflows set to a smaller number of workflows than I submit.  Previously I would have to keep my own queue and dribble workflows into Cromwell to get the same effect.

However, one thing I have lost is the ability to prioritize those workflows!  I need to be able to prioritize those submitted workflows that have not started running.

This feature has several components:
    - ability to specify a priority (integer) when submitting a workflow
    - ability to set a priority for a submitted workflow (ok to not check it's status) [new REST endpoint to PATCH a workflow]
    - change the query for the polling mechanism that picks up workflows to sort by descending priority (e.g. 1 is highest priority) when selecting workflows

While users can change the priority of a running workflow, this has no effect.  It is the priority to start a workflow.

**Comment by katevoss** [comment]
@kbergin this sounds like the feature HCA wants, would you add your use case here too?

**Comment by katevoss** [comment]
@geoffjentry what do you think the effort would be? Any risks?

**Comment by geoffjentry** [comment]
For the wording of this issue it'd not be hard to do.

**Comment by Selonka** [comment]
Hi,
Kate brought me here by this thread in the [forum](https://gatkforums.broadinstitute.org/wdl/discussion/10296/prioritize-workflows-which-are-allready-in-server-queue#latest) 

It mostly covers the features @kcibul already requested. In addition, I would like to have an API command which forces a workflow directly to start by sending an actual running workflow to sleep/ pause. Maybe this could go hand in hand with call-caching for the sleeping workflow?

Greetings Selonka / EADG

**Comment by kbergin** [comment]
@katevoss @geoffjentry @kcibul @dshiga 

The HCA has no current need for prioritization of workflows, but has a strong need for the ability to submit jobs without starting them (in a queue) and then start them later on. Our entire infrastructure design relies on this feature existing. This ticket is framed by Kristian above as though that functionality already exists, but from my understanding it does not? 

I believe it is @ktibbett and the green team / gp production who really need the prioritization feature, so I'll tag her here to add in their use cases.

**Comment by katevoss** [comment]
Related Google doc on [Preflight Workflow Management](https://docs.google.com/document/d/1qYG2hff3D2ZcJWMoO4DrIjLjKYUuqKlP5p-a9_Bo988/edit#), or queuing.

**Comment by ernoc** [comment]
Hi, this sounds like a very interesting feature! In a scenario where you are submitting thousands of workflows taking potentially weeks to finish, there's always the possibility that you need to run something rather urgently to get a specific result.

**Comment by ruchim** [comment]
Hey all,

Since this is not on our roadmap for the next 6months or so, I'm closing the issue for now, and we can re-open it when it gets closer to the point of planning/implementation.
