### ISSUE TITLE
File inputs in the AWS Backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1568]
To wire up the File input, either by bootstrapping via a file copy script, or by mounting the required files via a mounted volume.

Success criteria: we can run a WDL such as:

```
task fileIn {
  File myFile
  command { cat ${myFile} }
}

workflow {
  call fileIn { input: myFile = "s3://..." }
}
```

**Comment by katevoss** [comment]
Closing too.
