### ISSUE TITLE
File outputs in the AWS backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1569]
To wire up the File output, either by running the file delocalisation in the execution script, or by copying the required files to a known mounted volume.

Success criteria: we can run a WDL such as:

```
task fileOut {
  command { echo "hello, amazon" > myFile }
  output { File outFile = "myFile" }
}

workflow {
  call fileOut
}
```

**Comment by katevoss** [comment]
If ss working, then this must be done.
