### ISSUE TITLE
Tidy up the synchronous hell that is the current AWS backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1570]
- [ ] Add the AsyncAwsBackendExecutionActor FSM to manage all the states we're going to need
- [ ] Remove `Await.result()`
- [ ] Remove `Thread.sleep()`

**Comment by geoffjentry** [comment]
I'd <3 it if this was done via actor messaging vs futures, from convo with @cjllanwarne it sounded like that was viable

**Comment by cjllanwarne** [comment]
@geoffjentry I agree. I think we could easily replace the `promise.complete`s in `AwsSdkAsyncHandler` with appropriate messages to appropriate actors (NB we probably don't *need* the `AwsSdkAsyncHandler` wrapper class at all)

**Comment by ruchim** [comment]
@kshakir is this a duplicate of your current ticket?

**Comment by katevoss** [comment]
Unlikely to clean up in the next 6 months. Closing for now.
