### ISSUE TITLE
Make mock-jes great again!

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1571]
Recent changes in Cromwell has made it such that mock-jes no longer works. 

https://www.youtube.com/watch?v=DtRNg5uSKQ0

**Comment by kcibul** [comment]
All fixed -- see https://github.com/broadinstitute/mock-jes/pull/1

Since this only works when deployed to App Engine, I've deployed it to our "mock production" there and ran 50 workflows... only the /batch endpoint is invoked and everything seems to be working properly

**Comment by geoffjentry** [comment]
@kcibul To be clear you mean that you only exercised the /batch endpoint, right? There's no weird reliance on that (I can't imagine how that even would be the case otherwise)

**Comment by kcibul** [comment]
No I ran Cromwell against mock-jes and successfully ran (now) a few thousand workflows, so it hit both the submit as well as batch status endpoints.  

Cromwell no longer calls the singleton status endpoint, just the batch, so I can't tell if the singleton status still works (although no code there changed so I'm confident it's fine)

**Comment by geoffjentry** [comment]
oh wehn you said batch i was picturing the cromwell batch submit endpoint, never mind :)
