### ISSUE TITLE
Create and Destroy TaskDefinitions per Job

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1572]
Every `Job` (or maybe `Call`) probably wants its own TaskDefinition, so that `ContainerImage` and `Command` can be customised per job.

Wire up the docker runtime attribute! I want to be able to run sleep in whatever docker I choose:

```
task sleep {
  command { sleep 23 }
  runtime { docker: "ubuntu:latest" }
}
workflow main {
  call sleep
}
```

**Comment by ruchim** [comment]
@mcovarr just checking --is this ticket now outdated?

**Comment by katevoss** [comment]
No longer relevant.
