### ISSUE TITLE
Option to skip (but don't invalidate) call cache hits that fail for permission errors

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1587]
As FireCloud, I would like to enable call caching.  Because this is a multi-tenant system, and Cromwell knows nothing about users, I may try to call cache to a call where I don't have permission to read the files.  Currently (due to #1510) this would cause that cache hit to be ejected from the cache, and thus unavailable to users who do have the right file permissions.

I would like to have a option in cromwell which would allow me to disable this invalidation step.  When I attempt to call cache, and the cache hit fails due to a permission problem I simply attempt to cache using the next hit (if there are any).

@abaumann -- please comment with any changes

**Comment by abaumann** [comment]
Yes this looks right - we also want to iterate over every possible cached file, just try on each until we hopefully find a hit we have permissions on
