### ISSUE TITLE
Some logging messages about completed jobs and (if possible) remaining jobs would be useful

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1593]
When looking at the output of cromwell (0.22) single workflow mode (local backend), it would be useful to have output that listed the number of completed jobs and remaining jobs.

Currently, it is not possible to determine whether the jobs are finishing, hanging, etc in single workflow mode.

The behavior in GATK 3.x Queue can serve as a model.

**Comment by geoffjentry** [comment]
Define "hanging" and "etc"

**Comment by LeeTL1220** [comment]
hanging = "job will run forever unless terminated"

Wrote that previous comment too quickly, I guess.

Simply requesting that cromwell stdout prints a status similar to Queue -- this makes debugging a lot easier:

```
.....snip....
INFO  15:50:08,653 QGraph - 0 Pend, 1 Run, 0 Fail, 1375 Done
```

**Comment by LeeTL1220** [comment]
Also, helps to determine whether cromwell itself is hanging.

**Comment by kcibul** [comment]
This seems like a useful feature.  It's most useful in single workflow mode as you know that only 1 workflow is running and can interpret the results easily.  

Emitting the number of 

- pending
- running 
- failed
- successful

 calls every 60 seconds.  

I don't think we can do something about "hanging" calls, but as Lee points out by knowing your workflow and seeing that nothing is moving from running to done/failed the user can make that determination

**Comment by LeeTL1220** [comment]
Yes, I would not expect Cromwell to be able to determine what is hanging.
