### ISSUE TITLE
Cromwell should complain about unrecognized config keys

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1598]
An incorrect key was being used to specify hashing strategy, but Cromwell didn't complain and the user wrongly thought their value was accepted.

**Comment by LeeTL1220** [comment]
+1000

**Comment by geoffjentry** [comment]
That'd be really tough to do, particularly when considering pluggable backends

**Comment by katevoss** [comment]
@mcovarr what is a config key, and when would a user interact with it? 
@LeeTL1220 is this something you encounter often?
@geoffjentry do you still think it would be really tough?

**Comment by geoffjentry** [comment]
My view of impossibility has only increased.

You could narrow it down to a subset of things - 

- Nothing in the backend
- Nothing in the service registry
- In the future, nothing involving filesystems

And it'd be easy to do. But most of the stuff people will be fiddling with are in those blocks.

**Comment by mcovarr** [comment]
I'm fine with closing this but that might make @LeeTL1220 cry.
