### ISSUE TITLE
ExecutionStore should not be a Map

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1602]
The keys in the current `Map[JobKey, ExecutionStatus]` contain `Scope`s, which lead to unexpectedly expensive filtering operations on the store.  This has already led to #1468 and appears to be implicated in the recent "Cromwell takes forever to finish" reports from our Methods friends.

**Comment by mcovarr** [comment]
This showed up in a stack trace for #1603

**Comment by Horneth** [comment]
Should we just rewrite the hash / equals methods in the Scope trait ?

**Comment by cjllanwarne** [comment]
It sounds like you aren't really objecting to it being a map, instead that the key is not narrow enough?

If you changed this to something else (`List`?) you'd still have to filter based on the expensive `scope`s

**Comment by mcovarr** [comment]
It's currently cheap to `==` `Scope`s since matches satisfy instance equality and misses fail quickly, so filtering `List`s of `Scope`s is not an issue.  It's the deep `hashCode` computation to determine map buckets that's the problem.

**Comment by geoffjentry** [comment]
@mcovarr: "It's the deep hashCode computation to determine map buckets that's the problem." how did you determine this? jprofiler?

**Comment by mcovarr** [comment]
At the time `hashCode` was all over the Ctrl-\ thread dumps.  After seeing all the expensive computation in `hashCode` and considering that keys should have been comparable via instance equality, it became clear that was the problem.  It sounds like that's not what you're seeing now?

**Comment by geoffjentry** [comment]
@mcovarr I don't *think* so but as I mentioned earlier I wasn't completely buying what jprofiler was selling and need to take a closer look. Also our comparisons shouldn't be hash code based anyways.

One thing I did turn up was elsewhere in that file you had been converting some sets to lists to avoid hashes coming out of filters and such, that might be a thing here as well.

**Comment by Horneth** [comment]
The 10K call caching run revealed that we still spend a lot of time doing in this area, even with scheduled time based calls to `runnableCalls`.

![screen shot 2017-04-19 at 2 09 51 pm](https://cloud.githubusercontent.com/assets/2978948/25194952/1bd7ee2e-250a-11e7-9eff-cef3b3f78c4f.png)

**Comment by Horneth** [comment]
I'm looking at ways to reduce that
