### ISSUE TITLE
Feature Request: Splitting an intervals file

### ISSUE THREAD

**Issue by knoblett** [broadinstitute/cromwell#1605]
A user had the below features request, which I agreed to pass on to you here. 

> It would be nice to have a setting where the user could choose to automatically split an interval file into contigs, or an arbitrary number, for the scatter gather process. I'm sure there are more optimal ways to split interval files, I think I saw in your example script on your github that you chose to split your interval list into 50 pieces due to your local server setup? Not every user is able to optimize an individual analysis, so having the option to automatically split the interval list into contigs is probably better than running it serially. We will probably set up a bash script for it, but having it built in could be usable for others too.

**Comment by cjllanwarne** [comment]
Am I reading correctly that this is a change to the example WDLs?

I would be very skeptical of adding filetype-specific manipulations into the Cromwell engine.

**Comment by kcibul** [comment]
@geoffjentry -- to put this in your head

Let's not jump to it being an engine feature.  But I think the point here is a good one.  

I think this, and other use cases, might be best met by a set of "built-in" tasks that cromwell could come with.  For example, through the use of imports and having cromwell released with a equivalent of "genomics-stdlib" we could provide genomics specific manipulations as tasks.  This solves the problem of the user having to write them themselves.

Then through the use of smart multi-backend support we could also have some of these stdlib tasks run on the same machine as cromwell.

This requires a bunch of advances to the engine, but I think it's where we can provide a lot of value to the users.

The first step in this could be having Kate & Crew (along with our help) publish that "gatk-stdlib.wdl" that performs these functions and people could import.  Then if that is successful we could see how we would best provide that sort of support in a batteries included fashion.

**Comment by geoffjentry** [comment]
@kcibul I like that idea. Also agree that the first step would be WDL of useful (both in end functionality and generic enough to be generally useful) tasks. It'd be easy to embed them into Cromwell at that point.

**Comment by katevoss** [comment]
If I understand this correctly, the user wants a way to automatically include an intervals file for certain tasks, right? @knoblett do you have any more details about specific tasks or situations when the user would want this? 
@kcibul is it genomic intervals, say for joint calling, or is it programmatic intervals to help with scatter/gather?

**Comment by kcibul** [comment]
It's just that people often have a big list of intervals (e.g. the exome intervals are ~200,000 intervals).  Then they want to scatter to VMs based on that interval list, but it's not 1:1.  They want 50 or 100 shards.  So the work of taking that one file, and splitting it into 50 or 100 files is I think what's being talked about here.

You can (and people do!) accomplish this today by writing a task that does some python to chop up the file and then feed that array of files into a scatter.  It's just such a common operation that it would be helpful to make it easier for people

**Comment by ruchim** [comment]
I recently went through a scenario where there were two ways of combining a long list of intervals into 50 scatters -- depending on whether the actual intervals were contiguous or not--though its uncommon for them to be contiguous. My point is -- there are going to be times where it wont be obvious how to combine intervals ---I feel it may be best to publish an explicit task, and let users customize

**Comment by gemmalam** [comment]
This issue exists in Jira now. Please add any new comments to this link https://broadworkbench.atlassian.net/browse/BA-1605
