### ISSUE TITLE
embiggen texty columns

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1607]
Joel attempted a 0.19 -> 0.21 migration on a Firecloud dev database and hit an overflow migrating call outputs:

```
Oct 20 19:11:12 gce-cromwell-dev203 docker/cromwell-app[5085]: Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changesets/metadata_migration.xml::call_output_symbol_table_migration::tjeandet:
Oct 20 19:11:12 gce-cromwell-dev203 docker/cromwell-app[5085]:     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Could not apply migration script for metadata at CallOutputSymbolTableMigration
.
.
.
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'METADATA_VALUE' at row 1

```

This column is currently of type `TEXT` which has a size limit of 2^16 bytes.  Perusing the MySQL docs I see that `MEDIUMTEXT` supports 2^24 bytes and `LONGTEXT` supports 2^32 bytes, and these consume only 1 and 2 additional bytes over `TEXT` respectively.

Looking at our DB schema I'm also noticing that 

`CALL_CACHING_DETRITUS_ENTRY.DETRITUS_VALUE` has type `VARCHAR(255)`

which I could see ending badly with long GCS paths.

**Comment by kcibul** [comment]
... in addition to fixing this in develop, this should be backported to 0.21

**Comment by helgridly** [comment]
👍 for the naming of this ticket
