### ISSUE TITLE
Filename WDL function

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1608]
Currently to extract the name of a file from a WdlFile value, one needs to use the sub method with the right regexp.
This seems unnecessary complicated for a case as simple and frequent as getting the name of a file.
If not a function it could at least be an example of how to use the sub function in the docs.

**Comment by kcibul** [comment]
Can you update the issue with an example of what you want to do, using the regex?

**Comment by Horneth** [comment]
Yes, this comes from a user trying to run a very simple wdl, but because of the way localization / docker / path transformation works in cromwell something like that doesn't work:

```
task foo {
  File myinputfile # let's say this is /Users/me/myfile.txt

  command {
    dosomething -using ${myinputfile} > ${myinputfile}.samples
    // evaluates to dosomething -using  /Users/me/cromwell_executions/.../inputs/Users/me/myfile.txt > /Users/me/cromwell_executions/.../inputs/Users/me/myfile.txt.samples
   }

   output {
     File out =  ${myinputfile}.samples # this doesn't work because myinputfile resolves to /Users/me/myfile.txt.samples
   }
}
```

Now that I write this I realize that maybe the real issue is actually fixing the above behaviour ?

Regardless, what the user really wanted to do here is write the output of his command to a file having the same name as his input file + ".samples", which it turns out is a lot more difficult than it should.

**Comment by cjllanwarne** [comment]
Duplicated in #2235, fixed in https://github.com/broadinstitute/wdl4s/pull/109

**Comment by vdauwera** [comment]
Documented in https://software.broadinstitute.org/wdl/documentation/article?id=10554
