### ISSUE TITLE
Investigate File Hashing Strategy for JES Backend

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1623]
From @jsotobroad

Even though getting MD5 from GCS is fast for call caching, when you do 20k of these it does take a bunch of time.  Would it be possible to adopt a strategy like the "File" hashing strategy if the user wanted?

from Kris: especially for interior (e.g. from another task) inputs where we can be confident it hasn't been fiddled with

from @cjllanwarne : question: since call caching actually copies files, it's the MD5 we really need because we copy outputs around

**Comment by cjllanwarne** [comment]
NB: s/MD5/CRC32C/g

**Comment by geoffjentry** [comment]
@kcibul I'm advocating that this earns the `scalability` label but leaving it up to you

**Comment by katevoss** [comment]
Linking to #901

**Comment by katevoss** [comment]
@kcibul with the 20k genomes complete, would you say slow hashing is still a problem?

**Comment by kcibul** [comment]
agreed -- closing!
