### ISSUE TITLE
Propagate workflow labels to JES

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1624]
JES now allows for labels to be applied to pipeline runs.  Labels are important because they allow us to tag pipeline tasks with metadata which is exposed in other Google APIs, specifically in billing exports that are visible in BigQuery.  This will allow us to, for example, calculate the exact cost of a pipeline run which is immensely important for FireCloud and @abaumann 

The changes to the pipelines API are described here:

https://cloud.google.com/genomics/reference/rest/v1alpha2/pipelines/run#RunPipelineArgs.FIELDS.labels

Cromwell should propagate the workflow level labels to the JES calls for downstream use.  According to Google, we should be able to see these labels right away in the operations metadata

**Comment by abaumann** [comment]
I agree that this is important to me

**Comment by kcibul** [comment]
@cjllanwarne
