### ISSUE TITLE
End-to-End Support for Workflow Labels

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1625]
Overall epic providing support to add labels to workflows, use those labels in the various APIs, and have them propagate to Google

**Comment by katevoss** [comment]
Most of these issues are complete so I am going to add the remaining one, #637, to the [Abort Spec](https://docs.google.com/document/d/1B0FElJXOp4IP-v24C62CLsC0JQMbQPjaIrjOwnDqko8/edit).
