### ISSUE TITLE
Support retrieving workflow labels in metadata API

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1626]

**Comment by cjllanwarne** [comment]
Is there something more to this than just adding labels into the metadata in #635 ?

**Comment by kcibul** [comment]
probably not!  Should be pretty straightforward

**Comment by cjllanwarne** [comment]
As of https://github.com/broadinstitute/cromwell/pull/1834, we can find user-supplied custom labels in the metadata but not yet JES backend's auto-generated ones.

**Comment by erichpeterson** [comment]
Need this! :+1:

**Comment by ruchim** [comment]
Completed as a part of https://github.com/broadinstitute/cromwell/pull/2253 and https://github.com/broadinstitute/cromwell/pull/2357
