### ISSUE TITLE
Standard library support for reading outputs from task generated JSON file

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/cromwell#1628]
This is a continuation of a discussion from the Forum (http://gatkforums.broadinstitute.org/wdl/discussion/8454/feedback-on-initial-version-of-bcbio-wdl-converted-from-cwl) with @kcibul and @geoffjentry

It would be useful to have functionality in the standard library to be able to read outputs from a file generated by a task. This is based on transitioning from CWL, where your task can generate an output that looks like:

```
{
    "region": "chrM:0-1000", 
    "vrn_file_region": {
        "class": "File", 
        "path": "/var/spool/cwl/gatk-haplotype/chrM/Test2-chrM_0_1000.vcf.gz", 
        "secondaryFiles": [
            {
                "class": "File", 
                "path": "/var/spool/cwl/gatk-haplotype/chrM/Test2-chrM_0_1000.vcf.gz.tbi"
            }
        ]
    }
}
```

then WDL could ideally define a way to read the outputs from this file:

```
    output {
        File vrn_file_region = read_cwl_json('cwl.output.json', 'vrn_file_region')
        String region = read_cwl_json('cwl.output.json', 'region')
}
```

Synchronizing with CWL would help with CWL/WDL interoperability but other ways of supporting this that are easier/more workable with WDL would also work great. Thanks for considering this.

**Comment by geoffjentry** [comment]
Closing this - ultimately this would be a ticket for OpenWDL
