### ISSUE TITLE
Store the hashes of workflow inputs at submit time and make them retrievable

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/cromwell#1629]
For FC provenance tracking we need to keep an eye on the file hashes of workflow inputs. My understanding is that call-caching stores the CRC32c of each _call_ input, but it's difficult to trace those hashes back to workflow inputs.

Could you store the hashes of workflow inputs at job submit time and throw them in the workflow metadata?

Ping @abaumann for prio but I don't think it's super urgent.

**Comment by abaumann** [comment]
Not super urgent, but yes I agree.  Ideally we would have access to each of the hashes that get hash cached so we could compare them later to see if things changed (i.e. file hashes, other input hashes, docker image hashes, etc)

**Comment by geoffjentry** [comment]
Playing ye olde advocate of the devyl here.

Outside of "firecloud would love to be able to look up this information somewhere" is there a more general application for this behavior in Cromwell? Let's suppose hypothetically the answer is "No, that makes no sense outside of the context of Firecloud", why would Firecloud not generate and store that information themselves? If in fact the answer is "yes" the whole line of questioning obviously goes away.

(Full disclosure, I *think* the answer is 'yes' but I'm not sure)

**Comment by abaumann** [comment]
The use case in Cromwell is the same as FireCloud - Cromwell now will use cached data if it exists, and not if it doesn't, but you can't tell why it wasn't in cache when you expected it to be.  People could do forensics themselves, but if we had this stored and accessible you could quickly see "the docker image changed" or "the file changed".

**Comment by katevoss** [comment]
@abaumann does the [call caching diff endpoint](https://github.com/broadinstitute/cromwell/blob/develop/README.md#get-apiworkflowsversioncallcachingdiff) help with this situation? If not, can you explain further what you're looking for?

**Comment by abaumann** [comment]
I believe it does now cover it since you can see the difference in hash per input and trace that back to a change in the contents of a file (however you might not be able to tell difference between different file path to same input vs same file path with different file contents, but you can tell it's a different file path from the inputs that were used, so I believe you have enough info to make this call).

Unless @helgridly can think of something this isn't covering

**Comment by helgridly** [comment]
Yeah I suspect that's most of what we need. I can't think of any use case for this beyond that, but this was also forever ago and that particular Hussein is long since dead.
