### ISSUE TITLE
Boolean default value overrides value in input file

### ISSUE THREAD

**Issue by adamstruck** [broadinstitute/cromwell#1632]
Using the 0.22 release jar

The default value of a Boolean variable is always used regardless of what is passed in the inputs file. 

WDL:

```
task test {
  File testFile
  Boolean long = false

  command {
    ls \
    ${true='-l' false='' long} \
    ${testFile}
  }

  output {
    File foo = stdout()
  }

  runtime {
    docker: 'ubuntu:14.04'
  }
}

workflow run {
  call test
}
```

inputs:

```
{
  "run.test.testFile": "/tmp/tmpfile",
  "run.test.long": true
}
```

Results in the command:
`ls /tmp/tmpfile` rather than `ls -l /tmp/tmpfile` as expected.

Additionally, if I try to specify a default value for a Boolean `${true='-l' false='' default=true long}`, this translates to 'true' being passed in to the command line rather than '-l' as expected.  It also doesn't seem to matter if I pass the default as a string or boolean.

**Comment by adamstruck** [comment]
FYI - I can workaround this issue if I make the Boolean optional. In this case the false option is used by default.

**Comment by katevoss** [comment]
@adamstruck this is actually intended behavior, when you include `Boolean long = false` it is hardcoding the value of `long` as `false`. You are correct that to make this into a configurable value that you should make the Boolean optional.
