### ISSUE TITLE
Support copying subsets of output files to different locations

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1642]
We would like one of our WDL pipelines to be able to deposit its workflow outputs in two different locations.  For our purposes, all the output files go to one location or the other and none go to both.  It would be helpful if we could provide Cromwell's copy outputs function with a map of what outputs go where.  Depending on how its implemented, this could also be the solution for https://github.com/broadinstitute/cromwell/issues/1641.

**Comment by katevoss** [comment]
@ktibbett I finally have time to follow up on this, can you explain more about why you want the WDL pipeline to copy workflow outputs into two locations?
How often do you face this problem? Is it a weekly/daily/monthly thing?

**Comment by ktibbett** [comment]
@katevoss , this is a hundreds-of-times-a-day issue :)  Our principal workflow produces two different types of files that we store in different locations.  So this would be a great help.

We were talking about this just today, and I'm wondering if this could be managed with subworkflows.  Can a sub-workflow copy its own outputs to a separate location?  That would (for our purposes at least) do the job.

**Comment by katevoss** [comment]
@ktibbett Unfortunately subworkflows cannot copy outputs to a separate location.

@geoffjentry what would estimate the effort to put this in place? GOTC wants to get rid of their Zamboni-based workaround for copying files to different locations. As Kathleen noted, this is related to #1641 .

**Comment by geoffjentry** [comment]
Is "this" the original topic or subworkflow?

**Comment by katevoss** [comment]
"This" is the original topic, copying outputs to different locations. It could be a way to "flatten" directories. However, as you noted on the [other issue](https://github.com/broadinstitute/cromwell/issues/1641), there is the risk of overwriting results.

**Comment by geoffjentry** [comment]
It looks like it'd be pretty straightforward to do, but would need answers to questions like "what happens if the outputs in the map don't match the actual outputs"?

**Comment by geoffjentry** [comment]
@ktibbett While doing some spring cleaning we came across this. We're assuming you've long since worked around this issue and don't care anymore. If you'd still like to see this done at some point please feel free to reopen
