### ISSUE TITLE
Cannot automatically kill SGE jobs through cromwell when I terminate the workflow in single workflow mode

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1645]
- SGE backend
- single workflow mode

When a user ctl-C the cromwell process, all of the  SGE jobs are still running.  And now the user has to kill the jobs manually.

Apologies, if you can do this and I just forgot.

**Comment by kshakir** [comment]
I believe that this was a case of `abort-jobs-on-terminate` not being set. The default has changed in #1664, so one shouldn't have to opt in to this.
