### ISSUE TITLE
Create a standard docker build process for cromwell

### ISSUE THREAD

**Issue by hjfbynara** [broadinstitute/cromwell#1654]
Standardize docker builds with git commits.  Automatically build docker images and push to the cromwell docker hub when certain commits occur on certain git branches.  A suggested tagging scheme in docker could be:
     <Cromwell-version>-<git-commit-hash>

For example:  0.21-5273abb  This not only informs you what major cromwell version it is but also the specific git hash.  And this tag would pretty much not ever move.

Additionally a moving tag could be built with just the <cromwell-version> (ex. 0.21)  This will always be the most recent commit for that version.  And of course it will be updated each time.

Tasks

- [x] change docker image labeling to be <version>-<git-commit-hash> in Settings.scala
- [x] change .travis.yml to run 'sbt dockerBuildAndPush' as part of the after_success step (confirm that is the right place
- [x] manually publish the docker image for the 0.21 latest release (ie checkout, sbt dockerBuildAndPush).  
 - [x] also tag ^^ with 0.21
 - [x] at this tagging step to our release process document
 - [x] tell @hjfbynara and @abaumann about ^^

**Comment by kcibul** [comment]
Hi Henry -- I'm not sure if this ticket is about changing the current sbt docker command (I don't think so?) or more around devops/jenkins changes to run that regularly and do the push to dockerhub.

Let's discuss with @geoffjentry and @ruchim with faces

**Comment by davidbernick** [comment]
Hi @kcibul it's about consolidating all of our various devops-y things into a more unified manner. Ideally we'd like to have the Push To DockerHub wrapped into our Jenkins. @hjfbynara can explain more, but from a strategic point, unifying how we move our Dockers around is a good thing, particularly for security and accountability. You can all meet but we're trying to make our DevOps work more unified. Please find me for this meeting.

**Comment by kcibul** [comment]
closing per alex (who is present) and herny in abstensia
