### ISSUE TITLE
Wide scatter led to wide array of issues

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1662]
I ran the WDL at the bottom of this issue using mock-jes. Initially it ran everything but then got stuck in a state with 2 jobs left and the 1 wf still "running". I looked and those 2 jobs had had 500 errors associated with them. 

At a later point I restarted Cromwell, for a long (> 10 mins) period of time the stats endpoint was unresponsive although other endpoints were fine. After some period of time (< 1.5 hours) I came back and those 2 jobs had completed but the WF was still stuck as Running.

task snooze {
  command {
    sleep 10 && ps > myfile.txt
  }
  output {
    File procs = "myfile.txt"
  }
  runtime {
    docker: "ubuntu:14.04"
    preemptible: 3
    cpu: 10
  }
}

workflow one_step {
  Array[Int] integers = range(20000)
  scatter(i in integers) {
    call snooze
  }
}

**Comment by geoffjentry** [comment]
The 0 jobs is incorrect and is an artifact of there being no EJEA for them

**Comment by seandavi** [comment]
What is mock-jes?  Just curious.

**Comment by geoffjentry** [comment]
@seandavi Ah, it's something @kcibul whipped up which runs on google app engine which presents the JES API for trivial tasks - we've been using it to be able to run things which test the cromwell engine under load w/o having need to run up a large bill (or run into quota issues!) on JES.

I've been starting to use it heavily and have run into some weird issues, such as this ticket and those unexpected actor death notifications from the other issue. I've been theorizing that they're due to responses from appengine which we don't see in JES but i need to verify that - and clearly that's not the case w/ the unexpected actor death ones.

**Comment by geoffjentry** [comment]
Forgot to update this. I'm fairly certain of two things:

- This is an artifact of using mock jes
- There's a subtle bug somewhere

I've not been able to replicate this. I'm still not sure *what* happened exactly nor why but I will jot down what I saw in case this comes up again. There were 2 jobs out of the 20k scatters which found their way back into the engine with FailedRetryable errors. In the code there are only 2 places where those are created and both involve preemption. On the engine side at the moment there's a direct assumption when this happens that the job was indeed preempted. I'm not certain how exactly this led to wacky behavior (and admittedly don't completely remember the details) but it appeared that the original "preempted" jobs did in fact complete and the preempted jobs never ran.

In the DB the errors were CromwellFatalErrors w/ 500 messages in them. This should be impossible considering that when these FailedRetyrable things are created they're stuffed with a preempted error.
