### ISSUE TITLE
Cromwell and rate limits when running on JES

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1663]
How does Cromwell deal with rate limits on JES?  I have some largish batch jobs that seem to result in triggering JES (google genomics api) rate limits when submitted via Cromwell.  Is Cromwell robust to this?

**Comment by geoffjentry** [comment]
Yes. How it gets handled depends on what version you're using. Up until recently (I believe 22) would see the rate limit notification and just retry it. The latest version changes how we poll JES in that it is sending bulk requests over. The rate at which that happens is designed to stay below the rate limits, although if something were to still happen it'd just go back to the previous behavior and retry it.

**Comment by seandavi** [comment]
Great.  Thanks, @geoffjentry.  That is exactly what I wanted to hear.
