### ISSUE TITLE
Allow user-defined labeling or tagging of jobs

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1666]
Just a feature request (not a roadblock to anything we are doing), but it would be useful to be able to track a batch ID when submitting batch jobs.  Batch jobs are often a set of related jobs that can be thought of as a logical unit.

**Comment by geoffjentry** [comment]
@seandavi To throw out another possibility would you be just as (or even more) happy w/ user defined labeling? We've discussed both and personally I've been leaning towards the latter as it seems like it could cover the former and is more flexible.

Either way it might be a bit (or not, one never knows) - the reason this doesn't currently exist is our one primary internal use case for batch submit is firecloud and they're already managing logical collections of workflows using their own data model, so one batch submit might represent multiple logical collections.

**Comment by seandavi** [comment]
User-defined labeling was actually my first thought, so yes!  I also understand how a very thin layer on top of Cromwell could serve a similar purpose.  As I said, just a suggestion, but I like your redefinition of the problem.

**Comment by geoffjentry** [comment]
Cool, tagging @kcibul so he sees this is here

**Comment by katevoss** [comment]
This should be complete as of Cromwell 25.
