### ISSUE TITLE
LSF support?

### ISSUE THREAD

**Issue by ink1** [broadinstitute/cromwell#1667]
Hi, can someone please clarify on LSF support?
It was introduced in 0.19 hotfix,... then it came back again.
But it does not seem to be in the main branch e.g. in the current development branch.
Apologies if I've missed something obvious.
Thanks

**Comment by geoffjentry** [comment]
Hi -

It's there but apparently un(der?)documented. 

Could you please ask this question on [the main user support forum](http://gatkforums.broadinstitute.org/wdl) and they'll provide the information that you need.

**Comment by kshakir** [comment]
The "intro" docs are [here](https://github.com/broadinstitute/cromwell/tree/0.22#sun-gridengine-backend), but as mentioned the main user support forum is probably the best bet for further discussion.

Quick answer: Post 0.19, LSF, Grid Engine, and Local were all merged into a single backend for anything (PBS, Torque, etc.) that uses command lines to dispatch jobs over a shared file system.

**Comment by ink1** [comment]
Thanks! Will try the forum
