### ISSUE TITLE
Misconfigured Permissions causes silent death

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1669]
This sucked up a few hours of time with the debugger, we need a better error message/handling.

If you misconfigure Cromwell (in my case using a service account) whereby the auth specified in JES.filesystems.gcs.auth is unable to write to the bucket specified in JES.config.root.

Specifically, I found that the uploadCommandScript was dying silently in the JABJEA and my workflow just stopped running

**Comment by cjllanwarne** [comment]
Did you see that "token reclaimed" message or not?

If not, we might also want to add some deathwatching around the JABJEA so that at least we don't run forever if it crashes

**Comment by vdauwera** [comment]
@kcibul Is this still a thing?

**Comment by katevoss** [comment]
Following up with @kcibul again, is this still a problem?

**Comment by mcovarr** [comment]
IMHO since the instructions to reproduce this are so clear it might be more appropriate for us to check this rather than putting that on @kcibul.  It might even be something for the current bug rotation person to look at... 🙂

**Comment by mcovarr** [comment]
I am happy to report that Cromwell now fails spectacularly, not silently.

**Comment by katevoss** [comment]
Wohoo!
