### ISSUE TITLE
Call caching has issues on symlink mode if data is gone

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1671]
Reported by @fleharty - it appears that when call caching in symlink mode if the real file no long exists the caching will not fail. 

Regardless of the mode we should be robust to cases where we're attempting to call cache but the underlying data is not there

**Comment by cjllanwarne** [comment]
Fixed

**Comment by fleharty** [comment]
Was this fixed?

**Comment by fleharty** [comment]
@cjllanwarne  Woot!
