### ISSUE TITLE
start & end timestamp strings in metadata use non-standard timezone format

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1672]
Example of what appears in metadata:
```JSON
{
  "end": "2016-11-15T13:35:52.416+10:00",
  "start": "2016-11-15T13:27:31.092+10:00"
}
```

The `+10:00` on the end is neither a "general time zone" format:
`GMT+10:00`
(includes the GMT)
nor RFC822 format:
`+1000` 
(no colon between hrs & mins)

which makes it non-easy to parse these things into Date-like objects.

**Comment by kshakir** [comment]
The format is ISO 8601, generated by Java 8's OffsetDateTime:

- https://en.wikipedia.org/wiki/ISO_8601
- https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html

**Comment by delocalizer** [comment]
apologies; I'm obviously stuck in the past (of Java, anyhow)! :smiley:
I'll take ISO 8601 standard over the other two anyday
