### ISSUE TITLE
Scriptify repeated portions of the release process

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1673]
Source: https://broadinstitute.atlassian.net/wiki/pages/viewpage.action?spaceKey=DSDEEPB&title=Cromwell+Release

There are specific portions in the Cromwell Release checklist that are common among all the repos and can become reusable/composable step in automating the Cromwell release. Turn those steps into an executable script.

repos = [wdltool, lenthall, wdl4s, cromwell]

- [ ] Run tests locally on develop to ensure tests still pass
- [ ] Ensure the build.sbt file has the correct version. If it does not, adjust it, commit and push to develop.
- [ ] Merge develop into master.
- [ ] Tag the resulting merge commit on master with the version number (e.g. 0.10,1.2.0)
- [ ] git push origin master
- [ ] git push --tags
- [ ] This should kick off the travis build of the tag. Ensure that it completes successfully.  This job should also produce a JAR in artifactory: https://artifactory.broadinstitute.org/.  Ensure that this JAR exists. For example for wdl4s it would be in: libs-release-local/org/broadinstitute/wdl4s_2.11
- [ ] On develop, update build.sbt with the next version number

**Comment by ruchim** [comment]
Assigning to @kcibul for prioritization.

**Comment by kcibul** [comment]
Let's put this to the top!

**Comment by katevoss** [comment]
This is completed per the connected PR.
