### ISSUE TITLE
Support additional terminal status(es) in Cromwell

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1677]
It would be very helpful to be able to distinguish between workflows that are failed and under investigation (possibly to be started again) and workflows that are failed in a more permanent way -- ones that have been investigated and need not be looked at further.  Some additional terminal status, such as "ABANDONED," that would help us make this distinction, would be very useful.

**Comment by katevoss** [comment]
This is related to Custom labels (being able to apply and update them at different times in the workflow) and custom retry strategies, #1847 & #2253

**Comment by katevoss** [comment]
@ktibbett I believe this is fixed now that custom labels are implemented. Is there anything remaining here?

**Comment by ktibbett** [comment]
@kbergin : was the plan for "archiving" in JobManager to leverage labels?

**Comment by kbergin** [comment]
Yes @ktibbett I think the easiest way to mark jobs for follow up or to archive/abandon them would be to leverage labels as long as that still works for you

**Comment by katevoss** [comment]
Closing as fixed then, thanks!
