### ISSUE TITLE
Notes field for Cromwell workflows

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1679]
It would be helpful to have a free text field for storing notes about a Cromwell workflow.  We might use it to display this information in a UI running against the Cromwell database.  We'd need to have ways to set and retrieve this data.

**Comment by geoffjentry** [comment]
@ktibbett re "a UI running against the Cromwell database" - i would recommend *not* doing this. If there's information you can't get through the REST API I'd ask that you open tickets to provide that information via REST. I very much don't want to be in a position where we have to worry about breaking other people's tools if/when we change the DB schema

**Comment by ktibbett** [comment]
@geoffjentry , I misspoke.  We are, I believe, using the REST API for all Cromwell info and expect to continue to do that.  We will not be accessing the DB directly.

**Comment by geoffjentry** [comment]
👍

**Comment by katevoss** [comment]
@geoffjentry sounds like the workflow notes would be another endpoint, is that right? If so, what would you say the effort and risk is?

**Comment by geoffjentry** [comment]
low and low, other than "it's another thing to maintain, document, and such"

one thing i'll throw out there, one could do this if there maximum desired note size was smaller than the maximum label size. At the moment that number is 63 characters. 

Note (pardon the pun) that just increasing that limit comes with other headaches but we can wait until we go down that path before discussing.

**Comment by patmagee** [comment]
@geoffjentry Just wondering if there is is already a way to do this by using the `meta {}` object in the workflow.  

I know the meta object is not added  to the cromwell `/metadtata`, but it might be reasonable to add the `meta` to that object or includae an option for it. Alternatively at the moment it is entirely possible to use one of the WDL parsers to get this information directly from the workflow AST.

@ktibbett does your use case require different notes on each execution, or the notes unique for a workflow?

**Comment by geoffjentry** [comment]
@patmagee I'm not @ktibbett but I believe I know what she's after here (in fact I think I might have implemented the same feature for her on our previous system). Her group uses the notes field to annotate per-execution, particularly for failed runs. So if I'm an operator and see a workflow has failed I can use that to fill in some notes after investigation - that way if another operator comes and sees it they know what the real current situation is.

And if I got that all wrong correct me @ktibbett because the above thought is shaping my responses :)

**Comment by geoffjentry** [comment]
Closing this as we're using labels for this functionality
