### ISSUE TITLE
Make the github.io page not suck

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1687]
Either update it or remove it:
http://broadinstitute.github.io/cromwell/

**Comment by cjllanwarne** [comment]
Is this the new https://github.com/broadinstitute/cromwell/issues/778 ?

**Comment by geoffjentry** [comment]
huh, i could have sworn i opened this a couple of months ago but nope, it was last week. It appears to be gone now.

**Comment by geoffjentry** [comment]
Err, it actually isn't gone. I'm just going to figure out how to remove it.
