### ISSUE TITLE
Request for workflow-wide global variables

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/cromwell#1689]
Workflow-wide global variables would be useful for input parameters to the workflow that are constant across tasks e.g. reference file, reference index, gatk jar. Way things are now we have to give them as input to each task individually, which clutters code.

**Comment by kcibul** [comment]
I believe this is now live in develop after the recent merge of the wdl4s branch.  Correct @Horneth ?

**Comment by Horneth** [comment]
As far as I know it's never been tested so I told @takutosato that it probably wasn't working yet, but a quick test with something like
```
String a = "hello"

task t {
    String i
    command {
      echo ${i}
    }
    output {
      String o = read_string(stdout())
    }
}

workflow w {
  call t {input: i = a }
}
```

proved me wrong so apparently yes it's live !
