### ISSUE TITLE
Can we have a version endpoint?

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/cromwell#1694]
As a user I would like:

- [ ] an endpoint (/version) which returns metadata about the current version of cromwell.  Currently just the version of the server, but if/when we have WDL versioning it should include that as well
- [ ] the same information available from a command line option (version)

--- Original -- 
That returns the versions of Cromwell / WDL / etc.

Ultimately we want to bubble this up to users in FC.

**Comment by ruchim** [comment]
assigning to @kcibul for prioritization.

**Comment by mcovarr** [comment]
It would be nice to have this information available from the command line too, i.e. a -version flag that dumps the version/hash and exits.

**Comment by kcibul** [comment]
great idea!

**Comment by ruchim** [comment]
@kcibul do we need this endpoint in 23_hotfix as well? Currently the PR is against develop.

**Comment by kcibul** [comment]
Nope -- it'll be part of 24
