### ISSUE TITLE
cpu (and other Int type) runtime attribute not evaluated as expression in configurable backend

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1702]
Following the docs at https://github.com/broadinstitute/cromwell#runtime-attributes, I'd like to be able to pass runtime attributes as the inputs to a task, for example:
```
task iRun {
    String runtimeMemory
    Int runtimeCpu
    command {
        echo "so far away"
    }
    output {
        String out = read_string(stdout())
    }
    runtime {
        memory: runtimeMemory
        #cpu: runtimeCpu
    }
}
```
When using a configurable backend, I can confirm this works for the String type attribute `memory` but not the Int type `cpu`: running the above with the cpu runtime attribute uncommented I get this in the logs:
```
[ERROR] [11/24/2016 10:49:13.299] [cromwell-system-akka.dispatchers.engine-dispatcher-22] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor Workflow beb03899-5f22-4f2c-8a85-d619a2d8a969 failed (during InitializingWorkflowState): java.lang.IllegalArgumentException: Task iRun has an invalid runtime attribute cpu = runtimeCpu
```

My custom backend application.conf section: 
```
PBS { 
  actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
  config { 
    runtime-attributes = """
    Int cpu = 1 
    Int memory_mb = 1000
    String? pbs_email
    String? pbs_queue
    String  pbs_walltime = "1:00:00"
    """
    ...
  }
}
```

I thought it might be because of the special nature of the `cpu` runtime attribute, but I tested with a different custom runtime attribute `Int pbs_cpu` and got the same result, so my guess is that it's the Int type that is the problem.

I am working around this by defining `String pbs_cpu` which is then interpreted as an expression in the runtime block, as documented, but it feels wrong because the value should really be validated as an Int.

**Comment by delocalizer** [comment]
I should have said, this was running with release 0.22

**Comment by katevoss** [comment]
@geoffjentry is it still the case that cpu and other Int type runtime attributes are not evaluated as expressions?
@delocalizer are you still coming across this problem? Or were you able to find a workaround?

**Comment by delocalizer** [comment]
@katevoss I've re-tested with release 29 and this works as expected now — and may have been working for some time, I haven't revisited this for a while. Thanks to all for the fix.
