### ISSUE TITLE
Support re-running a task with modified resources

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1729]
Aberrant data sometimes requires our pipelines to run with much more memory than is required in the normal case.  It would be helpful to have some mechanism to support automatically re-running a task with more memory (or other resources) if it fails for certain reasons -- e.g. if we knew that the task failed for OOM, we would want to try again with double the memory, perhaps more than once (up to some set threshold of attempts or total memory).

**Comment by katevoss** [comment]
Use case for custom re-try strategies, #1847
