### ISSUE TITLE
Documentation bug for MySQL

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1730]
If you use the example in the docs at https://github.com/broadinstitute/cromwell#database

you'll get a warning:

`Move the configuration directly under the 'database' element, and remove the key 'database.config'.`

The docs should be updated

Below is the config given in the readme

database {
  config = main.mysql

  main {
    mysql {
      db.url = "jdbc:mysql://localhost:3306/cromwell"
      db.user = "root"
      db.password = ""
      db.driver = "com.mysql.jdbc.Driver"
      db.connectionTimeout = 5000 # NOTE: The default 1000ms is often too short for production mysql use
      driver = "slick.driver.MySQLDriver$"
    }
  }

  test {
    ...
  }
}

**Comment by ruchim** [comment]
Fixed by #1731
