### ISSUE TITLE
version scheme

### ISSUE THREAD

**Issue by ilovezfs** [broadinstitute/cromwell#1736]
Is the version scheme intentionally being changed from

0.20, 0.21, 0.22, ...

to 23, 24, .... ?

**Comment by geoffjentry** [comment]
Yes it was. There was internal debate on how to handle version numbering in general and dropping the 0. Was the simplest path to our original intention (plus matched how they were colloquially referred to)

**Comment by ilovezfs** [comment]
@geoffjentry Cool, thanks for clearing that. I'll merge 23 to Homebrew now.

**Comment by geoffjentry** [comment]
Oh great, thanks!
