### ISSUE TITLE
Incomplete files on local (all SFS?) being pulled in by the engine

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1746]
We've noticed recently in the centaur local travis builds that things are failing here and there and the reason appears to be that output files for jobs are not fully written prior to the engine reading them.

There's been some speculation that this could be a file flushing issue however this is now happening far more frequently than I'm comfortable handwaving and if it turns out to be a more general (i.e. non-travis) issue this could be *really* bad for users. In particular this could be related to using docker.

Try to get more information that we can use to further diagnose. 

Some things to investigate:

- If we remove the dockers (at least the ones which make sense) from the wdls does the problem go away entirely?
- If it does still remain, does it happen running on our local unix environment? Obviously that can only apply if the dockers are removed
- If one were to run centaur local on their machine oodles of times does this problem ever occur?

**Comment by katevoss** [comment]
@geoffjentry seeing as this issue is old but sounded rather urgent, I'm guessing that this has been resolved. If not let me know and I'll reopen.

**Comment by mcovarr** [comment]
This hasn't been truly cleanly fixed but I'm not sure a true clean fix is possible.  This is the reason for that "script epilogue" stuff that invokes various Unix spells in a desparate attempt to make sure data is flushed to disk before the job completes.  

I'm fine with this being closed as I don't expect any activity on it in the forseeable future.

**Comment by geoffjentry** [comment]
@katevoss & I were just chatting w/ faces w/ the same content
