### ISSUE TITLE
Investigate dispatcher tooling in lightbend monitoring

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1747]
I've been complaining that monitoring doesn't provide any insight into dispatchers. I was getting ready to inquire about this and noticed this in the docs:
https://developer.lightbend.com/docs/monitoring/latest/instrumentations/akka/dispatchers.html

I believe this is (relatively) new, see what's going on here

**Comment by katevoss** [comment]
@geoffjentry Did you do anything related to dispatcher tooling for your recent Health monitoring pre-gull PR?

**Comment by geoffjentry** [comment]
No, in fact we're not going to be using this at all
