### ISSUE TITLE
Document that concurrent-job-limit is available on all backends

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1751]
Quoth the CHANGELOG.md:

>You can now limit the number of concurrent jobs for a backend by specifying the following option in the backend's config stanza:
```
backend {
  ...
  providers {
    BackendName {
      actor-factory = ...
      config {
        concurrent-job-limit = 5
```

But this is not generally true.  The implementation in `BackendLifecycleActorFactory` defaults to an infinitely large job limit and does not look for this `concurrent-job-limit` configuration setting.  `ConfigBackendLifecycleActorFactory` overrides this behavior to be consistent with CHANGELOG.md, but no other backend factory does.

**Comment by katevoss** [comment]
This sounds like a job for our documentation, or is there development work necessary?

**Comment by mcovarr** [comment]
Having the documentation be consistent with reality would be preferable to the current situation, but it would be even better if our backends generally honored this.  I'm not sure how much work that "better" solution would be.

**Comment by katevoss** [comment]
@kshakir Per https://github.com/broadinstitute/cromwell/pull/2547, I believe that concurrent-job-limit is now available on all backends, so this issue is null and void. Correct?
