### ISSUE TITLE
API batch endpoint: support for imports?

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1753]
Currently only the `workflows/:version` endpoint supports `wdlDependencies`; can we have it for `workflows/:version/batch` too? We love imports and we love the batch endpoint :smile:

**Comment by cjllanwarne** [comment]
Is this a question or a bug report? As far as I know this does already work (as of release 23). Maybe it missed the changelog though?

Check out the wdlDependencies field of the batch endpoint.

**Comment by delocalizer** [comment]
I thought it was a feature request (wdlDependencies isn't a documented field for batch endpoint in the README.md) but if you're expecting that it should work, then it's a bug report - because if I submit to `:version/batch` with `wdlDependencies`: 
```
curl http://bionode05/cromwell/api/workflows/V1/batch -FwdlSource=@test.wdl -FworkflowInputs=@test.batch.inputs -FwdlDependencies=@dependency.wdl.zip
```
I get a failed workflow with the following metadata:
```
{
  "submittedFiles": {
    "inputs": "{\"test.foo.showIt\":\"that\"}",
    "workflow": "import \"dependency.wdl\" as dependency\n\nworkflow test {\n\n\tcall dependency.foo\n\n}\n",
    "options": "{\n\n}"
  },
  "calls": {

  },
  "outputs": {

  },
  "id": "d97a5124-0933-4243-b542-6467b496ba22",
  "inputs": {

  },
  "submission": "2016-12-08T10:21:10.205+10:00",
  "status": "Failed",
  "failures": [{
    "message": "Workflow input processing failed.\nUnable to load namespace from workflow: Failed to import workflow, no import sources provided."
  }],
  "end": "2016-12-08T10:21:16.957+10:00",
  "start": "2016-12-08T10:21:16.952+10:00"
}
```

**Comment by delocalizer** [comment]
Th handler for batch endpoint appears to be explicitly disallowing imports: 

https://github.com/broadinstitute/cromwell/blob/6a526d62556bc556d9ddcff726b8619020067f40/engine/src/main/scala/cromwell/webservice/CromwellApiHandler.scala#L70-L71

**Comment by cjllanwarne** [comment]
Oh right! Thanks for spotting this. Turns out I did all the parsing of the REST params and then threw it away at the last minute... oops!

Definitely was a bug. Thanks for fixing.

**Comment by cjllanwarne** [comment]
Note to self: should probably modify the README to include this too

**Comment by ruchim** [comment]
@cjllanwarne can we close this issue?

**Comment by delocalizer** [comment]
this is fixed and the README appears to have been be updated too
