### ISSUE TITLE
Array[Int] array = read_lines(stdout()) no longer works

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1761]
From `IntToIntArray` in the JG workflow, this was working on 23 but not 24. I chatted with @Horneth and he said it wasn't intentional so let's fix it. Presumably it's a coercion issue but unclear.

error was:

`to evaluate outputs.: RuntimeException: Could not evaluate IntToIntArray.array = read_lines(stdout())
wdl4s.util.AggregatedException: Failed to evaluate outputs.: RuntimeException: Could not evaluate IntToIntArray.array = read_lines(stdout())`

**Comment by Horneth** [comment]
@geoffjentry I just ran this on JES
```
task IntToIntArray {
    Int number
    command <<<
        python <<CODE
        for i in range(${number}):
          print(i)
        CODE
      >>>
    runtime {
      docker: "python:2.7"
      memory: "1 GB"
    }
    output {
        Array[Int] array = read_lines(stdout())
    }
}

workflow w {
    call IntToIntArray {input: number = 5 }
}
```

and got no issue. When you say it's not working on 24 do you mean develop ?

**Comment by geoffjentry** [comment]
@Horneth Errr yeah, sorry.

**Comment by Horneth** [comment]
Still worked :/
Also yours failed when trying to evaluate the outputs. So it's not necessarily a coercion problem, maybe something went wrong and stdout wasn't there, or it couldn't read it.
Could you try again ?

**Comment by geoffjentry** [comment]
Hrm, the most likely thing here then is that I misinterpreted the log and did something stupid :)
