### ISSUE TITLE
MetadataService.wdlValueToMetadataEvents enormous bottleneck for large outputs

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1776]
For large output arrays this can get really bogged down as it's processing single threaded. At first glance it looks like it should be monoid-y, perhaps we can farm this out to multiple workers?

**Comment by Horneth** [comment]
I'll just throw out there the scala `par` collection again even, if I know @geoffjentry doesn't like it :p, I think it could be a cheap way to at least test if parallelization does improve speed significantly.

**Comment by geoffjentry** [comment]
@Horneth True, I can set that up quick to see how it goes. 

If it does go well, this might end up being a good simple use case to start rolling w/ streams: https://groups.google.com/forum/#!topic/akka-user/v01YeU6Zb-o

**Comment by geoffjentry** [comment]
Looks like that link I posted might be outdated. Based on reading last night it looks like `Balance` is the right `Flow` to use here.

**Comment by geoffjentry** [comment]
I think something like this gist is the right path https://gist.github.com/geoffjentry/fa12154052f866b10c52a3994f8cddef

**Comment by geoffjentry** [comment]
Actually `mapAsyncUnordered` seems to do the trick here. Note that `mapAsync` didn't go so well, I'm betting it needs for everything to finish so that they're emitted in the same order.

**Comment by mcovarr** [comment]
Was there a specific test case for this?  I'm not sure how big is reasonably expected to work.

**Comment by geoffjentry** [comment]
Based on when I was likely using either 20k, 40k or 200k wide simple scatters and just watching jprofiler and such

**Comment by mcovarr** [comment]
On develop Cromwell running locally with local MySQL, this WDL takes about 30 seconds to write 400,050 metadata rows.  Does this need to be more performant than that?  Perhaps the problem before was a lack of batched DB writes?

```
task IntToIntArray {
    Int number

    command <<<
        python <<CODE
        for i in range(${number}):
          print(i)
        CODE
      >>>

    runtime {
      docker: "python@sha256:bda277274d53484e4026f96379205760a424061933f91816a6d66784c5e8afdf"
      memory: "1 GB"
      preemptible: 2
    }

    output {
        Array[Int] array = read_lines(stdout())
    }
}


workflow wide {
  call IntToIntArray { input: number = 200000 }
}
```

**Comment by geoffjentry** [comment]
Considering this was originally created in an investigation which led to the batched inserts you're likely correct. There's surely bigger fish to fry in this milestone even if this is still true.

I'm thinking it might be good to get a general profiling effort at high scale but that's not this ticket.

**Comment by mcovarr** [comment]
Not seeing this at current scale, closing at least for the time being.
