### ISSUE TITLE
Improve WdlGlobFiles

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1777]
Any details I provide are only definitely true w/ the jes backend, haven't looked at others but I'm assuming they're similar. Also glob processing is backend-specific which leads to further problems I'll also address. Even if other backends aren't similar I think the same problems will manifest in other ways so there should still be similarity of solution.

When a glob returns there's a FOFN on JES and that path is stored in a WdlGlobFile. In `JesAsyncBackendJobExecutionActor.postProcess` the function `evaluateOutputs` is called which effectively decomposes the `WdlGlobFile` into a `WdlArray[WdlSingleFile]` and then this array is carried around in memory in perpetuity (for the workflow). Much CPU and memory are spent for this conversion both at creation time and trying to stuff these things into the metadata service (see the very patriotic #1776). 

I'm wondering if we could do something sneaky here and maintain the `WdlGlobFile` as-is and evaluate only what's necessary when necessary. Some thoughts as examples, some are contradictory I'm sure

- Allow that `Array[WdlFile]` to have both `WdlGlobFile` and `WdlSingleFile` with the former being dynamically expanded
- When we need the full list of files for downstream tasks perhaps we can stream them somehow instead of holding in memory
- In an example like a scatter/gather perhaps we could perform the collection on the glob files themselves via merging the stored glob file
- Perhaps we could *always* store an Array[WdlFile] as a FOFN on disk?
- Presumably we'll want to always expand to the full list of single files stored in the metadata for output reporting purposes. Could we stream the strings directly (and then remove) into the DB instead of all of the multiple boxings/unwrappings/etc?

Beyond "this is all a bunch of work" some issues that pop out:

- As stated not all backends might be handling globs the same. 
- What if Backend 1 generates a `WdlGlobFile` but that gets handed to Backend 2?

**Comment by cjllanwarne** [comment]
What I thought when I read this:
 - Technically, the WdlGlobFile which is a glob specification rather than a file path. Internally the JES backend has a conversion function from (`Workflow ID`, `Call` and `WdlGlobFile(*.txt)` into a FOFN in GCS.
- If we did this, we'd probably want to split WdlGlobFile in two - a `WdlGlobFileSpec` (what we have now) and `WdlGlobResult` which holds, as you want, a concrete FoFN address.
- Assuming pluggable FSs, I think the WdlGlobResult would be much easier to wrangle across backends. (Without pluggable FSs, it's a pipe dream anyway 😄)
- !! Controversial proposal alert !! What about a full-blown FoFN as a first-class WDL type? That way a WDL author can decide when they want their globs to be exploded and when they don't?

**Comment by cjllanwarne** [comment]
Alternatively, change glob() to return `File` instead of `Array[File]` with the understanding being that it just always returns a FoFN.

**Comment by cjllanwarne** [comment]
One other comment, the FoFN made in JES contain only the relative filenames, not absolute paths.

**Comment by geoffjentry** [comment]
@cjllanwarne I'm going to take this the complete opposite direction but I'll give you all the credit as it was what you said that led me here.

Specifically it started with your statement " a WDL author can decide when they want their globs to be exploded  ..." my reaction was "hell no!" as the point here is system sanctity and not user desire. If the point is to not allow a large glob to take down a cromwell server then we should not allow users to be the ones deciding what's getting processed in a more/less efficient manner. To bend an old gem of wisdom a bit beyond its original meaning, "never trust the client"

That got me thinking that I think all of this (including my original post) is coming at this all wrong. To the WDL user they should only ever have to think in terms of `File` and `Array[File]`, but that should imply no specific implementation under the hood. I think some of this goes to how tightly coupled WDL is to implementation in Cromwell and how that fact tends to guide our thinking in certain directions.

If instead we *always* treated `Array[File]` as a FOFN behind the scenes in a completely invisible to the user manner we'd be able to keep the simplistic sugar of WDL but go even beyond glob situations when it comes to memory savings.

For obvious reasons (including your last statement and others that we both made) that wouldn't be a tiny change but I don't think it'd be monumental either.

**Comment by katevoss** [comment]
@geoffjentry @cjllanwarne what is the user story here? What are users trying to do that improving globs would help them?

Is this something users have asked for, or is it a mucky problem within Cromwell that we want to fix?

**Comment by geoffjentry** [comment]
The problem turns out to be broader than globs as joint genotyping pointed out. The way we handle large arrays, particularly large file arrays chews up a massive amount of ram- in the case of a single large workflow it can be impossible to run. In a multi tenant case it can be death by a thousand cuts. 

This will absolutely need to be improved before we get too far down the caas journey

**Comment by geoffjentry** [comment]
closing as it is so old. if it comes up again we will address anew
