### ISSUE TITLE
Retry Travis downloads

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1791]
(No links to failed builds, as clicking Travis "Retry Build" erased the logs.)

Travis has been having network errors recently attempting to download artifacts from maven central, and in at least one case downloading the ubuntu:latest docker image.

In the various scripts under src/bin/travis, the scripts should retry:

- `sbt update` before any other sbt commands
- `docker pull ubuntu:latest`
- possibly: `sudo apt-get …`

The retries should wait some time (60 seconds?) between failures, and try at least twice? Possibly this could be put into a utility bash script.

**Comment by katevoss** [comment]
@kshakir Can you tell me a bit more about this ticket? Is it still happening, or is Travis not having network errors anymore?

**Comment by kshakir** [comment]
Closing as this is not an issue recently. If it pops up again, this or a new ticket may be opened.
