### ISSUE TITLE
Add count, pagesize, and page to metadata api calls

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1793]
Currently, as far as I can tell, the paging functionality is pretty hard to use since there is no notation of the total records (given filters) available.  Returning page and pagesize or at least starting record would be helpful.  Finally, being able to do this relies some kind of reproducible ordering of records; I assume that ordering is deterministic.

**Comment by geoffjentry** [comment]
@seandavi Beyond being hard to use, does this imply you're actually using the paging? I came across a comment in the relevant code that it wasn't believed to be properly using. The one group who had asked us to put it in weren't actually using it which made the "how is it actually working" question easy to answer but this makes it look like you are as well.

**Comment by katevoss** [comment]
@seandavi I wanted to follow up on @geoffjentry 's question, are you using paging? Can you explain more how you are using it?

**Comment by geoffjentry** [comment]
When I upgraded to Akka http I found and verified that note from @kshakir that out paging "exists" but is massively broken 

Generally it is viewed as good practice to provide paging for either all or all potentially large results, this is definitely the latter and obviously the former :)

**Comment by geoffjentry** [comment]
Closing this - we're actively using paging via Job Manager UI. While there's always room to modify paging, this seems to be viable
