### ISSUE TITLE
Finding all jobs, including those submitted but not yet listed in "query"

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1794]
When submitting a large batch (at least on JES), I am unable to see all jobs using any API endpoint.  Query does not return all jobs.  The batch submission process sometimes times out.  This leaves no real way to gather a full list of submitted jobs (except, perhaps, to query the backend database directly).  First, is my explanation something to be expected?  If so, what is the preferred method to get at all the jobs that have been submitted?

**Comment by geoffjentry** [comment]
Hi Sean - the query/metadata/etc endpoints are hitting a section of the DB which is intentionally eventually consistent so there might be a gap between the time when something really happened and when it becomes visible to the outside world.

The timing out portion is troubling and I think the main issue here. @kcibul we should look into that.

Also, now that I reread what you wrote - are you saying that you're unable to get all the workflows ever or just right after submission?

**Comment by seandavi** [comment]
How "eventually" consistent should I be thinking on metadata, etc.?  Seconds, minutes, hours, longer?  The timeout at batch submission is likely a client-side thing, so we can probably ignore that issue for now.

**Comment by kcibul** [comment]
The query endpoint should return you status on all workflows filterable by
status (e.g. Running).  Is that what you're looking for?  Or is that broken
(and if so can you describe more what behavior you see)

If you're looking for call level details from that you can use the metadata
endpoint for those workflows that are running (which now has field
selectors so you can make it quite slim).

**Comment by geoffjentry** [comment]
for query I'd expect for it to typically be measured in seconds, not minutes and certainly not longer than that, it's just that we don't make any guarantee that the data is in there before we move on.

For the metadata endpoint there's a summarization process which happens (to make the response time faster) that sweeps around every few minutes (rate is configurable) and calculates the current state of the world

**Comment by cjllanwarne** [comment]
@seandavi, out of interest, how many submissions are happening all at once during the batch submit? And are you using imports?

**Comment by katevoss** [comment]
@seandavi have you noticed similar problems recently? If not I'll close this.
