### ISSUE TITLE
Possible to specify runtime config (for example, zones) in application config?

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#1795]
I haven't been able to discern from the documentation if specifying GCE zones in the application config is possible.  I see that it is listed as runtime config.  Sorry if I am misunderstanding.

**Comment by geoffjentry** [comment]
That's not currently possible, but IMO it's a good idea. 

@kcibul what do you think about having a JES configuration setting for the default zone(s) for jobs? Currently it's just hardwired to us-central1-b

**Comment by kcibul** [comment]
Yes -- this is an excellent idea!  Let's make it so

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by pgrosu** [comment]
@seandavi You might still want to stick with the `central` region (with zones `us-central1-a`, `us-central1-b`, `us-central1-c`, and `us-central1-f`) to prevent the possibility of preemption on such instances, and noted here:

https://github.com/broadinstitute/wdl/issues/64#issuecomment-263665554

~p

**Comment by geoffjentry** [comment]
@pgrosu IIRC we use `central` to avoid some of their other large customers in other zones. However note that we *are* one of their large customers so choosing the same zone as us might not be the best plan for success in avoiding preemptions :)

**Comment by seandavi** [comment]
So we need an uber api that tracks preemptions across registered Cromwell
servers and then uses machine learning to make predictions of lowest cost
configuration that meets system resources. Simple.... (joke)

**Comment by geoffjentry** [comment]
@seandavi Our ultimate goal is for Cromwell to achieve sentience - I think that will be a nice stepping stone for that march.

**Comment by pgrosu** [comment]
@seandavi You may laugh, but that is how Google data centers auto-reshape their network topology globally via software-defined networks.

@geoffjentry That brings even more opportunity of self-organization through complexity - out of chaos comes order ;)

**Comment by seandavi** [comment]
I fear for my job already!

**Comment by pgrosu** [comment]
The shoulders of giants is always a safe place :)
