### ISSUE TITLE
Optional / Array Interchangeability

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1806]
EDIT: Modified since I realised `X? => Array[X]` can be done already via `select_all`

Don't mention the M word to @kcibul!

But, we could have a functions that converts from an Array[X] to X?

One concrete benefit of `Array[X] => X?`, this would allow genuine optional outputs from tasks:
```
task optional_output {
  command { 
    ...
    # maybe make a file foo.txt
  }
  output {
    File? o = headOption(glob("foo.txt"))
  }
}
```

**Comment by Horneth** [comment]
Hmm wouldn't be easier to just allow `File? o = "foo.txt"` at this point ?
