### ISSUE TITLE
Do we care about MetadataPutAcknowledgement?

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1811]
Based on a quick search I believe these are ignored 100% of the time. Considering the enormous mass of metadata writes going on this generates a lot of messages which can wind up backing up things which are actually used.

**Comment by geoffjentry** [comment]
It's also worth noting that `MetadataPutFailed` manages to get logged both when we send it in the metadata service and where it's used, but we don't do anything other than those log messages. It seems like one would be enough.

**Comment by kcibul** [comment]
I don't think we care about the acks per-se... but we need to not lose metadata writes.  Seems like we're somewhere in the middle now?

**Comment by geoffjentry** [comment]
Writes are just super slow (as per a couple of tickets now). This is just about internal bookkeeping that we set up and never used.

**Comment by geoffjentry** [comment]
example of this - in one of my tests i was generating ~1000 metadata requests per second. every single one of those in turn generated a message back to my original actor which was ignored, which would slow down the original actor.

**Comment by geoffjentry** [comment]
The answer is "no".

**Comment by cjllanwarne** [comment]
@geoffjentry: https://www.reddit.com/r/QTWTAIN/
