### ISSUE TITLE
Automatically apply cromwell workflow id as a Pipelines API label

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1813]
This is a much smaller ticket than the entire epic.  In this case, when a each task in a pipeline is run on the JES backend, we want to apply a label (key = cromwell_workflow_id, value = <the workflow id>) to the pipeline operation (job).

This will enable the billing use case for FireCloud as they can then query the billing data and slice by cromwell workflow id.

**Comment by cjllanwarne** [comment]
Changing to key = `cromwell_workflow_id` to fit with [RFc1035](https://www.ietf.org/rfc/rfc1035.txt)
