### ISSUE TITLE
Add a "current" soft link to point to most recent run

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/cromwell#1814]
When I use cromwell, I often would like to be able to refer to the most recent files that we produced while also keeping earlier versions.

This way a user could refer to a file as,
cromwell-executions/Workflow/current/call-Job/shard-3/execution/filename
instead of
cromwell-executions/Workflow/ebbf651b-2dc6-4066-9e8d-b4e2ca722c1e/call-Job/shard-3/execution/filename
or some other hash that is subject to change.

**Comment by katevoss** [comment]
@fleharty can you explain your use case a bit more? Is this something you still want?

**Comment by geoffjentry** [comment]
With the advent of things like miniwdl we're looking to move away a bit from the command line, single user mode. We do have things like Job Manager which can provide this sort of information via UI
