### ISSUE TITLE
The bash command with ${array[@]} doesn't parse correctly

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/cromwell#1819]
The wdl below doesn't pass input processing. It's a valid bash command. I suspect it has to do with the @ sign? 

This wdl (also copied below) reproduces the issue:
/humgen/gsa-hpprojects/dev/tsato/m2-evaluation/wdl/test/hello.wdl
/humgen/gsa-hpprojects/dev/tsato/m2-evaluation/wdl/test/hello.json

#### wdl ####

task hello {
  String addressee
  
  command <<<
    echo "Hello ${addressee}!"
    array=(one two three)
    for i in ${array[@]}; do
      echo $i
    done
  >>>

  runtime {
      docker: "ubuntu:latest"
  }
  output {
    String salutation = read_string(stdout())
  }
}

workflow hello_and_goodbye {
  String hello_and_goodbye_input

  call hello {input: addressee = hello_and_goodbye_input }

  output {
    String hello_output = hello.salutation
  }
}

#### json ####
{
  "hello_and_goodbye.hello_and_goodbye_input": "Takuto"
}
#### error message ####
"failures": [{
    "message": "Workflow input processing failed:\nUnable to load namespace from workflow: Unrecognized token on line 7, column 22:\n\n    for i in ${array[@]}; do\n                     ^"
  }]

**Comment by cjllanwarne** [comment]
I think this is expected behavior since `array[@]` is not a valid WDL expression and so cannot be used between `${ }` in a command string.

Since WDL doesn't have a way to escape the sequence, I suggest inserting the `$` in manually in a way that doesn't trigger WDL string interpolation:
```
String dollar = "$"
command <<<
  echo "Hello ${addressee}!"
  array=(one two three)
  for i in ${dollar}{array[@]}; do
    echo $i
  done
```

**Comment by cjllanwarne** [comment]
I verified this workaround using the following WDL file:
```
task dollarInterpolation {

	String dollar = "$"
	command <<<
	  array=(one two three)
	  for i in ${dollar}{array[@]}; do
	    echo $i
	  done
	>>>

	output {
		String s = read_string(stdout())
	}
}

workflow main {
	call dollarInterpolation
}
```
