### ISSUE TITLE
Gather reliability / workflow failure causes from GOTC

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1820]
GOTC keeps track of very workflow failure in a spreadsheet, and summarizes.  @bradtaylor has shown it to me before, so he might be the place to start.

The task here is to review that spreadsheet, provide a summary of the top failure modes and schedule a tech/design meeting to define the tickets that would have prevented these failures.

**Comment by Horneth** [comment]
@kcibul I created tickets related to this and scheduled a meeting on Monday to hash them down.
Let me know if that covers this ticket and if so I'll close it.

**Comment by ruchim** [comment]
@kcibul now that even have a proposal doc to help reduce GOTC failure modes, it seems this spike/investigation is complete. Closing it for now.
