### ISSUE TITLE
Implement basic soak test for Cromwell

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1822]
The goal here is to gather reliability metrics on Cromwell.  The theme here is basic.. the data is the most important artifact. Create something (e.g. a bash or python script) that 
 
- launches N (e.g. 50) workflows
- polls for workflow completion
- upon workflow completion, log workflow id + status (success/failure) and launch a new workflow

If a workflow fails, perhaps also grab the metadata for the workflow and write it out (although we could also query Cromwell for this later).  This should run until we kill it.  

Then start it up and let it run.  Each day investigate workflow failures and generate a findings document which will feed into reliability ticket creation

**Comment by geoffjentry** [comment]
Realizing I might be taking this into me having to do it one possibility would be to take advantage of the cRomwell R package. The rest interaction is already there and having the data sucked into R allows us to take advantage of its plotting and report generation infrastructure 

Further it helps them keep it in sync with the Cromwell API and would potentially provide cool functionality which would be better served in that package

**Comment by geoffjentry** [comment]
Thinking about my comment more I don't think this is a great idea. R's lack of decent concurrency (as opposed to parallelism) would make this difficult I think.
