### ISSUE TITLE
Workflow fails without error possibly due to declaring variables in a scatter

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#1826]
Here is a wdl:

```
task Decapitate {
	File inputFile
	String outputFilename

	command {
		tail -n+2 ${inputFile}
	}
	runtime {
  		memory: "4 GB"
  	}
	output  {
		Array[Array[String]] outputMatrix=read_tsv(stdout())
	}
}

task Fingerprint {
  String PICARD
  File input_bam
  File input_bam_index
  File haplotype_database_file
  File genotypes
  String sample
 
  command {
    java -Dsamjdk.buffer_size=131072 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx1024m  \
    -jar ${PICARD} \
    CheckFingerprint \
    INPUT=${input_bam} \
    OUTPUT=${sample} \
    GENOTYPES=${genotypes} \
    HAPLOTYPE_MAP=${haplotype_database_file} \
    SAMPLE_ALIAS=${sample} \
    IGNORE_READ_GROUPS=true
  }
  runtime {
  	continueOnReturnCode: true
  	memory: "4 GB"
  }
  output {
    File summary_metrics = "${sample}.fingerprinting_summary_metrics"
    File detail_metrics = "${sample}.fingerprinting_detail_metrics"
  }
}

task CrossCheckFingerprints {
	String PICARD
	Array[File] input_bams
	Array[File] input_bam_indexes
	File haplotype_database_file
	String metrics_filename
 
  command <<<
      java -Dsamjdk.buffer_size=131072 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx2000m \
       -jar ${PICARD} \
       CrosscheckReadGroupFingerprints \
       OUTPUT=${metrics_filename} \
       HAPLOTYPE_MAP=${haplotype_database_file} \
       EXPECT_ALL_READ_GROUPS_TO_MATCH=false \
       INPUT=${sep=' INPUT=' input_bams} \
       LOD_THRESHOLD=-20.0
  >>>
  runtime {
  		memory: "4 GB"
  }
  output {
    File metrics = "${metrics_filename}"
  }
}

workflow FingerprintSamples{
	File SamplesTSV
	File haplotype_database_file  
	String PICARD

	call Decapitate {
		input:
			inputFile=SamplesTSV,
			outputFilename=SamplesTSV+".headless"
	}

	scatter(row in Decapitate.outputMatrix) {
		 String PROJECT=row[0]
		 String SAMPLE=row[1]
		 String DATA_TYPE=row[2]
		 String COMPARE_SAMPLE=row[3] 
		 String COMPARE_PROJECT=row[4]
		 String CLEAN_SAMPLE=row[5]
		 String CLEAN_COMPARE_SAMPLE=row[6]

		 Array[File] bams =    ["/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bam", "/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bam"]
		 Array[File] indexes = ["/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bai", "/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bai"]
		 File genotypes = "/seq/references/reference_genotypes/non-hapmap/${PROJECT}/Homo_sapiens_assembly19/${CLEAN_SAMPLE}.vcf"

		 call Fingerprint {
		 	input:
		 		PICARD=PICARD,
		 		input_bam=bams[0],
		 		input_bam_index=indexes[0],
			    haplotype_database_file=haplotype_database_file,
		  	 	genotypes=genotypes,
				sample=SAMPLE,
   		 }

		 call Fingerprint as FingerprintOther {
		 	input:
		 		PICARD=PICARD,
		 		input_bam=bams[1],
		 		input_bam_index=indexes[1],
			    haplotype_database_file=haplotype_database_file,
		  	 	genotypes=genotypes,
				sample=COMPARE_SAMPLE,
   		 }

   		 call CrossCheckFingerprints {
	 		input:
	 			PICARD=PICARD,
	 			input_bams=bams,
	 			input_bam_indexes=indexes,
	 			haplotype_database_file=haplotype_database_file,
	 			metrics_filename=CLEAN_SAMPLE+"_and_"+CLEAN_COMPARE_SAMPLE+".crosscheck"
   		 }

		 output {
		 	Fingerprint.*
		 	FingerprintOther.*
		 	CrossCheckFingerprints.*
		 }
	}
}
```

And a json to go with it:
```
{
  "FingerprintSamples.PICARD": "/seq/software/picard/current/bin/picard.jar",
  "FingerprintSamples.haplotype_database_file": "/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.haplotype_database.txt",
  "FingerprintSamples.SamplesTSV": "sampleSetTest.txt"
}
```

This is sampleSetTest.txt: 
[SampleSetTest.txt](https://github.com/broadinstitute/cromwell/files/694627/SampleSetTest.txt)

All of the individual tasks seem to work, but when it begins the scatter it fails to start most of the tasks. I don't see a pattern to which it seems to start. It then reports QueuedInCromwell on the started tasks, even though they seem to have finished with output. This fails **both** in SGE and Local backends. There is a suspicion that this might be due to declaring variables inside of the scatter? I'm going to try extracting all variable declaration into a task to see if that works.

**Comment by cjllanwarne** [comment]
@meganshand Was this resolved by using the file-path hashing method? If so, can I close this ticket?

**Comment by meganshand** [comment]
I'm not sure, the symptoms looked different. Let me try running it again with file-path and see what happens.

**Comment by meganshand** [comment]
@cjllanwarne Unfortunately it looks like this is a separate issue. I tried running it with the file-path hashing method: When I ran it with a wide scatter (312) it hangs before it starts any tasks in the scatter. When I ran it with a small scatter (6) it "starts" the jobs inside the scatter but the timing diagram just says `QueuedInCromwell` for all of them.

It might not be the fact that there are declarations inside of the scatter, but the fact that those declarations include declaring multiple files, which all happen at once.

**Comment by ruchim** [comment]
@meganshand you mentioned in your original comment you'd try running it under different conditions:

> This fails both in SGE and Local backends. There is a suspicion that this might be due to declaring variables inside of the scatter? I'm going to try extracting all variable declaration into a task to see if that works.

Did moving variable declarations outside of the scatter help?

**Comment by cjllanwarne** [comment]
Hi @meganshand, I just re-looked at the WDL and it looks like you're using string interpolation where it isn't currently supported. Right now it's only available in `command` blocks. I don't know whether that'll solve the issue you're seeing but it's almost certainly causing problems!

E.g. These `${...}` won't be expanded and will probably be passed in verbatim to bash, where who knows how they'll be interpreted: 
```
Array[File] bams =    ["/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bam", "/seq/picard_aggregation/${PROJECT}/${CLEAN_SAMPLE}/current/${CLEAN_SAMPLE}.bam"]
```

**Comment by cjllanwarne** [comment]
See also https://github.com/broadinstitute/cromwell/issues/2060

**Comment by meganshand** [comment]
Ahha, that is useful information. I think this WDL didn't work for multiple reasons. Is there a simple example WDL or test that uses declarations in a scatter?

**Comment by cjllanwarne** [comment]
@meganshand you can use declarations just not interpolation. So that previous example would be:
```
Array[File] bams =
["/seq/picard_aggregation/" + PROJECT + "/" + CLEAN_SAMPLE + "/current/" + CLEAN_SAMPLE + ".bam", ...
```

**Comment by katevoss** [comment]
@meganshand are you still having problems with this WDL?

**Comment by meganshand** [comment]
@katevoss I haven't tried it. If there is a test that has declarations in a scatter then I'm happy with closing this. I'm sure I was running into some other issue, including what @cjllanwarne mentioned above.

**Comment by katevoss** [comment]
For the fixer: please add a test with declarations using string interpolations in the scatter. If it passes, then there is likely something else wrong with Megan's WDL. If it fails, then we have a bug to fix.

**Comment by Horneth** [comment]
There is already a test that tests a declaration used as a scatter array in centaur: https://github.com/broadinstitute/centaur/blob/develop/src/main/resources/standardTestCases/declarations_as_nodes/declarations_as_nodes.wdl#L23

**Comment by cjllanwarne** [comment]
It turns out we had a problem evaluating file outputs from array literals where internal strings needed further evaluation.

This was resolved as a side-effect of my FileEvaluator changes in https://github.com/broadinstitute/wdl4s/pull/97 - and new tests in the `FileEvaluatorSpec` have been added to confirm this.
