### ISSUE TITLE
Document concurrent-job-limit

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1841]
The `concurrent-job-limit` option is in the CHANGELOG but never appears in the documentation:

```
backend {
  ...
  providers {
    BackendName {
      actor-factory = ...
      config {
        concurrent-job-limit = 5
```

It should probably also make an appearance in the  reference.conf file

**Comment by geoffjentry** [comment]
Despite the text in the issue I'm assuming you meant `concurrent-job-limit`?

**Comment by cjllanwarne** [comment]
Thanks, @geoffjentry. Fixed.

**Comment by katevoss** [comment]
I added the `concurrent-job-limit` to the `reference.conf` and I will add it to the [Configuration draft on the WDL website](http://gatkforums.broadinstitute.org/dsde/discussion/8687/how-to-configure-cromwell), tracked in [DSDE-docs #1524](https://github.com/broadinstitute/dsde-docs/issues/1524).
