### ISSUE TITLE
Additional options for hashing-strategy

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#1843]
It would be great to be able to include last modified date in the hashing-strategy when using the current `path` strategy. This would prevent having incorrect output from a task if the file was modified but the path was not.

**Comment by katevoss** [comment]
@geoffjentry how much effort would it be to include the last modified date in the hash? 
@meganshand do you still want this feature? Or have you found a workaround?

**Comment by meganshand** [comment]
I'm still interested in this feature in the sense that it will prevent mistakes in the future, but it is not blocking any of my work. It's more of a QC feature.

**Comment by geoffjentry** [comment]
This has been added recently for shared file system: https://github.com/broadinstitute/cromwell/blob/90154ed22b2a78dfbb1c5342a8f0d39164aaeac8/docs/Configuring.md#local-filesystem-options
