### ISSUE TITLE
Rethink retry mechanism for post processing of successful execution

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1846]
Currently, after a backend job completes successfully, if something goes wrong trying to read the RC file and / or the stderr file size, the previous "handle" is sent back which triggers a new status poll and it goes down the same code path again, trying to re-read the RC file / stderr.
If for some reason one or both of those files is permanently damaged and can never be read, the actor will be stuck in an infinite retry loop.

**Comment by geoffjentry** [comment]
@Horneth Is this the same issue you're referencing in #1782? If so let's close #1782

**Comment by geoffjentry** [comment]
It appears that this is the same error being referenced in #1782, closing that one but leaving the breadcrumb in case someone wants a stacktrace

**Comment by geoffjentry** [comment]
@Horneth referenced this as a possible cause of #1846

**Comment by katevoss** [comment]
This is fixed.
