### ISSUE TITLE
Always provide RC file (or as much as possible)

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1848]
In JES, the use case where a task exits without producing 1 or more expected output files will end up with the JES job in a failed status (because of non-existing output files failed to be delocalized), and the error message "Failed to delocalize files".
This looks like an error from JES where it's actually most likely an error of the task failing to produce some outputs.
If the job fails Cromwell never tries to read the RC file which makes it difficult for a user to know if it's a JES error or a task error.

1) Make sure that JES will delocalize the RC file first before trying to delocalize outputs - so it's available in the bucket.
2) Have cromwell try to read the file even if the job failed and make sure it's present in the metadata.

**Comment by cjllanwarne** [comment]
And/or include a link to stderr in the failure message?

**Comment by Horneth** [comment]
Yes although the path to stderr is already in the metadata
