### ISSUE TITLE
Cromwell Client APIs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1855]
As in, a nice easy-to-use client API for the Cromwell REST endpoint.

So if anything RESTy changes in the future (like the shift to multipart forms...) a user must simply update their client API version, rather than modifying their own code.

**Comment by geoffjentry** [comment]
@cjllanwarne Are you implying a scala based library here?

**Comment by cjllanwarne** [comment]
@geoffjentry I was... to cover most of our internal DSDE users at least

**Comment by cjllanwarne** [comment]
(though I guess Java would also suffice, if there's a nice REST API generator you had in mind that only-in-Java

**Comment by antonkulaga** [comment]
I also vote for Scala client!

**Comment by geoffjentry** [comment]
@antonkulaga No worries, there'll definitely be one that's at least scala compatible (e.g. perhaps Java). And if I do it I can guarantee it'd be scala ;) 

I was more curious if @cjllanwarne was looking for other things as well. We had discussed in person and the answer was no.

**Comment by cjllanwarne** [comment]
Request for scalaJS from #1992

**Comment by kcibul** [comment]
I think having at least two bindings would be valuable -- although if we're using swagger isn't the idea that many of these could just be generated?  

Since this is about people outside cromwell using it programmatically, we should target the most widely used languages.  Something like Java (which could still be used in scala), Python and maybe even JS would be what comes to mind.

**Comment by antonkulaga** [comment]
@kcibul Scala crosscompiles to javascript, that means that a scala client can be used: 1) in JVM world 2) in nodejs 3) in client javascript (although having scala itself gives 400kb overhead) 4) in LVVM (thought Scala-native)

**Comment by antonkulaga** [comment]
@kcibul I am writing a Scala/ScalaJS Cromwell client mostly for internal (inside the lab) use now. I will post the link to the repo as soon as there will be something

**Comment by kcibul** [comment]
Sounds like a good option.  I think a python binding would be very useful
as well given the automation community, but this sounds like a good start

-------------------------------
Kristian Cibulskis
Engineering Director, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by geoffjentry** [comment]
Don't forget that there is an R client already out there as well

**Comment by antonkulaga** [comment]
I pushed first code of my Scala/ScalaJS cromwell client https://github.com/antonkulaga/cromwell-client

**Comment by katevoss** [comment]
@geoffjentry what do you think the effort would be to add Client APIs?

**Comment by geoffjentry** [comment]
@katevoss Irrelevant as we shouldn't do it. The proper path forward is to [fix our swagger](https://github.com/broadinstitute/cromwell/issues/2533) and then use codegen.

**Comment by danxmoran** [comment]
@geoffjentry @cjllanwarne do you think your swagger is in good enough shape now for codegen to work well? Green was hoping to use your client in our next project instead of rolling yet-another-of-our-own, but some of the endpoints we need (top-level query, and labels patch) haven't been implemented.

**Comment by geoffjentry** [comment]
My recollection is that it would "mostly work", but .....

- Because we're not great at making sure there's a 1:1 correspondence there's probably some things which aren't right. It'd be great to figure out what these were though.
- The metadata return packet isn't at all described in swagger
