### ISSUE TITLE
"cromwell --help" should return zero exit code (success) rather than one (failure)

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/cromwell#1870]
When run, `cromwell --help` currently returns an exit code of 1, indicating unsuccessful execution. It would be helpful for the exit code of this command to be 0. This change would make it possible to more easily check whether cromwell has been built correctly and that it runs. The exit code for bare `cromwell` can still be non-zero since such a call lacks any actionable parameters, but when `cromwell --help` is specified, the return code would ideally be zero.

**Comment by rvalieris** [comment]
`cromwell -version` also returns exit code 1.

**Comment by geoffjentry** [comment]
Changed in develop
