### ISSUE TITLE
Something is rotten in the state of WorkflowStore (maybe)?

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1874]
In a conversation with @hjfbynara he referenced seeing an issue a few more times which had come up in the past. I remembered that @kshakir posted the following in slack and wanted to capture it for posterity here:

the firecloud thingy is “worked around”. cromwell 1 and 2 were restarted, and both started running jobs again.

ruchi and I glanced at the supervision in the CromwellRootActor of the WorkflowStoreActor, and didn’t see anything special that would catch 100% of errors*. However— it was only a hypothesis that the WorkflowStoreActor was dead, as doug and henry reported little to no cpu activity from cromwell if I recall correctly.

* The WorkflowStoreActor appears to be supervised for initialization exceptions, but the rest are handled with a “default”. It looks like default might be equal restart, but as of this second I don’t know what exact state a new instance of a WSA actor/fsm restarts based on the akka spec. Also there was some error logging on db futures within the WSA, but it’s possible an exception was throws before the `Future` got a chance to wrap the exception in a failure? All guesses at this point that could be way off target.

**Comment by Horneth** [comment]
One other possible explanation could be a bug we found in the post processing of a successful job when cromwell tries to read the value of the RC file. If for some reason cromwell failed to read it, it would get stuck in a stale running state. If that happens to enough workflows and then a concurrent-workflows-limit set, then it would produce the observed behavior.

**Comment by mcovarr** [comment]
believed fixed by #2150 and #2154
