### ISSUE TITLE
Handle JES preemptions in the JES backend

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1889]
This is currently more of an opinion than a request :)

When we were discussing some of the retry stuff the other day the point was made by @cjllanwarne that the preemption handling really should be by the JES backend and not the engine as it is backend specific behavior. In theory the code path in the engine is general but it's basically tied 1-1 w/ preemption. Further, if we're going to be modifying preemption handling further (the "inner loop" idea) this seems like it'd make the behavior even more specific.

We should solidify the notion of engine level retry and backend level retry

**Comment by katevoss** [comment]
@geoffjentry is this still how retries work?

**Comment by geoffjentry** [comment]
Yes and no, but this isn't meaningful any longer.
