### ISSUE TITLE
Adding "sleep 2" should not be necessary for Local Backend to work

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1894]
Centaur tests should reliably pass even when they don't have a `sleep 2` suffixed to the command block.

**Comment by mcovarr** [comment]
+1000

**Comment by geoffjentry** [comment]
@cjllanwarne I think this is a dupe of #1868?

**Comment by ruchim** [comment]
Closed by https://github.com/broadinstitute/centaur/pull/158
