### ISSUE TITLE
Sub() function doesn't accept stdout() as a parameter

### ISSUE THREAD

**Issue by anton-khodak** [broadinstitute/cromwell#1908]
I am trying to reproduce one of the [examples](https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#example-5-word-count) in the spec. It doesn't work out of the box since `wc` command produces a string with filename, and not just integer. Thus, I tried to substitute all non-digit characters with function `sub`:
```
  output {
    Int count = read_int(sub(stdout(), "\D", "")
  }
```
However, I get an error:
```
Unable to load namespace from workflow: Unrecognized token on line 7, column 40:

    Int count = read_int(sub(stdout(), "\D", ""))
                                       ^
cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$3$$anon$1: Workflow input processing failed:
```

**Comment by cjllanwarne** [comment]
Good spot! Looks like the command is actually wrong rather than the output. One change we could make to correct it would be:
```
task wc2_tool {
  File file1
  command {
    cat ${file1} | wc -w
  }
  output {
    Int count = read_int(stdout())
  }
}
```

For future reference, your command won't work for a few reasons:
 - stdout() returns a file, not a string, so you'd be modifying the file path rather than its content
 - As far as I know, `sub()` doesn't recognize wildcards like `\D`

**Comment by anton-khodak** [comment]
@cjllanwarne Thank you, my fallacy was that stdout() returns a String, should have looked in the Spec more carefully first. Why though the regexp is not recognized?

**Comment by geoffjentry** [comment]
@anton-khodak An aside re the spec document, all of our documentation including that is undergoing heavy change, we've now have a group of people to manage our community & documentation and they're in the process of figuring out how to transform what docs we have now to their new format.

One of the many things about the spec is that the examples are often out of date (sigh) - if you want to have concrete examples of WDLs there should be examples on the [WDL site](https://software.broadinstitute.org/wdl/userguide/). I apologize that it'll be confusing, pardon our mess :)

**Comment by anton-khodak** [comment]
@geoffjentry Admittedly, despite some inaccuracies you might have, the documentation on the site is very user-friendly, special thanks, hopefully, the style itself won't change. I turned to the spec because I needed simpler examples for my own purposes. Nonetheless, this issue is resolved, thank you

**Comment by geoffjentry** [comment]
@anton-khodak Cool. I'm gonna ping @katevoss and @vdauwera so they see the feedback. Thanks!

**Comment by katevoss** [comment]
@anton-khodak I'm glad to hear that you find the docs user-friendly, can you elaborate what you find particularly helpful? I want to make sure I preserve it as I review and update the docs. Thanks!
