### ISSUE TITLE
Jes Backend Retries

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1912]
We would like to handle certain JES VM errors in a manner which allows for some automatic retries prior to failing the job. There will be two categories, each handled slightly differently from the other:

Preemption for preemptible VMs (i.e. Error 14)
JES error codes other than preemption which we believe to be transient (e.g. Error 13)
For both situations, the following statements will be true:

When one of these events happens we will determine if the job is retryable (see below for criteria)
If the job is not retryable it will be failed
If the job is retryable
-- An event will be sent to the metadata service
-- The retry will be logged
-- The attempt number shall be incremented
-- The job will be attempted again
In terms of visibility to the end user, preemption shall be handled exactly as it is now. For the other error codes we retry up to 2 times, and there will be a server level configuration option to toggle this behavior on and off.

There will be a subtle implementation change for these compared to how preemption is handled now. In the JES backend if a job fails for one of these two reasons and we decide the job is retryable (either because it was preempted and the remaining preemption count is > 0 or non-preemption and the master retry count is > 0) a signal will be sent back to the engine that the job failed but is to be retried. The difference here from the current behavior is that the JES backend is the one tracking the retry counts and merely telling the backend to retry the job instead of the engine tracking the retry count(s).

**Comment by katevoss** [comment]
All 3 issues are completed, closing this as complete!
