### ISSUE TITLE
memory-driven VM sizing may be surprisingly high on JES

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1918]
I ran into this during Centaur testing to confirm that the `memory` attribute is plumbed through to JES as expected.  Cromwell is handling `memory` correctly (i.e. this is not a bug report), but I found the consequences of my chosen `memory` values somewhat surprising.

JES guarantees a VM with at least as much memory as the user requests.  But combining this fact with the [memory thresholds](https://cloud.google.com/compute/docs/machine-types) for standard instance types means that common memory specifications may procure a VM with nearly double the requested memory at [double the cost](https://cloud.google.com/compute/pricing#machinetype).  For example:

```
runtime {
  memory: "4 GB"
}
```

or 

```
runtime {
  memory: "8 GB"
}
```

These specifications might be expected to procure an n1-standard-1 (3.75 GB) and n1-standard-2 (7.5 GB).  But JES guarantees a VM with _at least_ as much memory as requested, not _about_ as much memory as requested.  So a request for 4 GB would procure a 7.5 GB n1-standard-2 and a request for 8 GB would procure a 15 GB n1-standard-3.  It seems unlikely a WDL author intending to execute on JES would intentionally write `memory` values of 4 GB or 8 GB with this understanding of how JES interacts with GCE memory sizes.

**Comment by katevoss** [comment]
We think this is a documentation issue, I will file a DSDE-comms ticket to add this to our docs. Thanks!
