### ISSUE TITLE
Test MySQL/HSQL in Travis/Centaur

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1920]
Following on from https://github.com/broadinstitute/cromwell/issues/1919 - we should prevent regressions like this in the future.

**Comment by cjllanwarne** [comment]
As far as I can tell, all Centaur tests in Travis use HSQLDB for Cromwell

**Comment by geoffjentry** [comment]
Change the centaur jes Cromwell to use MySQL, leave local centaur as heal

**Comment by katevoss** [comment]
Sounds like we don't test MySQL, HSQL, or CloudSQL ( #1726 ), is that right?
@cjllanwarne would the effort to test MySQL and HSQL be the same as testing CloudSQL? Who do we know is using MySQL and HSQL?

**Comment by mcovarr** [comment]
We are testing MySQL and HSQL but not CloudSQL. Unfortunately CloudSQL is what we actually use in production.

**Comment by mcovarr** [comment]
...soooo I think this particular ticket can be closed.
