### ISSUE TITLE
Document that call caching is not backend-specific

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1921]
This caused some confusion...

Please copy the block from local backend into SGE.

**Comment by katevoss** [comment]
@LeeTL1220 I don't see any mention of SGE on [reference.conf](https://github.com/broadinstitute/cromwell/blob/1707a4a793decc3c5f93115275abb98e7890aad2/core/src/main/resources/reference.conf). 

I do see SGE in [cromwell.examples.conf](https://github.com/broadinstitute/cromwell/blob/6e202ad3119d7b6329df584e267e89a04c014883/cromwell.examples.conf) but it seems like the call caching block is not backend specific. Is that where you were looking?

**Comment by LeeTL1220** [comment]
@katevoss When I filed this issue, the examples were in the reference.conf.  

If call-caching is truly not backend specific in any way, then feel free to close this issue.

**Comment by katevoss** [comment]
@geoffjentry call caching is not backend-specific, right?

**Comment by geoffjentry** [comment]
Right. At most this is a documentation issue

**Comment by katevoss** [comment]
Another item that needs to be documented: runtime attributes that will (and won't) affect call caching. 
From #2604, the only runtime attributes that do count in call caching are `ContinueOnReturnCode`, `Docker`, and `FailOnStderr`.

**Comment by ruchim** [comment]
@LeeTL1220 the name of a `backend` is part of the caching algorithm today (though its possible it was different when you first reported this issue). I'm closing this as the call caching assumptions in this issue no longer apply. Feel free to re-open with an alternate recommendation, or file a new issue if you prefer. Thanks
