### ISSUE TITLE
Cromwell fails to construct output array of a scatter block with conditional tasks inside the block

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/cromwell#1936]
This is a general form of the workflow that I had this issue with:

```
workflow wf {
  Boolean condition
  Array[String] files

  scatter (row in files) {
    if(condition) {
      call A
    }
    if(!condition) {
      call B
     }
  }
}
```

The tasks themselves finish, however I get the following error:

`Could not construct array of type WdlMaybeEmptyArrayType(WdlOptionalType(WdlFileType)) with this value: List(WdlSingleFile(/dsde/working/asmirnov/evaluations/CovariateCorrection/scripts/test_wdl/cromwell-executions/cnv_coverage_workflow/c71f4899-6031-4a21-b9b4-1dafd659cd05/call-CalculateTargetCoverage/shard-0/execution/TCGA-02-2483-10A-01D-1494-08.coverage.tsv), WdlSingleFile(/dsde/working/asmirnov/evaluations/CovariateCorrection/scripts/test_wdl/cromwell-executions/cnv_coverage_workflow/c71f4899-6031-4a21-b9b4-1dafd659cd05/call-CalculateTargetCoverage/shard-1/execution/TCGA-02-2485-10A-01D-1494-08.coverage.tsv))`

**Comment by cjllanwarne** [comment]
Interesting, this should be covered by https://github.com/broadinstitute/centaur/blob/develop/src/main/resources/standardTestCases/conditionals_tests/ifs_in_scatters/ifs_in_scatters.wdl - I wonder if this is a File specific bug.

Is this report against C24 or the develop branch (which has a few fixes)? If C24 I might double-check against develop

**Comment by katevoss** [comment]
@asmirnov239 are you still having this problem with Cromwell 25?

**Comment by geoffjentry** [comment]
Closing due to lack of response
