### ISSUE TITLE
Either cromwell or wdl4s should provide lenthall, but not both

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#1955]
We're beginning to get warning during our build because both wdl4s and cromwell are specifying different lenthall versions:

```scala
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.broadinstitute:lenthall_2.11:0.20 -> 0.21-e1b7822-SNAP
[warn] Run 'evicted' to see detailed eviction warnings
```

Options:
1. wdl4s leaves the lenthall dependency as a compile dependency, the default. cromwell removes its explicit dependency on lenthall, and receives lethall as a transitive dependency through wdl4s. Anytime cromwell wants to update lenthall, wdl4s will need to also be updated and regression tested.
2. wdl4s marks the lenthall dependency as provided. It must be included in cromwell, wdltool, rawls(?), and other downstream build.sbt's. This option may not catch lenthall version incompatibilities between cromwell and wdl4s until runtime, but will not cause version conflicts in build.sbt.
3. We ignore the problem, and continue to have sbt output warnings whenever cromwell and wdl4s disagee on a lenthall version. Has similar potential runtime errors as option 2.

**Comment by geoffjentry** [comment]
I agree from a practical perspective but I always get a little weirded out by relying on transitive deps like this.

**Comment by katevoss** [comment]
@geoffjentry this feels relevant to our repo dependency discussion.
