### ISSUE TITLE
Improve error message for Type error, was "invalid"

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1963]
- 0.24
- SGE backend

I accidentally gave an Int parameter a String value in the json.  I would prefer an error specific to parameter type, rather than a generic invalid runtime attribute error message (below).

Proposed solution:  
``Task m1_task was given an invalid type for cpu = "${cpu}".  A String was given, though parameter is an Int``

Current error message:
```
[ERROR] [02/08/2017 10:38:57.225] [cromwell-system-akka.dispatchers.engine-dispatcher-8] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor Workflow 07a3f007-8c62-4cd4-8668-6ac034ff42f1 failed (during InitializingWorkflowState): Task m1_task has an invalid runtime attribute cpu = "${cpu}"
java.lang.IllegalArgumentException: Task m1_task has an invalid runtime attribute cpu = "${cpu}"
        at cromwell.backend.BackendWorkflowInitializationActor$class.validateRuntimeAttributes(BackendWorkflowInitializationActor.scala:156)
        at cromwell.backend.BackendWorkflowInitializationActor$class.initSequence(BackendWorkflowInitializationActor.scala:171)
        at cromwell.backend.sfs.SharedFileSystemInitializationActor.initSequence(SharedFileSystemInitializationActor.scala:37)
```

**Comment by katevoss** [comment]
@LeeTL1220 cleaning up old issues, are you still having this problem?

**Comment by LeeTL1220** [comment]
This is an issue with the error reporting.  I have not checked (and I do not remember how to replicate).

**Comment by katevoss** [comment]
Okay, I'll close it for now and if you notice another problem feel free to reopen or open a new issue. I'll follow up much sooner :)
