### ISSUE TITLE
Create engine functions so`gs://` `sub`s aren't required

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1968]
The single sample WF has to resort to multiple `sub`s to manipulate `gs://` paths.  For AWS the WDL needed to be changed to operate on `s3://` paths instead.  Provide whatever engine functions are required such that this will no longer be necessary.

**Comment by vdauwera** [comment]
This would be soooo helpful!

**Comment by geoffjentry** [comment]
Related: 1839

I believe if one were to look that there are others out there as well

**Comment by cjllanwarne** [comment]
For all but the most extreme cases, those `sub`s can now be removed via judicious use of the `basename` function.
