### ISSUE TITLE
JES aborts seem to not (always?) abort

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1976]
in the workbench chat room they were tracking something where rawls was spamming cromwell with abort requests. The root cause was that a workbench submission was requested to abort which causes rawls to continuously send abort requests to the submission's workflows until it is aborted, which sometimes never happens.

they're not fans of this behavior. Tagging @helgridly and @jmthibault79 as people who can provide more details.

**Comment by katevoss** [comment]
@helgridly and @jmthibault79 I'm guessing you don't remember any details from February, but have you seen any similar behavior since?

**Comment by helgridly** [comment]
A very quick peek in the Rawls db for workflows still in Aborting gives me 92. The earliest one is from February so I'd _guess_ this is still a problem.

**Comment by helgridly** [comment]
The workflow d800c362-e8e7-48e2-bb08-3b88226307e9 has been aborting on cromwell1 since 2017-06-27. Rawls is still trying as of the time of me posting this.

**Comment by Horneth** [comment]
Closing this, as far as I can tell this should not be happening anymore as per https://github.com/broadinstitute/cromwell/pull/2808 (unless the underlying jobs are  indeed stuck in which case Cromwell will wait until they reach a terminal status). If that happens we talked about having a separate endpoint like "just mark this workflow aborted anyway".
