### ISSUE TITLE
glob-xxx.list not created

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/cromwell#1980]
Hello,

I'm seeing this error with glob. Looks like the glob-xxx.list file is not create for some reason. The file it's looking for has a couple commas (,) in them, could that be the issue?

wdl: /humgen/gsa-hpprojects/dev/tsato/palantir/Analysis/451_MedicallyRelevantCoverageWorkflow/medically-relevant-coverage.wdl.copy
json: /humgen/gsa-hpprojects/dev/tsato/palantir/Analysis/451_MedicallyRelevantCoverageWorkflow/medically-relevant-coverage.json
cromwell server: gsa5:8003 (configured for SGE)
metadata: http://gsa5:8003/api/workflows/v2/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/metadata?expandSubWorkflows=false

"message": "Failed to evaluate outputs.: Could not evaluate GetHSMetrics.per_target_coverage = glob(\"*.per_target_coverage\")[0]\n\tFile not found /humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/execution/glob-66c7ddc0219653b72a61bd2dae8bb454.list"

**Comment by kshakir** [comment]
Nothing obvious yet. More details.

Cromwell command, with commit `9264cb1` stamped in the jar name:
```bash
java -Dconfig.file=/humgen/gsa-hpprojects/dev/tsato/wdl/sge_pc_application_ruchi.conf -jar /home/unix/tsato/cromwell-jars/cromwell-25-9264cb1-SNAP.jar server
```

Contents of `script` from the same execution directory, with no attempt to even create the `.list` file:
```bash
#!/bin/sh
umask 0000
(
cd /humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/execution
base_name=$(basename /humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/inputs/seq/picard_aggregation/DEV-7039/Pond-544027,_Standard_Kapa_LC/v1/Pond-544027,_Standard_Kapa_LC.bam .bam)
java -Xmx4g -jar $picard CollectHsMetrics \
I=/humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/inputs/seq/picard_aggregation/DEV-7039/Pond-544027,_Standard_Kapa_LC/v1/Pond-544027,_Standard_Kapa_LC.bam \
O=$base_name.hs_metrics \
PER_TARGET_COVERAGE=$base_name.per_target_coverage \
TI=/humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/inputs/humgen/gsa-hpprojects/dev/tsato/palantir/Analysis/451_MedicallyRelevantCoverageWorkflow/ice-22.interval_list \
BI=/humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/inputs/humgen/gsa-hpprojects/dev/tsato/palantir/Analysis/451_MedicallyRelevantCoverageWorkflow/ice-22.interval_list \
R=/humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/inputs/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta
)
echo $? > /humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/execution/rc.tmp
(
cd /humgen/gsa-hpprojects/dev/tsato/wdl/cromwell-executions/MedicallyRelevantCoverage/e97e55f5-f0e0-42dd-9a7d-ae4edd66dc19/call-GetHSMetrics/shard-1/execution

)
```

**Comment by cjllanwarne** [comment]
NB this didn't happen when the `[0]` wasn't part of the output declaration. If I had to guess, I'd say the FileEvaluator is looking for GlobFiles to expand, but is missing this one because it looks like an array member access rather that a GlobFile type.

**Comment by kshakir** [comment]
Good news, this particular issue is fixed in develop. Less good news, similar syntax doesn't work, yet: broadinstitute/wdl4s#90
