### ISSUE TITLE
Add more Call Caching tests to Centaur

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1985]
Write a workflow such that you run a task A, and then run task A again with one of the call caching hash components is altered to confirm there were no false positive call cache hits.

The hash components to tweak include:
 - [x] input files (in this case, a secondary task can be used to alter the input files for task A)
 - [x] command template
 - [x] backend name
 - [x] output expressions
 - [x] runtime attributes
 - [x] non-file inputs

**Comment by cjllanwarne** [comment]
Fixed! See https://github.com/broadinstitute/centaur/pull/159
