### ISSUE TITLE
Manual Call Caching Testing

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#1986]
1. Find a scientific workflow and run it manually a couple of times to confirm that it is successfully caching as expected (write to cache set to true for all these runs).
2. Try to invalidate some cache hits (by deleting certain outputs).
3. Re-run the workflow and confirm that it's not using the invalidated cache hits and using alternate cache hits instead.
4. Re-run with using floating tags vs hashing and confirm expected behavior.
 
AC: Try the alterations above and others that seem relevant. Keep logs of the workflow attempts or metadata, something to journal this testing.

**Comment by katevoss** [comment]
I believe this is complete with the release of Cromwell 25, is this ready to be closed @ruchim?

**Comment by ruchim** [comment]
Yup :)
