### ISSUE TITLE
Call Caching Debug Endpoint

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1990]
Endpoint with these arguments:
 - `call1_fqn`
 - `call1_index`
 - `call2_fqn`
 - `call2_index`

Which would return a set of call caching hashes which were generated for call2 which do not match call1.

Has to be exactly that, to mirror the call caching algorithm

**Comment by katevoss** [comment]
@cjllanwarne can you tell me a bit more about the usage and impact of this endpoint?

**Comment by cjllanwarne** [comment]
This is about people wanting to know why their job (which should have call cached) did not call cache.
It's come up quite a few times and can be infuriating to debug

**Comment by kcibul** [comment]
As someone who is struggling with this right now... this would be very handy

**Comment by katevoss** [comment]
I think this would be a very good tool to have. @cjllanwarne do you have an idea of how much effort this would be to implement? Days or weeks or months?
