### ISSUE TITLE
cromwell scala client

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#1992]
As cromwell is written in Scala, it should not be very hard to have scala/scalajs-client library that will call cromwell REST API

**Comment by geoffjentry** [comment]
@antonkulaga Take a look at #1855 - it's on my personal todo list to add an artifact w/ a scala client library (probably taking the code out of https://github.com/broadinstitute/centaur and modifying as appropriate).

As for scala.js, much like I said in the wdl4s issue, I like the idea on paper but it's unlikely to happen anytime soon.

**Comment by cjllanwarne** [comment]
Let's combine this ticket with #1855 - I think it's essentially a duplicate.
