### ISSUE TITLE
SFS backend ignores result of cache hit file copying

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#1999]
When a file is being copied as a result of a cache hit, the SFS backend implementation will ignore the result of said copy. 
This means that even if some/all output files, including stdout from the cached job have been deleted, the hit will be consider successful.
Consequently the workflow will continue and depending tasks will likely fail if they use one of those outputs, in turn failing the workflow.

Fix: If a file can't be copied, it should be reported to the EJEA which will run the job instead.

**Comment by cjllanwarne** [comment]
Is this the SFS version of invalidate cache results? Can we also update the centaur test `invalidate_bad_caches` to include whatever causes this?
