### ISSUE TITLE
Cannot specify an optional output using select_first

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2005]
- 0.25
- Local+docker backend (though I doubt it matters)
- single workflow (though I doubt it matters)

Workflow output is optional and sometimes both ``oncotate_m2_ob.oncotated_m2_vcf`` and ``oncotate_m2_no_ob.oncotated_m2_vcf`` are not populated.

Proposed solution:  select_first returns null if no inputs are populated.

Offending workflow output:
```
File? oncotated_m2_vcf = select_first([oncotate_m2_ob.oncotated_m2_vcf, oncotate_m2_no_ob.oncotated_m2_vcf])
```

Error message:
```
[ERROR] [02/17/2017 14:18:45.923] [cromwell-system-akka.dispatchers.engine-dispatcher-5] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor Workflow e241e2bc-95cd-4a8c-a814-20bb8852c6b5 failed (during ExecutingWorkflowState): select_first failed. All provided values were empty.
java.lang.IllegalArgumentException: select_first failed. All provided values were empty.
        at wdl4s.expression.WdlStandardLibraryFunctions$$anonfun$select_first$1$$anonfun$apply$10.apply(WdlStandardLibraryFunctions.scala:180)
        at wdl4s.expression.WdlStandardLibraryFunctions$$anonfun$select_first$1$$anonfun$apply$10.apply(WdlStandardLibraryFunctions.scala:180)
        at scala.Option.getOrElse(Option.scala:121)
        at wdl4s.expression.WdlStandardLibraryFunctions$$anonfun$select_first$1.apply(WdlStandardLibraryFunctions.scala:180)
        at wdl4s.expression.WdlStandardLibraryFunctions$$anonfun$select_first$1.apply(WdlStandardLibraryFunctions.scala:175)
        at scala.util.Success.flatMap(Try.scala:231)
        at wdl4s.expression.WdlStandardLibraryFunctions$class.select_first(WdlStandardLibraryFunctions.scala:175)

....snip....
```

**Comment by LeeTL1220** [comment]
Workaround:

```
File? oncotated_m2_vcf = select_first([oncotate_m2_ob.oncotated_m2_vcf, oncotate_m2_no_ob.oncotated_m2_vcf, "/dev/null"])
```

**Comment by cjllanwarne** [comment]
Hmm, I think this is as-intended and I want to push back.

The primary purpose of `select_first` is to guarantee that you get a non-optional from a sequence of optionals. If you aren't sure that one of the values will be good, you can't use it. That's what the function is for!

In other words, your WDL should not be `File? = select_first(...)`. It should be `File = select_first(...)`

What it sounds like you want is something like `select_first_maybe`, which would be a new feature.

**Comment by LeeTL1220** [comment]
That is okay by me.  For other optional File parameter, I am seeing things like:   ``"Mutect2_Multi.ob_filtered_vcf_files": ["null"],``

**Comment by cjllanwarne** [comment]
You could use this workaround for `select_first_maybe`:
```
Array[File?] maybes
Array[File] goods = select_all(maybes)
if (length(goods) > 0) {
  File select_first_maybe = goods[0]
}
```

**Comment by LeeTL1220** [comment]
@cjllanwarne Many thanks!  Can I put that in a workflow output block?

**Comment by cjllanwarne** [comment]
You would need to put it in the workflow itself and then add something like:
```
output {
  File? maybe_output_file = select_first_maybe
}
```

**Comment by cjllanwarne** [comment]
(FWIW I agree that a single function call would be nicer... But it isn't there yet and it isn't what select_first is for)

**Comment by LeeTL1220** [comment]
@cjllanwarne No sweat.  For me, this is not a big deal and I have an okay-for-now workaround in place.

**Comment by cjllanwarne** [comment]
Closing for now. Feel free to open another "I want a WDL function to do this" ticket if that's something you still want!
