### ISSUE TITLE
"Making a Backend" blog post

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2017]
Here is the permalink for the document that was already written by @cjllanwarne about [How to Make Your Own Backend](https://github.com/broadinstitute/cromwell/blob/9a734c4f36ae122153736004e8d54fc44af8fbde/MakingABackend.MD).

I would like to release it around the same time that we publish the [AWS repo](https://github.com/broadinstitute/aws-backend), which is pending until the [documentation is improved](https://docs.google.com/document/d/1qwY0QBo04WIAvsACbvtIshfxbs1OJRvNp93oclxCRk8/edit#heading=h.pqdhlnltxuz5). This blog post would show up on the WDL blog, which is developer focused. 

@sooheelee I am thinking of including a message to the effect of "This blog post is about our story, it is not a living document. If you decide to write your own backend you should contact us". Then if many people contact us then we can make a living document about how to write your own backend for Cromwell. This is instead of making this blog post into a living document from the outset, which would take effort in its upkeep, without any clear need for it. What do you think?

**Comment by sooheelee** [comment]
I've requested permission to view your google doc (3rd link) so I can get a better sense of what you're talking about.

What do you mean by "our story" and "living document"? Doesn't your "How to Make Your Own Backend" document already cover how to make a backend for Cromwell?

**Comment by katevoss** [comment]
I think of "our story" type blog post like a thinking-out-loud account of how the author, likely Miguel, put together a backend for AWS this one time. If this document was for other users to make their own backend in the future, then it would need to be "living", meaning kept up to date with changes as we make them. 

However as a blog post we can write how we made a backend this one time, rather than worry about whether it will be the right directions for the future. We can include a note at the top that users can use this as a rough idea but may not necessarily be up to date, and they should contact us first. Does that help clarify?

**Comment by sooheelee** [comment]
Ah, I get it. Thanks for the clarification!

**Comment by mcovarr** [comment]
closeable?

**Comment by katevoss** [comment]
Yes, let's revisit in the future but I don't think this ticket serves a purpose any longer. And with Github's automagic search features, we can always find it in the "closed" tickets 😃
