### ISSUE TITLE
Rename JES backend

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2019]
Rename (at least for user visible aspects) the JES backend. As time goes on fewer people are going to be able to make the connection between JES and the google genomics pipelines api and this is going to lead to confusion

**Comment by geoffjentry** [comment]
We should try to find a way to deprecate this in the config files, the combo of the reflection and the way that users just copy/paste whole blocks even if they're not modifying anything will make it hard to have this be purely cosmetic

**Comment by katevoss** [comment]
The README refers to "JES" as well, so part of this issue is cleaning that up too.

**Comment by geoffjentry** [comment]
Yeah, that's the easy part :)

Honestly a reasonable Definition Of Done could be "all docs and the renaming of the reflectively loaded class(es)" as the real problem is our user facing stuff - it's starting to cause confusion, but we might as well go all the way at that point.

**Comment by katevoss** [comment]
@geoffjentry what is the reflectively loaded classes? If it's just the docs, I can do a quick ReadMe "search and replace" 😁

**Comment by geoffjentry** [comment]
The issue is that the way one loads a backend into Cromwell is to reference the implementing scala class, like [this](https://github.com/broadinstitute/cromwell/blob/f1955f963ee65ca9296f554376bd655b9529c10d/cromwell.examples.conf#L466)

If we change the name of that class old config files will be broken. In theory we could deprecate it and have some sort of redirect but not sure offhand how that'd work. We have the same problem in #2440

**Comment by katevoss** [comment]
As a **user setting up Cromwell**, I want **only want to see references to Google Genomics Pipelines API**, so that **I know how to set up the Google backend, not some JES thing.**
- effort: small
- risk: small to medium
- business value: small
   - may grow if it becomes confusing

**Comment by geoffjentry** [comment]
This is close enough to complete for me
