### ISSUE TITLE
using cromwell-executions folder to track for run history in local mode

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2022]
You say:
```
By default, Cromwell uses an in-memory database which will only live for the duration of the JVM. This provides a quick way 
```
I see that cromwell has cromwell-executions folder that is not deleted when JVM closes. Can it just scan this folder in local mode when I want to see the workflows that were finished?

**Comment by geoffjentry** [comment]
Not really. Some of the information we store is in there, but not nearly enough to recreate the state of things.

**Comment by cjllanwarne** [comment]
I agree, a local database is the way to do this, e.g. I can use a mysql database even when testing things locally.

**Comment by antonkulaga** [comment]
Why cannot use SQLLite by default in such case?

**Comment by geoffjentry** [comment]
Because we don't support SQLite. There's no technical reason, it's just not a use case we have

**Comment by geoffjentry** [comment]
@antonkulaga If you'd like to open a ticket for SQLite support please do so, although to be upfront it's not something likely to happen in a reasonable timeframe until if/when there's an internal use case pushing for it to happen.

**Comment by cjllanwarne** [comment]
@antonkulaga I think a default SQLite DB would be pretty awesome! I'd love to see that ticket - although yeah, timeframes... :) I'm also assuming there's a slick driver for it already, but I'd be surprised if not.

As to why something like that isn't the default already, it's mostly historical: we have use-cases where people don't want things persisted (in memory), and we have use-cases where people want to use cloudSQL (i.e. the MySQL API), and "in memory" was just the easiest one to use as the default.

**Comment by geoffjentry** [comment]
@cjllanwarne Yep: http://slick.lightbend.com/doc/3.0.0/supported-databases.html
