### ISSUE TITLE
Wide submissions to batch endpoint slow, may orphan workflows

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2025]
Seeing this during testing for call cache perfomance:

I'm submitting a fairly small scatter workflow to the batch endpoint, with 3000 (empty) inputs to launch 3000 copies of the workflow.  It takes several minutes for Cromwell to produce a response, by which time the client has timed out.  So Cromwell is going to run all these workflows but the client doesn't know their IDs.

**Comment by geoffjentry** [comment]
There's at least one linear processing operation in there. doesn't have to be that way.

**Comment by mcovarr** [comment]
@danbills [WDL](https://gist.github.com/mcovarr/081b1500dac0804dfa51dbd4790ca918) and [inputs array](https://gist.github.com/mcovarr/375440c250b2529c13118b2cca38937d).

**Comment by danbills** [comment]
While trying to reproduce this issue with the provided files, I see a pretty timely response that these workflows were submitted (200 status).  Is it possible the issue has been fixed?

**Comment by mcovarr** [comment]
I'm not sure what's changed in the vicinity of this code, but given how much time has passed it's certainly possible.  😄

**Comment by geoffjentry** [comment]
@danbills What @mcovarr said. Can you try submitting 100K and see if it still works? If not, where does it start to crap out?

**Comment by danbills** [comment]
I was able to reproduce at 120K (meaningless) inputs.

**Comment by danbills** [comment]
@geoffjentry  Starts to crap out between 25K and 30K inputs

**Comment by danbills** [comment]
I was able to establish the current threshold is roughly 10x what was originally reported.  As such we are de-prioritizing.

**Comment by katevoss** [comment]
If this is no longer an actionable issue, I'll close it.
