### ISSUE TITLE
WEA transitions to failed state and leaves jobs running

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2029]
There are two general cases where the `WorkflowExecutionActor` switches the workflow to a failed state:
- [`handleRetryableFailure()`](https://github.com/broadinstitute/cromwell/blob/f64c16e62c84b66ddba14705bede5e6fde8376b0/engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala#L292-L306)
- [`handleExecutionFailure()`](https://github.com/broadinstitute/cromwell/blob/f64c16e62c84b66ddba14705bede5e6fde8376b0/engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala#L240-L255)

In _both_ cases, the method:
- is triggered by the failure of an individual job, but
- fails the entire workflow, and
- doesn't send signals to other jobs to stop

Thus other jobs stay running, while the workflow gets deregistered from the system. Because the workflow manager can no longer delegate aborting the running jobs, this issue may also be related to #1414 and #1504.

**Comment by katevoss** [comment]
@kshakir did this change at all with the retries work earlier this year?

**Comment by Horneth** [comment]
Fixed by https://github.com/broadinstitute/cromwell/pull/2808, although other jobs are not stopped when a job fails, they're left as is and are being monitored until they reach completion.
