### ISSUE TITLE
update readme on spark backend

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2033]
I see that in readme

```
Configuring Spark Project
When using Spark backend uncomment the following Spark configuration in the application.conf file
```

But I do not see it in application.conf Looks like this is outdated.

**Comment by cjllanwarne** [comment]
I think this probably should be move the relevant section across to `application.conf` from `reference.conf`

**Comment by antonkulaga** [comment]
It would be nice to have clearer docs on Spark backend (what should be put to wdl and what should be given to cromwell.jar instead of default application.conf)

**Comment by geoffjentry** [comment]
Attn @francares & @gauravs90 - there's a request for some love on the Spark backend

**Comment by gauravs90** [comment]
@jainh Can you update / help clarify the readme docs for spark?

**Comment by jainh** [comment]
@antonkulaga I will update Readme to point right configuration, however on `what should be given when running java -jar Cromwell.jar` it doesn't need any additional runtime attributes besides uncommenting Spark backend configuration from `reference.conf`  and on `what should be put to wdl` is referred here : [WDL](https://github.com/broadinstitute/cromwell#sample-wdl)

**Comment by katevoss** [comment]
The PR was merged, closing this out.
