### ISSUE TITLE
exporting non-existent TMPDIR in commandScriptContents considered harmful

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#2035]
https://github.com/broadinstitute/cromwell/blob/25c6573bb9342a859fee735f4190b6b6d9f2dec4/backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala#L181

The environment variable $TMPDIR set to a custom value and exported in the shell script preamble, but the directory isn't actually created. This is an unpleasant surprise for some things a user might have in their command (e.g. `mktemp`) which assume that if $TMPDIR is set, then it exists.

**Comment by mcovarr** [comment]
Yeah I would agree that's a bug.  If you've patched this locally we would certainly welcome a PR!  😄

**Comment by delocalizer** [comment]
I don't actually know what the fix is because I don't know the intent behind exporting custom `TMPDIR` into the shell environment. I could just delete that line — it seems redundant to me, I can't think why the command shell `TMPDIR` has to equal `java.io.tmpdir` — but I don't know if it's there to fix some other issue that I don't know about.

**Comment by geoffjentry** [comment]
without looking at it, my guess is that Picard is looking for it.

**Comment by delocalizer** [comment]
Then I guess `mkdir $TMPDIR` is the way to go

**Comment by delocalizer** [comment]
looks like this has been covered before https://github.com/broadinstitute/cromwell/issues/731

**Comment by geoffjentry** [comment]
Oh the things which fell through the cracks during the march toward version 19.

Thanks @delocalizer
