### ISSUE TITLE
Clean out the ridiculously outdated docs in cromwell dockerhub

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2042]

**Comment by katevoss** [comment]
Moving this to docs.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/dsde-docs #1932](https://github.com/broadinstitute/dsde-docs/issues/1932) via [**ZenHub**](https://www.zenhub.com/)

**Comment by geoffjentry** [comment]
![images](https://cloud.githubusercontent.com/assets/961771/24725302/639dff6c-1a1c-11e7-96a9-7b7cfa532c22.jpg)
