### ISSUE TITLE
Unreported AggregatedExceptions

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2046]
Currently, it seems that aggregated failures have an identical key within metadata, and thus when metadata is reported with that key, only one of the multiple aggregated errors is reported. 

AC: Fix this behavior such that, going forward, all aggregated errors are reported by metadata.

**Comment by ruchim** [comment]
@cjllanwarne has this has already been fixed by https://github.com/broadinstitute/cromwell/pull/2055 ?

**Comment by katevoss** [comment]
Wohoo it's fixed!
