### ISSUE TITLE
Standard backend's "<cwd>/tmp" dir means command cannot use own path "tmp"

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2047]
The resolution of #2035 exposed this issue. A centaur issue was mitigated by https://github.com/broadinstitute/centaur/pull/165.

A proper fix in the [StandardBackend](https://github.com/broadinstitute/cromwell/blob/335e9838abce1405f0d26fe18c5dba2dfa7ad0f5/backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala#L173) will enable a centaur test to run a task with command:

```
command {
  echo "hello" > tmp
}
```

This regression centaur test should run on all backends.

**Comment by kshakir** [comment]
See above for the missing centaur tests.

**Comment by ruchim** [comment]
Test merged:
https://github.com/broadinstitute/centaur/commit/c377c658ec47cf3c0acf7966d3f56eaa27362d2c
