### ISSUE TITLE
JES job recovery attempted despite "abort-jobs-on-terminate" enabled

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2050]
As far as I can tell, the timeline is:

 - Shutdown signal received
 - The job is aborted in JES but not removed from the JobStore
 - On restart, the job is recovered because it remains in the JobStore, but in JES it's already been aborted
 - On the console, a "Job Failed" message appears.
 - The EJEA actor dies in an unexpected way (this concerns me *most*. Why isn't the failure cause recorded!)

Not tested on SFS backends.

**Comment by vdauwera** [comment]
@cjllanwarne Might this have been addressed in the recent (c28?) EJEA/better error messages push? We had some FC reports of similar things that were reported resolved after the FC cromwell was bumped to 28 iirc.

**Comment by katevoss** [comment]
@cjllanwarne any update on whether this is still an issue? I know aborts is a tangled mess, is this still part of that?

**Comment by Horneth** [comment]
Fixed by https://github.com/broadinstitute/cromwell/pull/2808
