### ISSUE TITLE
version_scheme: 0.25 or 25?

### ISSUE THREAD

**Issue by ilovezfs** [broadinstitute/cromwell#2052]
See https://github.com/broadinstitute/cromwell/issues/1736

It looks like there's been a regression in the versioning. The last jar was named "cromwell-24.jar" (https://github.com/broadinstitute/cromwell/releases/download/24/cromwell-24.jar) and according to #1736 that was intentional. The new jar is named "cromwell-0.25.jar" not "cromwell-25.jar" (https://github.com/broadinstitute/cromwell/releases/download/25/cromwell-0.25.jar).

Is this a mistake? Shouldn't the file be named cromwell-25.jar?

**Comment by mcovarr** [comment]
Thanks for spotting this!  That is a mistake, we'll fix it.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by ruchim** [comment]
The new release jar has been renamed and updated, thanks for the catch!

**Comment by ilovezfs** [comment]
Thanks! Voilà: https://github.com/Homebrew/homebrew-core/pull/10588
