### ISSUE TITLE
JES WF hangs when Disk Full error encountered

### ISSUE THREAD

**Issue by patmagee** [broadinstitute/cromwell#2054]
Ive noticed a few time when files sizes have been greater than anticipated that the exit status is unable to be written and Cromwell tries to read an empty string from cloud storage. The expected behaviour of this should be to fail the run after some sort of exponential backoff, however the task and the workflow will be listed as Running indefinitely and no new tasks will be launched

**Comment by Horneth** [comment]
This should have been fixed by https://github.com/broadinstitute/cromwell/pull/2056
@patmagee are you still experiencing this issue ?

**Comment by patmagee** [comment]
@Horneth I have run into the disk full error several times and the workflow appropriately fails

**Comment by Horneth** [comment]
Ok I'll close this then. Feel free to re-open if the issue reappears.
