### ISSUE TITLE
Create a "DockerHashLookup" artifact

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2062]
Extract the DockerHashLookup code from `core`, create a new sub-project, and have `sbt assembly` publish an artifact for it in artifactory.
`core` should in turn depend on this new sub-project.

This will enable use of this docker lookup functionality outside of the context of cromwell.

**Comment by katevoss** [comment]
After discussing with @abaumann and @geoffjentry, we are going to plan this for Cromwell 27, our first release of Q4 (April-or-so). Once this is complete, the A-Team will be able to use the Docker Hash library for their own features.

**Comment by katevoss** [comment]
This was covered by @mcovarr 's work in #2048 epic
