### ISSUE TITLE
Error running the GATK WDL best practices pipeline

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2064]
@sooheelee commented on [Mon Mar 13 2017](https://github.com/broadinstitute/dsde-docs/issues/1815)

Investigate whether Cromwell v25 may be misinterpreting our public PESS pipeline script. The "unmerged" label is not present when user runs the workflow. 

```
output_bam_basename = sub(sub(unmapped_bam, sub_strip_path, ""), sub_strip_unmapped, "") + ".unmerged",
```

---
At the bottom of the stack, after Cromwell calls docker, which executes a shell script, the following shell command fails:

 java -Xmx3000m -jar /usr/gitc/picard.jar \
    SamToFastq \
    INPUT=/cromwell-executions/PairedEndSingleSampleWorkflow/610155cd-e94f-4db2-bd9e-9b2322fc412f/call-SamToFastqAndBwaMem/shard-0/inputs/home/orodeh/genomics-public-data/test-data/dna/wgs/hiseq2500/NA12878/H06HDADXX130110.1.ATCACGAT.20k_reads.bam \
    FASTQ=/dev/stdout \
    INTERLEAVE=true \
    NON_PF=true | \
  /usr/gitc/bwa mem -K 100000000 -p -v 3 -t 16 $bash_ref_fasta /dev/stdin -  2> >(tee genomics-public-data/test-data/dna/wgs/hiseq2500/NA12878/H06HDADXX130110.1.ATCACGAT.20k_reads.unmerged.bwa.stderr.log >&2) | \
  samtools view -1 - > genomics-public-data/test-data/dna/wgs/hiseq2500/NA12878/H06HDADXX130110.1.ATCACGAT.20k_reads.unmerged.bam && \
  grep -m1 "read .* ALT contigs" genomics-public-data/test-data/dna/wgs/hiseq2500/NA12878/H06HDADXX130110.1.ATCACGAT.20k_reads.unmerged.bwa.stderr.log | \
  grep -v "read 0 ALT contigs"

The input file exists, but something goes wrong, and the outputs are not generated. This caused the rest of the pipeline to fail. Perhaps that provides more debugging information. 

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/37003#Comment_37003

---

@sooheelee commented on [Mon Mar 13 2017](https://github.com/broadinstitute/dsde-docs/issues/1815#issuecomment-286223385)

Since Kate said she hasn't answered any questions, perhaps she would like to take ownership of this one. I've also gone ahead and asked two devs.

---

@sooheelee commented on [Mon Mar 13 2017](https://github.com/broadinstitute/dsde-docs/issues/1815#issuecomment-286238890)

Devs are busy and say to send this to redteam@broad. So @katevoss if you find there is no obvious answer, please be sure to seek help.

---

@sooheelee commented on [Mon Mar 13 2017](https://github.com/broadinstitute/dsde-docs/issues/1815#issuecomment-286242796)

@ruchim will look into this

**Comment by katevoss** [comment]
@ruchim I believe this issue has been resolved on the forum, is there anything else you need from me?

**Comment by vdauwera** [comment]
We'll follow up with a documentation task.
