### ISSUE TITLE
Cromwell hangs when it cannot find the WDL for a sub-workflow

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2066]
- local backend
- cromwell-0.25
- using docker
- single workflow mode

The WDL is in GATK protected.  https://github.com/broadinstitute/gatk-protected/blob/master/scripts/mutect2_wdl/mutect2_multi_sample.wdl

The WDL functions fine, in general, but the sub-workflow WDL needs to be local to the cromwell execution call.  If it is not there, cromwell cannot find the sub-workflow WDL and then it hangs.

See an example of the hanging in automated gatk-protected M2 testing:

https://travis-ci.org/broadinstitute/gatk-protected/jobs/210985238

I had to manually stop the build, since it would hang forever otherwise.

**Comment by cjllanwarne** [comment]
Note to fixer: also investigate why the centaur test `missing_imports` failed to catch this
