### ISSUE TITLE
cromwell failing process workflows after restart

### ISSUE THREAD

**Issue by gdlex4015** [broadinstitute/cromwell#2067]
I was running a bunch of workflows (same wdl, same method) when we had to restart and redeploy cromwell service and I got Errors with no visible message, when we dug into the cromwell metadata we discovered this message that Cris interpreted as a restart issue.
message": "Workflow input processing failed:\nWorkflow contains invalid labels JSON: Unexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:\n\n^\n"

**Comment by kshakir** [comment]
Just a reminder, this needs to be eventually added to develop as well before this issue is closed.
