### ISSUE TITLE
Option to enable/disable backends

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2069]
Currently Cromwell ships with local backend enabled by default. I want to add an option to disable all backends (or at least local). 

@kshakir let me know if you need more information.

**Comment by kshakir** [comment]
After discussion, we will resurrect the config named [`backend.backendsAllowed`](https://github.com/broadinstitute/cromwell/commit/9faa735df0039652b124ecc0b7e7e5ffa62fd0ff#diff-29d3e359e75a05cf433ad3abe5f194a8L85), [`backend.allowedBackends`](https://github.com/broadinstitute/cromwell/commit/9faa735df0039652b124ecc0b7e7e5ffa62fd0ff#diff-59ba4e6691e949675b4ccaa65a906e1dL22), or maybe just `backend.allowed` to match the style of the config named `backend.default`.

Whatever the name, only backends found in this explicit list will be loaded. By default, the reference list will only contain "Local". Thus, after upgrading, cromwell will default back to running _only_ the Local backend, until admins/users re-enable the other backends by overriding the list.

**Comment by katevoss** [comment]
So when users upgrade to this version of Cromwell, they will need to re-configure their Cromwell or they will go back to using Local? That will need to be clearly included in the release notes, changelog, and possibly a blog post so users are less likely to miss the update.

**Comment by katevoss** [comment]
Here is a branch with the option to dis/enable Local: https://github.com/broadinstitute/cromwell/compare/ks_allow_backends

**Comment by ruchim** [comment]
Resurrecting this issue as the desire to disable the Local backend is still of interest to the general community, and can be useful from a CaaS perspective. 

While adding an `enable` feature isn't backwards compatible, as everyone is forced to change their application.conf when upgrading. It would be great to implement a `disable` feature, mostly for the case that there is no way to turn off the Local backend otherwise (other than editing the reference.conf directly)

**Comment by kshakir** [comment]
For those coming across this issue, there is already an "alternative" `disable`. Add this to your config file and the "Local" backend will be disabled. 

```hocon
backend.providers.Local.config.root = "/dev/null"
```

**Comment by ruchim** [comment]
Closing this issue as what @kshakir explains above meets the needs on disabling local backend.
