### ISSUE TITLE
Cripple local

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2073]
Add ability to cripple local via the configuration file, for hot-fix 25.

**Comment by kshakir** [comment]
This line will allow cromwell to start, but will fail all the workflows on a Local backend:

```
backend.providers.Local.config.root = "/dev/null"
```

Tested on 24_hotfix (489f66b) and develop (b1039f7).

**Comment by kshakir** [comment]
Deployed in the FC dev repo, PR 349.
