### ISSUE TITLE
I/O Actor blog post

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2075]
Write a blog post for the WDL/Crom Blog about the I/O Actor: how it streamlines I/O operations and gives us a lot more flexibility in how we manage how much data we're slinging around at once, retries, etc. 
This can be anywhere from 3-7 paragraphs long, it's up to you. Please write it in a Google doc to help @sooheelee with reviewing it.
It will be posted here: https://software.broadinstitute.org/wdl/blog.

It would be great to have this ready by Cromwell 26, end of March/beginning of April.

**Comment by sooheelee** [comment]
Ping me when it's ready for review.

**Comment by sooheelee** [comment]
Hey Thibault, can you let me know your timeline for this? I'm going on vacation in a week but want to be available to you to discuss anything you have questions about and also available to give feedback.

**Comment by Horneth** [comment]
Hey, I have started thinking about it but haven't written anything yet. I'll see if I can draft a first version this week at least to get your feedback on it before you go on vacation :)
