### ISSUE TITLE
GCS URLs that are not valid URIs are not supported

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#2078]
The following path isn't copying into the task correctly:

`gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar`

It gives the following message in the JES logs:

```
2017/03/20 15:37:09 I: Docker file /cromwell_root/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar maps to host location /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar.
2017/03/20 15:37:09 I: Copying gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar to /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar
2017/03/20 15:37:09 I: Running command: sudo gsutil -q -m cp gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar
```

And the `exec.sh` that it generates is:
```bash
#!/bin/bash
export _JAVA_OPTIONS=-Djava.io.tmpdir=/cromwell_root/tmp
export TMPDIR=/cromwell_root/tmp

(
cd /cromwell_root
if [ false = false ]; \
  then java -Xmx1g -jar gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar PadTargets --targets /cromwell_root/broad-dsde-methods/th/target/ice_targets.tsv --output targets.padded.tsv \
        --padding 250 --help false --version false --verbosity INFO --QUIET false; \
  else touch targets.padded.tsv; \
fi
)
echo $? > /cromwell_root/PadTargets-rc.txt.tmp
(
cd /cromwell_root

)
mv /cromwell_root/PadTargets-rc.txt.tmp /cromwell_root/PadTargets-rc.txt
```

The WDL that has this issue is:
```
workflow BrokenFilePath {
  File targets = "gs://broad-dsde-methods/th/target/ice_targets.tsv"
  File GATK_protected_jar = "gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar"
  Boolean isWGS = false
  Int padding = 250

  call PadTargets {
    input:
        target_file=targets,
        gatk_jar=GATK_protected_jar,
        isWGS=isWGS,
        mem=1,
        padding=padding
  }
}

task PadTargets {
    File target_file
    Int padding
    File gatk_jar
    Boolean isWGS
    Int mem

    command {
        if [ ${isWGS} = false ]; \
          then java -Xmx${mem}g -jar ${gatk_jar} PadTargets --targets ${target_file} --output targets.padded.tsv \
                --padding ${padding} --help false --version false --verbosity INFO --QUIET false; \
          else touch targets.padded.tsv; \
        fi
    }

    output {
        File padded_target_file = "targets.padded.tsv"
    }

    runtime {
      docker: "broadinstitute/genomes-in-the-cloud:2.2.4-1469632282"
      zones: "us-central1-a us-central1-b"
      disks: "local-disk 200 SSD"
      memory: "6G"
    }
}
```

Note that I have not tried running this with version 25. The problem occurred both on version 24 and in firecloud.

@ruchim @Horneth

**Comment by ruchim** [comment]
Ran it on 25_hotfix, call logs available here:
https://console.cloud.google.com/storage/browser/cloud-cromwell-dev/cromwell_execution/ruchi/BrokenFilePath/16caeb92-3c39-496b-bf44-7cd1e5c33269/call-PadTargets/?project=broad-dsde-cromwell-dev

Failed to delocalize files:
```
2017/03/20 16:48:49 I: Running command: sudo gsutil -q -m cp -L /var/log/google-genomics/out.log /mnt/local-disk/targets.padded.tsv gs://cloud-cromwell-dev/cromwell_execution/ruchi/BrokenFilePath/16caeb92-3c39-496b-bf44-7cd1e5c33269/call-PadTargets/targets.padded.tsv
2017/03/20 16:48:51 E: command failed: CommandException: No URLs matched: /mnt/local-disk/targets.padded.tsv
CommandException: 1 file/object could not be transferred.
 (exit status 1)
```

Stderr:
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.TdaNa3
Error: Could not find or load main class org.broadinstitute.hellbender.Main
```

**Comment by meganshand** [comment]
Yeah so it looks like the exact same thing happened. It can't delocalize the output file because it was never created. In the JES logs the same message as before happened again:

```
2017/03/20 16:44:51 I: Docker file /cromwell_root/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar maps to host location /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar.
2017/03/20 16:44:51 I: Copying gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar to /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar
2017/03/20 16:44:51 I: Running command: sudo gsutil -q -m cp gs://bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar /mnt/local-disk/gs:/bg_tag_team/Tumor_Only_Resources/gatk-protected-1.0.0.0-alpha1.2.4.jar
```

**Comment by Horneth** [comment]
@meganshand @ruchim So I found the root of the problem. Cromwell tries to parse gcs paths as `URI`s. The bucket is parsed as the hostname. Underscores are not valid characters for hostnames. This messes up with a bunch of things that end up manifesting as the jar file not being properly handled in the script.

Since underscores are considered valid in a GCS bucket name I think we should be able to parse them regardless of them being valid hostname characters. I'll label this ticket as a bug.

**Comment by Horneth** [comment]
@katevoss Just to add to this, as per google documentation, bucket names with `_` are allowed but [not recommended](https://cloud.google.com/storage/docs/naming):

> Also, for DNS compliance and future compatibility, you should not use underscores (_) or have a period adjacent to another period or dash. For example, ".." or "-." or ".-" are not valid in DNS names.

**Comment by meganshand** [comment]
@Horneth @katevoss That's good to know. I've asked Niall to make a new bucket without underscores, so hopefully this will be less urgent than I originally thought. Sorry for the confusion.

**Comment by meganshand** [comment]
@katevoss Niall created a new bucket, so this issue is no longer a priority for us. Thanks!

**Comment by katevoss** [comment]
@meganshand thanks for the update! I'll lower this in priority.

**Comment by ernfrid** [comment]
I think this has just bitten me as well. I am reading from a  collaborator's bucket of several hundred terabytes that has underscores in the bucket name. I _think_ this is resulting in the input files being unhashable and thus disabling call-caching.

The error I see (minus a real bucket path) is:

```
[2017-05-15 17:08:12,44] [error] a05af6bd:Pre_Merge_SV.Extract_Reads:21:1: Hash error, disabling call caching for this job.
java.lang.Exception: Unable to generate input: File input_cram hash. Caused by java.lang.IllegalArgumentException: Could not find suitable filesystem among Gcs to parse gs://bucket_with_underscores/my.cram.
```

**Comment by mcovarr** [comment]
The current `JesExpressionFunctions#preMapping` logic does not distinguish between a path that fails to parse as a valid GCS URI for being relative to the call root and a path that fails to parse for being a fully qualified `gs://uri_with_underscores/file.txt` containing invalid characters in the bucket name.

**Comment by mcovarr** [comment]
I should have made this explicit in the previous comment: 

I don't currently see a way we can support underscores in bucket names as long as we're using Google's GCS NIO filesystem.  But I do think Cromwell can and should fail with useful and timely error messages when presented with bucket names that will not work.
