### ISSUE TITLE
JobStoreWriterActor can become a bottleneck when lots of jobs are finishing at the same time

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2085]
When a lot of jobs are finishing at the same time and all try to write their result to the jobstore, it can become a bottleneck.
A possible solution (or improvement) would be to batch those requests to the DB.

**Comment by mcovarr** [comment]
You mentioned the dependency of job store simpletons on job store entries, is that still a complication here?

**Comment by Horneth** [comment]
Yes, it makes it more difficult to batch but I'm sure there's some slick magic that can make it happen ?
But yeah pretty much those events arrive in the form of

`JobStoreEntry -> List(JobStoreSimpleton)`

The simpletons have a FK mapping to their job store entry, which means job store entries have to be inserted first and the PK collected before simpletons can be inserted.
