### ISSUE TITLE
Lots of metadata writes, even batched, can be time consuming

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2086]
In a case where a very large amount of metadata needs to be written at the same time, even with batching, it can take a significant amount of time for the DB to absorb it, in which case the eventual consistency can be of several minutes.
A pathological test case with a  200K wide scatter, all finishing at the same time but with minimal metadata entries to be written (1 input, no output, not backend execution events), can take around 15 minutes after the workflow finished to be reported as "Done" in the metadata.

**Comment by geoffjentry** [comment]
Is this on MySQL or CloudSQL? The data won't be the same.

**Comment by Horneth** [comment]
MySQL

**Comment by geoffjentry** [comment]
Right, so when I put in the batched metadata i ran into exactly this. I talked to bernick and the tl;dr was that he felt CloudSQL would be able to take this much further (hooray for our production) but any MySQL instance would need proper tuning to handle a load like this, and that that point it'd be a YMMV situation where every setup would be a bit different.

If you're poking around this space try pointing at a CloudSQL and see if that helps, I never did verify that.

**Comment by Horneth** [comment]
Ok I'll try that

**Comment by mcovarr** [comment]
Not seeing this at the scale we're currently interested in, but we can reopen if necessary.
