### ISSUE TITLE
Add tests for aborts

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2088]
Write (and run) a bash script for sending the abort, wait, and check the ~~response~~ job has actually aborted.

**Comment by geoffjentry** [comment]
a big issue w/ abort is not that it doesn't claim it aborted in the response but all hell breaks loose internally :)

**Comment by kcibul** [comment]
ToL about a few ways to assert deeper on this -- for JES, you could label
the VM with a random number (so you can find it later), then assert you can
find it out of band using gcloud commands, do the abort, then assert it
goes away.  Similar for the local backend using a command with some unique
value that you can grep a ps for.

-------------------------------
Kristian Cibulskis
Engineering Director, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by geoffjentry** [comment]
Right, there are ways one can look deeper, I was just commenting that just looking at our response wasn't going to provide any comfort that we were actually doing the right thing here.

**Comment by katevoss** [comment]
@geoffjentry how much effort would this take? And how can it be automated?

**Comment by katevoss** [comment]
@Horneth how about this ticket for testing aborts?

**Comment by Horneth** [comment]
:+1:

**Comment by Horneth** [comment]
centaur now has abort tests
