### ISSUE TITLE
Consistently resolve Docker labels to hashes within a workflow

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2094]
To be further refined:
Move docker hash request/response handling from Job Preparation to Workflow Materialization (or similar).

**Comment by mcovarr** [comment]
I'd suggest titling this something like "Consistently resolve Docker labels to hashes within a workflow" that captures the point of this, if in fact that is the point.  😄

**Comment by katevoss** [comment]
@mcovarr is this the "make docker lookup it's own separate project" issue that you completed?

**Comment by mcovarr** [comment]
The docker lookup as a separate project was #2099, which is complete.  @Horneth is currently working on this ticket.

**Comment by Horneth** [comment]
I rebased and cleaned up the branch I have: https://github.com/broadinstitute/cromwell/tree/cromwell-2094

What's left is:

- Handle failure cases in `WorkflowDockerLookupActor` (see FIXMEs)
- Figure out the right way to handle the tag/hash pair: Currently the runtime attribute value is overridden with the hash + we pass a `CallCacheEligible` object in the descriptor. This is probably too much. We could live the runtime attribute as is and pass the hash only if needed and successfully retrieved ?
- Have backend report if it used the hash or the tag when a call runs. Note that this could affect call caching I think ? (We need to wait from the backend to know which was used before being able to compute the real call hash ? What if they used the tag ?)
- Test it (unit ? centaur ?)
