### ISSUE TITLE
Need a HOWTO on creating a refresh token and how to modify a configuration file appropriately

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2100]
This is to enable running cromwell (on JES) in single workflow mode and to use the authentication of the user for bucket access.

This ticket is to provide documentation on how to do that.

@Horneth and @kshakir helped me do it, but I'd like general instructions so that we do not have to nag the red team.  I cannot recall all of the steps.

**Comment by LeeTL1220** [comment]
@katevoss

**Comment by katevoss** [comment]
Moving this to DSDE-docs

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/dsde-docs #1916](https://github.com/broadinstitute/dsde-docs/issues/1916) via [**ZenHub**](https://www.zenhub.com/)
