### ISSUE TITLE
Add ability to get count of results returned by query endpoint without full results

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#2105]
For large return sets, paging seems appropriate for query results.  However, paging works best when the total number of results is known.  It would be nice to have an extra object to the query return JSON that would return the total number of records that would be returned if all were returned at once.  

```
{ "total": TOTAL_NUMBER_RECORDS,
  "page": REQUESTED_PAGE,
  "pagesize": REQUESTED_PAGESIZE
}
```

Having something like this makes writing dashboards and the like much easier.

**Comment by ruchim** [comment]
@seandavi I believe the requirements listed in this issue have been addressed by previous PRs:
- https://github.com/broadinstitute/cromwell/pull/3126 -- total count of query results
- https://github.com/broadinstitute/cromwell/pull/830 -- page number/page size 

Closing it for now, feel free to re-open if you have questions/concerns.

**Comment by seandavi** [comment]
Thanks, @ruchim. I had meant to comment/close.
