### ISSUE TITLE
Support query by customLabel

### ISSUE THREAD

**Issue by seandavi** [broadinstitute/cromwell#2106]

**Comment by katevoss** [comment]
@ruchim I believe this is now supported as of Cromwell 27 (released yesterday).

**Comment by katevoss** [comment]
See the [Readme](https://github.com/broadinstitute/cromwell/blob/develop/README.md#get-apiworkflowsversionquery) for more information.

**Comment by seandavi** [comment]
Thanks! Appreciate the work on this.
