### ISSUE TITLE
Migration from 19-42b47c1 to 25 (latest) 

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2108]
@hjfbynara has started testing the migration from 19 -> 25 and he noticed restart_and_recover_migration.xml seems to be throwing an unhelpful liquibase error.

**Comment by ruchim** [comment]
assigning to @katevoss for bug level triage.

**Comment by katevoss** [comment]
Is the problem that the error message is unhelpful, or that there is an error in the migration that is blocking?

**Comment by ruchim** [comment]
@katevoss  error that is blocking the migration

**Comment by katevoss** [comment]
@hjfbynara are you still having trouble with the migration? If so, reach out to @mcovarr, who is our bug smasher for the next two weeks.

**Comment by vdauwera** [comment]
I'm going to assume this was resolved but feel free to reopen if I'm wrong
