### ISSUE TITLE
Testing Database Migration: spoof data and migrate

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2110]
Before releasing a jar, run it on a different database. Test that the liquid-base scripts work. 
Ask each time. 

Standup database, load data in. Migrate. Start running workflows and see if it works.

**Comment by katevoss** [comment]
We should still do this, @geoffjentry do you have an estimate of how long this would take?

**Comment by geoffjentry** [comment]
IMO this would be handled in spirit by that staging environment we're talking about setting up.

**Comment by katevoss** [comment]
Okay, in that case I'll add it to the CaaS milestone as "something to make sure is covered" by our work there.

**Comment by ruchim** [comment]
@kshakir I believe this is addressed by https://github.com/broadinstitute/cromwell/pull/4132. Feel free to re-open as needed.
