### ISSUE TITLE
SRE: Add support for Sentry to Cromwell

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2120]
As a Site Reliability Engineer (SRE) , I would like to have Cromwell support Sentry (https://sentry.io) to capture and report exceptions.  This will allow me to better support our runtime operations and know when the system is functioning properly.

This could be as simple as a document detailing how to deploy cromwell with the appropriate configuration, or it may involve code changes.  @ansingh7115 is working on this in workbench at the moment and should be able to provide more information.  @davidbernick can also provide configuration details.

**Comment by davidbernick** [comment]
Can this get done soon?

**Comment by geoffjentry** [comment]
@davidbernick It's part of our QGoals

**Comment by geoffjentry** [comment]
Closed via #2541 - will be in Cromwell 29.
