### ISSUE TITLE
graph-building barfs on aliased calls

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#2125]
Currently it barfs on aliased call commands yielding the following error:
```
Exception in thread "main" wdl4s.parser.WdlParser$SyntaxError: ERROR: Expression references output on call that doesn't exist (line 1572, col 5):

    ValidateCram.*
    ^
     
	at wdl4s.Workflow.$anonfun$expandedWildcardOutputs$5(Workflow.scala:166)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.immutable.List.flatMap(List.scala:341)
```

FYI: `ValidateCram` was called as such in the file:
```
 call ValidateSamFile as ValidateCram {
    input:
      input_bam = ConvertToCram.output_cram,
      input_bam_index = ConvertToCram.output_cram_index,
      report_filename = sample_name + ".cram.validation_report",
    .....
```

**Comment by cjllanwarne** [comment]
@yfarjoun - Just as a warning, this style of outputs is deprecated and might go away in a future version of WDL.

**Comment by yfarjoun** [comment]
what do you mean by "this style of outputs"?

**Comment by cjllanwarne** [comment]
Oops, that wasn't a particularly useful comment from me! Here's @Horneth giving the full explanation: https://github.com/broadinstitute/cromwell/blob/develop/CHANGELOG.md#annex-a---workflow-outputs

Basically, the wildcards (`*`) have been deprecated in favor of outputs with explicit types and names, as a necessary prerequisite for subworkflows.

All that said, I still think it's worth fixing this problem!

**Comment by Horneth** [comment]
I can't reproduce this. I ran the following WDL without issues:

```
task test {
    command {
        echo "hello"
    }
    output {
        String o = read_string(stdout())
    }
}

workflow workflow_test {
    call test as aliased_test
    output {
        aliased_test.*
    }
}
```

@yfarjoun do you happen to have the full WDL ?

**Comment by yfarjoun** [comment]
it's not about running the wdl...it's about generating the graph using pywdl

**Comment by geoffjentry** [comment]
@yfarjoun PyWDL is unsupported as per the first line in the [README](https://github.com/broadinstitute/pywdl/blob/master/README.md)

**Comment by vdauwera** [comment]
The E Pam pipeline builder has actually gotten pretty good at making graph visualizations, you should try that yossi

**Comment by vdauwera** [comment]
Here's the URL to the EPAM pipeline builder: http://pb.opensource.epam.com/

I assume this can be closed but crommers can feel free to reopen if I am in error
