### ISSUE TITLE
Make wdlTool graph output more useful

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#2126]
The (no-longer maintained) pywdl repo has a graph building tools (from wdl) that would put the nodes that comprise a scatter block in a small rectangle labeled by the scatter variable. It would be really nice to have a similar result from the graph tool in wdlTool.

**Comment by geoffjentry** [comment]
FWIW I'm pretty sure that functionality wasn't even developed by us in the first place.

Also not to spoil things but I think if one were to wait a few weeks one might find something far better magically appear.

**Comment by yfarjoun** [comment]
not to spoil things?
