### ISSUE TITLE
CromIAM

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2127]
IAM CromIAM

**Comment by katevoss** [comment]
@geoffjentry as a part of your spec-ing of CromIAm, we'd like to add to the Role vs. Permission chart on [this page in confluence](https://broadinstitute.atlassian.net/wiki/display/GAWB/Workspace+Access+Control+-+User+experience), with the FireCloud roles and what actions they can take in Cromwell. We'd like you (and @cjllanwarne) to add the Cromwell actions, and Tiffany and I can help with deciding what roles have permission to do the actions.

**Comment by geoffjentry** [comment]
@katevoss Should be squared away, let me know if you need anything more

**Comment by katevoss** [comment]
@geoffjentry any more issues for this Epic? Or are we waiting for SamIAM?

**Comment by geoffjentry** [comment]
At the moment I think it's just waiting to be able to do query. We're also not using it in anger so issues might pop up once we start to do so but we can always make new issues for that.

**Comment by katevoss** [comment]
@geoffjentry any new issues to add here?

**Comment by geoffjentry** [comment]
Still blocked on query, which is blocked on collections, which is blocked on many things

**Comment by katevoss** [comment]
As a **user running workflows through a hosted Cromwell**, I want **to be able to authenticate and authorize permissions to my workflows**, so that **my labmates and I can view and take action on the workflows for which we have the right permissions**.

- Remaining work: adding Collections to the /Query endpoint
