### ISSUE TITLE
Abstract Cromwell client code

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2128]
Centaur contains a semi-complete Cromwell client library. CromIAM will also need something similar. Abstract the concept into an artifact (ideally contained as a subproject in the Cromwell repo unless that doesn't make sense for some reason) and have both Centaur and CromIAM using this artifact.

**Comment by ruchim** [comment]
@cjllanwarne  is this the issue associated to https://github.com/broadinstitute/cromwell/pull/2169?
