### ISSUE TITLE
Identify how to grab identify from HTTP header

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2132]
We should be able to grab the principal ID from the HTTP header via the apache proxy. Get this info from DevOps and demonstrate capability to grab this in the HTTP code. I suspect the easiest path here would be to talk to some folks in firecloud on how to handle this for testing and such when the proxy is not available

**Comment by cjllanwarne** [comment]
Closed by https://github.com/broadinstitute/CromIAM/pull/7
