### ISSUE TITLE
Query endpoint

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2138]
The how is still TBD but the end result is the query endpoint shall only return results for workflows the user has access to

**Comment by katevoss** [comment]
As a **user accessing CaaS**, I want **to query a Collection of workflows**, so that I can **view the status of many workflows at once and get the results quickly**.
- Effort: **Small to Medium** @geoffjentry do you agree?
- Risk: **Small**
- Business value: **Medium to Large**

**Comment by geoffjentry** [comment]
This is going to be a pain in the ass
