### ISSUE TITLE
Create a mock WDL for new JG 

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2144]
Create a mock WDL that mimics the shape of the new JG WDL w/o actually doing anything of note so that we can run this way mo faster. It sounds like @jsotobroad might have already done this or something close to it.

**Comment by jsotobroad** [comment]
This file should be similar enough to what a final JG wdl will look like 

[mock_3.txt](https://github.com/broadinstitute/cromwell/files/900002/mock_3.txt)

You just have to set `num_partitions` to however wide you want the scatters to be - should mimic how many intervals you are splitting the genome into.

**Comment by Horneth** [comment]
Thanks @jsotobroad
