### ISSUE TITLE
Iterate towards 10K w/ mock WDL

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2145]
Iterate at whatever pace makes sense towards running a 10K JG w/ the mock WDL. If there issues (errors and/or things which seem unreasonably pokey) follow this decision tree:

- If the problem seems small, fix it and continue
- If the problem seems large but there's a clear hack/workaround, file a ticket and do the hack/workaround then continue
- If the problem seems large but there is no clear hack/workaround, bring this up with the team to figure out how to proceed

**Comment by ruchim** [comment]
Closing this issue as @Horneth has successfully run the 10K mock WDL.
