### ISSUE TITLE
No coercion defined from WdlString(true) and WdlString(false) to WdlBooleanType

### ISSUE THREAD

**Issue by jbuhacoff** [broadinstitute/cromwell#2152]
Since read_json and write_json are not implemented yet, I'm documenting for my team which types we can serialize and de-serialize using the available library functions.

I wrote a pair of WDLs, one to write data to files and another to read data from files:

[test_read_data.wdl.txt](https://github.com/broadinstitute/cromwell/files/901057/test_read_data.wdl.txt)
[test_write_data.wdl.txt](https://github.com/broadinstitute/cromwell/files/901056/test_write_data.wdl.txt)

When I tested these I noticed that I can read and write a single Boolean value, and I can write complex types with Booleans, but reading  Array[Boolean] didn't work and neither did reading any Map[Boolean,?] or Map[?,Boolean]. 

**What is the best way to read in complex types that involve Boolean?**

The error I got when trying to read Array[Boolean] looks like this:

> Error: No coercion defined from 'WdlString(true)' of type 'class wdl4s.values.WdlString' to WdlBooleanType$

The errors I would get for the complex types involving Boolean look like this:

> Error: Failed to coerce one or more keys or values for creating a Map[String, Boolean]: java.lang.IllegalArgumentException: No coercion defined from 'WdlString(true)' of type 'class wdl4s.values.WdlString' to WdlBooleanType$

> Error: Failed to coerce one or more keys or values for creating a Map[Int, Boolean]: java.lang.IllegalArgumentException: No coercion defined from 'WdlString(true)' of type 'class wdl4s.values.WdlString' to WdlBooleanType$

Here are the files generated by test_write_data.wdl that I can read back in with test_read_data.wdl:

[a_false.txt](https://github.com/broadinstitute/cromwell/files/901058/a_false.txt)
[a_float.txt](https://github.com/broadinstitute/cromwell/files/901061/a_float.txt)
[a_string.txt](https://github.com/broadinstitute/cromwell/files/901063/a_string.txt)
[a_true.txt](https://github.com/broadinstitute/cromwell/files/901062/a_true.txt)
[a_zero.txt](https://github.com/broadinstitute/cromwell/files/901059/a_zero.txt)
[arr_float.txt](https://github.com/broadinstitute/cromwell/files/901060/arr_float.txt)
[arr_int.txt](https://github.com/broadinstitute/cromwell/files/901064/arr_int.txt)
[arr_string.txt](https://github.com/broadinstitute/cromwell/files/901065/arr_string.txt)
[map_float_float.txt](https://github.com/broadinstitute/cromwell/files/901066/map_float_float.txt)
[map_float_int.txt](https://github.com/broadinstitute/cromwell/files/901069/map_float_int.txt)
[map_float_string.txt](https://github.com/broadinstitute/cromwell/files/901067/map_float_string.txt)
[map_int_float.txt](https://github.com/broadinstitute/cromwell/files/901068/map_int_float.txt)
[map_int_int.txt](https://github.com/broadinstitute/cromwell/files/901073/map_int_int.txt)
[map_int_string.txt](https://github.com/broadinstitute/cromwell/files/901070/map_int_string.txt)
[map_string_float.txt](https://github.com/broadinstitute/cromwell/files/901072/map_string_float.txt)
[map_string_int.txt](https://github.com/broadinstitute/cromwell/files/901074/map_string_int.txt)
[map_string_string.txt](https://github.com/broadinstitute/cromwell/files/901071/map_string_string.txt)

Here are the files generated by test_write_data.wdl that I cannot read back in with test_read_data.wdl:

[arr_boolean.txt](https://github.com/broadinstitute/cromwell/files/901077/arr_boolean.txt)
[map_boolean_boolean.txt](https://github.com/broadinstitute/cromwell/files/901081/map_boolean_boolean.txt)
[map_boolean_float.txt](https://github.com/broadinstitute/cromwell/files/901079/map_boolean_float.txt)
[map_boolean_int.txt](https://github.com/broadinstitute/cromwell/files/901080/map_boolean_int.txt)
[map_boolean_string.txt](https://github.com/broadinstitute/cromwell/files/901082/map_boolean_string.txt)
[map_float_boolean.txt](https://github.com/broadinstitute/cromwell/files/901078/map_float_boolean.txt)
[map_int_boolean.txt](https://github.com/broadinstitute/cromwell/files/901083/map_int_boolean.txt)
[map_string_boolean.txt](https://github.com/broadinstitute/cromwell/files/901084/map_string_boolean.txt)

**Comment by jbuhacoff** [comment]
The test_read_data.wdl has lines commented out that resulted in errors I'm reporting here.

**Comment by katevoss** [comment]
Hi @jbuhacoff, welcome to our humble repo! I'd recommend posting your questions to our [forum on the WDL and Cromwell website](http://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team). Our team will get back to you with an answer about what they recommend.

**Comment by aednichols** [comment]
The premise of this ticket - "read_json and write_json are not implemented yet" - has long ago passed into history, closing.
