### ISSUE TITLE
Optional File input file path passed as gs:// string instead of localized file path

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/cromwell#2162]
Happens with Cromwell 24 and pretty sure also Cromwell 25 

I was running the GOTC single-sample WDL and found that in a call of a task where one of the input files was set to optional (but a file path was specified), the call failed because the path passed to the command was the gs:// path instead of the localized path. 

Can provide more details + logs if this is something you haven't seen before.

**Comment by mcovarr** [comment]
I think this should be fixed in 25 hotfix or develop.  I entered #1945 a while back for what sounds like the same issue.

**Comment by katevoss** [comment]
@vdauwera is this still a problem? Or can it be closed?

**Comment by vdauwera** [comment]
No idea -- I'll close and if it happens again we'll reopen.
