### ISSUE TITLE
Bring sanity to Config backend docs

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2166]
Currently we have docs for the SGE backend which is a bit of a hodgepodge between describing the historical SGE backend and the flexibility of the Config backend. There's also doc for the HTCondor backend which as of #2141 is also using the Config backend. 

Change all of this to demonstrate how one can use the Config backend, primarily from the lens of an HPC user. Make it clear that it can handle most use cases and provide a couple of generic examples (e.g. SGE)

**Comment by katevoss** [comment]
Is this a purely documentation fix, or is there dev effort too?

**Comment by geoffjentry** [comment]
Purely doc.

**Comment by katevoss** [comment]
Moving over to DSDE-docs

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/dsde-docs #1959](https://github.com/broadinstitute/dsde-docs/issues/1959) via [**ZenHub**](https://www.zenhub.com/)
