### ISSUE TITLE
Additional retries for preemption, when under 10 minutes

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2167]
Feature request from @gsaksena:

Often times a job is preempted in under 10 minutes, it would be nice to retry those jobs more than the runtime attribute for preemptible. Users are not charged within the first 10 minutes, so it is a cheap way to try to save costs while only taking a bit more time. 

From Google, it is likely that if a machine will be preempted, it will be within the first 10-20 minutes.

**Comment by geoffjentry** [comment]
So what if a user actually means they only want to preempt N times no matter what? How do we know which the user really means?

Sometimes it's about time, not cost.

**Comment by gsaksena** [comment]
If preemptible is requested, cost is being considered a higher priority
than time.  Preempting within 10-20 minutes is not going to rack up much
cost.

I could imagine a default cap of 10-20 for the number of early retries.  If
the user cares a lot about time, it may be useful to expose it as a
parameter, but this seems less important for the common case.

**Comment by geoffjentry** [comment]
@gsaksena Not necessarily. I know that there are people who have tuned their preemption number specifically thinking about total time on top of cost. 

I'm not saying that this is a bad idea but it's not necessarily as cut & dry as you're making out.

**Comment by vdauwera** [comment]
From the point of view of the wider user community (which reaches far outside the Broad's walls), it would be difficult to justify (not to mention communicate and support) an implicit retry mechanism that would effectively override the request stated by the user in their WDL. So we would have to expose that second setting, but then that increases the technical complexity that we need to maintain and support as well.

Additionally, this would be vulnerable to business decisions by Google -- for example, what if they change the no-charge duration cutoff in response to a sudden dramatic increase of retries on early-preemption jobs? 

Generally speaking I believe the best thing we can do for the user community is provide a transparent way for people to understand what are the odds and tradeoff of preemption, and to control the setting depending on their time & cost constraints (ie how much they're willing to gamble).

**Comment by cjllanwarne** [comment]
@gsaksena -

Be aware that preemption has temporal locality. If a job is preempted in 10 minutes 3 times in a row, it's probably because the Google servers are busy, and therefore the next 10 preemptible VMs are likely to be preempted too.

Between this and the other issue, it sounds like what you're really requesting is time-limited (rather than retry-limited) preemptions. E.g. "try this job preemptibly for up to 5 hours, but after that fall back to non-preemptible and just get it done"

**Comment by katevoss** [comment]
Closing this issue as it sounds like the result is that there is not enough of a consensus that users want this as an option. Feel free to reopen if there are additional use cases, like for "retry for X amount of time".
