### ISSUE TITLE
Upgrade preempted VMs if killed after 24 hours

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2168]
Feature request from @gsaksena:
If a preemptible VM is killed because it hit the time-out (of 24 hours), then it should automatically be upgraded to a full price VM (non-preemptible). Currently it would retry the number of times it would try, per the preemptible runtime attribute. So if preemptible is 3, then it would take 3 days to upgrade to a non-preemptible VM.

**Comment by geoffjentry** [comment]
The current behavior depends on if this time out would cause GCP to return a preemption signal or another termination signal. They're not the same buckets of retries.

**Comment by mcovarr** [comment]
We could also look at the elapsed time.

**Comment by cjllanwarne** [comment]
We'd need a way to detect that a job was timed out rather than genuinely preempted (either another error code or by analyzing the total run time).
We'd also need a special case in the "start this as a preemptible VM?" logic to not start the subsequent job preemptibly.

**Comment by geoffjentry** [comment]
I wouldn't want to just look at elapsed time. What if google changes their rules? I'd want this information to come from Google.

**Comment by gsaksena** [comment]
If the job took 23 hours 50 minutes and was preempted, it would be reasonable to treat it the same as if it timed out - it would be unlikely to succeed if relaunched on another preemptible.  Of course it would be better if you can distinguish the two via signals, but in practice the time approach would be just as good.

**Comment by katevoss** [comment]
As a **user running workflows on PAPI**, I want **my workflow to be upgraded from preemptible to regular compute if it is killed after 24 hours rather than retrying**, so that I can **avoid retrying on a job that will need more than 24 hours to run**.
- Effort: **@geoffjentry** ?
- Risk: **Small to Medium**
   - We'd need a way of being certain that the job was killed due to timeout, rather than another reason, to prevent from upgrading jobs that the user doesn't want upgraded.
   - The information about a preemptible VM timing out should come from Google.
   - This should be an "opt-in" feature, so users do not have the default behavior change from under them.
- Business value: **Medium**

**Comment by geoffjentry** [comment]
@katevoss If this is in fact something we actually want to do it'd be relatively easy to put in.

**Comment by mbookman** [comment]
+1 to this feature.

Is there a feature request submitted to the Cloud Health team to have the Pipelines API v2 distinguish regular preemption vs. preemption at 24 hours?

We needed to workaround this recently for an RNA alignment workflow (using STAR). What we did was to use the [timeout](https://linux.die.net/man/1/timeout) command:

```
timeout 23.5h STAR <args>
```

- We made it 23.5 hours to account for localization and delocalization time.
- By using the timeout, we got a hard-failure and avoided the "run 24 hours and get preempted and retried" cycle.
- We then manually re-ran these failures, setting the preemptible retries to 0 (and removing the timeout). 

Managing the workflows in Terra made this all relatively painless.

**Comment by gemmalam** [comment]
@mbookman our backlog has been moved to Jira. Here is the link to this [ticket](https://broadworkbench.atlassian.net/browse/BA-2168) 
You will need to create an account to access this ticket.

I defer to @ruchim for priority of this feature.
