### ISSUE TITLE
Batch management program

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2171]
Create a Python program which can interact with Cromwell but provide batching capabilities, submitting a batch of workflows but then being able to manage them as a group, e.g. getting status, aborting, etc.

**Comment by katevoss** [comment]
@ruchim You didn't do this as a part of your batching work, right? If so I'm going to deprioritize it.

**Comment by katevoss** [comment]
@geoffjentry resurrecting this, I'm not sure if it was ever completed. Can you tell me more about what the batch management program does?

**Comment by geoffjentry** [comment]
It was done but it wasn't really intended to be an end user product. We were using this as a way to introduce some functionality outside of Crowell to inform what we wanted to put *in* cromwell
