### ISSUE TITLE
Job Status Metadata events with same timestamp

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2173]
It appears to be possible for some of the `executionStatus` metadata events for the same job to have the exact same timestamp values.
This seems very unlikely to be possible in real life. Investigate wether or not this behavior is correct.

![screen shot 2017-04-13 at 10 58 28 am](https://cloud.githubusercontent.com/assets/2978948/25010604/a060fb6c-2038-11e7-8317-78b7e85873a1.png)

**Comment by Horneth** [comment]
I believe this might be a consequence of the fact that the `WorkflowExecutionActor` is responsible for sending status updates to the metadata, and under the current load it accumulates those updates in its mailbox. Those updates then get processed and it's possible that 2 status updates close to each other in the mailbox end up generating the same timestamp.

Those timestamps reflect the `WEA` view of the world, which might be delayed compared to reality if it's very busy. If that's not the desired behavior we could maybe have each job (EJEA) independently send status updates.

**Comment by geoffjentry** [comment]
If that's the case then I think that as long as we get the desired result (via CRDTs, etc) that it doesn't really matter. That timestamp is really just there to determine "what came last" and if we're not making incorrect decisions based off of that information then it shouldn't matter.

**Comment by Horneth** [comment]
Yeah I agree. All right then I'll close this for now and if something else pops up that doesn't fit with this explanation we can reopen it
