### ISSUE TITLE
Create an even interval list with 5k and 10k shards

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2175]
For Joint genotyping, 3 intervals files are used

1. A GATK-style interval list
2. A Padded version of the above
3. A tile-db partition list of the above

I *believe* the most accurate version of the above are in these files
gs://broad-gotc-dev-storage/dshiga/wgs_split_even_tiledb.hg38.v3.interval_list
gs://broad-gotc-dev-storage/dshiga/wgs_split_even_tiledb.hg38.v3.padded.interval_list
gs://broad-gotc-dev-storage/dshiga/wgs_split_even_tiledb.hg38.v3.padded.tiledb

For calling 20k samples we had 2500 shards.  For 50k samples, we need somewhere between 5k and 10k shards.  

This ticket is to create those two sets of interval files, for 5k shards and 10k shards.

**Comment by kcibul** [comment]
@geoffjentry @Horneth

**Comment by eitanbanks** [comment]
@kcibul what's the downside of just splitting every interval in the original set (N=2500) into 4 even pieces?  Is it just that we won't be able to ensure that each quarter is equally balanced?  Because rather than spending effort balancing shards, I'd rather optimize the GATK code.  Thoughts?

**Comment by kcibul** [comment]
That might be a reasonable place to start.  Part of the confusion (that I just want someone to get right!) is what that list should be.  There's v2 and v3, which are "right" but only about 1000 shards.  Then there are several flavors of what was used to do the 20k, which is the ~20k shards.  

So the task is simply getting someone who knows to (a) pick the best starting point (something with the right territory and somewhat even) and (b) do the splitting 

Thinking out loud... Do you think that the balance of the shards changes with the number of samples?  That is... could you take a 100-sample call set and use it to empirically balance the shards and then that would scale to 50k?  or does the distribution change significantly as you add more samples?

**Comment by jsotobroad** [comment]
I talked to @dshiga about how gs://broad-gotc-dev-storage/dshiga/wgs_split_even_tiledb.hg38.v3.interval_list was created.  If you want an interval list for hg38 then that is the best interval list we have created thus far.  `v1` is our first crack at creating an interval list that was "even" in terms of run times starting with histograms created from the 1000 genomes vcfs (converted from hg19).  `v2` is `v1` after taking the 15 longest running shards from the callset we used `v1` on and chopped them into 10 equal parts by bases.  `v3` was created once we realized that `v2` nor `v1` covered all of the genome territory that our calling intervals cover so we added the parts of the genome that were missing (they're small so they shouldn't be problem causing).  If you wanted to split this interval list without any kind of model helping you make smart splits you will probably run into what we did with gnomad of having to iteratively split the same intervals multiple times to hit acceptable run times which is no fun.  

You can always overfit the problem and just make a crazy number of intervals where you can guarantee that even in the worst case for each of those intervals, it will still be under some run time you want to beat but that probably isn't the best strategy for many reasons.

Alot of it has to do with the content of the callset which is something we are not good at predicting.  The callset we used `v2` on had one interval that was multiple times longer than the next longest shard but in the callset we used `v1` on that same interval was one of the faster ones.  Both callsets had around the same number of samples.  Currently we are always retroactively "fixing" our interval list

**Comment by eitanbanks** [comment]
@kcibul can we close this?

**Comment by kcibul** [comment]
Done:

gs://broad-jg-dev-storage/WHI/hg38.even.100.intervals
gs://broad-jg-dev-storage/WHI/hg38.even.10k.intervals
gs://broad-jg-dev-storage/WHI/hg38.even.1k.intervals
gs://broad-jg-dev-storage/WHI/hg38.even.just_3_of_10k.intervals
gs://broad-jg-dev-storage/WHI/hg38.even.just_3_of_1k.intervals
