### ISSUE TITLE
Cromwell doesn't fail workflow with bad inputs

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2178]
A workflow was submitted and the inputs looked like:
```
"inputs": {
    "HaplotypeCallerGvcfScatterWf.ref_dict": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.dict\"",
    "HaplotypeCallerGvcfScatterWf.MergeVCFs.disk_size": 10,
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.mem_size": "4 GB",
    "HaplotypeCallerGvcfScatterWf.ref_fasta": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta\"",
    "HaplotypeCallerGvcfScatterWf.ref_fasta_index": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta.fai\"",
    "HaplotypeCallerGvcfScatterWf.input_bam_index": "gs://gatk-tutorials/workshop_1702/variant_discovery/data/bams/father.bai",
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.interval_padding": 100,
    "HaplotypeCallerGvcfScatterWf.MergeVCFs.mem_size": "2 GB",
    "HaplotypeCallerGvcfScatterWf.scattered_calling_intervals_list": "gs://gatk-test-data/intervals/b37_wgs_scattered_calling_intervals.txt",
    "HaplotypeCallerGvcfScatterWf.input_bam": "gs://gatk-tutorials/workshop_1702/variant_discovery/data/bams/father.bam",
    "HaplotypeCallerGvcfScatterWf.HaplotypeCaller.disk_size": 100
  },
```
Cromwell started jobs but they don't have operations IDs and the jobs/workflow remain in the "Running" state forever. Ideally the workflow should fail, and fail gracefully with an error message that makes sense. This ticket can be easily reproduced on 25_hotfix by corrupting a file input path to look like:
```
"HaplotypeCallerGvcfScatterWf.ref_fasta_index": "\"gs://gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta.fai\"",
```

**Comment by ruchim** [comment]
Bringing to attention of respective PO's for prioritization: @katevoss @bradtaylor 

The issue was initially reported by @vdauwera

**Comment by katevoss** [comment]
@ruchim how likely is it that there would be bad inputs of this sort? Is it a super common/easy mistake? I agree that Cromwell should fail gracefully, how much effort would it be to make that happen?

**Comment by vdauwera** [comment]
Super easy mistake to make. Though maybe I'm just saying that because **it happened to me**, and if it was a really hard/dumb mistake it would be embarrassing.

**Comment by ruchim** [comment]
It does seem like an easy mistake and I don't think it would take significant effort to fix this.

**Comment by katevoss** [comment]
In that case, I'll throw it into the User Driven Dev bucket (and milestone) for the bug rotator to pick up at their leisure.
