### ISSUE TITLE
Feature Request: Visualize Cromwell Metadata

### ISSUE THREAD

**Issue by knoblett** [broadinstitute/cromwell#2179]
A user would like to be able to visualize the timing diagram of his workflow using the metadata output, without using FireCloud. [Here](http://gatkforums.broadinstitute.org/wdl/discussion/9424/is-there-a-tool-for-job-metadata-visualization) is a link to the original user request. Below is a visual for the FC timing diagram, and [here](https://github.com/broadinstitute/firecloud-ui/blob/develop/src/js/timingDiagram.js) is FC's code for actually making the diagram.

![screen shot 2017-04-18 at 11 09 42 am](https://cloud.githubusercontent.com/assets/13629186/25138508/b2e2b64c-2428-11e7-9a76-8545c4af54dd.png)

**Comment by cjllanwarne** [comment]
@knoblett I replied directly to the forum post. 

This is already part of Cromwell (FC actually duplicates us!). The user needs to start up Cromwell in server mode and can then access the timing diagram at:
```
http://<HOST>:<PORT>/api/workflows/v1/<WORKFLOWID>/timing
```
