### ISSUE TITLE
garbage in stdout when using docker

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2188]
I created very simple pipelines.
```
workflow worms {

  Array[File] inputFiles

  scatter (oneFile in inputFiles) {
    call extract { input: sraFile=oneFile }
  }
}

task extract {

  File sraFile

  command {
    /opt/sratoolkit/sra-stat ${sraFile} > stats.txt
  }
  runtime {
    docker: "itsjeffreyy/sratoolkit"
  }

  output {
    File stats = "stats.txt"
  }
}
```
There I am supposted to get sra-stat output that is 
```
52687861:1896762996:1896762996|0:0|0:0|0:07
```
As in input you can put any sra files.
But what I get is
```
/cromwell-executions/worms/ddb1ae2d-e4c2-4a6e-8577-18b7faf69a84/call-extract/inputs/home/shelluser/nematodes/SRR2040663.sra||52687861:1896762996:1896762996|0:0|0:0|0:0
```
With some internal trash in the beginning. I do not need to get this trash, I just want to get sra-stat output.

**Comment by cjllanwarne** [comment]
Hmm, just to make sure, are you saying:

- The sra-stat tool adds the filename to the start of the output when you run it like this, and you want a way to remove it before reading the output? or...
- Cromwell is incorrectly adding the filename to the start of the "stats.txt" file which is being created by running this workflow?

**Comment by antonkulaga** [comment]
Let me check it again. Maybe indeed the mistake was on my side

**Comment by antonkulaga** [comment]
Looks like it was my mistake, closing it now
