### ISSUE TITLE
Strange NPE on actor context

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2189]
The first run of JG failed because an actor context happened to be null.
Specifically this happened when we use the actor system dispatcher as an Execution Context for the execution of futures in the Actor.
I only saw this once and the reason is unclear. Akka claims actor contexts can't be null.
One possible explanation (maybe?) is that the actor schedules some futures, then die for an unknown reason. By the time the futures become runnable and try to access their EC, the actor is already dead so the creation of the EC from the `context.dispatcher` fails.

<img width="1411" alt="screen shot 2017-04-10 at 5 07 02 pm" src="https://cloud.githubusercontent.com/assets/2978948/25280517/3f8fc75a-2678-11e7-966a-54340199c1e0.png">

**Comment by cjllanwarne** [comment]
Yeah I've seen this a few times before. I think you're right (from `context` scaladoc):
```
   * WARNING: Only valid within the Actor itself, so do not close over it and
   * publish it to other threads!
```

**Comment by geoffjentry** [comment]
This was also reported here: `http://gatkforums.broadinstitute.org/wdl/discussion/9576/is-this-error-caused-by-a-job-submission-failure#latest`

**Comment by awacs** [comment]
I've seen the same problem with LSF. It turns out it was because the main cromwell process is doing too many IO operations too fast.

**Comment by Horneth** [comment]
@awacs  Out of curiosity how did you come to this conclusion ?

**Comment by awacs** [comment]
@Horneth Changing the io settings     number-of-requests = 50    per = 10 seconded seem to ameliorate the issue somewhat. On a side note I'm seeing NoSuchFileException popping up for the stderr file in addition to the nullpointer exception at times.

**Comment by katevoss** [comment]
Is this complete?

**Comment by geoffjentry** [comment]
Will need to wait for @Horneth - I remember asking him recently but sadly don't remember the important part (ie the answer)

**Comment by Horneth** [comment]
The silver lining is 
"If you declare an execution context variable in an actor using `context.dispatcher`, don't make it a lazy val". I remember removing the lazy in a couple places so I think we can close this and re-open it if it happens again.
The underlying problem still exists in that if an actor starts some work asynchronously and then stops without waiting for it, the asynchronous work might never be acted upon. But this could manifest itself in unpredicatable ways.
