### ISSUE TITLE
Wire in new GATK tool to the new JG workflow

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2197]
Get the jars from #2196 

If I understood @droazen correctly, for each interval we will want 2 tasks. One task will build the GenomicsDB and output the database (which is a directory of files). The other task will run GenotypesVCF and take in that database as an input. For the first part he provided instructions (see below), for the second part he said he'd chime in w/ instructions.

./gatk-launch GenomicsDBImport --genomicsDBWorkspace WORKSPACE_DIR -L 20:1-1000 -V gs://bucket/sample1.g.vcf -V gs://bucket/sample2.g.vcf etc...

Note that the tool takes 3 required inputs:

    -a SINGLE interval for which to import GVCF data (-L)

    -GVCF URIs for all of the samples (-V). You can provide a text file ending in ".list" with one GVCF URI per line to the -V option instead of enumerating them all on the command line, if you prefer (or exceed the maximum UNIX command line length!)

    -The location where the GenomicsDB workspace should be created (--genomicsDBWorkspace). This should be an empty directory.

There are also optional inputs to control memory use and buffer size, but try running with the defaults for those first.

**Comment by geoffjentry** [comment]
Also I'm thinking it's worth seeing if it works out better to actually have that as 2 separate tasks vs a single task which runs both.

**Comment by kcibul** [comment]
TIL: The localization be a bit complex as the output of the first tool is a directory structure of all the genomics DB data.

**Comment by geoffjentry** [comment]
Yeah, you could do it via a glob but once I started thinking about it it seemed like it'd be easier to just do them on the same machine.

**Comment by kcibul** [comment]
I assigned myself since I started doing this anyway...

**Comment by droazen** [comment]
For `GenotypeGVCFs` you just provide the path to the GenomicsDB workspace written by `GenomicsDBImport` as a "gendb://" URI to the `-V` option. You'll also need to provide a reference fasta as a local file (this is a limitation of GenomicsDB that we were unable to remove).

So, a typical `GenotypeGVCFs` command line might look like:

```
./gatk-launch GenotypeGVCFs -V gendb://path/to/genomicsdb/workspace -R reference.fasta -O output.vcf
```

**Comment by katevoss** [comment]
@droazen did this happen?

**Comment by droazen** [comment]
It's happened for the 11k run, but the changes to the joint genotyping workflow haven't been merged into dsde-pipelines/master yet.

**Comment by kcibul** [comment]
@eitanbanks is on this now, closing from cromwell repository
