### ISSUE TITLE
Create a TES-to-Cromwell conversion service

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2202]
Create a web service in a similar vein to CromIAM which will act as a passthrough to an underlying Cromwell server. This server will expose the [TES](https://github.com/ga4gh/task-execution-schemas) API and interact with Cromwell presumably by creating a single task workflow out of the what was passed in.

The ultimate goal of this project is not to have some whizbang standalone server but to use this as an opportunity to identify what the translation path from submitting and interacting with a single task via TES looks like in the Cromwell world, instead of diving in and grafting TES directly into Cromwell's front end. 

DoD: A completed server (language, etc is dealer's choice) which we can use to guide another stage of development to directly support TES as part of Cromwell's front end API *or* a document detailing why this can't happen.

**Comment by katevoss** [comment]
@geoffjentry this is still To-Do, right?

**Comment by geoffjentry** [comment]
Yeah, although whether or not it's something we would care about sooner, later or ever is a little TBD at the moment. Need to let some of the job manager dust settle. 

It's not a *bad* idea period, but it's not important w/o a motivating use case - but the status of that isn't known yet

**Comment by katevoss** [comment]
@geoffjentry this is still relatively low priority for the moment, correct? I vote we not build it until we have a motivating use case.

**Comment by geoffjentry** [comment]
Yes. It does bubble up now and then but the things which would make it a high priority keep themselves finding themselves turned into a low priority. 

It comes up often enough that we should still do it at some point just so we're ahead of the game but it's not pressing ATM

**Comment by geoffjentry** [comment]
Closing this as it no longer makes sense
