### ISSUE TITLE
Validation misses unfound interpolation variables

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2209]
Variables in string interpolations do not undergo existence checks, so the following will validate despite `t` not existing:

```
task foo {
    # Shouldn't validate, no 't' defined:
    String s = "I like to drink ${t}"
    command {
        echo ${s}
    }
    output {
        String out = read_string(stdout())
    }
}
```

EDIT: Simplified the example

**Comment by jmthibault79** [comment]
Thanks!  The comments in the file are not directly relevant to the issue at hand.

**Comment by Horneth** [comment]
Fixed by https://github.com/broadinstitute/wdl4s/pull/178
