### ISSUE TITLE
Validation sucks: Tell me the input name that wasn't found!

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2211]
Ok, so validation fails because I had a typo in my input variable name, fine.

But TELL ME WHICH VARIABLE IT WAS!!!

The rest of this description is an example:

```
workflow foo {
	call bar
	# Oops, bar didn't have an output called b:
	call baz as bad_output_name { input: b = bar.b }
	# Oops, baz doesn't have an input called a:
	call baz as bad_input_name { input: a = bar.a }
}

task bar {
	command {
		# noop
	}
	output {
		String a = "a"
	}
	runtime {
		docker: "ubuntu:latest"
	}
}

task baz {
	String b
	command {
		# noop
	}
	runtime {
		docker: "ubuntu:latest"
	}
}
```

The messages I actually get:
```
Unable to load namespace from workflow: ERROR: Expression references input on call that doesn't exist (line 4, col 47):

	call baz as bad_output_name { input: b = bar.b }
                                              ^
Unable to load namespace from workflow: ERROR: Call references an input on task 'baz' that doesn't exist (line 6, col 38)

	call baz as bad_input_name { input: a = bar.a }
                                     ^
```

The message I want:
```
Unable to load namespace from workflow: ERROR: Cannot use 'bar.b' as an input. That variable was never created. (line 4, col 47):

	call baz as bad_output_name { input: b = bar.b }
                                              ^
Unable to load namespace from workflow: ERROR: Call supplies an input 'a' that isn't declared in the 'baz' task (line 6, col 38)

	call baz as bad_input_name { input: a = bar.a }
                                     ^
```

**Comment by knoblett** [comment]
Since the latter error message specifies that the input 'a' isn't declared in 'baz', I think it would be good to have the error messages paired, like so:

```
Unable to load namespace from workflow: ERROR: Call supplies an input 'a' that isn't declared in the 'baz' task (line 6, col 38)
```


and 

```
Unable to load namespace from workflow: ERROR: Call supplies an output 'b' that isn't declared in the 'bar' task (line 4, col 47)
```

And while we are here, I'm curious--why do we display a `^` if it doesn't point to the proper column within the line?

**Comment by antonkulaga** [comment]
Yes, it would also be nice. Right now, most of the wasted time in my pipelines is due to the things like this: when something in cromwell crashes and I spend a lot of time figuring out what exactly.
P.S.
To be honest, I do not understand why you started to create a language with a lot of problems to solve ( like this one) instead of just providing better declarative scala DSL (I think it is even possible to make it look almost like current wdl syntax) where tooling and errors are solved by scala ecosystem.

**Comment by geoffjentry** [comment]
@antonkulaga The primary reason is that the type of user we're targeting with WDL don't want to be fiddling around with scala (or java or python or ....). Thus baking in an internal dsl doesn't really work.

**Comment by antonkulaga** [comment]
@geoffjentry is it not possible to make the DSL in a way that it will look like curent WDL but will be scala-based? So, new users will deal with it like they currrently deal with WDL (but with checks/tooling provided by scala compiler) but those of users who know Scala will get extra benefits?

**Comment by geoffjentry** [comment]
@antonkulaga Is it possible? Sure. I don't see it happening in the near future. I do expect however that over the next few months we'll be exposing a general object model in cromwell to express workflows/tasks/etc (ie abstracting wdl out of cromwell) and at that point it'd be pretty straightforward for someone to create tools like you describe if they wanted to.
