### ISSUE TITLE
Deprecation exception triggered incorrectly...

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2217]
*See comment below on how to fix/address*

- cromwell-27-c89c83f-SNAP.jar
- JES backend
- server mode
- local mysql

I have a database block that looks exactly like the one in the example (from the error message), yet I still get the error message.  I tried a diff on the database blocks, between the example and my database block, so I am sure that they match.  Is this just a mistake in the error message itself?  

This is blocking me.

The error:

```
Caused by: java.lang.Exception:
*******************************
***** DEPRECATION MESSAGE *****
*******************************

Use of configuration path 'database.driver' has been deprecated. Replace with a "profile" element instead, e.g:

database {
  #driver = "slick.driver.MySQLDriver$" #old
  profile = "slick.jdbc.MySQLProfile$"  #new
  db {
    driver = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://host/cromwell?rewriteBatchedStatements=true"
    user = "user"
    password = "pass"
    connectionTimeout = 5000
  }
}

Cromwell thanks you.

        at cromwell.services.SingletonServicesStore$.<init>(ServicesStore.scala:70)
        at cromwell.services.SingletonServicesStore$.<clinit>(ServicesStore.scala)
        ... 22 more

```

My conf file for database:
```
database {
  #driver = "slick.driver.MySQLDriver$"
  profile = "slick.jdbc.MySQLProfile$"
  db {
     driver = "com.mysql.jdbc.Driver"
     url = "jdbc:mysql://localhost/cromwell_24?useSSL=false&rewriteBatchedStatements=true"
     user = "root"
     password = "blahblah"
     connectionTimeout = 5000
  }
}

```

**Comment by LeeTL1220** [comment]
The issue is in the reference.conf.  It still uses the old convention.  Even if you override the values in your own conf file, the reference.conf will trigger the deprecation exception.

This issue should be simple as correcting the reference.conf.

**Comment by LeeTL1220** [comment]
(I can confirm that fixing the reference.conf solves this issue)

**Comment by cjllanwarne** [comment]
:man_facepalming:

**Comment by cjllanwarne** [comment]
Although, that mysql example does look wrong

**Comment by LeeTL1220** [comment]
I grabbed the latest from develop this morning and the hsql driver info was
incorrect.  (And the commented mysql)  Maybe I did something wrong, but
seems unlikely.
