### ISSUE TITLE
JobStore write failure error message

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2219]
- cromwell-27-c89c83f-SNAP
- server mode
- JES backend
- call caching on localhost mysql server

Is this a matter of hitting some sort of ceiling in number of concurrent jobs?  Can I increase this?

```
....snip....
  "failures": [
    {
      "causedBy": [
        {
          "causedBy": [],
          "message": "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@122f57e rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@35ca91f1[Running, pool size = 20, active threads = 20, queued tasks = 1000, completed tasks = 2293]"
        }
      ],
      "message": "JobStore write failure: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@122f57e rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@35ca91f1[Running, pool size = 20, active threads = 20, queued tasks = 1000, completed tasks = 2293]"
    }
  ],
```

**Comment by LeeTL1220** [comment]
Is this related to ``genomics-api-queries-per-100-seconds``?

**Comment by Horneth** [comment]
Not it isn't, I believe @mcovarr is working on something that should make this "go away". 
In the meantime you can try to increase `database.db.queueSize` in the configuration. Results are not guaranteed though it's just giving slick more room but it might still fail. The default is 1000.
Also how big is your workflow ? Must be large to hit this.

**Comment by LeeTL1220** [comment]
@Horneth workflow is >20k jobs.

**Comment by LeeTL1220** [comment]
I just tried 3000

**Comment by Horneth** [comment]
yeah that's a lot, we just found out about this issue a week ago while testing large scale for joint genotyping but looks like "large scale" is quickly becoming "normal scale".
Definitely keep filing those failure modes as they come up !

**Comment by LeeTL1220** [comment]
@Horneth No problem.  I *might* have to scale up to 200k jobs in this workflow.  Depends on how many samples I need.

**Comment by LeeTL1220** [comment]
@Horneth Also, if you can alert me when a fix is in ``develop``, I can ingest that.  I'm running a ``develop`` version now.

**Comment by mcovarr** [comment]
Fixes for this were pushed out a long time ago, closing.
