### ISSUE TITLE
Support adding labels retroactively

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#2221]
It would be helpful to be able to add labels retroactively.  The particular use case I have in mind is to allow us to distinguish between "permanently" failed workflows (that we never need to look at again) and workflows that we are still investigating or trying to resuscitate, but I can imagine this would be useful in other ways as well.

**Comment by geoffjentry** [comment]
👍 @katevoss I asked @ktibbett to file this. This would be a big help for ops.

**Comment by katevoss** [comment]
@geoffjentry would this fit under the current work with labels that @ruchim is doing? I agree that it's a good idea and it would help make labels even more robust and useful.
