### ISSUE TITLE
adding clean to REST API

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2223]
As pipelines often deal with very large files (including intermediate files) and writing a good pipeline implies many runs it will be useful to have a clean rest API call to clean up previous executions to save some hard disk space.

**Comment by katevoss** [comment]
@antonkulaga this sounds like a use case for #1292, is that the same idea of what you're looking for?

**Comment by geoffjentry** [comment]
Closing as a dupe - this has been on our desired todo list for quite some time. Will get there eventually
