### ISSUE TITLE
Cromwell release doesn't bump WDL4S versions

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2225]
The WDL4S version used in Cromwell 26 is 0.11 ([proof](https://github.com/broadinstitute/cromwell/blob/26/project/Dependencies.scala#L5)). 

The develop `git.baseVersion`in WDL4S remains 0.11 (at least until https://github.com/broadinstitute/wdl4s/pull/104 merges).

Quoth @Horneth and @mcovarr: 
> our magic release stuff doesn't do this?
> Yeah that's weird, it should do it if it doesn't it's a bug

**Comment by katevoss** [comment]
@cjllanwarne this wasn't fixed in your PR, right?

**Comment by Horneth** [comment]
This seems to be fixed with the latest release wdl
