### ISSUE TITLE
Sporadic JES failure: error code 10 / message 15

### ISSUE THREAD

**Issue by jmthibault79** [broadinstitute/cromwell#2233]
During FireCloud testing, one job out of many similar jobs (all others succeeded) failed in the following way:

```
$ gcloud alpha genomics operations describe EPKmsKy8KxiFwqr275_Y6hwg9vy4-dodKg9wcm9kdWN0aW9uUXVldWU

message: "15: Gsutil failed: failed to upload logs for \"gs://fc-7ffecbef-0544-4db7-92a0-a3a0d4bafdfe/447d9c70-0173-47f3-8a00-e59a69290dde/echo_strings/3f63e284-cfd2-4a3d-a846-d468258e1aaf/call-echo_files/\"\
    : cp failed: gsutil -h Content-type:text/plain -q -m cp /var/log/google-genomics/*.log\
    \ gs://fc-7ffecbef-0544-4db7-92a0-a3a0d4bafdfe/447d9c70-0173-47f3-8a00-e59a69290dde/echo_strings/3f63e284-cfd2-4a3d-a846-d468258e1aaf/call-echo_files/,\
    \ command failed: AccessDeniedException: 403 Caller does not have storage.objects.create\
    \ access to bucket fc-7ffecbef-0544-4db7-92a0-a3a0d4bafdfe.\nAccessDeniedException:\
    \ 403 Caller does not have storage.objects.create access to bucket fc-7ffecbef-0544-4db7-92a0-a3a0d4bafdfe.\n\
    AccessDeniedException: 403 Caller does not have storage.objects.create access\
    \ to bucket fc-7ffecbef-0544-4db7-92a0-a3a0d4bafdfe.\nCommandException: 3 files/objects\
    \ could not be transferred.\n: "
```
I verified the user's permissions by auth-ing as that user and manually copying a file to the bucket successfully.  We should probably add this one to the retry list.

**Comment by geoffjentry** [comment]
@jmthibault79  Adding this to the retry list would retry the user's job. Is that really what you're advocating for?

This is coming from JES. They've actually been requested (by both Firecloud & other users) to tune down the retries that they do on the gsutil up/downloading.

**Comment by jmthibault79** [comment]
(noting here that a few Cromwellians & Workbenchers had a face conversation about this and general retry policy)

My goal is to enable a user to say "run my workflow and if JES has a random hiccup, try again and keep going".  The details of where in the stack we should do this, and under which conditions, are unclear to me.  So I guess what I want here is to note one failure case for FireCloud.  As for the actual action taken, that depends on the policy we decide on.

**Comment by geoffjentry** [comment]
@jmthibault79 One of our standing rules is to never reinvoke an entire jes job for someone w/o their consent (i.e. "cost them money"). It's possible to wire in some pre-authorization but that should be a cross-PO type conversation.

**Comment by jmthibault79** [comment]
Yeah, agreed this is for POs.

**Comment by patmagee** [comment]
This is an exceptionally annoying error, any more thoughts on how to potentially fix this? Should we go through the pipelines team?

**Comment by geoffjentry** [comment]
Refers to PAPIv1, closing
