### ISSUE TITLE
Feature request: A wdl function to get the basename of a file

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#2235]
This would alleviate the need to write a full task just to get the basename of a file.

**Comment by Horneth** [comment]
Is this the same as https://github.com/broadinstitute/cromwell/issues/1608 ?

**Comment by meganshand** [comment]
Almost, it looks like there you're getting the full file name (`/home/chrisl/superexcitingfiles/myFile.txt`), whereas basename would get you just the filename without the full path (`myFile.txt`). Or basename with the argument `.txt` might get you just the name without the extension (`myFile`). I'm thinking of the bash basename function here.

But I completely agree with your last comment on #1608. That example is basically the same case I ran into and it would be great if that use case was easier.
