### ISSUE TITLE
CWL support

### ISSUE THREAD

**Issue by naskokam** [broadinstitute/cromwell#2237]
Will Cromwell support CWL?  I'd see this as an extremely important feature enabling cross cloud-platform compatibility.

**Comment by geoffjentry** [comment]
I don't see what this has to do with using different clouds, but yes, we're adding support to ingest CWL over the next few months. I can't say specifically which Requirements we'll support or not support (there's a specific set of CWLs which are our definition of done) but it should be fairly comprehensive

**Comment by naskokam** [comment]
This is GREAT news!

Sorry I meant "cross cloud platform", not "cross cloud" compatibility.  It has a lot to do with that - if my pipelines are in WDL, I can't use them e.g. on the SevenBridges platform; if they are in CWL, I can't use them in FireCloud.

Anyways, thanks for the positive reply and keep up the great work.

**Comment by geoffjentry** [comment]
Ah the nci cloud pilots. Yes - your wishes should be answered soon :) I'm closing this but feel free to reopen if you feel it needs further discussion
