### ISSUE TITLE
WDL plugin in Intellij does not recognize Pairs

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2246]
As you see on the screenshot all pairs are highlighted as errors in Intellij while wdltool validates everything without an issue.
![pair_highlightning_error](https://cloud.githubusercontent.com/assets/842436/25742086/783c9136-3196-11e7-8649-9fd5e1403b70.png)

**Comment by geoffjentry** [comment]
Hi @antonkulaga - you're right, and likely more than just Pairs. It's been a while since we've updated the plugin so it's not totally on board with newer WDL constructs at the moment.

**Comment by geoffjentry** [comment]
@ruchim @danbills did this get updated in the intellij repository?

**Comment by ruchim** [comment]
@geoffjentry Unclear, I was only aiming to clear the closed PR from the board. Reopening and I'll let @danbills close this whenever appropriate.

**Comment by danbills** [comment]
I'll get it out today.

**Comment by danbills** [comment]
Plugin has been submitted "for approval" by @cjllanwarne , will close the ticket when it's approved.
