### ISSUE TITLE
Explore bloom filter for call caching file lookups

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2248]
When we're determining call cache hits we have an issue where we need to pull hashes and compare them to potential hits in our database. Many of these lookups are likely to be failures. It seems like a bloom filter could be a good optimization here (provided the memory tradeoff is worth the time benefit) by filtering out obvious negative results prior to hitting the database.

**Comment by katevoss** [comment]
@geoffjentry what is a bloom filter? What would be the effort to implement it?

**Comment by danbills** [comment]
Bloom filter is a test of "have we seen this before?" on a huge set.  We get one for free from Google Guava [here](https://google.github.io/guava/releases/22.0/api/docs/com/google/common/hash/BloomFilter.html)

**Comment by geoffjentry** [comment]
What @danbills said. It's a probabilistic data structure which can tell you either "I've probably seen this before" or "I've definitely *not* seen this before" in a very space & time efficient manner. So in a case like this where there are a lot of misses we could use it to do a quick "should I even bother hitting the DB" sanity test. 

I'd want to see that this is actually a bottleneck before proceeding, this was just an idea I had that I wanted to keep around for memory's sake in case we do see it be a bottleneck.

**Comment by geoffjentry** [comment]
call caching is changing as we speak, so closing

@mcovarr & @Horneth - tagging you just in on the off chance this tidbit might be useful somewhere in your current poking
