### ISSUE TITLE
retrieve hashes from quay.io for the call caching

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2252]
As most of biological containers (like http://biocontainers.pro) are hosted at quay.io it will be useful to get docker hash from there for call caching. Right now with the latest release I get the following message:
"""
Cromwell attempted to retrieve the current hash for this docker image but failed.\nThis is not necessarily a cause for concern as Cromwell is currently only able to retrieve hashes for Dockerhub and GCR images.\nThe job will be dispatched to the appropriate backend that will attempt to run it.
"""

**Comment by Horneth** [comment]
Cromwell 27 will be able to retrieve hashes for public images stored on quay.io
