### ISSUE TITLE
docker image has an invalid syntax nightmare

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2254]
Quite often I get 
```
 "failures": [
    {
      "causedBy": [],
      "message": "Docker image quay.io/biocontainers/star:2.5.3a--0@sha256:352f627075e436016ea2c38733b5c0096bb841e2fadcbbd3d4ae8daf03ccdf1b has an invalid syntax."
    }
  ],
```
Here is example of the task that caused this error. What is interested is that cromwell even did not start this task, so I suspect there is something wrong with docker parsing (I have this issue for this container both in develop and latest release of cromwell).

```
task star {

  Int  numberOfThreads = 8
  File file
  File genomeDir

  command {
    STAR --runThreadN ${numberOfThreads} --genomeDir ${genomeDir} --readFilesCommand gunzip -c --readFilesIn ${file}
  }

  runtime {
    docker: "quay.io/biocontainers/star:2.5.3a--0@sha256:352f627075e436016ea2c38733b5c0096bb841e2fadcbbd3d4ae8daf03ccdf1b"
  }

  output {
    String result = "STAR WORKS!"
  }

}
```

**Comment by Horneth** [comment]
You're specifying both a tag and a hash, which you're right docker recognizes as a valid image (surprisingly I must say). We should fix Cromwell to validate that correctly. In the meantime if you use `quay.io/biocontainers/star@sha256:352f627075e436016ea2c38733b5c0096bb841e2fadcbbd3d4ae8daf03ccdf1b` it should work
