### ISSUE TITLE
cromwell docker scripts cannot handle containers with entry points well

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2256]
I noticed that if I give cromwell a container with existing entry-point  (like quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa , for instance) and give a file as an input it (both develop branch and latest release) fails to run the entry point properly. Here is an example of task
```
task report {

  String fileName
  File file

  command {
    ${file}
  }

  runtime {
    docker: "quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa"
    #docker: "quay.io/biocontainers/fastqc@sha256:bb57a4deeec90633e746afbc38c36fdb202599fe71f9557b94652e9c8f3c1a02"
  }

  output {
    #File out = sub(file, "\\.fastq.gz", "_fastqc.gz")
    File out = "${fileName}.fastqc.gz"
  }
}
```

**Comment by cjllanwarne** [comment]
Right now, Cromwell provides its own command for the container to run (invoking a script containing the command block in your WDL). This overrides any entry point in the docker. To get your WDL to work, you'll need to write the command you want the image to run in the command section.

I'm gonna leave this ticket open though since I could imagine an extension of WDL whereby parameters to a docker run are passed in by replacing the `command` block with some sort of `docker_run_args` section

**Comment by geoffjentry** [comment]
@cjllanwarne I can't find it now (perhaps it has since been closed as a won't fix) but this has come up before. If you're open to trying to track it down close one as a dupe.

**Comment by antonkulaga** [comment]
>Right now, Cromwell provides its own command for the container to run (invoking a script containing the command block in your WDL). This overrides any entry point in the docker.

For the container that I gave ( quay.io/ucsc_cgl/fastqc@sha256:86d82e95a8e1bff48d95daf94ad1190d9c38283c8c5ad848b4a498f19ca94bfa  ) it does not override it correcctly whenever I put fastqc there. That is the problem

**Comment by Horneth** [comment]
I don't think we override the entrypoint that's correct. If you're using a "ConfigBackend" technically you can choose what the docker command is so you could do something like 
```
submit-docker = """
        docker run \
          --rm -i \
          ${"--user " + docker_user} \
          --entrypoint /bin/bash \
          -v ${cwd}:${docker_cwd} \
          ${docker} \
          /bin/bash ${script}
        """
```

And in your WDL command call whatever the original entrypoint of your docker was (`/opt/FastQC/wrapper.sh` in your case).

**Comment by cjllanwarne** [comment]
Oh @antonkulaga @Horneth, so the fix to this is to add `--entrypoint /bin/bash` to our config examples, so that we can guarantee overwriting whatever the docker is trying to do with `bash` (which Cromwell assumes)? That sounds sensible enough to me!

**Comment by antonkulaga** [comment]
Looks like
```
 submit = "/bin/bash ${script}"
        submit-docker = """
        docker run \
          --rm -i \
          ${"--user " + docker_user} \
          --entrypoint /bin/bash \
          -v ${cwd}:${docker_cwd} \
          ${docker} ${script}
        """
```
works for me (I moved bin-bash from end to entrypoint there)

**Comment by dshiga** [comment]
Greetings, my illustrious Cromwellian friends!

I find your workflow engine indispensable but am still running into problems related to this issue. PR #2280 fixes part of the problem, but only for the local backend.

I am trying to use the official Picard docker:
https://hub.docker.com/r/broadinstitute/picard/~/dockerfile/

Here is a simplified version of my WDL for illustration purposes:

task picard{
  command {
    CollectAlignmentSummaryMetrics
  }
  runtime{
    docker:"broadinstitute/picard"
  }
}

workflow picardwf {
  call picard
}

If I locally do
`docker run broadinstitute/picard CollectAlignmentSummaryMetrics`

I get the behavior I expect -- in this simplified example, it prints out the help command for CollectAlignmentSummaryMetrics. (The Dockerfile specifies an entrypoint that calls a script in the container and passes "CollectAlignmentSummaryMetrics" to it.)

When running with the JES backend, however, I get:
'/tmp/ggp-298770331' is not a valid command. See PicardCommandLine -h for more information.'

Cromwell has inserted a file path immediately after the image name in the docker run command:
`Running command: docker run -v /tmp/ggp-298770331:/tmp/ggp-298770331 -v /mnt/local-disk:/cromwell_root -e exec=/cromwell_root/exec.sh -e picard-rc.txt=/cromwell_root/picard-rc.txt -e __extra_config_gcs_path=gs://<path_redacted> broadinstitute/picard@sha256:1ddf5888182718c55054c96dca6a5d65d23a703f98e66832400e4837d04854a7 /tmp/ggp-298770331`

I don't think this default behavior makes sense for any backend. It should either override the entrypoint by default (as the local backend now does) or -- this would be much better -- it would work with the existing entrypoint.

A lot of published containers specify an entrypoint, which means when running in Cromwell they can't really be used as intended with that entrypoint. To get them running at all requires changing Cromwell's config to ignore the entrypoint, and then if you want to use the entrypoint you have to re-specify it as part of the command.

Could you please consider changing the default behavior to make it compatible with entrypoints out of the box?

Thanks!

**Comment by geoffjentry** [comment]
Hi @dshiga - unfortunately there's currently a limitation with PAPI, see what @kshakir wrote [here](https://github.com/broadinstitute/cromwell/issues/2461#issuecomment-316418026). It's expected that PAPI will overcome these limitations over the next couple of quarters and then we can change to be more flexible, but until then there's not much that we can do.

**Comment by dshiga** [comment]
Thanks @geoffjentry. It dawned on me after my comment that this might be something controlled by PAPI. I had planned to file an issue with them, but it sounds like they're already working on a fix. Thanks!

**Comment by ruchim** [comment]
@dshiga We expect this to be fixed in PAPI v2 backend. Have you had a chance to test this in v2 yet? Thanks!

**Comment by geoffjentry** [comment]
@TMiguelT I'm largely channeling the thoughts [in this paper](https://f1000research.com/articles/7-742/v1). The main issue I have w/ `ENTRYPOINT` is that it makes things less explicit in terms of what's happening when one reads the workflow descriptor. 

The other main argument which tends to come up is that this effectively locks the workflow to using the docker container, vs systems where one could ensure the appropriate software is installed. This one is definitely a real world use case but I feel less strongly about it as the use of the container is part of the selling point.

**Comment by TMiguelT** [comment]
I still think you're misunderstanding. I (and the other commenters) don't expect WDL to use the entrypoint script for any purpose, but what we do expect is for Cromwell to override this entrypoint script when it uses the docker image, because currently this behaviour is inconsistent across backends (the local executor already does this, but the PAPI executor does not)

**Comment by geoffjentry** [comment]
Ah, apologies. Got it

**Comment by dinvlad** [comment]
Looks like this is still an issue, correct? I’ve just stumbled upon it in one of our pipelines that uses PAPIv2 (on Cromwell 36). Thanks

**Comment by antonkulaga** [comment]
I think it is not longer relevant

**Comment by dinvlad** [comment]
> I think it is not longer relevant
Could you elaborate? We still can't use images that have `ENTRYPOINT` set.

**Comment by sworisbreathing** [comment]
@antonkulaga  why is this no longer relevant? Does cromwell now give us the ability to specify the docker entrypoint in a WDL?
