### ISSUE TITLE
Cromwell needs a way to input "Pair" objects from JSON

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#2260]
AC:
Something like this should run:

JSON:
{
  "Test.testMe":{"left":"Left","right":"Right"}
}

WDL:
workflow Test {
	Pair[String,String] testMe
call echoPair{input: pair=testMe}
}

task echoPair{
Pair[String,String] pair
command{
echo (${pair.left}, ${pair.right)
}
output {
  String out = read_string(stdout())
}

**Comment by cjllanwarne** [comment]
Also requested in https://github.com/broadinstitute/cromwell/issues/1708
