### ISSUE TITLE
Impact of runtime params on versioning of method configuration

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2268]
@vdauwera commented on [Wed Apr 12 2017](https://github.com/broadinstitute/dsde-docs/issues/1963)

This needs to be discussed further with both workbench and cromwell peeps/POs

----

This may have been asked before, but I can't find the relevant thread...
It looks like any change to a method configuration automatically triggers a version increase. It would be very useful to be able to control this. For example, changing a memory parameter should be possible without changing the version. In Firehose this was/is possible with the 'Outdate task' option.

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/firecloud/discussion/9388/versioning-of-method-configuration/p1

---

@vdauwera commented on [Tue Apr 18 2017](https://github.com/broadinstitute/dsde-docs/issues/1963#issuecomment-295047979)

@knoblett @katevoss This is a total can of worms that should probably be discussed with POs across teams

---

@knoblett commented on [Wed Apr 19 2017](https://github.com/broadinstitute/dsde-docs/issues/1963#issuecomment-295445174)

Is this a Red Team request or a FireCloud request? Seems more like the latter, but just want to clarify.

---

@vdauwera commented on [Wed Apr 19 2017](https://github.com/broadinstitute/dsde-docs/issues/1963#issuecomment-295453435)

I think it cuts across both. There are Cromwell-level implications in terms of call caching.

**Comment by abaumann** [comment]
In my opinion, Cromwell should call cache based upon it's best effort to know everything that is different.  Clearly you could write a WDL that does the same thing in the end with different inputs (e.g. more memory is given than before), but I'd rather err on the side of no false positives than trying to make sure Cromwell is too clever.  This really feels more like sugar in workbench where we could make some best guesses based upon what our users do or simply organize things in a way that it's less confusing/less effort for our users.

**Comment by mcovarr** [comment]
I don't believe there's anything to do for Cromwell in this ticket and this should be closed.
