### ISSUE TITLE
IntelliJ plugin throwing exceptions

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2276]
I do not really know how to give you more relevant information, but IntelliJ is complaining that the WDL plugin has an error  ...

```
Cyclic TextAttributesKey dependency found: BAD_CHARACTER->BAD_CHARACTER
```

**Comment by geoffjentry** [comment]
Could you hold off a bit? There's an update in flight to the plugin.

**Comment by LeeTL1220** [comment]
Sure.  Otherwise, seems fine.

**Comment by geoffjentry** [comment]
@LeeTL1220 Is this still happening w/ the latest version of the plugin? Also, if you didn't notice, pycharm works now too

**Comment by katevoss** [comment]
@cjllanwarne I know you just made an update to the IntelliJ plugin, did you fix this too?

**Comment by danbills** [comment]
This is fixed.
