### ISSUE TITLE
call logs on TES backend not localizing

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2285]
Seems that the call logs are not being copied to the final directory when run on the TES backend.

This test is failing: https://github.com/broadinstitute/centaur/blob/develop/src/test/scala/centaur/FinalDirsSpec.scala#L64

using these parameters:
https://github.com/broadinstitute/centaur/blob/develop/src/main/resources/finalCopy/final_call_logs_dir_tes.test

**Comment by katevoss** [comment]
@danbills are the call logs still not localizing on TES?

**Comment by danbills** [comment]
I wasn't unable to test w/ latest funnel TES implementation so I suspect that not only is this not fixed but more things are broken
