### ISSUE TITLE
Convert CWL files into WDL4S

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2303]
Cromwell Workflow Object Model (CromWOM) will be a subset of WDL4S and ultimately a superset of WDL and CWL.  Look at converting CWL files to the WDL4S format to guide the design of CromWOM.

The general approach is in increasing order of complexity:
1st-tool.cwl
1st-workflow.cwl
env.cwl

**Comment by katevoss** [comment]
@danbills are there any more issues in this Epic after [#156](https://github.com/broadinstitute/wdl4s/issues/156)? Or can it be closed after?

**Comment by katevoss** [comment]
@geoffjentry are there any more issues remaining after [#156](https://github.com/broadinstitute/wdl4s/issues/156) is complete?

**Comment by danbills** [comment]
We have this now.
