### ISSUE TITLE
File-of-File-Names (fofn) mystifies cromwell call caching

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2309]
As a user, I have a workflow that runs a scatter over 10 shards with a task that produce a file, then uses writelines to write out the gathered array of files (the fofn), which is used as an input to a downstream step.  That downstream step will never call cache because the fofn is different every time because the file in it, while each having the same md5, produce a different fofn because call caching copies the data to new paths on each cache hit.

This is painful because I love call caching, and now I have to recompute this step (and all steps downstream of it) every time.

@cjllanwarne @jmthibault79 any more details or ideas for addressing this
@katevoss this is the issue we talked about on the phone yesterday.  It's slowing down JG, but depending on how hard it is to fix may be too late for this use case

**Comment by jmthibault79** [comment]
Pretty sure you mean @Horneth here :)

**Comment by kcibul** [comment]
I did!  Sorry!

**Comment by cjllanwarne** [comment]
Is the FoFN itself important, or is it more about inputting things without localizing them? We were considering earlier something like a  `FileRef` type:
```
workflow foo {
  Array[Int] indices
  scatter (i in indices) {
    call mkfile { input: mkfile_input = i }
  }
  call use_files { input: fileRefs = mkfile.f }
}

task mkfile {
  Int mkfile_input
  command { ... }
  output {
    File f = outfile
  }
}

task use_files {
  Array[FileRef] fileRefs
  command { ... }
}
```

The `FileRef` would be hashed like a `File` for call caching but not localized by Cromwell to run the task

**Comment by cjllanwarne** [comment]
Or, here's an alternative `use_files` that supplies a FoFNs if the command needs it:
```
task use_files {
  Array[FileRef] fileRefs
  command { 
    ./read_fofn ${write_lines(fileRefs)}
  }
}
```

**Comment by kcibul** [comment]
@geoffjentry asked me to clarify, so here I am!

Currently, PAPI doesn't understand FOFN... so they are really just a File that contains strings.  Often they are created by taking the file output of a scatter call as an array and writing it to an array like

`Array[File] vcfs = PreviousTask.output ...
File fofn = write_lines(vcfs)
`
Then that FOFN is used as the parameter to the task, and used by the tool in the command directly.  The only thing that gets localized by PAPI is the FOFN itself.  Keep in mind right now that the only scenario where this works is where your docker has access to the file, which on Google means when you're running in service account mode, but hopefully we can overcome that in the future.

Just for context, my use case here is more like 'resume' than call caching.  I don't expect to find results from some previous/other run of the pipeline.  It's really that something broke, I tweaked the WDL, and now want to basically pick up where I left off.  That's the specific problem I have (and any methods developer will have with a FOFN step).

There are two ways I can think of going about this:

1. Fix call caching to handle FOFNs specifically.  This is tricky I think, but is most robust.  In this case, I want Cromwell to understand a File of File references as a specific type but just for call caching purposes.

2. Change call caching to re-use files rather than copying, thus the path of the file doesn't changes, the FOFN doesn't change, and the call cache hits.  This is how I ended up working around this by splitting the WDL into pieces where I supply the inputs to avoid the cache-miss step.  I believe we have this option in the SFS?

In your proposal @cjllanwarne a FileRef would be hashed like a file for job avoidance, but treated like a string for all other purposes (e.g. passing to PAPI, etc)?  I think that could work.

**Comment by geoffjentry** [comment]
On your last question, yeah that's basically it (although there was a request by Lee to refer to it as a `Path` and there was even some discussion that perhaps it should be cloud URL only so e.g. `CloudPath`). Despite the nomenclature the idea would be a type which would be treated as a String except that Cromwell would understand that it represents a file for things like call caching and handle them appropriately. Unlike a `File` the underlying path is never localized, it's always maintained as-is.

Coercion between `File` and this new type would be seamless.

I'll use `FileRef` for examples w/o necessarily endorsing that term.

In a much simpler example where you have a single `FileRef` it'd be treated just like a `String` when it came to a command block, e.g.

    task foo {
      FileRef bar
      File baz

      command {
          grep ${bar} ${baz}
     }
   }

This would be grepping the delocalized path referenced by `bar` in the contents of the localized file `baz`

For the `Array[FileRef]`/`writelines()` examples, the belief was that if the writelines was in the command block (or the declaration? crap, now I forget which) that call caching would work as desired as the individual `FileRef`s would have their hashes checked *prior* to the FOFN generation.

Moving away from your specific situation, I alluded to `CloudPath` above. The reason this came up in a separate context was e.g. GATK4's NIO capability where one doesn't want to be localizing files but does want call caching to be in effect. So there was a request for this concept of a file like thing which stays where it originally is. Some tricky edge cases start coming up when you're talking about actual local files for this and all the examples people came up with were people using cloud based storage, thus .....

**Comment by cjllanwarne** [comment]
To clarify @geoffjentry: if `write_lines` is in a declaration (e.g. `File fofn = write_lines(file_refs)`) then that's evaluated and used for CC (and with changeable paths being hashed, CC will miss, just like today). 

So to make CC work as you'd want in this new scheme, the `write_lines` would have to be in the command block (e.g. `command { ./foo.sh write_lines(file_refs) }`).

**Comment by geoffjentry** [comment]
Aside: I don't think having that sort of subtlety in any language, much less wdl, is particularly awesome

Aside part deux: If we go down this path we should think carefully how it is worded in the spec. WDL shouldn't be aware of call caching, so dropping in a feature that's effectively purely for call caching needs some explanation beyond that :) The whole cloud path/not for localization seems like the right official reason. This is of course assuming that this whole scheme gets @kcibul what he needs in the first place.

**Comment by cjllanwarne** [comment]
Agree 💯. IIRC the outcome of the "write the right `write_lines`, right" discussion was pretty much "always write the localized version".

And yeah there is an intrinsic value in being able to create a file of unlocalized file names (again, IIRC the main argument in favour of the current write_lines split was it enabled getting hold of unlocalized file names in a `write_files` output)

**Comment by cjllanwarne** [comment]
Just realized that last comment was especially well related how `write_lines` interacts with CC, maybe we can reconsider how CC interprets actual input values vs. Declarations (i.e. if the inputs are the same then any declarations will be the same too, so let's not cache expression results?)

**Comment by Horneth** [comment]
Hmm we would still need to cache at least the "unevaluated expression" I think, whatever that means. Otherwise what about this : 

```
task t1 {
  String a
  String b = "hello" + a
  command {
    echo ${b}
  }
}

task t1 {
  String a
  String b = a + "hello"
  command {
    echo ${b}
  }
}

workflow w {
  call t1 { input: a = "a" }
  call t2 { input: a = "a" }
}
```

Same input / command but the result will be different.

**Comment by Horneth** [comment]
The "resume" part in @kcibul explanation made me think that we could actually separate the "resume" case from the "I use call caching to simulate resume" case, although it's probably not the solution for this and I'm not even sure it's a good idea at all.
We could imagine a resume endpoint that takes a workflowId and a WDL, and same way call caching works now, re-uses succeeded task outputs (except this time no need to copy them because we're still running the same workflow technically) from this workflow previous run as long as their hash matches the one of the new WDL, and when they don't or/and the job was failed, run it again. It'd be very similar to "call caching without copying files" in the end, just conceptually a bit different as it would be the same workflow.
