### ISSUE TITLE
Occasionally run `check-alive` in config backend

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2315]
Some SFS backends can kill jobs outside of Cromwell, leaving us waiting forever for an rc file that will never be created. 

Idea: occasionally run the `check-alive` command to verify that long-running jobs are indeed still alive outside of restarting Cromwell.

**Comment by MatthewMah** [comment]
This is a duplicate of #2281.

**Comment by katevoss** [comment]
Closing in favor of #2281
