### ISSUE TITLE
Move WdlType into wdl4s.wom and rename

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2316]
E.g. WdlString should be CromwellString, WomString, WorkflowString, ONO

**Comment by katevoss** [comment]
@cjllanwarne any update on this issue? Is it still to-do?
Also, what is it for?

**Comment by mcovarr** [comment]
Oh whoops I just duplicated this with #2660 😦  I'll close #2660 and move this to the epic.
