### ISSUE TITLE
turn abort request into GET request

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2318]
I noticed that in swagger abort is marked as POST request despite it contains only two parameters: version and id. I suggest to make it a get request

**Comment by mcovarr** [comment]
Abort is definitely not idempotent; I don't think it would be appropriate to make this a GET.

**Comment by mcovarr** [comment]
Er I meant "safe" where I said "idempotent", but still this should remain a POST.

https://stackoverflow.com/questions/1254132/so-why-should-we-use-post-instead-of-get-for-posting-data
