### ISSUE TITLE
Convert WdlExpression to WomExpressions

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2319]

**Comment by mcovarr** [comment]
are we still doing this?

**Comment by katevoss** [comment]
@mcovarr Is this something you and @danbills are working on right now?

**Comment by danbills** [comment]
We are currently focused on the CWL side.  I think this is mis-labeled.

**Comment by danbills** [comment]
i.e. it is labeled _CWL_ and should not be.

**Comment by katevoss** [comment]
@danbills so it is still to-do? It's fine if it's labeled CWL, it's part of that general effort. I just want to understand whether it is completed or not.
