### ISSUE TITLE
Get everyone up to speed on vault

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2326]
See instructions:
For setting up with vault: https://broadinstitute.atlassian.net/wiki/display/DO/Vault

or to get vault token using docker instead of cli: https://github.com/broadinstitute/dsde-toolbox

# Self-assessment:

### Do you done the vault stuff?

- [x] @cjllanwarne
- [x] @geoffjentry 
- [x] @jsotobroad 
- [x] @mcovarr 
- [x] @Horneth 
- [x] @ruchim 
- [x] @danbills 
- [x] @kshakir

**Comment by jsotobroad** [comment]
I highly recommend using the dsde-toolbox method as it gives you access to the `vault-edit` command which is much less error prone

**Comment by katevoss** [comment]
@geoffjentry and @cjllanwarne are the only current team members who haven't done this yet. 

@ruchim reminder to do it too.

**Comment by geoffjentry** [comment]
@cjllanwarne and @ruchim - reminder that you two still have this
