### ISSUE TITLE
Cromwell Developer's Guide

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2327]
As an outside developer who would like to develop new functionality for Cromwell, I would like to have a developers guide that can get me going.  The developer's guide can assume a high level of technical proficiency, but I need help in understand the architecture and concepts that are relevant.

The areas that are important to me (in rough order) are:
   - creating a new backend
   - extending an existing backend
   - replacing "pluggable" components with new implementations (e.g. the Metadata Store)

**Comment by katevoss** [comment]
Per @davidbernick's comments on Slack, this guide should include how Cromwell administrators should set up Authorization, Authentication, Encryption, and Persistent Databases.

This guide will be created during the [Doc-A-Thon](https://docs.google.com/document/d/1M5u-ESSpt_eM0ORsvIu2AoOtvYXImPmAKoyvXFo4p9s/edit) in November.

**Comment by katevoss** [comment]
The Cromwell Developer's guide is here!
- [Quick Start](http://cromwell.readthedocs.io/en/develop/tutorials/FiveMinuteIntro/)
- [How to Configure](http://cromwell.readthedocs.io/en/develop/tutorials/ConfigurationFiles/)
- [Google Pipelines API quick start](http://cromwell.readthedocs.io/en/develop/tutorials/PipelinesApi101/)
- [Timing Diagrams](http://cromwell.readthedocs.io/en/develop/tutorials/TimingDiagrams/)
- [Setup a persistent server](http://cromwell.readthedocs.io/en/develop/tutorials/PersistentServer/)
- [Setup on HPC cluster](http://cromwell.readthedocs.io/en/develop/tutorials/HPCIntro/)
- [Run in Server Mode](http://cromwell.readthedocs.io/en/develop/tutorials/ServerMode/)

Checkout the full [Cromwell Docs!](http://cromwell.rtfd.io)
