### ISSUE TITLE
Bring sanity to command line processing

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2343]
The thought of tacking on yet more parameters whose position implies their meaning is too horrible to contemplate.  Make Cromwell arg processing sane.

**Comment by katevoss** [comment]
👍  
This relates to #1260 and #1939

**Comment by mcovarr** [comment]
Wow yeah, I'm not quite the first person to notice the shortcomings.  😄

**Comment by geoffjentry** [comment]
Please do

**Comment by gemlam3** [comment]
Connected to https://github.com/broadinstitute/cromwell/pull/2369
