### ISSUE TITLE
Don't hardcode WDL as the default Cromwell language for REST

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2344]

**Comment by mcovarr** [comment]
Don't hardcode "WDL" out at the API service layer.  This particular ticket doesn't need to drive as far as a full registry of "pluggable frontends", but it should move the default language determination for the REST layer to a more reasonable place than it is now.

**Comment by gemlam3** [comment]
Hey @mcovarr is this issue a duplicate of this issue #2345?

**Comment by mcovarr** [comment]
@gemlam3 No they're different.  This ticket is for the REST API, #2345 is for the command line interface.

**Comment by mcovarr** [comment]
Please note this is the last remaining ticket in the #2313 epic, so that can be closed when this ticket is closed.  Maybe GitHub is smart enough to do that automagically, I'm not sure.
