### ISSUE TITLE
Create config scheme for pluggable language support

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2346]
Seems like this would currently look something like PBE, with probably a lot less configuration.  In the KISS spirit, perhaps only a list of supported `workflowType` + `workflowTypeVersion`s for each language processor.

**Comment by geoffjentry** [comment]
@mcovarr Can you explain more? Why would this need to be pluggable? I think we went through this a while back so if you think you've explained this to me previously you probably have.

**Comment by mcovarr** [comment]
It certainly doesn't *need* to be pluggable, that just seemed more elegant than hardcoding WDL and CWL.  We can just say "when N > 2" and revisit this later.

**Comment by geoffjentry** [comment]
Ah! So it's more about language than version. Gotcha.

While I very much want to see a world where anyone can latch onto WOM, I think this is a case where using the @kcibul quote of "2 is not N" would be the better part of valor

**Comment by mcovarr** [comment]
Well depending on how different a given language becomes between versions we might want to route to different processor implementations.  But again, when N > 2.
