### ISSUE TITLE
Deprecate 'WDL' terminology on the REST API

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2348]
I'm thinking specifically of 'wdlSource' on the submit endpoints, but scan through the rest of the REST for other references.

I'm expecting the CLI arg processing changes in #2343 to be completely breaking changes, so I'm not planning to make a ticket analogous to this one for the CLI.  But we should definitely remove WDL references in the CLI as part of the #2343 work.

**Comment by gemlam3** [comment]
@mcovarr is this issue closed by #2355 ?

**Comment by mcovarr** [comment]
@gemlam3 Yes!  I forgot to connect them, closing now.
