### ISSUE TITLE
Add ability to Centaur to directly control the Cromwell server

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2350]
Currently Centaur is configured with a URL for a live Cromwell server. Leave this capability but also allow for Centaur to manage its own Cromwell such that it can start/stop it at will. Note that there's currently a bash script that does a lot of this, that script should be refactored as necessary once the functionality is in Centaur proper.

**Comment by mcovarr** [comment]
not sure why this was asked for or if we still need it

**Comment by Horneth** [comment]
this is actually done as it's how the restart test works

**Comment by katevoss** [comment]
Per @geoffjentry "no longer meaningful"
