### ISSUE TITLE
Excess load causes slick to start rejecting tasks

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2381]
See [this forum post](http://gatkforums.broadinstitute.org/firecloud/discussion/9851/cryptic-failure-messages)

>message: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@1fc7758d rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@39871354[Running, pool size = 200, active threads = 200, queued tasks = 1000, completed tasks = 1543924]

**Comment by danbills** [comment]
It may be worth setting the queue size to something huge or even unlimited as a stop gap measure.

In the settings conf file set put in database -> db  `queueSize = -1`.

**Comment by geoffjentry** [comment]
One thing I'd like to see before trying stuff is to have a setup that can reliably reproduce the problem and allows us to at least sorta kinda measure how effective our stopgaps & solution attempts are. 

For instance, is it possible that cranking the queue size causes something else to fall over? It'd be good to know that before diving in. (Probably not, but just trying to make the point)

**Comment by Horneth** [comment]
FYI same issue as https://github.com/broadinstitute/cromwell/issues/2182 and https://github.com/broadinstitute/cromwell/issues/2219

**Comment by Horneth** [comment]
A few slick issues talking about this: https://github.com/slick/slick/issues/1683
https://github.com/slick/slick/issues/1183

**Comment by geoffjentry** [comment]
Huh, they're recommending streams but I didn't think slick took streamed inserts?

**Comment by danbills** [comment]
duplicate of #2182 as mentioned
