### ISSUE TITLE
tail for an array

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2414]
Having a tail function in the array is very useful as it is quite common to read tsv files where first column is name of condition and others are sample accession numbers. I also opened a forum question on this http://gatkforums.broadinstitute.org/wdl/discussion/9893/getting-tail-of-the-array/p1?new=1

**Comment by katevoss** [comment]
@antonkulaga can you tell me more about your use case for the tail function?
@geoffjentry what would be the effort to add this?

**Comment by antonkulaga** [comment]
In most of RNA-Seq you have tsv where first cell is condition and all other cells are samples you should compare. Tail function allows to extract only samples from the condition raw, so I can pass them for further processing.

**Comment by geoffjentry** [comment]
This would be a WDL change, thus needs to be brought up over there and not as a Cromwell issue.
