### ISSUE TITLE
Fully add or remove 403 status for abort

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2415]
While doing the akka http changes i noticed that we purport to return a 403 status code when "workflow in terminal status". This hasn't been true for a while - some of the code is still there but it intermediate code was removed at some point and it can't happen anymore. I preserved the current behavior with the akka http-ification so this continues to be the case.

We should decide if we want to have the original behavior, and if so, reinstate it.

**Comment by katevoss** [comment]
As a **user aborting workflows**, I want to **get a 403 status after aborting a workflow**, so that **I know that my workflow is going to abort**.
* Effort: Small
  * Decide whether we want to keep the 403 status
  * @geoffjentry what does the 403 status gain us?
* Risk: Small
* Business value: Small

**Comment by geoffjentry** [comment]
It allows a user to understand that they're requesting to abort something which is already terminal. Whether or not that's useful is a matter of debate. Clearly someone does because it was put in by someone. I say that it's "useful" but am using quotes because I doubt anyone is ever going to act on knowledge.

I don't recall if it returns 200 or just a generic error (I could dig it up if it matters, but not now as I don't have the energy and I don't think we should keep it)

**Comment by mcovarr** [comment]
But someone is one of our most important stakeholders! 😛

Totally agree with closing this, we can work out the desired behavior when we fix abort in Cromwell 50.

**Comment by geoffjentry** [comment]
IIRC it's pretty non-obvious that that return code is impossible to trigger. I'll open a PR w/ a code comment in the appropriate place and close this. It'll be much more likely that we come across it then than this ticket anyways.
