### ISSUE TITLE
PartialWorkflowSources.toMap throws RuntimeException, is this ok?

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2418]
@Horneth pointed this out in an unrelated code review. Determine if this is appropriate, if not fix it

**Comment by katevoss** [comment]
@geoffjentry is this still relevant? It so, can you explain further?

**Comment by geoffjentry** [comment]
It still exists and no one ever determined if it was appropriate, so it is still potentially relevant. It's just not how we typically handle errors that occur in API calls so it looked weird. May or may not actually be an issue.

**Comment by geoffjentry** [comment]
This was just some random question from a code reviewer in a PR. No one is ever going to investigate it as-is and if it's an issue we'll find out. Closing.
