### ISSUE TITLE
Should metadata endpoint be forcing gzip on users?

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2419]
A while back we changed things to return gzipped content in the metadata endpoint by default, despite what the client says it can handle. generally the client should be telling the server what it can expect and the server either handles it appropriately or returns a 415.

I think that we should switch this to encoding on request. The downside is that there might be users who would be much better off getting a gzipped response but not realizing they have to do something extra (depending on their client).

**Comment by TMiguelT** [comment]
Agreed. As a user, I found this behaviour very strange, especially considering the other endpoints return uncompressed responses
