### ISSUE TITLE
Document expandSubworkflows in metadata

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2420]
It exists, and is in the swagger doc, but isn't in the readme

**Comment by katevoss** [comment]
@geoffjentry Let's add this to the Doc-A-Thon! Adding it to [the plan here](https://docs.google.com/document/d/1M5u-ESSpt_eM0ORsvIu2AoOtvYXImPmAKoyvXFo4p9s/edit#).

**Comment by katevoss** [comment]
As a **user running workflows**, I want to **know how to expandSubworkflows by reading the documentation**, so that **I know when to use this feature**.

Effort: Small
Risk: Extra-Small
Business value: Medium

**Comment by ruchim** [comment]
Resolved: https://cromwell.readthedocs.io/en/stable/api/RESTAPI/#parameters_10
