### ISSUE TITLE
Expose Meta object or labels in Cromwell Metadata Output 

### ISSUE THREAD

**Issue by patmagee** [broadinstitute/cromwell#2421]
We are investigating ways we can store additional information with a cromwell run that is useful for our downstream applications.

The two ways to pass associated metadata with a workflow are the Labels attribute through the runtimeOptions, or the `meta` object within cromwell itself.

Exposing either of these as parsable json in the metadata objet would achieve what we are looking for
 
## Meta
If I Have a workflow with a meta object:

```
workflow a {
   call b

   meta {
       some_key: "some_value"
   }
}
```
The only way to retrieve the meta values from the /metadata endpoint would be to re-parse the workflow string contained in metadata object 
```
   "workflow": " ....."
```
Since they are simple KV pairs it would be nice to have an output that looks like the following, embedded in the `metadata` object:
```
{
   "meta": {
      "key":"value",
      "key2":"value2"
   }
}
```

**Comment by geoffjentry** [comment]
Hi @patmagee - I started poking at this but then just reread your ticket. Have you looked at the enhanced label functionality that was just pushed out in 28? It sounded like that might get you what you want here. 

Let me know if not or if you'd still rather use the meta fields, it's easy enough to put in, just wanted to make sure it was worthwhile.

**Comment by patmagee** [comment]
@geoffjentry prior to today I wasn't aware of the new labels functionality. I believe this will be the solution, but have not tested it! I will let you know once I've seen the output

**Comment by geoffjentry** [comment]
@patmagee Cool, no rush. If you decide you still want the meta stuff just let me know, or if you want to go the label route just close the issue once you're confident it's the right path.

**Comment by patmagee** [comment]
@geoffjentry exposing the labels in the metadata looks like it will work great. No need to expose the workflow meta object at this point
