### ISSUE TITLE
Support Enumerations

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2425]
It would be nice to restrict types to specific values so that users can only specify one of a limited number of a values.

Per this [forum post](http://gatkforums.broadinstitute.org/wdl/discussion/9914/wdl-enum-type#)

**Comment by cjllanwarne** [comment]
Could be a nice bring-along with https://github.com/broadinstitute/cromwell/issues/2283

**Comment by patmagee** [comment]
Just wondering if there has been any discussion regarding this.

**Comment by katevoss** [comment]
@patmagee not to my knowledge but I can start the ball rolling. 
@geoffjentry & @mcovarr, any opinions on supporting enums?

**Comment by geoffjentry** [comment]
I'm leery but not necessarily against it. I'm also generally the one with the most conservative opinion in terms of adding WDL syntax, so view that take as a lower bound of acceptance :)

@patmagee what were you thinking in terms of the syntax?

Pinging @vdauwera so she's abreast of this convo.

**Comment by vdauwera** [comment]
FWIW Enum support would definitely be very valuable to us in GATK-world, and are likely to be useful in general. 

My one caveat would be that they should be easier to work with than they were in Queue (friendly elbow poke at @kshakir).

**Comment by patmagee** [comment]
@geoffjentry I share your concern with adding any sort of syntax to the spec, and my first inclination is to fake support enumeration. Im not exactly sure how to do that though, nor am I sure of whether its possible.

The cleanest way I can think of implementing would be maybe something like a Java style enum:

```
enum MyEnum {
     "A","B","C"
}

workflow wf {
    MyEnum thisIsMyEnum
}
```

Another way that we would be able to do it would be define an Enum type in a workflow like so:

```
workflow wf {
     #This would get overridden at run time, but the value would need to be validated
     Enum greeting = ["HELLO","GOODBYE"]
     or
     #Done override anything but validate it
     Enum["HELLO","GOODBYE"] greeting
     
}
```

**Comment by katevoss** [comment]
@geoffjentry sounds like this is more of a WDL feature request, shall I move it to the WDL repo?

**Comment by geoffjentry** [comment]
![628b747f8ccdfb757062f36a27eedecfc2295f515c0586e05fbfb0620c0571a2](https://user-images.githubusercontent.com/961771/30977362-51c7e54c-a445-11e7-829e-37880ac9b9d1.jpg)

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/wdl #139](https://github.com/broadinstitute/wdl/issues/139) via [**ZenHub**](https://www.zenhub.com/)
