### ISSUE TITLE
Add a `status` endpoint

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2432]
Cromwell will need to provide an endpoint called status which will return a 200 with other information on subsystems. For examples of how this was implemented in Rawls, see their [StatusService](https://github.com/broadinstitute/rawls/blob/eccaae155ef7a7bba7cbd7403405beb155a723a9/core/src/main/scala/org/broadinstitute/dsde/rawls/status/StatusService.scala) and [HealthMonitor](https://github.com/broadinstitute/rawls/blob/eccaae155ef7a7bba7cbd7403405beb155a723a9/core/src/main/scala/org/broadinstitute/dsde/rawls/monitor/HealthMonitor.scala). Subsystems to monitor include the CloudSQL database, Dockerhub, GCS and PAPI. If you can think of something else which seems useful feel free to add it in.

This endpoint should also be exposed via CromIAM w/o needing authZ

**Comment by gemlam3** [comment]
@geoffjentry is this still in progress or can it get moved back into the backlog?

**Comment by geoffjentry** [comment]
It's in progress, just at my typical 🐌 pace. It's not blocking anything though.
