### ISSUE TITLE
Add an else statement in WDL

### ISSUE THREAD

**Issue by knoblett** [broadinstitute/cromwell#2436]
A user today requested an `else` statement be added, in the conventional sense below:

```
if (myBool) {
    #do something
}
else {
    #do something else
}
```

I agree that adding something like this would enhance the readability we advertise for WDL, though I understand that this isn't completely pressing as there is currently a workaround (`if(!myBool)`). I leave this to your team to prioritize/discuss further as needed.

You can find the original user question [here](http://gatkforums.broadinstitute.org/firecloud/discussion/9929/is-there-a-null-value-that-can-be-used-in-wdl-could-else-statements-be-added-to-conditionals).

**Comment by katevoss** [comment]
@geoffjentry was this added by @cjllanwarne ever? I thought he did something similar.

**Comment by Horneth** [comment]
@cjllanwarne added [`if then else` in expressions](https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#if-then-else).
 This is asking for flow control `else` which we don't have.

**Comment by geoffjentry** [comment]
Closing this as it is a WDL spec issue
