### ISSUE TITLE
Un-bottleneck Jeff's computer

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2442]
There are a few development activities that are blocked by needing Jeff's computer. It has something to with the encryption of a configuration something something... more to be filled in by Jeff. 

@geoffjentry I would really like you to work on unblocking this when you have your work computer back. If there's anything across other teams or BITs etc that you need, just say the word.

**Comment by geoffjentry** [comment]
There's already a ticket for this. I'll link in here when I find it.

**Comment by geoffjentry** [comment]
https://github.com/broadinstitute/cromwell/issues/1296
