### ISSUE TITLE
Possible to never get "Done" executionStatus with badly-timed server restart

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2445]
Try it yourself, if you think you're fast enough (you probably are):

- Run a simple workflow with a few small tasks
- Watch like a hawk for a "workflow done" in the Cromwell log
- Quickly stop the server
- On restart, presto chango, the `executionStatus` remains `Running` forever!
- ...
- Weep?

**Comment by katevoss** [comment]
@cjllanwarne hopefully there will be less weeping with the graceful shutdown, @Horneth do you agree that this will be improved?

**Comment by Horneth** [comment]
Yes this should be improved in Cromwell 30

**Comment by katevoss** [comment]
Then I'll close this out as fixed! If it returns, well that's future Redteam's problem.
