### ISSUE TITLE
Workflow inputs don't override WDL defaults

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2446]
Say you have a task with an optional input with a default:
```
task foo {
  Int? inputInt = 5
}
workflow bar {
  call foo
}
```

I believe the order of precedence should be:
- Inputs provided by the inputs JSON
- Inputs specified explicitly by call (i.e. in the workflow doing `call foo {input: inputInt = 6}`)
- The default value in the task

Right now the  order appears to be:
- Inputs specified explicitly by call (i.e. in the workflow doing `call foo {input: inputInt = 6}`)
- The default value in the task
- Inputs provided by the inputs JSON

**Comment by katevoss** [comment]
@cjllanwarne I agree this sounds un-ideal. Maybe we should pass this by the WDL Focus group and see if they agree with the order of operations?

**Comment by geoffjentry** [comment]
Without going to deep into what this means (the key people know what this means), this is no longer a topic for the WDL Focus Group.

**Comment by geoffjentry** [comment]
This might not be an issue for the wdl focus group (in favor of upcoming situations). It depends on if this starts becoming more of a Cromwell implementation thing or a WDL thing. I think it is purely the latter, and if that's the case it should be moved to the wdl repo and left for that triage.

**Comment by patmagee** [comment]
@geoffjentry I agree with you. This is a specification issue, precedence should be dictated at the language level and not be implementation specific. 

As to the actual use case, I agree this would be a good feature to have but the semantics of it I think could probably be discussed over on the wdl page. Ie should setting default values have a different look and feel then an assignment. Something like `String? X default "my string" `

All execution engines s

**Comment by geoffjentry** [comment]
@patmagee Was "All execution engines s" a partial thought or one that was meant to be removed? :)

**Comment by patmagee** [comment]
@geoffjentry it was partial thought :) My mind can be scattered. Ive update the comment

**Comment by geoffjentry** [comment]
@patmagee Gotcha & totally agree. My own wishy washiness from before was due to misunderstanding the ticket at first and then realizing what it meant halfway through. You'd think I could have just gone back and reworded, but no. Always forward. :)

**Comment by katevoss** [comment]
As a **user running workflows**, I want **Cromwell to follow this order for looking at inputs: Inputs provided by the inputs JSON, Inputs specified explicitly by call, and then the default value in the task**, so that **Cromwell is processing the inputs that I want it to**.

- Effort: @geoffjentry any thoughts?
- Risk: Small
- Business value: Small to Medium
  - @cjllanwarne have any users asked or complained about this?

**Comment by geoffjentry** [comment]
@katevoss This is purely a WDL specification thing.

**Comment by katevoss** [comment]
Then I'll move it over to that repo
