### ISSUE TITLE
Confirm call caching properly considers overridden declarations

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2451]
Cromwell currently allows overrides of initialized task declarations.  Confirm that call caching properly takes this into account.

```
task foo {
  Int i = 3
  command {}
  output {
    Int o = 4
  }
}

workflow bar {
  call foo
  # should not cache to the above
  call foo as foo4 { input: i = foo.o }
}
```

**Comment by mcovarr** [comment]
Phew Cromwell gets this right.  😄   I'll add a centaur test to make sure it stays right.

**Comment by geoffjentry** [comment]
Crisis averted. Top notch ticketing.

**Comment by katevoss** [comment]
Sounds like there's nothing else to do here, closing this.
