### ISSUE TITLE
cromwell 28 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [broadinstitute/cromwell#2463]
URL:
https://github.com/broadinstitute/cromwell/releases/download/28/cromwell-28.jar

Expected SHA-256: 25c6c30fe062fb4a8384ef82aa5313ad5a5ee05eae62a2c831219d7c6c756347

Actual SHA-256:
c9ce762df236588ded042ceaf099848c0c1685d34788442ee251615ff13b5190

The expected checksum is what what we had in Homebrew for the SHA-256 when the formula was upgraded to version 28 on Fri Jun 30 12:44:57 2017 -0700. See https://github.com/Homebrew/homebrew-core/pull/15166.

But currently downloading the file gives a different checksum.

I wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by mcovarr** [comment]
Thanks for letting us know about this.  We discovered a critical bug in Cromwell 28 yesterday and released a patched version of the jar.  I believe @geoffjentry prepared an updated version of the Homebrew formula yesterday as well.  The formula from June 30 is certainly referencing the older jar and will not match the current checksum.

**Comment by ilovezfs** [comment]
@mcovarr any chance of getting it re-released as 28.1 or 29? Unfortunately users will just get a checksum mismatch error if the jar is already in their cache since cromwell is `bottle :unneeded`.

**Comment by geoffjentry** [comment]
Hi @ilovezfs , I opened the PR over on Homebrew with the revision flag set as per the instructions.

We will not tag that as 29, I could change it to read 28.1 on homebrew but it won't match what's over here.

**Comment by ilovezfs** [comment]
Can you reupload the 28 tarball so it has a 28.1 url?

**Comment by geoffjentry** [comment]
The downloadable jar on Github was intentionally kept the same, and that's the URL used in the Homebrew formula.

This whole incident has illustrated the need for better release & version management going forward but that doesn't exist right now.

**Comment by ilovezfs** [comment]
OK. Let's hard code a `version "28.1"` in the formula even though it won't match the URL, since that will prevent the checksum error.

**Comment by geoffjentry** [comment]
@ilovezfs Ok. Will update the PR in a few.

**Comment by ilovezfs** [comment]
@geoffjentry I just did :)

**Comment by geoffjentry** [comment]
@ilovezfs Thanks. I had just fired up this computer for the first time in about 6 weeks and was in the midst of a million 2FA auths :)

Sorry for the confusion on this, hopefully it doesn't happen again.

**Comment by ilovezfs** [comment]
>Sorry for the confusion on this, hopefully it doesn't happen again.

In the future if the jar needs to be modified after initial release, please bump the version.

**Comment by geoffjentry** [comment]
Thanks again @ilovezfs - we definitely will
