### ISSUE TITLE
Timing diagram cannot differentiate between running and queued on SGE backend

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2464]
- cromwell v27
- SGE backend
- server mode

Cromwell timing diagram displays SGE queued (qw) status as Running.  This increases difficulty of debugging (or evaluating) a tool, since we do not have a reliable and easy(!) way to look at timing.

**Comment by coption** [comment]
Can't this be fixed?

**Comment by coption** [comment]
@aednichols Excuse me ，why do you close this question ？

**Comment by aednichols** [comment]
Hi @coption, the user who reported the issue is no longer with the organization so it would be impossible to obtain repro steps from him.

If you have the same problem please file a new ticket.

**Comment by coption** [comment]
> Hi @coption, the user who reported the issue is no longer with the organization so it would be impossible to obtain repro steps from him.
> 
> If you have the same problem please file a new ticket.

ok，thank you very much

**Comment by coption** [comment]
> * cromwell v27
> * SGE backend
> * server mode
> 
> Cromwell timing diagram displays SGE queued (qw) status as Running. This increases difficulty of debugging (or evaluating) a tool, since we do not have a reliable and easy(!) way to look at timing.



> * cromwell v27
> * SGE backend
> * server mode
> 
> Cromwell timing diagram displays SGE queued (qw) status as Running. This increases difficulty of debugging (or evaluating) a tool, since we do not have a reliable and easy(!) way to look at timing.



> * cromwell v27
> * SGE backend
> * server mode
> 
> Cromwell timing diagram displays SGE queued (qw) status as Running. This increases difficulty of debugging (or evaluating) a tool, since we do not have a reliable and easy(!) way to look at timing.

@LeeTL1220 hi，Have you solved this problem ？
