### ISSUE TITLE
Graceful degradation in the face of excessive database activity

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2466]
At the moment we see slick errors from excessive database activity. This is working as intended on the part of slick, so now we need to gracefully handle this. There are temporary measures people can enact, but this ticket is about rewiring things to be brave in the face of danger.

I see this as requiring heavy tech talk/design discussion prior to being shovel ready. 

Some initial thoughts:

- My assumption is via a backpressure mechanism but I don't want to mandate this. But it seems natural to me that the answer to "it hurts when I do this" is "stop doing that for a while". 
- One area where this gets tricky is the metadata service. The solution should not overfit to the default (currently only) metadata service implementation (i.e. MySQL tied to the same database connection as the rest of the system).

**Comment by rtitle** [comment]
I'm not too familiar with the Cromwell DB or its usage patterns, but in the past I've helped scale databases via:

1. Master-slave replication -- if you can separate your reads from your writes you can direct your reads to a replica and writes to the master. That way you can horizontally scale. This works best when reads vastly outweigh writes.

2. Materialized views -- if you have some expensive queries you can periodically (perhaps via cron) refresh the query results in a table (e.g. `CREATE TABLE .. AS <expensive select query>`). Then the application just queries that table which is a lot cheaper query.

**Comment by geoffjentry** [comment]
@rtitle 
The real meat of this ticket though is less the "omg the DB barfed" but rather "omg we don't do anything smart when omg the DB barfed" :)

That said, the bulk of our data storage *is* separated out, just not practically in our default "Jane User" configuration. Currently the "Jane User" configuration is the only one which exists. So e.g. for CaaS that's not going to be the case, and we'll probably need to support horizontal scaling scenarios that don't take adantage of GCP tooling for external customers as well. 

The lion's share of our DB activity consists of writes coming from the write side of our cqrs to the read side's event store and reads on that event store coming from the API. It's logically all separated out but in stock Cromwell they're sharing the same DB/connection/etc.

So e.g. one possibility (which has come up before for other reasons) would be to make it easier for a user to bifurcate those to using separate DBs (or at least separate connections), although you'd still possibly have this problem.

**Comment by danbills** [comment]
Let's stash all the data in a GCP Task Queue and pull it in to the DB with a separate service.

**Comment by geoffjentry** [comment]
@danbills We can't do that here. We can do stuff like that in CaaS but not in mainstream Cromwell.

**Comment by kcibul** [comment]
@geoffjentry do you mean from a default configuration perspective?  We could have a pluggable "metadata service" in Cromwell (which I think we already have) with two implementations (direct DB write vs JMS emitter) could go into mainstream cromwell.  Of course the listener for that would be a separate service (and easy to scale).  Maybe that's what you mean though?

**Comment by geoffjentry** [comment]
@kcibul Right now there are two problems:

- We're overloading the DB (largely metadata) in FC
- Nothing good happens when the DB is overloaded

The first one is solvable by a new metadata impl and will be the sort of route we go in CaaS

The second one should be fixed no matter what one is doing, so I'm specifically talking about all slick interaction which includes the stock metadata impl. 

Related -  as part of the CaaS milestone there are tickets (#1349 in particular) to make sure the standard impl isn't too tightly coupled with the resto f our DB stuff.

**Comment by aednichols** [comment]
Closing due to being old, and not having surfaced recently.
