### ISSUE TITLE
Finish wiring between CromIAM and Sam

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2469]
Sam is now up and accessible. Complete the wiring process for CromIAM to be able to talk to a live Sam.

@cjllanwarne Can you fill in the blanks on what this entails?

(EDIT below by cjllanwarne):

- Have a look at the `handleRequest` method in `SamActor`. It's called by the actor's `receive`.
- Right now, the placeholders complete `Promises` after a set time. You'll want to message SAM, wait for a response, and then complete them more appropriately.
  - NB in case you're wondering, the `Promise/Future` stuff is because the CromIamApiService is not an actor and so cannot receive responses in the usual actor-y way. Feel free to make it better, I ended up doing this because the actor-y way was adding in enormous/unnecessary overheads in terms of boilerplate... YMMV.
  - FWIW even if `CromIamApiService` isn't an actor, I still suspect `SamActor` will end up spinning up individual worker actors. It's just the interface back to the service which isn't messages.
- The SamActor is parameterized with the `userIdHeader`. SamActorRequests will both have a `userIdtoken` included (oops, `RegisterWorkflow` calls it `user` but it's the same thing). When you make your request to same, you'll need to add the appropriate header (called whatever the actor was parameterized with) with the user token's value.
- Success or Failure completions, everything else *should* be wired up correctly already. You might want to double check that (especially for SAM rejections).

If the intrepid person picking up this ticket is not me (@cjllanwarne), I'm happy to make this make more sense in person, if required.

**Comment by gemlam3** [comment]
@cjllanwarne connects to https://github.com/broadinstitute/CromIAM/pull/14
