### ISSUE TITLE
if cromwell restarts while liquibase is running, database is left in bad state

### ISSUE THREAD

**Issue by ahaessly** [broadinstitute/cromwell#2476]
When running firecloud in a box, the services start with an empty database and initialize them with liquibase. Sometimes the cromwell service can't connect to port 8000 right away and when this happens the service shuts down and restarts. Typically, the shutdown happens during the liquibase initialization and this leave a lock in the DB. On restart, cromwell can connect to port 8000, but can't complete the DB initialization because of the lock left during shutdown.

The cromwell system should either complete the DB initialization before shutting down if it can't connect to the port or it should handle an interrupted DB initialization on restart.

[cromwell-app.rtf.txt](https://github.com/broadinstitute/cromwell/files/1166281/cromwell-app.rtf.txt)
[cromwell-proxy.rtf.txt](https://github.com/broadinstitute/cromwell/files/1166282/cromwell-proxy.rtf.txt)
[cromwell-mysql.rtf.txt](https://github.com/broadinstitute/cromwell/files/1166280/cromwell-mysql.rtf.txt)

**Comment by mcovarr** [comment]
Possibly relates to #2373

**Comment by mcovarr** [comment]
...or as discussed with @geoffjentry and @cjllanwarne, it makes a lot more sense to do all the Liquibasing before even trying to bind the port.  😦
