### ISSUE TITLE
Metadata endpoint returns compressed response by default(though documentation says otherwise)

### ISSUE THREAD

**Issue by shivagopalan** [broadinstitute/cromwell#2487]
`curl http://localhost:8000/api/workflows/v1/d3c6baa2-bf9b-4acb-84f0-00195ebc4595/metadata`
should return metadata in uncompressed format, according to https://github.com/broadinstitute/cromwell#get-apiworkflowsversionidmetadata 
However, the following is observed - 
`curl localhost:8000/api/workflows/v1/d3c6baa2-bf9b-4acb-84f0-00195ebc4595/status
{
  "status": "Succeeded",
  "id": "d3c6baa2-bf9b-4acb-84f0-00195ebc4595"
}
compute-2-5 ~$ curl localhost:8000/api/workflows/v1/"d3c6baa2-bf9b-4acb-84f0-00195ebc4595"/metadata
Ĵ(0I▒!▒o(▒:4▒fZm▒vK▒▒▒J1▒▒▒▒a>▒▒▒H▒▒▒▒▒▒0IDV@e▒▒▒M)▒▒8/▒▒▒Q▒▒▒n&▒]▒▒O▒▒5▒b▒▒4▒▒J▒z▒=NM/▒W":▒b▒љv=▒Q▒▒x▒▒▒▒▒9▒▒c▒S▒▒8▒ܚ▒▒M▒4▒▒▒)ɥ)!<@,5▒S▒▒4▒▒)▒2▒▒▒;q.▒▒▒`▒▒▒▒^▒sk▒ӄ▒$▒x;▒8t▒t▒=G▒▒▒>Dq▒?▒w4S▒uj/▒2b▒ ª▒$YKP▒I▒HJ▒5n▒▒▒▒▒▒y▒|J▒`9▒▒▒ڑH
▒▒Xp0▒Z▒1▒6▒:c%Kq▒▒▒▒%▒▒IqΡ▒S▒H8!c▒▒=▒▒▒▒]
           ▒V▒▒▒▒▒▒▒▒tN▒▒▒e.▒ M
HS▒Ev{▒▒▒x
          :I▒ո▒▒B▒▒ ▒g▒j▒ە▒k▒7▒▒m▒a▒2▒Zr(▒(I(k▒▒ ▒▒▒q▒▒,▒▒▒▒▒za_A#▒)}Y▒_▒9c▒Q
                                                                             ▒W▒▒?▒▒▒▒▒▒1▒/▒▒MH▒n▒b▒#6▒\▒8▒b▒|▒j3▒▒▒▒▒z▒▒7
▒▒▒~*z▒6b▒▒▒٬▒▒Z▒▒|▒`a▒u*(▒▒▒▒އ▒+▒▒H▒▒A5:gTm￫▒r▒L1{▒▒▒▒gT▒▒v▒:3▒▒▒▒ɰ|Y▒▒A^▒▒,▒▒▒▒I▒#▒▒▒▒▒D6▒▒▒V▒▒       T▒▒▒I▒oD▒vo윗#▒2▒▒j▒▒(▒s▒S>▒Ne$P>▒▒^o}▒▒\▒▒▒p▒
compute-2-5 ~$ xtermxtermxterm
`

The header "Accept-Encoding: gzip" is not being included in the request, yet compressed response is returned.

**Comment by geoffjentry** [comment]
What version are you using? 

Versions prior to what's on develop were forcing compression on users.

**Comment by shivagopalan** [comment]
I'm using v28. The jar was downloaded from this page
https://github.com/broadinstitute/cromwell/releases/tag/28

**Comment by geoffjentry** [comment]
Unless you want to build a jar off of `develop`, until 29 comes out you'll want to accept gzip encoding.

**Comment by mcovarr** [comment]
29 is out now, closing.
