### ISSUE TITLE
optional per-task for docker enviroment

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2494]
Right now the exact docker commands are defined in cromwell application.conf. In the same time for some tasks I need to add extra volumes or other run parameters. I want to be able to do it directly in wdl.

**Comment by mcovarr** [comment]
As a short-term workaround you might define different config backends for each Docker configuration you want to support, but that wouldn't scale well if you have a lot of different configurations.  Also that requires changes to your conf file to match your WDL which is kind of gross.

Do you have any specific suggestions how you'd want this to work?

**Comment by aednichols** [comment]
Closing due to being old, and not having surfaced recently.
