### ISSUE TITLE
Solution for 503 errors in cromwell

### ISSUE THREAD

**Issue by droazen** [broadinstitute/cromwell#2495]
Hi Cromwell team,

I've heard rumors that lately you've been plagued with the same intermittent 503 errors using the GCS NIO library that have plagued the GATK. We have what we believe is a definitive fix for this issue up at https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2281.

To take advantage of the fix, client code needs to set the library-level retry/reopen settings to be sufficiently aggressive. The settings GATK uses (which have cleared up our 503 issues at scale completely) can be seen in the `setGlobalNIODefaultOptions()` method in this class:

https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/gcs/BucketUtils.java

Mentioning @LeeTL1220 on this ticket by request

**Comment by geoffjentry** [comment]
@droazen not that i'm aware of. If you're referring to what I think you're referring to, @leetl1220 is experiencing these errors as part of the Pipelines API process which isn't code we control.

**Comment by droazen** [comment]
@geoffjentry Ah, thanks for the clarification -- by "Pipelines API process", do you mean JES? Are you in touch with the people who maintain that (or are we able to submit PRs to that project)?

**Comment by droazen** [comment]
Closing -- @geoffjentry answered my question in private.
