### ISSUE TITLE
lazy variables inside a task

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2505]
What I expect from variables inside the tasks is that they will be initialized when the task is executed.
So, for instance, if I have a task like this:
```
task my_task {
 String a
Strinb b = a + "/" + "annotation.fa"

  command { something ${b}   }
}
```
and call it like this
```
    call my_stak  {
    input: a = "my_path"
    }
```
I expect b to be "my_path/genome" cause it is reasonable. But looks like it is not the case with cromwell as cromwell initializes b before the task my_task is called.

**Comment by mcovarr** [comment]
Running a slightly cleaned up version of your example:

```
task my_task {
  String a
  String b = a + "/" + "annotation.fa"

  command {
    echo ${b}
  }
}

workflow my_workflow {
  call my_task { input: a = "my_path" }
}
```

I see this command go by in the logs:

```
... INFO  - BackgroundConfigAsyncJobExecutionActor [...]: `echo my_path/annotation.fa`

```

So this appears to be working as expected.
