### ISSUE TITLE
Cromwell doesn't supply a name over HTTPS

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2513]
If you use a java or scala client (e.g. CromIAM...) to connect to Cromwell over HTTPS, you'll get an error like:
```
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
```
cf. Google, this can be ignored client-side by adding:
```
System.setProperty("jsse.enableSNIExtension", "false")
```
However, it would probably be nicer if Cromwell addressed this by adding an appropriate name when running in HTTPS mode. Since CromIAM is happy talking to Sam over HTTPS, they probably know how to do this.

**Comment by kcibul** [comment]
@dvoet -- how is Sam setting this?

**Comment by kshakir** [comment]
Talked to Doug. "SAM" itself doesn't serve HTTPS. The proxies do. The names are set there:
- [SAM](https://github.com/broadinstitute/firecloud-develop/blob/41b78578eaadb140ccdcf86d6d44de822bf9410c/configs/sam/proxy-compose.yaml.ctmpl#L17)
- [Cromwell](https://github.com/broadinstitute/cromwell-develop/blob/d37f37cc8fd472b844a0b004178a1bfc458a3796/configs/caas/docker-compose.yaml.ctmpl#L32) (actually CaaS)

**Comment by aednichols** [comment]
Given that we have not needed to serve HTTPS from Cromwell in 6 years, closing this issue 🙂
