### ISSUE TITLE
Feature request: add usernames to database

### ISSUE THREAD

**Issue by Osiris1975** [broadinstitute/cromwell#2514]
Hi,

We'd like to make a feature request to be able to include a username to be stored in the cromwell database that we can later query using the API so that, given a username, all workflows for that username are returned by the query. 

Is this doable?

Thanks,
Amr

**Comment by katevoss** [comment]
Hi @Osiris1975,
Thanks for your question, if you could please ask it on the Cromwell/WDL forum, https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team that would be great. That's where we answer questions like this. Thanks!

**Comment by mcovarr** [comment]
Closing this in GitHub.
