### ISSUE TITLE
Max and Min functions

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#2515]
We now have floor and ciel functions, it would be great to also have max/min functions that take two floats or ints (or an array) and return the max or min of them. I'm happy to provide an example use case!

**Comment by cjllanwarne** [comment]
Until this is added, you can do the same with:
```
Int a
Int b
Int max = if a > b then a else b
Int min = if a < b then a else b
```

**Comment by vdauwera** [comment]
May I suggest that min/max should work on any array of numbers of arbitrary length, not just two?

**Comment by geoffjentry** [comment]
This is a request for the WDL spec and should be directed over there
