### ISSUE TITLE
Cromwell can fail to respond to metadata requests on large workflows

### ISSUE THREAD

**Issue by droazen** [broadinstitute/cromwell#2519]
When busy running a large workflow (like the current 20k gnomAD callset), cromwell can fail to respond to metadata requests. This makes it very hard to see what's going on with the workflow.

**Comment by droazen** [comment]
In this situation, metadata requests (via, eg., `curl` or similar) either hang (seemingly) indefinitely or time out with a message like:

```
status": "error",
  "message": "Communications link failure\n\nThe last packet successfully received from the server was 3 milliseconds ago.  The last packet sent successfully to the server was 173,470 milliseconds ago."
}
```

**Comment by LeeTL1220** [comment]
👍 👍 

This makes debugging failures so difficult.  Even with includeKey and excludeKey.

**Comment by katevoss** [comment]
@Horneth is this because of the Slick database exceptions?

**Comment by Horneth** [comment]
The slick exceptions could technically cause this but no this is more generally due to the metadata building process being very expensive therefore causing all kinds of timeouts / errors.

**Comment by mcovarr** [comment]
There's a good forum post on this topic here, including not only `includeKey` and `excludeKey` but also increasing Akka HTTP timeouts.

We might want to change those timeout defaults in `reference.conf` if users are seeing this routinely even with those filters.

https://gatkforums.broadinstitute.org/wdl/discussion/10209/retrieving-metadata-for-large-workflows

**Comment by aednichols** [comment]
This will be fixed with the new metadata implementation.

**Comment by AlexMTX** [comment]
Hi @aednichols ! Are there any news on the new metadata implementation?

**Comment by aednichols** [comment]
Yes, the Cromwell 51 release completed the metadata archiving implementation and it is now operating in production at Broad Institute. Archiving is targeted at our internal production instance only so it's not an officially documented or supported feature, but an enterprising Cromwell admin could surely get it working.
