### ISSUE TITLE
Define "I/O interface" for WOM

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2521]
Define an interface in WOM that contains a minimal set of methods such that

- Cromwell can supply an implementation of them at runtime
- It meets the I/O needs of both CWL and WDL so that they can evaluate expressions using this interface for I/O related work

It might be interesting to think about whether or not this interface should be made asynchronous.

**Comment by mcovarr** [comment]
I think this [happened](https://github.com/broadinstitute/wdl4s/blob/develop/wom/src/main/scala/wdl4s/wom/expression/WomExpression.scala#L23) as part of my "wrap WDL expressions in WOM" work, so this might be closeable.

**Comment by cjllanwarne** [comment]
I agree with @mcovarr - this has happened. Future improvements to it can be new tickets
