### ISSUE TITLE
Implement CWL expression evaluation

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2524]
The CWL bindings should provide a way to evaluate CWL expressions that is compliant with WOM interface.

CWL has a concept of `Parameter References` similar to WDL lookup that does not require Javascript. And the concept of expression that does.

Here are some links that could help:

- [Parameter References](http://www.commonwl.org/v1.0/CommandLineTool.html#Parameter_references)
- [Expressions](http://www.commonwl.org/v1.0/CommandLineTool.html#Expressions)
- [CWLTool](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/expression.py)
- [Bunny](https://github.com/rabix/bunny/tree/master/rabix-bindings-cwl/src/main/java/org/rabix/bindings/cwl/expression)
- [Nashorn](https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/)

**Comment by danbills** [comment]
A nominal implementation has been committed to wdl4s and will be iterated upon, thus I am closing this.  The wld4s epic 159 (unfortunately unlinkable!) covers the effort to get full CWL expression support.
