### ISSUE TITLE
Bucket names with underscores cause problems

### ISSUE THREAD

**Issue by abaumann** [broadinstitute/cromwell#2525]
If you use an input file from a google bucket where the bucket name has an underscore, you get behavior like this:

input file gs://my_underscorey_bucket/file.txt
localizes to a file named: gs:/my_underscorey_bucket/file.txt (note the single slash)

**Comment by katevoss** [comment]
Could this be related to #2078 ?

**Comment by vdauwera** [comment]
Sounds connected. Following that issue, Miguel made changes that cause Cromwell to fail on disallowed bucket names including those containing underscores; see https://github.com/broadinstitute/cromwell/pull/2364

That being said, based on the dates the change should in C28, which is what FC is running right now. So it might be worth having the on-call bug rotator take a look (still @kshakir ?)

**Comment by vdauwera** [comment]
@abaumann I assume this was run in FireCloud? Would be good to specify the Cromwell version explicitly in the ticket.

**Comment by Horneth** [comment]
@vdauwera I'm the bug rotator now. I'm going to take a look at this.

**Comment by vdauwera** [comment]
Merci!

**Comment by kcibul** [comment]
@gemlam3 -- what is the closure reason?  could not reproduce?  fixed?  duplicate?

**Comment by kshakir** [comment]
@kcibul see https://github.com/broadinstitute/cromwell/pull/2531

**Comment by kcibul** [comment]
perfect -- always good to mention the reason for closing when closing.  We used to link PRs to the issues they resolved, can we keep doing that?  Just put yourself in the shoes of an external user who was watching this ticket

**Comment by gemlam3** [comment]
@kcibul the PR is connected to this issue. Can you not view it?
