### ISSUE TITLE
JES backend not honoring the `default-zones` configuration parameter

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2527]
- v28
- JES backend

With the below changes to a reference.conf, I would expect my jobs to be distributed between us-central1-f and -c, but when I check the VM instances, they are all still going to us-central1-b, the cromwell default. 

Do I have the default-zones in the correct location in the hierarchy?  This was taken from reference.conf, but might have gotten stale in v28.

Here is a snippet of my configuration:

```
backend {
  default = "JES"
    providers {
              JES {
              actor-factory = "cromwell.backend.impl.jes.JesBackendLifecycleActorFactory"
 	      .... snip...
	      genomics {
			....snip....

			   # Specifies the zone(s) to use for JES jobs unless overridden by a task's runtime attributes
			   default-zones = ["us-central1-f", "us-central1-c"]
		....snip....
```

**Comment by Horneth** [comment]
@LeeTL1220 
The configuration path seems to be different from the one you have (don't know if / when / why it changed).
Here's the current location for default runtime attributes: https://github.com/broadinstitute/cromwell/blob/develop/cromwell.examples.conf#L531

I did check and this is honored

**Comment by LeeTL1220** [comment]
Okay, I'll update and see if it works.  Regardless, you can close this issue.

**Comment by LeeTL1220** [comment]
(And this is an improvement -- I like it)

**Comment by LeeTL1220** [comment]
@Horneth Hey, in your reference.conf, you forgot `bootDiskSizeGb`, otherwise, this seems to have worked fine.

**Comment by Horneth** [comment]
@LeeTL1220 thx for the info, I will update the reference.conf
