### ISSUE TITLE
Administrators of a Cromwell should be able to restrict what Dockers are run

### ISSUE THREAD

**Issue by davidbernick** [broadinstitute/cromwell#2528]
Onprem and restricted environments can be really cagey about what Dockers are being run. Cromwell should be able to be configured (maybe in conf file? Maybe something more dynamic?) to restrict what Dockers are being run. Both the NIH and Broad Internal have mentioned the fact that unrestricted Dockers being run is something they're a bit cagey about. This would help them feel good, even if it eventually goes unused.

**Comment by aednichols** [comment]
Closing due to being old, and not having surfaced recently.
