### ISSUE TITLE
Ungrossify CWL to Wom following https://github.com/broadinstitute/wdl4s/pull/175

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2556]
I'm going to merge https://github.com/broadinstitute/wdl4s/pull/175 in case people are waiting for it, but I still need to ungrossify some of the CWL stuff. I think that's going to be better addressed in a later PR so it gets the attention it will need in PR

Specifically:
- [x] Uncomment the two tests in `CWLWorkflowWomSpec.scala`
- [ ] Remove the `.getOrElse(???)` in `WorkflowStep.scala`

**Comment by danbills** [comment]
need to fix the getOrElse still
