### ISSUE TITLE
Dynamic runtime determination of backend for a job

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2584]
In a Cromwell configured with multiple backends, be able to dynamically determine which backend to send a job based on where the input files live. 

1. If there are no files, use the default backend
2. If all of the files are on the same filesystem, use the backend associated w/ that filesystem (see below)
3. If the files are not all on the same filesystem, error

This will require moving backend determination (at least for many tasks) out of materialization and closer to the runtime dispatch.

Note that the 2nd stage really only works right now because there's (mostly) a 1-1 mapping of backend to filesystem. If you can find a way to do this slickly in a world where a backend might support multiple filesystems, so much the better.

Note also that this relates to #1312 (ideally this is done after that, but shouldn't matter too much either way). The workflow option should always override dynamic dispatch determination.

**Comment by katevoss** [comment]
More information in this [google doc](https://docs.google.com/document/d/1rdAhp0UrbyV4UbkBcAEXVu9g1yXW8Ybn59W3PL7hnwo/edit?ts=59554862#heading=h.ti1r65e7rwbp).

**Comment by geoffjentry** [comment]
This might happen some day, but that day is not today
