### ISSUE TITLE
Wire cromwell into cwl conformance tester

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2590]
Running locally: https://github.com/common-workflow-language/common-workflow-language/blob/master/CONFORMANCE_TESTS.md

Then get it on their master one: http://ci.commonwl.org/

Don't wire it into our travis yet as we won't be green for a while.

**Comment by mcovarr** [comment]
tl;dr we want a CLI that allows SWR Cromwell to be invoked through an interface that greatly resembles `cwltool`. Per `cwltest`, it might even be a good idea to call it that:

```
        # Add prefixes if running on MacOSX so that boot2docker writes to /Users
        with templock:
            if 'darwin' in sys.platform and args.tool == 'cwltool':
```

**Comment by geoffjentry** [comment]
also my likely incomplete understanding is that systems like arvados and bunny have their cwltest script actually launching a server and then converting the command line calls into http calls. another possibility.

**Comment by mcovarr** [comment]
Hmm maybe we should specify what we want here before I start writing... 🙂

**Comment by geoffjentry** [comment]
@mcovarr DoD is to have the conformance test exercising Cromwell in their CI. I know that that requires a command line program in a well known location, but they're not picky about the implementation of that program other than it's transforming that API they provide to the CWL implementation. I'm also not picky, was just throwing out a few other possibilities which might have been overlooked. 

If you're afraid of proceeding without some Bird-X, I'd suggest maybe writing up something (or via faces) describing how other systems handle this and seeing if anyone else has strong opinions.

**Comment by mcovarr** [comment]
OK, let me think this through as much as possible and write up the pros/cons I see in the different approaches. We can discuss in person before I start to code (faces over feces).

**Comment by mcovarr** [comment]
Actually if #1492 is done first there may not be a whole lot of difference between SWR and server mode interactions.

**Comment by geoffjentry** [comment]
Useful tidbit to note, [this is how you signal failure due to unimplemented functionality](https://github.com/common-workflow-language/common-workflow-language/pull/278/files#diff-ee814a9c027fc9750beb075c283a973cR49) - which I believe means that one can still be "green" on CI

**Comment by kshakir** [comment]
https://github.com/broadinstitute/cromwell/pull/2821 wires an always-passing build into travis so that curious developers can follow the ongoing conformance status.

TODO:
> get it on their master one: http://ci.commonwl.org/

**Comment by geoffjentry** [comment]
Thais is not done
