### ISSUE TITLE
REST Endpoint to shut down Cromwell

### ISSUE THREAD

**Issue by patmagee** [broadinstitute/cromwell#2595]
It would be nice to have a rest Endpoint which would cause Cromwell to stop launching any new Jobs, wait for a terminal state in all of the current jobs, then gracefully shutdown after a set delay.

The use case for this is an attempt to scale cromwell. We run a large number of workflows are and monitor the number of workflows per machine,  sometimes we need to increase the number of cromwells to accomodate the load, but then want to shut them off later

**Comment by geoffjentry** [comment]
@patmagee Why not send a `kill` signal to the process?

I see the utility of what you're asking for but this seems like something better handled via devops-y manipulation of the process itself. This also gets into the issue of needing to protect the endpoint in a situation where one doesn't trust all users to not be jerks.

**Comment by geoffjentry** [comment]
Hi @patmagee - we discussed this and don't believe it's a direction we want to go. With some of the new graceful shutdown functionality sending a `kill` signal should be drastically better vs what you experienced in the past
