### ISSUE TITLE
Check full dev CaaS usability

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2596]
Via Swagger (thus ignoring "how does a random user auth" issue):

- Attempt to interact with all endpoints other than `query`.
- For any interaction which does not work appropriately, file a ticket
- Document any non-obvious/trivial steps you needed to take to make things work (e.g. "now go to Sam and do `something`")

CaaS dev URL: https://cromwell.caas-dev.broadinstitute.org/

**Comment by kshakir** [comment]
All endpoints (other than`query`) verified in good working order.
