### ISSUE TITLE
Call caching Placeholder File Copied in the wrong mode

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2597]
https://gatkforums.broadinstitute.org/firecloud/discussion/10282/confusing-file-left-in-call-cached-execution-directory#latest

Even though the call-caching mode is set to copy, the outputs have been copied and unexpectedly -- a placeholder has also been written to the call directory. I'm not sure of the frequency of this event as I'm not sure how many people are checking call directories for jobs they expect to have cached. Ideally we'd never see this placeholder file in the case of the `copy` duplication-strategy for call caching.

**Comment by mcovarr** [comment]
I think is is complete given that #2601 and #2602 are merged.

**Comment by aednichols** [comment]
Closing due to being old, and not having surfaced recently.
