### ISSUE TITLE
Verify API based auth activity

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2598]
From both swagger & purely from command line verify that the following workflow (pardon the pun) works. If it does not, file tickets here or with Sam as appropriate. Create a doc detailing the outcome.

- Perform OAuth authentication (via clicky buttons in swagger, gcloud on CLI)
- Register user in Sam
- Submit workflow to Cromwell
- Get final results from Cromwell for that workflow

**Comment by kshakir** [comment]
RE: auth
- https://docs.google.com/document/d/1tVbhtMfzPv1vjkTlpmmlrdBgqJqXEeHttgjv6MIE6eQ/edit

**Comment by kshakir** [comment]
- [x] Perform OAuth authentication (via clicky buttons in swagger, gcloud on CLI)
- [x] Register user in Sam
- [x] Submit workflow to Cromwell
- [x] Get final results from Cromwell for that workflow
