### ISSUE TITLE
Add an option to turn off Docker hash lookups

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2600]
Per the linked forum post, add an option to turn off Docker hash lookups with the understanding that this would not be compatible with call caching.

https://gatkforums.broadinstitute.org/wdl/discussion/10279/problem-with-docker-images-pulled-self-hosted-registries

**Comment by katevoss** [comment]
@mcovarr is this related to #1670 or #1695 ?

**Comment by mcovarr** [comment]
It's not unrelated to those but in no way duplicates them.

**Comment by aednichols** [comment]
Closing due to being old, and not having surfaced recently.

**Comment by katevoss** [comment]
Hey now, who're you calling old? 😀

**Comment by aednichols** [comment]
Hi Kate! 👋

**Comment by geoffjentry** [comment]
@katevoss I was also referred to as old by @aednichols - although in my case it seems more deserving 😉

**Comment by aednichols** [comment]
I would be more offended at the apparent comparison to a marine mammal

>not having surfaced recently

**Comment by katevoss** [comment]
![giphy](https://user-images.githubusercontent.com/2395211/73525892-5e458000-4410-11ea-8d56-0f68d886d741.gif)
