### ISSUE TITLE
Fix runtime attributes

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2606]
Cromwell can fallback to configured default runtime attributes. The current implementation leverages the fact that `WdlExpression` extends `WdlValue`. This is not true anymore with WomExpressions. Find a way to fix this preferably without having WomExpression extend WdlValue.
This breaks runtime attribute validation in the `BackendWorkflowInitializationActor` and default runtime attributes.

**Comment by cjllanwarne** [comment]
Luckily, we now have a simple wrapper that can turn `WomValue`s into `WomExpression`s (which simply return the value given to them), so runtime attributes can be WomExpression, and the values given in the default runtime attributes can be easily converted into expressions
