### ISSUE TITLE
Call Caching .md5 files should have trailing whitespace removed

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2621]
A very common way of producing a side .md5 file is to use something like

`md5 -q dbsnp_138.vcf > dbsnp_138.vcf.md5`

Which produces a trailing newline character, which cromwell reads and interprets as part of the hash, thus causing cache misses against files that (a) were hashed by cromwell or (b) don't have a newline.  Not only isn't this the desired behavior... it's very confusing because it appears that sometimes call caching works and other times it does not.

Cromwell should strip out all trailing whitespace (e.g. \n, \r\n) from the data read in the .md5 file

**Comment by cjllanwarne** [comment]
We could go one further and say we should be verifying that it's actually an MD5?

**Comment by kcibul** [comment]
One could... but that does introduce some new complexity... how do you tell the user?  Is this more metadata?  If there are quick answers for those, then sure!

**Comment by geoffjentry** [comment]
I think for now it's safe to believe the user
