### ISSUE TITLE
Cromwell server start/stop script

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2623]
It would be really handy to have a `cromwell.server` script that would make starting and stopping a server cromwell easy.

```
$ cromwell.server start
... Started!

$ cromwell.server status
running

$ echo $?
0

$ cromwell.server stop
... Stopped!

$ cromwell.server status
stopped

$ echo $?
1
```

**Comment by katevoss** [comment]
@cjllanwarne What's the background here? What are users trying to do that it would make their lives easier? Not that I doubt it would, I just don't understand the use case.
