### ISSUE TITLE
Update CromIAM SAM resource type for `workflow`

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2629]
Doug will soon be changing the SAM resource type for workflows from `workflow` to something like `workflow-collection`.

CromIAM will need to be updated [here](https://github.com/broadinstitute/CromIAM/blob/a65b4569c40b10bd3477e0394f2c55dd1ddd234a/src/main/scala/cromiam/sam/SamClient.scala#L47).

This change must be synchronized with the change to SAM in the dev environments. NOTE: Doug has also mentioned that the existing workflow resources will not be migrated in SAM during this change.

**Comment by dvoet** [comment]
Merge this when ready https://github.com/broadinstitute/sam/pull/20
