### ISSUE TITLE
Allow simple string containment checks

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2634]
To make life easier for authors doing string checks like in https://gatkforums.broadinstitute.org/wdl/discussion/10354/multiple-backends-for-cromwell#latest

Eg:
```
File f
Boolean a = endsWith(basename(f), ".suffix")
Boolean b = startsWith(basename(f), "prefix.")
Boolean c = contains(basename(f), ".middle.")
```

**Comment by geoffjentry** [comment]
@cjllanwarne Can you start filing these sorts of tickets over in the WDL repo? (and move this one)

**Comment by cjllanwarne** [comment]
Moved to https://github.com/broadinstitute/wdl/issues/133
