### ISSUE TITLE
Socket file for cromwell server listener

### ISSUE THREAD

**Issue by CanWood** [broadinstitute/cromwell#2637]
To follow up #1653, would it be possible to have cromwell server mode be configurable to listen on a socket file, as an option instead of a TCP listener?  With correct permissions, this would allow a user to run a cromwell server that's listener is in a protected location?

This would allow regular users, who would not have access to set firewall rules on hosts, the tools they need to run their own secure listener.

Cheers!
CanWood

**Comment by geoffjentry** [comment]
Hi @CanWood - I don't *believe* so, at least not without radically changing all of our web code. We're using the [Akka HTTP](http://doc.akka.io/docs/akka-http/current/scala/http/) high level server API and I didn't see an ability to use such a thing. I might have missed it though.

**Comment by geoffjentry** [comment]
This would be a major change to the internals of Cromwell and unlikely to be on our roadmap in the near future. Closing for now
