### ISSUE TITLE
Spike: Get 1st-workflow cwl running in Cromwell

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2638]
Building off #2570 I think it'd be great to keep going!

Re-iterating the goal is to identify things needed to reach a stable working state.  The deliverables are:

* issues 
* PR on the `womification` branch of cromwell and/or wdl4s

**Comment by mcovarr** [comment]
https://github.com/broadinstitute/wdl4s/blob/develop/cwl/src/test/resources/three_step.cwl#L59

😮

**Comment by danbills** [comment]
I'm afraid we are not yet running 1st workflow, only 3 step.  Have a few more things to do here.

**Comment by gemlam3** [comment]
@danbills can we move this to in-progress or is there a PR in-review that is current?
