### ISSUE TITLE
Summing up Array[Floats] 

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#2650]
It would nice to have a way of summing up a list of floats like if you have a scatter task that you then want to gather the outputs of, its not straightforward on how you dynamically size that gather task.  This is what we currently do (and if it's stupid let us know!)

```
scatter (bam in list_of_bams) {
  call MakeBam{
    inputs:
      bam
  }

  Float mapped_bam_size = size(MakeBam.output_bam, "GB")
}

call SumFloats {
  input:
    sizes = mapped_bam_size,
}

.....
task SumFloats {
  Array[Float] sizes

  command <<<
  python -c "print ${sep="+" sizes}"
  >>>
  output {
    Float total_size = read_float(stdout())
  }
  runtime {
    docker: "python:2.7"
    preemptible: preemptible_tries
  }
}
```

**Comment by geoffjentry** [comment]
@jsotobroad Please file this in the wdl repo, not the cromwell repo

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/wdl #137](https://github.com/broadinstitute/wdl/issues/137) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsotobroad** [comment]
I was told to put it here!! sorry
