### ISSUE TITLE
Support http(s) imports

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#2677]
Allow users to write

import "http://foo.bar/my.wdl" as imp

Should support http / https

@katevoss -- I'm sure you've heard more requirements, just wanted to put a placeholder in here

**Comment by katevoss** [comment]
As a **user running subworkflows**, I want to **be able to reference and import workflows by URL**, so that I **can use subworkflows within my main workflow**.

@kcibul or @geoffjentry will this feature be WDL-specific? Or does CWL have a concept of subworkflows too?

**Comment by geoffjentry** [comment]
Cwl has a while section about imports in their spec

**Comment by kcibul** [comment]
This isn't done -- there's a Cromwell PR required as well (and probably a centaur one for tests)

**Comment by gemlam3** [comment]
@kcibul is this ready to be closed?
