### ISSUE TITLE
Unbreak release WDL after Cromwell unification

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2679]
Because the unification most definitely will break it.

**Comment by mcovarr** [comment]
Yup the release WDL has most definitely been broken. 🤕

**Comment by Horneth** [comment]
Good news is it should become simpler no ?

**Comment by mcovarr** [comment]
Yes definitely! 😄

**Comment by mcovarr** [comment]
I'll start looking at this in my spare cycles since I seem to be the one doing most of the breaking.
