### ISSUE TITLE
RFE: call_caching_placeholder.txt should contain details of the cache hit.

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/cromwell#2681]
I have a workflow where one of the inputs was created by a brand-new version of a tool, but it had a cache-hit for a run from 2 months ago. I can only assume that this is because the new input file had the exact same hash as the old input file, but because the google bucket the old input file was in is gone, I have no way to confirm this.

It seems like it would be fairly trivial, and extremely helpful, for this information to be contained in the call_caching_placeholder.txt, or some equivalent file when outputs are copied.

Thanks!

**Comment by katevoss** [comment]
@geoffjentry  is it possible to call cache when the original input no longer exists? 
@dheiman have you looked at the [call cache diff endpoint](https://github.com/broadinstitute/cromwell#get-apiworkflowsversioncallcachingdiff)? This is not available in FireCloud but it may have more information about why a workflow cached (or did not).

**Comment by dheiman** [comment]
@katevoss, it not being available in FireCloud is my high-level issue - it turns out that since FireCloud currently implements Cromwell 28, [call_caching_placeholder.txt gets placed, even though it is actually cache-by-copy rather than reference](https://gatkforums.broadinstitute.org/firecloud/discussion/10282/confusing-file-left-in-call-cached-execution-directory). 

This makes me believe that it should be trivial to leave a file or log entry with details of _why_ a call was cached, which would be quite useful to me, or anyone else trying to troubleshoot an unexpected occurrence like this.

**Comment by cjllanwarne** [comment]
@dheiman for what it's worth, "why a call was cached" is very conservative, so you can be assured that yes, your file's hash exactly matched the old input. As indeed did every other input value, the command string, the relevant workflow and runtime options, and the docker image specified.

If anything wasn't the same, Cromwell wouldn't have used the cached result.

**Comment by cjllanwarne** [comment]
@katevoss we can reuse the result even if the original input file is gone, because we record the hash of the file at execution time.

That way, even if the old input file is modified, we won't call-cache unless the new input file matches what was used to generate the original result.

**Comment by geoffjentry** [comment]
We view this as being resolved via the diff endpoint
