### ISSUE TITLE
Call input validation expects LHS of MemberAccess in the input mappings to be Calls, but now they can be scatter items too if the item is a pair.

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2692]
@Horneth commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48)

---

@meganshand commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261072803)

The attached wdl results in an error message:

`Workflow has invalid declarations: : AggregatedException: : VariableNotFoundException: Variable 'generateArray' not found`

[scratch_3.wdl.txt](https://github.com/broadinstitute/wdl4s/files/595927/scratch_3.wdl.txt)

---

@Horneth commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261089538)

@meganshand 

This is actually a different problem - Cromwell doesn't support (yet) Workflow Declarations that reference call outputs. This wouldn't work either:

```
task t {
  command {
    echo "hello"
  }
  output {
    String o = read_string(stdout())
  }
}

workflow w {
  call t
  String declarationDependingOnCallOutput = t.o
}
```

---

@meganshand commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261092137)

Oh no! This actually makes using zips infeasible, since I'd imagine in most cases the things you want to zip will be outputs from previous tasks. I suppose I can use a workaround where inside of a scatter loop I can create a task that takes in a File and Array[File] and outputs a Pair, then scatter over the output of that task outside of the original scatter.

---

@meganshand commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261095003)

I tried that workaround with a task like this:

```
task ZipUpWorkaround {
  File unmapped_bam
  Array[File] fastqs

  command {
    #do nothing
  }
  output {
    Pair[File, Array[File]] p = [unmapped_bam, fastqs]
  }
}
```

and got this error message (after it submitted that task):
`Failed to evaluate outputs.: WdlTypeException: Arrays/Maps must have homogeneous types`

---

@Horneth commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261095284)

I think `Pair`s are declared with parenthesis and not brackets. Does 

```
output {
    Pair[File, Array[File]] p = (unmapped_bam, fastqs)
  }
```

work ?

---

@Horneth commented on [Wed Nov 16 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261096132)

Also, as long as you don't declared the zip as a workflow variable you should be fine. For example, this should work:

```
task t {
  command {
    echo "hello"
    echo "world"
  }
  output {
    Array[String] o = read_lines(stdout())
  }
}

task t2 {
   Array[Pair[String, String]] p
  command {
   #do something
  }
  output {
    Array[Pair[String, String]] o = p
  }
}

workflow w {
  call t
  call t as u
  call t2 { input: zip(t.o, u.o) }
}
```

---

@meganshand commented on [Thu Nov 17 2016](https://github.com/broadinstitute/wdl4s/issues/48#issuecomment-261247751)

Pair with ( ) worked perfectly with the workaround tasks. I tried to not declare a workflow variable, but since I need to scatter over the zipped array I did the following:

`scatter(unmapped_pair in zip(QuerySortSam.sorted_bam, SamToFastq.fastqs)){`

Which gave me the error:

`Workflow input processing failed.
Unable to load namespace from workflow: Unrecognized token on line 282, column 55:`

Regardless, for my current use case I'm happy with my workaround, and using Pair seems to be working! Thanks!

**Comment by katevoss** [comment]
@Horneth can you explain the problem?

**Comment by cjllanwarne** [comment]
This has been fixed for a while - it's quite possible to assign task outputs into declarations. Closing.
