### ISSUE TITLE
wdl4s not erroring when a scatter variable is missing

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2699]
@kshakir commented on [Mon Feb 27 2017](https://github.com/broadinstitute/wdl4s/issues/92)

The following wdl currently parses in wdl4s without error, later causing an error within cromwell.

```
workflow undeclared_scatter_variable {
    scatter (i in undeclared) {}
}
```

See https://github.com/broadinstitute/cromwell/issues/2020 for more info of cromwell patches, including a centaur test, that may be updated or removed if this is fixed in wdl4s.

**Comment by katevoss** [comment]
@kshakir Will this still be an issue now that WDL4S is in Cromwell?

**Comment by kshakir** [comment]
Fixed by https://github.com/broadinstitute/wdl4s/pull/105
