### ISSUE TITLE
wdl4s not erroring when an output variable is missing

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2700]
@kshakir commented on [Mon Feb 27 2017](https://github.com/broadinstitute/wdl4s/issues/93)

The following wdl currently parses in wdl4s without error, later causing an error within cromwell.

```
task x {
    Int i
    command { echo $i }
    runtime { docker: "ubuntu" }
    output {
        Int out_but_intentionally_misnamed = i
        Boolean validOutput = i % 2 == 0
    }
}

workflow missing_optional_output {
  Array[Int] arr = [0,1,2,3]
  scatter (i in arr) {
    call x { input: i = i }
    if (x.validOutput) {
      Int x_out = x.out_except_undeclared
    }
  }

  Array[Int?] x_out_maybes = x_out
}
```

See https://github.com/broadinstitute/cromwell/issues/2020 for more info of cromwell patches, including a centaur test, that may be updated or removed if this is fixed in wdl4s.

**Comment by katevoss** [comment]
@kshakir same question as #2699 , is this still a problem now that WDL4S is in Cromwell?

**Comment by kshakir** [comment]
Closing this, as the above now fails fast during Materialization in cromwell/develop. Previously this would try to run several jobs and then fail (possibly) hours later.

For the curious, from going through the git history, I believe https://github.com/broadinstitute/cromwell/pull/2647 is the first time this started failing fast in cromwell. From that commit's [Dependencies.scala](https://github.com/broadinstitute/cromwell/pull/2647/files#diff-0ecdbc5a001d52fb34f5eafb7cd1aaa6), here are the four commits on the wdl4s side around that time too:  https://github.com/broadinstitute/wdl4s/compare/ba89da9...f63dc02
