### ISSUE TITLE
Allow arrays to be concatenated, flattened

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2702]
@cjllanwarne commented on [Mon May 22 2017](https://github.com/broadinstitute/wdl4s/issues/111)

egs:
```
# Inputs
Array[Array[X]] xs
Array[Y] ys_1
Array[Y] ys_2

# New functionality we should support:
Array[X] flat_xs = flatten(xs)
Array[Y] flat_ys = flatten(ys_1, ys_2)
```

**Comment by katevoss** [comment]
@cjllanwarne can you explain more about what this issue is for?

**Comment by ldgauthier** [comment]
@katevoss I would love to have this functionality.   I'm effectively nesting two scatters (by scatter over calls to a subworkflow with a scatter), which returns an Array[Array[File]].  Nothing happens to those Files at the top level, they just get passed up the callstack, so it doesn't matter to me which scatter generated which subset of Files.  It would be nice to be able to operate on a flattened Array of Files at the top level to avoid gathering and moving extra data or making the WDL unnecessarily complicated.

**Comment by geoffjentry** [comment]
@ldgauthier You'll be wanting to talk to @cjllanwarne (also this is effectively a WDL question, not a Cromwell question)

**Comment by ldgauthier** [comment]
I thought that @katevoss was looking for use cases for this issue.  Sorry for spamming your github issues.

**Comment by geoffjentry** [comment]
@ldgauthier Oh no worries, this is a good enough place for the ticket, the main nugget of info there was the point of contact change from @katevoss to @cjllanwarne

**Comment by geoffjentry** [comment]
Closing this as it is a WDL speci ssue
