### ISSUE TITLE
CWL Parser support Any types

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2706]
@danbills commented on [Wed Jun 28 2017](https://github.com/broadinstitute/wdl4s/issues/122)

The CWL specification declares an "Any" type which does not have an analogous JSON type.  It seems it can support any JSON value be it an object, String, etc.

**Comment by katevoss** [comment]
@danbills is there an existing issue for this in Cromwell? Or is it specific to wdl4s?

**Comment by danbills** [comment]
Specific to wdl4s, so no it is not in Cromwell

**Comment by katevoss** [comment]
Therefore it can be closed as wdl4s is in Cromwell, or it needs to be kept?

**Comment by danbills** [comment]
I'm a little confused, but this is the only issue that I know of and  it needs to be kept open as it is not yet implemented.

**Comment by katevoss** [comment]
Got it, sorry for the confusion.

**Comment by danbills** [comment]
We have a plan to implement commonly seen types and a catchall `Json` type for any others.
