### ISSUE TITLE
[Wom] Superset Types that accomodate both WDL and CWL

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2711]
@danbills commented on [Mon Jul 31 2017](https://github.com/broadinstitute/wdl4s/issues/154)

Currently wom is using WdlType directly.   We should create a superset of the types each supports and use that instead.

**Comment by katevoss** [comment]
@danbills is this still to-do?

**Comment by danbills** [comment]
Yes.  I believe @mcovarr is looking at this now.
