### ISSUE TITLE
Investigate long compile times for wdl4s cwl subproject

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2712]
@mcovarr commented on [Mon Jul 31 2017](https://github.com/broadinstitute/wdl4s/issues/156)

It appears that some relatively recent changes have greatly extended compile times into multiple minutes, probably due to Circe decoding and encoding.  Investigate and see if there's anything that can be done to lessen the pain.

---

@geoffjentry commented on [Mon Jul 31 2017](https://github.com/broadinstitute/wdl4s/issues/156#issuecomment-319094471)

@mcovarr "anything that can be done"

Remove Circe autoencoding? :)

On a serious note, wdl4s still needs to be bumped up to 2.12.3 which should help a bit. In fact I'll do that now.

---

@mcovarr commented on [Mon Jul 31 2017](https://github.com/broadinstitute/wdl4s/issues/156#issuecomment-319094942)

We tried 2.12.3 locally and whatever improvement there was didn't rock our worlds.

---

@kshakir commented on [Wed Sep 13 2017](https://github.com/broadinstitute/wdl4s/issues/156#issuecomment-329144787)

Some things to also try:

[![Generic Derivation: The Hard Parts—Travis Brown](http://img.youtube.com/vi/80h3hZidSeE/0.jpg)](https://youtu.be/80h3hZidSeE?t=34m7s "Generic Derivation: The Hard Parts—Travis Brown")

---

@danbills commented on [Mon Sep 18 2017](https://github.com/broadinstitute/wdl4s/issues/156#issuecomment-330304677)

I propose we move everything JSON-related into a subproject that depends on the object model. 

This would allow rapid development and testing of CWL -> WOM.  

Json stuff is pretty small and contained so it wouldn't be too spaghetti-y.

**Comment by katevoss** [comment]
@danbills is it still taking a long time to compile?

**Comment by danbills** [comment]
It is still taking a long time to compile, yes.

I think an easy win would come with breaking encoding out into another project and not including it in the root.  I'll give that a try.

**Comment by katevoss** [comment]
As a **Cromwell dev**, I want **the wdl4s-CWL subproject to compile quickly**, so that **I don't waste my time waiting and waiting**.
- Effort: small? 
   - As @danbills mentioned, maybe putting Circe encoding into another project will save time.
- Risk: small
- Business value: Small
