### ISSUE TITLE
true & false statements in command

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2713]
@ruchim commented on [Fri Aug 11 2017](https://github.com/broadinstitute/wdl4s/issues/168)

The wdl docs say that when using the true/false syntax in the command block, one can get away with declaring just one of the 2, however the WDL fails validation and fails to create a namespace and therefore never gets run. 

AC:
Actually allow being able to declare True or False and statements OR Keep enforcing that both the behavior for true/false need to be defined, and adjust that expectation in the docs accordingly.

https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#true-and-false

**Comment by katevoss** [comment]
@ruchim is this still to-do? What would the effort be (small, medium, large)?

**Comment by cjllanwarne** [comment]
@katevoss I don't think this belongs under the "CWL label... I'd guess it's more "minor bug fix"

**Comment by cjllanwarne** [comment]
This was addressed in the WDL spec: https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#true-and-false

Closing this issue with no changes needed in Cromwell.
