### ISSUE TITLE
Support CWL expressions in WOM

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2714]
@mcovarr commented on [Wed Aug 16 2017](https://github.com/broadinstitute/wdl4s/issues/174)

**Comment by katevoss** [comment]
@mcovarr is this a dupe of #2524 ?

**Comment by katevoss** [comment]
@kshakir is this still a to-do?

**Comment by kshakir** [comment]
As mentioned above, this is a dupe.
