### ISSUE TITLE
Publish scaladoc for CWL library

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2715]
@danbills commented on [Thu Aug 17 2017](https://github.com/broadinstitute/wdl4s/issues/177)

Once it's available it would be nice to have scaladocs published for CWL as they are for WDL

**Comment by katevoss** [comment]
@danbills what kinds of docs are these?

**Comment by danbills** [comment]
These docs are auto-generated descriptions of our scala code.
