### ISSUE TITLE
WOM CommandPart redo

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2717]
@Horneth commented on [Mon Sep 11 2017](https://github.com/broadinstitute/wdl4s/issues/195)

WOM currently uses the WDL CommandPart which contains WDL specific constructs (WdlFunctions)
WOM should get its own CommandPart.
Also factor in the fact that tweaks will have to be made in the way the command is instantiated depending on the language or even language configuration (this might be better put in the TaskDefinition instead though)

**Comment by katevoss** [comment]
@Horneth is this still to-do?

**Comment by Horneth** [comment]
Yep I'll close it
