### ISSUE TITLE
Document CWL usage and highlight cwltool requirement in README

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2718]
@danbills commented on [Mon Oct 02 2017](https://github.com/broadinstitute/wdl4s/issues/245)

**Comment by katevoss** [comment]
@danbills what kind of docs are necessary here?

**Comment by danbills** [comment]
* one must install `cwltool` to test the code and/or use CWL functionality
* show people how to use CWL parsing 
* give some pointers as to how to use coproducts

**Comment by denis-yuen** [comment]
- what version of cwltool is used and versions of transitive dependencies if known
