### ISSUE TITLE
Test CWL ECMAScript Functions

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2719]
@danbills commented on [Mon Oct 02 2017](https://github.com/broadinstitute/wdl4s/issues/243)

Currently we are focused on delivering ECMAScript "Expressions" which are denoted w/ `$(...)`.

ECMAScript functions, denoted by `${....}` (i.e. w/ braces instead of parens) are as of yet untested.

Creating this ticket so I can move forward with spike https://github.com/broadinstitute/cromwell/issues/2638

**Comment by katevoss** [comment]
@danbills any update on this ticket?

**Comment by danbills** [comment]
nope
