### ISSUE TITLE
Support "complex" workflow input types in CWL

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2720]
@Horneth commented on [Thu Sep 28 2017](https://github.com/broadinstitute/wdl4s/issues/238)

Currently only primitive types are supported in workflow inputs in CWL.
`***RecordSchema` and array support should be added

**Comment by katevoss** [comment]
@Horneth is this still to-do?

**Comment by Horneth** [comment]
yep

**Comment by katevoss** [comment]
As a **user running CWL scripts**, I want **Cromwell to process complex workflow input types**, so that **I can run my workflow with complex inputs**.
@Horneth what's an example of a complex input?
