### ISSUE TITLE
Handle cwl.outputs.json with respect to outputBinding

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2721]
@danbills commented on [Thu Sep 28 2017](https://github.com/broadinstitute/wdl4s/issues/237)

Per the CWL Spec:

>  If the file cwl.outputs.json is present in the output, outputBinding is ignored.

http://www.commonwl.org/v1.0/CommandLineTool.html#File

**Comment by katevoss** [comment]
@danbills this is still to-do, right?

**Comment by danbills** [comment]
yep
