### ISSUE TITLE
CWL Requirements, hints etc.. in WOM

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2726]
@Horneth commented on [Mon Sep 11 2017](https://github.com/broadinstitute/wdl4s/issues/204)

CWL has a lot of meta information that is currently not available in WOM.
This could be part of a larger work and include re-work of WDL runtime attributes but those bits need to make it to Cromwell somehow.

**Comment by katevoss** [comment]
@Horneth is this necessary for CWL support?

**Comment by Horneth** [comment]
Yes

**Comment by mcovarr** [comment]
There's general support for hints and requirements in CWL now but I'm not sure if that satisfies the requirements of this ticket.

**Comment by Horneth** [comment]
I feel like we could close it for now and make tickets for individual not supported requirements as needed
