### ISSUE TITLE
Custom WOM Call outputs

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2727]
@Horneth commented on [Mon Sep 11 2017](https://github.com/broadinstitute/wdl4s/issues/203)

Wom currently automatically derives call outputs from TaskDefinition.
CWL separately declares call outputs and "run" outputs, which mean the former could be a subset of the latter. Make it so that WOM can support this use case.

**Comment by katevoss** [comment]
@Horneth is this still to-do?

**Comment by Horneth** [comment]
yep
