### ISSUE TITLE
CWL Workflow name

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2728]
@Horneth commented on [Mon Sep 11 2017](https://github.com/broadinstitute/wdl4s/issues/202)

The CWL parser currently hardcode the same name for all workflows.
Find out if CWL has a way to specify a workflow name. If not use a hash ? A new endpoint parameter ?
@katevoss this could use PO input if it turns out CWL has no way to specify a workflow name

---

@danbills commented on [Tue Oct 03 2017](https://github.com/broadinstitute/wdl4s/issues/202#issuecomment-333894259)

So it turns out that CWL v1.0.2 has an `id` field for Workflow, and cwltool gives us one for free:

http://www.commonwl.org/v1.0/Workflow.html#Workflow.

so we should update the model to have a required `id: String` and this problem goes away.

---

@danbills commented on [Tue Oct 03 2017](https://github.com/broadinstitute/wdl4s/issues/202#issuecomment-333894392)

This also applies to `CommandLineTool`, cwltool pre-processing gives us one.

**Comment by katevoss** [comment]
Is this still to-do?

**Comment by Horneth** [comment]
yep

**Comment by cjllanwarne** [comment]
I'm picking this up as a hopefully gentle "intro to CWL stuff" ticket
