### ISSUE TITLE
Make WomExpression evaluateValue method asynchronous

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2729]
@Horneth commented on [Mon Sep 11 2017](https://github.com/broadinstitute/wdl4s/issues/200)

This is a nice to have. `IoFunctionSet` already returns `Future`s for I/O methods. It would be nice to have the evaluate method itself be asynchronous to allow for a fully asynchronous evaluation.
Whether or not WDL evaluation should be made asynchronous too is left to implementor.

**Comment by katevoss** [comment]
@Horneth if this is a nice-to-have then I'll take it out of the Milestone, which is our goal for Q4

**Comment by Horneth** [comment]
If we don't do it now we'll very very unlikely do it later and you might as well close it.
