### ISSUE TITLE
Support CWL and WDL expressions in WOM

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2732]
@danbills commented on [Tue Aug 01 2017](https://github.com/broadinstitute/wdl4s/issues/159)

There is no formal way to represent CWL expressions in WOM.

We seek to support the evaluation of both WDL and CWL expressions.

For reference: [CWL Expression](http://www.commonwl.org/v1.0/CommandLineTool.html#Expressions)

---

@danbills commented on [Tue Aug 01 2017](https://github.com/broadinstitute/wdl4s/issues/159#issuecomment-319495280)

also see `outputEval` in [CommandLineBinding in CWL](http://www.commonwl.org/v1.0/Workflow.html#CommandOutputBinding)

**Comment by katevoss** [comment]
@danbills this was formerly an epic, does it still have any useful information?

**Comment by danbills** [comment]
It doesn't have useful information, but it is not yet complete.
