### ISSUE TITLE
call caching for directories

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2735]
It is very common to provide folders as inputs to different bioinformatic tools. For instance, STAR index is usually computed once per reference genome and then provided to each STAR-based RNA-Seq task as an input. However, when this is done a common caching failure is reported (because it is a folder):
```
"hashFailures": [
            {
              "causedBy": [],
              "message": "Is a directory"
            }
```

**Comment by antonkulaga** [comment]
Any progress on this?
This issues causes our lab a huge amount of pain.

**Comment by geoffjentry** [comment]
Now that there's a concrete `Directory` type, this should work as expected
