### ISSUE TITLE
Running tasks depth first?

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [broadinstitute/cromwell#2736]
From looking at the behaviour of cromwell, I think it traverses the execution graph (is that what it's called, the order in which tasks are run?) breadth-first, (e.g.  first perform trimming for all samples, then mapping for all samples, then genotyping, etc).

For most workflows, different tasks will have different performance characteristics (trimming and mapping is read/write heavy, genotyping is mostly read/CPU intensive). Would it then not make sense to do a depth first traversal of the execution graph? That way, we will have the most diversity in performance characteristics for all running tasks, which should speed up the overall runtime (e.g. no fighting over harddisk time between two trimming tasks)

As a secondary bonus, depth first will mean that all different tasks are run as soon as possible, so when there is an error in one of the later tasks this is revealed to the user much more quickly.
The drawback is that cromwell will then also stop running the early tasks that do not give an error, but IIRC that behaviour is configurable in the settings file.

**Comment by geoffjentry** [comment]
In theory it shouldn't make a difference.* Cromwell isn't scheduling anything, it's merely seeing what is runnable and launching it. Thus the time delta should be miniscule. However, in the real world there are things such as quotas on the backend and that could make a difference, yes. But keep in mind that backends will themselves process job requests differently and aren't necessarily going to honor the order we send them in anyways. Thus, in my opinion this sort of general optimization is going to be folly as we can never guarantee the underlying behavior anyways.

To your primary point, I get what you're saying although my experience has been that every time someone has stated that a behavior should be X as it matches the real world I find someone telling me that the opposite behavior matches the real world. :) This is one of those cases. This one is more complex in that we also hear differing opinions on the whole workflow level (ie should workflows be processed as many at once as possible or optimizing for throughput for any individual workflow). At the end of the day the limiting factor is going to be the backend set up and whatever quotas are in place.

* Yes, there is a global job limit but this can be tweaked as high as one would like, so effectively not an issue.

**Comment by Horneth** [comment]
Out of curiosity, did you observe a behavior that makes you think that tasks are not being run as early as they could be ?
Cromwell periodically traverses the "unstarted" nodes to determine if all their dependencies are satisfied, and if so starts the task, which should effectively run all tasks as soon as possible.

**Comment by geoffjentry** [comment]
This might be something we look at in the future but is unlikely to be on our roadmap in the upcoming future. Closing this for now
