### ISSUE TITLE
PAPI requests don't get removed from queue when aborted

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2750]

**Comment by geoffjentry** [comment]
@Horneth just for my own mental book keeping, what led to this?

**Comment by Horneth** [comment]
More people are using the JG server to launch multiple workflows w/ jobs on the order of 10k and it's being slow to start those jobs. There's definitely something going on w/ memory still but one explanation is also that jobs are being queued and throttled in Cromwell to respect quota for submission which is good, but if we have tens of thousands of then it might take some time to start them. Jose submitted a 40k jobs workflow and aborted it almost immediately and it got me thinking that *if* they were in that queue they would still be submitted.

**Comment by Horneth** [comment]
Fixed by https://github.com/broadinstitute/cromwell/pull/2808
