### ISSUE TITLE
non-api endpoints should be public

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2766]
Currently the endpoints not off of `/api` (e.g. `/engine/Segment/version`) still require an authorization header. This should not be the case. These endpoints should be fully public.

**Comment by gemlam3** [comment]
@geoffjentry can you connect this ticket to https://github.com/broadinstitute/CromIAM/pull/18 so they move together?

**Comment by geoffjentry** [comment]
@gemlam3 done
