### ISSUE TITLE
Default limit on file input to read_lines is too small

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2768]
Currently, this is set to default to 128000.  This is too small for most practical use, especially given that gs URLs can get quite long.  Can the new limit be much higher?  We'll need 5GB (no joke!) for some our larger analyses.  Or at least a workflow option to temporarily override?

Otherwise, we get an error such as:
```"Workflow has invalid declarations: Could not evaluate workflow declarations:\nSingleSampleGenotyping.gvcfs_list:\n\tUse of WdlSingleFile(gs://broad-dsde-methods/gauthier/Finnish_FE_WGS.1000samples.gvcf_list) failed because the file was too big (174730 bytes when only files of up to 128000 bytes are permissible"```

**Comment by cjllanwarne** [comment]
One person's "way too small" is another's "way too big" so whatever we have is going to be inappropriate for somebody...

On the other hand, 128k does seem a little too small (at least until we have actual, real FoFN support)

**Comment by Horneth** [comment]
> We'll need 5GB (no joke!) 
Hmm it doesn't seem like a good idea to load a 5GB file over network in Cromwell's memory 😄

**Comment by geoffjentry** [comment]
The limit is intentionally small. If you’ve got that much data you shouldn’t be using read lines

**Comment by LeeTL1220** [comment]
@ldgauthier has the actual use case.  We've already upgraded the methods cromwell.  Is there a way to scatter over an iterator, so the whole list does not have to be read into RAM?

**Comment by geoffjentry** [comment]
@LeeTL1220 No although there have been discussions about potentially adding operators to WDL which could provide optional streaming - I wouldn't expect to see that until after WDL 1.0 but YMMV.

It seems unlikely that the limits for `read_X()` would be drastically increased. Even if we thought it'd be a good idea for Cromwell (it's not), it'd also require the same behavior for other implementers, and if different implementations had different limits the workflows would not be portable.

**Comment by geoffjentry** [comment]
Also, this is really a WDL issue and not a Cromwell issue. The Cromwell team no longer directly controls WDL.

**Comment by geoffjentry** [comment]
Deleting some comments due to being interspersed with untrue things.

@LeeTL1220 

As per #1762 the intention was to have spec mandated minimums and implementation level maximums. The former never happened so technically it's not part of the spec at all. And as I noted, Cromwell team is no longer in charge of the WDL spec, so ...

That said, it's tunable. You can increase it if you want. I wouldn't recommend going all that high unless you're willing to really jam a lot of memory in there.

As per your iterator comment, I go back to the Cromwell team doesn't control WDL anymore and there's no WDL construct which would allow that. There's been chatter about things which might help but they're unlikely to arrive until after WDL 1.0

**Comment by LeeTL1220** [comment]
If it can be specified by a workflow option, then everyone is happy.  And
we don't have to wait for 1.0.

**Comment by geoffjentry** [comment]
The point of the setting is to protect the server from users. Putting the power directly in the hands of the users seems unwise

**Comment by githubshuangluo** [comment]
I am using exactly the wdl and json offered by gatk GitHub page for gatk4-germline-snps-indels, locally, I got this error, intervals-hg38.even.handcurated.20k.intervals is larger than 128000 Bytes. Maximum read limits can be adjusted in the configuration under system.input-read-limits.
I tried to change it via type this in command line: java -Dsystem.input-read-limits=500000 -jar /cromwell-34.jar 
Didn't work.
Who can tell me how to fix it?

**Comment by danbills** [comment]
You want `java -Dsystem.input-read-limits.lines=500000 -jar /cromwell-34.jar`

For reference you are setting this:
https://github.com/broadinstitute/cromwell/blob/0ad9cb61f90276e3576f6ba135cab65c02f09a9e/core/src/main/resources/reference.conf#L157

**Comment by githubshuangluo** [comment]
Thanks very much. Problem solved.

**Comment by ruchim** [comment]
@LeeTL1220 since its possible to configure this limit as needed, I'm hoping you've got what you needed. Feel free to reopen if I missed something.
