### ISSUE TITLE
Less wasteful, more accurate 64KB file limit in CWL

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2771]
Ideal:
- Read the first 64KB of data from the file.
- There you go.

Now:
- Take the whole file (all 400GB) into memory
- Carefully select the first `64 * 1024` characters (not bytes)
- Drop the rest on the floor (but only at GC time)

**Comment by geoffjentry** [comment]
Iirc the limit in cwl was a minimum and not a maximum. We could tie this into the standard limits we have for wdl

**Comment by cjllanwarne** [comment]
It could, I sort-of don't like the idea of encouraging non-portable workflows by allowing users to make the read-length higher in config files without making that explicit in the CWL

**Comment by geoffjentry** [comment]
THIs wouldn’t be us contributing to nonportability, the feature is inherently non portable

**Comment by geoffjentry** [comment]
Note that I don’t really care but it seems like it’d be simpler for us and it’s not being skeezy or anything, that was literally how they intended it to work
