### ISSUE TITLE
No information from workflow to debug when Cromwell can't delocalize a missing file

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2774]
This may be a known issue, in which case feel free to link this to that. If not...

I ran a workflow on the DSDE-Methods server, which is running on P.API, and it failed when a file didn't exist. I was running a CNV pipeline to create a Panel of Normals, and a few of the bams (and their bai's) in the list did not exist.

From @LeeTL1220: Cromwell can't localize a file because the file does not exist. As a result, instead of saying it, it does not create workflow root directory, doesn't make any usable log files.
The error message is just the name of the file, rather than to say that this file is missing.

**Comment by bradtaylor** [comment]
We get 'fail to delocalize' as the error message over a bunch of failure types. In particular, when the task failed with return code 0. This makes failures hard to debug in FireCloud, as users have to dig down into logs.

**Comment by geoffjentry** [comment]
:+1: this has been pointed out as something which should be resolved prior to the GATK launch

**Comment by katevoss** [comment]
This is a dupe of #2740, closing.
