### ISSUE TITLE
Add workflow option to not run new job upon certain call cache errors

### ISSUE THREAD

**Issue by abaumann** [broadinstitute/cromwell#2787]
For instance, someone used "docker.io/<their image>" path in their runtime block and this led to a failure to call cache since call caching doesn't support docker.io urls.  

Right now, since this failed to call cache it reran the job, however this was due to user error and they assumed caching would work.  Additionally, there are cases such as when there's a failure to communicate with dockerhub that would also lead to failure to call cache.

This request is for a workflow option that worked in conjunction with read_from_cache that set this behavior more strictly - if there is call cache miss, then run a new job, but if there is any other type of failure to call cache (transient, bad url, etc) then fail the job for the reason that the user requested to call cache and call caching failed to determine caching correctly.

**Comment by gemmalam** [comment]
This ticket has been moved to Jira. BA-2787
