### ISSUE TITLE
Task failing with "the local copy message must have path set" but no other logs are output.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/cromwell#2791]
"failures": [{"causedBy": [{"causedBy": [],"message": "the local copy message must have path set."}],"message": "Unable to complete JES Api Request"}]

See workflow metadata at: https://cromwell-v29.dsde-methods.broadinstitute.org/api/workflows/v1/4ff9cb8a-cade-482a-8492-66ea3b7a2eaa/

**Comment by samuelklee** [comment]
Apologies, that metadata appears to have disappeared, but the same issue is referenced here: https://gatkforums.broadinstitute.org/firecloud/discussion/10740/error-the-local-copy-message-must-have-path-set/p1?new=1

**Comment by LeeTL1220** [comment]
I'm getting this as well.

**Comment by LeeTL1220** [comment]
This workflow works fine with SGE and local backends.

**Comment by LeeTL1220** [comment]
And only exec.sh is present in the bucket (no log etc)....
```#!/bin/bash
tmpDir=$(mktemp -d /cromwell_root/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /cromwell_root
java -Xmx4g -jar /cromwell_root/broad-dsde-methods/lichtens/test_cnv_validation/gatk.jar ModelSegments \
    --denoisedCopyRatios /cromwell_root/broad-dsde-methods/lichtens/cromwell-executions-test-dl-oxoq-full/CNVValidation/6246d2fa-a8e5-49c0-ac38-8ae33867f394/call-cnvPair/CNVSomaticPairWorkflow/c8a063ce-0309-45a1-a6cf-25fdcfe4245c/call-DenoiseReadCountsNormal/G25783.TCGA-55-6986-11A-01D-1945-08.2.denoisedCR.tsv \
    --allelicCounts /cromwell_root/broad-dsde-methods/lichtens/cromwell-executions-test-dl-oxoq-full/CNVValidation/6246d2fa-a8e5-49c0-ac38-8ae33867f394/call-cnvPair/CNVSomaticPairWorkflow/c8a063ce-0309-45a1-a6cf-25fdcfe4245c/call-CollectAllelicCountsNormal/attempt-3/G25783.TCGA-55-6986-11A-01D-1945-08.2.allelicCounts.tsv \
     \
    --maxNumSegmentsPerChromosome 500 \
    --minTotalAlleleCount 30 \
    --genotypingHomozygousLogRatioThreshold -10.0 \
    --genotypingBaseErrorRate 0.05 \
    --kernelVarianceCopyRatio 0.0 \
    --kernelVarianceAlleleFraction 0.01 \
    --kernelScalingAlleleFraction 1.0 \
    --kernelApproximationDimension 100 \
    --windowSize 8 --windowSize 16 --windowSize 32 --windowSize 64 --windowSize 128 --windowSize 256 \
    --numChangepointsPenaltyFactor 1.0 \
    --minorAlleleFractionPriorAlpha 25.0 \
    --numSamplesCopyRatio 100 \
    --numBurnInCopyRatio 50 \
    --numSamplesAlleleFraction 100 \
    --numBurnInAlleleFraction 50 \
    --smoothingThresholdCopyRatio 2.0 \
    --smoothingThresholdAlleleFraction 2.0 \
    --maxNumSmoothingIterations 10 \
    --numSmoothingIterationsPerFit 0 \
    --output . \
    --outputPrefix G25783.TCGA-55-6986-11A-01D-1945-08.2
)
echo $? > /cromwell_root/ModelSegmentsNormal-rc.txt.tmp
(
cd /cromwell_root

)
sync
mv /cromwell_root/ModelSegmentsNormal-rc.txt.tmp /cromwell_root/ModelSegmentsNormal-rc.txt```

**Comment by samuelklee** [comment]
The only difference between the tasks is a single optional parameter (File? normal_allelic_counts in the WDL here: https://github.com/broadinstitute/gatk/blob/sl_wgs_acnv/scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl)

**Comment by cy-bao** [comment]
True. This workflow works fine with local backends and FC without normal_allelic_counts.

I guess cromwell read null as a file based on line 141 in file "ModelSegments.java ".  Then, it return the message "the local copy message must have path set.". Not sure...

ModelSegments.java 
141   private File inputNormalAllelicCountsFile = null;

**Comment by cy-bao** [comment]
It seems that “” is not an acceptable value for FC in cnv_somatic_pair_workflow.wdl:
File? normal_het_allelic_counts = if defined(normal_allelic_counts) then "${output_dir_}/${entity_id}.hets.normal.tsv" else ""  

So, my new solution is:
File? normal_het_allelic_counts = if defined(normal_allelic_counts) then "${output_dir_}/${entity_id}.hets.normal.tsv" else "${output_dir_}/${entity_id}.hets.tsv"   

Thanks a lot! 

Best,
Chunyang

**Comment by ruchim** [comment]
@cy-bao is this still the case on the latest version of Cromwell in FireCloud? 

All future updates to this issue will be made in JIRA: 
https://broadworkbench.atlassian.net/browse/BA-2791
Sorry for the inconvenience.
