### ISSUE TITLE
Don't abort prematurely on workflow restart

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2820]
There's some flakiness in the abort tests right now, I believe the reason is we tend to abort too quickly when a workflow is being restarted (for example if we receive an abort message during materialization, we'll assume that it's fine to stop without going further, which is not the case if the workflow is being restarted as jobs might be running and need to be reconnected to)

**Comment by geoffjentry** [comment]
@Horneth Does this mean we should hold off before claiming we "fixed aborts"? :)

**Comment by Horneth** [comment]
Well that doesn't make it worse than it used to but yeah it's not 100% there. This shouldn't be hard to fix though.
