### ISSUE TITLE
Re-implement globbing in WDL 

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2831]
cromwell 30 will need this back.  See `WdlFunctions` in the code.

Then reinstate centaur tests:
- [x] `globbingscatter`
- [ ] `globbingindex`
- [x] `space`
- [x] `globbingBehavior`
- [x] `dontglobinputs`
- [x] `lots_of_inputs`

**Comment by geoffjentry** [comment]
Make sure that this gets pointed out at standup tomorrow
