### ISSUE TITLE
WDL tasks that specify an output directory of "." (sometimes indirectly) will cause failures in downstream tasks.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2844]
- JES/PAPI backend
- Cromwell v29

I have a task that dropped its outputs into "./", since output directory was a parameter and that is how it was set.  So when cromwell/PAPI saw an output file `...././my_output.txt`, they created a bucket that actually contains the "." ... 

The task was allowed to complete successfully and then downstream tasks failed.

Proposed solutions:
- check the output location either when the first/upstream task completes (or, if possible, before it starts).
- Simple prune the ./ from the output path.

```
java.lang.IllegalArgumentException: I/O not allowed on dot-dirs or extra slashes when !permitEmptyPathComponents: /lichtens/cromwell-executions-test-dl-oxoq-full/CNVValidation/25df0c1d-5a13
-4bc1-8712-0cf90a78dfda/call-cnvPair/CNVSomaticPairWorkflow/6fe3dc67-c5f0-4c61-8881-474ceac4c8d7/call-ModelSegmentsTumor/./G25783.TCGA-55-6986-01A-11D-1945-08.2.modelFinal.seg
```

**Comment by LeeTL1220** [comment]
And (for obvious reasons) this does not error out on SGE and local backends.

**Comment by aednichols** [comment]
Appears fixed in https://github.com/broadinstitute/cromwell/pull/2512 and has a regression test, closing.
