### ISSUE TITLE
File issue cause cromwell to enter funny state where workflow status is running, but it has stalled indefinitely.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2845]
- JES Backend
- v29

See #2844 

This error causes cromwell to enter a funny state when the error described in #2844 occurs in a subworkflow.  Cromwell states that the workflow (and subworkflow) are running, though the server log shows the exception.  Not only that, the backend status is `Success` for the task that generated the invalid filename, though the task status remains `Running`, just like the workflows.  Without looking at the server logs, a user cannot determine what is going on, easily.

**Comment by LeeTL1220** [comment]
And I can't seem to abort the workflow.

**Comment by LeeTL1220** [comment]
Another way to make this happen....

This also happens when a task writes an output path with an extra `/` ...
For example the task output:
```
String output_dir = "output/"
....snip....
output {
  File foo = "${output_dir}/foo.txt"
}
```
The above will cause a stall, since GCS will write a directory called "/" and then cromwell will never know that it is done.

In other words:
GCS:  `call-MyTask` `output` `/` `foo.txt`
Cromwell wants:  `call-MyTask` `output` `foo.txt`

**Comment by katevoss** [comment]
Regarding aborts, @Horneth made significant changes to aborts in Cromwell 30 (coming soon!) that should make it easier and more reliable to abort jobs.

**Comment by LeeTL1220** [comment]
Aborts were working fine for me (in this case).  I still had to identify that the job had stalled, manually.

**Comment by LeeTL1220** [comment]
@katevoss Sounds good.  Generally, abort has worked for me.  Just not in this case.

**Comment by gemmalam** [comment]
AC: Add a centaur test for this.

**Comment by aednichols** [comment]
Based on the presence of a centaur test named `dot_dir_stuck_running` associated with a [PR that fixed this issue](https://github.com/broadinstitute/cromwell/pull/2512), closing.
