### ISSUE TITLE
Wom: Reinstate write_lines in JES

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2864]
Reinstate centaur tests:
- [x] `write_lines`
- [ ] `fofn_caching`
- [x] `array_io`
- [x] `write_lines_files`

**Comment by mcovarr** [comment]
[Oh my](https://github.com/broadinstitute/cromwell/blob/05c8dfdc914c40ef6b5443cad0361073e6b837f0/supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala#L162)

**Comment by cjllanwarne** [comment]
Closing because `fofn_caching` is being fixed in #2922
