### ISSUE TITLE
WdlNamespace should have an API to create a namespace without actual inputs

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2867]
@mcovarr commented on [Tue Nov 14 2017](https://github.com/broadinstitute/wdltool/issues/51)

This is for the benefit of womtool which is going to have to resort to forging inputs as a [stopgap measure](https://github.com/broadinstitute/cromwell/pull/2857). WdlNamespace should continue to make the current API available for production code.

**Comment by cjllanwarne** [comment]
Closing this, the draft 2 language factory is able to create a `WomBundle` without inputs.
