### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2872]
@vdauwera commented on [Sun Jan 08 2017](https://github.com/broadinstitute/wdltool/issues/20)

I had a few issues that were fixed by building the latest from source. There's a good chance that will also be the case for the other issues that have been reported. Would be good to cut a release to make it available without requiring people to build from source. 

---

@knoblett commented on [Mon Feb 20 2017](https://github.com/broadinstitute/wdltool/issues/20#issuecomment-281030248)

Are we responsible for building a new release now that we own this repo? Or am I misremembering?

---

@ruchim commented on [Mon Feb 20 2017](https://github.com/broadinstitute/wdltool/issues/20#issuecomment-281054777)

The wdltool release is a part of the Cromwell release process 

---

@knoblett commented on [Mon Feb 20 2017](https://github.com/broadinstitute/wdltool/issues/20#issuecomment-281096658)

Ah, thank you, that makes sense. @vdauwera do we still need a release? The most recent release was done 3 days prior to the creation of this ticket.

---

@vdauwera commented on [Mon Feb 20 2017](https://github.com/broadinstitute/wdltool/issues/20#issuecomment-281097178)

Does the release process include making a packaged jar? I think my problem was that there wasn't a jar that corresponded to the latest releases version available for download, come to think of it.

**Comment by mcovarr** [comment]
We have a dazzling new "monorepo" setup and release process which builds and publishes a version of womtool matched to the currently released version of Cromwell. Though we may have some more work to do here since:

* womtool won't actually report [its version](https://github.com/broadinstitute/cromwell/issues/2868)
* We publish jfrog "executable" artifacts for cromwell, womtool, and centaur-cwl-runner, but only the cromwell artifact is published to Github.

**Comment by cjllanwarne** [comment]
Closing this, we've released at least once since Nov '17
