### ISSUE TITLE
wdltool 0.10 validates too generously

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2873]
@ruchim commented on [Wed May 24 2017](https://github.com/broadinstitute/wdltool/issues/29)

Given a task:

task myTask {
  File f
  command {
     touch ${f.bam.bai}
  }
}

A workflow with such a task validates in wdltool-0.10 but when run on cromwell-26, it fails with an error: java.lang.UnsupportedOperationException: Could not evaluate expression:....

Given a slightly altered version of that previous task:

task myTask {
  File f
  command {
     touch ${f%%.bam.bai}
  }
}

This task also validates but fails before the Workflow is about to run with the error: scala.MatchError: null

---

@geoffjentry commented on [Wed May 24 2017](https://github.com/broadinstitute/wdltool/issues/29#issuecomment-303819742)

Is this an artifact of wdltool being out of synch? it happens way too often :(

**Comment by mcovarr** [comment]
Sync problems are a thing of the past in the monorepo world so it should be easy enough to test Jeff's hypothesis.

**Comment by aednichols** [comment]
A current version of Womtool validates these tasks as OK.

Upgrading the tasks to WDL 1.0 causes Womtool validation to fail with messages of varying helpfulness:

```
version 1.0

task myTask {

  input {
    File f
  }

  command {
    touch ${f.bam.bai}
  }
}
```
```
Failed to process task definition 'myTask' (reason 1 of 1):
  Failed to process expression 'f.bam.bai' (reason 1 of 1):
    No such field 'bam' on type File
```
---
```
version 1.0

task myTask {

  input {
    File f
  }

  command {
    touch ${f%%.bam.bai}
  }
}
```
```
Failed to read task definition at line 3 column 6 (reason 1 of 2):
  Failed to convert AST node to ExpressionElement (reason 1 of 2):
    No attribute 'rhs' found on Ast 'Remainder'. Did you mean: lhs
Failed to read task definition at line 3 column 6 (reason 2 of 2):
  Failed to convert AST node to ExpressionElement (reason 2 of 2):
    No attribute 'value' found on Ast 'MemberAccess'. Did you mean: member
```

**Comment by geoffjentry** [comment]
I'm going to close this. can reopen if it winds up being A Thing
