### ISSUE TITLE
issue with wdltool 0.4?

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2876]
@eddiebroad commented on [Wed Aug 10 2016](https://github.com/broadinstitute/wdltool/issues/12)

I try to use wdltool validate on a WDL and it seems to _not_ catch
an error in the WDL.

In the example "bad" WDL attached the call to VCF_to_MAF_task
has the line "inputVCF=inputVCF" but the "inputVCF" exists only
in the task but not at the workflow level 
but invoking wdltool 0.4 on it seems to _NOT_
cause an error.  Shouldn't it be saying the WDL has an error
because inputVCF does _not_ exist at the workflow level?

I downloaded the wdltool from the latest release
https://github.com/broadinstitute/wdltool/releases/download/0.4/wdltool-0.4.jar

the two WDLs are attached.  [wdl_files.zip](https://github.com/broadinstitute/wdltool/files/412067/wdl_files.zip)

```
wm8b1-75c:red_bug esalinas$ find *.wdl -exec java -jar wdltool-0.4.jar validate  {} \;


wm8b1-75c:red_bug esalinas$ diff  good.wdl  bad.wdl 
188c188
<           inputVCF=inVCF,

---
>           inputVCF=inputVCF,
wm8b1-75c:red_bug esalinas$ 
```

**Comment by geoffjentry** [comment]
Closing as it refers to an outdated version of the tool. If this still exists on a modern womtool, please open a new ticket
