### ISSUE TITLE
Wom: Reinstate invalidate bad caches local

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2905]
This might be related to centaur configuration, which IIRC requires specific, non-default, options for this test. NB fails on both `centaurLocal` and `centaurTest`

Once fixed, reinstate centaur test:
- [x] `invalidate_bad_caches_local`

**Comment by kshakir** [comment]
Close this ticket once the test has been turned back on and verified. PR #2952 should fix this test as well.

**Comment by cjllanwarne** [comment]
Fixed in #2956
