### ISSUE TITLE
Defining variables declared in a task level where the task has multiple aliases.

### ISSUE THREAD

**Issue by leepc12** [broadinstitute/cromwell#2914]
Task `t` is called three times with different aliases. Is there any way to share the same string variable `a` for `t`, `t1` and `t2`?
```
workflow test {
    call t {}
    call t as t1 {}
    call t as t2 {}
}

task t {
    String? a
    command { ... }
}
```
What I expected...
```
input.json
{
    "test.t.a" : "hello world"
}
```
But I had to use...
```
input.json
{
    "test.t.a" : "hello world"
    "test.t1.a" : "hello world"
    "test.t2.a" : "hello world"
}
```
I am developing a pipeline and it has 9 aliases for the same task. I actually don't want to define the same variable 9 times in `input.json`.

**Comment by geoffjentry** [comment]
Hi @leepc12 - this has been [brought up before](https://github.com/broadinstitute/cromwell/issues/1335). I'll close this as a duplicate.

Note that WDL spec is no longer directly controlled by the Cromwell team, if you want a change for something like this you'll need to bring it up with the [OpenWDL group](http://openwdl.org/#two).
