### ISSUE TITLE
an option to copy ONLY file-results

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2915]
The configuration option "final_workflow_outputs_dir" is misleading. 
What many users commonly want to do is just to copy final results to the folder in case if the workflow succeded. Right now this option copies standard nested-trash like "MyWorkflow/bc5f9f3e-0daf-4ee3-b0c2-35971af26772/call-hello/execution" Although this nested structure is useful for the debugging, it is not what we expect as a final result. 
I suggest giving an option for a folder where _only_ final files will be copied without any nested folders and debugging files/logs/whatsoever.

**Comment by geoffjentry** [comment]
This seems like a duplicate of [1641](https://github.com/broadinstitute/cromwell/issues/1641)

**Comment by antonkulaga** [comment]
Looks like a duplicate, move the discussion there
