### ISSUE TITLE
s"/workflows/${version}/${id}/logs" should always have calls field

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2917]
When I run logs API on workflow that failed before execution (for instance, when wdl file was damaged) and query for its logs I do not see "calls" field. I think it will be good just to give empty 
```
"calls": {}
```
field instead of omitting it at all.

**Comment by ruchim** [comment]
@antonkulaga We don't get a lot of usage of the /logs endpoint and considering removing it, so feel free to re-open with use cases for this endpoint.
