### ISSUE TITLE
Colon ':' in output filename causes workflow failure

### ISSUE THREAD

**Issue by MatthewMah** [broadinstitute/cromwell#2919]
In Cromwell 29, having a ':' character present in the filename of a non-glob task output results in a workflow failure. It does not matter whether this is hard-coded or simply in the filename. 

`WorkflowManagerActor Workflow 1356670a-cea2-45b7-a9c4-e379dc601f9f failed (during ExecutingWorkflowState): Could not evaluate A.out = "A:out"
java.lang.RuntimeException: Could not evaluate A.out = "A:out"`

This is reproducible with the following wdl:
```
workflow colon_filename{
	call A {}
}

task A{
	command{
		echo "testing" > A:out
	}
	output{
		File out = "A:out"
	}
}

```
Task A completes normally with return code 0 and creates the file A:out. 

I expected this workflow to complete normally without error. 

Workaround
-
I have an acceptable workaround where I simply replace all ':' characters with '-'.

**Comment by ruchim** [comment]
@kshakir do you know if ":" characters are allowed by how we parse filenames?

**Comment by ruchim** [comment]
https://broadworkbench.atlassian.net/browse/BA-2919
All future updates to this issue will be posted in JIRA. Sorry for the inconvenience, but you will need to create a free account to access it.
