### ISSUE TITLE
Fix fofn_caching test

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2922]
#2864 fixes may be a prereq. [This](https://github.com/broadinstitute/cromwell/blob/develop/engine/src/main/scala/cromwell/engine/WdlFunctions.scala#L18) appears to be the trouble spot. Please talk to @kshakir before taking this ticket as he already began looking into it.

**Comment by mcovarr** [comment]
Per @kshakir's research, it's believed that the underlying issue is the use of `write_lines` in the `input` section to the call [here](https://github.com/broadinstitute/cromwell/blob/develop/centaur/src/main/resources/standardTestCases/fofn_caching/fofn_caching.wdl#L35). The statement about fixes for #2864 being a prereq remains true, and so far those fixes are still on my mlc_fix_jes_write_lines branch and not on develop.

**Comment by cjllanwarne** [comment]
Looks to have been fixed by #2960
