### ISSUE TITLE
Validate docker attribute as part of WDL validation

### ISSUE THREAD

**Issue by andy7i** [broadinstitute/cromwell#2932]
I encountered this error when running a WDL:
```message: Runtime validation failed
causedBy: 
message: Task hello has an invalid runtime attribute docker = !! NOT FOUND !!
```

I understand that it requires a docker attribute. The issue is that the error gets found at runtime. This should be caught when validating the WDL. 

The risk is that users could "run half their tasks and only find out mid-workflow that one needs an extra parameter" (ChrisL's words).

**Comment by geoffjentry** [comment]
How would the validation know what backend the task is going to be run on and if that backend requires docker?

Which is not to say that it can't happen sooner, but I don't think it can work like you're picturing.

**Comment by geoffjentry** [comment]
Closing this issue. If given enough user hue and  cry we will reopen
