### ISSUE TITLE
some tasks have "Running" executions status when workflow already failed

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2934]
What is very confusing is that some tasks have "Running" executions status when workflow already failed. I think if the workflow failed they should be marked as "Terminated" or something similar.

**Comment by geoffjentry** [comment]
Are you talking about tasks which will never leave the `Running` state? If so this was recently resolved in `develop`. If not, can you re-open and explain more?

**Comment by antonkulaga** [comment]
> which will never leave the Running state? If so this was recently resolved in develop

Yes, it is great that it is fixed now. BTW, when do you plan to make a next release?

**Comment by geoffjentry** [comment]
We'll be releasing v30 within the next few weeks
