### ISSUE TITLE
Return all labels when using the PATCH labels endpoint

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2953]
currently it just returns the updated ones.

this is needed for job manager

https://www.youtube.com/watch?v=1Isjgc0oX0s

**Comment by rexwangcc** [comment]
Thanks for making this ticket @geoffjentry !

**Comment by kbergin** [comment]
@geoffjentry can this be included when #3233 happens?

**Comment by geoffjentry** [comment]
@kbergin They're not quite as coupled as you might think but i'll add it to that milestone we discussed yesterday
