### ISSUE TITLE
if a job is aborted before it is started, cancel it efficiently

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/cromwell#2966]
My jobs aren't starting because there's a giant queue of jobs that have been cancelled, but are waiting to start before they can be aborted.  This shouldn't happen. If a job is aborted before it can be launched it shouldn't take a long time to process it.  

I heard this might be fixed in 30 already, but if it's not, it would be great to have it fixed.

**Comment by Horneth** [comment]
This is indeed fixed in 30

**Comment by mcovarr** [comment]
30 has been released.
