### ISSUE TITLE
Add new retryable case: JES error code 2.  Message: Instance failed to start due to preemption.

### ISSUE THREAD

**Issue by dianekaplan** [broadinstitute/cromwell#2970]
There’s a new response from JES that should be retryable: 
JES error code 2.  Message: Instance failed to start due to preemption.” 

THE CATCH: Henry chatted with Google, and it sounds like JES error code 2 isn’t *always* about preemption. (But in the past few weeks we’ve had a handful of cloud workflows failing each day from this response, always with the message about preemption). So to be safe, we want to make this one retryable based on the combination of the code + the message. 

Example: 
UUID: 7da0394b-371f-4fdb-ae70-737833c4fbfa
OPERATION_ID: operations/EKmIx96ALBjh373VhLH0ui8gkYad9-AKKg9wcm9kdWN0aW9uUXVldWU

Relevant workflow metadata: 
"failures"
: [
{
"causedBy": [],
"message": "Task PairedEndSingleSampleWorkflow.CollectUnsortedReadgroupBamQualityMetrics:2:1 failed. JES error code 2.  Message: Instance failed to start due to preemption."
}
],

**Comment by cjllanwarne** [comment]
@dianekaplan could you run `gcloud alpha genomics operations describe operations/EKmIx96ALBjh373VhLH0ui8gkYad9-AKKg9wcm9kdWN0aW9uUXVldWU` and add in anything that looks like an error message or error code?
