### ISSUE TITLE
Archive old repositories

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2980]
During the 30 release, the previous code repositories should be archived.

For each repository:
- Create a new commit on the default branch linking future visitors to cromwell
- Ensure all PRs and Issues are closed/migrated as they will be read-only for all users after archiving
- [Archive](https://help.github.com/articles/archiving-a-github-repository/) the repository making it read-only

Old repositories:
- https://github.com/broadinstitute/lenthall
- https://github.com/broadinstitute/wdl4s
- https://github.com/broadinstitute/wdltool
- https://github.com/broadinstitute/centaur

**Comment by geoffjentry** [comment]
These are now all archived. Even if the rest of the stuff isn't done, it's been quite some time now
