### ISSUE TITLE
CWL Feature: InlineJavascriptRequirement

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2995]
Link to specs:
- http://www.commonwl.org/v1.0/CommandLineTool.html#InlineJavascriptRequirement
- http://www.commonwl.org/v1.0/Workflow.html#InlineJavascriptRequirement

Example conformance tests:
- <span>#</span>16 [v1.0/null-expression1-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/null-expression1-tool.cwl)
- <span>#</span>17 [v1.0/null-expression2-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/null-expression2-tool.cwl)
- <span>#</span>52 [v1.0/wc4-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/wc4-tool.cwl) (Parses file contents in JS)

A/C: These or similar CWL should run to `WorkflowSucceeded` via centaur
Bonus: CWL conformance test passes (may also be a future ticket)

**Comment by danbills** [comment]
We plan to support only the `expressionLib` declaratoin with this requirement.

#3058 is created to support the stipulation that expressions should _not_ be evaluated if this requirement is missing
