### ISSUE TITLE
CWL Feature: Directory type

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3004]
Link to specs:
- http://www.commonwl.org/v1.0/CommandLineTool.html#Directory
- http://www.commonwl.org/v1.0/Workflow.html#Directory

Example conformance test(s):

- <span>#</span>78 [v1.0/dir3.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/dir3.cwl)
- <span>#</span>85 [v1.0/dir6.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/dir6.cwl)
- <span>#</span>93 [v1.0/dir7.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/dir7.cwl)
- <span>#</span>99 [v1.0/recursive-input-directory.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/recursive-input-directory.cwl)

A/C: These or similar CWL should run to `WorkflowSucceeded` via centaur
Bonus: CWL conformance test passes (may also be a future ticket)

**Comment by kshakir** [comment]
A directory without sub-directories _should_ work, but nested directories won't work in PAPI until #3173.
