### ISSUE TITLE
CWL Feature: Secondary Files

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3009]

**Comment by kshakir** [comment]
Until #3173 is fixed, globbed paths will be adjusted before they are delocalized. This breaks secondary file resolution, as each glob ends up in a different cromwell-generated-directory.

Example-- workflow declares an output as:
```
File: out/*.bam
Secondary: ^.bai
```

workflow outputs:
```
out/sample.bam
out/sample.bai
```

Via the linked issue, cromwell delocalizes the files matched to `*.bam` and `*.bai` to (something like) "cromwell-glob-1" _and_ "cromwell-glob-2":
```
out/cromwell-glob-1/sample.bam
out/cromwell-glob-2/sample.bai
```

The secondary file resolution code doesn't realize that the `bai` is no longer in the same directory as the `bam`. The secondary file resolver is looking for both files under "cromwell-glob-1":

```
out/cromwell-glob-1/sample.bam
out/cromwell-glob-1/sample.bai
```

Easiest solution: don't change the glob paths like this.
