### ISSUE TITLE
Build WOMTool Jar with Cromwell release and update docs

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#3031]
Our WOMTool (previously WDLTool) has moved into the mega-mono-repo of Cromwell, but there's no way for Jamie User (like me) to find the latest of the WOMTool. 

AC
- [x] have the WOMTool jar on the [Cromwell releases page](https://github.com/broadinstitute/cromwell/releases)
- [x] update the [WOMtool docs](https://cromwell.readthedocs.io/en/develop/WOMtool/) to point to the releases page for the latest tool

**Comment by kshakir** [comment]
While this ticket is being resolved for the womtool-on-the-releases-page, for docker users the latest WOMTool is available @ https://hub.docker.com/r/broadinstitute/womtool/tags/

**Comment by katevoss** [comment]
I already did this as a part of #3095, closing as completed.
