### ISSUE TITLE
Cromwell CWL: JobStore and restarts

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3035]
Seemingly the cause of many of my centaur woes: if any CWL test happens to be caught up in a restart, the JobStore lookup fails and so does the workflow

**Comment by mcovarr** [comment]
I believe @Horneth put in a short term fix for this by excluding CWL tests from the set of restart tests, but presumably we'll want restart support for our CWL workflows at some point.

**Comment by geoffjentry** [comment]
It'd be nice :)

**Comment by mcovarr** [comment]
It would. But should it be AlphaCWL?

**Comment by geoffjentry** [comment]
Yes, I'd expect Cromwell works the same regardless of what the input format is

**Comment by mcovarr** [comment]
see also #3012

**Comment by ruchim** [comment]
Closed by https://github.com/broadinstitute/cromwell/pull/3470
