### ISSUE TITLE
Optional parameter not being honored in cromwell 30

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#3038]
- cromwell 30
- JES backend

 ** This WDL worked just fine in cromwell 28.2 **

I have a workflow calling a sub-workflow.  The parent workflow has an optional parameter.  Cromwell is refusing to run the workflow stating that the optional parameter has no value.  Even though the task has a `{$default= ....` statement.  The optional parameter is given by the input json and does not interact with the subworkflow at all.

The only difference was that I upgraded cromwell.

**Comment by LeeTL1220** [comment]
Contact me if you want the example WDL.

**Comment by cjllanwarne** [comment]
Wing me the WDL and I'll have a look at it (and for your other ticket too).

**Comment by LeeTL1220** [comment]
For this one, I basically just worked around it.  The other one is still an issue.

I'll send it to you with the workaround in place.  We can discuss rolling back the workaround when issue #3039 is sorted.  I'm hoping that is a typo.

**Comment by geoffjentry** [comment]
This is fairly old, #3039 has been closed, and we're assuming this has been resolved. if this can be replicated on a modern version of Cromwell we can reopen
