### ISSUE TITLE
caching is totally wrong (false positive) for many tasks

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#3044]
I recently got into a trouble because of wrong caching in cromwell. In most of my pipelines I copy the results of last tasks to some folder which I define in the variable (unfortunately the option.json feature of cromwell to kind'of "copy workflow results" is useless for us as it copies all the nested trash, like "id/execution" instead of just resulting files). 
Unfortunately, my task that does the copying was cached even if the task on which it depends had different inputs (and was not cached). That means that we have a false positive caching and the copying task copies the same file from cache all over again.
Here is an example of my WDL. However, it fails in all WDLs where I use the copy-task for results
```wdl
workflow Diamond_Blast {

  Int threads
  File db
  File query
  String result_name
  String results_folder
  String mode = "blastx"

  call diamond_blast {
      input:
        threads = threads,
        database = db,
        name = result_name,
        query = query,
        mode = mode

    }

  call copy as copy_results {
    input:
        files = [diamond_blast.out],
        destination = results_folder
  }

  output {
       File out = copy_results.out[0]
  }

}

task diamond_blast {

  Int threads
  File database
  File query
  String name
  String mode

    command {
        diamond ${mode} -d ${database}  -q ${query} \
          --more-sensitive -o ${name}.m8 \
          -f 6 sseqid qseq score pident stitle qcovhsp qtitle \
     }

  runtime {
    docker: "quay.io/comp-bio-aging/diamond:latest"
  }

  output {
       File out = name + ".m8"
  }

}


task copy {
    Array[File] files
    String destination

    command {
        mkdir -p ${destination}
        cp -L -R -u ${sep=' ' files} ${destination}
    }

    output {
        Array[File] out = files
    }
}
```
and here is an example of the input:
```json

Diamond_Blast.mode = "blastp"
Diamond_Blast.query = "/pipelines/indexes/GRAY_WHALE/NTJE01P.1.fasta"
Diamond_Blast.threads = 8
Diamond_Blast.result_name = "graywhale_in_minkywhale_blastp"
Diamond_Blast.db = "/pipelines/indexes/diamond/MINKY_WHALE_GCF_000493695.1.dmnd"
Diamond_Blast.results_folder = "/pipelines/results/graywhale/transcriptome/diamond/blastp"
```
when I run the workflow many times with input changes I get the following:
```

name | status | stdout | stderr | cache | shard
-- | -- | -- | -- | -- | --
Diamond_Blast.copy_results | Done | /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/da1376f4-6f31-403f-941d-e8c36483897e/call-copy_results/execution/stdout | /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/da1376f4-6f31-403f-941d-e8c36483897e/call-copy_results/execution/stderr | Cache Hit: fdda40c0-a501-456c-a903-954aa52af83d:Diamond_Blast.copy_results:-1 | -1
Diamond_Blast.diamond_blast | Done | /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/da1376f4-6f31-403f-941d-e8c36483897e/call-diamond_blast/execution/stdout | /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/da1376f4-6f31-403f-941d-e8c36483897e/call-diamond_blast/execution/stderr | Cache Miss | -1
```
that shows that the task diamond_blast recomputes while the copy task copies the cached result, in other words it sends the same file as previous time, totally ignoring the changes of output in the diamond_blast task from which it depends!!!

**Comment by geoffjentry** [comment]
Please add your version

**Comment by antonkulaga** [comment]
Cromwell 30, stable, Oracle Java 8, latest Linux Mint (and also Ubuntu 16.04 on server)

**Comment by Horneth** [comment]
Could you post the full workflow metadata for 2 of those runs with the false positive please ?

**Comment by antonkulaga** [comment]
@Horneth here is my metadata. I enclose first run from which the cache was created. There I made a mistake in input and gave graywhale_in_human_blastp output name for the cow data. In two runs that followed I tried to fix this mistake by giving graywhale_in_cow_blastp instead, but it cached the copy task from the first run, so nothing changed.
[metadata_false_positive.zip](https://github.com/broadinstitute/cromwell/files/1551960/metadata_false_positive.zip)

**Comment by Horneth** [comment]
@antonkulaga It appears that changing the `name` only changes the filename of the output produced by your task, but not the actual processing. So I bet if you look at the files produced by the diamond blast task for all 3 workflows you'll see that even though their names differ they have the same content.
Cromwell by default only cares about the content of a file with respect to call caching and its name is ignored. In this case it likely md5ed the files and found they had the same hash so the copy task was cached.
I'll wait for you to confirm that the output files have indeed the same hash before closing this:

```
md5 /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/ab101af5-26ba-45c8-b592-fb37e06a523d/call-diamond_blast/execution/graywhale_in_human_blastp.m8
md5 /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/3d75657d-7dc9-4b6f-bbc8-ae579a3fa773/call-diamond_blast/execution/graywhale_in_cow_blastp.m8
md5 /pipelines/cromwell_1/cromwell-executions/Diamond_Blast/276d6f9e-15b1-4dc3-a8a7-889414406511/call-diamond_blast/execution/graywhale_in_cow_blastp.m8
```

should all produce the same hash

**Comment by antonkulaga** [comment]
@Horneth could you add a cache configuration option that will switch on caring about the filenames when caching?
Non-chaching of filenames can get many users in a really big trouble and sometimes screw whole research or medical diagnosis. If I did not discover that the files were not written because of caching my colleagues would have treated cow data as if it was human.

**Comment by geoffjentry** [comment]
Yeah this seems like a case of being too clever for our own good

**Comment by Horneth** [comment]
https://github.com/broadinstitute/cromwell/issues/3054

**Comment by antonkulaga** [comment]
@Horneth as you created #3054 I close this issue
