### ISSUE TITLE
WOMtool should specify what WDL (or subWDL) has the error

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#3055]
I validated `cnv_param_sweep.wdl` and received this error:
```
ERROR: Missing value or call: Couldn't find value or call with name 'CollectAllelicCountsNormal' in workflow (line 136):

    Int model_segments_disk = ceil(size(DenoiseReadCountsTumor.denoised_copy_ratios, "GB")) + ceil(size(CollectAllelicCountsTumor.allelic_counts, "GB")) + ceil(size(CollectAllelicCountsNormal.allelic_counts, "GB")) + disk_pad
```
`cnv_param_sweep.wdl` imports 3 WDLs, and the error was actually in `cnv_somatic_pair_workflow.wdl`. It would be great to know what WDL the error is in, especially if it's not the primary WDL.

**Comment by cjllanwarne** [comment]
Good news - I have a fix for this incoming in WDL 1.0 soon!
