### ISSUE TITLE
Support CWL InlineJavascriptRequirement stipulation to not evaluate JS when requirement is missing.

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3058]
an edgy edge case

**Comment by whlavina** [comment]
This issue was closed, apparently without any change or fix. Just to confirm, does this mean Cromwell won't honor this edge case of the specification, intentionally? A cost/benefit justification is fine.

**Comment by geoffjentry** [comment]
We bulk closed these sorts of issues as they represented todos during development and in many cases were long since complete. Further we had transitioned to a model where we’ll react to bug reports vs a development todo list.

If this isn’t working for you feel free to reopen the issue
