### ISSUE TITLE
Cannot specify multiple input files in Cromwell v30

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#3061]
In previous versions of Cromwell, it was possible to specify multiple input files when submitting a workflow but in v30 it is only possible to upload one inputs file:

<img width="1398" alt="screen shot 2017-12-13 at 6 39 37 pm" src="https://user-images.githubusercontent.com/6414394/33968251-164348f0-e035-11e7-9591-72d3b22f2cad.png">

**Comment by geoffjentry** [comment]
Is this just in swagger, via he endpoint, or both?

**Comment by samanehsan** [comment]
I just noticed it through the swagger UI but haven't tried the endpoint directly

**Comment by geoffjentry** [comment]
Ok. If this is blocking you try the endpoint. We also changed the swagger yaml so it’s entirely possible it’s just a swagger artifact

**Comment by cjllanwarne** [comment]
@samanehsan just to check, are you trying to submit a single workflow or a batch? And are you then trying to supply multiple input files or just a list of inputs objects?

**Comment by cjllanwarne** [comment]
(because the image you posted is for the batch submit, which doesn't sound like the one you want)

**Comment by samanehsan** [comment]
Oh wow! I was trying to submit multiple input files into a single workflow. Thanks for pointing that out @cjllanwarne! :octocat:
