### ISSUE TITLE
/query response to provide total page count

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3083]
It would be helpful if the /query endpoint included total page count when requesting paginated results.

**Use case:**
Currently, the response of `/query` endpoint returns workflows from oldest to newest. The requirements for the Job Manager are such that they require information about newest workflows first. One way that the Job Manager can access newest workflows first is they could paginate through the results in reverse order, which is possible if they have access to the total page count. 

The other solution for this use case is if there was an option to provide a sort param and sort direction for the query endpoint. A separate [issue] (https://github.com/broadinstitute/cromwell/issues/3082) has been filed for that.

**Comment by ruchim** [comment]
Turns out that the query response header includes a link to the last page of paginated query results, addressed by an older PR: https://github.com/broadinstitute/cromwell/pull/830. @dshiga  has mentioned they would prefer to have the a total query result count instead of total page count in the response body. Dave -- is this still a requirement for Mint, or can the ticket be closed?

**Comment by dshiga** [comment]
Yes, we'd still like to be able to get the total results count in the json response, which is a little more convenient and gives us a little more info than a total page count. Thanks for putting that in the 30 hotfix https://github.com/broadinstitute/cromwell/pull/3145. We would definitely like to continue to have that functionality in future versions of Cromwell.

**Comment by ruchim** [comment]
@dshiga Since the query endpoint now returns the count of total results, can this issue be closed?

**Comment by dshiga** [comment]
Thanks @ruchim, the total results count gives us what we need, so this can be closed.
