### ISSUE TITLE
Detritus in execution directory

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3092]
The CWL conformance tests have a new addition that is globbing everything in the current directory and expecting files based on what the command produced. It fails because in addition to those files Cromwell also has the script file, rc file etc...

**Comment by geoffjentry** [comment]
@Horneth I did see them talking about adding it in gitter, it was to provide a test for a bug which was found in toil. we should probably ask what the bug was and see if perhaps we're failing it for the same reason or if this was just an unfortunate side effect.

**Comment by mr-c** [comment]
Huh, I thought we were explicit about the execution directory being empty in http://www.commonwl.org/v1.0/CommandLineTool.html#Runtime_environment 

I've made an issue on our end to document this assumption: https://github.com/common-workflow-language/common-workflow-language/issues/579

`OutputBinding: { glob: * }` is fairly common in CWL

**Comment by ruchim** [comment]
@mcovarr did this work get completed? If yes, would you mind closing the issue? if no, any idea on where this last stands? Thanks!

**Comment by mcovarr** [comment]
No this is not completed.
