### ISSUE TITLE
localization and duplication-strategy do not work.

### ISSUE THREAD

**Issue by rhpvorderman** [broadinstitute/cromwell#3109]
Cromwell seems to love `hard-links`:
*  No matter what configuration I feed it, it will always tries `hard-links` first.
* When this fails. It does not try anything else.

Given the config file `test.config`
run with `java -Dconfig.file=test.config -jar cromwell-30.1.jar run -i inputs.json test.wdl` 
```HOCON
include required(classpath("application"))

backend {
  default="Local"
  providers {
    Local {
      config {
        filesystems {
          local {
            localization: [
              "soft-link", "copy", "hard-link"
            ]
            caching {
              duplication-strategy: [
                "soft-link", "copy", "hard-link"
              ]
            }
          }
        }
      }
    }
  }
}
```

## Expected behavior:
Crommwell will prefer to use `ln -s`. If that fails it will copy.

## Actual behavior:
Cromwell output:
```
ln: failed to create hard link '/home/ruben/IdeaProjects/construct-centrifuge-index/cromwell-executions/ConstructCentrifugeIndex/3e1afa55-3234-4fa9-b7e8-63d143846b9f/call-download/shard-0/execution/glob-0bd9f0edef72448a92c8f9e79babdc8d/GCF_000889155.1_ViralProj51245_genomic.fna' => '/tmp/test/centrifuge/data/libraries/53abeac3037f9afe08309700c99f725f/viral/GCF_000889155.1_ViralProj51245_genomic.fna': Invalid cross-device link
ln: failed to create hard link '/home/ruben/IdeaProjects/construct-centrifuge-index/cromwell-executions/ConstructCentrifugeIndex/3e1afa55-3234-4fa9-b7e8-63d143846b9f/call-download/shard-0/execution/glob-0bd9f0edef72448a92c8f9e79babdc8d/GCF_001343785.1_ViralMultiSegProj274766_genomic.fna' => '/tmp/test/centrifuge/data/libraries/53abeac3037f9afe08309700c99f725f/viral/GCF_001343785.1_ViralMultiSegProj274766_genomic.fna': Invalid cross-device link
```
It tries only `hard-links` if this fails. It just continues, not even trying soft links, failing to record my globbed files and crashing the pipeline down the line.

**Comment by Horneth** [comment]
Is your task using docker ? If you are `soft-link` is not tried as it doesn't play well with docker.
It should still try to `copy` though. Do you see any failed attempt to copy the files earlier in the log ?

**Comment by rhpvorderman** [comment]
My task are not using docker. Also I see no attempts at all to copy or softlink the files. Not in the log, and not in the cromwell-executions folder.
Also hard-linking seems to persist using the `SGE` backend. Even though the localization has the same configuration as above. This is very unfortunate as our cluster does not allow hard-linking.

Fortunately, all the other values in the config are used. Which makes me think that either my configuration file has some error (keys in wrong place). Or the backend just ignores the values due to a bug.

**Comment by rhpvorderman** [comment]
Managed to fix the problem. Cromwell 32 errorred and explained the problem. The filesystem section was moved to the SGE section. Are config file now looks like this:
```HOCON
backend {
  default="SGE"
  providers {
    SGE {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        concurrent-job-limit = 10000
        runtime-attributes= """
          Int? cpu=1
          Int? memory=4
        """
        submit = """
        qsub \
            -terse \
            -V \
            -b n \
            -wd ${cwd} \
            -N ${job_name} \
            ${'-pe BWA ' + cpu} \
            ${'-l h_vmem=' + memory + "G"} \
            -o ${out} \
            -e ${err} \
            ${script}
        """
        kill = "qdel ${job_id}"
        check-alive = "qstat -j ${job_id}"
        job-id-regex = "(\\d+)"

        filesystems {
          local {
            localization: [
              "soft-link", "copy", "hard-link"
            ]
            caching {
              duplication-strategy: [ "soft-link", "copy", "hard-link" ]
              hashing-strategy: "file"
            }
          }
        }
      }
    }
  }
}
```
