### ISSUE TITLE
Honor cwl.outputs.json file

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3110]
The CWL Spec [says](http://www.commonwl.org/v1.0/CommandLineTool.html#File) that if a file named `cwl.outputs.json` is present in the output directory of the task, the `outputBinding` should be ignored and this file should be used as the output of the task.
It's hard to tell how extensively this functionality is used by real CWL workflows but at least 1 conformance test makes use of it (#2).
Implementing this might be a bit challenging (especially in JES where we need to know in advance what to delocalize, maybe we'll have to use some sort of special glob ?..)

**Comment by Horneth** [comment]
Dupe of https://github.com/broadinstitute/cromwell/issues/2721

**Comment by geoffjentry** [comment]
Note that there's a typo in the spec, it's `cwl.output.json`
