### ISSUE TITLE
Command variable expansion masks bash variable interpretation with ${...}

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/cromwell#3111]
Bash and WDL have overlapping syntax for variable definitions:  `${VARNAME}` is valid in both.

This is a problem if you need to do variable manipulation in bash (e.g. get the length of a variable via `${#VARNAME}`).

Cromwell should support escaping this statement so that it can be passed through and interpreted in bash.

**Comment by geoffjentry** [comment]
@jonn-smith I mentioned it in another issue but this is another one which should be directed at OpenWDL. I'm tagging @cjllanwarne as he's the key Broad representation

**Comment by jonn-smith** [comment]
@geoffjentry - sounds good.  

@cjllanwarne - if there are no objections, I'll close this ticket and create the equivalent in OpenWDL.

**Comment by cjllanwarne** [comment]
@jonn-smith that sounds great! Thanks!

(if you have a concrete suggestion, you're also welcome to make it a PR against the (open, public) spec for community voting

**Comment by cjllanwarne** [comment]
@jonn-smith I've made a PR in openwdl that addresses this here: [Escaping the Almighty Dollar](https://github.com/openwdl/wdl/pull/184)

I'm going to close this one and once we sort things out on the WDL side, I'll open a new ticket in Cromwell to implement it here. 

Thanks!

**Comment by cjllanwarne** [comment]
PS @jonn-smith, please feel free to comment, suggest improvements, +1, etc the openwdl PR, since the more input we get there the more likely the change will address your requirements.

**Comment by odoublewen** [comment]
@cjllanwarne Just curious -- Is Cromwell likely to implement the spec changes you worked out in [openWDL #184](https://github.com/openwdl/wdl/pull/184) anytime soon?  I think this would be a really nice change. 
 Thank you.
