### ISSUE TITLE
Need a way to use Directories as input arguments to tasks/workflows

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/cromwell#3114]
There is currently no good way to specify a directory as an input argument to a task/workflow.  You must specify it as a string and do checks in the command block.

I suggest updating the `file` input keyword to work on directories as well.

**Comment by geoffjentry** [comment]
Hi @jonn-smith - just wanted to point out that the Cromwell team is no longer the controllers of the WDL specification. You want to check out [OpenWDL](http://openwdl.org/), in particular you should take a look at the [mailing list](https://groups.google.com/a/openwdl.org/forum/#!forum/community) and [github](https://github.com/openwdl/wdl)

**Comment by jonn-smith** [comment]
@geoffjentry - OK, cool.  I didn't realize that.  I'll move this to the appropriate place.

**Comment by jonn-smith** [comment]
Closing (moved to OpenWDL github issues).
