### ISSUE TITLE
Query endpoint `additionalQueryResultFields` parameter database error

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#3115]
On cromwell version 30.1, when making a request to the query endpoint that includes an `additionalQueryResultFields` parameter, the database will throw an error if the query matches ~1000 results. This seems to be because cromwell is querying the db to get that field's value for each workflow in the result set.

Example GET request:
"https://cromwell.mint-dev.broadinstitute.org/api/workflows/v1/query?additionalQueryResultFields=parentWorkflowId"

Error message: 
```{
  "status": "fail",
  "message": "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@349b84c3 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@37b87f04[Running, pool size = 200, active threads = 200, queued tasks = 1000, completed tasks = 3928972]"
}
```

This does not occur when paginating the results (as long as the page size is not 1000+)

**Comment by rexwangcc** [comment]
@ruchim Any updates on this issue? We are running this issue with CaaS/Cromwell again, unfortunately :(  The current workaround is, for a query of 1000 workflows, we send 1000 individual requests to the Cromwell, which could also put pressure to Cromwell.

**Comment by cjllanwarne** [comment]
Hey @rexwangcc when I was trying this recently I didn't get any problems. I was querying for a page size of 50 against a database of 250k workflows. 

I *did* have problems with `includeSubworkflow=false` but that seems like it would be unrelated to this?

**Comment by rexwangcc** [comment]
@cjllanwarne Thanks for looking into it! Our current use case is heavily relying on `"additionalQueryResultFields": ["labels"]`, with this error we have to loop through all workflows and make X thousands requests each time :( And I assume JMUI is relying on `"additionalQueryResultFields": "parentWorkflowId"`

**Comment by geoffjentry** [comment]
We believe this to be resolved as of C39
