### ISSUE TITLE
No error message when the input JSON has incorrect workflow names

### ISSUE THREAD

**Issue by MartonKN** [broadinstitute/cromwell#3120]
I gave Cromwell the following JSON when I had to specify the pair workflow:

{
  "CNVSomaticPairWorkflow.common_sites": "gs://broad-dsde-methods/mkanaszn/iota_small_exac_grch38.interval_list",
  "CNVSomaticPairWorkflow.gatk_docker": "samuelklee/gatk:sl_wgs_acnv_headers",
  "CNVSomaticPairWorkflow.intervals": "gs://shlee-dev/CNV/intervals/pad_parmY_int_agilent_1kg_exotars_logrch38.tsv",
  "CNVSomaticPairWorkflow.normal_bam": "gs://shlee-dev/hcc/hcc1143_N_clean.bam",
  "CNVSomaticPairWorkflow.normal_bam_idx": "gs://shlee-dev/hcc/hcc1143_N_clean.bai",
  "CNVSomaticPairWorkflow.read_count_pon": "gs://broad-dsde-methods/cromwell-execution-29/CNVSomaticPanelWorkflow/b36a6e5a-d31e-45e1-9935-b44b87690b6e/call-CreateReadCountPanelOfNormals/1kg_tutorial.pon.hdf5",
  "CNVSomaticPairWorkflow.ref_fasta_dict": "gs://shlee-dev/ref/GRCh38_1kg/GRCh38_full_analysis_set_plus_decoy_hla.dict",
  "CNVSomaticPairWorkflow.ref_fasta_fai": "gs://shlee-dev/ref/GRCh38_1kg/GRCh38_full_analysis_set_plus_decoy_hla.fa.fai",
  "CNVSomaticPairWorkflow.ref_fasta": "gs://shlee-dev/ref/GRCh38_1kg/GRCh38_full_analysis_set_plus_decoy_hla.fa",
  "CNVSomaticPairWorkflow.tumor_bam": "gs://shlee-dev/hcc/hcc1143_T_clean.bam",
  "CNVSomaticPairWorkflow.tumor_bam_idx": "gs://shlee-dev/hcc/hcc1143_T_clean.bai",
  "CNVSomaticPanelWorkflow.PreprocessIntervals.bin_length": "0",
  "CNVSomaticPanelWorkflow.PreprocessIntervals.padding": "250"
}

As you can see, I accidentally wrote "CNVSomaticPanelWorkflow" instead of "CNVSomaticPairWorkflow" in the last two entries. I didn't get an error for this, which might have been useful though.

This might be a duplicate issue but I didn't find another one related to this problem. Sorry if it is.

**Comment by cjllanwarne** [comment]
What version of Cromwell are you using? I believe this might be fixed in Cromwell 30.1

**Comment by MartonKN** [comment]
My Cromwell version is 29. This likely was the issue then, thank you.
