### ISSUE TITLE
ECMAscript "strict" mode interpretation

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3141]
The spec declares that ECMAscript should be evaluated using "strict mode". (http://www.commonwl.org/v1.0/Workflow.html#Expressions)

Conformance test of description "Test InitialWorkDirRequirement ExpressionEngineRequirement.engineConfig feature" (number 6 as of this writing) imports the library `underscore.js`, which in turn uses a `with` clause that is apparently forbidden in strict mode, at least according to the JDK Nashorn JS Engine.

Thus, in order to pass this conformance test, *strict mode is not enabled* currently (1/16/18).

So do we enable strict mode according to spec or do we do as people passing the conformance test do and not enable it?

**Comment by geoffjentry** [comment]
Perhaps this is a question to raise with them?

**Comment by danbills** [comment]
Submitted issue: https://github.com/common-workflow-language/common-workflow-language/issues/596
