### ISSUE TITLE
PAPI returning message 13 liberally

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#3157]
Here is the current situation from Google from https://partnerissuetracker.corp.google.com/issues/71697449:
> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #1 Jan 8, 2018 09:25AM 
> Reported Issue
> I don't have specific numbers at this time, but over the past several weeks our production operations staff started noticing an odd behavior that we originally thought was just normal preemption.    Normally we see preemption showing up as "Error code 10: Message 14:" - and cromwell takes care of re-submitting and following the logic coded in our WDLs.  Try pre-emptibles 3 times then try a non-preemptible instance.  
> 
> cromwell metadata output:
> 
>             "message": "Task PairedEndSingleSampleWorkflow.SamToFastqAndBwaMemAndMba:1:1 failed. JES error code 10. Task 417bb61c-16cc-4fda-91d5-443ccba4da11:SamToFastqAndBwaMemAndMba was preempted for the 1st time. The call will be restarted with another preemptible VM (max preemptible attempts number is 3). Error code Status{code=ABORTED, description=null, cause=null}. Message: 14: VM ggp-15030877962490231612 stopped unexpectedly."
> 
> However we have seen a new error response.  "Error code 10: Message 13"  metadata output showing:
> 
>       "message": "Task PairedEndSingleSampleWorkflow.HaplotypeCaller:46:3 failed. JES error code 10.  Message: 13: VM ggp-9289873678241352278 shut down unexpectedly."
> 
> From what Cromwell team indicates is that "Message 13" is not the same as Message 14 - as such a different logic occurs within cromwell.  Cromwell will try the task three times and after that it will just "Fail" the task.  So the "try 3 pre-emptible then try non-preemptible" logic is never followed.
> 
> So my question is what is "Message 13" and how is it different from "Message 14"?  Below are OpsIDs for a set of tasks - the first are the "Message 14"  (which again are normal preemption but I wanted to provide some for comparison to Message 13) and the second list are the "Message 13".   This is just a small sample of Message 13 failures.
> 
> MESSAGE 14:  
> operations/ENWy-aWLLBi89uiD6_uZzNABIMf5sPc2Kg9wcm9kdWN0aW9uUXVldWU
> operations/EMzb1NeLLBj0jsHwufD1gHogpfe0-ecHKg9wcm9kdWN0aW9uUXVldWU
> operations/EOn3vcOKLBibqZWQsay6xlUgpfe0-ecHKg9wcm9kdWN0aW9uUXVldWU
> operations/EK3Nx_aKLBjUn5bp5oqJz9oBIJGGnffgCioPcHJvZHVjdGlvblF1ZXVl
> operations/EIyjs-eKLBiUx5LdqLi-kh8gkYad9-AKKg9wcm9kdWN0aW9uUXVldWU

> MESSAGE 13:
> operations/EMCgv6aLLBifhsPH4fzAufMBIL3p_s7RASoPcHJvZHVjdGlvblF1ZXVl
> operations/EPOYsKiLLBib6JnQtvmKzPoBIL3p_s7RASoPcHJvZHVjdGlvblF1ZXVl
> operations/EL-QlNKLLBjeuPH9gd3Ck24gven-ztEBKg9wcm9kdWN0aW9uUXVldWU
> operations/EK6y-aWLLBjV36D2ueHGsKYBIMf5sPc2Kg9wcm9kdWN0aW9uUXVldWU
> operations/EMPd46GLLBj1iYrpkrCipPsBIKX3tPnnByoPcHJvZHVjdGlvblF1ZXVl
> operations/ENTd46GLLBiN8JPluoXAzFUgpfe0-ecHKg9wcm9kdWN0aW9uUXVldWU
> operations/EMPehaqLLBiS7p7OzdzYu5wBIKX3tPnnByoPcHJvZHVjdGlvblF1ZXVl

> ------------------------------- 
> kcibul@broadinstitute.org  <kcibul@broadinstitute.org>  #2 Jan 8, 2018 03:52PM 
> This is important to understand so Cromwell can do the right thing.  It 
> hasn't been clear in the past why we sometimes get 13s on these preemptible 
> jobs 
> 
> Kristian Cibulskis 
> Director of Platform Engineering, Data Sciences Platform 
> Broad Institute of MIT and Harvard 
> kcibul@broadinstitute.org 
> 
> 
> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #3 Jan 10, 2018 08:58AM 
> Not sure if you need any additional opsids - let me know if you do.  While I have not gathered specific statistics on the frequency of this happening - our operations staff reports that it is not unusual for this to happen up to dozen or so times a day where the "Message 13:" failures cause the entire workflow to fail and need to be re-submitted.  I would only assume that at a task level it is happening more often and as long as it does happen three times in succession for the same task - our ops team may not even notice it.  Since the retry covers it up.  
> 
> But it can cause considerable amount of delay on completing a sample.  The time spent to do the 3 retries but then the time it takes for a human to notice the failure and re-submit the entire thing again.  For "normal" preemption - we have codified things in our WDL such that when failures occur - it is usually something unusual.  With the higher occurrence of "Message 13" cause workflow failures - there is a new added step that needs to be looked at first.  Did the workflow fail due to "Message 13"?
> 
> At a minimal it would be nice to understand what are the circumstances a "Message 13" failure happens - so the Red/Cromwell team can determine if there is anything they can or should do differently. 
> 
>   -Henry

> ------------------------------- 
> jgentry@broadinstitute.org  <jgentry@broadinstitute.org>  #4 Jan 12, 2018 11:45AM 
> As I'm fielding questions about why there's a cromwell bug\ for not properly retrying preemptions in these cases I wanted to bump this a bit.

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #5 Jan 16, 2018 03:59PM 
> This is occurring more and more.  It is starting to impact our through-put for our production pipeline processing

> ------------------------------- 
> kemp@google.com  <kemp@google.com>  #6 Jan 17, 2018 10:44AM 
> Nothing has changed in Pipelines API in this regard.  I suspect either a GCE preemption policy change or some other resourcing issue.  Mike, can you reach out to the GCE team on this?
> 
> Garret, let's look at some of the operations in #1 and see if we can see any differences that point to the 13/14 error codes.

> ------------------------------- 
> maltarace@google.com  <maltarace@google.com>  #7 Jan 17, 2018 11:45AM 
> Henry, can I get a project name and recent most time this issue occurred?

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #8 Jan 17, 2018 12:12PM 
> Mike,
> 
>   Will get some more recent ones - but here is the project, start, end times, instance name, zone/machinetype  for the opids listed in ticket.  As you can see diff projects, diff region/zones, diff machine types
> 
> broad-wgs-prod2, 2018-01-02T03:00:06Z, 2018-01-02T03:53:16Z, ggp-17542369260334007071, us-east1-c/n1-standard-2
> broad-wgs-prod2, 2018-01-02T04:05:53Z, 2018-01-03T04:21:41Z, ggp-18057230858599167003, us-central1-f/n1-standard-2
> broad-wgs-prod2, 2018-01-03T04:26:14Z, 2018-01-03T04:46:10Z, ggp-7937324860344917086, us-central1-b/n1-standard-2
> broad-wgs-prod5, 2018-01-02T02:41:01Z, 2018-01-02T03:22:06Z, ggp-11988893419759480789, us-central1-c/n1-highcpu-16
> broad-wgs-prod4, 2018-01-02T00:15:18Z, 2018-01-02T00:21:17Z, ggp-18106873489744102645, us-east1-c/n1-highcpu-16
> broad-wgs-prod4, 2018-01-02T00:15:18Z, 2018-01-02T00:41:12Z, ggp-6167961352240691213, us-east1-c/n1-highcpu-16
> broad-wgs-prod4, 2018-01-02T05:04:12Z, 2018-01-02T08:08:13Z, ggp-11274588927191136018, us-east1-d/n1-standard-2

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #9 Jan 17, 2018 12:14PM 
> Mike, 
> 
>   by the way all this information can be gotten from the opsIDs by querying:
> 
> gcloud alpha genomics operations describe

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #10 Jan 17, 2018 12:24PM 
> Mike here is a sample of a single cromwell workflow that had several msg 13 today.  These will be all in the same google project because they are all tasks for a single cromwell workflow - hence submitted to the same google project.
> 
> OPSIDs:
> operations/EJSY-PyPLBj70ovqz_bsgBkgx_mw9zYqD3Byb2R1Y3Rpb25RdWV1ZQ
> operations/EKGY-PyPLBiP3ujwj4bp2RIgx_mw9zYqD3Byb2R1Y3Rpb25RdWV1ZQ
> operations/EJyY-PyPLBiCmP-w6fbCkvkBIMf5sPc2Kg9wcm9kdWN0aW9uUXVldWU
> operations/EOmJ04WQLBje78i27O_npfIBIMf5sPc2Kg9wcm9kdWN0aW9uUXVldWU
> operations/EOCf-4iQLBjstJf68LiInBkgx_mw9zYqD3Byb2R1Y3Rpb25RdWV1ZQ
> operations/EOjA9oqQLBjtl7_8otWYjTQgx_mw9zYqD3Byb2R1Y3Rpb25RdWV1ZQ
> 
> broad-wgs-prod5, 2018-01-16T15:37:16Z, 2018-01-16T17:45:43Z, ggp-1801918915849415035, us-central1-c/n1-standard-16
> broad-wgs-prod5, 2018-01-16T15:37:16Z, 2018-01-16T15:46:25Z, ggp-1347601243842424591, us-east1-c/n1-standard-16
> broad-wgs-prod5, 2018-01-16T15:37:16Z, 2018-01-16T17:14:27Z, ggp-17952768368412969986, us-east1-c/n1-standard-16
> broad-wgs-prod5, 2018-01-16T20:41:42Z, 2018-01-16T22:28:14Z, ggp-17459223747282221022, us-central1-b/n1-standard-2
> broad-wgs-prod5, 2018-01-16T22:37:32Z, 2018-01-16T23:38:28Z, ggp-1817239588482439788, us-east1-c/n1-standard-2
> broad-wgs-prod5, 2018-01-16T23:46:08Z, 2018-01-17T14:57:19Z, ggp-3754421722448645101, us-east1-d/n1-standard-2

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #11 Jan 17, 2018 12:32PM 
> Mike, 
> 
>   For comparison - the previous reported workflow also had a Message 14: type pre-emption.  Which is what cromwell normally detects as pre-emption.  Not sure what is difference between the above pre-emptions and the one below.  Info as follows:
> 
> OPSID
> operations/ENOi-PyPLBioyJKO-s3GhY0BIMf5sPc2Kg9wcm9kdWN0aW9uUXVldWU
> 
> broad-wgs-prod5, 2018-01-16T15:37:17Z, 2018-01-16T16:43:22Z, ggp-10163246050849367080, us-east1-d/n1-standard-16

> ------------------------------- 
> gdk@google.com  <gdk@google.com> Jan 17, 2018 01:36PM
> Accepted by gdk@google.com

> ------------------------------- 
> gdk@google.com  <gdk@google.com>  #12 Jan 17, 2018 02:52PM 
> The difference between 13 and 14 here is simply when PAPI notices that the VM has been shut down.  They mean essentially the same thing, and cromwell should be able to retry with the same logic.
> 
> It looks like this might have been exacerbated because changed the shutdown behavior of VMs so that they won't stay around for 24h for debugging before the holidays.  This means that when a VM is preempted it shuts down faster than it used to, and so PAPI may see the shutdown at a different point.

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #13 Jan 17, 2018 03:08PM 
> So, gdk - will Message 13 - only happen with pre-emptibles?   Will a non-preemptible vm that is somehow shutdown also end up getting a Message 13 returned?  If so - then how can one tell the difference?  I thought Message 14 only happened on pre-emptibles.

> ------------------------------- 
> jgentry@broadinstitute.org  <jgentry@broadinstitute.org>  #14 Jan 17, 2018 03:13PM 
> Hi - 
> 
> In the past we've been told that Message 13 was a generic catch all for 
> something unexpected happening. For instance I'm pretty sure (but don't 
> have data to back this up) that we see 13s when not running a preemptible 
> instance. 
> 
> Cromwell retries both messages, but treats them differently. It will simply 
> retry on a 13, but for preemptibles we will switch from using a preemptible 
> to a standard instance after N preemptions. 
> 
> J 
> 
> ------------------------------- 
> gdk@google.com  <gdk@google.com>  #15 Jan 17, 2018 05:01PM 
> Hi Henry, Jeff,
> Message 13 can occur with non-preemptible instances as well.  In cases where the controller sees an error and exits, if the PAPI servers don't see the instance shutting down then you'll see an error 13 as well.
> 
> I think the solution is to not differentiate your behavior on the content of the returned message, and always retry if the operation is showing as aborted and the instance was preemptible.

> ------------------------------- 
> ferrara@broadinstitute.org  <ferrara@broadinstitute.org>  #16 Jan 18, 2018 07:20AM 
> Can Message 14's occur with non-preemptible instances?  Like Message 13s cane?

> ------------------------------- 
> jgentry@broadinstitute.org  <jgentry@broadinstitute.org>  #17 Jan 18, 2018 10:26AM 
> hi - 
> 
> So is it the case that 100% of the time one receives a message 13 that it's 
> a preemption? 
> 
> The problem is that we keep them on separate counters so as to maximize the 
> number of preemptible tries a user gets (we try preemptibles up to N times 
> before falling back to a standard instance) but will retry other retryable 
> errors on their own count. If we're treating transient errors as 
> preemptible when they're not people can wind up on a standard instance 
> before it's necessary. 
> 
> If it's not 100%, is there any way for the error to include a message that 
> can indicate it's really a preemption? As an example, error code 2 will 
> sometimes indicate it was a preemption. 
> 
> J 

@hjfbynara tagging you if you have anything you want to add

**Comment by geoffjentry** [comment]
Closing this as even if we get to this we'll be on PAPI2 exclusively and that works differently. If this problem re-arises there we can deal with it then
