### ISSUE TITLE
Workflow option to retry any task failure

### ISSUE THREAD

**Issue by dshiga** [broadinstitute/cromwell#3161]
# Summary

Currently Cromwell will retry tasks that fail in Pipelines API due to preemption, with the number of retries configurable on a task by task basis.

It would be very helpful if this could be generalized, so that I could tell Cromwell to retry all tasks that fail -- for any reason, not just preemption.

I imagine this being configured via a workflow option like "failed_task_retries: 3", which would tell Cromwell to run each task in the workflow up to 3 times if any type of failure is encountered.

# Why it would be valuable

For people running many instances of a well-tested workflow, such as Green Team and Mint Team production at Broad, the vast majority of failures are due to transient problems in the cloud, and it is very time consuming to deal with them.

Having this auto-retry capability in Cromwell would be a huge help in making these workflows more robust and would greatly reduce the amount of manual work required to relaunch failed workflows (or save people from having to write their own bespoke scripts to auto-retry failed workflows). Having retries at the task level (rather than having to resubmit the whole workflow) would also be more efficient, especially when call caching is not in use.

# Difference from existing issue

I believe this feature would satisfy the use cases of many (but not all) of the commenters on #1991, but in a simpler way. In contrast to that issue, no error messages need to be parsed here and there is no added functionality around auto increasing memory or disk. (For Mint Team produciton, we're interested in something like #1991, too, especially the stderr pattern matching, but I am guessing it would take longer to make happen given the wdl changes required, etc. The issue I'm filing here is the low hanging fruit for us.)

# Combining with preemptibles

There is a question to resolve about what to do for a preemptible task in a workflow where failed_task_retries has also been set.

My preference would be to make them additive. If the task says "preemptible: 5" and the workflow says "failed_task_retries: 3", then Cromwell will retry that task up to 8 times. The first 3 retries will use a preemptible machine -- regardless of the reason for the error. Additional retries beyond that will not use a preemptible machine.

This approach would let failed_task_retries act as a floor for the entire workflow that guarantees all tasks, preemptible or not, will retry at least failed_task_retries times upon failure.

**Comment by cjllanwarne** [comment]
I remember we added this for certain JES failures so the backend plumbing might already be there (although IIRC we called it "unexpected failure" and it was hard coded to 3)

**Comment by dshiga** [comment]
**Update: Non-additive retry counts**

If failures due to preemption can be clearly distinguished from failures due to other causes, I would prefer the failed_task_retries count to be independent of the preemptible count, rather than additive.

For example, with failed_task_retries: 2 and preemptible: 2, I would expect the following behavior:
- try 1: preemptible machine, got preempted
- try 2: preemptible machine, other error (not preemption)
- try 3: non-preemptible machine, error
- try 4: non-preemptible machine, error
- task fails

We have only retried 3 times here, because one of the non-preemption retries was "used up" when try 2 failed. (With additive behavior, we would have retried 4 times.)

This behavior would allow users to independently set the retries due to preemption from those due to other causes, to more finely tune the desired behavior.

However, if this can't be accommodated, this feature would still be very valuable with the additive behavior.

**Comment by geoffjentry** [comment]
@dshiga We already track preemptions and other retries separately

**Comment by kbergin** [comment]
Curious if #1991 relates to this?

**Comment by dshiga** [comment]
Definitely does, some discussion of it in "Difference from existing issue" above.

**Comment by kbergin** [comment]
@dshiga: @ruchim talked to myself and @samanehsan today about whether it would be ok for this to be implemented as a runtime attribute that could be configured per task and we thought that would be ok. It is the way they prefer to implement it.

**Comment by geoffjentry** [comment]
Please do not have this as a runtime attribute.

**Comment by brmyers** [comment]
Any thoughts on how a general task retry policy may interact with [#1499](https://github.com/broadinstitute/cromwell/issues/1499) when the job scheduler (or user) kills a job on sge and the server is restarted?

I'm envisioning the "check-alive" result showing no job on sge invoking one of the task retries that a user specifies (whereas currently it'd be marked as failed).

Thanks!
