### ISSUE TITLE
Allow size() to accept Array[File]

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3183]
- [x] Implement WDL spec change https://github.com/openwdl/wdl/pull/169
- [x] Comment on the spec change that an implementation exists and that it may now be closed

**Comment by cjllanwarne** [comment]
This was already released in Cromwell 32

**Comment by freeseek** [comment]
I want to comment on the fact that there are hidden dangers in using the function `Float size(Array[File])` as shown in a Terra community forum [post](https://support.terra.bio/hc/en-us/community/posts/360071583412-PreparingJob-state-consumes-most-of-a-task-running-time-how-to-avoid-). For large arrays, this can cause tasks to take forever to start in Google Cloud. Although this is not a WDL specification issue, developers need somehow to be made aware of this, especially in cases where the array contains files that are known in advance to have similar sizes, in which case the following code:
```
input {
  Array[File]+ files
}
Float arr_size = size(files, "GiB")
```
Could be replaced by:
```
input {
  Array[File]+ files
}
Float arr_size = length(files) * size(files[0], "GiB")
```
And be significantly more efficient.
