### ISSUE TITLE
CWL salad left behind after workflow finishes

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#3186]
While running a CWL workflow, cromwell writes files to disk so that [cwltool](https://github.com/broadinstitute/cromwell/issues/2718) may salad them.

While the top-level CWL is read back into memory (& db??) the top-level CWL often refers to other relative files on disk. These relative files are required to remain for the duration of the workflow. After the workflow completes the files should be deleted. Otherwise after a large number of workflows the local disk will fill up.

Right now, the salad files are being written to a random path. For the purposes of this ticket the files could be written to a directory based on the stable `workflowId` (a `UUID`). The per-workflow logs do something similar, and are deleted at the end of the workflow in a way that the cwl files should be also.

**Comment by Horneth** [comment]
Why do we need them for the duration of the workflow ? Aren't we good once we've got the full CWL object ? If so we could delete the whole thing right after it ?

**Comment by kshakir** [comment]
> Why do we need them for the duration of the workflow ?

Just getting to this now and I don't 100% remember why. I would try deleting them and "see what happens". From what I remember at least one conformance test crashed due to missing files.

**Comment by Horneth** [comment]
The original issue __might__ be alleviated by the fact that the conformance test runner (as well as `cromwell submit`) now salads everything in place and inlines all imported cwls into a single standalone CWL workflow
