### ISSUE TITLE
Support $(runtime.outdir)

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#3208]
Description to be added once I understand what this means.

**Comment by cjllanwarne** [comment]
> once I understand what this means

Bit of a guess but I believe `runtime` is a set of attributes to add into the javascript DOM before executing, just like `inputs`. I'd guess that `outdir` is one of those which specifies where outputs are referenced relative to

**Comment by mcovarr** [comment]
Yup, thanks. I never circled back to updated this. 😄 It actually was being set but not quite correctly and also some environment variables aren't quite right, that's still WIP.
