### ISSUE TITLE
Metadata Endpoint Timing Out (cromwell restarted while subworkflows of workflow running)

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#3209]
version: `"cromwell": "30-f58c191-SNAP"`

I'm trying to get metadata for some workflows and it seems that for workflows whose subworkflows were running when cromwell was restarted are unable to retrieve their metadata.

`/api/workflows/v1/8e9802db-f846-4ea5-a72c-55f257e53abe/metadata?expandSubWorkflows=true` 

returns
```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```
even if i try compressed payload or any other kind of trick I could think of. 

If I try grabbing the metadata without expanding the subworkflows

`/api/workflows/v1/8e9802db-f846-4ea5-a72c-55f257e53abe/metadata?expandSubWorkflows=false`

returns the metadata just fine almost instantly.  If I try to get the metadata of the subworkflow(s) directly it works as well.

These workflows also have interesting responses to `includeKeys` parameter.

When trying to get only the key `calls` from the workflow that was timing out (in hopes to make it not time out by requesting less data) 

`/api/workflows/v1/8e9802db-f846-4ea5-a72c-55f257e53abe/metadata?expandSubWorkflows=true&includeKey=calls`

returns
```
{
"status": "error",
"message": "Received unexpected response while waiting for sub workflow metadata."
}
```
note `calls` is a key that normally doesn't return anything so normally you would expect to get

`/api/workflows/v1/905e2b4c-908d-4e93-a99c-ad20f6e4c41a/metadata?expandSubWorkflows=true&includeKey=calls`
```
{}
```
if you try to filter down the metadata to a key that does exist in the metadata like

`/api/workflows/v1/8e9802db-f846-4ea5-a72c-55f257e53abe/metadata?expandSubWorkflows=true&includeKey=call`

returns
```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```
for the workflow that was restarted mid run (like it did when we were asking for the full metadata)
and returns the `calls` metadata successfully for the workflow that always returned the metadata.

**Comment by geoffjentry** [comment]
Spoke to @jsotobroad who said this is not blocking at all, but just a FYI for us

**Comment by Horneth** [comment]
Fixed by https://github.com/broadinstitute/cromwell/pull/3260
