### ISSUE TITLE
Request: hombrew formula installing womtool

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/cromwell#3254]
Currently, the formula in hombrew-core (https://github.com/Homebrew/homebrew-core/blob/master/Formula/cromwell.rb) does install only cromwell, but not womtool. It will be nice to install both at the same time, or have an option to do so.

Another possibility is to add a new formula for it informing that it exists...

**Comment by cjllanwarne** [comment]
+1

**Comment by magicDGS** [comment]
I added a PR to fix this https://github.com/Homebrew/homebrew-core/pull/24031

**Comment by magicDGS** [comment]
Already merged on homebrew-core
