### ISSUE TITLE
Stuck for running. (dead letters encountered)

### ISSUE THREAD

**Issue by hmkim** [broadinstitute/cromwell#3269]
Hello! 

Firstly, I'm thank you so much for useful program. (cromwell)

![2018-02-13 10 44 32](https://user-images.githubusercontent.com/4966343/36129525-eed876ea-10aa-11e8-8956-2ccf81ae18c7.png)

Command line is..
$ java -jar /home/brandon/cromwell/cromwell-30.2.jar run -i test.json processing-for-variant-discovery-gatk4.wdl

It does not processing anymore in this status. 

How can I handle this problem?

**Comment by Horneth** [comment]
Hi @hmkim !

A couple questions to help us figure out what's going on:
Is this happening consistently or have you been able to get it to run successfully ?
Does it always get stuck at the same point ?

**Comment by Horneth** [comment]
Looking into it more closely, there's a good chance we fixed this issue already, we just haven't released a 30.3 jar yet. Meanwhile if you're able to build from the `30_hotfix` branch you might want to try that.

**Comment by hmkim** [comment]
Hello @Horneth !

With deleting the docker code in workflow script, I passed this issue.

Ok, I'll try to run from the 30_hotfix branch and report it. 

Thanks.

**Comment by hmkim** [comment]
@Horneth I tried to run with build from 30_hotfix.
but it was same.  This happening consistently.

![2018-02-19 12 01 10](https://user-images.githubusercontent.com/4966343/36361090-9906fdba-156c-11e8-9e1d-37ab4f39bf1a.png)

**Comment by Horneth** [comment]
Interesting, could you look at the content of `stdout` and `stderr` for those stuck tasks ? Does it look like it's still doing work ?
It looks like you're running this locally on your machine ? How big are the samples in your `test.json` ?
I don't think the docker dead letters message are actually the issue (even though I'm not sure why they're appearing I'll look int that).

**Comment by hmkim** [comment]
Yes, I also think dead letters message is no issue. 

root@d0ef87b8b6b8:/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/7ffcdf28-2324-4c07-8e87-926a150334d9/call-SamToFastqAndBwaMem/shard-0/execution# **cat stderr**
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/7ffcdf28-2324-4c07-8e87-926a150334d9/call-SamToFastqAndBwaMem/shard-0/execution/tmp.rmIqEe
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
> [M::bwa_idx_load_from_disk] read 0 ALT contigs
> [W::main_mem] when '-p' is in use, the second query file is ignored.
> 

stdout is 0 byte.

I'm running on local machine. 
Just I used 2 bam file only.
$ /BiO/Project/brandon-genome-analysis/data/NA12878_24RG_small.txt
/BiO/Project/brandon-genome-analysis/data/HJYFJ.4.NA12878.downsampled.query.sorted.unmapped.bam
/BiO/Project/brandon-genome-analysis/data/HJYFJ.5.NA12878.downsampled.query.sorted.unmapped.bam

I found some issue in stderr file.

> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/7ffcdf28-2324-4c07-8e87-926a150334d9/call-SamToFastqAndBwaMem/shard-0/execution/tmp.rmIqEe
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

Could you suggest any comment for this ?

**Comment by Horneth** [comment]
I'm not a specialist of GATK but this error doesn't seem like a big deal, it looks like it's defaulting to another logging mode. Maybe @vdauwera would know more ?
If you `ps -elf | grep java` is there anything still running in this docker container ?

**Comment by hmkim** [comment]
No fatal error. so, close.
