### ISSUE TITLE
Investigate AWS docker compose

### ISSUE THREAD

**Issue by elerch** [broadinstitute/cromwell#3287]
There is a jes-specific docker compose file that includes hooks for authentication. We probably need the same thing for the AWS backend.

**Comment by Horneth** [comment]
If you're talking about the one in the `scripts` directory, the ones that are here now are mostly convenience scripts but are not strictly necessary to run Cromwell. We just wanted a place to put script that could be useful.
If you want to add AWS scripts to it though feel free. Like you said in another ticket, that would be a good place for a cloud formation script for instance I think.

**Comment by elerch** [comment]
CloudFormation will be handled by @delagoya in a repo outside Cromwell, so I'm going to close this issue for now.
