### ISSUE TITLE
JES_JOB database table

### ISSUE THREAD

**Issue by elerch** [broadinstitute/cromwell#3288]
Looking at the database migration scripts there is a JES_JOB table for overseeing Google Pipelines work. Do we need a) an AWS_JOB or b) should this be more generic to accommodate all CSPs?

**Comment by mcovarr** [comment]
That table ceased to exist a while ago, hopefully the schema we have now should work for all backends.

**Comment by Horneth** [comment]
There is a more generic `JOB_KEY_VALUE_ENTRY` table now that backends can use to store K/V pairs. The standard backend uses it to store and retrieve job IDs for example so that jobs can be reconnected to on restart.

**Comment by geoffjentry** [comment]
@Horneth Just to double check, one shouldn't be writing to that table directly, correct? Instead, going through the KeyValueServiceActor (itself via the ServiceRegistryActor)

**Comment by Horneth** [comment]
@geoffjentry yep absolutely, thanks for clarifying

**Comment by elerch** [comment]
Excellent - thanks!
