### ISSUE TITLE
Array or complex File objects are ignored when final_workflow_outputs_dir is specified

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/cromwell#3293]
Although I specify `final_workflow_outputs_dir` in my JSON options, not all the files are copied to that directory. My workflow output looks like this:

```wdl
...
    output {
        File sync = NeutralSimulations.sync
        Array[File]? input_fasta = input_fasta.fastas
        Array[Pair[Int, Array[File]]] fastas_per_generation = zip(tracked_generations, simulation_fastas.fastas)
    }
...
```
Only the `sync` file is output in the directory, but the `input_fasta` and `fastas_per_generation` are ignored and kept only under `cromwell-execution`.

**Comment by Horneth** [comment]
@magicDGS if you can build from the head of develop this issue should be fixed now. Let us know if that's not the case :)

**Comment by magicDGS** [comment]
Now it's working. Thank you very much!
