### ISSUE TITLE
loops do not work properly

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#3305]
I cannot mutate any variables outside of the loop. I cannot even rewrite an array by its index if array is declared outside of while loop. Why the hell do we need loops then?
```wdl
    Array[Int] array = ["one", "two", "three"]
    Int i = 0
    Int len = length(array)
    while(i < len){
        i = i +1 #does not work
        array[i] = "other value" #does not work
        #some other stuff
    }
```

I also tried to do the same with scatters, same problems (I cannot change variables outside of the loop). That means that both while and scatter loops are half-functional in Cromwell.

**Comment by geoffjentry** [comment]
Hi - loops have never been supported and frankly should be considered for removal from the wdl spec (for now at least)

**Comment by antonkulaga** [comment]
@geoffjentry in such case I have not idea how I can do anything other than super-simple linear pipelines with wdl: tsv-s with headers cannot be read, read_json does not work, loops do not work, I cannot make even simpliest preprocessing of input arrays or maps with wdl!

**Comment by geoffjentry** [comment]
@antonkulaga Not a value judgement on my side, just that you are officially the first person I've ever heard of trying to use WDL loops so to call it a dusty corner is an understatement. 
When we first created WDL there was a single use case that we knew of and even that project decided they didn't really want a loop construct.

My statement that it should be removed for now was because whatever the spec currently says is almost certainly not ideal since it wasn't rooted in reality but just 3 people trying to foresee the future.

**Comment by antonkulaga** [comment]
@geoffjentry my labmates prefer TSV-s with headers and I had to adapt, so I tried loops as a solution. Going through Array[Array[String]] and turning it into Array[Map[String, String]] in a loop looked like the best solution for me. I tried both while loops and scatters and both of them could not change change the array announced before the loop.

**Comment by cjllanwarne** [comment]
* This actually has been officially removed from the draft-3 spec on account of it never being implemented by any engine.
* The read_json and write_json (and structs in draft-3) will hopefully ease a lot of the annoyances you're finding here (it's been known to be annoying, we're just finally able to put resources towards easing it now)
* All WDL values are immutable as an early design choice for the language. Think of them less as variables in an imperative language and more as write-once declarations in a DAG (ie an execution graph). Say some subsequent task uses `len` in your example above. If values are mutable then how can Cromwell know when it's safe to use the value? If you force all tasks to complete before anything after them starts then one slow task cannot run in parallel with several fast tasks.
* I think what you really want is some kind of list comprehension (eg equivalent to python's `[x + 1 for x in x_list]`). You can get something similar by using the implicit gather on a scatter. eg I could map over an array to calculate the "values plus one" array like this:
```wdl
workflow foo {
  Array[Int] input_array
  scatter(i in input_array) {
    plus_ones = i + 1
  }
  Array[Int] input_array_plus_ones = plus_ones # gathers the results from the plus-one'ing
}
```

**Comment by geoffjentry** [comment]
@antonkulaga Gotcha. Again, not saying you're wrong, just explaining why it manages to both look like a forgotten artifact in the WDL spec and was never implemented in Cromwell.

From my Cromwellian perspective I personally wouldn't support implementing it until it at least underwent some sort of transformation in the WDL spec (e.g. clarifications at a minimum), which requires someone to champion it over there.

**Comment by antonkulaga** [comment]
@cjllanwarne you are totally right, if read/write_json worked it would not be such a pain, I would simple write everything to json, give it to a task with some Scala (or whatever language I want) script that return json and then read it to a cromwell Map.

>All WDL values are immutable as an early design choice for the language.

I do not mind it, I am used to it in Scala, but in Scala I have powerful filter/map/flatMap/foldLeft are you going to give any of them to WDL?

>You can get something similar by using the implicit gather on a scatter. eg I could map over an array to calculate the "values plus one" array like this:

Thanks, I did not know that such thing is possible, I thought that all variables declared inside loops/scatter are not visible from outside

**Comment by cjllanwarne** [comment]
@antonkulaga -

1. If you use read_json the type you get will actually be a WDL `Object`. You should be able to coerce to map but only if the values are all the right type. Also look out for better `object` support with draft 3's `struct`s.

2. you're right, some kind of list comprehension (equivalent to a scala map function) has certainly come up before (they'd need to be spec changes in openWDL, but I'd certainly be happy to see those sorts of PR popping up).

3. for values available outside scatters - it's just like call outputs - we add implicit gatherers for Declarations too. The syntax is ugly but hopefully it works for you until we get some sugar around it in the spec via openwdl 😄

**Comment by cjllanwarne** [comment]
I'm going to close this issue - I think the original question was answered but if you have other issues (with the workarounds mentioned for example), continue to open bug reports or forum posts about them specifically. Thanks!

**Comment by bolton-lab** [comment]
How are people handling a group of bam files and their indexes?  I.e. I have an array of maps, where each map has a "bam" file and a "bamIndex" file.  How would I be able to send this Array of Maps to samtools merge as in:

input {
	Array[Map[String, File]] bamPlusIndexes
}

command {
~{runtime_params.samtools_path} merge -f merged.bam ${sep=' ' bamPlusIndexes.bam}
}

How do I get the same key from every entry in the array of maps?
