### ISSUE TITLE
reads_json does not work

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#3306]
Whenever I try to use read_json it does not work.
For instance, when I make a simple wdl like:
```wdl
workflow quantification {

    File references
    Map[String, String] indexes = read_json(references)
}
where test.json is:
```json
{
  "quantification.references": "/home/antonkulaga/rna-seq/workflows/rna-seq/quantification/inputs/test.json"
}
```
```
it tells
```
Unable to build WOM node for Declaration 'indexes': Return type of read_json() can't be known statically
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
```
That means I cannot just load a file and parse it, so how else can I read JSON then?

**Comment by cjllanwarne** [comment]
Hey @antonkulaga, are you running this in Cromwell 30?

The good news: this was indeed a known issue for a long time but I believe it's finally been fixed as of https://github.com/broadinstitute/cromwell/pull/3175. 
The bad news: that won't be available until the next Cromwell release. If you're comfortable building from develop you're welcome to do that and try it out!

**Comment by antonkulaga** [comment]
@cjllanwarne I run it on latest cromwell 30.2 release, the latest release at the moment

**Comment by geoffjentry** [comment]
@antonkulaga What @cjllanwarne means is that if you build off of the `develop` branch it should work for you. If you're ok with waiting until the next release (likely 31, potentially 30.3), it'll also be fixed for you.

**Comment by antonkulaga** [comment]
@geoffjentry my labmates prefer TSV-s with headers and I had to adapt, so I tried loops as a solution. Going through Array[Array[String]] and turning it into Array[Map[String, String]] in a loop looked like the best solution for me. I tried both while loops and scatters and both of them could not change change the array announced before the loop.

My second usecase is

**Comment by antonkulaga** [comment]
>If you're ok with waiting until the next release (likely 31, potentially 30.3), it'll also be fixed for you.

Everything depends on how soon you are agoing to publish 30.3 If it is a week, I am ok to wait, if it will take longer - I will build from source

**Comment by geoffjentry** [comment]
@antonkulaga It'll probably be > 1 week. We can't predict the frequency of the dot releases as they're almost always in response to some fire that erupts in production.

**Comment by antonkulaga** [comment]
I build from master, looks like read/write_json work there. Thank you!
If I will find any bugs with them I will reopen

**Comment by antonkulaga** [comment]
Looks like read_json in current trunk still has some issues.
When I give a json like this:
```json
{
  "Homo sapiens": {
    "transcriptome" : "/pipelines/indexes/HUMAN/27/gencode.v27.transcripts.fa",
    "gtf": "/pipelines/indexes/HUMAN/27/",
    "salmon": "/pipelines/indexes/HUMAN/27/salmon"
  },
  "Mus musculus": {
    "transcriptome" : "/pipelines/indexes/MOUSE/M16/gencode.vM16.transcripts.fa",
    "gtf": "/pipelines/indexes/MOUSE/M16/gencode.vM16.annotation.gtf",
    "salmon": "/pipelines/indexes/MOUSE/M16/salmon"
  }
}
```
with wdl like this
```
Map[String, Map[String, String]] indexes = read_json(references)   
```
I get:
```
Workflow input processing failed
WorkflowFailure(ERROR: indexes is declared as a Map[String, Map[String, String]] but the expression evaluates to a Object: Map[String, Map[String, String]] indexes = read_json(references) ^ ,List())
```
I do not get what is wrong there, I've tried different type combinations.

**Comment by cjllanwarne** [comment]
Hi @antonkulaga - sorry to come to this so late. It does look like the coercion function might require a little bit of a fixup here. In the mean time did you try using the `Object` type?
```
Object indexes = read_json(references)
```
