### ISSUE TITLE
Secondary files not supported on arrays of files

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#3317]
Required for the Wash U CWL and conformance test 93. I originally wrote this to demonstrate that handling of array of file secondary files was broken in Cromwell, but actually it looks like even regular file secondary files are broken on the Docker local backend. 😢

This must use the branch `cwl_secondary_files` as it requires a fix for a shellquoting bug wrt CWL expressions that is only on this branch. The `cwl_secondary_files` conformance test demonstrates these issues in the context of inputs to a CommandLineTool. To test with cwltool:

```
cd ${CROMWELL_REPO}/centaur/src/main/resources/standardTestCases/cwl_secondary_files
cwltool cwl_secondary_files.cwl cwl_secondary_files.json
```

Note from the cwltool output how each primary input file is put into its own separate staging directory alongside all of its secondary files. 🤔 

For Cromwell this needs to be tested with server mode since run mode blows up. Start up a server:

```
cd ${CROMWELL_REPO}/centaur/src/main/resources/standardTestCases/cwl_secondary_files
java -jar /path/to/cromwell.jar server
```

Then run the Centaur test:

```
cd ${CROMWELL_REPO}
sbt "centaur/it:testOnly * -- -n cwl_secondary_files"
```

Note that in Cromwell none of the secondary files are staged into the inputs directory, not even for the single file.

This Centaur test requires files to be staged in the same directory where the Cromwell server is running which I don't think is something the Travis Centaur setup currently supports. However once this bug is fixed conformance test 93 may be sufficiently equivalent and perhaps this test can just be deleted. Please don't delete the expression shellquoting fix though, we want to keep that. 🙂 It would be nice to find a test other than this that exercises it.

**Comment by mcovarr** [comment]
oh hello `CreateFileRequirement`

**Comment by kshakir** [comment]
I don't know about `CreateFileRequirement`, but the original report has been addressed in `develop`.
