### ISSUE TITLE
umask overriden when creating directories, leads to access denied errors with linux access control lists

### ISSUE THREAD

**Issue by carolynlawrence** [broadinstitute/cromwell#3333]
We are using cromwell server to run workflows in a shared HPC environment. As it is a shared environment and we are dealing with sensitive data, we have purposely set cromwell to use umask 0007 so that others can't access our files. However, cromwell seems to override the umask and gives rwx world permissions on all directories it creates. 

As far as I can tell, the override is programmed here:
cromwell/core/src/main/scala/cromwell/core/path/EvenBetterPathMethods.scala

Beyond it being non-ideal from a security perspective, this ends up causing downstream "access denied" problems for us when cromwell creates directories downstream of a linux access control list (ACL). It seems like what is happening in this case is (1) the directory is created via cromwell (2) via the OS, the ACL is applied to the folder, giving user & group privileges (3) the world privileges are modified via cromwell, which disrupts the ACL, thus the user and group lose all privileges (4) access denied error when cromwell tries to use the folder

**Comment by geoffjentry** [comment]
Hi @carolynlawrence - yeah, unfortunately this is the result of a careful tension between a handful of usecases where sometimes this is critically necessary and in others it isn't, and obviously it's completely undesirable when it's not absolutely necessary.

Thinking about it a bit more though, the reasons we do this all tie to Docker, and typically in HPC environments people are not using Docker (I'm assuming this applies to you). While internally there's a shared code path we could tease that apart to at least start living more strictly to the mantra of only doing this when we need to.

**Comment by danbills** [comment]
Hi @carolynlawrence.

Would a configuration option to remove this privilege re-assignment be sufficient to fix this?

**Comment by danbills** [comment]
actually I can make it automatic provided the user is not running their workflows via docker.

**Comment by carolynlawrence** [comment]
From my testing, it seems that anything that runs a "chmod"-like command disrupts the ACL-controlled permissions, leading to permission denied and/or other errors. I think if the configuration option wrapped any commands that did this, it would fix the issue. In the meantime I was able to come up with a few workarounds to fix the permissions so that we were happy with the system (moved some files around so cromwell wasn't accessing or trying to move anything past our ACL, and added a "chmod o-wrx..." command to my submit script, but a configuration option that did this by default would be great!

**Comment by geoffjentry** [comment]
@carolynlawrence Just to double check, are you all using Docker in your workflow tasks? The only reason we're fiddling with permissions is due to Docker, and I don't know of anyone using Docker w/ Cromwell in an HPC environment - so my thought was that we could simply disable that permission activity for tasks which are not using docker. 

To tie it into what @danbills suggested, perhaps **that** should be what the configuration flag is doing, just to be sure it's not breaking anyone's reliance on current behavior either way.

**Comment by carolynlawrence** [comment]
@geoffjentry We are not using Docker, but you are right that it might be better to make it a configuration flag like @danbills initially suggested, rather than automatic, in case it would break someone's workflow... like maybe if they were using Docker and non-Docker in the same workflow?

**Comment by geoffjentry** [comment]
@carolynlawrence Great, thanks. @danbills this seems like the best plan IMO

**Comment by danbills** [comment]
Debrief here from a face-to-face w/ @geoffjentry :

So the config flag should be set _AND_ the call should be using docker to do the override.

To be clear, the truth table here is 

Using Docker on this call | Configuration Flag is set to true | Should reassign
--|--|--
T|T|T
T|F|F
F|T|F
F|F|F

Config flag should be `docker.override_umask_when_creating_directories`
