### ISSUE TITLE
Options for Womtool inputs generation

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3338]
Feature requested by Sam Lee:

An optional flag to use along with the `inputs` command in Womtool to print only required inputs vs all inputs (required & optional)

**Comment by Redmar-van-den-Berg** [comment]
I agree that it would be nifty, I currently use
`womtools inputs workflow.wdl | grep -v optional`
But then I have to make sure that the last entry of the json file doesn't have a comma, or else the json file is invalid.

**Comment by cjllanwarne** [comment]
Good news! https://github.com/broadinstitute/cromwell/pull/3611
