### ISSUE TITLE
Record identity of Cromwell running a workflow

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#3340]
In the workflow store, also record the identity of the Cromwell who has been assigned a workflow. 

Without thinking about it deeply, having it be a configurable name seems the best path. Another option would be to use the hostname. Both have issues - config could be misconfigured, but could be running multiple cromwells on the same host. Another thought would be a UUID generated by the Cromwell.

**Comment by kcibul** [comment]
host/port is nice when you think about autoscaling.  having the config file need to be different on every machine will be a headache when you want an ELB to spin up more nodes based on load.

in a non-container world, that's straightforward.  In a container world, the hostname (as defined by /etc/hostname, which is what typical java apis use to determine hostname) is set to a unique container id.  So even if you're running multiple containers on the same host on the same port (pre-NAT) you'll get unique IDs.

```
wm80b-899:~ $ echo $HOSTNAME
wm80b-899
wm80b-899:~ $ docker run -it ubuntu /bin/bash -i
root@62d62e5dc805:/# echo $HOSTNAME
62d62e5dc805
root@62d62e5dc805:/# cat /etc/hostname
62d62e5dc805
root@62d62e5dc805:/# 
```

@jacmrob

**Comment by geoffjentry** [comment]
@kcibul what port, the web server associated with the Cromwell?

It can't be just the host as the host might have multiple cromwells running on it and this needs to work in all situations, not just in a load balanced world.

**Comment by mcovarr** [comment]
There's code now on develop that looks at a config value. It's not clear from the discussion above if that's enough to satisfy this ticket?

**Comment by kcibul** [comment]
Let’s talk after standup.  In this case I think the port that Cromwell itself is listening on works.
