### ISSUE TITLE
Updates in tables shared between workflows should be locked

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#3342]
For any table where there are update queries made (not insert) where the rows represent extra-workflow information, make sure that the table is locked when those updates are happening.

Examples of such a table would be the workflow store or call cache stuff. 

A counterexample would be the metadata table, which is insert-only

**Comment by mcovarr** [comment]
looking at this in the context of the workflow store as part of #3340

**Comment by kcibul** [comment]
Hey Miguel -- happy to brainstorm/tagdeam on the tools for this if you need help.  I think the "SELECT... FOR UPDATE" semantics are what we need here.  See https://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html

Basically when you do the something like 

SELECT ... FROM workflow_store WHERE [is new or dead workflow] ORDER BY submission_time LIMIT n FOR UPDATE

will prevent two things from touching that workflow at the same time.  Then just make sure the update of status happens in the same transaction and you're all set.  

Give a shout... my next two days are shockingly meeting light!

**Comment by mcovarr** [comment]
Hi Kristian, I have WIP out on mlc_horicromtal that I think does essentially what you're suggesting. Apparently I have some dumb bugs in there beyond the ones I documented since all the builds are red, hopefully I can straighten that out tonight.

Thanks!

**Comment by mcovarr** [comment]
fixed

**Comment by ruchim** [comment]
Reopened to confirm this issue has been fixed.
