### ISSUE TITLE
Allow for a DB write to trigger abort of a workflow

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#3344]
Currently when a user issues a request to abort a workflow, the process is purely in-memory. This means that there's no way to manually trigger an abort other than the web endpoint.

Instead, do something similar to the workflow store. Record the request in a table, and have cromwell monitor that table looking for workflows it is running, and when it sees such a thing use that to trigger the abort. 

It is **not** a bad state if there's a workflow in the table which Cromwell doesn't know about.

Make sure any updates to this table are [locked](https://github.com/broadinstitute/cromwell/issues/3342)

**Comment by mcovarr** [comment]
Not 100% sure there's a locking issue in this case as there should be only one Cromwell processing the append-only abort request and at most one Cromwell running an abortable workflow?

**Comment by ruchim** [comment]
@geoffjentry is there consensus that the locking isn't required? or its more of a cautionary choice?

**Comment by kcibul** [comment]
Happy to be a reviewer of the approach w.r.t. locking

**Comment by geoffjentry** [comment]
IMO anything being updated in a shared environment should be protected but i also loathe shared mutable state so YMMV

**Comment by ruchim** [comment]
Closed by #4401
