### ISSUE TITLE
Modify the WorkflowStore update mechanism on Cromwell startup

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3347]
Currently when Cromwell starts it updates all `Running` workflows to `RestartableRunning` and `Aborting` to `RestartableAborting` so that it knows which workflows were already running and need to be restarted.
If multiple Cromwells are started against the same DB, they can't all keep changing all workflow statuses as they start.

**Comment by mcovarr** [comment]
hopefully fixed
