### ISSUE TITLE
Scale CWL ResourceRequirements' memory correctly when expressed as String or Expression

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3382]
CWL expresses memory in MB whereas Cromwell expects Bytes.  For integer/long we simply multiply but for strings and expressions it's not so straightforward.

**Comment by mr-c** [comment]
The `string` in https://www.commonwl.org/v1.0/CommandLineTool.html#ResourceRequirement refers to the text of a CWL Expression/Parameter reference, not the output value. Likewise a CWL Expression must return an `int` or `long` (as specified) and likewise a CWL Parameter Reference must refer to a matching type.
