### ISSUE TITLE
&& operator doesn't short-circuit, possibly || as well 

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#3384]
Reported by @asmirnov239

Cromwell 30.2 doesn't seem to short-circuit for logical operators so that the following fails to evaluate when `optional_int` is undefined:

```wdl 
Integer? optional_int
if (defined(optional_int) && select_first([optional_int]) == 2 ) {
#expresssions to do if optional_int is defined and equal to 2
}
```

expected behavior: if `optional_int` is undefined, if statement evaluates to false. 
actual behavior: cromwell fails and stops with the error: 

>Evaluating defined(gc_low_high_filter_params) && select_first([gc_low_high_filter_params]) == 2 failed: select_first failed. All provided values were empty.

While it hasn't been tested, I presume that cromwell doesn't short-circut for the `||` operator...but it should!

**Comment by geoffjentry** [comment]
@yfarjoun just so i'm clear are you providing the version number to suggest that it used to work, or just because it's generally a useful thing to include?

**Comment by yfarjoun** [comment]
just because it's generally useful.

**Comment by cjllanwarne** [comment]
This should be simple enough to fix for 31 (I think I still have time...)

interestingly the if/then/else do already short circuit so this should work:
```wdl
if (defined(optional_int) then select_first([optional_int]) == 2 else false)
```
... on the other hand the nested if is probably an even easier workaround

**Comment by bolton-lab** [comment]
Is this valid WDL from mutect2.wdl line [982](https://github.com/broadinstitute/gatk/blob/4.2.0.0/scripts/mutect2_wdl/mutect2.wdl#L982)?
`String filter_funcotations_args = if defined(filter_funcotations) && (filter_funcotations) then " --remove-filtered-variants " else ""`

Visual Studio plugin seems to complain.  Just wondering???
