### ISSUE TITLE
Flaky Test: HealthMonitorServiceActorSpec

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3391]
Here's the error message:
```
"Unknown status" did not start with "Timed out" (HealthMonitorServiceActorSpec.scala:76
```

**Comment by cjllanwarne** [comment]
@mcovarr did your PR fix this one? Can we close it?

**Comment by mcovarr** [comment]
Time will tell I guess, but I haven't seen any of these since I merged my PR.

**Comment by cjllanwarne** [comment]
ok. I'll close this for now but let's keep a close eye on it in the spreadsheet
