### ISSUE TITLE
Apply inputbinding algorithm to InputArraySchema

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3394]
The [algorithm to apply inputbinding](http://www.commonwl.org/v1.0/CommandLineTool.html#Input_binding) is not correctly applied to `InputArraySchema` when it is being converted into WOM `CommandPart`s.

**Comment by Horneth** [comment]
Can you comment specifically on what is incorrect ?

**Comment by danbills** [comment]
:frowning:  this is a poor choice of words.  The gist is: it works but I don't understand how the `orElse`'s and "default" are specified so I feel uneasy about it. 

I think that means this is not necessarily a bug, and I should close this.
