### ISSUE TITLE
Files referenced in cwl.output.json are not delocalized on PAPI

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3412]
Not sure how we can do this without globing **everything**
PAPI2 will hopefully make this easier

**Comment by danbills** [comment]
can we interpret cwl.output.json (look for files) rather than glob?

**Comment by Horneth** [comment]
we can't know what the content of `cwl.output.json` will be before the task runs though. And the path of the files that need to be delocalized need to be known beforehand so we can tell PAPI to delocalize them.
