### ISSUE TITLE
Add options for retry calls

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/cromwell#3417]
I have been experimenting some random failures due to docker containers being killed for some reason on my system (not only https://github.com/broadinstitute/cromwell/issues/3370), but if I re-run the workflow with caching enabled then this calls end without failure and the pipeline can continue and work.

Nevertheless, it is tedious to re-run a whole pipeline due to random failures and rely on caching for avoid re-computation. This is something that can be avoided by providing a configuration option for retry jobs (cromwell level) or add to some tasks a runtime attribute (WDL level) to set the number of retries that can be done per-task.

Do you think that this is possible in the near future to avoid re-running a whole pipeline due to a random failure in a concrete task(s)?

**Comment by geoffjentry** [comment]
Hi @magicDGS - we have a number of tickets around custom retries that we intend to tackle. Most near term is #3161 which we expect to complete over the next month-ish.

I'm going to close this, but can you look at both #3161 and #1991 and see if either of them would meet your needs? If not, can you comment on the one which appears closest to what you're looking for and we can go from there.

**Comment by magicDGS** [comment]
Sorry, I use to search in previous issues but I didn't this time - my fault. Issue #3161 is the one that describes what I would like to have in cromwell. Thanks!

**Comment by geoffjentry** [comment]
@magicDGS not a problem at all!
