### ISSUE TITLE
AWS S3 Filesystem Support

### ISSUE THREAD

**Issue by elerch** [broadinstitute/cromwell#3427]
Placeholder for S3 filesystem which will be a dependency of the backend core support #3426

**Comment by elerch** [comment]
Initial support landed. Ref 1689e81 and ff89630.

Some failing tests commented out. In order to pass these tests, S3Path (which should probably be broken out into another file) needs to implement the Path trait directly rather than inheriting from Path.

**Comment by tom-dyar** [comment]
I am trying to use this. I switch to the "aws_backend" branch, checked it out, figured out how to build it, and now I have run into:

[2018-06-04 06:34:20,69] [error] java.lang.IllegalArgumentException: s3://atbiofx-cromwell/cromwell-execution exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: MacOSXFileSystem. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
cromwell.core.path.PathParsingException: java.lang.IllegalArgumentException: s3://atbiofx-cromwell/cromwell-execution exists on a filesystem not supported by this instance of Cromwell. Supported filesystems are: MacOSXFileSystem. Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems

**Comment by elerch** [comment]
@tom-dyar Pull latest and try it now. My initial test is working and I'm running remaining Centaur tests on the code base. S3 FS support was added tonight in aa99ec2. Please open a new issue with the AWS Backend label for any bugs you see. This is still super-early, so I'm sure we'll run into some stuff. Thanks!
