### ISSUE TITLE
Upgrade Cromwell Pipelines API Backend to version 2. 

### ISSUE THREAD

**Issue by bradtaylor** [broadinstitute/cromwell#3449]
Please upgrade Cromwell Pipelines API Backend to version 2. This will be necessary for our portal to launch workflows against GCS "requester pays" buckets with appropriate billing

**Comment by Horneth** [comment]
This can't be closed yet, the previous PR was ground work for this but was not effectively adding V2 support

**Comment by nrockweiler** [comment]
@gemmalam, does this mean "requester pays" buckets can now be used with cromwell?

**Comment by gemmalam** [comment]
@nrockweiler hello, please refer to https://github.com/broadinstitute/cromwell/issues/2916 for requester pays updates.

**Comment by nrockweiler** [comment]
thanks
