### ISSUE TITLE
LOG_LEVEL support in run command

### ISSUE THREAD

**Issue by bwalsh** [broadinstitute/cromwell#345]
Hi.  Thanks for a great project.  Attempting to bring up docker container and hit REST endpoints.
Looks like I needed to add -DLOG_LEVEL to `run` command

```
# pwd
/etc/service/cromwell
# cat run
#!/bin/bash
exec java $JAVA_OPTS -DLOG_LEVEL=$LOG_LEVEL -Djava.library.path=./native -jar /cromwell/cromwell-0.14.jar server
```

**Comment by geoffjentry** [comment]
@scottfrazer Can you take a look at this and file a ticket if necessary

@bwalsh Thanks for reporting this!

**Comment by scottfrazer** [comment]
Perhaps I'm missing something... though I checked versions 0.14, 0.15, and the latest `develop` branch, and they all seem to optionally accept `-DLOG_LEVEL`.  If it was omitted, then it defaulted to the INFO log level in each case.  Are you seeing different behavior?

**Comment by bwalsh** [comment]
@scottfrazer   thanks for the quick follow up.  Yes, the jar accepts the parameter.  However,  it didn't seem as if setting it in the environment was enough, AFAIK I needed to add `-DLOG_LEVEL=$LOG_LEVEL` to the `run` script.

**Comment by scottfrazer** [comment]
Oh, I see, you wanted to do something like this:

```
$ export LOG_LEVEL=DEBUG
$ java -jar cromwell-0.14 server
```

And have it honor the `LOG_LEVEL` environment *without* having to specify `-DLOG_LEVEL=$LOG_LEVEL` at the command line.  That makes sense.

**Comment by bwalsh** [comment]
Thanks.  Our use case is to run cromwell as a docker service for development.  It took a bit of digging to set the log level.  If it picked it up from the environment, we could set if from docker

**Comment by geoffjentry** [comment]
@bwalsh Sorry for the delay here. We have a ticket in our internal tracking system to take care of this.

**Comment by bwalsh** [comment]
no worries, thanks for the update

**Comment by scottfrazer** [comment]
@kshakir was this fixed with your latest changes to logging?
