### ISSUE TITLE
Permission issue Cromwell-31 & WDL

### ISSUE THREAD

**Issue by u909090** [broadinstitute/cromwell#3500]
Hi,

I just moved to a new cluster (no sudo) and try to run a WDL script with Cromwell-31.
Everything worked fine on my previous cluster (same Cromwell / WDL / Java versions and same script).

After creating the wdl script, I validated it and generated a JSON file (with wdl-0.14), no problem.

After running `java -jar cromwell-31.jar run my_script.wdl -i my_script.JSON` the workflow stops, outputting `Permission denied` for the program I call in my .wdl script (which is called from the 'cromwell_executions' folder during the process).

I changed the permission to 777 for this program located in my `/usr/bin`, but still the same issue. The program, once located in the 'cromwell_executions' folder, loses the execution permission for the owner.
Same issue no matter if I submit a PBS job or run it interactively.

Is there anything to mention in a cromwell configuration file or something to tune in the cluster?

Thanks !

**Comment by Horneth** [comment]
Are you running the cromwell 31 release jar or did you build Cromwell from the sources ?
We changed something related to permissions in the develop branch ~1 week ago but it's not in the released 31 jar so I want to (maybe) rule that out.

**Comment by u909090** [comment]
I use the .jar

**Comment by geoffjentry** [comment]
@u909090 Can you provide more information about the set up of your previous cluster and new cluster?

**Comment by u909090** [comment]
! SOLVED !

I reinstalled Cromwell from bioconda (version 30).
I left wdl-0.14.jar. All works well.

Thanks for your help !
