### ISSUE TITLE
CWL conformance 98: Test embedded subworkflow

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#3552]
It looks like our homegrown embedding doesn't take care of calling workflows from external files in workflow steps? `cwltool --pack` seems to create a merged CWL file correctly though.

**Comment by danbills** [comment]
Seems like we could do a two-step process,

1) `pack` to inline
2) `salad` to, um, salad

**Comment by Horneth** [comment]
Oh I didn't know about `pack`, it sounds like we could get rid of our custom inlining with `pack` + `print-pre` like @danbills suggested then ?
