### ISSUE TITLE
Docker private registry configuration 

### ISSUE THREAD

**Issue by delagoya** [broadinstitute/cromwell#3574]
The current [AWS 101 docs](https://github.com/broadinstitute/cromwell/blob/aws_backend/docs/tutorials/AwsBatch101.md) lists an optional section for specifying a private Docker registry. 

```
// Optional Dockerhub Credentials. Can be used to access private docker images.
    dockerhub {
       // account = ""
       // token = ""
    }
```

This should be taken out, since it is handled at the level of a custom AMI for AWS Batch and is not something that you can specify at runtime or within Cromwell.

**Comment by delagoya** [comment]
Closing since this is handled outside of Cromwell and in AWS Batch custom AMI.

**Comment by dfeinzeig** [comment]
can you please elaborate on how to use a private docker registry?

**Comment by aednichols** [comment]
@dfeinzeig for private registries I believe you have to use the Docker CLI as described here: https://cromwell.readthedocs.io/en/stable/tutorials/Containers/#docker-config-block
