### ISSUE TITLE
Implement File literals for Cloud backends

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3581]
File literals should be written to disk similar to the way WDL `write_lines` operation works.

At the moment it is generating a file during workflow materialization, and that code is not compatible with the cloud backends (as the file is generated locally).

IMO this should be done on an ad-hoc basis, i.e. whenever the backend needs a file, it writes a temp one and populates the `File` fields [as specified](https://www.commonwl.org/v1.0/Workflow.html#File).

**Comment by cjllanwarne** [comment]
OOI, what happens currently if the file literals are based on strings generated in upstream tasks?
