### ISSUE TITLE
Highlight removes runtime section

### ISSUE THREAD

**Issue by adamstruck** [broadinstitute/cromwell#360]
The highlight subcommand of cromwell strips out the runtime, param_meta and meta information. 

test.wdl:
```
task runtime_meta {
  String memory_mb
  String sample_id
  String param
  String sample_id

  command {
    java -Xmx${memory_mb}M -jar task.jar -id ${sample_id} -param ${param} -out ${sample_id}.out
  }
  output {
    File results = "${sample_id}.out"
  }
  runtime {
    docker: "broadinstitute/baseimg"
  }
  parameter_meta {
    memory_mb: "Amount of memory to allocate to the JVM"
    param: "Some arbitrary parameter"
    sample_id: "The ID of the sample in format foo_bar_baz"
  }
  meta {
    author: "Joe Somebody"
    email: "joe@company.org"
  }
}

workflow test {
  call runtime_meta
}
```

The command `$ java -jar cromwell-0.15.jar highlight test.wdl console` outputs:

```
task runtime_meta {
  String memory_mb
  String sample_id
  String param
  String sample_id

  command {
    java -Xmx${memory_mb}M -jar task.jar -id ${sample_id} -param ${param} -out ${sample_id}.out
  }
  output {
    File results = "${sample_id}.out"
  }

workflow test {
  call runtime_meta
}
```

**Comment by geoffjentry** [comment]
@adamstruck Thanks for reporting this! As an aside I wanted to add that the functionality other than server/run will be moving to its own utility in the next week or so. I'll make sure it's announced on the Cromwell and WDL mailing lists.

@cjllanwarne Can you take a look at this and create ticket(s) as necessary?

**Comment by scottfrazer** [comment]
Thanks for reporting this, here's the PR for the fix: https://github.com/broadinstitute/wdl4s/pull/4, though it's not complete as it does not add the `meta` and `parameter_meta`.  I will add those to that PR.

**Comment by adamstruck** [comment]
Thanks for addressing this.

**Comment by scottfrazer** [comment]
This should be in the next release
