### ISSUE TITLE
Ability to do NOT(keyX:ValueY) queries

### ISSUE THREAD

**Issue by kbergin** [broadinstitute/cromwell#3608]
A key feature for job manager is an ability to 'archive' a job so that it no longer shows in the UI when you don't want to see it anymore. Say it was a failure and you have dealt with the failure. You don't need to see it every time you look at recently failed jobs if you've dealt with it. The idea for implementing this was to have a label key called "flag" and have a value "archived" that we could apply to jobs a user wants to archive. The part we are struggling with is how to filter those out of view in the UI. If it's not difficult, the best way would be to be able to do queries where we say "show me all the jobs that match this query and do not have the label `flag:archived` attached to them"

Is this something that would be possible?

**Comment by aednichols** [comment]
@kbergin - if Cromwell already faithfully returns any labels Job Manager has set on it, can the filtering functionality live in the Job Manager API or UI instead?

In other words, filtering feels to me like it naturally belongs in Job Manager rather than Cromwell.

**Comment by ruchim** [comment]
Hey @aednichols —so this particular query is paginated, and filtering on the client side gets difficult to handle. I imagine doing this work on the client side would mean having to query for all results, manually filter, fill up the page to the expected item count and discard the unused results?

**Comment by geoffjentry** [comment]
Also, pagination for similar endpoints is going to be required for WES (although I think via a different scheme) so we'll need to start doing it anyways

**Comment by kbergin** [comment]
@aednichols, @ruchim is correct, it's why the JMUI really doesn't perform well (Sometimes crashes) when thousands of workflows with subworkflows are submitted, because we do what you've describedf or filtering out subworkflows in a paginated way on the front end. This is the issue described in #3240. I appreciate the question though, although we have been making changes to cromwell API to support JMUI, it is worth thinking through each one and which team should be accommodating the use case.

**Comment by aednichols** [comment]
Makes sense, thanks for the explanation (asking "why?" is often a great way to get context).

**Comment by salonishah11** [comment]
Hi @kbergin, is the label `flag:archived` applied to root workflows or both root and it's subworkflows?
