### ISSUE TITLE
How to localise a directory with a symbolic link?

### ISSUE THREAD

**Issue by santiagorevale** [broadinstitute/cromwell#3614]
Hi there!

I'm new to both WDL and Cromwell. I'm trying to run a workflow and the main input is an Illumina run folder, which could be up to a Tb in size. So I don't want it to be copied or hard-linked (which is almost the same in time) but to be soft-linked. I changed the localization option in the backend but then I'm getting the following error:

`Cannot localize directory with symbolic links`

So, isn't this possible? Will I always have to hard-linked the directories? This is not an option in my case due to performance issues. Everything is in the same shared file system, so I don't see the point in hard-linking. Also, if I call the same directory in different tasks, will it be hard-linked every time?

Thank you very much in advance!

Best,
Santiago

**Comment by geoffjentry** [comment]
The fact that you can reference a directory with a `File` in WDL is an artifact and not intended behavior. It certainly won't work properly outside of the shared filesystem backends.

I'd encourage you to participate in the discussion of the new [Directory type](https://github.com/openwdl/wdl/pull/241) instead
