### ISSUE TITLE
Some aborted workflows still have "running" subworkflows 

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#3654]
A few workflows that we aborted in Cromwell-as-a-Service have the status "Aborted" (e.g. "429e0aaf-c429-4438-a12d-734f1f444801") but the subworkflow that was running when the parent workflow was aborted is still in the "running" status. When trying to abort the subworkflow that is still running ("34074359-f8ed-4402-ba65-c92ab550e999"), I see the error:

```
{
  "status": "error",
  "message": "Couldn't abort 34074359-f8ed-4402-ba65-c92ab550e999 because no workflow with that ID is in progress"
}
```

It looks like Cromwell thinks the workflow is not running, but it's metadata says that it is.

**Comment by kshakir** [comment]
Possibly an extension of earlier PRs:
- https://github.com/broadinstitute/cromwell/pull/3260
- https://github.com/broadinstitute/cromwell/pull/2808

https://github.com/broadinstitute/cromwell/issues/3259#issuecomment-367435337 may also be related.

**Comment by samanehsan** [comment]
Mint team just noticed a similar issue for a few of our workflows, where the workflow status in Cromwell is "running" but the VM instance is no longer running. These specific workflows were "stuck" on the first task and did not start any subworkflows. When trying to abort the workflow, I get the following error: 

```
{
  "status": "error",
  "message": "Couldn't abort 467b64cc-9aa4-4eaf-85ef-16ed4d540d4c because no workflow with that ID is in progress"
}
```

**Comment by ruchim** [comment]
@samanehsan -- do you continue to see this issue with newer versions of Cromwell?

**Comment by samanehsan** [comment]
I haven't seen this recently @ruchim

**Comment by gemmalam** [comment]
Thank you @samanehsan I am going to close this for now and we can re-open if necessary. This ticket has been moved to our new Jira board, too :) https://broadworkbench.atlassian.net/browse/BA-3654
