### ISSUE TITLE
Home Override set to invalid value (Cromwell V31)

### ISSUE THREAD

**Issue by patmagee** [broadinstitute/cromwell#3656]
Cromwell Appears to be setting the HOME Override in a really really wonky way that completely breaks several tools. Additionally the initial `$HOME` value is being set to `/root` as opposed to the `/cromwell_root`. I am not sure if that is by design or if that is a slight oversight. This bug however effectually renders GenomicsDBImport useless unless the user once again overrides the `$HOME` variable

the offending line in the `exec.sh` looks like the following:
```bash
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME"

```

IN previous versions of cromwell (v29) this Home override did not exist

```bash
tmpDir=$(mktemp -d /cromwell_root/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir
```

**Comment by mcovarr** [comment]
Yeah that's unfortunate, thanks for reporting it. 🙂 This was [fixed](https://github.com/broadinstitute/cromwell/issues/3421) on the 31_hotfix branch a couple of months ago. There's a corresponding 31-39223b8 image up on Docker Hub but GitHub doesn't seem to have 31.1. For now you could use the Docker image or build from the 31_hotfix branch, I'll try to update GitHub with 31.1 this week.
