### ISSUE TITLE
WES to Cromwell API Conversions

### ISSUE THREAD

**Issue by salonishah11** [broadinstitute/cromwell#3672]
The WES to Cromwell Shim (wes2cromwell) is being built to demonstrate use of Cromwell through the GA4GH-specified WES interface. The shim is an independent executable that provides the WES REST API and calls the Cromwell REST API to perform the workflow operations.

WES client ⇒ wes2cromwell ⇒ Cromwell

**Comment by gemmalam** [comment]
New ticket to be created for part 2.
