### ISSUE TITLE
SGE default config redirects stdout,stderr to the same file twice

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/cromwell#3705]
https://github.com/broadinstitute/cromwell/blob/215cca97e6efafa7406fd89b38e21a39ce2d0d4e/cromwell.examples.conf#L440

It seems like the default configuration sends the stdout and stderr to the same filenames twice. In the config above, qsub is called with -o EG:
```e1bd0801-52c1-445c-8513-72e9872a0c7d/call-thing/execution/stdout```

In the script that will be executed on the node, there is some shenanigans:
```
(
cd .../e1bd0801-52c1-445c-8513-72e9872a0c7d/call-thing/execution


bla bla bla my command invocation
)  > >(tee '.../e1bd0801-52c1-445c-8513-72e9872a0c7d/call-thing/execution/stdout') 2> >(tee '.../e1bd0801-52c1-445c-8513-72e9872a0c7d/call-thing/execution/stderr' >&2)
```

Those 'tees' are generated by cromwell somewhere, I do not know if the config has control of that. I don't know the details of what will happen, but I do not think it will be healthy. I smell race conditions. I came across this trying to debug missing log data when SGE aborts a job.

**Comment by EvanTheB** [comment]
I have confirmed and worked-around by changing the configuration -o and -e parameters to 
```
-o ${out}.cromwell
-e ${err}.cromwell
```
identical duplicated files are now written to the work directory. (Identical except in the case of error, which is when I need these files anyway). My request is to remove the >(tee) lines, but I understand they probably exist to serve some other backend. The ability to turn them off would be appreciated.

**Comment by mcovarr** [comment]
Thanks for reporting this, you're right that those files should not have the same name. The files within the script are meant to capture the stdout and stderr of the user command only and are required for both WDL and CWL support. The files on the `qsub` command line are meant to capture all stdout and stderr including those log messages. The structure of the script has changed somewhat with Cromwell 32 but I suspect this problem still exists so we'll look at making a fix.

**Comment by EvanTheB** [comment]
If it is intended that the `qsub` files also capture the `command` output, then I think the only 'bug' is the default configuration and docs.

**Comment by mcovarr** [comment]
There's certainly an issue with config and docs, and now that I'm thinking about this more it's possible that with a recent bug fix we might be able to do away with the tee and keep the command stdout/err out of the qsub stdout/err. I'll look into this further.

**Comment by ruchim** [comment]
@EvanTheB thanks for reporting this! We're planning on pushing out some fixes in the next version, but let us know if that's not enough.

**Comment by EvanTheB** [comment]
thanks guys
