### ISSUE TITLE
CWL parameter reference string interpolation should be JSON, not YAML

### ISSUE THREAD

**Issue by mr-c** [broadinstitute/cromwell#3710]
From https://www.commonwl.org/v1.0/CommandLineTool.html#Parameter_references
>If the value of a field has non-whitespace leading or trailing characters around a parameter reference, it is subject to string interpolation. The effective value of the field is a string containing the leading characters, followed by the string value of the parameter reference, followed by the trailing characters. The string value of the parameter reference is its textual **JSON** representation with the following rules:
> 
> * Leading and trailing quotes are stripped from strings
> * Objects entries are sorted by key
>
> Multiple parameter references may appear in a single field. This case must be treated as a string interpolation. After interpolating the first parameter reference, interpolation must be recursively applied to the trailing characters to yield the final string value.

Test code: `runtime-dump.cwl`
``` cwl
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs: []
arguments: [ '{"runtime":$(runtime)}' ]
stdout: runtime.json
outputs:
  runtime: stdout
```
Example contents of the generated `runtime.json` (linewrapped for readability):
``` json
{"runtime":object {ram: 4, cores: 1, tmpdir: "/home/mcrusoe/src/cromwell/cromwell-executions/c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/c4e0e9bd-432a-4182-93dc-e842171dde6e/call-c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/tmp.095e5005",
outdir: "/home/mcrusoe/src/cromwell/cromwell-executions/c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/c4e0e9bd-432a-4182-93dc-e842171dde6e/call-c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/execution",
outdirSize: 2147483647, tmpdirSize: 2147483647}}
```
Corrected version of the generated `runtime.json`:
1. No `output ` prefix
2. JSON, not YAML: key names are in quotes
3. Objects entries are sorted by key
``` json
{"runtime":{"cores": 1, "outdir": "/home/mcrusoe/src/cromwell/cromwell-executions/c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/c4e0e9bd-432a-4182-93dc-e842171dde6e/call-c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/execution",
"outdirSize": 2147483647, "ram": 4, "tmpdir": "/home/mcrusoe/src/cromwell/cromwell-executions/c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/c4e0e9bd-432a-4182-93dc-e842171dde6e/call-c4e0e9bd-432a-4182-93dc-e842171dde6e.cwl/tmp.095e5005",
"tmpdirSize": 2147483647}}
```

This was discovered by a new conformance test: https://github.com/common-workflow-language/common-workflow-language/pull/706

**Comment by mr-c** [comment]
For completeness sake, the same issue occurs with `arguments: [ '{"inputs":$(inputs)}' ]`.

Interestingly `argument: [ '{"self":$(self)}' ]` works, but only because `null` is represented the same way in YAML and JSON. I would guess that if this was tested in a context where `self` wasn't null then it could have the same issue.

**Comment by EvanTheB** [comment]
#3487
