### ISSUE TITLE
Disable /stats endpoint

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3713]
specifically /engine/v1/stats

**Comment by danbills** [comment]
@hjfbynara Can we configure apache to disable this endpoint in production as a stopgap?

**Comment by danbills** [comment]
@ktibbett is green team using /stats for anything meaningful?

**Comment by hjfbynara** [comment]
From a technical perspective - sure likely possible.  My question is what do you want requests to that URL to return?  400,404, 50X?  

The biggest challenge is how to make the change such that it does not break everything else, the current proxy setup is pretty simple ( / (slash - which is where /engine falls under) does one thing, /api does another).  This will require adding a 3rd option around /engine/v1/stats - likely something with mod_rewrite.

Will take me a bit to work through a workable config

**Comment by hjfbynara** [comment]
fwiw - green team currently run their own cromwell instances - so they are not currently impacted by anything we do on WB prod for their pipelines.  Plus they generally are not as aggressive at taking newer cromwell versions - so even if you disable (remove) that endpoint they would likely not see the results for quite a bit.

**Comment by ruchim** [comment]
Completed by https://github.com/broadinstitute/cromwell/pull/3985
