### ISSUE TITLE
output path based on input path, causes incorrect rerun of job

### ISSUE THREAD

**Issue by DavyCats** [broadinstitute/cromwell#3717]
When using call-caching using a MySQL database, one of my jobs gets incorrectly rerun. It finishes successfully on the first run, and it's output isn't deleted or changed afterwards.
This happens in the `samtoolsIndex` call in this workflow: https://github.com/biowdl/aligning/tree/BIOWDL-25 which is run as a subworkflow of this one: https://github.com/biowdl/RNA-seq

I noticed that the command which is run on the rerun is different from the one during the initial run.
The initial run produces this command:
```
samtools index /exports/sasc/biowdl-testing/src/04_RNA-seq/cromwell-executions/pipeline/257197fe-a034-4c51-addc-3dc47564b967/call-sample/shard-0/sample/0e4e2e8d-d042-4907-9fb5-1d4f894f8366/call-library/shard-0/library/d995de1f-ecc6-4034-b35b-a860506821ff/call-starAlignment/AlignStar/d339740c-c1be-44ae-b4dd-8db2b47237c7/call-samtoolsIndex/inputs/exports/sasc/biowdl-testing/analysis/04_RNA-seq/samples/S1/lib_lib1/star/S1-lib1.Aligned.sortedByCoord.out.bam /exports/sasc/biowdl-testing/analysis/04_RNA-seq/samples/S1/lib_lib1/star/S1-lib1.Aligned.sortedByCoord.out.bam.bai
```
The rerun uses this:
```
samtools index /exports/sasc/biowdl-testing/src/04_RNA-seq/cromwell-executions/pipeline/14df3e76-ea79-4423-bfa2-1198de69cd1b/call-sample/shard-0/sample/0380d883-7bc4-4ef5-ac60-b3bbee90e53d/call-library/shard-0/library/c6c844c8-6e18-44ac-9cff-01a9da900159/call-starAlignment/AlignStar/bb11fd8a-33f9-4343-bf4b-bf397e063ecc/call-samtoolsIndex/inputs/exports/sasc/biowdl-testing/src/04_RNA-seq/cromwell-executions/pipeline/14df3e76-ea79-4423-bfa2-1198de69cd1b/call-sample/shard-0/sample/0380d883-7bc4-4ef5-ac60-b3bbee90e53d/call-library/shard-0/library/c6c844c8-6e18-44ac-9cff-01a9da900159/call-starAlignment/AlignStar/bb11fd8a-33f9-4343-bf4b-bf397e063ecc/call-star/analysis/04_RNA-seq/samples/S1/lib_lib1/star/S1-lib1.Aligned.sortedByCoord.out.bam /exports/sasc/biowdl-testing/src/04_RNA-seq/cromwell-executions/pipeline/14df3e76-ea79-4423-bfa2-1198de69cd1b/call-sample/shard-0/sample/0380d883-7bc4-4ef5-ac60-b3bbee90e53d/call-library/shard-0/library/c6c844c8-6e18-44ac-9cff-01a9da900159/call-starAlignment/AlignStar/bb11fd8a-33f9-4343-bf4b-bf397e063ecc/call-star/analysis/04_RNA-seq/samples/S1/lib_lib1/star/S1-lib1.Aligned.sortedByCoord.out.bam.bai
```
The second argument changes from the intended path to a path inside of the execution folder.

It looks like the output from the preceding mapping job gets linked to in the execution folder after restarting the workflow. Which is used as output for that job(?). This output `File` is used to determine what the name for the output of the indexing call is. Which is now different because it now points at the link in the execution folder, rather than the actual output the mapping job produced. As such the expected output doesn't exist and the job gets rerun. 
Am I correct in these statements? If so, is there a way this can be avoided? (ie. Is there a way the original output path can be remembered between restarts?)

**Comment by Horneth** [comment]
Hi thanks for reporting this issue, could you post your Cromwell configuration ? Specifically the [call caching part of the backend configuration](https://github.com/broadinstitute/cromwell/blob/cea07d69919a609362d2e374888f9ed8c4220564/cromwell.examples.conf#L332) (if any)

**Comment by DavyCats** [comment]
I have to note that I didn't make this configuration (@rhpvorderman will know more about this)
This is in the backend section:
```
caching {
  duplication-strategy: [ "soft-link", "copy", "hard-link" ]
  hashing-strategy: "file"
}
```
This is on the top level:
```
call-caching {
  enabled = true
  invalidate-bad-cache-results = true
}
```

**Comment by rhpvorderman** [comment]
The entire configuration here.
https://gist.github.com/rhpvorderman/cd91d3356e3fb460df09b0953c31eadb

**Comment by ruchim** [comment]
@rhpvorderman @DavyCats -- did `mergeLibraries` cache? Would you mind posting the outputs of that task from the first/second run?

**Comment by DavyCats** [comment]
@ruchim `mergeLibraries` would be run after the indexing step which is not getting call-cached, so no it would not get cached (or at least it will get rerun). I assume you're asking about this call because its output is given to the `mergedIndex` call. This is a different indexing step from the one I was referring to (`samtoolsIndex`  in https://github.com/biowdl/aligning/tree/BIOWDL-25).

Actually, `mergeLibraries` doesn't get run at all, because there is only one bam file (notice the if statement surrounding the call). `linkBam` is called instead at this point.

If you're wondering about the input for the `samtoolsIndex` call, yes that call (`star`) gets cached.

**Comment by mcovarr** [comment]
I think the problem might be that `bamIndexPath` is an [optional String](https://github.com/biowdl/tasks/blob/d8fd75696ef2c04d0cc2876e77b38e80e0c37e6d/samtools.wdl#L4) whose value will vary depending on the path to the index file rather than its content. I think this should be a File type instead.

**Comment by DavyCats** [comment]
@mcovarr It's not a file at the time the task is called. It's a path to the file which will be created by the task. So, (correct me if I'm wrong here) the workflow would fail if it were of type File, because the file doesn't exist.

**Comment by mcovarr** [comment]
Perhaps the index task can calculate the path to the BAI itself rather than taking an unstable String path as an input. The index task could then return the BAI it creates as a File.

**Comment by DavyCats** [comment]
The output which is produced by STAR might be named differently depending on the settings used. Currently this isn't supported yet in this task, but it might be in the future. Because of this I didn't want to make any assumptions on the naming of these files, in order to maintain flexibility in the use of these settings.

After some consideration, though, for this specific pipeline I suppose these settings won't (or shouldn't) be changed. So, for now: Yes, the path to the BAI can be calculated in a more stable way.

It still seems a bit awkward, though, that a rerun might try to produce a different file from the original run, but I'll close this for now.
