### ISSUE TITLE
Call caching doesn't work 

### ISSUE THREAD

**Issue by rogerzzw** [broadinstitute/cromwell#3740]
Hi, 
I understand cromwell that call caching will copy whatever it finished last time to current run if I keep the script unchanged. However, it seems to be not that case to me.

I have run Mutect2, one of the GATK tool on fireclouds. one of the major step is it splits to 50 jobs based on some genomic interval and runs separately on different VM. Most jobs are successful done but a few fail because of some transient error. Once I relanuch the job, it splits to 50 jobs based on the same interval, but it is still running all 50 jobs simultaneously without knowing some of the jobs have run successfully last time (of course, I enabled call caching). So I ends up spending more and more money and time on it.

Could you please advise on this ?

Thanks

**Comment by mcovarr** [comment]
Hi

Call caching is turned off by default, did you turn it on in your configuration? Also call caching will require the use of a MySQL-like database to preserve caching information between runs.

Thanks

**Comment by geoffjentry** [comment]
Hi @rogerzzw - please ask Firecloud support questions in the Firecloud support forum: https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team
