### ISSUE TITLE
Custom Localization for dos

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3759]
The use case here is that a user wants to pass in a dos url, with a specific docker to handle the localization of that docker. Cromwell's job is to put both those pieces together to allow for custom localization in addition to the default localization performed on the filesystems declared in the Cromwell config.

Requirements:
1) A new option that allows for one to pass in the custom localization docker (globally or per-workflow)
2) Parse and accept dos urls as task inputs
3) Feed the dos url + the final destination for that file to the docker 
4) Fail gracefully if any functions (read_lines, size, etc) are performed on this input type, not required for this stage.

**Comment by ruchim** [comment]
@geoffjentry is it appropriate to hash the url itself for caching purposes for this stage?

**Comment by geoffjentry** [comment]
IMO yes as that's the stated purpose of DOS, to provide access to the **same** file in **different** locations. 

Since this level of work is really for the blue box stuff and that's not **quite** the same as DOS yet I'd check with the relevant folks on our side and in particular try to have them to circulate that question among their larger group.

**Comment by ruchim** [comment]
@dvoet Is it acceptable for Cromwell to hash the dos url string itself for the purposes of call caching? Would this ever be different in the future?

**Comment by dvoet** [comment]
I think it is acceptable for the now. There is still discussion over the
final format of the uri so the future, as usual, is a little murky. If you
want to be fancy you can resolve the uri and grab the hash.

**Comment by ruchim** [comment]
If Cromwell were to resolve the URI -- it would mean Cromwell can talk to Bond & Martha?

**Comment by geoffjentry** [comment]
You mean for things like size()?

**Comment by dvoet** [comment]
We should talk
