### ISSUE TITLE
Womtool validate does not acept wdl files with only tasks

### ISSUE THREAD

**Issue by ffinfo** [broadinstitute/cromwell#3762]
Since version 32 Womtool validate give this error on wdl file without a workflow: 
`Namespace does not have a local workflow to run`

Is this required by spec? Would be better to still accept this for reusable tasks like this: https://github.com/biowdl/tasks

**Comment by geoffjentry** [comment]
It's not required by the spec per se, but it is required in order to be runnable so presumably what womtool is doing is validating "can this be run" instead of "is this correct syntax".

@cjllanwarne Something to consider, those two things aren't **quite** the same.

**Comment by ffinfo** [comment]
For us there are just 2 workarounds:
- stay with womtools 31 (not preferred)
- Make a dummy workflow (also not preferred)

**Comment by cjllanwarne** [comment]
Interesting - I thought it would only push as far as "can I execute it" if an inputs file is provided, but that appears to not be true.

Thanks for raising this - we should be able to get a fix in for the Cromwell 33 release which should be sometime next week.

**Comment by cjllanwarne** [comment]
PR now in for review #3772 - I can add another workaround in the meantime, since apparently this was only affecting the draft-2 language factory:

* upgrade to WDL 1.0

However, since an upgrade script is also coming in as part of Cromwell 33, maybe one of your other workarounds is less effort in the short term?

**Comment by ffinfo** [comment]
@cjllanwarne Thanks for fixing this so fast. For validation I just skip version 32 ;) When is 33 planned?

We want to upgrade to wdl 1.0 anyway but first need to complete our testing framework around wdl, see also https://github.com/biopet/biowdl-test-utils (library) and https://github.com/biowdl/QC (real pipeline with testing)

**Comment by tomkinsc** [comment]
@cjllanwarne: I also encountered this issue. Until the mentioned upgrade script is released, is there information available highlighting the changes necessary to migrate from draft 3 (or 2/1) to WDL 1.0? Any sort of guidance about what's different between the versions would be helpful. Doing a visual diff of the `SPEC.md` files isn't ideal...

Somewhat related: Is there an estimate of when womtool will have `-imports` exposed as a parameter?
