### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by PeteClapham** [broadinstitute/cromwell#3791]
Hi,
I'm seeing a number of compilation errors with head dev etc. I've attached the output from debug.

Scala version
scala-2.12.0-1.noarch

Java version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

CentOS Linux release 7.5.1804 (Core)

Error output attached

Any thoughts ? Could be something obvious as I'm new to scala.
Thanks

[comp.log](https://github.com/broadinstitute/cromwell/files/2109138/comp.log)

**Comment by mcovarr** [comment]
At first glance I'm not aware of anyone on the Cromwell team trying to compile with Java 10. 🙂 Can you try with Java 8 instead?

**Comment by PeteClapham** [comment]
and that was the magic. 
Many thanks.
Pete
