### ISSUE TITLE
Requester Pays v2

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3799]

**Comment by danbills** [comment]
from Aaron Kemp of Google pipelines, emphasis mine:

"In the short term, I think the original option we discussed is the best: try without, if it fails, try with.  **You will not be billed for the failed request**."

**Comment by danbills** [comment]
understanding that we are going to proceed w/ cached API calls approach.  Just noting that we are not billed for the failed request.

**Comment by Horneth** [comment]
There's also the possibility that GCS/gsutil get smarter w.r.t RP and would potentially make caching unnecessary

**Comment by danbills** [comment]
* It does seem simpler
* not 100% sure how it plays into generic impl
* I think gsutil is getting smarter soon per the hint we got
