### ISSUE TITLE
Add support for staging INPUTS/OUTPUTS from/to AWS S3

### ISSUE THREAD

**Issue by delagoya** [broadinstitute/cromwell#3804]
Functionality is needed to stage data files to/from S3 on a per-task level.

For the example WDL file:
```
task copy_file {
  String output_file
  File input_file

  command {
    cp  ${input_file} ${output_file}
  }
  runtime {
    docker: "ubuntu:latest"
  }
}

workflow wf_copy_file {
  call copy_file
}
```
and corresponding `inputs.json`

```json
{
  "wf_cop_file.copy_file.input_file": "s3://myBucket/hello.txt",
  "wf_cop_file.copy_file.output_file": "greetings.txt"
}
```

The workflow execution should be able to copy the input file from S3 to the working task directory, and copy the output file "greetings.txt" to the configured S3 bucket for writing logs and outputs. An example of files written to the output S3 bucket would be:

```
# $WF_ID is the workflow identifier (e.g. "E6D5143C-89BC-4823-AED7-2A6AE00A1C2B")
s3://cromwell-output-bucket/$WF_ID/copy_file/outputs/greetings.txt
s3://cromwell-output-bucket/$WF_ID/copy_file/wf_copy_file-rc.txt
s3://cromwell-output-bucket/$WF_ID/copy_file/wf_copy_file-stdout.txt
s3://cromwell-output-bucket/$WF_ID/copy_file/wf_copy_file-stderr.txt
```

**Comment by danbills** [comment]
@delagoya what about the privileged docker that's running other docker containers?  I.e. the phases of localization - command - delocalization.  Would be nice to spell that out in more detail

**Comment by danbills** [comment]
Just brain-dumping my understanding of the approach to get the convo started:

The idea as I understood it was to run an orchestrating docker with elevated privileges, which I'll call Orchestrator in a fit of creativity.

Orchestrator would kick off N number of localization commands to localize files onto the host.
  (N could be 1)  

Orchestrator runs exec.sh with files existing on host.

Orchestrator runs N de-localization commands.

--

## Idle Thoughts

I don't immediately recall why this had to be separate docker commands and not just scripts running before and after the main script.  

This is how GCP Papi v2 works, by chaining dockers together (I think some concept of fork() is supported too)

**Comment by delagoya** [comment]
@danbills The Orchestrator pattern as described above is what we discussed. 

Per your other questions, the answer is that AWS Batch does not take a array of arbitrary scripts as an option, nor can you override a Docker container's `ENTRY_POINT` to supply your own script if the entry point of the container has been changed from the default shell. You can only specify an array to pass into Docker daemon's `CMD`.

Speaking of default shells, the other arguments against a set of shell scripts is that it limits the set of containers that can be called from a WDL. For example, the current Cromwell scripts that are injected into the container assume Bash support, but by default Alpine Linux (and many containers that build off of it) do not have Bash installed. 

Most of the time the above two items are safe assumptions, but not always, hence the current plan to implement data staging via a sibling container approach similar to how CI systems are deployed today. For inspiration, I refer to [Dave Hein's excellent article on running sibling containers in lieu of docker-in-docker](https://www.develves.net/blogs/asd/2016-05-27-alternative-to-docker-in-docker/)

**Comment by elerch** [comment]
So, quick thoughts on this. +1 on @delagoya's sidecar container concept (with some concerns I'll mention below). When implementing #3835 I had this issue in mind as well, along with some thoughts on implementation.

My thought was to have a sidecar always running, using the [system events](https://docs.docker.com/engine/api/v1.37/#operation/SystemEvents) api to monitor for containers that have exited. At that time, it can [inspect the container](https://docs.docker.com/engine/api/v1.37/#operation/ContainerInspect), make sure it's a cromwell container, and use the volume information (in conjunction with the TASK_ID environment variable I'm setting) to find the local files and copy them out to s3.

Something to consider that I don't see discussed yet on this thread: A sidecar approach requires the sidecar to have fairly permissive access to S3. On the positive side, this does alleviate the need for S3 permissions on the container running the task.

**Comment by geoffjentry** [comment]
@delagoya as of not too long ago you can override the default bash usage in favor of the shell of your choice

**Comment by delagoya** [comment]
A system event monitoring and interrupt system seems way complex to me than implementing some conventions that leverage a standard task definition.  At the point of submitting a process to Batch, you should already have all of the information needed to run a task, and can pass this along in a standard way to the standard task definition. This is the same information that is used to create the current job wrapping script. 

FYI - the Funnel worker that is wrapped in `batch-task-runner` is modified to run stand-alone from a input JSON file, as opposed to communicating back to a Funnel server for task scheduling and distribution. The modified worker consumes the return codes passes the result back through it's own process and back to Batch. In this way, the sibling process is not hidden from Batch (or Cromwell).

**Comment by elerch** [comment]
Closing pending pr #3948 and #3934

**Comment by gemmalam** [comment]
Hi Emil,
Reopening this ticket to connect with the associated PR. Once the PR is merged, this issue will automatically close.

**Comment by delagoya** [comment]
Quick question, instead of a docker container, can this be a daemon process that runs on instance start before being added to the AWS Batch ECS cluster? E.g. make it a part of the custom compute resource AMI.

**Comment by elerch** [comment]
@delagoya  The plan is to bake this into an AMI similar to the way ecs agent is installed. It will be a container with a always-on restart policy. https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by brainstorm** [comment]
@elerch Careful with that `always-on` restart policy for docker. In my experience, it did not re-read `env-files` (in my case those env vars are sitting on the host's `/dev/defaults/ecs`). I expected SIGHUP-like behavior when changing ecs-agent attributes like `ECS_CLUSTER`, i.e:

https://github.com/umccr/umccrise/blob/master/deploy/roles/brainstorm.umccrise-docker/files/bootstrap_instance.sh#L39

Instead, I had to resort to a systemd service that re-runs the ecs-agent docker container:

https://github.com/umccr/umccrise/blob/master/deploy/roles/brainstorm.ecs-agent/tasks/main.yml#L75
