### ISSUE TITLE
Support for GS as resolved URL

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3818]

**Comment by geoffjentry** [comment]
@kshakir @salonishah11 Does this look like it belongs in the blue box milestone?

**Comment by salonishah11** [comment]
I somehow feel that this ticket is what I am currently working on, the ammonite script which resolves DOS url and localizes the file (#3834). I had created a new ticket because I didn't know this one existed.

**Comment by geoffjentry** [comment]
:+1:
