### ISSUE TITLE
[docs] Edit on Github 404

### ISSUE THREAD

**Issue by vsoch** [broadinstitute/cromwell#3862]
Hi cromwell! The "edit on Github" page is broken in your docs, the one in the upper right here:

![image](https://user-images.githubusercontent.com/814322/42294715-f98caf46-7f97-11e8-9d5c-88d960d6f211.png)

![image](https://user-images.githubusercontent.com/814322/42294726-0f7cfd2e-7f98-11e8-8f8f-dd92c5d9d383.png)
The url it tries to go to is:

 https://github.com/broadinstitute/cromwell/tree/develop/docs/edit/master/docs/index.md

and the extra bit seems to be the repetition of a branch (master and develop). It should be something like:

https://github.com/broadinstitute/cromwell/edit/develop/docs/index.md

Even just a link to the Github repo (without the edit page) would be useful, this is the link I was looking for (and could have gotten there from the edit button).

Fantastic pig, btw! :)

**Comment by geoffjentry** [comment]
Thanks @vsoch ! This should be fixed by #3866

**Comment by geoffjentry** [comment]
@vsoch Just a heads up, @katevoss did point out that her fix will be on the `/develop` version of RTD shortly but won't be on `/stable` until the next Cromwell release

**Comment by vsoch** [comment]
okay awesome, thanks muchly! I have seen readthedocs have (rather silent) build errors, so it's very good to have a develop --> stable branch. It will be muchly appreciated as I read about cromwell
