### ISSUE TITLE
Report this bug! Static validation failed.

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/cromwell#3863]
```
{
    "causedBy": [],
    "message": "Bad output 'GatherVcfs.output_vcf_index': No such field 'tbi' on type String. Report this bug! Static validation failed."
}
```

from wdl snippet: 
```
output {
    File output_vcf = "~{output_vcf_filename}"
    File output_vcf_index = "~{output_vcf_filename}".tbi
  }
```

**Comment by Horneth** [comment]
I think you might want 

```wdl
File output_vcf_index = "~{output_vcf_filename}.tbi"
```

or even

```wdl
File output_vcf_index = output_vcf_filename + ".tbi"
```

**Comment by cjllanwarne** [comment]
Thanks! I think that the `"Report this Bug"` is *probably* a typo as long as the static validation in `womtool validate` *does* fail for this workflow.

I this workflow started, ran a few jobs and **then** this happened, we should fix that ASAP.

**Comment by EvanTheB** [comment]
Hello, I posted this bug because the validator does NOT do a check. IE I run the validator on every WDL I submit, but the validator did not catch this error. The error happens, as you said, after many tasks have run already.
[wot.wdl.txt](https://github.com/broadinstitute/cromwell/files/2168605/wot.wdl.txt)

**Comment by cjllanwarne** [comment]
@EvanTheB aha!

There must be something different between our test cases - the most obvious thing I can see is that your expression is in the task definition vs mine in the workflow definition. I'll investigate this now.

**Comment by cjllanwarne** [comment]
@EvanTheB I've updated my PR with a fix and a new test for this problem in task outputs. Thanks again for the bug report!
