### ISSUE TITLE
Query endpoint `includeSubworkflows` parameter database error

### ISSUE THREAD

**Issue by rexwangcc** [broadinstitute/cromwell#3873]
On Cromwell version, "34-5156b78-SNAP", when making a request to the query endpoint that includes the `"includeSubworkflows": "false"` parameter, the database will throw an error if the query matches ~1000 results. 

Example POST request:
```
curl -X POST "https://cromwell.caas-dev.broadinstitute.org/api/workflows/v1/query" -H "accept: application/json" -H "authorization: Bearer XXXXX" -H "Content-Type: application/json" -d "[ { \"status\": \"Failed\", \"includeSubworkflows\": \"false\" }]"
```
Error message:
```
{
  "status": "fail",
  "message": "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@27386688 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@2e52a800[Running, pool size = 200, active threads = 200, queued tasks = 999, completed tasks = 16375]"
}
```
This error is very similar to the other issue: https://github.com/broadinstitute/cromwell/issues/3115
but `includeSubworkflows` shouldn't limit the number of results the `/query` endpoint can handle.

**Comment by cjllanwarne** [comment]
This problem no longer happens but the related issues #3115 and #4561 may still be problems.

**Comment by rexwangcc** [comment]
Sorry @cjllanwarne , I just tested with:
```
[
  {
    "includeSubworkflows": "false"
  }
]
``` on 
https://cromwell.caas-prod.broadinstitute.org which has version `36-fde91e6`, the problem appeared to me again:
```
{
  "status": "fail",
  "message": "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@23304acb rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@233013e3[Running, pool size = 200, active threads = 200, queued tasks = 1000, completed tasks = 2178366]"
}
```
Maybe the query is too ambitious? I should use pagination or more restrictive query instead?
