### ISSUE TITLE
Pagination breaks with query filtering 

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3884]
When one uses certain filtering on the query endpoint (such as “excludeSubworkflows” and exclude labels)—the pagination doesn’t reflect the filtered response. It almost seems like pagination is done upstream of the final response. 

ideally pagination would be accurate upon any request made to the query endpoint.

**Comment by cjllanwarne** [comment]
Is this the same as #3878 ?

**Comment by ruchim** [comment]
YES! I shall close as dup--thanks Chris!
