### ISSUE TITLE
Update google chart js codes

### ISSUE THREAD

**Issue by zhanxw** [broadinstitute/cromwell#3887]
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    

I am proposing to update workflow timing web page as the google timeline chart codes have been revised.

Here the current code uses 'http://www.google.com/jsapi' (https://github.com/broadinstitute/cromwell/blob/c8bf8fdc51e2df19d8e8a3d066acc64f588f1b1c/engine/src/main/resources/workflowTimings/workflowTimings.html#L4). It is not suggested by Google Chart documentation (https://developers.google.com/chart/interactive/docs/gallery/timeline), and this URL is blocked by our firewall.

In order to use cromwell timing API for myself, I suggest to change relevant lines to:

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript">

        var parentWorkflowNames = [];
        var expandedParentWorkflows = [];
        var chartView;
        google.charts.load('current', {packages: ['timeline']});
     google.charts.setOnLoadCallback(drawChart);

Can you update cromwell source codes to do that? Or please let me know if you need a pull request.

Thanks.

**Comment by geoffjentry** [comment]
Hi @zhanxw - yeah, if you're willing to submit a PR that'd be great
