### ISSUE TITLE
Feature Request: Ability to add custom labels to Google VMs

### ISSUE THREAD

**Issue by agraubert** [broadinstitute/cromwell#3900]
[WDL Forums discussion](https://gatkforums.broadinstitute.org/wdl/discussion/12295/how-to-submit-labels-to-gcs-backend)

In #3233 the ability to customize GCS VM labels was removed. My understanding was that this was to lift Google's restrictions on VM labels from the workflow labels. However, I would benefit greatly from the ability to optionally supply labels to each VM. 

Specifically, I'm operating my own fork of the [cromwell_on_google](https://github.com/openwdl/wdl/tree/master/runners/cromwell_on_google/wdl_runner) tool which I use to spin up large batches of VMs to execute workflows. However, it's hard to pick out individual VMs from the compute api console, especially when running multiple unrelated submissions.

My tool creates one Cromwell VM for each submission, which then (via the Google JES backend) starts new VMs for each workflow. To distinguish and filter the VMs in the console, I want to attach two labels to every vm:

* `execution-role` : A label to distinguish between Cromwell VMs and worker VMs
* `submission-id` : A label with submission IDs generated by my tool to distinguish between VMs working on different submissions

The `cromwell-workflow-id` label is helpful, but not convenient if I wish to operate on all VMs working on a single submission _en masse_.

The Google genomics API allows me to set `execution-role=Cromwell` and `submission-id={ID}` labels on the Cromwell VMs. However, without Cromwell support, I can't set `execution-role=Worker` and `submission-id={ID}` labels on the workers at creation time. 

I'm currently pursuing a workaround to manually set these labels after creation, but having control via Cromwell would be preferable. 

Thanks!

**Comment by geoffjentry** [comment]
Hi @agraubert - one thing we discussed when we did that was to simply provide another concept altogether (because cromwell labels and google labels were 2 concepts shoehorned together) and then removed them completely as the only known users didn't need them.

If we bring them back as they were before but **not** as standard cromwell labels, would this still work for you?

**Comment by agraubert** [comment]
Absolutely! I just need the ability to apply custom labels to the VMs, and I don't really need the labels to be attached to the workflows themselves

**Comment by geoffjentry** [comment]
Perfect, thanks @agraubert

**Comment by dplichta** [comment]
I want to thumb up this development, if I understood it correctly. 

In my lab we have multiple users submitting workflows individually into the common project space in the google cloud, hence the VMs overview becomes useless due to many gpp-XXX processes. My question, @geoffjentry, is whether these new labels will allow marking specific VMs by, at least, user ID?

**Comment by geoffjentry** [comment]
@dplichta google is highly opinionated about the structure of keys and values in their labels, so as long as it doesn't run afoul of that, sure.

**Comment by agraubert** [comment]
Can you shuffle the labels again, please? Just so that I know this still isn't being worked on

**Comment by ruchim** [comment]
Hey @agraubert, the best way to know that a ticket will be worked on is when the pipeline for it changes to backlog bucket. 

Just as an FYI, we are focused on scale improvements and small bug fixes for the near future. Out of curiosity, are you interested in contributing this feature yourself, especially with the guidance of a Cromwell developer? Thanks!

**Comment by agraubert** [comment]
Scala is very much not in my wheelhouse, so unfortunately this is not a task I'd be comfortable taking on. But I really do appreciate the status update
