### ISSUE TITLE
jar file doubled in size between 32 and 33.1?

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [broadinstitute/cromwell#3909]
I just noticed that the size of the cromwell .jar file went up from 123M to 206M when upgrading to version 33.1. Is this intended or did something go wrong with building the .jar file?

```
$ du -sh cromwell-32.jar cromwell-33.1.jar 
123M	cromwell-32.jar
206M	cromwell-33.1.jar
```

**Comment by kshakir** [comment]
The AWS dependencies needs to be pruned.

The entire known universe of AWS libraries [were pulled in](https://github.com/broadinstitute/cromwell/blob/9bee537c5f6a9ff4e8597f75b6844c0eaee721cc/project/Dependencies.scala#L230) during the work-in-progress towards a new backend for cromwell.

The image below was produced using [GrandPerspective](http://grandperspectiv.sourceforge.net/) on the expanded cromwell 33 jar. It shows the amount of AWS libraries that have been assembled transitively by that one `aws-sdk-java` [blanket](https://mvnrepository.com/artifact/software.amazon.awssdk/aws-sdk-java/2.0.0-preview-9) dependency.

![cromwell_expanded](https://user-images.githubusercontent.com/791985/43986825-3ccde314-9ce5-11e8-8260-c9bbb66d3623.png)

The dependencies should be slimmed down to only the required libs.
We don't need to have AWS [Route53](https://aws.amazon.com/route53/) etc. zipped in the jar to run workflows on the upcoming backend.

**Comment by geoffjentry** [comment]
The jar size isn't viewed to be an issue. We can definitely trim dependencies going forward, but closing this for now
