### ISSUE TITLE
TESK Backend support

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3928]

**Comment by Myskmadra** [comment]
Hey,

I am trying to use TESK as a backend for a cromwell server (version 51) just running a simple task to test if it works (echo "Hello World" using an alpine image) and it does not work. TESK receives the input from the server with the correct syntax, however, the script files and all other files generated by cromwell are pointing to a local directory which TESK does not have (TESK is running in a kubernetes cluster). Maybe I am missing something but I this behaviour with creating local files does not work with a kubernetes cluster. Can I change it by setting the config differently or what is a possible solution? Is there anyone who is experiences with Cromwell-TESK?
