### ISSUE TITLE
Call Caching and backend names

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#3955]
- People should be able to change the backend name in the config without losing their call cache
- People should (probably?) be able to upgrade from PAPI1 to PAPI2 without losing their call cache

**Comment by geoffjentry** [comment]
Not sure I agree with he first poinT. I was thinking about it earlier and the answer is not clear to me.

**Comment by geoffjentry** [comment]
Also I definitely don’t agree off the cuff with he second point

**Comment by cjllanwarne** [comment]
What if the emphasis is on "be able to" as opposed to "this always happens"?
