### ISSUE TITLE
stderr/out aren't available during runs and are sometimes in application/octet-stream

### ISSUE THREAD

**Issue by kyuksel** [broadinstitute/cromwell#3967]
From [a user's forum post](https://gatkforums.broadinstitute.org/firecloud/discussion/12577/stdout-stderr-output-in-bucket-does-not-seem-to-be-updated-while-task-is-running#latest):

1. `stderr` and `stdout` do not appear to show up until a workflow finishes. 
2. In some cases `stderr` and `stdout` are of type `application/octet-stream` rather than `text/plain`, not allowing the content to be viewable without downloading. 

I was able to see these by running a [five-dollar-genome-analysis-pipeline](https://portal.firecloud.org/#workspaces/fccredits-silver-pumpkin-7172/five-dollar-genome-analysis-pipeline_copy) as well.

**Comment by geoffjentry** [comment]
@ruchim @mcovarr is this complete?

**Comment by mcovarr** [comment]
The streaming is complete but I doubt the octet/stream bit is.

**Comment by mcovarr** [comment]
And I'm not 💯 the mime type is right in PAPI v2 either since they may both be using the same code.

**Comment by ruchim** [comment]
I'm closing this issue as the #1 has been addressed for PAPI v1 in Cromwell v34. Like Miguel said -- we're going to address #2 in PAPI v2, and I'll generate a separate ticket for that.
