### ISSUE TITLE
imported files in develop version expected to be at system root

### ISSUE THREAD

**Issue by DavyCats** [broadinstitute/cromwell#3986]
Imports of local files seem to be broken in the development version of cromwell. The paths to the imported wdl files seem to be expected to be absolute paths. Any relative path is treated as relative to the root directory of the system. 

For example:
In the following workflow, test.wdl is imported. If test.wdl is located in the same directory as this workflow it can't be found (`/home/<various directories>/test/test.wdl`), however, if test.wdl is located in the root directory it will be found (`/test.wdl`).
```
version 1.0

import "test.wdl" as test

workflow test2 {
    call test.sayHello as blah {
        input:
            name="Grog"
    }

    output {
        String out = blah.blah
    }
}
```
test.wdl looks like this:
```
version 1.0

task sayHello {
    input {
        String name
    }

    command {
        echo Hello, ~{name}
    }

    output {
        String blah = read_string(stdout())
    }
}
```
The following is mentioned in the printed output:
```
Failed to import 'test.wdl' (reason 1 of 2): Failed to resolve 'test.wdl' using resolver: 'relative to directory / (without escaping None)' (reason 1 of 1): Import file not found: test.wdl
Failed to import 'test.wdl' (reason 2 of 2): Failed to resolve 'test.wdl' using resolver: 'http importer' (reason 1 of 1): Cannot import 'test.wdl' relative to nothing
```
Looking at the cromwell source code I suspect the problem lies with the directory path being given to `DirectoryResolver` in `localFilesystemResolvers` ([this line](https://github.com/broadinstitute/cromwell/blob/develop/engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala#L271)).

**Comment by salonishah11** [comment]
Hi @DavyCats, thanks for reporting this! We will look into it.

**Comment by DavyCats** [comment]
@cjllanwarne The commit hash was 519708d9cafd4c4886d089f3cdf545879d81812c
I ran it in run mode, something along the lines of this: `java -jar ~/Desktop/cromwell-35-SNAPSHOT.jar run test2.wdl` (jar name not exact)
