### ISSUE TITLE
input definition for one call affects input definition for others

### ISSUE THREAD

**Issue by DavyCats** [broadinstitute/cromwell#3999]
Defining inputs in a call overwrites/affects inputs to other calls when these inputs have the same name. This happens in cromwell 34, as well as the develop version (9bee537). It happens for WDL version 1.0 and Biscayne, but not for draft-2.

example:
```
version 1.0
workflow test {
    String out = "hello"
    call echo1 { #Should run `echo hello1`, but runs `echo21` if run second
        input:
            out = out + "1"
    }
    call echo2 { #should run `echo hello2`, but runs `echo 12` if run second
        input:
            out = out + "2"
    }
}
task echo1 {
    input {
        String out
    }
    command {
        echo ~{out}
    }
}
task echo2 {
    input {
        String out
    }
    command {
        echo ~{out}
    }
}
```
I added the echo task twice to check if it might be caused by running the same task multiple times, but this also happens when it's two different tasks with equally named inputs.

Defining one or both inputs as variables before passing them to the call seems works as expected:
```
workflow test {
    String out = "hello"
    call echo1 { # runs `echo hello1`
        input:
            out = out + "1"
    }
    String out2 = out + "2"
    call echo2 { # runs `echo hello2`
        input:
            out = out2
    }
}
```

**Comment by rhpvorderman** [comment]
This also happened in my workflow. It worked fine until I switched to `version 1.0`

**Comment by aednichols** [comment]
Interesting find, thanks for reporting. I've also easily reproduced this on latest `develop`.

**Comment by aednichols** [comment]
`womtool womgraph` is pretty interesting here. Seems like all calls beyond the first are taking their `out` from the LHS of the previous call assignment, instead of the global `out`.

`input_overwriting.wdl`
```
version 1.0

workflow test {
    String out = "hello"
    call echo as a {
        input:
            out = out + "1"
    }
    call echo as b {
        input:
            out = out + "2"
    }
    call echo as c {
        input:
            out = out + "3"
    }
    call echo as d {
        input:
            out = out + "4"
    }
}
task echo {
    input {
        String out
    }
    command {
        echo ~{out}
    }
}
```
![input_overwriting](https://user-images.githubusercontent.com/1087943/44554203-0f18fd00-a6fe-11e8-86dd-8320a37c3a60.png)

---

`input_not_overwriting.wdl`
```
version 1.0

workflow test {
    String snout = "hello"
    call echo as a {
        input:
            out = snout + "1"
    }
    call echo as b {
        input:
            out = snout + "2"
    }
    call echo as c {
        input:
            out = snout + "3"
    }
    call echo as d {
        input:
            out = snout + "4"
    }
}
task echo {
    input {
        String out
    }
    command {
        echo ~{out} 
    }
}
```
![input_not_overwriting](https://user-images.githubusercontent.com/1087943/44554151-d4af6000-a6fd-11e8-888c-8ded8bd924c8.png)

**Comment by aednichols** [comment]
Discovered another lovely potentially-related bug while looking into this: https://github.com/broadinstitute/cromwell/issues/4048

**Comment by aednichols** [comment]
Maybe see also https://github.com/broadinstitute/cromwell/issues/3811

**Comment by aednichols** [comment]
@DavyCats the fix will be in the next release of Cromwell.

**Comment by DavyCats** [comment]
@aednichols Thanks!
