### ISSUE TITLE
Improve output of womtool validate

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4040]
Feedback from today's workshop: `womtool validate` uselessly prints a few newlines on successful exit.

Various workshop participants thought:
1. It should exit with no output to harmonize with Unix CLI tool conventions
2. It should confirm success in a way that is obvious to users who are e.g. biologists first, programmers second

Either would be an improvement over the current state.

cc @rmeffan @ndbolliger

**Comment by rsasch** [comment]
After discussion with @ruchim, the output of a successful validation will be `Success!`.
