### ISSUE TITLE
Failure to recognize variable declared in task call

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4048]
Example WDL taken directly from the spec: https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#workflow-level-resolution
```
version 1.0

workflow wf {
  input {
    String s = "wf_s"
    String t = "t"
  }
  call my_task {
    String s = "my_task_s"
    input: in0 = s+"-suffix", in1 = t+"-suffix"
  }
}
```
results in
```
ERROR: Unexpected symbol (line 9, col 5) when parsing 'call_body'.

Expected input, got "String".

    String s = "my_task_s"
    ^
```

**Comment by Horneth** [comment]
Oh wow I didn't even know that was allowed in the first place

**Comment by mcovarr** [comment]
Neither did I. That's pretty strange.

**Comment by geoffjentry** [comment]
After poking at this a bit, this looks oddly familiar as something which I recently discussed with someone (@cjllanwarne perhaps?) as being an ancient artifact (it dates to `draft-1`) that no one actually uses

**Comment by aednichols** [comment]
I hope we don’t have to support it because it would require a ton of rework given how the code currently works 🙂

**Comment by geoffjentry** [comment]
@aednichols bad news. Unless some enterprising soul goes and submits a PR to the WDL spec, not supporting it is kinda counter to our mantra that Cromwell will be 100% spec compliant

**Comment by aednichols** [comment]
That can be arranged...
