### ISSUE TITLE
No timeout on rc file

### ISSUE THREAD

**Issue by ffinfo** [broadinstitute/cromwell#4050]
Related maybe: https://github.com/broadinstitute/cromwell/issues/3905

When my job is killed by our cluster (SGE or Slurm) the rc file will not appear anymore. Cromwell then stay forever waiting on this file.
When manual writing this file (aka `echo "2" > rc`) cromwell does see this as a failed job.

I have tested this also on a Local backend but here the problem does not exists. I think this is because cromwell stays connected to the process.

I have tested cromwell 34 and the current develop branch (ce27a93).

For testing I have used this workflow:
```
version 1.0

workflow Test {
  input {
  }

  call Echo as echo {
    input:
  }

  output {
  }
}

task Echo {
  input {
  }

  command {
    # killing bash process
    kill -9 $$
    echo test
  }

  output {
  }
}
```

**Comment by ruchim** [comment]
@kshakir is there a configurable timeout for job completion in the SFS backends?

**Comment by ffinfo** [comment]
@ruchim and @kshakir: Any update on this? This is for our piplines a real blocker to bring our pipelines to production. See also https://github.com/biowdl

**Comment by ffinfo** [comment]
Fixed in https://github.com/broadinstitute/cromwell/pull/4112
