### ISSUE TITLE
Bad validation output: "MatchError: null"

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4081]
Based on this report on the forums: https://gatkforums.broadinstitute.org/wdl/discussion/12878/exception-in-thread-main-scala-matcherror-null-validating-my-wdl

In this case the mistake was using `if (is_exome !=) {` instead of `if (!is_exome)` - but that should be nicely turned into a reportable error... rather than throwing up some obtuse scala-internals error message.

**Comment by ruchim** [comment]
@cjllanwarne any sense if this is the same for draft-3

**Comment by cjllanwarne** [comment]
@ruchim good question! I'll try that out...
