### ISSUE TITLE
Can a function be executed after a command?

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/cromwell#4092]
I have a command that creates an output file, and prints the name of that file to a known file.

EG `./program` puts its output in 1234.txt, and prints '1234' into output_name.

I thought I could do this in my task:

```
command <<<
./program
>>>
String filename = read_string('output_name')
output {
        File output = "~{filename}.txt"
}
```

However this fails, because apparently read_string is executed before command. (no such file error, cromwell never calls the backend to execute the command). I tried replacing `File output = "~{filename}.txt"` with `File output = "~{read_string('filename')}.txt"`. This does not work as arbitrary expressions are not yet allowed in string interpolation:

`Unable to start job due to: No implementation of FileEvaluator[StringExpression]`

Is there anything I am doing wrong? Can I make read_string execute after command?

**Comment by cjllanwarne** [comment]
If you're running on local backend this should work:
```wdl
output {
  String filename = read_string('output_name')
  File output = "~{filename}.txt"
}
```

Note that this cannot work in PAPI (google cloud) and is unlikely in other clouds either. The problem is, we have to tell the cloud execution service what we want to delocalize *before* we start running the task (which we cannot do if the task hasn't run yet!)

**Comment by EvanTheB** [comment]
Thanks cjllanwarne, does this then need to be noted in the wdl spec / cromwell docs? My guess is that it currently is a grey area of the spec.
