### ISSUE TITLE
CPU on Cromwell machines pegged and unable to recover without restart

### ISSUE THREAD

**Issue by rsasch** [broadinstitute/cromwell#4093]
**What happened:**
On 9/12/18 at 3:41 pm, the Cromwell servers' (801 and 802) CPU were pegged.

801 was restarted (4:11 pm) and immediately got pegged again but recovered 35 min later without further intervention. As for 802, the CPU remained pegged so, at 5:21 pm, 802 was restarted and recovered right away.

**Comment by danbills** [comment]
@davidangb did I see you were you running a query at this time?  If you think it could be associated, could you share some details?

**Comment by davidangb** [comment]
Kate Noblett asked a question, via Slack, about a user who could not view a workflow's details via the FireCloud UI. I first loaded that same workflow in my own browser, then attempted to make a direct API query for that workflow via Rawls. So yes - I was running a query - but it was the same one the end user was making: a specific workflow whose metadata was expensive to calculate.

**Comment by rebrown1395** [comment]
Closed as duplicate.
