### ISSUE TITLE
Please add support for images.sbgenomics.com

### ISSUE THREAD

**Issue by kaushik-work** [broadinstitute/cromwell#4098]
At least one WDL workflow on dockstore (https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller:1.17.0?tab=files) refers to a tool that uses `images.sbgenomics.com`.

Thanks!
-Kaushik

**Comment by geoffjentry** [comment]
It does? 

The WDL workflow is taking the docker container is as a parameter, and the test parameter file has:

 "TopMedVariantCaller.docker_image": "quay.io/ucsc_cgl/topmed_freeze3_calling:1.9.0"`

Further in the GitHub repo the only references to `images.sbgenomics.com` are for the CWL.

**Comment by kaushik-work** [comment]
Hi @geoffjentry ! The WDL `import`s a workflow which is on github (https://raw.githubusercontent.com/DataBiosphere/topmed-workflows/1.17.0/variant-caller/variant-caller-wdl/calculate_contamination.wdl) and that has the SBG image.

`String? docker_image = "images.sbgenomics.com/vladimir_obucina/topmed:VerifyBamID"`

**Comment by geoffjentry** [comment]
Ah I see. That's an outdated version, later versions modified to a more standard container registry

**Comment by kaushik-work** [comment]
Hi @geoffjentry, does that mean Cromwell will not support all docker repos? Thanks!

**Comment by geoffjentry** [comment]
Hi @kaushik-work - internally Cromwell access docker APIs directly and is not shelling out to `docker` for a variety of reasons. Our experience has been that various container registries have needed to be individually supported as things like auth differ, and there are sometimes subtle differences between the sites.

It'd likely not be much work to provide a generic catch all which would work for most sites on public images. However this isn't a common request so prioritizing that over more frequent requests is difficult. However, if what you're getting at is that SBG is now supporting WDL (or is planning on doing so), presumably we'd start seeing more uses of SBG's container registry showing up in WDLs we see in the wild.

**Comment by kaushik-work** [comment]
@geoffjentry , thanks for that explanation!
