### ISSUE TITLE
Empty scatters appear to be skipped because they are not logged

### ISSUE THREAD

**Issue by vruano** [broadinstitute/cromwell#4136]
Im using FireCloud (workspace: broad-firecloud-dsde/dsde-methods-sv-dev)

The WDL can be found in GATK's repo: [cnv_germline_cohort_workflow.wdl](https://github.com/broadinstitute/gatk/blob/master/scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl) that imports [cnv_common_tasks.wdl](https://github.com/broadinstitute/gatk/blob/master/scripts/cnv_wdl/cnv_common_tasks.wdl)

This is the graph that ```wdltools``` output for that WDL
[graph.pdf](https://github.com/broadinstitute/cromwell/files/2406647/graph.pdf)
![graph](https://user-images.githubusercontent.com/791104/45901323-88187c80-bdb0-11e8-91df-c9a61a12a96a.png)

As you can see in the monitor's "Failure" [report ](https://portal.firecloud.org/#workspaces/broad-firecloud-dsde/dsde-methods-sv-dev/monitor/88f444ae-0898-4b5e-af0c-ede98216641d/6d980272-4aa7-4d32-ab90-84880a0723b2)```GermlineCNVCallerCohortMode``` scatter task never get calls before the dependent ```PostprocessGermineCNVCalls```.
<img width="788" alt="screen shot 2018-09-21 at 3 21 43 pm" src="https://user-images.githubusercontent.com/791104/45901815-47b9fe00-bdb2-11e8-9043-9f771ee8bd9e.png">

The log confirms this if one searches for "Starting":
```
2018-09-20 22:45:12,561 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.PreprocessIntervals
2018-09-20 23:03:42,454 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.CollectCounts (95 shards), CNVGermlineCohortWorkflow.ScatterIntervals
2018-09-21 02:12:52,275 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.DetermineGermlineContigPloidyCohortMode
2018-09-21 02:31:18,476 INFO  - WorkflowExecutionActor-6d980272-4aa7-4d32-ab90-84880a0723b2 [UUID(6d980272)]: 
    Starting CNVGermlineCohortWorkflow.PostprocessGermlineCNVCalls (95 shards)  
```
The beginning of the sam log confirms that the skipped task was initially parsed in:
```
2018-09-20 22:45:09,504 INFO  - MaterializeWorkflowDescriptorActor [UUID(6d980272)]: Parsing workflow as WDL draft-2
2018-09-20 22:45:09,877 INFO  - MaterializeWorkflowDescriptorActor [UUID(6d980272)]: Call-to-Backend assignments: 
    CNVGermlineCohortWorkflow.GermlineCNVCallerCohortMode -> JES, 
    CNVGermlineCohortWorkflow.DetermineGermlineContigPloidyCohortMode -> JES, 
    CNVGermlineCohortWorkflow.PreprocessIntervals -> JES, 
    CNVGermlineCohortWorkflow.ScatterIntervals -> JES, 
    CNVGermlineCohortWorkflow.PostprocessGermlineCNVCalls -> JES, 
    CNVGermlineCohortWorkflow.AnnotateIntervals -> JES, 
    CNVGermlineCohortWorkflow.CollectCounts -> JES
```
<i>Notice that in the log extract above I had added new-lines and 4-blank indents to make them more readable.</i>

**Comment by vruano** [comment]
It seems that the input to the missing-in-action scatter, the indexed array that it scatters on, is empty and that is the root cause of the failure....
IMO it would help to see in the locks that the scatter has actually been observed but it simply had 0 elements which quite often may indicate that something is wrong (perhaps it should have a warning icon next to it in the report (e.g. a yellow ! triangle) .

**Comment by cjllanwarne** [comment]
Thanks for reporting, @vruano - I've modified the title to reflect your discovery that this was caused by an empty scatter and that better logs from Cromwell would be nice when debugging.

I think the yellow triangle in the UI would be a FireCloud change - perhaps you'd want to ask them to make a change too to make this even more visible? (the Cromwell team can only change what logs we produce and the error messages on failure, not how the UI interprets what we give them!)

**Comment by gemmalam** [comment]
We've reported this to the Firecloud App team and they will work on improving this on the UI.

**Comment by ruchim** [comment]
https://github.com/DataBiosphere/firecloud-app/issues/192
