### ISSUE TITLE
File evaluation in PAPI v2

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4140]
Based on a conversation with the Epigenomics group that is using Cromwell 34 on PAPI v2 --
it seems that a task can fail, not delocalize an expected output and the workflow will continue to start a downstream task but fail at running the command (as an expected input is missing). It's been confirmed that Cromwell was running in a Fail fast mode.

There seem to be two main requirements here:
1. Cromwell should be evaluating if all expected outputs for a task exist before marking the task as a success.
2. Cromwell should fail a job if it failed localize a specific input file. 
3. Cromwell should fail a job if it failed to delocalize any expected output file.

AC: Ensure that the PAPI v2 backend fulfills requirements #1-3.

**Comment by cjllanwarne** [comment]
I think there should be a \#3: Cromwell should fail a job if it failed to delocalize a required output file.

**Comment by ruchim** [comment]
@mcovarr -- has this been fixed for PAPI v2?

**Comment by mcovarr** [comment]
There was a [34 hotfix](https://github.com/broadinstitute/cromwell/pull/4149) for this a while back. This should also be fixed in Cromwells 35 and greater.
