### ISSUE TITLE
Replace backend-specific execution tables

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#415]
The `JES_JOB`, `LOCAL_JOB`, and `SGE_JOB` tables are specific to the backends currently hardcoded into Cromwell and are not suitable for dynamically pluggable backends.  The data currently captured by these tables should be replaced by a schema that is not backend specific, perhaps something like the following:

```
EXECUTION_INFO

EXECUTION_ID  INT           FK to EXECUTION.EXECUTION_ID, NOT NULL
INFO_KEY      VARCHAR(xyz)  NOT NULL
INFO_VALUE    VARCHAR(xyz)  
```

I'd also propose adding a nullable `BACKEND_TYPE VARCHAR(xyz)` field to `EXECUTION` to record what backend was actually used to run a job.

**Comment by mcovarr** [comment]
Just a heads up to Intel friends @francares  @gauravs90 @jainh that work on this issue is now underway.

**Comment by gauravs90** [comment]
@mcovarr  This is great :smile:
