### ISSUE TITLE
Allow for zero sized disk in runtime attributes

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4150]
Zero is a perfectly valid size for a disk specification. At the moment it is disallowed because it's wired in through the same validations we use for things which don't make sense to be zero (e.g. CPU/memory). 

Allow for zero sized disk

**Comment by chapmanb** [comment]
Jeff and all;
This is bcbio CWL triggering the problem. We use 0 for disk when we have operations that don't need to download/manage the inputs and are just manipulating things in memory. If changing turns out to be a major issue I'm happy to re-explore how we handle it.

**Comment by geoffjentry** [comment]
Closing this as the driving use case has been taken care of via implementation of the DX `inputDir` hint
