### ISSUE TITLE
Relative imports from a URL based CWL workflow file seems to fail

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4152]
`java -Dconfig.file=/home/jgentry/jes.conf -jar ~/cromwelserver/target/scala-2.12/cromwell-35-49d15d2-SNAP.jar run https://raw.githubusercontent.com/bcbio/test_bcbio_cwl/master/gcp/somatic-workflow/main-somatic.cwl -i main-somatic-samples.json -t CWL -o /home/jgentry/bootDisk.json`

Led to

`2018-09-26 15:24:34,35] [error] WorkflowManagerActor Workflow bd190770-2d7a-4a14-893a-71a7081512c4 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
running cwltool on file /tmp/bd190770-2d7a-4a14-893a-71a7081512c4.temp.8962849824592019273/bd190770-2d7a-4a14-893a-71a7081512c4.cwl failed with null
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)`

**Comment by cjllanwarne** [comment]
Another example of this bug: https://github.com/broadinstitute/cromwell/issues/4235
