### ISSUE TITLE
Report invalid string along with error

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4161]
Original report here: https://gatkforums.broadinstitute.org/firecloud/discussion/10273/error-messages-should-include-the-problematic-input-whenever-possible-disk-strings

AC: 
The failure message returned today looks like `Disk strings should be of the format 'local-disk SIZE TYPE' or '/mount/point SIZE TYPE'`

but it should be 
`Disk strings should be of the format 'local-disk SIZE TYPE' or '/mount/point SIZE TYPE'. Found 'foo'`

**Comment by cjllanwarne** [comment]
This was addressed in https://github.com/broadinstitute/cromwell/pull/2588 on 9/1/17. Maybe an old version of Cromwell is being used?
