### ISSUE TITLE
Run Demo TESK workflows

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#4163]
https://github.com/EBI-Metagenomics/CWL-assembly/tree/demo/cwl
Workflows are `demo_megahit_pipeline_paired.cwl` and `demo_metaspades_pipeline_paired.cwl`

**Comment by ruchim** [comment]
@Horneth for provenance, would you mind linking the respective CWL workflows to this issue? Thank you for making this issue!

**Comment by Horneth** [comment]
@ruchim updated the issue, I'm thinking we could add them to centaur too eventually

**Comment by ruchim** [comment]
Great point
