### ISSUE TITLE
Periodic network connectivity hiccups in Firecloud

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4164]
![image](https://user-images.githubusercontent.com/165320/46151480-da3c2080-c23c-11e8-97a4-ecfa39139c11.png)

We're seeing intermittent connectivity issues w/ message of "socket timeout, cannot connect to server" in Pingdom.

They last 1-3 minutes and seem to be off and on:
![image](https://user-images.githubusercontent.com/165320/46151547-05267480-c23d-11e8-865a-f9c1fc1c4e4d.png)

From the looks of things this looks to be between pingdom and the load balancer or proxy, as neither Cromwell nor proxy logs are showing signs of distress during these times.

**Comment by hjfbynara** [comment]
Just to clarify things.  The check goes directly against the backend cromwell (cromwell1.dsde-prod.broadinstitute.org -> cromwell601.dsde-prod.broadinstitute.org).  So no LB is involved.  So the only "layer" that is there is the openidc proxy that is running the cromwell host.

**Comment by danbills** [comment]
It's happening again.  Last time this was the result of our LB blocking new pingdom servers.  @hjfbynara could you please run update script?

I don't see any added in december here: https://help.pingdom.com/hc/en-us/community/posts/208953545-Pingdom-Probe-Servers-Pingdom-IPs.
But it seems too coincidental that the symptoms are exactly the same as they were last time.

![image](https://user-images.githubusercontent.com/165320/50653143-8f762700-0f56-11e9-9b2d-76da416c47f2.png)

**Comment by danbills** [comment]
@davidbernick @hjfbynara would you please confirm update script has been run so that I can rule out pingdom/firewall issues?

**Comment by RLuckom** [comment]
Ran it  just now, there were updates.

**Comment by danbills** [comment]
issue has not recurred since update
