### ISSUE TITLE
Fix dontglobinputs centaur test flakiness

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#4202]
It appears that the `evaluateFiles` method on `WomExpression` first tries to evaluate the expression, basically calling `evaluateValue`.
In the case of globs, this means trying to read the file containing the list of files that have been globbed, which is
1) (Almost - see 2)) bound to fail since `evaluateFiles` is called before the task is run to determine the output files that _will_ be generated by an expression, therefore trying to evaluate the glob is pointless and generates unnecessary I/O.
2) If for some reason the list file _is_ there but is invalid, the result of `evaluateFiles` will be invalid.

Why 2) would happen is unknown at the moment, but some of our centaur integration test (dontglobinputs) present very odd failure mode consistent with 2)

**Comment by ruchim** [comment]
@Horneth -- you probably have all the details already, but would you mind adding a description of what is broken (maybe an example) and is it broken across all backends & Cromwell versions?

**Comment by Horneth** [comment]
@ruchim I updated the description and title, this is not nearly as bad as the previous title made it sound. It's a very weird case found in the centaur test failures that I'm looking at.
