### ISSUE TITLE
missing config header

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromwell#4204]
Does the config file https://github.com/broadinstitute/cromwell/blob/develop/scripts/docker-compose-mysql/compose/cromwell/app-config/application.conf#L1
need the header
include required(classpath("application"))
at the top?

**Comment by kshakir** [comment]
Yes.

This pulls in the cromwell "server" [application.conf](https://github.com/broadinstitute/cromwell/blob/1dc56871a958c3c2cfdf1a59c6ccc2bec3968300/server/src/main/resources/application.conf) with a few required overrides of akka's various reference.conf files, and reports an error if for some reason the file is not found.

https://github.com/broadinstitute/cromwell/blob/1dc56871a958c3c2cfdf1a59c6ccc2bec3968300/server/src/main/resources/application.conf#L1-L23
