### ISSUE TITLE
config parameters inconsistent between submit and submit-docker

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/cromwell#4212]
The parameters available to config scripts are mostly undocumented. A list can be reverse engineered using the cromwell.examples.conf file, and by forcing the parser to crash - which prints the generated submit wdl script to the log. I could then build this config:

```
          submit-docker = """
          /usr/bin/env ${job_shell} ${script}
          echo ${job_name}
          echo ${cwd}
          echo ${out}
          echo ${err}
          echo ${script}
          echo ${job_shell}
          echo ${docker_cid}
          echo ${docker_cwd}
        """
        submit = """
          /usr/bin/env ${job_shell} ${script}
          echo ${job_name}
          echo ${cwd}
          echo ${out}
          echo ${err}
          echo ${script}
          echo ${job_shell}
        """
```

(note while String job_id is available in the submit task, using it causes a crash-loop).  

The values of cwd and docker_cwd make sense, cwd (in both scripts) refers to the 'shared file system' path to the cromwell created directory, and docker_cwd strips everything before 'cromwell-executions'. I do not see the necessity for docker_cwd, but fair enough.

However 'out', 'err' and 'script' do not follow the pattern. In 'submit' they are sfs paths, but in submit-docker they are docker paths. This kind of inconsistency, combined with lack of documentation makes cromwell extremely frustrating to use.

**Comment by kshakir** [comment]
We just merged a little bit of [cleanup](https://github.com/broadinstitute/cromwell/pull/4666/files#diff-a0a39c998215634e799c30ace2dfd58b) around the issue above, including editing [the docs](https://cromwell.readthedocs.io/en/develop/backends/SGE/) and adding a new `docker_out`, `docker_err`, and `docker_script` that should behave closer to expectations.

Please check it out and file any additional feedback as a new issue or PR? Thanks!

**Comment by EvanTheB** [comment]
This is great, thanks for making the documentation awesome!
Only thing I could improve is to explicitly specify which base the memory_*b conversion uses, (I think both are available? MiB and MB). And to specify the rounding behaviour of 'Int memory_gb', probably ceil.
