### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by danxmoran** [broadinstitute/cromwell#4221]
https://cromwell.readthedocs.io/en/develop/filesystems/HTTP is linked to in both the [release notes for 35](https://github.com/broadinstitute/cromwell/releases/tag/35) and the [Filesystems overview page](https://cromwell.readthedocs.io/en/stable/filesystems/Filesystems/). It leads to a maze page.

**Comment by geoffjentry** [comment]
Hi @danxmoran - thanks, I noticed this last week and meant to fix it. Doing it now.

**However** - NB that I also discovered last week that the HTTP fs doesn't work for workflow level engine functions (e.g. getting `size()` in a `runtime` block) which makes it not so useful in real world workflows. If you'd like to see this fix quickly I'd advocate raising a ruckus to @ruchim
