### ISSUE TITLE
cwl_format_valid_with_workflow_url next failing intermittently

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4232]
Per our test review meeting, we see this is one of the more commonly failing tests.  

![image](https://user-images.githubusercontent.com/165320/46823419-236f9280-cd5c-11e8-8f32-0401c7bdee71.png)

(working on a BQ sample of an error for some more details)

**Comment by Horneth** [comment]
From my investigation, those were due to transient failures of ontology parsing, which this should alleviate now: https://github.com/broadinstitute/cromwell/pull/4210
