### ISSUE TITLE
Flakey test: LoadControllerServiceActorSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4237]
```The code passed to eventually never returned normally. Attempted 51 times over 3.8950992149999997 seconds. Last failure message: HighLoad was not equal to NormalLoad.```

`https://broadinstitute.atlassian.net/browse/GAWB-3876`

```tc: LoadControllerServiceActor should update global load level periodically (each time with same test case)```

**Comment by salonishah11** [comment]
Closing this ticket as the test hasn't failed since #4231 was merged (4231 added span scale factor which increased the timeout duration for Jenkins).
