### ISSUE TITLE
De-serialize the workflow starter and heartbeat writes 

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#4239]
This was serialized to remove the deadlock observed in production).  Looking at the code this is just reverting a change made back on 6/15 of a few lines per actor.  WorkflowStoreHeartbeatWriteActor and WorkflowStoreEngineActor.scala should stop calling WorkflowStoreCoordinatedWriteActor.scala (which can probably be removed) as changed in commit 2e905b10db79587edc185733f41be9764ef788f9.

**Comment by ruchim** [comment]
AC: As a part of deserialization, one should add a unit test (or some test) to run a bunch of load through the workflow store and report failure if there is an exception thrown from mysql.

Possible ways to reproduce the deadlocking error:

- Start 10K workflows (that just sleep) and configure the heartbeat-interval rate to be the shortest duration possible (or whatever is reasonable). One would have to check the Cromwell server logs to see if there's a SQL exception
