### ISSUE TITLE
Order of heartbeats database updates

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#4240]
To prevent deadlocks, we have to acquire locks in the same order in the heartbeat writing batches and the workflow starting.  Workflows currently start by ascending submission_time, so we need to order the updates in the same order. 

Unfortunately, at the time we are making the sequence of DBIO actions we don't have that information so it needs to be propagated along to that point and then use that information to sort that collection of actions

**Comment by mcovarr** [comment]
I thought we were going to try @aednichols's idea for autocommitting the heartbeat writes (still batched, just not wrapped in one big transaction) to avoid having to do this?

**Comment by aednichols** [comment]
We definitely won't if I keep forgetting to file an issue 😄 

Created https://github.com/broadinstitute/cromwell/issues/4249
