### ISSUE TITLE
Write heartbeats in a batch, but not in a transaction

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4249]
See https://github.com/broadinstitute/cromwell/pull/4022 - originally closed because I wasn't sure it was the right thing, and I didn't see a way to test it. I'm now more certain it's worth trying.

Even if this doesn't actually fix the deadlock and we need to use one of the other solutions, I think this may still be worth having because it will save the RDBMS a lot of work coordinating transactions.

[`autocommit` documentation](https://dev.mysql.com/doc/refman/8.0/en/innodb-autocommit-commit-rollback.html)
[Slick transactions and pinned sessions](http://slick.lightbend.com/doc/3.2.0/dbio.html#transactions-and-pinned-sessions)

Acceptance criteria:
- [ ] Not a performance regression - heartbeats are still efficiently written to the DB in batches
- [ ] Prevents the deadlock

**Comment by aednichols** [comment]
@mcovarr I remember you mentioned a way to pause & examine the Slick queries in the debugger - what's a good code location to pause at?

The last time I looked at this I just enabled MySQL logging, which was a ton to dig through

**Comment by mcovarr** [comment]
I'd try [here](https://github.com/broadinstitute/cromwell/blob/develop/database/sql/src/main/scala/cromwell/database/slick/WorkflowStoreSlickDatabase.scala#L82) first.

**Comment by aednichols** [comment]
thanks, I thought I tried that but I must have missed the field

**Comment by ruchim** [comment]
Dependent on the completion of #4239

**Comment by kcibul** [comment]
If we go this route -- let's make sure we know how we're going to verify
that the right behavior is happening.  I'm not sure this can actually be
done... so verifying it is key.

it also might end up being the same thing as setting the batch size to 1
which if that is acceptable is much easier to understand and maintain

**Comment by mcovarr** [comment]
A/C write a unit test that characterizes the performance of heartbeat writing with and without autocommit.

**Comment by danbills** [comment]
@mcovarr @kcibul can this be closed as a result of your work?

**Comment by kcibul** [comment]
This is now addressed in as part of the deadlock fixing round 2 PR I made a little while back.

Ultimately -- we weren't doing JDBC batched inserts anyway, so this was just turning autocommit on
