### ISSUE TITLE
Spike: scalability of bucket whitelist

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4266]
The proposed scale of buckets given to cromwell to search through has been tentatively identified as being up to 10k.

We currently support 3.  Let's see how well the current implementation scales, in order to increase this number to meet production expectations.

**Comment by salonishah11** [comment]
![image](https://user-images.githubusercontent.com/16748522/47726893-c6b41900-dc31-11e8-9d33-3120309fb152.png)

Legend:
Blue line- the query checks whether a call cache entry exists for the base aggregation hash
Orange line- the query retrieves 1 call cache entry matching the base aggregation hash and input files aggregation hash

**Comment by salonishah11** [comment]
Using raw SQL query which uses table join to find match in the prefix hints:

![image](https://user-images.githubusercontent.com/16748522/47813043-4d472400-dd20-11e8-9181-49d45fc56425.png)

Legend:
Blue line- the query checks whether a call cache entry exists for the base aggregation hash
Orange line- the query retrieves 1 call cache entry matching the base aggregation hash and input files aggregation hash

Same database was used as above.

**Comment by rebrown1395** [comment]
@salonishah11 can this be closed?
