### ISSUE TITLE
fc-develop docker compose file to include CromIAM

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4268]
I believe @hjfbynara is coordinating this, but make sure we have something to deploy CromIAM to firecloud environments.

Namely the docker-compose.yml includes CromIAM

**Comment by ruchim** [comment]
@danbills I believe this was in-progress before the break, so it will likely close soon, just contingent on Henry's confirmation.

**Comment by ruchim** [comment]
Closing this given the fact that the latest QA testing framework in the form of a Jenkins build is now green: https://fc-jenkins.dsp-techops.broadinstitute.org/view/CromIAM-Testing/job/Taurus-Gatling-Test-Pipeline/237/
