### ISSUE TITLE
Timing diagram inaccesible from Job Manager (CaaS Prod)

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4277]
Today, one can't see a timing diagram in Job Manager on production, there is 403 returned. Investigate why this timing diagram isn't visible, even though it should certainly exist as in this case the workflow succeeded successfully and its metadata reveals execution events.

**Comment by ruchim** [comment]
Yes!

**Comment by ruchim** [comment]
I've learned that this will never work given how the timing diagram works today. A fix for this behavior is what Chris seems to be describing here: https://github.com/broadinstitute/cromwell/issues/4309 @tjeandet does that sound right?

**Comment by Horneth** [comment]
I think that would definitely help but we might still have this issue if JobManager simply links out to CromIAM without providing the auth headers for the timing endpoint itself.

**Comment by ruchim** [comment]
@Horneth does this give Job Manager the html content itself, which JM could choose to display itself?

**Comment by ruchim** [comment]
This issue is being closed as #4408 and #4479 should allow Job manager to display its own timing diagram.
