### ISSUE TITLE
aws.config error https://cromwell.readthedocs.io/en/jg_add_http_doc/tutorials/AwsBatch101/

### ISSUE THREAD

**Issue by bfoster-lbl** [broadinstitute/cromwell#4278]
I noticed an error in your tutorial:
https://cromwell.readthedocs.io/en/jg_add_http_doc/tutorials/AwsBatch101/

The aws.config you supply is missing:
  numSubmitAttempts = 6
  numCreateDefinitionAttempts = 6
from the config portion:

It was generating a confusing error and should be updated.

**Comment by wleepang** [comment]
@bfoster-lbl - An example config with the parameters you highlighted is available [here](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/#cromwell-server).  That said, I agree that the tutorial in cromwell.readthedocs.io should match.

**Comment by rebrown1395** [comment]
This appears to be fixed, reopen if need be!
