### ISSUE TITLE
Retrieve contents for DOS URIs

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4292]
Today, there's no way to use certain language functions with DOS URI file types (such as read_lines(), read_string() etc). This makes it hard to use existing workflows with DOS inputs.

AC: Add support for being able to get file contents for DOS URIs as a part of the DOS filesystem provider in Cromwell. Ensure that this workflows for both workflow level functions and task level functions. For example:

```
workflow w {
File f = "dos://uuid"
String x = read_string(f)

call t { 
  input: 
     f = f
     x = x
}
}

task t {
  String x
  File f
  String y = read_string(f)
 
  command {
    if [[ ${x} != ${y} ]]; then
      exit 1
    fi
  }
  runtime {
    docker: "ubuntu"
  }
}
```

**Comment by cjllanwarne** [comment]
Is there an example of reading the content of a file in CWL that we can add an as additional AC for this ticket?
