### ISSUE TITLE
PAPIv2 Cron Job

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#4298]
Last few cron jobs on papiv2 have failed with

```should successfully run jointdiscovery

EntityStreamSizeException: actual entity size (Some(9030961)) exceeded content length limit (8388608 bytes)!
```

**Comment by adamnovak** [comment]
Did anyone ever figure out why Cromwell would fail with an `EntityStreamSizeException`? When and how was this issue with the CI fixed?

I managed to make a similar `EntityStreamSizeException` happen using Cromwell release 66 in `run` mode, without providing a configuration, with a workflow input that specified HTTPS URLs for large files as file inputs.

Is this exception ever supposed to happen? And, if so, when and why?

**Comment by adamnovak** [comment]
I did some more digging and I think #4302 was the fix
