### ISSUE TITLE
Add ability to abort on-hold workflows

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#4311]
The mint team submits workflows in "on hold" status and then has a separate service to start those workflows. If there is an issue with any of the on-hold workflows, there is no way to abort them until after they start running. It would be convenient to have the ability to abort those workflows so that our starter service queue is not full of these erroneous workflows that would fail.

**Comment by ruchim** [comment]
Hey @samanehsan 

Can you please explain what happens when you try and abort an on-hold workflow, what happens?
