### ISSUE TITLE
[AWS] IOException: Could not read from ... Unable to execute HTTP request: Certificate for ...

### ISSUE THREAD

**Issue by hmkim** [broadinstitute/cromwell#4321]
![2018-10-26 23 24 43](https://user-images.githubusercontent.com/4966343/47572651-79585300-d976-11e8-8027-a9bade3f91d4.png)

aws

https://github.com/broadinstitute/cromwell/blob/develop/centaur/src/main/resources/integrationTestCases/germline/haplotype-caller-workflow/HaplotypeCallerWF.aws.wdl

AWS Access Key ID [****************R62Q]: 
AWS Secret Access Key [****************uDg5]:
Default region name [ap-northeast-2]:
Default output format [None]:

**Comment by rebrown1395** [comment]
@wleepang do you mind looking at this? Thanks!

**Comment by wleepang** [comment]
@rebrown1395 - This appears to be related to a previous issue with the public dataset bucket for `gatk-test-data` which has been resolved.

**Comment by hmkim** [comment]
Yes @wleepang . Thank you for your reply.
