### ISSUE TITLE
monitoring log does not exist

### ISSUE THREAD

**Issue by benjamincarlin** [broadinstitute/cromwell#4330]
(cromwell version 35-5f86a05-SNAP)

call caching  version from previous run

**Comment by Horneth** [comment]
Hi !
Just to make sure I understand, are you saying that the monitoring log is not copied over when a call is being cached ?

**Comment by benjamincarlin** [comment]
Yes

**Comment by benjamincarlin** [comment]
Not critical but just very annoying as we have to set read and write from
cache to false to use the script

**Comment by ruchim** [comment]
Hey @benjamincarlin,

The call caching feature is really designed with the focus on not having to recomputing outputs. In the case of the monitoring script, it really was meant to be treated as a debugging tool and not a true output from a task. Can you explain why you need to the monitoring log for cached jobs, especially as its not new information? Is the motivation to be able to access all monitoring logs under one workflow uuid directory?

Thanks!

**Comment by ruchim** [comment]
Closing this for now!
