### ISSUE TITLE
Ontology for Cromwell

### ISSUE THREAD

**Issue by vsoch** [broadinstitute/cromwell#4339]
heyo Cromwell!

No bugs here! I wanted to ask if Cromwell (and wdl) had any sort of ontology, so for example, I could model a workflow using it, or more specifically, given that I have a valid Cromwell execution workflow, I can easily generate / export a model of it using the ontology. A good example would be (one I found) from CWL:

https://www.commonwl.org/v1.0/Workflow.html

Have you guys, or do you know of any biology based workflows, that have engaged with schema.org? 

Thanks!

**Comment by geoffjentry** [comment]
Hi @vsoch - I'm not sure quite what you're looking for here. There's the [WDL spec](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) and one can access programatically generated parsers in [multiple languages](https://github.com/openwdl/wdl/tree/master/versions/1.0/parsers) but at the moment the only option I know of which provide programatic **access** to WDL constructs is [miniwdl](https://github.com/chanzuckerberg/miniwdl) although it's still early days (however I'm sure they'd love support & ideas!)

There's the WOM layer which we have in Scala and is what we use to internally generalize both WDL & Cromwell but it's likely not useful for your purposes as you can't directly input WOM. Although if what you're asking is if you were to take a WDL or CWL and export e.g. the WOM graph file you can do that with [womtool](https://cromwell.readthedocs.io/en/develop/WOMtool/)

Let me know if this comes even close to answering your question :)

**Comment by vsoch** [comment]
This is really old, and I don't remember what I had in mind so I'm going to close the issue. But thank you for coming back to it! If I am able to remember, I'll know where to look :)

**Comment by geoffjentry** [comment]
Hah, got it. And sorry for the delay :(
