### ISSUE TITLE
AWS Batch: Docker hash lookup failed with code

### ISSUE THREAD

**Issue by alexfrieden** [broadinstitute/cromwell#4345]
Crossposting here as I was not able to get an answer on WDL forum.  Post is here:
https://gatkforums.broadinstitute.org/wdl/discussion/13540/unable-to-do-docker-lookup#latest

Trying to get hello world working on AWS Batch and cromwell.

I am able to spin up the servers however it fails in pulling the docker image with the following error message in the cromwell logs:

`
2018-10-30 15:43:14,845 cromwell-system-akka.dispatchers.engine-dispatcher-9 WARN - BackendPreparationActor_for_7d0c30ad:wf_hello.hello:-1:1 [UUID(7d0c30ad)]: Docker lookup failed java.lang.Exception: Failed to get docker hash for ubuntu:latest Docker hash lookup failed with code 503. The server is currently unavailable (because it is overloaded or down for maintenance). at cromwell.engine.workflow.WorkflowDockerLookupActor.cromwell$engine$workflow$WorkflowDockerLookupActor$$handleLookupFailure(WorkflowDockerLookupActor.scala:188)
`

Here is my wdl:

```
   task hello {
        String addressee
      command {
        echo "Hello ${addressee}! Welcome to Cromwell on AWS"
      }
      output {
        String message = read_string(stdout())
      }
      runtime {
        docker: "ubuntu:latest"
      }
    }

  workflow wf_hello {
    call hello

    output {
      hello.message
    }
  }
```

This is originally from tutorial by @wleepang found here:
https://www.youtube.com/watch?v=jcC3pz_K4gI

Any idea on how to diagnose?  I was not able to find a similar issue.  Thanks so much for the help.

**Comment by alexfrieden** [comment]
@Horneth just tried this again three times.  These jobs are now getting stuck in the runnable state.

**Comment by wleepang** [comment]
@alexfrieden - I just ran this successfully.

With your first error, the fact that you are getting an HTTP response indicates that it's not necessarily a networking issue on the AWS side, and as @Horneth stated something going on with DockerHub.  For debugging in that scenario, I would try launching a t2.micro based on the CustomAMI you created with the same Batch instance profile in the VPC used by the Batch compute environment and try `docker pull <image>`.

As for your second issue, did your tasks eventually transition from RUNNABLE?  I've noticed that sometimes it takes about 5-10min for the Batch scheduler to "re-warm" after scaling down instances that were used for previous tasks.

**Comment by alexfrieden** [comment]
@wleepang these seem to be runnable.  Does everything need to be set as /cromwell_root or /cromwell_mount?  Thanks!

**Comment by alexfrieden** [comment]
Also @wleepang I was able to do a docker pull on the AMI that I am using:

AMI ID: amzn-ami-2018.03.h-amazon-ecs-optimized (ami-0a0c6574ce16ce87a)

`[ec2-user@ip-172-31-29-236 ~]$ docker pull ubuntu:latest
latest: Pulling from library/ubuntu
473ede7ed136: Pull complete
c46b5fa4d940: Pull complete
93ae3df89c92: Pull complete
6b1eed27cade: Pull complete
Digest: sha256:29934af957c53004d7fb6340139880d23fb1952505a15d69a03af0d1418878cb
Status: Downloaded newer image for ubuntu:latest`

Let me know if there is something off here, it seems fine to me

**Comment by wleepang** [comment]
@alexfrieden - the scratch mount point in the custom Ami should be set to `/cromwell_root`.  The docker pull you ran seems fine, was that under the same scenario as task instances (i.e. same vpc and same subnet)?

**Comment by alexfrieden** [comment]
@wleepang this should have been under the same VPC (the genomics stack one that was autocreated with the cloudformation)

**Comment by alexfrieden** [comment]
Is there a separate instruction set I should be following @wleepang ?  The youtube video was what I used to initially create everything.  Let me know!  Thanks!

**Comment by ruchim** [comment]
Hey @alexfrieden -- to try to eliminate the possibility that the issue isn't Dockerhub and one of the other services, any chance you can try your workflow with an equivalent docker image hosted in a public quay repo?

**Comment by wleepang** [comment]
@alexfrieden - Sorry to say that the youtube video might be a bit out of date.  We've been iterating pretty quickly on this.

Can you try launching a new stack with the following [Cromwell "All in One" template](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/#tldr)?  This is a new one that will also configure and launch a Cromwell server that you can get to from a web-browser.  I just launched this stack and successfully ran a couple of workflows on it.

**Comment by alexfrieden** [comment]
@wleepang worked great.  Was able to run the workflow.  Thanks a ton!
