### ISSUE TITLE
Feature Request: Memory increase on retry

### ISSUE THREAD

**Issue by DavyCats** [broadinstitute/cromwell#4346]
It would be nice if cromwell would have the option to incrementally increase the memory attribute for a job, based on the retries. This is related to #1991, but the conclusion there (if I'm understanding it correctly) seems to be adding a feature to the WDL specs. I feel that these types of features might be more appropriate as a backend configuration, since whether this is something you want to do or not will depend on the infrastucture your workflow is running on.

One potential way to configure this, might be to add multipliers for certain runtime attributes in the backend configuration:
```
[...]
config {
    runtime-attributes = """
        Int? cpu = 1
        Int? memory = 4
    """
    runtime-attribute-retry-multipliers = {
        memory: 1.5
    }
    [...]
}
[...]
```

This would, for example, cause the memory attribute to be multiplied by `1.5` with each retry. For the first attempt it would be `4`, for the the second `6`, the third `9` etc. Another option might be that the values here indicate a fraction of the original attribute which it should be increased it by each retry, so in the above example it would be: `4` -> `10` -> `16` etc. You would probably want set a lower value in that case, though.

Another option would be to supply a list of numbers with each indicating a multiplier for a certain attempt. A value of `[1.5, 2]` (or maybe `[1, 1.5, 2]`) would cause the value to be multiplied by `1.5` on the second attempt and `2` on the third, repeating the last multiplier if neccesary. (ie. `4` -> `6` -> `8` -> `8`)

**Comment by ruchim** [comment]
hey @DavyCats,

I think you're right that this could be an engine option (in the backend, or per workflow or something like that). Are you concerned about the scenario where a job failed for reasons not related to memory and you end up retrying it _n_ number of times, each costing more, until the job failed?

**Comment by ruchim** [comment]
Thanks for the clarification! This is very much on our roadmap, but a few months out, likely around March next year.

**Comment by dinvlad** [comment]
Any updates on this front? We’ve been having issues with occasional spikes in memory usage that don’t abide by a linear model for memory allocation. Currently this requires a lot if “babysitting” for our pipelines, significantly reducing their reliability. Thanks!
