### ISSUE TITLE
Cromwell Hangs on SLURM for GATK PreProcessing WDL 

### ISSUE THREAD

**Issue by alongalor** [broadinstitute/cromwell#4347]
Hello!

I am experiencing issues with Cromwell hanging on the O2 cluster, at Harvard Medical School, which uses SLURM. I am using Cromwell v31 and am running the GATK4 Pre-Processing WDL (https://github.com/gatk-workflows/gatk4-data-processing, with minor modifications to runtime parameters to accommodate SLURM). I have ran this script successfully for thousands of samples several months ago. The only discernible difference this time around (all else has stayed constant, except for time) is that my input uBAMs are 50-400G, while last time around they were all <5G.

You can find several relevant files below:

The command I use to start the operation: `NFRI_S003_M1.bam.sh.txt`
 - The corresponding .conf file: `overrides.conf.txt`
 - The corresponding .wdl file: `processing-for-variant-discovery-gatk4.wdl.txt`
 - The corresponding .json file and associated list files: `input.json.txt`, `list.txt`

[NFRI_S003_M1.bam.sh.txt](https://github.com/broadinstitute/cromwell/files/2540502/NFRI_S003_M1.bam.sh.txt)
[input.json.txt](https://github.com/broadinstitute/cromwell/files/2540503/input.json.txt)
[list.txt](https://github.com/broadinstitute/cromwell/files/2540504/list.txt)
[overrides.conf.txt](https://github.com/broadinstitute/cromwell/files/2540505/overrides.conf.txt)
[processing-for-variant-discovery-gatk4.wdl.txt](https://github.com/broadinstitute/cromwell/files/2540506/processing-for-variant-discovery-gatk4.wdl.txt)

Next, I am attaching the corresponding slurm output log to the command submitted (`NFRI_S003_M1.bam.sh.txt`) : `slurm-27492257.out.txt`

[slurm-27492257.out.txt](https://github.com/broadinstitute/cromwell/files/2540512/slurm-27492257.out.txt)

As you can see in the slurm output log, the workflow stops making progress at the MergeBamAlignment step. Insterestingly, if you go into the `executions` directory in `cromwell-executions`: `path/to/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/d41833e7-2c4a-4a92-a9d7-fd194d3059d3/call-MergeBamAlignment/shard-0/execution/`: you'll find in the `stderr` that in fact the jobs seems to have complete successfully and produced the desired output file. Unfortunately, for some reason this is where the job hags (the job continues running but the worfklow makes no progress).

I checked with our Research Computing division and they closely investigated the issue. 

Below is there message to me, which finds that something unexpected is going on with Cromwell. 

```
Hi Alon,
 
That "child" job is running on compute-p-17-32 along with few others:
 
JOBID USER PRIORITY PARTITION STATE TIME_LIMIT TIME NODELIST(REASON) ELIGIBLE_TIME START_TIME TRES
27492251 ag457 514600 park RUNNING 30-00:00:00 4-15:26:38 compute-p-17-32 2018-10-25T22:10:29 2018-10-25T22:10:52 cpu=1,mem=10G,node=1
27492313 ag457 405657 park RUNNING 25-00:00:00 4-10:32:08 compute-p-17-32 2018-10-25T22:11:33 2018-10-26T03:05:22 cpu=16,mem=224000M,node=1
27518966 ag457 360221 park RUNNING 25-00:00:00 3-19:32:50 compute-p-17-32 2018-10-26T13:53:05 2018-10-26T18:04:40 cpu=1,mem=3500M,node=1
27587803 ag457 357888 park RUNNING 25-00:00:00 2-15:03:00 compute-p-17-32 2018-10-27T17:37:01 2018-10-27T22:34:30 cpu=2,mem=10000M,node=1
27612863 ag457 343479 park RUNNING 25-00:00:00 2-09:38:44 compute-p-17-32 2018-10-28T03:57:58 2018-10-28T03:58:46 cpu=1,mem=6000M,node=1
27612723 ag457 343389 park RUNNING 25-00:00:00 2-11:30:58 compute-p-17-32 2018-10-28T02:05:27 2018-10-28T02:06:32 cpu=1,mem=3500M,node=1
 
Looking at 27612723 in particular we see
 
rp189@compute-p-17-32:~ ps -AF|grep slurmstep| grep 27612723
root 15371 1 0 67067 3120 11 Oct28 ? 00:00:08 slurmstepd: [27612723]
 
and the all chain of processes:
 
rp189@compute-p-17-32:~ pstree -s -p 15371
systemd(1)───slurmstepd(15371)─┬─slurm_script(15375)───bash(15377)───bash(21704)───sync(21705)
├─{slurmstepd}(15372)
├─{slurmstepd}(15373)
└─{slurmstepd}(15374)
 
so that job is waiting on the command "sync" which is a linux command used to flush file system buffers and make sure there is nothing left that should be written to file, normally it should run very quickly.
There are 5 of those "sync" jobs stuck there:
 
rp189@compute-p-17-32:~ ps -AF |grep ag457|grep sync
ag457 3388 3387 0 26974 364 9 Oct26 ? 00:00:00 sync
ag457 5036 5035 0 26974 364 2 Oct27 ? 00:00:00 sync
ag457 21705 21704 0 26974 360 11 Oct28 ? 00:00:00 sync
ag457 22304 22303 0 26974 364 12 Oct28 ? 00:00:00 sync
ag457 22345 22344 0 26974 364 26 Oct28 ? 00:00:00 sync
 
and they have been running from a minimum of 46 hours to 85 hours for the oldest, so they are definitely stuck.
 
Bhanu and Jason (the DevOps team leader) checked the node and found out that you have several duplicate processes that are running and doing exactly the same thing.
 
This is never good and it is likely what is causing "sync" to hang.
 
More in detail:
 
those are all the PID associated with your username:
 
rp189@compute-p-17-32:~ ps -AF |grep ag457|awk '{printf "%s ",$2}';echo""
2904 2906 3387 3388 5035 5036 12888 12890 14814 15375 15377 21704 21705 21850 21852 22303 22304 22344 22345 24802 24804 29768 29770
 
Looking at the commands being executed by some of those processes we found several duplicates which likely corrupted the file(s) where command sync was potentially flushing the buffer data, those below are the PID and associated commands (cat /proc/PID/cmdline),
you can see how there are 5 duplicates, exactly as the number of stuck "sync" commands:
 
15377, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S003_M1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/d41833e7-2c4a-4a92-a9d7-fd194d3059d3/call-MergeBamAlignment/shard-0/execution/script
21704, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S003_M1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/d41833e7-2c4a-4a92-a9d7-fd194d3059d3/call-MergeBamAlignment/shard-0/execution/script
22344, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S005_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/b004cf90-7c72-498e-b378-d49cd0b0c2cb/call-SortAndFixTags/execution/script
2906, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S005_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/b004cf90-7c72-498e-b378-d49cd0b0c2cb/call-SortAndFixTags/execution/script
21852, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S007_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/102df484-18d8-4dc3-87f1-85c034d77d9a/call-BaseRecalibrator/shard-15/execution/script
22303, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S007_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/102df484-18d8-4dc3-87f1-85c034d77d9a/call-BaseRecalibrator/shard-15/execution/script
29770, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S013_M1d.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/b75cd521-c92d-4264-98f4-7a6571860bb3/call-SamToFastqAndBwaMem/shard-0/execution/script
5035, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S013_M1d.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/b75cd521-c92d-4264-98f4-7a6571860bb3/call-SamToFastqAndBwaMem/shard-0/execution/script
24804, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S013_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/99b4c5f7-50c2-4888-a448-934329112f83/call-MergeBamAlignment/shard-0/execution/script
3387, /bin/bash/n/no_backup2/dbmi/park/gem_wgs/.PreProcessing/.NFRI_S013_N1.bam/.sh/cromwell-executions/PreProcessingForVariantDiscovery_GATK4/99b4c5f7-50c2-4888-a448-934329112f83/call-MergeBamAlignment/shard-0/execution/script
 
 
I am not sure if this was happening because you started multiple identical jobs or if it is a bug in the cromwell pipeline but it is the reason why those child jobs are hanging now.
``` 

Just to clarify, I did not submit multiple identical jobs. Everything on my end was kosher. 

In any case, theres the issue - its not the first I've had with Cromwell (you can see previous discussions related to this at e.g. https://gatkforums.broadinstitute.org/wdl/discussion/comment/50624#Comment_50624) . I had to make lots of modifications to my configuration file before I got it to work as well as it does now. So if you have any idea what is causing this or any changes to my configuration file you'd recommend id greatly appreciate your help.

Thanks a lot,

Alon

[rc.tmp.txt](https://github.com/broadinstitute/cromwell/files/2540522/rc.tmp.txt)
[script.submit.txt](https://github.com/broadinstitute/cromwell/files/2540523/script.submit.txt)
[script.txt](https://github.com/broadinstitute/cromwell/files/2540524/script.txt)

[stderr.txt](https://github.com/broadinstitute/cromwell/files/2540525/stderr.txt)
[stdout.submit.txt](https://github.com/broadinstitute/cromwell/files/2540526/stdout.submit.txt)

**Comment by ruchim** [comment]
@alongalor -- did @MatthewMah's suggestion work for you?

**Comment by alongalor** [comment]
@ruchim apologies for the late reply - yes, It did! @MatthewMah thanks for your very helpful comment once again! Helped me get this up and running!

**Comment by ruchim** [comment]
Glad to hear that @alongalor . Closing, thanks to @MatthewMah's help.
