### ISSUE TITLE
Auto size of boot disk on PAPI based on docker image size

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#4352]
When running a job on PAPI the docker images used are pulled onto the boot disk. Cromwell uses a defaults the size of this disk to 10GB but it needs to be adjusted if the image is larger than that.
WDL has a `bootDiskSizeGB` runtime attribute for that purpose. However CWL doesn't have such attribute, and it would be an overall better user experience not to have to worry about this.

However, it currently does not seem possible to obtain the total **uncompressed** size of an image from the docker API (more info [here](https://github.com/docker/distribution/issues/1575) and [here](https://github.com/docker/distribution/issues/2034)).
What the API does give is the size of each **compressed** layer. The sum of the sizes therefore does not equal to the actual size on disk when the image is pulled and uncompressed.

A possible path would be to investigate whether or not a sensible and relatively stable factor can be determined with which we could estimate the uncompressed size based on the compressed one.
This is not necessarily possible as the effectiveness of the compression likely depends on the layer's content which can be arbitrary. Nevertheless, taking a sample of most commonly used docker images (in FC) and calculating the compressed/uncompressed diff could give us some insight on whether or not this could be a valid approach.

**Comment by geoffjentry** [comment]
I found [this](https://github.com/docker/hub-feedback/issues/331)

We should still do the experiment Thibault proposes but it looks like there might be some reasonable scale factor to apply here
