### ISSUE TITLE
glob doesn't work on AWS

### ISSUE THREAD

**Issue by TimurIs** [broadinstitute/cromwell#4353]
Hi,

I've noticed that the glob() function from WDL doesn't work on the AWS.

Here is a sample workflow:

```
workflow glob_test
{
 call GlobTest
  {
    input:
      m1 = "msg1",
      m2 = "msg2"
  }
}

task GlobTest
{
   String m1
   String m2
   command
   <<<
     echo ${m1} > foo.1.txt
     echo ${m2} > bar.1.txt
     echo ${m2} > foo.2.txt
   >>>
  runtime
  {
     cpu: 1
     memory: "128 MB"
     docker: "ubuntu:latest"
  }
  output
  {
    Array[File] o1 = glob("*.1.txt")
    Array[File] o2 = glob("*.2.txt")
  }
}
```

The workflow finishes successfully, but in the AWS logs I see the following line:
```
aws s3 cp --no-progress /cromwell_root/glob-6f3569c1e6d4f3f2cfb3469eb61bd5a0/* s3://path/to/s3/
The user-provided path /cromwell_root/glob-6f3569c1e6d4f3f2cfb3469eb61bd5a0/* does not exist. 
```

I've checked and there is no trace of directory with the name "glob-*" anywhere starting from root dir.

Command used to run this workflow on aws:
`java -Dconfig.file=aws.conf -jar cromwell-36.jar run test.wdl`

Thank you,
Timur

**Comment by delocalizer** [comment]
I had a similar issue: #4335 but it turned out I was using an old version of the custom ECS AMI that cromwell-on-AWS requires. If you built your AWS Batch resources more than about 10 days ago, I suggest you recreate the stack and try again.

**Comment by rebrown1395** [comment]
@TimurIs did @delocalizer suggestion help you?

**Comment by TimurIs** [comment]
@rebrown1395 
Yes, it worked. I didn't see this error anymore.

**Comment by geoffjentry** [comment]
Great news @TimurIs - I'll close this issue now.
