### ISSUE TITLE
Task doesn't fail if the output file can't be found on AWS

### ISSUE THREAD

**Issue by TimurIs** [broadinstitute/cromwell#4354]
Hi,

The task doesn't fail when the output file can't be found, hence, cromwell tries to run the next job.

Here is a small sample workflow:

```
workflow should_fail
{
  call Task1
  {
    input:
     out_base = "foo"
  }
}

task Task1
{
  String out_base

  command
  <<<
    #typo simulation, one extra 't'
    echo "Hello World!" > ${out_base}.ttxt
  >>>

  runtime
  {
    cpu: 1
    memory: "128 MB"
    docker: "ubuntu:latest"
  }

  output
  {
    File out = "${out_base}.txt"
  }
}
```

command used to run the workflow on the aws: 
`java -Dconfig.file=aws.conf -jar cromwell-36.jar run test.wdl`

Thank you,
Timur

**Comment by rebrown1395** [comment]
@ruchim to set acceptance criteria

**Comment by geoffjentry** [comment]
It looks like at least one of the `bad_output_task` and `bad_file_string` centaur tests fail (well, succeed, but you know ...) for the same reason

**Comment by geoffjentry** [comment]
See if this is fixed by pushing the new proxy

**Comment by geoffjentry** [comment]
Closing. This should now be fixed. Please reopen if you still encounter this.
