### ISSUE TITLE
Add support for restart / resume a workflow

### ISSUE THREAD

**Issue by gauravs90** [broadinstitute/cromwell#437]
Pluggable backends branch currently doesnt support resuming or restarting a WF

**Comment by geoffjentry** [comment]
If the server is turned off and brought back up any previously running workflows need to be resumed as they would have previous to this PR

**Comment by mcovarr** [comment]
Is there a difference between this and #435, apart from the plea for consistent terminology?

**Comment by gauravs90** [comment]
I think the other one is redundant

**Comment by mcovarr** [comment]
I've created mlc_restart branches in cromwell and cromwell-backend with sketches of the work that needs to be done *before* involving the CallActors.  This is going to be a lot of work and should probably be decomposed into subtickets.
