### ISSUE TITLE
Support workflow level prepare/cleanup

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#439]
The use case here is JES auth file upload and cleanup

**Comment by gauravs90** [comment]
Think we decided to use task level prepare() and cleanUp() for each task isn't it?

**Comment by mcovarr** [comment]
We really do have a business case for doing this once per workflow.  Having this at the task level will run prepare() / cleanup() as many times as we have calls to run on that backend.  This specific use case also involves some sensitive data which we'd particularly like to avoid making many copies of unnecessarily.

**Comment by geoffjentry** [comment]
In fact I'd go a step further and say that any change to number and method of copying would likely run afoul of regulatory issues and at the very least would require sign off of other parties

**Comment by gauravs90** [comment]
So in a world where different tasks run on different backends, how would a particular backend know that some particular task is the last task in the WF and as such it should delete the auth files?

**Comment by mcovarr** [comment]
I think the engine would need to coordinate this and tell the backends it had used to do a workflow-level cleanup.

**Comment by geoffjentry** [comment]
We talked about that last week. The first time a backend is used in a wf call the prepare and then call the cleanup on all back ends used when wf is done

**Comment by francares** [comment]
IMHO, I will disagree with that since that's specific for JES right? So it should be handled by this backend... and the prepare function in this backend should check if the file is there and if it's not it should copy it. I think executions should be atomic and should not keep that file at a workflow level... what happen if Cromwell-engine fails?

**Comment by francares** [comment]
I will add this topic to discuss in tomorrow's meeting.

**Comment by geoffjentry** [comment]
It's just a single example. 

I find it entirely plausible that a backend might want to act upon something at a workflow level and not a simple task level.

**Comment by geoffjentry** [comment]
@francares Also don't forget the cleanup portion which needs to be called when no further processing on that backend happens. So either the engine or the jes backend would need to somehow be aware that the final task was being called. I'll reiterate that changing this behavior will quickly run afoul of some regulatory nonsense and won't be changeable.

Either way, I still say I think it's entirely plausible to desire per 'workflow' prepare/cleanup (where really what I mean is "do this the first time" and "do that when the WF is done". Perhaps it's a PITA the way that cromwell-backend is currently set up but it would be pretty easy to change the backend actor-y structure to not be difficult.
