### ISSUE TITLE
Jobs fail if Google Cloud bucket key contains spaces

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4393]
Cromwell: 36
Backend: PAPI/Google Cloud

If an input file to a WDL pipeline contains a space, the script Cromwell generates to run on the pipelines API will fail.

For instance, I have an input file like this (truncated):
```json
{
  "best_practise.ref_fasta": "gs://genovic-test-data/hg19/Reference Genome/default_unzipped/ucsc.hg19.fasta",
}
```
This make Cromwell generate a PAPI script containing this line:
```bash
bash_ref_fasta=/cromwell_root/genovic-test-data/hg19/Reference Genome/default_unzipped/ucsc.hg19.fasta
```

This then causes the following error in the script:
```
/cromwell_root/script: line 26: Genome/default_unzipped/ucsc.hg19.fasta: No such file or directory
```

**Comment by cjllanwarne** [comment]
@TMiguelT I believe in this case the issue is with the command section in the WDL.

Cromwell won't add `"`s around filenames for you if they aren't there in the WDL. So a line like this:
```wdl
command <<<
    [...]
    bash_ref_fasta=${ref_fasta}
    [...]
>>>
```

will interpolate the `ref_fasta` variable into the command section as a file name verbatim.

So I think the solution for you here is to ask the author of the WDL you're using to add `"`s into their command section, like:
```wdl
command <<<
    [...]
    bash_ref_fasta="${ref_fasta}"
    [...]
>>>
```

**Comment by TMiguelT** [comment]
No, the part that fails isn't part of the WDL. See how the line I mentioned is setting a bash variable? Cromwell does this for each input variable, so that it can run the bash section with those variables. This issue is in the script that's generated for submission to the PAPI

**Comment by TMiguelT** [comment]
Apologies, you're totally right. I checked the wrong pipeline for this. This issue came from the WDL in the `gatk3-data-processing` workflow: https://github.com/gatk-workflows/gatk3-data-processing/blob/88fb7e2ba99b251ff917965640a5fe89f02c4dfd/processing-for-variant-discovery-gatk3.wdl#L279
