### ISSUE TITLE
backend root issue

### ISSUE THREAD

**Issue by abdulrauf** [broadinstitute/cromwell#4404]
If you see I've configured root to be root = "/fast/gdr/uat/cromwell-executions"

but randomly sometime workflows when I check cromwell api metadata it is pointing to old root which was /g/cromwell/cromwell-executions. 

Note I'm running cromwell in server mode with mariadb. I've cleaned and deleted all tables from mariadb. restarted the server as well. Can't find any other config/cache file where it has saved old address. Sometime workflows are fine pointing to new root but sometime not

SLURM on cromwell 36

backend {
  # Override the default backend.
  default = "PhoenixSLURM"

  # The list of providers.
  providers {

    PhoenixSLURM {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
        String userid
        String partitions
        String memory_per_node
        Int nodes
        Int cores
        String time
        """

        # If an 'exit-code-timeout-seconds' value is specified:
        # - When a job has not been alive for longer than this timeout
        # - And has still not produced an RC file
        # - Then it will be marked as Failed.
        # Warning: If set, Cromwell has to run 'check-alive' for every job at regular intervals (unrelated to this timeout)

        exit-code-timeout-seconds = 600

        submit = """
          chmod 770 -R ${cwd}
          sudo change-files.sh ${userid} ${cwd}
          phoenix_home_cwd="/home/${userid}"
          phoenix_home_out="/home/${userid}/stdout"
          phoenix_home_err="/home/${userid}/stderr"

          phoenix_script=${script}_phonix
          cat ${script} | sed -s "s@#\!/bin/bash@#\!/bin/bash\nsource '/etc/profile' @g" > $phoenix_script

          sbatch --uid=${userid} --gid=${userid} \
           -J ${job_name} \
           -p ${partitions} \
           -N ${nodes} \
           -n ${cores} \
           --mem=${memory_per_node} \
           --time=${time} \
           -D $phoenix_home_cwd \
           -o $phoenix_home_out \
           -e $phoenix_home_err \
           $phoenix_script
        """

        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"

        root = "/fast/gdr/uat/cromwell-executions"
      }
    }

  } # providers

} # backend

# https://gatkforums.broadinstitute.org/wdl/discussion/9536/how-do-i-set-up-a-mysql-database-for-cromwell
# http://slick.lightbend.com/doc/3.2.0/api/index.html#slick.jdbc.JdbcBackend$DatabaseFactoryDef@forConfig(String,Config,Driver):Database

database {
  profile = "slick.jdbc.MySQLProfile$"
  db {
    driver = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://gdr-cromwell-uat-URL/uat_gdr_cromwell?rewriteBatchedStatements=true"
    user = "uat_gdr_cromwell"
    password = "<<cromwell_mysql_password>>"
    connectionTimeout = 15000
  }
}

system {
  abort-jobs-on-terminate = false
  max-concurrent-workflows = 1000
  new-workflow-poll-rate = 2
  max-workflow-launch-count = 50
}

# helpful links
# https://devhub.io/repos/broadinstitute-cromwell

**Comment by geoffjentry** [comment]
@abdulrauf To be clear - are you saying that you originally were using `/g/cromwell/cromwell-executions` but then changed to `/fast/gdr/uat/cromwell-executions`? If so, is it the case that the workflows showing up as `/g/cromwell/cromwell-executions`  are workflows which were run prior to that change? Cromwell will not migrate these directories

**Comment by geoffjentry** [comment]
@abdulrauf We're closing this as we haven't heard back. Please feel free to reopen if my previous comment was not sufficient for you
