### ISSUE TITLE
How to specify Java absoulate path ?

### ISSUE THREAD

**Issue by plsysu** [broadinstitute/cromwell#4410]
Hello,

I'm using cromwell and GATK4 run on SGE cluster. When I submit jobs to compute node, the defult java is 1.7, so GATK4 can not run anymore. When I use a local version 1.8 java, it can run. I want to use a specific version of java, how to set up the alsoulate path to cromwell or gatk ?

Thanks a lot !

**Comment by ruchim** [comment]
Hey @plsysu,

Cromwell doesn't take care of dependencies, it's usually managed via dockers. However, another option is to add something to the start of your command block that exports the JAVA_HOME variable to point to version 1.8.

Maybe something like...
```
command {
  export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
  java -jar gatk.jar ...
}
```

Hope that works!
