### ISSUE TITLE
How to set and import global variables 

### ISSUE THREAD

**Issue by alartin** [broadinstitute/cromwell#4416]
Hi all,
I wonder if there is a mechanism of global variables setting and importing like workflow importing or application conf including. I just tried to ways:
1. setting global variables in customized conf which can be used as conf option with cromwell cmd but I don't know how to reference them in the WDL file
2. put all global variables in a separated workflow WDL file using workflow variables and import them in other WDL files, while it looks like only imported tasks can be called and no way to just use the variables
My purpose is that we have many pipelines and there are some shared variables (a.k.a global variables) and I prefer to reference them in some separated WDL/conf rather than repeat them again and again, and let individual pipeline developer not to modify them by accident and only focus on his pipeline specific variables and reference them by importing. How can I do that in an elegant way? Thanks!

**Comment by alartin** [comment]
Finally I figure out one solution, but it is a little bit ugly and still look for an elegant way:

- Global variables WDL as below:

```
workflow global {
}

task init {
  command { }
  output {
    String version = "v1.0"
    String reference = "hg19"

  }
}
```

- Pipeline WDL as below:
```
import "global.wdl" as global

workflow pipeline {
  # Global variables
  call global.init
  String version = init.version
  String reference = init.reference
  # Pipeline variables
  String sample_id = "Sample_001"
  call snp { input: version = version, reference = reference, sample_id = sample_id }
}

task snp {
  String version
  String reference
  String sample_id
  command { echo "SNP_${version} for ${sample_id} on ${reference}!" }

  output { String out = read_string(stdout()) }
}

```
The final result is:
```
[2018-11-21 18:23:14,32] [info] BackgroundConfigAsyncJobExecutionActor [a225847apipeline.snp:NA:1]: echo "SNP_v1.0 for Sample_001 on hg19!"
```

And you can see global variables are passed to the pipeline WDL while there are some workaround such as empty global workflow and helper task of init.
Is there any other solution?

**Comment by aednichols** [comment]
Hi @alartin - this is a perfectly reasonable method and one I've recommended to people in the past ("elegant by WDL standards").

**Comment by cjllanwarne** [comment]
Hi @alartin -

You're right that there's not a really nice way - I'd suggest asking or making an issues over at https://github.com/openwdl/wdl where the spec is held.

In the mean time, I do think that you can cut out the need to make a call, just use workflow outputs:
```wdl
workflow global {
  output {
    String version = "v1.0"
    String reference = "hg19"
  }
}
```

While logically it's the same, you remove the need to make a call out to the cloud backend to run an empty command by doing this

**Comment by aednichols** [comment]
Cromwell can only be as good as the WDL spec in this area, so closing with a hopefully reasonable workaround having been discussed.
