### ISSUE TITLE
Fix flakey test: ScatterWorkflowSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4418]
https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/cromwell-test-runner/1415

**Comment by geoffjentry** [comment]
https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/cromwell-test-runner/1699

**Comment by geoffjentry** [comment]
Jenkins job #1847

**Comment by mcovarr** [comment]
Centaured
