### ISSUE TITLE
Revisit the FinalCall flow in the pluggable backends

### ISSUE THREAD

**Issue by gauravs90** [broadinstitute/cromwell#443]
There is only one call actor in the pluggable backends branch , while it was divided into two viz. BackendCallActor and FinalCallActor (likewise for CallExecutionActor, except it doesn't exist anymore). See how this can be reimplemented in the Pluggable Backends world

**Comment by mcovarr** [comment]
@cjllanwarne @geoffjentry are we open to the idea of moving the execution of final calls to the backend?  It's possible that could simplify this ticket.
