### ISSUE TITLE
Failed to create AMI when using /cromwell_root

### ISSUE THREAD

**Issue by lij41** [broadinstitute/cromwell#4435]
I tried to set up AWS Batch with Cromwell 36, and using https://docs.opendata.aws/genomics-workflows/aws-batch/create-custom-ami/ to create the AMI, but when I use /cromwell_root as ScratchMountPoint instead of /scratch, the cloud formation failed to create AMI:

11:43:03 UTC-0500 | CREATE_FAILED | AWS::EC2::Instance | EC2Instance | Received FAILURE signal with UniqueId i-0428e258c971e355e
-- | -- | -- | -- | --
  | Physical ID:i-0428e258c971e355e
  | Client Request Token:Console-CreateStack-2b86244b-f98c-4c65-9b87-7988dd39a4df

Please advise.
Thanks
Jing

**Comment by wleepang** [comment]
@lij41 - do you have any more error information, like a specific failure message?  Also, were you creating the AMI from the CloudFormation templates?  If so, which version - with or without VPC creation?

**Comment by ruchim** [comment]
Closing this for now. Please re-open if your issue was never resolved.
