### ISSUE TITLE
Failed to delete auth file in PAPI v1 fails workflow

### ISSUE THREAD

**Issue by gdlex4015** [broadinstitute/cromwell#4439]
message: [Attempted 2 time(s)] - FileNotFoundException: gs://cromwell-auth-perf-test-a/ea5553fc-7be0-44a2-aae2-683b4d312de6_auth.json

**Comment by Horneth** [comment]
message: [Attempted 2 time(s)] - FileNotFoundException: gs://cromwell-auth-perf-test-a/ea5553fc-7be0-44a2-aae2-683b4d312de6_auth.json

**Comment by ruchim** [comment]
Hey @gdlex4015 

We expect IO failures from time to time. There's a place in the Cromwell config to increate the number of retries on IO actions, so possibly bumping that up will help. 


Closing this for now but please re-open if you see this at a high frequency. Thanks!
