### ISSUE TITLE
Workflow pickup on heartbeat TTL expiration should be highly visible

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4451]
During our Tech Talk today Thibault pointed out it could be quite bad if one Cromwell instance unexpectedly loses its connection to the database and other Cromwells pick up its workflows and start running them. This sparked a discussion that heartbeat TTL expiration is something that should be highly visible to make sure it isn't happening when not expected.

A/C
Log when a workflow is claimed under `INFO` visibility

**Comment by kshakir** [comment]
Closed by #4763
