### ISSUE TITLE
Fix flakey test: PostfixQuantifierWorkflowSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4453]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1763
Jenkins job 1920
Jenkins job 1938

**Comment by geoffjentry** [comment]
@rebrown1395 Why was I assigned? (genuine curiosity and not whining, hard to convey tone over text!)

**Comment by mcovarr** [comment]
PR merged.
