### ISSUE TITLE
Failed attempt to allocate memory only when run via cromwell

### ISSUE THREAD

**Issue by hkeward** [broadinstitute/cromwell#4465]
I am running the program [deFuse](https://bitbucket.org/dranew/defuse) version 0.8.1 using a local backend.

When I run the progam locally inside a docker container, the program completes successfully. When I run it using Cromwell/WDL, it raises the following error:
```
Starting defuse command:
        /usr/local/bin/gmap -D defuse-data/gmap -d cdna -f psl  #<1 > #>1
Reasons:
        /cromwell-executions/detectFusions/962429bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakp
oints.split.001.fa.cdna.psl missing
Failure for defuse command:
        /usr/local/bin/gmap -D defuse-data/gmap -d cdna -f psl  /cromwell-executions/detectFusions/962429bb-ddfa-456a
-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakpoints.split.001.fa > /cromwell-executions/detectFusions/96242
9bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakpoints.split.001.fa.cdna.psl.tmp
Reason:
        Job command with nonzero return code
Return codes: 139
Job output:
        Running on 2ecb3961d54d
        Note: /usr/local/bin/gmap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
        GMAP version 2018-07-04 called with args: /usr/local/bin/gmap.sse42 -D defuse-data/gmap -d cdna -f psl /cromwell-executions/detectFusions/962429bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakpoints.split.001.fa
        Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
        Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
        Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17 
        Finished checking compiler assumptions
        Pre-loading compressed genome (oligos)......done (78,222,840 bytes, 19098 pages, 0.00 sec)
        Pre-loading compressed genome (bits)......done (78,222,864 bytes, 19098 pages, 0.02 sec)
        Looking for index files in directory defuse-data/gmap/cdna
          Pointers file is cdna.ref153offsets64meta
          Offsets file is cdna.ref153offsets64strm
          Positions file is cdna.ref153positions
        Offsets compression type: bitpack64
        Allocating memory for ref offset pointers, kmer 15, interval 3...Attached existing memory (2 attached) for defuse-data/gmap/cdna/cdna.ref153offsets64meta...done (134,217,744 bytes, 0.00 sec)
        Allocating memory for ref offsets, kmer 15, interval 3...Attached new memory for defuse-data/gmap/cdna/cdna.ref153offsets64strm...done (234,475,312 bytes, 0.23 sec)
        Pre-loading ref positions, kmer 15, interval 3......done (276,173,052 bytes, 0.05 sec)
        Starting alignment
        Failed attempt to alloc 18446744073709550532 bytes
        Exception:  Allocation Failed  raised at indexdb.c:2885
        /cromwell-executions/detectFusions/962429bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/log/defuse.12.sh: line 6:  7481 Segmentation fault      (core dumped) /usr/local/bin/gmap -D defuse-data/gmap -d cdna -f psl /cromwell-executions/detectFusions/962429bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakpoints.split.001.fa > /cromwell-executions/detectFusions/962429bb-ddfa-456a-ab35-c29cf554e409/call-deFuse/execution/OUT/jobs/breakpoints.split.001.fa.cdna.psl.tmp
        
        real    0m1.262s
        user    0m0.046s
        sys     0m0.564s

```

Run within the docker container but not using Cromwell, the output of that command looks like this:
```
Starting defuse command:
        /usr/local/bin/gmap -D Program_required_data/deFuse/defuse-data/gmap -d cdna -f psl  #<1 > #>1
Reasons:
        /mnt/Workflow_runs/2_fusion_detection_tools/BT474/BT474_deFuse_0.8.1/jobs/breakpoints.split.001.fa.cdna.psl m
issing
Success for defuse command:
        /usr/local/bin/gmap -D Program_required_data/deFuse/defuse-data/gmap -d est4 -f psl  /mnt/Workflow_runs/2_fus
ion_detection_tools/BT474/BT474_deFuse_0.8.1/jobs/breakpoints.split.001.fa > /mnt/Workflow_runs/2_fusion_detection_to
ols/BT474/BT474_deFuse_0.8.1/jobs/breakpoints.split.001.fa.est.4.psl.tmp
Return codes: 0
Job output:
        Running on a4980b348957
        GMAP version 2018-07-04 called with args: /usr/local/bin/gmap.avx2 -D Program_required_data/deFuse/defuse-dat
a/gmap -d est4 -f psl /mnt/Workflow_runs/2_fusion_detection_tools/BT474/BT474_deFuse_0.8.1/jobs/breakpoints.split.001.fa
        Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
        Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
        Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17 
        Finished checking compiler assumptions
        Pre-loading compressed genome (oligos)......done (185,456,136 bytes, 45278 pages, 6.22 sec)
        Pre-loading compressed genome (bits)......done (185,456,160 bytes, 45278 pages, 7.44 sec)
        Looking for index files in directory Program_required_data/deFuse/defuse-data/gmap/est4
          Pointers file is est4.ref153offsets64meta
          Offsets file is est4.ref153offsets64strm
          Positions file is est4.ref153positions
        Offsets compression type: bitpack64
        Allocating memory for ref offset pointers, kmer 15, interval 3...Attached new memory for Program_required_data/deFuse/defuse-data/gmap/est4/est4.ref153offsets64meta...done (134,217,744 bytes, 16.13 sec)
        Allocating memory for ref offsets, kmer 15, interval 3...Attached new memory for Program_required_data/deFuse/defuse-data/gmap/est4/est4.ref153offsets64strm...done (331,380,368 bytes, 38.82 sec)
        Pre-loading ref positions, kmer 15, interval 3......done (625,955,632 bytes, 54.79 sec)
        Starting alignment
        No paths found for 279
        No paths found for 396
        No paths found for 1308
        No paths found for 1785
        No paths found for 1880
        No paths found for 1883
        No paths found for 1947
        No paths found for 1948
        No paths found for 2184
        No paths found for 2262
        No paths found for 2403
        No paths found for 2536
        No paths found for 2577
        No paths found for 2742
       No paths found for 2756
        No paths found for 2907
        No paths found for 2919
        No paths found for 2921
        No paths found for 3058
        No paths found for 3298
        No paths found for 3837
        No paths found for 3942
        No paths found for 4020
        No paths found for 4124
        No paths found for 4274
        Processed 405 queries in 703.84 seconds (0.58 queries/sec)
        Removed existing memory for shmid 262152
        Removed existing memory for shmid 131076
        
        real    14m1.724s
        user    3m28.053s
        sys     0m13.563s
```

- The WDL I am using: [defuse.wdl.txt](https://github.com/broadinstitute/cromwell/files/2651338/defuse.wdl.txt). The commands I use when running this in the docker container interactively are the same

- I encounter the same error using Cromwell 32 and Cromwell 36

- A similar error was reported [here](https://bitbucket.org/dranew/defuse/issues/36/defuse-with-segmentation-error) for when deFuse was run on a server. I tried running the failing gmap command alone through Cromwell and it succeeded

- The breakpoints files that gmap uses as input for the failing steps differ (deFuse generates these files in earlier steps)

- Many gmap steps are run in deFuse; some do succeed when run through Cromwell

- The full log for the Cromwell version: 
[defuse.log](https://github.com/broadinstitute/cromwell/files/2653318/defuse.log)
- The full log for the docker version: 
[defuse.log](https://github.com/broadinstitute/cromwell/files/2653319/defuse.log)

**Comment by patmagee** [comment]
@geoffjentry We are having some strange issues with this. Likely the `defuse` software is not written that well, however Its odd how the tool runs fine in a docker, so long as that docker is not run through cromwell either locally or in the cloud.

Does Cromwell set any specific environment variables or properties related to memory maybe?

**Comment by aednichols** [comment]
Thanks for the report, we'll check it out.

It seems that something about running inside Cromwell causes the tool to attempt allocating `18446744073709550532 bytes`, or 18.45 exabytes!

**Comment by aednichols** [comment]
In the Cromwell log, I see
```
Attached existing memory
[...]
Failed attempt to alloc 18446744073709551612 bytes
```
in runs where the tool segfaults, while good runs in the Cromwell log and _all_ runs in the Docker log print 
```
Attached new memory
```
What does this mean in the context of the tool?

**Comment by aednichols** [comment]
Partially answering my own question: https://github.com/juliangehring/GMAP-GSNAP/blob/master/src/access.c#L595-L623

If the `shmget` on line `595` succeeds because an existing shared memory segment exists, then we enter the `else if` block and end up printing `Attached existing memory`.

**Comment by hkeward** [comment]
Ok - I have made it work via Cromwell using a specific version of deFuse / gmap / the reference dataset.
The reference dataset is built after downloading deFuse and gmap and I think it uses those tools to build the reference indexes.

Here is what I've found:

## Works locally and on Cromwell:
- deFuse 0.6.2
- gmap 2014-08-20
- Reference set ensembl v 75 (built using deFuse and gmap of the above versions)

## Works locally, fails on Cromwell:
- deFuse 0.8.1
- gmap 2018-07-04
- Reference set ensembl v 69 (built using deFuse and gmap of the above versions)

## Works locally, fails on Cromwell:
- deFuse 0.6.2
- gmap 2018-07-04
- Reference set ensembl v 69 (built using deFuse 0.8.1 and gmap 2018-07-04).

## Fails locally and on Cromwell:
- deFuse 0.6.2
- gmap 2018-07-04
- Reference set ensembl v 75 (built using deFuse 0.6.2 and gmap 2014-08-20)


It seems like only when using an old version of deFuse, old gmap, and a newer reference set will deFuse run successfully via Cromwell.

I am still in the dark about why some of these combinations succeed locally and don't work on Cromwell, but it looks like the heart of the problem is in newer versions of gmap.

**Comment by aednichols** [comment]
That is quite some digging you've done! I hope you were able to reach an acceptable working configuration.

I am going to go ahead and close this issue because there is not a clear Cromwell bug here as far as I can see.

**Comment by X-WJ** [comment]
> Thanks for the report, we'll check it out.
> 
> It seems that something about running inside Cromwell causes the tool to attempt allocating `18446744073709550532 bytes`, or 18.45 exabytes!

Hi，i also got this problem while running the gmap on Linux shell  ,it shows that is need such memory.
 Failed attempt to alloc 18446744073709551600 bytes
Exception:  Allocation Failed  raised at indexdb.c:2886
Segmentation fault
.Could you please tell me how you solve this problem ?
