### ISSUE TITLE
Add 'asia.gcr.io' as an allowable docker source

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4466]
Per https://cloud.google.com/container-registry/docs/pushing-and-pulling:

>The four options are:
>
> gcr.io hosts the images in the United States, but the location may change in the future
> us.gcr.io hosts the image in the United States, in a separate storage bucket from images hosted by gcr.io
> eu.gcr.io hosts the images in the European Union
> asia.gcr.io hosts the images in Asia

Cromwell today would appear to support the first three but not the last, `asia.gcr.io`.

The place in code that seems to be at fault is: https://github.com/broadinstitute/cromwell/blob/develop/dockerHashing/src/main/scala/cromwell/docker/registryv2/flows/gcr/GoogleFlow.scala#L20

**Comment by kshakir** [comment]
`gcr.io` domains come and go: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/59

If we don't want to keep require a recompile + redeploy whenever gcr creates or removes a new subdomain this fix should be more flexible.

**Comment by Horneth** [comment]
I will likely fix this as part of https://github.com/broadinstitute/cromwell/issues/4352

**Comment by ruchim** [comment]
@kshakir when you say more flexible...do you mean something in the config? even that requires a redeploy .

**Comment by Horneth** [comment]
I think we actually don't need an explicit listing of the supported regions at all (even in the config) and can have Cromwell use the right hostname based on what's in the docker string

**Comment by Horneth** [comment]
Done with https://github.com/broadinstitute/cromwell/pull/4472
