### ISSUE TITLE
Copying input files fails with1024 character path limit

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/cromwell#4471]
Jeff, Thibault and all;
I'm testing the latest development Cromwell which supports GCP runs using CWL (#3724). Thank you so much for this support. My bcbio test pipelines are running but I'm hitting an issue during copying input files from some nested subworkflows. There appears to be a 1024 character limit which we hit due to the combination of the root execution directory and the nested sub-workflow path from Cromwell:
```
Copying file:///cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-calculate_sv_coverage/shard-0/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-calculate_sv_bins/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-postprocess_alignment/shard-0/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-postprocess_alignment_to_rec/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-alignment/shard-0/wf-alignment.cwl/94c8f53c-dad4-4c48-9e09-f6927356f352/call-merge_split_alignments/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-alignment/shard-0/wf-alignment.cwl/94c8f53c-dad4-4c48-9e09-f6927356f352/call-process_alignment/shard-0/cromwell_root/align/Test2/Test2-sort.bam [Content-Type=application/octet-stream]...
/ [0/1 files][    0.0 B/  3.7 MiB]   0% Done                                    
BadRequestException: 400 The maximum object length is 1024 characters, but got a name with 1055 characters: ''gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-...''
CommandException: 1 file/object could not be transferred.
Copying file:///cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-calculate_sv_coverage/shard-0/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-calculate_sv_bins/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-postprocess_alignment/shard-0/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-postprocess_alignment_to_rec/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-alignment/shard-0/wf-alignment.cwl/94c8f53c-dad4-4c48-9e09-f6927356f352/call-merge_split_alignments/cromwell_root/bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-alignment/shard-0/wf-alignment.cwl/94c8f53c-dad4-4c48-9e09-f6927356f352/call-process_alignment/shard-0/cromwell_root/align/Test2/Test2-sort.bam.bai [Content-Type=application/octet-stream]...
/ [0/1 files][    0.0 B/  184.0 B]   0% Done                                    
BadRequestException: 400 The maximum object length is 1024 characters, but got a name with 1059 characters: ''gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295/call-...''
CommandException: 1 file/object could not be transferred.
```
We could avoid in this case by shortening the folder name we're using for cromwell storage but I'm worried about hitting this later since it will be dependent on sample names (the `Test2` in these paths) and users correctly setting a short root path.

Do you know where this limit originates from? Is there any way to work around it? Thanks for any suggestions.

**Comment by Horneth** [comment]
Hi Brad,

Interesting, thanks for reporting this. I did run into a similar issue when I started testing and I merged [this PR](https://github.com/broadinstitute/cromwell/pull/4358) which should have at least made this less likely to happen. I think the issue comes from gsutil or maybe even the gcs API that appears to have a limit on the file path length.
You said you're using the latest development Cromwell ? Did you build the jar yourself from the `develop` branch ?
Can you also point me to the CWL workflow you're trying to run ?

Thanks

**Comment by chapmanb** [comment]
Thanks so much for walking through this. The tests are develop built on Friday after the merge. This is the CWL workflow I'm running, which isn't much different than the ones we've tested on but has everything in Google Storage:

https://github.com/bcbio/test_bcbio_cwl/tree/master/gcp

and this is the configuration:

https://gist.github.com/chapmanb/93d5468ac691012eaf70e67c17ed2498

It's running good up until this point, which I'm excited about. I figured I triggered the issue by having a slightly longer root location:

https://gist.github.com/chapmanb/93d5468ac691012eaf70e67c17ed2498#file-bcbio-cromwell-gcp-conf-L89

Thanks again for helping look at it.

**Comment by Horneth** [comment]
Hi Brad, thanks. I'm looking at the error and the paths seem to have the same pathological repetition of the root  (`bcbiotest/gcp/work_cromwell/main-somatic.cwl/c21b8bf4-9f80-45a3-9a23-f345b4d8f295`) that I was hoping to have fixed in that PR I mentioned before. Can you double check you're running from the latest develop ?
I'm re-running it right now as well with a longer root path to see if I can reproduce it.

**Comment by chapmanb** [comment]
Thibault;
You're exactly right, I hadn't compiled against the right branch with this fix. Apologies for wasting your time looking at this, once I got the most up to date version compiled it avoided this problem and the GCP test run I mentioned ran all the way through cleanly to the end. Brilliant, thank you for all the help getting this in place and sorry again for the erroneous report.

**Comment by Horneth** [comment]
That's great news, and no worries at all, glad it worked !

**Comment by TMiguelT** [comment]
I just noticed this issue, do you think it's the same as the one I noticed a while ago? https://github.com/broadinstitute/cromwell/issues/4279. If so I can close mine
