### ISSUE TITLE
CromIAM: Allow submission whitelist to be optional

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4475]
At the moment there's a concept of a submission whitelist for users in CromIAM. Allow for this to be optional for situations where all users are allowed to submit workflows, this will reduce traffic between CromIAM & Sam

Although this CromIAM will be exposed to the internet, the Cromwell service will still be protected from drive-by whitelist-not-specified submissions by the Google authentication.  This authentication will be enforced by the proxy.

**Comment by ruchim** [comment]
@dvoet @danbills

**Comment by geoffjentry** [comment]
This is a requirement for FC prod

I hadn't considered removing `collectionName` but it's an interesting point. It'd certainly remove the wonkiness of having a subtly different API and might make the swagger headaches simpler

**Comment by danbills** [comment]
seems `collectionName` should be optional as well, as how does one who doesn't submit a collection submit a collectionName?

**Comment by geoffjentry** [comment]
`collectionName` is the argument and it is optional. If it is not provided, CromIAM pulls it from the user id in the OIDC header as the default.

I think @ruchim isn't quite right above but haven't had a chance to chat about it.

Firecloud will be manually setting the appropriate label in Cromwell directly as part of their workflow submissions but that should not affect CromIAM in any shape/way/form
