### ISSUE TITLE
January 7th Demo List

### ISSUE THREAD

**Issue by rebrown1395** [broadinstitute/cromwell#4480]

**Comment by ruchim** [comment]
1. JMUI features! (Bec)
2. Keys function in WDL (Chris!)
3. Womtool as a service, /describe endpoint (Adam)
4. PAPI v2 Boot Disk Auto-sizing--WDL & CWL (Jeff?)
5. Call Caching Names for Backends (Miguel)
6. Size and File Hash for DRS files (Saloni)
7. Progress on Horizontal Cromwell (Khalid & Miguel?)
