### ISSUE TITLE
Can't escape quotes in WDL 1.0

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4500]
Originally reported here:
https://gatkforums.broadinstitute.org/gatk/discussion/comment/54964#Comment_54964

Example workflow as the acceptance criteria:
```
version 1.0
workflow example{
    call print{
    }
}

task print{
    input{
        String s = "\""
    }
    command{
        echo "${s}"
    }
}
```

**Comment by ruchim** [comment]
@cjllanwarne 

Below are the logs around running Cromwell on the same WDL but under the "develop" version

[escape_wdl_cromwell.log](https://github.com/broadinstitute/cromwell/files/2691202/escape_wdl_cromwell.log)

**Comment by aednichols** [comment]
From the [WDL 1.0 spec](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#whitespace-strings-identifiers-constants):
>`$string` can accept the following between single or double-quotes:
>- Any character not in set: `\\`, `"` (or `'` for single-quoted string), `\n`
>- An escape sequence starting with`\\`, followed by one of the following characters: `\\`, `"`, `'`, `[nrbtfav]`, `?`
>[...]

so I think the example workflow should be
```
String s = "\\""
```

Nevertheless, this does not work in Cromwell's WDL 1.0 implementation as of today's date:
```
Failed to create WDLOM:
Unrecognized token on line 12, column 27:

    String quote = " \\" "
                          ^
```

**Comment by aednichols** [comment]
Adding this case to `string_escaping.wdl`, we see
```
ScalaTestFailureLocation: wdl.draft3.transforms.ast2wdlom.WdlFileToWdlomSpec at (WdlFileToWdlomSpec.scala:44)
org.scalatest.exceptions.TestFailedException: Failed to create WDLOM:
Unrecognized token on line 12, column 26:

    String quote = " \" "
                         ^
```

**Comment by aednichols** [comment]
On the forum, the most recent response from the user is
>For others' benefit, I had a discussion with Ruchi about this, and this is a bug which should be fixed in Cromwell 37.

I think we may have fixed this in https://github.com/broadinstitute/cromwell/pull/4135 but I will confirm.

**Comment by aednichols** [comment]
The root cause is that the regex
```
(.*?)(?=\\$\\{|~\\{|\")
```
used in the parser matches the string
```
"leading text \" trailing text"
```
as two separate chunks, `leading text \` and ` trailing text` as tested on regexr.com

**Comment by aednichols** [comment]
However - in WDL `development` the regex is the same!

**Comment by ruchim** [comment]
@aednichols that is mysterious! Will it be possible to change the regex? Or is that a spec change?

**Comment by aednichols** [comment]
I think the regex was a red herring, but the bug should still be fixable without a spec change (likely a grammar bugfix).
