### ISSUE TITLE
Refresh token functionality: fix tests or remove feature

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4504]
In https://github.com/broadinstitute/cromwell/pull/4502 I ignored three tests related to the refresh token functionality because they were blocking all other merges and I had no idea how to fix them. My rationale for doing so is my impression the feature is unused/end-of-life.

@ruchim to decide whether we
1. Fix the tests
or
2. Delete the feature

**Comment by kshakir** [comment]
If the feature is removed, also cleanse it from [the docs](https://cromwell.readthedocs.io/en/stable/search.html?q=refresh_token).

**Comment by geoffjentry** [comment]
The feature is to be removed. I wouldn't put any effort into fixing the tests. Whether or not you want to put the effort in to excise the feature now is up to you for now :)
