### ISSUE TITLE
Certain heterogeneous maps validate in Womtool, fail in Cromwell

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4512]
Based on a report from @curoli 

I can't immediately reason out what the correct behavior is (post-vacation fuzziness...) so this is just a  a log of stuff that looked suspicious to me.

---

A workflow like
```
version 1.0

workflow test {
  
  Map[String, String] m = {"a": "a", "b": "b"}
  String s = "string"

  output {
    File write_attempt = write_json({"m": m, "s": s})
  }
}
```
validates in Womtool but fails at runtime with error
```
WorkflowManagerActor Workflow 2a3db889-e126-467b-be60-6abb815ea46e failed (during ExecutingWorkflowState):
  java.lang.UnsupportedOperationException:
    Cannot construct WomMapType(WomStringType,WomAnyType) with mixed types:
      Map(
        WomString(m) -> WomMap(WomMapType(WomStringType,WomStringType),Map(WomString(a) -> WomString(a), WomString(b) -> WomString(b))),
        WomString(s) -> WomString(string)
      )
```

---

The problem is not so simple as heterogeneous types in the map values; the workflow
```
version 1.0

workflow test {
  
  String s = "string"
  Float f = 0.1
  File file = "asdf"

  output {
    File write_attempt = write_json({"s": s, "f": f, "file": file})
  }

}
```
works just fine:
```
{"s":"string","f":"0.1","file":"asdf"}
```

---

Interestingly, if we take out `String s = "string"` we do get an error in Womtool, but it's a confusing one - why would we say a map value has to be an `Object` when we clearly used `String`, `Float`, and `File` right above?
```
version 1.0

workflow test {
  
  Map[String, String] m = {"a": "a", "b": "b"}

  output {
    File write_attempt = write_json({"m": m})
  }
}
```
yields
```
womtool validate any_map.wdl 
Failed to process workflow definition 'test' (reason 1 of 1):
  Failed to process declaration 'File write_attempt = write_json({ "m": m })' (reason 1 of 1):
    Failed to process expression 'write_json({ "m": m })' (reason 1 of 1):
      Invalid parameter 'MapLiteral(Map(StringLiteral(m) -> IdentifierLookup(m)))'. Expected 'Object' but got 'Map[String, Map[String, String]]'
```

**Comment by curoli** [comment]
In the second example (the one that works), it is surprising that the Float ends up a String in the JSON. It should become a number. I suspect if all values can be converted to String, it will construct a Map[String, String].

**Comment by antonkulaga** [comment]
Looks like your bug is similar to mine https://github.com/broadinstitute/cromwell/issues/4555

**Comment by aednichols** [comment]
WDL maps can't be heterogeneous; updating the workflow to use object fixes the issue.

```
version 1.0

workflow test {
  
  Map[String, String] m = {"a": "a", "b": "b"}
  String s = "string"

  output {
    File write_attempt = write_json(object {m: m, s: s})
  }
}
```

**Comment by antonkulaga** [comment]
>WDL maps can't be heterogeneous; updating the workflow to use object fixes the issue.

He-he, object is not supported anymore and sturcts are not fully supported yet, as whenever I try to return a struct - it crashes at runtime!

**Comment by aednichols** [comment]
Removing object is an accepted change for a future version of WDL, but Cromwell's WDL 1.0 implementation does and will continue to support it, so I think the example workflow is a reasonable basis to close this issue (whose motivating workflow was also 1.0).
