### ISSUE TITLE
Make the task scripts compatible with Busybox limitations

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4536]
Cromwell: 36
Backend: Google Cloud

When running a CWL snpEff  tool using Cromwell ([CWL is here](https://github.com/broadinstitute/cromwell/files/2743866/snpEff.cwl.txt)), I get the following errors: ([full error log](https://github.com/broadinstitute/cromwell/files/2743887/snpeff_indels-stderr.log))

```
xargs: invalid option -- 'I'
find: unrecognized: -empty
```

In other words, Cromwell is generating a script that uses `xargs -I` and `find -empty`, flags which are not compatible with Busybox ([full Cromwell-generated script](https://github.com/broadinstitute/cromwell/files/2743877/script.txt)). The reason this matters is that all [Biocontainers](https://biocontainers.pro/) are based on Busybox, and I would say they represent a majority of the bioinformatics containers, so ensuring compatibility is in everyone's interest.

Might it be possible to edit the Cromwell script to use a smaller subset of these command line flags?

**Comment by TMiguelT** [comment]
I think it's reasonable to assume the Bash shell, since's it's mostly ubiquitous now (or maybe it could be rewritten to work with `sh`?). Adding Alpine and Busybox to the testing suite sounds like an excellent idea. Is this as simple as just reducing the use of newer flags/utilities and ensuring those tests pass?

**Comment by geoffjentry** [comment]
I did just see that both Alpine & Busybox **are** in some of our tests, so it helps make the point that we do try here :) Clearly we're not hitting **this**

**Comment by DavyCats** [comment]
Since this was labeled as `CWL`, I would just like to note that this is also the case for `WDL` workflows.

**Comment by geoffjentry** [comment]
@DavyCats Agreed that this has nothing to do with CWL, it's been a sore spot long before we had CWL support. 

I'm also going to remove the `redwood` label as it's not really an issue for that team (for the non-Broad folks, there are 2 separate teams who work different aspects of these things)

**Comment by mcovarr** [comment]
When I tried to reproduce this locally Cromwell completed the workflow successfully despite the fact that `find` had been invoked with invalid syntax and no placeholder `.file`s had been created in my empty directories. It looks like our wrapper script is not checking for failures at this point.

**Comment by TMiguelT** [comment]
Is this issue fixed?

**Comment by mcovarr** [comment]
Yes, sorry that wasn't clear. This should be fixed in Cromwell 37 thanks to @DavyCats contribution in #4597.
