### ISSUE TITLE
WaaS /describe: performance testing

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4573]
Use [Apache bench](https://httpd.apache.org/docs/2.4/programs/ab.html) or similar to measure how many requests per second we can handle.

To submit the multi-part form, use the `-p` option for a post data file, example contents below. You can generate your own by capturing the network requests Swagger makes.
```
------WebKitFormBoundaryRwwHyBadF8e8Mwbp
Content-Disposition: form-data; name="workflowUrl"

https://firecloud-orchestration.dsde-alpha.broadinstitute.org/ga4gh/v1/tools/anichols:cnv_somatic_pair_workflow/versions/1/plain-WDL/descriptor
------WebKitFormBoundaryRwwHyBadF8e8Mwbp
Content-Disposition: form-data; name="workflowType"

WDL
------WebKitFormBoundaryRwwHyBadF8e8Mwbp
Content-Disposition: form-data; name="workflowTypeVersion"

draft-2
------WebKitFormBoundaryRwwHyBadF8e8Mwbp--
```
In my preliminary testing, throughput was about 15 validations per second of the workflow above. I had `ab` make multiple requests simultaneously with the `-c` option (don't remember the concurrency level though).

N.B. the above us a pretty tough scenario - workflow by URL with many HTTP imports. Our production use case uses files, not URLs.

**Comment by aednichols** [comment]
Excellent point from @cjllanwarne: we are protected from the "workshop scenario" - many users validating the same WF at the same time - by the Rawls cache

**Comment by ruchim** [comment]
AC:

**Case 1:** 
Benchmark the behavior of these endpoints given a few different style of workflows:
Option A: Hello World workflow
Option B: Five Dollar Genome workflow
Option C: CGA Production Workflow

For each case, run concurrent requests to the `/describe` endpoint , benchmark the response time and do so for a variety of concurrent requests: 15, 30, 50, 100...

**Case 2:**
Another case can be to see how many raw GitHub pages we can resolve (via http imports) before we start seeing issues from Github -- and observe we fail gracefully.

**Comment by aednichols** [comment]
The CGA "CPU WDL" validates pretty quickly. With 10,000 requests at a concurrency of 20, the 99% latency is just 249 ms

**Comment by aednichols** [comment]
Womtool on the command line takes wildly longer, probably all due to JVM startup cost
```
anichols@wm97a-a85 ~/Dropbox/Broad Institute/Bugs/cromwell-4573 $ time womtool validate cpu_WDL.wdl 


real	0m3.585s
user	0m7.393s
sys	0m0.552s
```

**Comment by aednichols** [comment]
Note:

There exists an optional namespace cache in the WDL draft-2 version of `validateNamespace`.

WaaS uses only `getWomBundle` and `createExecutable`, so it currently has no interaction with the cache for any language version.

**Comment by aednichols** [comment]
1m requests with Chet's WDL, no cache
```
anichols@wm97a-a85 ~/Dropbox/Broad Institute/Bugs/cromwell-4573 $ ab -n 1000000 -c 10 -T "multipart/form-data; boundary=----WebKitFormBoundaryU9q0VZiViUYYQmkV" -p ./postfile http://localhost:8000/api/womtool/v1/describe
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Completed 1000000 requests
Finished 1000000 requests


Server Software:        akka-http/10.1.5
Server Hostname:        localhost
Server Port:            8000

Document Path:          /api/womtool/v1/describe
Document Length:        178551 bytes

Concurrency Level:      10
Time taken for tests:   5304.621 seconds
Complete requests:      1000000
Failed requests:        0
Total transferred:      178708000000 bytes
Total body sent:        178756000000
HTML transferred:       178551000000 bytes
Requests per second:    188.51 [#/sec] (mean)
Time per request:       53.046 [ms] (mean)
Time per request:       5.305 [ms] (mean, across all concurrent requests)
Transfer rate:          32899.53 [Kbytes/sec] received
                        32908.37 kb/s sent
                        65807.89 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    6  12.7      5    1165
Processing:    12   44  28.2     39    1203
Waiting:        0   35  25.1     31    1178
Total:         12   50  30.7     44    1207

Percentage of the requests served within a certain time (ms)
  50%     44
  66%     47
  75%     50
  80%     51
  90%     59
  95%    104
  98%    154
  99%    167
 100%   1207 (longest request)
```

**Comment by aednichols** [comment]
The CPU WDL actually takes more like 600ms.
```
ab -n 20 -v 4 -c 1 -T "multipart/form-data; boundary=----WebKitFormBoundaryU9q0VZiViUYYQmkV" -p ./postfile http://localhost:8000/api/womtool/v1/describe
```
```
Percentage of the requests served within a certain time (ms)
  50%    566
  66%    572
  75%    572
  80%    575
  90%    586
  95%    596
  98%    596
  99%    596
 100%    596 (longest request)
```

**Comment by aednichols** [comment]
Idea for how to make this CI compatible
- Use apachebench Docker
- Serve HTTP imports from a Mock Server Docker, configured using its rest API

**Comment by aednichols** [comment]
Four cases to test:
1. Vanilla WDL
2. WDL with HTTP imports, imports are instant
3. WDL with HTTP imports, imports take a few seconds
4. WDL with HTTP imports, imports time out
   - mock server waits longer than `HttpResolver#innerResolver`
