### ISSUE TITLE
Status endpoint that reports health of CromIAM, Cromwell, & SAM

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4594]
Should aggregate a response from Cromwell & SAM and return those as a report of CromIAM's health (and its dependencies).

**Comment by kshakir** [comment]
Are there updated acceptance criteria for this ticket, or can this be marked as complete? This currently works on the caas-dev server:

```
$ curl https://cromwell.caas-dev.broadinstitute.org/engine/v1/status 2>/dev/null | jq .
{
  "ok": true,
  "systems": {
    "Cromwell": {
      "ok": true
    },
    "Sam": {
      "ok": true
    }
  }
}
$ 
```

**Comment by danbills** [comment]
I poked through the code but didn't see the endpoint.  Great, thanks @kshakir and @salonishah11 !
