### ISSUE TITLE
cromwell with AWS EFS

### ISSUE THREAD

**Issue by ylipacbio** [broadinstitute/cromwell#4602]
We are looking for a general guidance regarding how to use AWS EFS system with cromwell. 
Specifically, guidance of setup cromwell to recognize mounted EFS files in the backend and run jobs on AWS batch. 

Details of what we have attempted to run the workflow using EFS on AWS:
- We tried specifying a aws EFS file system as one of the filesystems both within backend and engine constructs in addition to S3. But we get this error: "Cannot find a filesystem with name efs in the configuration. Available filesystems: ftp, s3, demo-dos, gcs, oss, http". If I just specify EFS, Cromwell does not start, errors out looking for S3.

- Also, the EFS is mounted on my AWS batch computes. How do I specify the mount point to the container(I am asking this because, I don’t have control over creating AWS job definitions)?

We have checked lots of resources online but could not find any. And we have tried to ask questions on gatk forum with no luck: https://gatkforums.broadinstitute.org/wdl/discussion/23380/using-aws-backend-with-efs

Searched github issues, we found a similar issue opened here 7 days ago with no answer #4579 AWS backend with own source path to mount.

Thanks for looking into this issue.

**Comment by illusional** [comment]
Hey @ylipacbio, I'm not from Cromwell but wanted to throw out a comment. For Cromwell to pull files, a [_Filesystem_](https://cromwell.readthedocs.io/en/stable/filesystems/Filesystems/) needs to be implemented in Scala. 

As far as I'm aware, Amazon's EFS is **NOT** implemented, and cannot be configured to work with Cromwell. The available filesystems are ftp, s3, demo-dos, gcs, oss, http (and unix).

If you know some scala, [this](https://github.com/broadinstitute/cromwell/tree/develop/filesystems) might be good place to start on how to implement one.

**Comment by ylipacbio** [comment]
Thanks for letting me know this solution. @illusional 

I am closing this issue as we have find a way to go around it.
