### ISSUE TITLE
Overhaul bcbio testing strategy

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4613]
Discussed at standup 2019-02-04

Right now, bcbio uses:
- pinned CWL (checked in)
- floating docker
- floating data (not controlled by us)

As such, it breaks pretty frequently due to external factors, negating its usefulness as a regression test.

For this ticket, update our bcbio configuration to be two separate jobs - one fully floating to test compatibility at the cutting edge, one fully pinned to serve as a stable regression test.

Floating job:
- pull CWL from Brad's repo
- floating docker [same as now]
- floating data [same as now]

Pinned job:
- pinned CWL [same as now]
- our own stable copy of the data
- our own stable copy of the dockers

**Comment by geoffjentry** [comment]
Pinging @chapmanb in case he has thoughts on what we could do here

**Comment by chapmanb** [comment]
Adam and Jeff;
Thanks for this. I'm definitely agreed I don't want to break your tests every time we accidentally introduce a bug in bcbio. We have tagged versions of the Docker images (https://quay.io/repository/bcbio/bcbio-vc?tab=tags) so could pin to a specific CWL with a specific Docker tag. Data doesn't change as often in a back-incompatible way but you could also have a copy of that if it becomes an issue.

We could generate CWL that ties to a specific Docker build, or just have your tests download the tagged version we've tested on. How aggressive is Cromwell at updating the local Docker version based on what's in the CWL? If it would leave a pre-downloaded and ready to go Docker alone, it seems like a pre-pull from a known tag and the pinned CWL should do most of what we need. Would that work?

**Comment by aednichols** [comment]
To be clear @chapmanb, we never think of it as "you breaking our tests", but rather "we should test differently so we don't have to bug Brad as much when things change"
