### ISSUE TITLE
Add centaur CI for MariaDB support

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#4618]
At some point we will have to update our liquibase library, either for vulnerability patches or other bug fixes. 

However there is a report that the current liquibase version (3.6.3) plus the way our changelog differentiates databases (ex: using strings matching for things like `mysql`) causes an issue with MariaDB.

This ticket is not about updating liquibase. Before that can occur we need a CI regression test to ensure that MariaDB is supported.

A/C:
- At least centaur-local running against mariadb 10.3+

Links:
- https://github.com/broadinstitute/cromwell/issues/4605
- https://www.sourceclear.com/vulnerability-database/security/cross-site-scripting-xss-/java/sid-6098
- https://liquibase.jira.com/browse/CORE-3203
- https://liquibase.jira.com/browse/CORE-3263 (may not be related) 
- https://docs.travis-ci.com/user/database-setup/#mariadb
- https://docs.travis-ci.com/user/build-matrix/#explicitly-including-jobs

**Comment by aednichols** [comment]
Liquibase went to 4.8.0 in https://github.com/broadinstitute/cromwell/pull/6710 and we do have the test in place.
