### ISSUE TITLE
Detritus missing for call cache jobs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4622]
It appears that when a call cache hits on PAPIv1, the `stdout` and `stderr` links in the metadata are incorrect.

**Comment by danbills** [comment]
@ruchim are we addressing v1 issues?

**Comment by gemmalam** [comment]
also applies to V2

**Comment by salonishah11** [comment]
Closing this issue as the inconsistent links for `stdout` and `stderr` in metadata are occurring only in V1, and currently there is no plan for fixing this in near future.
