### ISSUE TITLE
error running cromwell on SLURM: "Fatal exception polling for status"

### ISSUE THREAD

**Issue by jfroula** [broadinstitute/cromwell#4651]
I think I am experiencing a bug in cromwell version 37.  The problem occurs when I submit a job to SLURM.  The job gets submitted but cromwell crashes without waiting for the job to finish.  Cromwell works fine when run locally or when I use version 36.  

## my command 
 java is v1.8
```
java -Dconfig.file=cori.conf -jar cromwell-37.jar run test.wdl 
```

## wdl 
```
workflow jgi_dap_leo {

    call doSomething { }

}

task doSomething {
    runtime {
        mem: "8G"
        cpu: 1
        time: "0:60:0"
        backend: "SLURM"
    }
    command {
        free
    }
}
```

## config 
```
include required(classpath("application"))

system {
    job-rate-control {
        jobs = 1
        per = 1 second
    }
}

backend {
    default="Local"
    providers {
        SLURM {
            actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
            config {
                runtime-attributes = """
                String time
                Int cpu
                String mem
                """

                submit = """
                sbatch -J leo_dap -t ${time} -c ${cpu} --mem=${mem} -C haswell -q regular -A m342 --wrap "/bin/bash ${script}"
                """
                kill = "scancel ${job_id}"
                check-alive = "squeue -j ${job_id}"
                job-id-regex = "Submitted batch job (\\d+).*"
            }
        }
    }
}
```

## system I'm running on 

NERSC's cori machines:
Cray XC40, comprised of Intel Xeon "Haswell" processor nodes

## cromwell logs
[cromwellError.txt](https://github.com/broadinstitute/cromwell/files/2866540/cromwellError.txt)

**Comment by flying-polarbear** [comment]
i have the same  problem, the job is normally submitted to slurm, but wdl got stderr: 
 [warn] DispatchedConfigAsyncJobExecutionActor [78ed5dc0report.t1:NA:1]: Fatal exception polling for status. Job will fail
and crashed right away

**Comment by flying-polarbear** [comment]
i have the same problem, the job is normally submitted to slurm, but wdl got stderr:
[warn] DispatchedConfigAsyncJobExecutionActor [78ed5dc0report.t1:NA:1]: Fatal exception polling for status. Job will fail
and crashed right away

cromwell: v37
slurm-wlm 17.11.2

**Comment by chapmanb** [comment]
FYI, this appears to be the same issue as #4560
