### ISSUE TITLE
caching of the last executed task does not work if workflow output throws error

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#4664]
When I was debugging my issue with maps ( https://github.com/broadinstitute/cromwell/issues/4663 ) I noticed (multiple times)
![screenshot_2019-02-15 screenshot](https://user-images.githubusercontent.com/842436/52890479-9e730a80-318d-11e9-9858-e6961d935d62.png)
 that even though all the tasks succeeded, the latest task (salmon) did not cache when a runtime error was thrown with workflow output type. I think as the task itelf succeeded it should be cached, so users will not loose several hours when only a small adjustment in the output type is needed.

**Comment by geoffjentry** [comment]
Hi @antonkulaga - we understand the underlying point you're making, this isn't the first time it has come up. However we try to take a less interactive view of caching and treat it more as an all or nothing event. While we might relook at this in the future, for now modifying caching in this way is not on our radar
