### ISSUE TITLE
if workflow is a subworkflow give its parent id

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#4667]
As you know I am developer of a cromwell Client application that visualizes cromwell results https://github.com/antonkulaga/cromwell-client In any more or less complex workflow you usually have several subworkflows, visualizing such workflow in a flat way makes the user output messy. 
I will be very grateful if you can provide parent_id for each subworkflow so I can setup a hierarcy in the UI.

**Comment by geoffjentry** [comment]
@antonkulaga Are you not getting `parentWorkflowId` in your metadata?

**Comment by antonkulaga** [comment]
@geoffjentry let me rerun it again, maybe was my mistake

**Comment by geoffjentry** [comment]
@antonkulaga Thanks, let me know. It occurred to me that `parentWorkflowId` might not show up in the subworkflow's metadata (as opposed to calling metadata directly on that subworkflow's workflow id). But I haven't been in a position to test it myself.

**Comment by cjllanwarne** [comment]
There's an intention to add parentWorkflowId (or rootWorkflowId) to the metadata summary table which should allow us to query for it faster. I don't see any reason we couldn't also expose it in the `/query` result set too

**Comment by antonkulaga** [comment]
@cjllanwarne yes, having it in Query would be superhelpful as it saves a lot of time (I can display the hierarcy of workflows without the need to metadata on all of them)
