### ISSUE TITLE
Add a `pull-docker` hook for the config file

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4673]
There is a fairly large need to support custom container engines in Cromwell, for those HPC systems that cannot run docker. This is discussed in the PR here: #4635. 

Currently the only hook we have for custom container engines is the `submit-docker` field, which is a script that runs when a task is run that specifies a docker image. This lets us download the image from docker, and convert it to a custom format (probably the Singularity SIF format) before submitting a job to the queue that runs the image. However, in the case of a scatter job, this means downloading the same Docker image N times, converting it to SIF format N times, and using up N times as much storage as we would like. This issue is discussed in my comment [here](https://github.com/broadinstitute/cromwell/pull/4635#issuecomment-463890367), and a number of preceding comments.

If we had another hook for the `cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory`, called `pull-docker` that was run each time a Docker image needs to be pulled, then we could resolve this issue. The hook could run each time a new image is encountered in a given workflow, but only once each time, so that a scatter job would result in only one call to the hook. We would then have to find some way for the image built in the `pull-docker` hook to be communicated to the `submit-docker` hook. The default value of `pull-docker` would be some kind of no-op, because this is not needed using Docker itself. However, it would be invaluable for custom engines.

**Comment by illusional** [comment]
Would you envisage `pull-docker` return some sort of identifier, or location to the built image file that Cromwell could pass to the submit-docker. `udocker` (as far as I can tell) will also rebuild the container on every `run` (and `create`), and there seems to be no way to get it to skip the build if it exists.

**Comment by TMiguelT** [comment]
That's what I was thinking, yes. But that's a bit tricky because bash scripts don't really "return" anything. Perhaps each unique image (based on the hash) could be assigned its own directory within Cromwell, and that directory is set as the working directory for both `pull-docker` and `submit-docker`. Then, you can build the image in `pull-docker`, and run it in `submit-docker` by just globbing for a `.sif` file (or whatever format it is)

**Comment by geoffjentry** [comment]
Hi @TMiguelT - this is a great idea although it is unlikely it'll be on our roadmap over the next 6 months. We'd definitely entertain a PR if someone sees this and wants to explore that, but otherwise closing this issue for now and might revisit in the future
