### ISSUE TITLE
Cromwell with aws s3:  Access Denied 

### ISSUE THREAD

**Issue by hmkim** [broadinstitute/cromwell#4677]
Please check this issue.
When I configure the aws, I followed up this page. (https://docs.opendata.aws/genomics-workflows/
)
I did not use the all-in-one template. With 3 step configure, I setup the cromwell server (Custom AMI -> VPC..and etc -> cromwell server instance)

aws

```
task echoHello{
    command {
        echo "Hello AWS!"
    }
    runtime {
        docker: "ubuntu:latest"
    }

}

workflow printHelloAndGoodbye {
    call echoHello
}
```

[cromwell-server.log](https://github.com/broadinstitute/cromwell/files/2897001/cromwell-server.log)

**Comment by TimurIs** [comment]
Do you use cromwell-37?

**Comment by hmkim** [comment]
> Do you use cromwell-37?

Yes, I used cromwell-37

**Comment by TimurIs** [comment]
Well, it seems that it this particular version has a considerable number of bugs and glitches. Try to use cromwell-36 while they are fixing it.

**Comment by hmkim** [comment]
@TimothyTickle Ok. When I used cromwell-37, it works well. Thanks!
