### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by azzaea** [broadinstitute/cromwell#4678]
Hello,

It seems to me that cromwell (at least `cromwell-37.jar`) can run `version 1.0` WDL scripts. Would you confirm this? It would also be helpful if you had this info readily on the ReadTheDocs page (https://github.com/broadinstitute/cromwell/blob/develop/docs/LanguageSupport.md).

Thank you,
Azza

**Comment by geoffjentry** [comment]
Hi - yes, I can confirm this. Cromwell has had WDL 1.0 support for not quite a year now. You're right that this should be updated (pinging @cjllanwarne )

**Comment by cjllanwarne** [comment]
hey @azzaea - I'll take a look at improving this documentation asap! thanks!
