### ISSUE TITLE
Allow more GPU Types

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4691]
Today, when using Cromwell, only 2 GPU types are allowed:

https://github.com/broadinstitute/cromwell/blob/develop/supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributes.scala#L26-L27

However, there's many more gpu types that are actually available:
https://cloud.google.com/compute/docs/gpus/

AC: 
- Cromwell shouldn't whitelist GPU types that are allowed, and instead make it possible to request a GPU machine type of choice.
- If someone asks for a gpu type that's a bad string, record the error returned by Piplines API and add it to our docs to explain that an error that looks like "..." means an invalid GPU type, and add a link to the list of available GPU types to the Cromwell docs.

**Comment by cjllanwarne** [comment]
@ruchim I'm stealing this one to work on since there's been no progress since 3/4. Tell me if that's a wrong decision...
