### ISSUE TITLE
Cromwell retry file download

### ISSUE THREAD

**Issue by adamvonp** [broadinstitute/cromwell#4710]
Hi All, 

I am currently running Cromwell 36 in AWS batch (both Server and run mode) in one account, lets say ACCT1, and all of my resource files are cross account in another account (ACCT2). Intermittently jobs will fail due to a failure to download a reference file.

Error seen through the Cromwell proxy logs:

> aws s3   cp --sse AES256 --no-progress   s3://s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta.bwt   /cromwell_root//s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta.bwt          download failed: s3://s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta.bwt   to   ../cromwell_root/s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta.bwt   ("Connection broken: error(104, 'Connection reset by peer')",   error(104, 'Connection reset by `peer'))

I'm wondering if it is in the scope of Cromwell on AWS to have a file download retry, or check at least, rather than continuing the task with an empty file which may persist silently causing troubleshooting to be quite difficult.

Best,
Adam

**Comment by geoffjentry** [comment]
I believe this is resolved in #4749 but it requires the proxy image to be pushed & verified that this is resolved

**Comment by geoffjentry** [comment]
Closing as this should now be resolved. Please reopen if you stil encounter this
