### ISSUE TITLE
Feature request: clean up inputs after job completion

### ISSUE THREAD

**Issue by DavyCats** [broadinstitute/cromwell#4711]
When running a workflow which utilizes containers, soft-linking cannot be used for file-localization. If the data is also on a different device than the cromwell-execution directory (like might be the case on a cluster), the only remaining localization option is to copy the files. When running a workflow on larger numbers of samples, this can cause a huge overhead in disk usage.

For example, a reference fasta might be needed for multiple jobs for each sample, since the file gets copied for each job, you can easily end up with hundreds of copies of the same file.

It would, therefore, be very useful if cromwell would clean up the inputs for each job after the job has finished.

**Comment by myazinn** [comment]
Hi @DavyCats - 
This issue was mentioned in another PR, which was accepted. Is the problem you described still relevant?

**Comment by DavyCats** [comment]
Hi @myazinn,

@rhpvorderman indeed solved this issue by implementing the cached-copy localization strategy. So no, this issue is no longer relevant.
