### ISSUE TITLE
brew distribution is still pointing to release version 37

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/cromwell#4713]
https://formulae.brew.sh/formula/cromwell

Should it be pointing to 36.1?
(I'm assuming DSP "owns" that formula.)

**Comment by salonishah11** [comment]
Hey @SHuang-Broad, yes you are right it should be pointing to 36.1. There was some conversation going on for forcing HomeBrew to recognize 36.1 as the newest version. But that has became unnecessary now as a new release should be out soon. You can look at the HomeBrew conversation [here](https://github.com/Homebrew/homebrew-core/pull/37175).

**Comment by SHuang-Broad** [comment]
Ah, I see. Thanks @salonishah11 !
