### ISSUE TITLE
write_map strang output in WDL1.0(version 1.0)

### ISSUE THREAD

**Issue by aukluobo** [broadinstitute/cromwell#4722]
try follow wdl code in cromwell36
```
version 1.0

workflow test {
  Map[String,String] aa= {"key1": "value1", "key2": "value2"}
  call example { input:map=aa }
}

task example {
  input {
    Map[String, String] map
  }

  command {
    cat ${write_map(map)}
  }
}
```

get a strange tmp file 
"
cat 377f5912-77cb-409f-8888-ac46fef2c448/call-example/execution/write_map_6b29aeb5bdc2e2cffaf159a56d2ad1f4.tmp
key1    key2
value1  value2

"
but when using draft-2, the output is ok
"
cat 7435a991-a7be-400c-b503-94df322a619d/call-example/execution/write_map_4b4637e67d71685228a1ff8b94e7d3e1.tmp
key1    value1
key2    value2
"
can someone fix this in version1.0 ?

**Comment by aednichols** [comment]
Thank you for reporting! Confirmed using latest Cromwell `develop`:
```
key1	key2
value1	value2
```
versus
```
key1	value1
key2	value2
```

**Comment by aednichols** [comment]
This is a vector for possible silent data corruption with far-reaching consequences.

**Comment by aednichols** [comment]
The underlying problem is that in Cromwell's WDL 1.0 implementation
```
Map[String,String] aa= {"key1": "value1", "key2": "value2"}
```
is interpreted as
```
WomObject(Map(key1 -> WomString(value1), key2 -> WomString(value2)),WomObjectType)
```
instead of
```
WomMap(WomMapType(WomStringType,WomStringType),Map(WomString(key1) -> WomString(value1), WomString(key2) -> WomString(value2)))
```
in draft-2.

`write_map()` and `write_object()` write two different TSV formats by design, per the spec.

**Comment by aukluobo** [comment]
thanks for fix !

**Comment by aednichols** [comment]
The fix will be in the next release of Cromwell. Thank you for reporting.
