### ISSUE TITLE
Publish metadata for which Cromwells have processed a workflow

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4723]
Cromwell publishes no metadata regarding which Cromwell instances have processed a workflow. This has been quite reasonable up to now since it has only been possible to have one worker Cromwell per deployment, but that is now changing with horizontal Cromwell. It would useful for operations and provenance to know which instances have been involved in processing a workflow.

Things to think about:

- This data can be multi-valued
- Time indexes are important
- Stable Cromwell identifiers are important. Conversely, ephemeral Cromwell IDs that evaporate on restarts aren't useful.

**Comment by kshakir** [comment]
Closing for now. Instead we chose to log this info via #4451
