### ISSUE TITLE
Test performance impact on /metadata endpoint of deleting indices METADATA_JOB_IDX and METADATA_JOB_AND_KEY_IDX

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4733]

**Comment by salonishah11** [comment]
The endpoints which query the metadata table and would be affected by the removal of the mentioned indices are:
- metadata
- timing
- logs
- query

The performance of `/metadata` and `/timing` endpoints have been measured and put in the doc. The remaining 2 endpoints are not being called through FC and hence their performance doesn't need to be evaluated.
