### ISSUE TITLE
Status endpoint for Reader Cromwells

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4737]
WAAS will have different `/status` requirements than the reader or writer Cromwells.

This could involve (depending on time available) either:
* Generalizing the current status implementation to allow callers of `/status` to opt-in/opt-out of status information they do or don't care about
* Creating a new specialist health implementation which knows what WAAS would care about.

**Comment by aednichols** [comment]
e.g. if the Womtool Cromwells do not have databases attached, status needs to not freak out about that
