### ISSUE TITLE
Create FC-develop configs

### ISSUE THREAD

**Issue by gemmalam** [broadinstitute/cromwell#4750]
Introducing the concept of a "lord" into the config, with the responsibilities:

* Summarize
* Liquibase

To complement this effort, these functions should be turned *off* in worker & reader Cromwells

**Comment by danbills** [comment]
Need to ensure:

1. only one instance is doing the liquibasing
1. The worker instances are waiting for that liquibasing to complete before running

**Comment by salonishah11** [comment]
Blocked on [issue](https://github.com/broadinstitute/cromwell/issues/4799).
