### ISSUE TITLE
Put Metadata Summarizer on its own thread pool

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4762]
Currently Metadata Writer and Summarizer share a thread pool.  Create a separate one for the Summarizer to use to eliminate contention at that level.

Note that there may still be thread contention as these thread pools share an underlying (larger) thread pool in the DB Hikari connection pool.

**Comment by likeanowl** [comment]
Hi @danbills !
Do you mean that `WriteMetadataActor` and `MetadataSummaryRefreshActor` just needs separate dispatchers?
I'll probably work on this issue.

**Comment by likeanowl** [comment]
Is this issue related to problem with deadlocks in `ServicesStoreSpec`?
If this task is still actual I'll appreciate more information about it (if any available).

**Comment by danbills** [comment]
Hi @likeanowl , thanks for your interest.

I'm tempted to close this issue.  I speculated that there could be contention.  However, we have since moved to an isolated process for the summarizer, rendering this issue moot for us.  

If you do work on this issue I would focus on developing a load test that can look at whether the thread pool suffers (is under heavy contenion) when under high metadata write load.

**Comment by likeanowl** [comment]
@danbills Could you give more information about the test cases you see for this issue? I thought about using [gatling-akka](https://github.com/chatwork/gatling-akka) in order to send a lot of messages to `WriteMetadataActor` and `MetadataSummaryRefreshActor`.
Do you thing this approach is suitable for this problem?

**Comment by danbills** [comment]
Hi @likeanowl , I'm closing this issue as it's based on speculation and has become an unfortunate distraction.  I appreciate your interest but your time is better spent on other issues.

Thanks again for your interest
