### ISSUE TITLE
Spike: Investigate NPE causing workflow failure

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4772]
Version: Cromwell v38
Backend: PAPI v2

Running a hello world workflow on Pipelines API v2 against inputs originating from a Requester Pays bucket.

The job finishes running, generates a 0 return code and detritus logs (stdout/stderr). However the workflow failures with an error message (full message attached).
[failed-workflow-metadata.txt](https://github.com/broadinstitute/cromwell/files/3008597/failed-workflow-metadata.txt)

```Unable to complete JES Api Request. Caught NPE while processing operation projects/dvoet-prod-test-20190305-3/operations/11506961050484846699```

Searched the code and found the error here:
https://github.com/broadinstitute/cromwell/blob/2d8ff3b0962bbe84828445fd3ac77d2379e499c2/supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/request/GetRequestHandler.scala#L49-L83

Operation metadata attached as well.
[operation-metadata.yaml.txt](https://github.com/broadinstitute/cromwell/files/3008623/operation-metadata.yaml.txt)

**Comment by ruchim** [comment]
This is a regression-- we should have a centaur test case that goes through this scenario, so this failure is surprising and worth investigating.

**Comment by rexwangcc** [comment]
We have also found 2000/2000 workflows failed due to this issue `Unable to complete JES Api Request. Caught NPE while processing...` today. We are using cass-prod `"cromwell": "36-fde91e6"`, and the Cromwell hasn’t been changed for at least ~2 weeks

**Comment by aednichols** [comment]
Response from Google:
>We are aware of a change that might be causing this issue and we are actively working on fixing it.

**Comment by lmtani** [comment]
My workflows are running without errors now.

**Comment by ruchim** [comment]
Learned that a change in Pipelines API omitted the "preemptible" key from the operations metadata, and that change introduced a null pointer in the Cromwell code. 

AC: As a way to address this, it would be great if we could modify the Cromwell code so that when its parsing operation metadata, that if certain keys are missing (such as Preemptible) -- we use the defaults where possible, else fail gracefully with an error that states which information couldn't be parsed, and that caused the workflow to fail.

**Comment by ruchim** [comment]
Closing this as the real fix is filed here: https://github.com/broadinstitute/cromwell/issues/4774
