### ISSUE TITLE
MySQL instance connections getting saturated

### ISSUE THREAD

**Issue by Xophmeister** [broadinstitute/cromwell#4777]
Cromwell (38, in this case) is saturating the available connections to our managed MySQL database. Our DBAs increased the limit and Cromwell proceeded to fill up these slots. How can we limit the number of concurrent connections to a MySQL database? There doesn't seem to be any configuration option for this.

**Comment by danbills** [comment]
Hi, look at the [`database.db` stanza](https://github.com/broadinstitute/cromwell/blob/40a0608a629976aca75ddf7f7adafc0fbe8bb399/cromwell.examples.conf#L800):

You want to set the following:
```
database.db {
    numThreads =20
    minThreads = 20
    maxThreads =20
    minConnections = 20
    maxConnections = 20
}
```

For reference and guidance on these nubmers, [look at the `forConfig` Docs for Slick](http://slick.lightbend.com/doc/3.2.3/api/index.html#slick.jdbc.JdbcBackend$DatabaseFactoryDef@forConfig(path:String,config:com.typesafe.config.Config,driver:java.sql.Driver,classLoader:ClassLoader):JdbcBackend.this.Database).

**Comment by danbills** [comment]
@Xophmeister forgot to note that we create 2 connections, one for metadata and one for all others, so **the numbers reflected here are exactly half of how many connections will ultimately be made**.
