### ISSUE TITLE
Add Grafana / Hosted Graphite support for summarizer and all worker Cromwells

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4781]
Horicromtal wants, please see also (and give preference to) the issue for our [existing configuration](https://github.com/broadinstitute/cromwell/issues/4780).

**Comment by ruchim** [comment]
Blocked by #4787 
Blocked by #4751

**Comment by gemmalam** [comment]
Issue moved to Jira
https://broadworkbench.atlassian.net/browse/BA-4781
