### ISSUE TITLE
Write StackDriver backend for Instrumentation

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4788]
The easiest way to capture and compare metrics from performance runs is to push them into GCP Stackdriver Monitoring.

We have an abstraction in the service registry for Instrumentation implementations, see the [StatsDInstrumentationServiceActor].(https://github.com/broadinstitute/cromwell/blob/develop/services/src/main/scala/cromwell/services/instrumentation/impl/statsd/StatsDInstrumentationServiceActor.scala)

## Library
`libraryDependencies += "com.google.cloud" % "google-cloud-monitoring" % "1.66.0"`

## Acceptance Criteria 

* Metrics can be labeled from global config settings. Namely: 
* Global config setting for Role (reader, worker, summarizer)
* Setting for Host name (e.g. "gce-cromwell-perfX")
* Setting for stable identifier for the perf test (e.g. "call-cache-whitelist").
* Logger can be configured using Service Account from Config.
* Performance runs are visible in GCP Stackdriver graphs with all labels.

# Reference

* [Configuring stackdriver agent, useful for service account creation](https://cloud.google.com/monitoring/agent/install-agent)
* [v3 monitoring javadoc](https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/monitoring/v3/package-summary.html)
* [GCP Client Libraries for monitoring](https://cloud.google.com/monitoring/docs/reference/libraries)

**Comment by gemmalam** [comment]
Issue exists in Jira
https://broadworkbench.atlassian.net/browse/BA-4788
