### ISSUE TITLE
Coordinate w/ DevOps the creation of a production instance for Summarizer

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4799]
Acceptance Criteria:

DevOps has deployed an instance ready to be configured using `summarizer` for `INSTANCE_TYPE` environment variable, [seen in this firecloud-develop PR](https://github.com/broadinstitute/firecloud-develop/pull/1590).

In detail this consists of a terraform `instance` stanza with `count=1` or omitted.

**Comment by ruchim** [comment]
Corresponding DevOps ticket https://broadinstitute.atlassian.net/browse/DSPTO-657
