### ISSUE TITLE
Centaur test the paths to horizontal

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4800]
How will The Great Horizontaling happen? Will we release Cromwell 4X and then sometime later change the configuration of that same version to be horizontal? Or will we release Cromwell 4X leaping into horizontal for the first time? Or different scenarios for different environments?

Whichever paths to horizontal are supported should have integration tests.

**Comment by cjllanwarne** [comment]
Sayeth @mcovarr: 
>The engine upgrade already has a horicromtal test, with some very recent bugfixes :wink:
so I think #4800 can be closed too

**Comment by cjllanwarne** [comment]
Confirmed closable as "done" by @mcovarr
