### ISSUE TITLE
Centaur test horizontal PAPI v2 upgrade

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4801]
NOTE: if the PAPI v2 upgrade happens in all environments before horizontaling, this ticket becomes unnecessary and should be closed as a noop. OTHERWISE:

Adapt the existing Centaur test for PAPI v1 to PAPI v2 upgrade for a horizontal Cromwell configuration.

**Comment by cjllanwarne** [comment]
@ruchim can you confirm that we're doing PAPIv2 first then horicromtal? If so, we may fall under the "noop" bracket for this ticket.

**Comment by cjllanwarne** [comment]
Confirmed closable as "done" by @mcovarr
