### ISSUE TITLE
Cromwell + CWL + Windows = thoroughly borked server

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4802]
Starting Cromwell on Windows and running any CWL workflow causes the server to crash and exit:
```
Uncaught error from thread [cromwell-system-akka.dispatchers.engine-dispatcher-50]: 
  java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/x86_64-Windows/jffi-1.2.dll, /jni/x86_64-Windows/jffi-1.2.dll]
```
What's worse, if one starts Cromwell back up it picks up that same workflow from the workflow store and immediately crashes. Notably, one can't even run WDLs at this point because the server does not stay up. The only remedy is to edit rows in the DB.

I realize running on Windows is a self-inflicted wound in my case, hence "low priority". It does seem likely that not every researcher who wants to use Cromwell works somewhere that can afford to issue Macs.

[jython_trace.txt](https://github.com/broadinstitute/cromwell/files/3048143/jython_trace.txt)

**Comment by aednichols** [comment]
@kshakir helpfully notes:
>That error looks like JNI, that I suspect is jython related, thus is probably heterodon. Heterodon was slimmed down to remove everything NOT tested via mac and/or CI. So since we don’t have any :travis: / :jenkins: testing windows I would not expect heterodon to work. Good news (?): we still support shell invoking `cwltool`, but I have zero expectation for that to work on windows either...

So this behavior is likely the result of a deliberate and helpful size optimization.

**Comment by cjllanwarne** [comment]
I don't know whether it even counts as a bug if it was never intended to work in the first place...

**Comment by aednichols** [comment]
It seems likely that the size optimization was made independent of knowing how completely and utterly borked Cromwell becomes (unable to run WDLs!), so I still feel that a pass of PO input is valuable.

**Comment by kshakir** [comment]
Here is the size optimization that deletes untested jython files:

https://github.com/broadinstitute/heterodon/blob/b54010d4f1fe9395f854ab62e4b66c203bf3f45d/build.sh#L82-L84

If we come up with a CI regression case for Windows (x64?) then the appropriate files could be excluded from the filter and tested.

Re: the borked Cromwell, we could catch-and-box the thrown `java.lang.Error` into a `java.lang.Exception` and Cromwell would handle this particular error more gracefully.
