### ISSUE TITLE
Document setting MYSQL databases to UTC

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4803]
With the mysql driver upgrade, it's not necessary to either set a MySQL database time zone *or* specify the timezone in the JDBC connection string. We should probably document this in our getting started documentation and/or configuration examples.

One (not exhaustive) example of where this type of documentation might make sense: https://cromwell.readthedocs.io/en/develop/tutorials/PersistentServer/

**Comment by aednichols** [comment]
When you ran into this locally, was the DB a native install or running in Docker?

**Comment by cjllanwarne** [comment]
Native install

**Comment by aednichols** [comment]
I _think_ using MySQL in Docker (as I do) sets UTC by default, as does CI, which is why this flew under my radar.

**Comment by cjllanwarne** [comment]
Perhaps then this would work better in a troubleshooting guide than the "getting yourself a MySQL database section"

**Comment by aednichols** [comment]
Assigning myself since the MySQL upgrade is the underlying cause.

Here is the command sequence I use to create a new local DB for use by a fresh, totally default Cromwell checkout.
```
docker run --name=mysql1 -p 3306:3306 -d mysql/mysql-server:latest
docker logs mysql1 # copy the auto generated password
docker exec -it mysql1 mysql -uroot -p # paste in the password from the previous stpe
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
CREATE database cromwell_test;
CREATE USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```
I just validated it still works with recent versions, so it seems my theory about Docker using UTC is correct.
