### ISSUE TITLE
Support high security networks (VPCs) specified in Google project labels

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4806]
#### Background

For background information see [this design doc](https://docs.google.com/document/d/1QqXuURg1HlwAymaQkwCL6v9HA5NWsp1pbribvGafNt0/edit?ts=5c6c875c#heading=h.56f418pyjwq8).

#### Concept

* Allow Cromwell to spin up PAPIv2 jobs on high security networks 
* At project-creation time, scripts may create a high-security network for that project and record the network name in the project metadata.
* If these fields exist, Cromwell should honor them.

#### Proposal

* Use a key in Cromwell's configuration to locate the appropriate project metadata
  * For example, perhaps: 
```
backend {
  providers {
    PAPIv2 {
      config {
        backend.providers.PAPIv2.config.vpc {
          name: "terra-network"
          subnetwork: "terra-subnetwork"
        }
      }
    }
  }
}
```
* When about to submit a job to PAPI, see whether the `name` field exists in the configuration.
  * If so, check whether the specified label exists in the Google project, eg:
```
$ gcloud projects describe my-fc-project

createTime: '2017-07-07T17:07:10.345Z'
labels:
  terra-network: firecloud
  terra-subnetwork: firecloud
lifecycleState: ACTIVE
name: my-fc-project
```
  * If so, deduce a `NETWORK_PATH` by combining the `GOOGLE_PROJECT_ID` (from workflow options) and `NETWORK_NAME` (the label value) as: `projects/GOOGLE_PROJECT_ID/global/networks/NETWORK_NAME`
  * Include this in the PAPI request:
```
  pipeline.resources.virtualMachine.network: {
    name: NETWORK_PATH
  }
```
* If both the `name` and `subnetwork` fields are defined in configuration, and both exist as project labels:
  * The `SUBNETWORK` is the raw value of the `subnetwork` label in the google project
  * We additionally provide the subnetwork in the PAPI request:
```
  pipeline.resources.virtualMachine.network: {
    name: NETWORK_PATH
    subnetwork: SUBNETWORK
  }
```

**Comment by aednichols** [comment]
So the network name, e.g. `"terra-network"`, would be the same for all projects created by Terra?

**Comment by skatragadda-nygc** [comment]
Hello @salonishah11 @cjllanwarne 

It is currently not possible to mention networks from different GCP project(not the project where pipeline is running)

PAPIv2 is accepting networks from from another project as well if we mention the value as
projects/PROJECT_ID_DIFFERENT_FROM_PIPELINE/global/networks/NETWORK_NAME

I know it is not possible to mention above using labels in project. Any chance this can be included google backend?

**Comment by skatragadda-nygc** [comment]
@cblack-nygc
