### ISSUE TITLE
Push new AWS proxy image

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4814]

**Comment by cjllanwarne** [comment]
Does this mean we can close this issue? Sort of disappointing/scary this isn't automatic

> geoffjentry moved this from In progress to Done in AWS Support 6 days ago

**Comment by geoffjentry** [comment]
It's not automatic, it'd be on us to automate it as the code is in our repo, so feel free to make a ticket for it. "when to trigger it" is a tricky question.

Leave this open for now. The image is indeed pushed, I haven't confirmed its success

**Comment by geoffjentry** [comment]
Confirmed done
