### ISSUE TITLE
Spike: Malformed dates in Cromwell metadata

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4818]
It seems that with some version change, Cromwell started deforming certain dates [see below]. This is breaking Tableau's tool reporting. It would be great to investigate when and how this change happened, and why our tests didn't catch it.

Need to confirm which version of Cromwell is seeing this change.

**Comment by ruchim** [comment]
![bad end time](https://user-images.githubusercontent.com/14941133/55826385-e8b1a180-5ad5-11e9-8b69-6e59a9f5c400.png)

**Comment by aednichols** [comment]
Related issues:

https://github.com/HumanCellAtlas/secondary-analysis/issues/523
https://github.com/broadinstitute/cromwell/issues/2743

See in particular this extremely helpful comment from @kshakir: https://github.com/broadinstitute/cromwell/issues/2743#issuecomment-341828400

**Comment by ruchim** [comment]
Thanks for looking into it! Closing this spike as its complete, and will update the respective issue with the proposed solution.
