### ISSUE TITLE
Womtool endpoint: separate field for input errors

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4824]
- Problems with inputs should be related to the input name in a machine-readable way so that a UI can display the information next to the field it pertains to (Doug)
- If a WDL is valid and there is only a problem with inputs, indicate that somehow and still return I/O (DA)
- ~If a WDL is invalid, don't return the keys for I/O... because they can be seen as falsely indicating that the WDL has no inputs or outputs. (DMohs)~ moved into https://github.com/broadinstitute/cromwell/issues/4892

**Comment by cjllanwarne** [comment]
Are we ok to unilaterally make these changes? Are agora and rawls already building out functionality based on our existing behavior? Will they be resilient to us making these changes?

**Comment by aednichols** [comment]
This needs refinement and will probably split into separate tickets.

**Comment by aednichols** [comment]
Refinement update:

We are going to solve the first two points by adding a sort of `input_errors` map with input names as keys and error(s) as values. The absence of `errors` and presence of `input_errors` indicates the DA case where WDL is good and inputs bad.

The last issue will split off into soliciting community feedback from non-workbench users and writing a nicer wrapper endpoint that's more compatible with curl (it is Adam's opinion, potentailly poorly supported, that this is hard right now)
