### ISSUE TITLE
Per-workflow log file does not get closed in server mode

### ISSUE THREAD

**Issue by tonybendis** [broadinstitute/cromwell#4826]
When Cromwell is configured with `workflow-log-temporary: false` and workflow does not specify `final_workflow_log_dir`, Cromwell server does not close the log file. 
When `final_workflow_log_dir` is specified the original log file is correctly closed and copied. 
In my case, this prevents blobfuse (waits for the file to be closed) from transferring the log files to Azure storage. 

Looking at the code, there is no call to `workflowLogger.close() `or `workflowLogger.close(andDelete = false)` unless the file is being copied. 

Probably this line in WorkflowActor.scala:
`case None if WorkflowLogger.isTemporary => workflowLogger.close(andDelete = true)` 
needs to change to:
`case None => workflowLogger.close(andDelete = WorkflowLogger.isTemporary)`

**Comment by kganjam** [comment]
I have validated that the log file for each submitted workflow does not get closed when Cromwell is run in server mode and is configured with `workflow-log-temporary: false` and the workflow does not specify the `final_workflow_log_dir` option. I also have tested that Tony's fix above resolves the problem. While using a workflow options file is a workaround, it's not a general solution for debugging failed workflows submitted by users who did not include the options file to begin with. Even worse, the bug results in a file handle leak in Cromwell server. 

Repro steps:

```
# cromwell.conf
include required(classpath("application"))
workflow-options {
  # When true, per workflow logs will be deleted after copying
  workflow-log-temporary: false
}
```

Run: `java -Dconfig.file=cromwell.conf -jar cromwell.jar server`  

Submit a simple Hello World .wdl file to /api/workflows (submit a couple times see the leak).

We see that many log file handles remain unclosed:
`sudo lsof -p $(pidof java)`

```
java    33951 cromwellbuild   33w      REG                8,1       117 533080 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.11dbb9e7-10e3-48dc-b36f-0b7e35941ce3.log
java    33951 cromwellbuild   34w      REG                8,1      1301 525688 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.0ed80fab-afd1-4783-9b27-409b75f0f2f7.log
java    33951 cromwellbuild   35w      REG                8,1       117 533081 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.ef428f60-f8c3-4456-a3ea-bea63486881a.log
java    33951 cromwellbuild   36w      REG                8,1       117 533085 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.4df4069e-0ef0-43ba-8bfb-37413d7ed229.log
java    33951 cromwellbuild   37w      REG                8,1       117 533086 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.48e5c4ff-c067-465d-820b-2b41cb74ef31.log
java    33951 cromwellbuild   38w      REG                8,1       117 533087 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.05bcd5a7-3924-4ba0-ab39-57bc09716abb.log
java    33951 cromwellbuild   39w      REG                8,1       117 533088 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.43bcbc56-3596-45b7-9f1d-c00dc36defd4.log
java    33951 cromwellbuild   40w      REG                8,1      1340 533089 /home/cromwellbuild/cromwell/cromwell-workflow-logs/workflow.5b4c1033-3dfe-470c-bba4-5d31f2120948.log
```
