### ISSUE TITLE
AWS backend: wrong separation of output directory in a container

### ISSUE THREAD

**Issue by leepc12** [broadinstitute/cromwell#4834]
I used cromwell-38.jar for testing.

It looks like outputs from tasks with the same task-name and shard index in different scatter blocks share the same scratch directory in a container.

Output files are written on this shared directory and globbed at the end of each task and then moved to S3 bucket together with all text/log files.

This can result in globbing of wrong output files (from tasks with the same task-name but different alias).
```
workflow cromwell_aws_glob_test {
        scatter(i in range(2)) {
                call t1 { input: i=i, alias = "t1" }
        }

        scatter(i in range(2)) {
                call t1 as t2 { input: i=i, alias = "t2" }
        }
}

task t1 {
        Int i
        String alias
        command {
                echo "${alias},${i}" > ${alias}-${i}.txt
        }
        output {
                Array[File] outs = glob("*.txt")
        }
}
```
On the execution directory for task t1 on S3. Everything looks okay. We don't have any t2 things.
ubuntu@ip-172-30-0-96:~/test_cromwell$ aws s3 ls s3://encode-pipeline-test-runs/test2/cromwell_aws_glob_test/d3fb65e0-54d0-495c-8bea-503a91d9dff3/call-t1/shard-0/
                           PRE glob-ef5df339533c1334f081dc8cc75ee4f3/
2019-04-11 20:30:54          0
2019-04-11 20:32:48         30 glob-ef5df339533c1334f081dc8cc75ee4f3.list
2019-04-11 20:30:54       2238 script
2019-04-11 20:32:49          2 t1-0-rc.txt
2019-04-11 20:32:51          0 t1-0-stderr.log
2019-04-11 20:32:50          0 t1-0-stdout.log

But the glob directory has outputs from task t2.
ubuntu@ip-172-30-0-96:~/test_cromwell$ aws s3 ls s3://encode-pipeline-test-runs/test2/cromwell_aws_glob_test/d3fb65e0-54d0-495c-8bea-503a91d9dff3/call-t1/shard-0/glob-ef5df339533c1334f081dc8cc75ee4f3/
2019-04-11 20:32:47        277 cromwell_glob_control_file
2019-04-11 20:32:47          5 t1-0.txt
2019-04-11 20:32:47          2 t2-0-rc.txt
2019-04-11 20:32:47          5 t2-0.txt

**Comment by geoffjentry** [comment]
I believe this is the same issue as #4364 so closing it as a duplicate. If you think I've misunderstood the problem let's reopen it.
