### ISSUE TITLE
200 files scattered 200x fails to call cache due to GCS hash timeout

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#4873]
@mwalker174 originally reported:

> Hi all, I’ve got a critical problem where call caching times out on a particular WDL task (`“message”: “Hashing request timed out for gs://...“’). This makes some sense since the task is checking ~200 files on each of ~200 shards. This is on cromwell v36/papiv2. I thinking bundling the files would probably fix this, but is there any way to increase the timeout limit in the server settings? Would upgrading to v38 help? Thanks!

There's currently a non-configurable 5 minute timeout per GCS hash request. Assuming no batching (which I didn't come across) for ~40K individual requests that's about 100 requests/second to GCS. I'm pretty sure w/ GCS request throttling & internal cromwell backoffs at least one of those requests would fail to return in 5 minutes.

**Comment by mwalker174** [comment]
@ruchim turned on file hash caching, which solved the problem for us.

**Comment by gemmalam** [comment]
@mwalker174 thanks for circling back to this and giving us this update!
