### ISSUE TITLE
At what interval does check-alive get called?

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/cromwell#4877]
The documentation for the new HPC backend 'check-alive' feature is a bit scattered an incomplete.

https://cromwell.readthedocs.io/en/stable/backends/HPC/
> This option will implicitly enable polling with the check-alive option.

https://github.com/broadinstitute/cromwell/releases:
> When the value exit-code-timeout-seconds is set, check-alive command is now only called once every timeout interval instead of each poll.

https://github.com/broadinstitute/cromwell/blob/73ad264b4c7919d0bbd344fecbc903f819f5e16c/cromwell.example.backends/SGE.conf#L27
> # Warning: If set, Cromwell has to run 'check-alive' for every job at regular intervals (unrelated to this timeout)

I had a look at the code and PRs implementing the feature, but am not confident I can even see how the feature is implemented, so cannot write the docs as a PR myself!

I had assumed, when you specify `exit-code-timeout-seconds`, cromwell would poll `check-alive` at that interval, and after 2 failed `check-alive`s with no rc file, would mark the job as failed. Now I think there is some other polling mechanism, perhaps to cap polling load per backend instead of scaling it with number of jobs. 

Is it possible to revisit that documentation and actually explain what is happening? Alternatively just a link here to the `unrelated to this timeout` documentation?

**Comment by cjllanwarne** [comment]
Hi @EvanTheB could you check something for me - you should be seeing a message like `Cromwell will watch for an rc file *and* double-check every {} seconds to make sure this job is still alive` when you start your job? (assuming `INFO` level logging is enabled)

Then, with that background polling ongoing throughout the job run, if a full iteration of `exit-poll-timeout` has passed since the job stopped running, Cromwell will then mark the job as failed.

If that gives you enough to put something more helpful into the docs that would be awesome! If not, I can maybe clarify a bit more? Otherwise we should hopefully be able to cycle round to improving this documentation _eventually_ (though unfortunately I can't make any stronger promises on an ETA than that!)

**Comment by EvanTheB** [comment]
Thanks @cjllanwarne , 

> 2019-04-24 10:49:25,556 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(917dfbca)JointGenotyping.ImportGenotypeGVCFs:7640:1]: Cromwell will watch for an rc file but will *not* double-check whether this job is actually alive (unless Cromwell restarts)

So I guess I have not managed to enable polling after all! Any tips?




I had not heard of exit-poll-timeout, I assume you mean exit-code-timeout-seconds, or is this the `unrelated to this timeout`?

**Comment by cjllanwarne** [comment]
1. Oops, yes, I meant `exit-code-timeout-seconds`. 
2. I think that the `unrelated to this timeout` side note is no longer accurate - the polling actually happens at the exact interval of the timeout now!

**Comment by EvanTheB** [comment]
I now notice that both checking for the RC and the 'check-alive' checks are controlled by this setting. This seems a bit strange as the rc checking is comparatively very cheap compared to 'check-alive'.

Initially the point of not running check-alive all the time was that the cost was high compared to rc file checking. But now the solution has been to slow down rc checking to the speed of the costly check-alive! I am a bit muddled on this, so am not sure if I am getting it. 

Without exit-code-timeout-seconds at what interval is the rc file checked for?

**Comment by EvanTheB** [comment]
@cjllanwarne you may have missed my question here after the ticket was closed.

**Comment by cjllanwarne** [comment]
The regular status polling is totally separate from this option. 

Regular polling backs off, so doesn't have a single "interval" value to configure or report (ie it starts off polling with short intervals but slows down as the job runs for longer and longer). That's true for all jobs across all backends.

The `is-alive` check is a fixed (configurable) duration, and it's the timeout between `is-alive` returning false, and the job being considered failed, that are the same.

Does that make sense?

**Comment by EvanTheB** [comment]
Ah I see thank you @cjllanwarne , I do not remember exactly where I got the idea that confused me, somewhere in the logs. But probably I was misunderstanding. Thank you.
