### ISSUE TITLE
Centaur to assert output hashes

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4904]
For the integration tests Cromwell runs, it would be good for the test definition to assert the hash of the expected output and actual output.

This particular case is to ensure that there are no changes to the engine that could cause the contents of the outputs to change over time, and alert the team when such a case happens.

**Comment by gemmalam** [comment]
Moved issue to Jira and added to Epic "CLIA Compliance"
https://broadworkbench.atlassian.net/browse/BA-5673
