### ISSUE TITLE
Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

### ISSUE THREAD

**Issue by anniepgu** [broadinstitute/cromwell#4935]
Hi , 
    When submitting jobs requiring GPU, we specified in the runtime session: 
gpuCount: 2
gpuType: "nvidia-tesla-k80"
 the jobs failed with following errors:
2019/05/03 14:40:50 E: command failed: nvidia-docker | 2019/05/03 14:40:50 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?

The same WDL file (with same docker and runtime attributes) used to work before.

Please help!

Thanks!

**Comment by aednichols** [comment]
Are you using Pipelines API v1?

We are tracking a possible PAPI GPU issue that is limited to v1. If you are able to use the v2 backend instead, I would recommend that as a workaround (v2 is better in other ways too!).

**Comment by aednichols** [comment]
The official word from Google is that the OS installed on Pipelines API v1 workers has aged enough that driver support is no longer available.

The best I can do on behalf of Cromwell is recommend switching to v2; if you have any further questions feel free to reopen!

**Comment by anniepgu** [comment]
Thanks! 
Switching to v2 solved the issues.
