### ISSUE TITLE
Limit Cromwell's resource usage

### ISSUE THREAD

**Issue by illusional** [broadinstitute/cromwell#4945]
Hi,

I'm finding that Cromwell is using too many resources in a shared environment. It's spawning other threads and using up to 400% CPU, which I can't see why when the logs just show it's watching for jobs (maybe it's trying to hash files for call-caching?)

I'd love a way to limit it, even at the expense of speed of the program, it would also be great if there was tooling (maybe an endpoint) to gauge the resource usage, and see what Cromwell's actually doing.

For context, I'm running Cromwell on a (shared) login node, submitting jobs to Slurm (custom SFS config). The workflow is scattering a subworkflow 25 times, each with 4 steps. All of those have actually executed prior and it's taking a long time (sometimes > 30 minutes) to look up a call result. I am using call-caching with a mysql database.

**Comment by delocalizer** [comment]
(disclaimer: cromwell user not dev) One possibility is that you're running with insufficient memory or inappropriate GC settings — you could try using Visual VM or another profiler to see what the JVM is doing and if check there are lots of GC threads running all the time. That's a pretty typical hazard for all Java programs, not just cromwell.

**Comment by illusional** [comment]
I've worked out what happened, but I don't know if I can resolve this next problem. 

I had call-caching turned on for SFS, and this was MD5 hash was being calculated by Cromwell on the login node, however for 2x 100GB BAM files at each step this was (obviously in retrospect) a resource drain.

This was only applicable to backends that use the Local Filesystem (GCS and S3 file systems probably use their blob / object id).

If you come across this issue, you might have a couple of solutions:
- Turn off call-caching, might not matter to you.
- If you're not using containers, you might be able to get away with the [path+modtime caching strategy](https://cromwell.readthedocs.io/en/stable/Configuring/#local-filesystem-options), requires you to use the [`soft-link` copying strategy](https://cromwell.readthedocs.io/en/stable/backends/HPC/#shared-filesystem).
- If you **are** using containers, you're out of luck unfortunately.

**Comment by geoffjentry** [comment]
re containers, would the `cached-copy` localization strategy in #4900 help you?

**Comment by illusional** [comment]
Yeah I've been following that! I'm excited to try it soon, and I think it'll knock out a good chunk of CPU when it's copying files between disks, but the `cached-copy` strategy hard links files, which means it's not eligible for any other call-caching strategy except File.

**Comment by bkohrn** [comment]
As someone who is having a somewhat similar issue, what did you do to fix the resource management problem?  I'm seeing a lot of processes spawned, and memory usage growing out of control.  I have a system with a 6-core CPU and 32 GB of RAM, running Linux Mint, and I'm trying to run the processing-for-variant-discovery-gatk4.wdl pipeline (with some interest in running other GATK pipelines as well)

**Comment by aednichols** [comment]
@bkohrn you can use the JVM memory options to limit how much RAM Cromwell consumes.

The impact of CPU can be moderated with the built-in `nice` options on Linux.

**Comment by illusional** [comment]
Hey @bkohrn, just checking up on old threads:

- running a MySQL database will reduce the memory usage of Cromwell for larger workflows.
- ie: memory(mySQL + cromwell) < memory(cromwell w/ NO MySQL)
- CPU can be mitigated by turning off call-caching, or at least the "File" strategy for call-caching.

**Comment by illusional** [comment]
I'm going to close this, our issues were related to the `file` call-caching method. Using md5 and request large files had very detrimental effects.

For future readers, I'd advise using (a hopefully now implemented) `fingerprint` caching method:

- #5450

**Comment by gbinux** [comment]
Found `taskset` handy to limit CPU usage of both Cromwell and its child processes, eg
```
taskset -a -c 0-16 java -jar cromwell-xx.jar run my.wdl -i myinput.json
```
- `-a` option: operate on all tasks or threads
- `-c` option: limits the engines and subprocesses (Local) to using CPU no. 0 to no. 16.
