### ISSUE TITLE
Ability to SSH into Google Genomics Worker Machines

### ISSUE THREAD

**Issue by indraniel** [broadinstitute/cromwell#4966]
Jobs submitted by [dsub][0] and [Google Genomics Pipeline Tools][1] both have the ability to start an SSH container in the background to allow one to inspect the runtime environment of a google genomics job in real-time.  This can often be a very helpful tool to aid in diagnosing various kinds of troublesome workflow jobs and appreciating workflow tasks containing complex scripts and programs.

Does cromwell support this feature?  If so, how would one enable this?  Otherwise, would it be possible to incorporate this feature in future releases?

[0]: https://github.com/DataBiosphere/dsub/releases/tag/v0.2.1
[1]: https://github.com/googlegenomics/pipelines-tools

**Comment by ruchim** [comment]
Hey @indraniel -- this isn't yet supported --but the plan is to add it eventually.

For now, it may be helpful to add something like an rsync at the top of your task, to see what logs are being produced by your task, or if things have gone quiet. It's also possible to add a monitoring script to run in the background that includes info about cpu/memory usage 
https://cromwell.readthedocs.io/en/stable/wf_options/Google/#google-pipelines-api-workflow-options (see "monitoring_script")

**Comment by kshakir** [comment]
For later when we want to begin implementing this feature:

The [Papi docs](https://cloud.google.com/genomics/docs/how-tos/migration#accessing_the_containers) recommend adding an action that looks like this:

```json
{
  "pipeline": {
    "actions": [
      {
        "imageUri": "gcr.io/cloud-genomics-pipelines/tools",
        "entrypoint": "ssh-server",
        "flags": [
          "RUN_IN_BACKGROUND"
        ],
        "portMappings": {
          "22": 22
        }
      }
    ]
  }
}
```

via: https://groups.google.com/forum/#!topic/google-genomics-discuss/1nkIxKrqBk0

Permalinks versions of the floating-"master"-links in that thread:
- ["Handling of the command line flag"](https://github.com/googlegenomics/pipelines-tools/blob/749315a73e6c3bd5277351e32a365f42198db1ae/pipelines/internal/commands/run/run.go#L402-L404)
- ["Container ("action") added"](https://github.com/googlegenomics/pipelines-tools/blob/749315a73e6c3bd5277351e32a365f42198db1ae/pipelines/internal/commands/run/run.go#L759-L766)

**Comment by acoffman** [comment]
Hi,

This is a feature we're interested in utilizing in our own workflows. If we started working on adding it ourselves, is it the sort of thing you guys would be interested in accepting a pull request for?  We wanted to check before starting work in earnest one it.

Thanks!
Adam

**Comment by aednichols** [comment]
Let's see what @ruchim says.

**Comment by acoffman** [comment]
Followed up with @ruchim via email and we poked around the codebase this afternoon and think we have a good idea on how to add this functionality.

 First though we wanted to run the general plan by you guys and had a couple of questions. 

It seems like the place to staple this in would be as an additional `Action` in `GenomicsFactory`  (as was alluded to above). We weren't sure if it made sense to staple it in as an additional `monitoringAction` or `userAction` as they are both handled slightly differently than this would be. Neither fits perfectly, but it seems like it could potentially be made to work in either place. 

Another alternative (maybe the cleanest one?) would be to just introduce a `remoteAccessAction` or similar helper that builds up an action just for this purpose.

We wouldn't want to change the default behavior and/or have this `ssh` server always running, so it seems to make sense to make it configurable. We figured the PAPI section of the conf file would be a reasonable place to add this new option.

Does that generally sound in line with how you guys would approach this?

**Comment by ruchim** [comment]
@salonishah11 Would you mind reviewing this proposal?

**Comment by gemmalam** [comment]
This issue exists in Jira now. Please add new comments to this link https://broadworkbench.atlassian.net/browse/BA-4966

You will be required to create a Jira account.

**Comment by acoffman** [comment]
I received an invitation to join JIRA and created an account with the email acc@fastmail.com, but cannot see this issue. If I'm intended to be able to do so, someone will likely have to grant me appropriate permissions.

**Comment by aednichols** [comment]
@rebrown1395 can you comment?

**Comment by aednichols** [comment]
Filed https://broadworkbench.atlassian.net/browse/JS-19 on your behalf @acoffman, we are brand new to this JIRA thing and I have asked that your situation be looked at

**Comment by araina2018** [comment]
@rebrown1395 invited Adam C again. Somehow user was not in the system. please check again and let us know.

**Comment by acoffman** [comment]
Whatever was done seems to have worked. I clicked the second invitation link while already logged in and I can now see the JIRA issues in question. Thanks all!
