### ISSUE TITLE
Nightly Perf Runs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4980]
After deep-diving into the QA perf environment, I think we could get some continuous-testing value very quickly by doing the following:

- Copy their `project-deploy` [(link)](https://fc-jenkins.dsp-techops.broadinstitute.org/job/project-deploy/) job over to deploy our `develop` image to our own perf environment every night
  - Or: do something more custom since we don't need all the general-purpose non-Cromwell stuff
- Copy their `perf-run-single-test-until-it-fails` [(link)](https://fc-jenkins.dsp-techops.broadinstitute.org/view/Perf/job/perf-run-single-test-until-it-fails/) job and make it run against our own environment every night

Even something this simple would (maybe after they check our working a few times?) allow us to remove the "wait for QA" portion of the release process since we'd be able to look-up the results rather than regenerating them. We'd also be able to track performance over time and have a better idea of how much signal-to-noise there is in the tests (eg how much variation is within normal bounds?).

**Comment by gemmalam** [comment]
Issue has been moved to Jira
https://broadworkbench.atlassian.net/browse/BA-4980
