### ISSUE TITLE
CallActor instantiate Backend

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#500]
1) CallActor will instantiate a Backend (currently this is in WorkflowManagerSystem)
  - Backend will have a TaskDescriptor
2) Make CallExecutionActor work with a Backend object
  - in props(), instead of passing a BackendCall, we will pass a Backend
3) pluggable_backends_develop branch on Cromwell has an example CallActor modifications

**Comment by mcovarr** [comment]
Depends on having call-scoped BackendActors, which currently are a ways off.

**Comment by kcibul** [comment]
Based on the most recent discussions (and following up with Miguel, Ruchi), this seems to be a different ticket (WorkflowActor will instantiate BackendActors which in our case may call CallActor-like things).  We'll tackle this as part of the implementation of our backends.  Closing for now
