### ISSUE TITLE
How to configure proxies?

### ISSUE THREAD

**Issue by haaskyle** [broadinstitute/cromwell#5006]
# Proxy Support in Cromwell

Are proxies supported in Cromwell? 

Cromwell fails to use remote hashing behind my corporate proxy. However, I can get this to work outside the proxy. While behind the proxy, Cromwell can still pull Docker images and local hashing works as these rely on the Docker daemon which does utilize my proxies.

## Exceptions

These are the exceptions that Cromwell is raising behind the proxy:
```
Request method=GET uri=https://auth.docker.io/token?service=registry.docker.io&scope=repository%3Alibrary/debian%3Apull headers= threw an exception on attempt #4. Giving up.
java.net.ConnectException: Failed to connect to endpoint: RequestKey(Scheme(https),auth.docker.io)
```
```
Docker lookup failed
java.lang.Exception: Failed to get docker hash for debian@sha256:75f7d0590b45561bfa443abad0b3e0f86e2811b1fc176f786cd30eb078d1846f Failed to connect to endpoint: RequestKey(Scheme(https),auth.docker.io)
```

## Troubleshooting

I set my JVM proxies using the bash command 
``` 
export _JAVA_OPTIONS='-Dhttp.proxyHost=proxy.myproxy.com -Dhttp.proxyPort=myport -Dhttps.proxyHost=proxy.myproxy.com -Dhttps.proxyPort=myport'
```

And at the top of my cromwell logs I can see 
```
Picked up _JAVA_OPTIONS: -Dhttp.proxyHost=proxy.myproxy.com -Dhttp.proxyPort=myport -Dhttps.proxyHost=proxy.myproxy.com -Dhttps.proxyPort=myport
```

Of note, I have tried with and without the digest tag. Both are unsuccessful. 

## Cromwell Version

I am using cromwell 41.

**Comment by gemmalam** [comment]
Hello @haaskyle, we are currently using Jira for our backlog. I have moved your ticket to https://broadworkbench.atlassian.net/browse/BA-5695

Please let me know if you have issues accessing it. You will need to create a Jira account.

The priority of this ticket will be reviewed.

**Comment by aednichols** [comment]
It's not likely this will be worked on as the dev team has no experience with proxies nor one to test against.

Can you have your corporate IT allowlist Docker? It seems like it would be a popular and non-risky request.
