### ISSUE TITLE
Can't view jira

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/cromwell#5031]
###
###
###
###

The jira is not visible to me and I'm logged in and on the Broad network.  

<img width="1439" alt="Screen Shot 2019-06-13 at 4 18 45 PM" src="https://user-images.githubusercontent.com/4700332/59464633-fdbcf080-8df6-11e9-88dc-0e4450a3d3ce.png">

**Comment by gemmalam** [comment]
@lbergelson I just messaged our system administrators. I believe someone keeps changing a setting. It shouldn’t matter if you are on the internal WiFi. I’m sorry for the inconvenience this is causing.

**Comment by gemmalam** [comment]
@lbergelson the issue has been fixed. Let me know if you still aren’t able to access our backlog.

**Comment by lbergelson** [comment]
I can access it now.  It's really gross to have to sign into a private jira in order to see bug reports from an open source project though.  If we have to use JIRA for some reason, is there a way to at least make it publicly visible without a login?

**Comment by aednichols** [comment]
We know and are equally unhappy, I created a JIRA issue for this JIRA issue: https://broadworkbench.atlassian.net/browse/JS-31

**Comment by illusional** [comment]
It would be nice to have some more documentation about this. When I first logged in this morning, I couldn't access the board, so I tried creating an account and that also failed initially for an _unexpected error, please try again later_ sort of thing. 

Also, what board do we create Cromwell issues under? My best guess is `Jira Support` and that's where I created my issue: [Cromwell (server) loses ability to poll some workflows](https://broadworkbench.atlassian.net/browse/JS-34), but all of the other issues aren't really Cromwell related.

A "query" field might also be useful. 

These are the boards currently on Jira:
- `Batch Analysis`
- `Cloud Accounts`
- `Data-repo`
- `DevOps`
- `DSP-ELT Backlog`
- `Interactive Analysis`
- `Jira Support`
- `New Project`
- `PERF`
- `PRODUCTION`
- `QA`
- `SAND-NG`
- `SANDBOX`
- `SUPPORT`
- `TERRA ROADMAP`
- `TerraUI`
- `User Metrics`
- `UX`

**Comment by gemmalam** [comment]
Hi @illusional, thank you for taking the time to create an account and working with us on this transition. Our board is located in the project 'Batch Analysis'. We will make sure to add this to Github for folks needing to create a ticket in the future. Please let me know if you run into any other issues.

**Comment by illusional** [comment]
I tried to move my issue from where I raised it but it didn't work, so I created a new one in the Batch Analysis board. [BA-5738](https://broadworkbench.atlassian.net/browse/BA-5738) and [BA-5737](https://broadworkbench.atlassian.net/browse/BA-5737).

**Comment by illusional** [comment]
Hi @gemmalam, is there a process for acknowledging issues in Jira? I've raised a few ([BA-5790](https://broadworkbench.atlassian.net/browse/BA-5790) | [BA-5738](https://broadworkbench.atlassian.net/browse/BA-5738) | [BA-5737](https://broadworkbench.atlassian.net/browse/BA-5737) | [BA-5736](https://broadworkbench.atlassian.net/browse/BA-5736)), but it looks like they're in the Backlog. Does this mean that they have been looked at and moved, or they are waiting to be looked at or have they not been created correctly, I just clicked new issue and filled out the fields. 

In GitHub, I could see my issues in the order they were raised / last commented on, but on Jira I can't get a scope where they are, if they've been seen (sometimes GH issues were tagged with `Needs triage`) or if I've raised it incorrectly.

**Comment by gemmalam** [comment]
@illusional currently each of these tickets have the label “need_triage” where we go through the tickets with that label to the decide their priority. If any of these tickets are blocking your work please let me know. If there is a specific question for any of the tickets you created in Jira please tag myself Ruchi Munshi or Adam Nichols in the specific ticket and we will work on getting them prioritized quicker.

**Comment by illusional** [comment]
Thanks @gemmalam, I hadn't seen the `Needs_Triage` label and appreciate the reply. Nothing is blocking, but didn't want to be yelling into the void.

**Comment by wholtz** [comment]
@gemmalam - I am trying to access the JIRA tickets for cromwell. I followed the link in the README and created an account, but I'm getting a message "<my_email_address> doesn't have access to Jira on broadworkbench.atlassian.net."

**Comment by gemmalam** [comment]
@wholtz unfortunately, I no longer work a the Broad Institute and cannot help you gain access to the cromwell Jira project. @aednichols should be able to help or connect you with someone who can.

**Comment by aednichols** [comment]
We have not consistently been able to keep the JIRA board configured for the partial public access we need.

The JIRA instance is shared by many groups and has to meet a lot of compliance needs, and the Cromwell access seems to get lost in the shuffle.

I think it's more likely that we will remove the link to JIRA and suggest sticking to Github issues.

**Comment by aednichols** [comment]
Changed in https://github.com/broadinstitute/cromwell/issues/5031

**Comment by wholtz** [comment]
I think @aednichols intended to mention PR https://github.com/broadinstitute/cromwell/pull/6729 instead of that circular reference to this issue. Thanks @aednichols.

**Comment by aednichols** [comment]
Yes, that is correct! Thank you.
