### ISSUE TITLE
cannot read rc

### ISSUE THREAD

**Issue by huangzhibo** [broadinstitute/cromwell#5051]
Jira:
https://broadworkbench.atlassian.net/browse/BA-5756?atlOrigin=eyJpIjoiYjk0YjlhYzYyN2Y2NGRkY2FiMGIwNWFmZDk5M2ZiMWEiLCJwIjoiaiJ9

```
version:  cromwell41
backend: SGE
hard disk：Network shared storage （lustre）
```

When the rc file has been generated, the task status is still running. This state will last a long time.
When we set "exit-code-timeout-seconds = 18000", such tasks will fail after 10 hours `("message": "The job was aborted from outside Cromwell") `.  Despite the fact that the task has been completed normally.

This situation does not always happen, and only a few tasks will encounter this problem.

**Comment by gemmalam** [comment]
Hello @huangzhibo, thank you for creating a Jira ticket. I will close this github ticket in favor of that one. Please reply on Jira if you have other issues related to this. Someone from the team will reach out to you to follow up on priority. Please let us know if this is an urgent matter and/or your work is being blocked by this.
