### ISSUE TITLE
How to cite WDL and Cromwell?

### ISSUE THREAD

**Issue by SitoTorres** [broadinstitute/cromwell#5187]
Hi! Being trying to find the info on the webpage but I don't seem to find it! How do I cite wdl and cromwell in my paper!!??

**Comment by aednichols** [comment]
Hello and thank you for your inquiry. For citation info please see https://gatkforums.broadinstitute.org/wdl/discussion/10125/cromwell-and-wdl-are-now-officially-citable-in-literature
