### ISSUE TITLE
How to retrieve all workflow options

### ISSUE THREAD

**Issue by guma44** [broadinstitute/cromwell#5246]
Hi, we allow users to run jobs with different workflow options and our users would like to know what options were used for given workflow run. I was searching a bit but I cannot find how to retrieve workflow options for given run. I can retrieve files that were uploaded (that's fine) from metadata but I would need also options listed if there were defaults set in the config file. Eg. user can change `read_from_cache=true` but if she does not supply any file the default option would not be listed in the metadata (nor in the `WORKFLOW_STORE_ENTRY` as far as I could check.

**Comment by aednichols** [comment]
The workflow options are not stored in metadata directly, but there is a record of how Cromwell behaved based on their values. For call caching, this is `allowResultReuse` and `effectiveCallCachingMode`. I _think_ we still record call caching info if the default is used. See https://github.com/broadinstitute/cromwell/releases/tag/25

**Comment by bolton-lab** [comment]
Is there an example of how to set call caching to true and allowResultReuse to true in the `-o options` file when running a workflow.  I am looking for examples and the documentation and I just keep guessing.  Both ways of setting outside of `callCaching` and inside still have my `-m metadata` file showing below:
```

"callCaching": {
        "allowResultReuse": false,
        "effectiveCallCachingMode": "CallCachingOff"
      },
```

options.json file:
```
{
	"default_runtime_attributes": {
		"write_to_cache": true,
		"read_from_cache": true,
		"system.file-hash-cache": true,
		"allowResultReuse" : true,
		"callCaching": {
			"hit": false,
			"effectiveCallCachingMode": "ReadAndWriteCache",
			"result": "Cache Miss",
			"allowResultReuse": true
		}
	}
}
```
