### ISSUE TITLE
Stopping and reruning cromwell process

### ISSUE THREAD

**Issue by PatrykBrzuchacz** [broadinstitute/cromwell#5300]
It's possible to stop cromwell, edit imported files and then rerun from a specific point?

**Comment by illusional** [comment]
If you back Cromwell with a database (see [persisting data between restarts](https://cromwell.readthedocs.io/en/stable/tutorials/PersistentServer/)), you are able to stop Cromwell and restart without job information loss.

After setting up this database, you can enable [call-caching](https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/) which if you modify your workflow, tools or inputs, will use previously computed results where:

- The command line used to generate the files is exactly the same
- The computed files still exist
-  Other [call-caching configurations](https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#call-caching-options) are valid.

Alternatively, you could always stop your workflow, and modify it to run only from the point you've executed from with your already computed files. Straight forward, but could be a little tedious.

**Comment by PatrykBrzuchacz** [comment]
So can i post wdl and other inputs, start pipiline and after get any status about created any files - stop process, get some data, edit files that is cromwell contains and then rerun it again?

**Comment by aednichols** [comment]
Can you elaborate on why you want the functionality described? It is possible that call caching will help, but be aware that Cromwell will only read from the cache when absolutely everything matches - hashes of input files, WDL workflow, etc.

**Comment by PatrykBrzuchacz** [comment]
i want to start process that is returning files in few steps, after first get files and check png's i want to edit something in input files and rerun process from this step

**Comment by aednichols** [comment]
It sounds like call caching should definitely solve your problem; the documentation links posted earlier should give you the info you need. If not feel free to reopen.
