### ISSUE TITLE
GATK4 jointdiscovery WDL issues with 6000 plus sample

### ISSUE THREAD

**Issue by Fazulur** [broadinstitute/cromwell#5305]
Dear WDL team,

I am using joint-discovery-gatk4.wdl for running jointcalling on 6000 plus samples using LSF as scheduler. I have lsf configuration file which was working with small set of samples. When I tried running Jointcalling on 6000+ samples using WDL, it is giving the below error.
 
**[2019-12-04 10:59:03,89] [ESC[38;5;220mwarnESC[0m] JobExecutionTokenDispenser - High load alert. Freeze token distribution.**
 
And I changed the concurrent-job-limit = 5000 in lsf configuration, now it is giving
 
**[2019-12-01 07:08:46,91] [info] WorkflowExecutionActor-b2c84d70-611d-4dad-bb18-78a6648e4113 [^[[38;5;2mb2c84d70^[[0m]: Starting JointGenotyping.ImportGVCFs (195 shards)
[2019-12-01 07:15:32,84] [^[[38;5;1merror^[[0m] Failed to summarize metadata
java.sql.SQLException: java.lang.OutOfMemoryError: GC overhead limit exceeded**

Could you please help me to proceed further.

Thanks In Advance
Fazulur Rehaman

**Comment by aednichols** [comment]
Looks like you need more memory to run that many things simultaneously. Try adjusting upward your JVM memory opts and if necessary your server’s physical memory. Hope this helps.
