### ISSUE TITLE
JES Backend fails call-caching if output y = input x

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#531]
The following workflow always fails on JES if call-caching is enabled. File paths are getting horribly mangled and the getHash fails.

```
task mirror {
  File x
  command {
    echo noop
  }
  output {
    File y = x
  }
}

workflow call_caching {
  File x_in
  Array[Int] blahs = [1,2,3,4,5,6,7,8,9,10]

  call mirror { input: x = x_in }

  scatter ( blah in blahs ) {
    call mirror as cached_mirror1 { input: x = mirror.y }
    call mirror as cached_mirror2 { input: x = cached_mirror1.y }
  }
}
```

**Comment by geoffjentry** [comment]
@cjllanwarne This looks like a "this might be fixed" candidate although I can't check it atm

**Comment by Horneth** [comment]
I'm pretty sure this is a centaur test

**Comment by cjllanwarne** [comment]
Added to the bug fix rotation milestone for verification/closing

**Comment by cjllanwarne** [comment]
Fixed as of today. Closing
