### ISSUE TITLE
Add Scalastyle for Cromwell

### ISSUE THREAD

**Issue by gauravs90** [broadinstitute/cromwell#537]
Once we decide on a style guide, go through the code and resolve all the issues / errors cropping up because of the check style.

**Comment by geoffjentry** [comment]
@gauravs90 What's the status of this? Are we still going w/ the XML file you & I pieced together?

**Comment by gauravs90** [comment]
@geoffjentry Yes, its that same XML, and a half baked version is lying in a local branch here on my laptop, after  which there were several PRs merged (possibly needing to re-fix all those changes. I think I should plan to sit with this and complete it in just one-shot-one-sitting in several increments. (I can push that branch to remote if you wanna have a look at it, or have a go at parts of it in some spare time?)

**Comment by geoffjentry** [comment]
Closing this ticket. As much as I love the idea my explorations led me to believe that it'd solve none of the nitpicky stuff that annoys people while adding *more* nitpicky stuff which would annoy people

**Comment by geoffjentry** [comment]
Addendum: scalafmt looks to be promising but is not yet to a place where I'd want to use it
