### ISSUE TITLE
Defining struct inline with boolean or float value causes no coercion defined from wom value error

### ISSUE THREAD

**Issue by keenangraham** [broadinstitute/cromwell#5414]
I know there have been some issues with read_object/write_object and structs but I haven't been able to find anything mentioning this particular problem.

If I define a struct with mixed types and assign a string and int value inline it works as expected (with cromwell-48):

```
version 1.0


struct Params {
    String? string
    Int? int
    Float? float
    Boolean? boolean
}


task print_params {
    Params p = {
        "string": "abc",
        "int": 4
    }

    command {
         echo -e "hello ~{p.string} ~{p.int}"
    }
}


workflow main {
    call print_params
}


// hello abc 4
```

If instead I just define a boolean value it also works:
```
version 1.0


struct Params {
    String? string
    Int? int
    Float? float
    Boolean? boolean
}


task print_params {
    Params p = {
        "boolean": true
    }

    command {
         echo -e "hello ~{p.boolean}"
    }
}


workflow main {
    call print_params
}


// hello true
```

However if I define a string and a boolean I get a wom conversion error:
```
version 1.0


struct Params {
    String? string
    Int? int
    Float? float
    Boolean? boolean
}


task print_params {
    Params p = {
        "string": "abc",
        "boolean": true
    }

    command {
         echo -e "hello ~{p.string} ~{p.boolean}"
    }
}


workflow main {
    call print_params
}

// Fails with no coercion defined from wom value(s) '"true"' of type 'String' to 'Boolean'.
```

Similarly for boolean and float:
```
version 1.0


struct Params {
    String? string
    Int? int
    Float? float
    Boolean? boolean
}


task print_params {
    Params p = {
        "boolean": true,
        "float": 0.04
    }

    command {
         echo -e "hello ~{p.float} ~{p.boolean}"
    }
}


workflow main {
    call print_params
}


// No coercion defined from wom value(s) '"true"' of type 'String' to 'Boolean'.
```

Though a float alone works:
```
version 1.0


struct Params {
    String? string
    Int? int
    Float? float
    Boolean? boolean
}


task print_params {
    Params p = {
        "float": 0.04
    }

    command {
         echo -e "hello ~{p.float}"
    }
}


workflow main {
    call print_params
}


// hello 0.04
```

If I try to define a float=0.04 and int=3 together I get `No coercion defined from wom value(s) '3.0' of type 'Float' to 'Int?'.` which is strange (seems like it's casting the 3 to 3.0 etc.).

In any case this only seems to be a problem with defining structs inline. The conversion seems to work okay if you use input.json or if you read_json from some params.json at runtime (however I want to fix parameters inline for my current use case).

The current workaround is to use object definition inline:

```
Params p = object {
        boolean: true,
        float: 0.04
 } 
```

This is okay but it seems like the object syntax is going to be deprecated in newer versions (and the WDL 1.0 spec doesn't have any examples of this). Also it's generally awkward that the JSON syntax works for some combinations but not others.

Thanks for any insights!

**Comment by rhpvorderman** [comment]
I think you should use the object notation here, because otherwise the construct will be evaluated as a map. Since you specified version 1.0 it is not weird that it crashes on stuff that is not valid WDL 1.0.

Could you try running with `version development` and see what happens?

**Comment by keenangraham** [comment]
Thanks for the clarification. I get same errors with `version development`.
 
> Since you specified version 1.0 it is not weird that it crashes on stuff that is not valid WDL 1.0.

I find this a little surprising. Maybe it is a documentation issue. The 1.0 spec says object literal and then shows an example using map literal? 

> Struct Assignment from Object Literal
> Structs can be assigned using an object literal. When Writing the object, all entries must conform or be coercible into the underlying type they are being assigned to
> 
> Person a = {"name": "John","age": 30}

In any case I think I was confusing Object type with object literal. I took following to mean object notation was also being removed:

> Be careful when using Object. They are superceded by 'struct' in WDL 1.0 and are being removed outright in WDL 2.0.

Can probably resolve this if this is intended usage.
