### ISSUE TITLE
womtool validate # sign in name

### ISSUE THREAD

**Issue by slzhao** [broadinstitute/cromwell#5434]
Hello,

I found that womtool validate can't ignore "#" in json file and will report 'Unexpected input provided'. I think this is a bug in womtool? Example listed below. The "#ValidateBamsWf.ValidateBAM.machine_mem_gb" line should be ignored as it starts with a "#"?

```
#all files downloaded from latest github version at https://github.com/gatk-workflows/seq-format-validation.git
java -jar womtool-48.jar validate validate-bam.wdl -i validate-bam.inputs.json         

```

> WARNING: Unexpected input provided: #ValidateBamsWf.ValidateBAM.machine_mem_gb (expected inputs: [ValidateBamsWf.ValidateBAM.disk_space_gb, ValidateBamsWf.gatk_docker_override, ValidateBamsWf.ValidateBAM.validation_mode, ValidateBamsWf.gatk_path_override, ValidateBamsWf.ValidateBAM.machine_mem_gb, ValidateBamsWf.bam_array])
> WARNING: Unexpected input provided: #ValidateBamsWf.ValidateBAM.validation_mode (expected inputs: [ValidateBamsWf.ValidateBAM.disk_space_gb, ValidateBamsWf.gatk_docker_override, ValidateBamsWf.ValidateBAM.validation_mode, ValidateBamsWf.gatk_path_override, ValidateBamsWf.ValidateBAM.machine_mem_gb, ValidateBamsWf.bam_array])
......

**Comment by aednichols** [comment]
Hi @slzhao, thanks for your interest in Cromwell and WDL.

You are correct that `#` is the comment character in WDL, but I am not aware of a documented feature that would allow `#` to be used in the inputs JSON. If that sounds wrong to you, please feel free to reopen.

**Comment by aednichols** [comment]
My recommendation would be to edit the JSON to remove the unwanted inputs; it is normal to have a few different input files for various scenarios.

**Comment by slzhao** [comment]
Hello @aednichols , thanks for your quick response. I am just following the examples provided by GATK best practice, such as the example above and another example at `https://gatk.broadinstitute.org/hc/en-us/articles/360035530952--How-to-Execute-Workflows-from-the-gatk-workflows-Git-Organization`

Any way, I will edit those files to remove #. Thank you!
