### ISSUE TITLE
one-off run has a slow startup time of 72s

### ISSUE THREAD

**Issue by shouldsee** [broadinstitute/cromwell#5451]
Question
-----------------
Is there any plan on speeding up `java -jar $JAR run`?  Pipeline developer would definitely benefits from a faster startup.

Symptom
-----------------
```bash
time java -jar cromwell-49.jar run sub-flow.wdl -i input.json
```

```
real	1m12.833s
user	1m12.148s
sys	0m7.644s
```

```
$ cat input.json 
{
"hello_and_goodbye.hello_and_goodbye_input":"test1"
}
```

Detail
----------
backend: local

File: `sub-flow.wdl`
```wdl
workflow myWorkflow {
    call myTask
}

task myTask {
    command {
        echo "hello world"
    }
    output {
        String out = read_string(stdout())
    }
}
```

**Comment by geoffjentry** [comment]
Why not use something like miniwdl? 

run mode was originally created for **cromwell** development purposes, although for most of time there wasn't really an alternative for workflow development.

**Comment by shouldsee** [comment]
> Why not use something like miniwdl?
> 
> run mode was originally created for **cromwell** development purposes, although for most of time there wasn't really an alternative for workflow development.

Hi Geoff thanks for your suggestion. I have checked miniwdl but it has a docker dependency which does not fit my need for a sudo-less installation. The devs will certainly benefit from a quick REPL for WDL.

**Comment by lindenb** [comment]
Hi all,

unless I'm wrong, I've got the same problem ( > 5 minutes for a Hello-World ) https://gist.github.com/lindenb/d89e69f31e1bc5d390dc043b48d651d9

I'm new to WDL. It's not clear to me if the `server` mode is the only 'true' way to run a WDL workflow (?)

**Comment by aednichols** [comment]
Server mode is the intended, first-class usage scenario for Cromwell. It's really [no harder to use](https://cromwell.readthedocs.io/en/stable/tutorials/ServerMode/) than run mode and enables way more features.

Run mode is in maintenance and we do not anticipate making enhancements.
