### ISSUE TITLE
Call ‘xxx’ doesn’t have an output ‘yyy’

### ISSUE THREAD

**Issue by guma44** [broadinstitute/cromwell#5479]
JIRA Issue for ref: [BA-6364](https://broadworkbench.atlassian.net/browse/BA-6364). Hi, I have a simple workflow that import subworkflow. After the subworkflow is run I would like to access an output from particular task from it. The output is not declared as an output of the subworkflow, and subworkflow is not maintained by us so I do not have a (easy) possibility to modify it. Here is the workflow:

```
import "subworkflow.wdl" as sub
workflow hello {
    call sub.hello
    call show {
        input: data = hello.say_hello.out
    }
}
task show {
    String data
    command {
        cat ${data}
    }
}
```

And subworkflow.
```
workflow hello {
    String name = "John"
    call say_hello {input: name = name}
}
task say_hello {
    String name
    command {
        which python
        python --version
        echo "Hello ${name}!"
    }
    output {
        String out = stdout()
    }
}
```
Of course I have an error: Call ‘hello’ doesn’t have an output ‘say_hello’ (line 6, col 29). But according to specs: `If the output {...} section is omitted, then the workflow includes all outputs from all calls in its final output.`

**Comment by rhpvorderman** [comment]
I am not from the Cromwell core team but what I can say is that in the latest openwdl hackathon that the consensus was `no output section -> no output`. Which is much more logical than `no output section -> all outputs`. This will be codified in WDL 2.0.

This does not answer your question, but I hope it gives some additional context.

**Comment by guma44** [comment]
Thanks a lot for the answer. We had to solve it in different way due to this.
