### ISSUE TITLE
Remove engine dependencies from backends

### ISSUE THREAD

**Issue by francares** [broadinstitute/cromwell#554]
Backend should not have any dependency from Engine.
This means that all utils implementation should be moved to backend or removed.
It may require a break down in sub-tasks.

**Comment by geoffjentry** [comment]
Or put in core if they're not a backed concept

**Comment by mcovarr** [comment]
Most of the remaining backend dependencies on engine look straightforward to move to backend or core, though there are a few prizes like the direct DB updates from JES and Local backends.  No heroics required, but do what's possible to remove unnecessary dependencies.
