### ISSUE TITLE
Lightweight and responsive workflow creation by moving heavy lifting to pollable future states

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#564]
Proposed high-level flow:

Workflows + inputs + options are submitted.  Any grossly malformed submission would quickly generate an error returned to the client immediately.  Otherwise save everything to WORKFLOW_EXECUTION and WORKFLOW_EXECUTION_AUX at status Submitted, and return the generated UUID to the client.

THAT’S IT.  Do not validate workflows synchronously to submission, that’s expensive and difficult to throttle back.  The returned UUID constitutes a pollable handle for the submission.  Technically this UUID is now a submission ID rather than a workflow ID, though if the workflow is eventually validated that UUID could certainly be thought of as the workflow ID.

When Cromwell is ready to validate a submission, the status of the WORKFLOW_EXECUTION can be moved to Validating and validation initiated.  Assuming the validation succeeds the workflow would move to state Validated.  Again when Cromwell is ready to run the workflow, it can be moved to state Running and the workflow would begin to run.  Workflows that fail validation would get status Failed with text describing the nature of the failures in the FAILURE_MESSAGES table.

**Comment by geoffjentry** [comment]
:+1: a bunch. It didn't take long to make me question why we tried to resolve a problem which involved doing too much stuff up front by adding even more stuff up front. 

I was talking about something a lot like this to one of our two main internal customers (I believe FC) and they were good with the idea - however I'd say that we should make sure to have official buy in from our internal policy makers just to be sure. The dept itself seems to be learning to wrap its collective head around models where not everything is immediate & 100% consistent fashion so it should be an easy sell now.

**Comment by geoffjentry** [comment]
I forgot I was supposed to use the new fandangled reactions these days! I'll give you the party hat or whatever it is

**Comment by Horneth** [comment]
:+1: to that - It reminds me that I've been thinking that we should have more workflow / call statuses, even if some of them are internal and are mapped out to the same external user facing status, but it would reflect more accurately what the current state of a workflow / call is (eg initializing, persisting, finalizing...)

**Comment by mcovarr** [comment]
Agree with @Horneth, these internal states could map to actors which could help break up the monolithic `WorkflowActor`, but these states don't necessarily need to be externally visible.

**Comment by kcibul** [comment]
double thumbs up on this one.  I don't want to muddy the SFD column right now with all the PBE work, but would love to prioritize this soon after that work is winding up

**Comment by geoffjentry** [comment]
Closing this one due to #1127
