### ISSUE TITLE
Problem with + and optional variable 

### ISSUE THREAD

**Issue by OgnjenMilicevic** [broadinstitute/cromwell#5694]
Hello! I used this snippet of code successfully on the Cromwell with Google backend:

```
task fastqc {
  input {
    File f1
    File? f2
    Int? cpu=1
    Int? machine_mem_gb
    Int? preemptible_attempts
    String mode

    Float f2size = if (mode == "PE") then size(f2, "GB") else 0.0
    Int disk_space_gb = ceil(size(f1, "GB") + f2size) + 20
  }

  command {
      fastqc -t ~{cpu} --outdir $PWD ~{f1} ~{f2}
  }

  output {
      Array[File] html = glob("*html")
      Array[File] zip  = glob("*zip")
  }

  runtime {
    docker: "biocontainers/fastqc:v0.11.5_cv2"
    memory: select_first([machine_mem_gb, 4]) + " GB"
    cpu: cpu
    disks: "local-disk " + disk_space_gb + " HDD"
    preemptible: select_first([preemptible_attempts, 3])
  }
}
```
On local backend I got this error:
_Failed to evaluate input '__disk_space_gb' (reason 1 of 1): Sorry! Operation + is not supported on empty optional values. You might resolve this using select_first([optional, default]) to guarantee that you have a filled value._

I tried following the advice (even though I don't see what is missing)
Float f2size = select_first([if (mode == "PE") then size(f2, "GB") else 0.0])
And then I got an even more confusing error:
_Failed to process task definition 'fastqc' (reason 1 of 1): Failed to process expression 'select_first([f2size, select_first([if (mode == "PE") then size(f2, "GB") else 0.0])])' (reason 1 of 1): Invalid parameter 'ArrayLiteral(Vector(TernaryIf(Equals(IdentifierLookup(mode),StringLiteral(PE)),Size(IdentifierLookup(f2),Some(StringLiteral(GB))),PrimitiveLiteralExpressionElement(WomFloat(0.0)))))'. Expected an array of optional values (eg 'Array[X?]') but got 'Array[Float]+'_

Can you help me understand? It all passes Womtools validation.

**Comment by illusional** [comment]
`size` is expecting a non optional file but `f2` is optional. The fix is to add `size(select_first([f2]), "GB")` You might consider adding `defined(X?)` to your if statement, but here's the suggested change:

```wdl
Float f2size = if (mode == "PE") then size(select_first([f2]), "GB") else 0.0`
```

**Comment by OgnjenMilicevic** [comment]
Thanks!

**Comment by OgnjenMilicevic** [comment]
Sorry, but this seems very related and I can't see why this is the problem:

```
task trim_PE {
  input {
    File f1
    File f2
    Int? cpu=1
#    Int? disk_space_gb=ceil(2*size(f1, "GB")+2*size(f2, "GB")) + 20
    Int? machine_mem_gb
    Int? preemptible_attempts
    String? adap
    String b1 = basename(basename(basename(f1, ".fastq"), ".fq"), ".gz")
    String b2 = basename(basename(basename(f2, ".fastq"), ".fq"), ".gz")
    String p1  = "W7_" + b1 + ".fq.gz"
    String p2  = "W7_" + b2 + ".fq.gz"
    String u1  = "W7_" + b1 + "_unpaired.fq.gz"
    String u2  = "W7_" + b2 + "_unpaired.fq.gz"
  }
```

This yields an error:
![image](https://user-images.githubusercontent.com/16489606/92958456-931bba00-f46a-11ea-97cb-ccc709929ad8.png)

Is this a similar problem?

**Comment by OgnjenMilicevic** [comment]
Actually, upon further examination b1 and b2 come up empty. Why does this triple basename return empty string? Is this not a valid synthax?

**Comment by OgnjenMilicevic** [comment]
OK, solved it. The whole block was in inputs which seem to be evaluated out of order or without it.

Moving the lines with basename out of the input block solved it!

Thanks!
