### ISSUE TITLE
 Unable to load the kernel module 'nvidia.ko'.

### ISSUE THREAD

**Issue by anniepgu** [broadinstitute/cromwell#5714]
###
###
###
###

Our backend: 
GCP PAPIv2 
actor-factory = "cromwell.backend.google.pipelines.v2alpha1.PipelinesApiLifecycleActorFactory"

endpoint-url = "https://genomics.googleapis.com/"

workflow runtime
runtime {
      docker: "us.gcr.io/cloudypipelines-com/til_segmentation:1.5"
      bootDiskSizeGb: 70
      disks: "local-disk 70 SSD"
      memory:  "52 GB"
      cpu: "8"
      maxRetries: 1
      gpuCount: 1
      zones: "us-east1-d us-east1-c us-central1-a us-central1-c us-west1-a us-west1-b"
      ##gpuType: "nvidia-tesla-k80"
      gpuType: "nvidia-tesla-t4"
      nvidiaDriverVersion: "418.40.04"
      ##nvidiaDriverVersion: "418.87.00"
     
 }

#### Recently, Our All workflows with GPU failed under the same configurations which  most of workflows used to work on Cromwell 48, we updated to the latest Cromwell 52, still had the same errors, see belowL

2020-08-04 23:44:00,228 cromwell-system-akka.dispatchers.engine-dispatcher-38 INFO  - WorkflowManagerActor Workflow f1dca11c-ea29-48b1-9691-9f30c9e59154 failed (during ExecutingWorkflowState): java.lang.Exception: Task wf_quip_lymphocyte_segmentation_v03232020.quip_lymphocyte_segmentation:NA:2 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: generic::unknown: installing drivers: container exited with unexpected exit code 1: + COS_DOWNLOAD_GCS=https://storage.googleapis.com/cos-tools
+ COS_KERNEL_SRC_GIT=https://chromium.googlesource.com/chromiumos/third_party/kernel
+ COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz
+ TOOLCHAIN_URL_FILENAME=toolchain_url
+ TOOLCHAIN_ARCHIVE=toolchain.tar.xz
+ TOOLCHAIN_ENV_FILENAME=toolchain_env
+ CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk
+ ROOT_OS_RELEASE=/root/etc/os-release
+ KERNEL_SRC_DIR=/build/usr/src/linux
+ NVIDIA_DRIVER_VERSION=418.40.04
+ NVIDIA_DRIVER_MD5SUM=
+ NVIDIA_INSTALL_DIR_HOST=/var/lib/nvidia
+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia
+ ROOT_MOUNT_DIR=/root
+ CACHE_FILE=/usr/local/nvidia/.cache
+ LOCK_FILE=/root/tmp/cos_gpu_installer_lock
+ LOCK_FILE_FD=20
+ set +x
[INFO    2020-08-04 23:40:07 UTC] Checking if this is the only cos-gpu-installer that is running.
[INFO    2020-08-04 23:40:07 UTC] Running on COS build id 12871.1174.0
[INFO    2020-08-04 23:40:07 UTC] Checking if third party kernel modules can be installed
[INFO    2020-08-04 23:40:07 UTC] Checking cached version
[INFO    2020-08-04 23:40:07 UTC] Cache file /usr/local/nvidia/.cache not found.
[INFO    2020-08-04 23:40:07 UTC] Did not find cached version, building the drivers...
[INFO    2020-08-04 23:40:07 UTC] Downloading GPU installer ...
[INFO    2020-08-04 23:40:09 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/418.40.04/NVIDIA-Linux-x86_64-418.40.04.run
ls: cannot access '/build/usr/src/linux': No such file or directory
[INFO    2020-08-04 23:40:11 UTC] Kernel sources not found locally, downloading
[INFO    2020-08-04 23:40:11 UTC] Kernel source archive download URL: https://storage.googleapis.com/cos-tools/12871.1174.0/kernel-src.tar.gz

real	0m2.220s
user	0m0.183s
sys	0m0.338s
[INFO    2020-08-04 23:40:18 UTC] Setting up compilation environment
[INFO    2020-08-04 23:40:18 UTC] Obtaining toolchain_env file from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain_env

real	0m0.126s
user	0m0.014s
sys	0m0.001s
[INFO    2020-08-04 23:40:18 UTC] Downloading toolchain from https://storage.googleapis.com/cos-tools/12871.1174.0/toolchain.tar.xz

real	0m11.907s
user	0m0.428s
sys	0m1.039s
[INFO    2020-08-04 23:41:17 UTC] Configuring environment variables for cross-compilation
[INFO    2020-08-04 23:41:17 UTC] Configuring installation directories
[INFO    2020-08-04 23:41:17 UTC] Updating container's ld cache
[INFO    2020-08-04 23:41:20 UTC] Configuring kernel sources
[INFO    2020-08-04 23:41:42 UTC] Modifying kernel version magic string in source files
[INFO    2020-08-04 23:41:42 UTC] Running Nvidia installer

ERROR: The kernel module failed to load, because it was not signed by a key
       that is trusted by the kernel. Please try installing the driver
       again, and set the --module-signing-secret-key and
       --module-signing-public-key options on the command line, or run the
       installer in expert mode to enable the interactive module signing
       prompts.

ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most
       frequently when this kernel module was built against the wrong or
       improperly configured kernel sources, with a version of gcc that
       differs from the one used to build the target kernel, or if another
       driver, such as nouveau, is present and prevents the NVIDIA kernel
       module from obtaining ownership of the NVIDIA GPU(s), or no NVIDIA
       GPU installed in this system is supported by this NVIDIA Linux
       graphics driver release.

       Please see the log entries 'Kernel module load error' and 'Kernel
       messages' at the end of the file
       '/usr/local/nvidia/nvidia-installer.log' for more information.

ERROR: Installation has failed.  Please see the file
       '/usr/local/nvidia/nvidia-installer.log' for details.  You may find
       suggestions on fixing installation problems in the README available
       on the Linux driver download page at www.nvidia.com.

**Comment by aednichols** [comment]
This is not a Cromwell problem, but rather a known issue affecting all users of Google Pipelines API.

Fortunately our contacts at Google report it will be fixed today.
