### ISSUE TITLE
Some inputs are being copied over twice for tasks

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#576]
**As a first step -- please confirm that this issue still exists**

It seems that some inputs are being copied over twice to the same path for all tasks. I'm not exactly sure when this started happening but the cromwell git hash we are currently using is https://github.com/broadinstitute/cromwell/tree/c66eabc3582085e28b197b667cb82b241ab6d1dd . Logs in comment.

In this example the input_bam and interval_list are listed twice as inputs.
jes operations ID for the following call : operations/EI3Pz-W1KhiNs_ydkKOavrwBIJ-ikOmeDSoPcHJvZHVjdGlvblF1ZXVl
295959:2016-03-09 18:46:47,375 cromwell-system-akka.actor.default-dispatcher-12 INFO - JesBackend UUID(a7884b2d):HaplotypeCaller:12: Starting call with pre-emptible VM
295960:2016-03-09 18:46:47,375 cromwell-system-akka.actor.default-dispatcher-12 INFO - JES Pipeline UUID(a7884b2d):HaplotypeCaller:12: Inputs:
295961: input_bam-0 -> disk:local-disk relpath:broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/a7884b2d-e859-4ef3-bb74-b820623755b4/call-GatherBamFiles/M1132.bam
295964: 2eb61371-0 -> disk:local-disk relpath:broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/a7884b2d-e859-4ef3-bb74-b820623755b4/call-GatherBamFiles/M1132.bam
295965: e1220deb-0 -> disk:local-disk relpath:broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/a7884b2d-e859-4ef3-bb74-b820623755b4/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/20scattered.interval_list
295966: interval_list-0 -> disk:local-disk relpath:broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/a7884b2d-e859-4ef3-bb74-b820623755b4/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/20scattered.interval_list
295968: input_bam_index-0 -> disk:local-disk relpath:broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/a7884b2d-e859-4ef3-bb74-b820623755b4/call-GatherBamFiles/M1132.bai

**Comment by Horneth** [comment]
I think this has been fixed already (see my comment in https://broadinstitute.atlassian.net/browse/DSDEEPB-2942)

**Comment by ruchim** [comment]
Have you had a chance to test the fix?

**Comment by scottfrazer** [comment]
@Horneth would you mind explaining to me how you figured that out?  I was looking over Jose's shoulder when this first happened and it was non-obvious to me what was happening.  Maybe my attempt to reproduce it failed because I was using post-PR499 code.

**Comment by Horneth** [comment]
Discussed with @scottfrazer, I reproduced the bug on the git hash provided by Jose, and same wdl didn't yield duplicate inputs on develop.
I think this can be marked resolved.

**Comment by ruchim** [comment]
@bradtaylor

**Comment by Horneth** [comment]
If you don't want to pull directly develop I can provide the oldest git hash that fixes this bug

**Comment by ruchim** [comment]
@Horneth that sounds good to me! @scottfrazer were you able to reproduce what you wanted? If yes, I'll close this issue.

**Comment by Horneth** [comment]
Git hash: 3eb1623d9a5ffdf0fc3626820eab84ae6560b2cd

**Comment by jsotobroad** [comment]
Awesome thanks guys!

**Comment by ruchim** [comment]
No-op, so I'll close this ticket.
