### ISSUE TITLE
Slurm + Docker cannot find script outside of container

### ISSUE THREAD

**Issue by OgnjenMilicevic** [broadinstitute/cromwell#5768]
Hello! I am trying to create a submit-docker block for use with docker containers, according to instructions from [here](https://cromwell.readthedocs.io/en/stable/tutorials/Containers/).

This is the how my config block looks:

```
    SLURM {
  actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
  config {
    runtime-attributes = """
    Int runtime_minutes = 600
    Int cpu = 1
    Int requested_memory_mb_per_core = 8000
    Int memory_mb = 4000
    String queue = "short"
    String? docker
    """

    submit = """
        sbatch -J ${job_name} -D ${cwd} -o ${out} -e ${err} -t ${runtime_minutes} -p ${queue} \
        ${"-c " + cpu} \
        --mem ${memory_mb} \
        --wrap "/bin/bash ${script}"
    """
    
    submit-docker = """
        docker pull ${docker}

        sbatch -J ${job_name} -D ${cwd} -o ${cwd}/execution/stdout -e ${cwd}/execution/stderr -t ${runtime_minutes} -p ${queue} \
        ${"-c " + cpu} \
        --mem ${memory_mb} \
        --wrap "docker run -v ${cwd}:${docker_cwd} ${docker} ${job_shell} ${script}"
    """

    kill = "scancel ${job_id}"
    check-alive = "squeue -j ${job_id}"
    job-id-regex = "Submitted batch job (\\d+).*"
  }
```
But, I get an error from each node:

/bin/bash: /data/og/wgs/cromwell-executions/HaplotypeCallerGvcf_GATK4/98c2fe18-92b7-49d4-b490-623ed61e3dfc/call-HaplotypeCaller/shard-41/execution/script: No such file or directory

As far as I can tell, it is trying to reach the script local on the main machine, and not in the docker container. Is this expected behavior, or am I missing something? I know I can replace ${script} with ${docker_cwd}/execution/script but I am unsure why I need this change that is not according to your documentation.

Thanks!

**Comment by illusional** [comment]
Hey @OgnjenMilicevic, looks like there is an error in that page. I believe it's supposed to be `${docker_script}` instead of `${script}`. 

For context, here is my config I use for Slurm + Singularity: https://gist.github.com/illusional/b70f870fa0e2f8e7a0ba0a9e71d568f5
