### ISSUE TITLE
Cromwell File to String conversion in output uses input name, not localized path name

### ISSUE THREAD

**Issue by illusional** [broadinstitute/cromwell#5785]
I'm noticing that in the outputs section of a task, that the basename is automatically applied. For example, running the following workflow:

```wdl
version development

task basenametest {
    input {
    	File inp
    }

    command <<<
        echo '~{basename(inp)}'
    >>>
    
    output {
        String outname = inp
        String outbasename = basename(inp)
        String out = read_string(stdout())
    }
}
```

with:

```bash
echo '{"inp": "inputs.json"}' >> inputs.json
java -jar cromwell-52.jar run basenametest.wdl --inputs "inputs.json"
```

I receive the output:

```json
{
  "outputs": {
    "escapetest.outname": "test.bam",
    "escapetest.out": "test.bam",
    "escapetest.outbasename": "test.bam"
  },
  "id": "<id>"
}
```

---

I think this might be logical, but differs from the spec and MiniWDL. I've put a message in the OpenWDL slack for clarification, but through me off a bit.

**Comment by pshapiro4broad** [comment]
The names in your output don't match your test input. The output I get is
```
    "basenametest.outbasename": "inputs.json",
    "basenametest.out": "inputs.json",
    "basenametest.outname": "/a/file/path/inputs.json"
```

What would you expect to see instead of these values? If you change the `inp` value in `inputs.json` to `"/a/file/path/inputs.json"` then I get:
```
    "basenametest.outname": "/a/file/path/inputs.json",
```
(assuming that a file at this path actually exists). This behavior matches what I'd expect to see.

**Comment by illusional** [comment]
Thanks @pshapiro4broad, sorry for detached example filename. I think I see more now what's happening now, but I'm less convinced it's the right behaviour. I believe the outputs section is using whatever is provided in the input, where I would expect it to be using the localised path. You're correct, if you use the full path in the inputs json (eg: `/path/to/inputs.json`), you get that full path in the outname.

I'll illustrate it a little bit differently, note that I've annotated a container in the basenametest task of the following workflow:

**outputsnametest.wdl**
```wdl 
version development 

workflow basenameconnectiontest {
    call createFile {}
    call basenametest {
        input:
            inp=createFile.out
    }

    output {
        String outname = basenametest.outname
        String outbasename = basenametest.outbasename
        String out = basenametest.out
    }
}

task createFile {
    input {}

    command <<<
        echo "Hello, Broad!"
    >>>

    output {
        File out = stdout()
    }
}

task basenametest {
    input {
        File inp
    }

    command <<<
        echo '~{inp}'
        echo '~{basename(inp)}'
    >>>
    
    output {
        String outname = inp
        String outbasename = basename(inp)
        String out = read_string(stdout())
    }
    runtime {
        docker: "ubuntu:latest"
    }
}
```

This time running with no inputs:

```bash
java -jar cromwell-52 run outputsnametest.wdl
```

```json
{
  "outputs": {
    "basenameconnectiontest.outbasename": "stdout",
    "basenameconnectiontest.out": "/cromwell-executions/basenameconnectiontest/51e0cb4d-f706-4540-9303-ed9c70a8764e/call-basenametest/inputs/-43085659/stdout\nstdout",
    "basenameconnectiontest.outname": "/Users/franklinmichael/Desktop/tmp/wdltests/cromwell-executions/basenameconnectiontest/51e0cb4d-f706-4540-9303-ed9c70a8764e/call-createFile/execution/stdout"
  },
  "id": "51e0cb4d-f706-4540-9303-ed9c70a8764e"
}
```

I would expect that the outname be the localised pathname (in the container), in this case that would be `/cromwell-executions/..../`.

**Comment by illusional** [comment]
Thanks @pshapiro4broad, I've updated the issue title. I don't know how much I agree with the behaviour, but to me it sounds strange. It's logged on OpenWDL, so I'll close this for now and reopen if required.

**Comment by pshapiro4broad** [comment]
See https://github.com/openwdl/wdl/issues/381
