### ISSUE TITLE
defaultRuntimeOptions in workflow options gives warnings, not clearly named either.

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#595]
When using the `defaultRuntimeOptions` field of workflow options, I get this warning:

```
[2016-03-21 12:59:31,470] [warn] Unrecognized workflow option(s): defaultRuntimeOptions
```

`defaultRuntimeOptions` is a valid workflow option so this warning is misleading.

Also, `defaultRuntimeOptions` is named oddly because lots of other places call it 'runtime attributes'

**Comment by mcovarr** [comment]
fixed
