### ISSUE TITLE
sub() expression language function

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#597]
As a pipeline author, I don't enjoy having to spin up a VM, with docker in order to do string substitutions on my parameters.  In the GOTC pipeline, we do this in order to strip off the extension of the input file in order to get a base-name, which happens ~40 times in a 20-plex workflow.  

This causes a real problem because by requiring so many VMs to spun up, we spend more money (although that cost is quite small) but also eat into our quotas and QPS limits, which actually does hurt our scalability.

The proposal is to add a new expression language function which allows for regex substitutions:

sub(string, pattern, replacement)

For example,

to strip off an extension from a file you could use `sub(filename, ".bam$","")`
to swap an extension, you could use `sub(filename, ".bam$", ".metrics")`

By being constrained to a regex (unlike an arbitrary code block) we don't have concerns about security or evaluating these in the cromwell engine.

This does not eliminate the need for a generally more expressive expression language or user defined functions, but does solve a large class of common usages that impact ease of use and performance

**Comment by cjllanwarne** [comment]
+1

**Comment by mcovarr** [comment]
I know we're supposed to be focusing on another class of work, but this sounds like great bang for the development buck.  :smile:
