### ISSUE TITLE
Figure out why Tyburn fails constantly, fix

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#598]
Way too many red Tyburn builds.  There was a commit last week that completely broke Cromwell in server mode that almost passed unnoticed due to all the red Tyburn runs that preceded it.

**Comment by geoffjentry** [comment]
Note that devops is starting to build out the centaur thing which should alleviate most/all of the tyburn redness. I'm hoping to have it within the week

**Comment by mcovarr** [comment]
Jeff has made it so Tyburn doesn't consistently fail instantly, now it consistently fails in ~50 minutes.  Progress!

**Comment by kcibul** [comment]
no more tyburn
