### ISSUE TITLE
Workflow Submission Cleanup Endpoint (Garbage Collection)

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#601]
As a user, I would like to be able to call an endpoint in cromwell which takes in a workflow submission identifier and have cromwell clean up all intermediate outputs of the workflow (files that are not declared as outputs of the workflow).
If there is a job avoidance feature when this is worked on, these cleaned up tasks internal to the workflow should not be eligible for job avoidance. However, the overall workflow would be eligible.

**Comment by cjllanwarne** [comment]
@kcibul @ruchim Could you opine (since "Job Avoidance" is certainly now available) what kind of behaviour we want if we "clear up" a call-cached task?

**Comment by katevoss** [comment]
This hasn't come up for a while, closing out.
