### ISSUE TITLE
Get rid of WorkflowManagerActor's state data

### ISSUE THREAD

**Issue by gauravs90** [broadinstitute/cromwell#606]
Currently, we are storing a relatively not-so-useful state data in the WMA. It is only used in case of abort to get the WA corresponding to the abortable workflow ID. The current scheme of things can be replaced by a relatively simple actor selection method for abort, which may have varied opinions amongst developers but I believe it provides a more bang for buck.

**Comment by gauravs90** [comment]
More triage is needed in terms of handling cases like `AbortAllWorkflows`

**Comment by cjllanwarne** [comment]
I like this so :+1: from me.

**Comment by cjllanwarne** [comment]
As long as we can still do "Abort All" and support Ctrl-C

**Comment by gauravs90** [comment]
Looking at it, and chewing my own words, the changes that I'm seeing has a few round-trips to the database (e.g. getting workflows in a particular state). Given that we are trying to reduce DB calls from the engine, do you guys think  it to be a good idea?

**Comment by Horneth** [comment]
Well we are already doing calls to the DB anyway in the current code no ?
If this will transform `State Data + DB calls` to `No State Data + other DB calls` it's still a win IMO.

**Comment by mcovarr** [comment]
It's possible there could be race conditions with this: submissions that were accepted but haven't been persisted yet, or persisted workflows that don't have workflow actors yet. I'm starting to think that state data is more useful than I originally thought...

**Comment by gauravs90** [comment]
@Horneth I believe the transformation is more like `StateData + DB Calls` to `DB Calls + more DB Calls`. Currently, the AbortAll route  just sends a msg to all the WorkflowActorRefs in the state data, and then waits's until the all the actors have responded with a terminal state.

**Comment by gauravs90** [comment]
In general, I feel that the DB calls should be used as sparingly as possible to have good scalability. And Miguel may be right here I believe

**Comment by geoffjentry** [comment]
From my perspective, since we know we'll be wanting (and likely needing) to completely revamp how submission is handled after the PBE changes I think that correctness of results trumps correctness of design.

That's not an opinion on anyone's proposals, just something to keep in mind.

**Comment by gauravs90** [comment]
What good is a correct design if it doesn't give correct results :stuck_out_tongue_closed_eyes:

**Comment by geoffjentry** [comment]
Heh, fair point :)

I just meant that it's probably not worth worrying about optimizing stuff around submission (although there are other aspects at play here besides submission) since itll need to be changed around soon anyways

**Comment by gauravs90** [comment]
Sure thing. This was just something that came up in one of the meetings, and I took an AR to work on it, hence the issue. I guess it can be closed based on the findings above.

**Comment by mcovarr** [comment]
Does this ticket still have relevance today?

**Comment by geoffjentry** [comment]
@mcovarr I almost proposed to close this ticket a couple of weeks ago, but when I poked around the WMA it seemed like some of the things being referenced were still around - so then the question becomes "is this actually a correct thing to do now" as opposed to "does it even make any sense at all". I figured that was something we should have a discussion on, and then promptly forgot about it.

**Comment by gauravs90** [comment]
If I recall correctly, it was proposed to not follow this route because the state consisted of the child workflow actor references in it, and was used to kill (or maybe abort) the workflow it was executing.

**Comment by geoffjentry** [comment]
At this point I'm saying "it is what it is" and not going to try to re-ascertain what's going on in this ticket :)
