### ISSUE TITLE
Step 1: Releasing Dependencies

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#608]
Releasing lenthall
This should be done if Lenthall has changed since the last release.

Releasing wdl4s
This should be done if wdl4s has changed since the last release

Releasing wdltool
This should be done if either lenthall or wdl4s has changed since the last release

Further details:https://broadinstitute.atlassian.net/wiki/display/DSDEEPB/Cromwell+Release

**Comment by mcovarr** [comment]
If this is actively being worked on, please be aware of broadinstitute/wdl4s#23 that is in flight.
