### ISSUE TITLE
Step 2: Release Candidate

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#609]
Create Release candidate branch (Please keep in mind the various issues marked "Blocks Release" as the plan is to include those changes in the next release.)

Verifying Release Branch

https://broadinstitute.atlassian.net/wiki/display/DSDEEPB/Cromwell+Release

**Comment by ruchim** [comment]
In order to test Issue 588 (and general restart issues) - run more than one multistep workflows and restart Cromwell 3x -- confirm it doesn't cause tasks to fail.

**Comment by Horneth** [comment]
Needs https://github.com/broadinstitute/cromwell/pull/593 merged

**Comment by cjllanwarne** [comment]
Someone will need to document the new configuration before this can be released.

**Comment by cjllanwarne** [comment]
https://github.com/broadinstitute/cromwell/issues/629
