### ISSUE TITLE
Atlas 2.1.0 -503 error

### ISSUE THREAD

**Issue by vijay-kattula** [broadinstitute/cromwell#6133]
Hi Atlas Team,

 

                I have installed the Atlas(apache-atlas-sources-2.1.0) in
our server by following in the link
"https://atlas.apache.org/2.0.0/InstallationSteps.html. After all the setup
have been done, we ran the atlas-start.py and the atlas is running on port
21000.When we are accessing the atlas, we are facing 503 Service Unavailable
Error.

We checked the logs from application.log file. We got below issue 

 

2020-12-13 06:29:02,309 WARN  - [main:] ~ JMX is not enabled to receive
remote connections. Please see cassandra-env.sh for more info.
(CassandraDaemon:81)

2020-12-13 06:29:02,310 ERROR - [main:] ~ cassandra.jmx.local.port missing
from cassandra-env.sh, unable to start local JMX service.null
(CassandraDaemon:87)

 

                We see there is no "cassandra-env.sh" file in atlas and we
tried other ways and didn't find any solution for the above error.

 

                Could you please help us in rectify these problem so that it
will be very helpful to us.

**Comment by geoffjentry** [comment]
@vijay-kattula Are you sure you're in the right place?

**Comment by vijay-kattula** [comment]
i felt the same:)
created new repo and posted the question. now i am closing this issue.
thank you
