### ISSUE TITLE
read_object problems

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#615]
I'm trying to run a WDL that examines disk sizes using `df -kh`. Unfortunately, read_object is not able to parse the output which appears to match the spec:
The WDL:

```
task df_kh {
 Int bootDiskSizeGb
 command { df -kh / }
 runtime {
  docker: "ubuntu:latest"
  bootDiskSizeGb: bootDiskSizeGb
 }
 output {
   Int size = read_object(stdout()).Size[0]
 }
}

workflow someBootDisks {
 call df_kh as smallBootDisk { input: bootDiskSizeGb = 10 }
 call df_kh as bigBootDisk { input: bootDiskSizeGb = 50 }
}
```

The console output (example):

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/disk1      465G   70G  396G  15% /
```

**Comment by mcovarr** [comment]
In this case `df` produces space-separated columns, but `read_object` is looking for tab separators.  So this particular failure is to be expected.
