### ISSUE TITLE
Cromwell 55 expected to handle 504 error in GCS but instead WDL pipeline failed

### ISSUE THREAD

**Issue by freeseek** [broadinstitute/cromwell#6154]
My WDL pipeline failed to run with Cromwell 55 configured with the `cromwell.backend.google.pipelines.v2beta.PipelinesApiLifecycleActorFactory` Google API with a long list of errors such as the following:
```
...
  {
    "causedBy": [
      {
        "causedBy": [
          {
            "message": "504 Gateway Timeout\nGET https://storage.googleapis.com/download/storage/v1/b/mccarroll-mocha/o/cromwell%2Fcromwell-executions%2Fmocha%2F86d47e9a-5745-4ec0-b4eb-0164f073e5f4%2Fcall-idat2gtc%2Fshard-73%2Frc?alt=media",
            "causedBy": []
          }
        ],
        "message": "Could not read from gs://mccarroll-mocha/cromwell/cromwell-executions/mocha/86d47e9a-5745-4ec0-b4eb-0164f073e5f4/call-idat2gtc/shard-73/rc: 504 Gateway Timeout\nGET https://storage.googleapis.com/download/storage/v1/b/mccarroll-mocha/o/cromwell%2Fcromwell-executions%2Fmocha%2F86d47e9a-5745-4ec0-b4eb-0164f073e5f4%2Fcall-idat2gtc%2Fshard-73%2Frc?alt=media"
      }
    ],
    "message": "[Attempted 1 time(s)] - IOException: Could not read from gs://mccarroll-mocha/cromwell/cromwell-executions/mocha/86d47e9a-5745-4ec0-b4eb-0164f073e5f4/call-idat2gtc/shard-73/rc: 504 Gateway Timeout\nGET https://storage.googleapis.com/download/storage/v1/b/mccarroll-mocha/o/cromwell%2Fcromwell-executions%2Fmocha%2F86d47e9a-5745-4ec0-b4eb-0164f073e5f4%2Fcall-idat2gtc%2Fshard-73%2Frc?alt=media"
  }
],
"message": "Workflow failed"
```
I was under the expectation that this had been handled in issue #5344 and that Cromwell would retry to access the files until available (the files do indeed exist at the time of this writing).

**Comment by aednichols** [comment]
Thanks. I think I have a clue, your lowest level exception says
```
504 Gateway Timeout\nGET https://storage.googleapis.com/download/storage/v1/b/mccarroll-mocha/o/cromwell%2Fcromwell-executions%2Fmocha%2F86d47e9a-5745-4ec0-b4eb-0164f073e5f4%2Fcall-idat2gtc%2Fshard-73%2Frc?alt=media
```
which does not match the pattern
```
".*Could not read from gs.+504 Gateway Timeout.*"
```
introduced in https://github.com/broadinstitute/cromwell/pull/5344

**Comment by aednichols** [comment]
@freeseek if I send you a patched JAR do you think you'd be able to verify the fix?

Which is to say, do you get 504s frequently enough that you can test updated handling?

**Comment by freeseek** [comment]
I actually only ever got this issue once, and that's it. I am currently re-running the same WDL pipeline and it is working fine. But if you send me a new JAR, I am more than happy to run that from now on and report back if I encounter the same issue again.

**Comment by aednichols** [comment]
> So was the error report useful? Is there anything else I need to provide? Thank you for replying sooo quickly! -Giulio

Yes, I've heard about people still having this issue but you are the first to provide the full error message (and also provide confirmation by being another data point)

I'll try to my fix idea of shortening the pattern in the regular release, if you're not likely to repro I won't do the custom JAR.

**Comment by aednichols** [comment]
Hi @freeseek, we found the bug and the fix will ship in Cromwell 56. Thanks again for reporting.
