### ISSUE TITLE
Could not download toolchain archive from https://storage.googleapis.com/chromiumos-sdk/2020/06/x86_64-cros-linux-gnu-2020.06.25.065836.tar.xz, giving up.

### ISSUE THREAD

**Issue by anniepgu** [broadinstitute/cromwell#6195]
###
###
###
###

  
Jobs which required gpuType: "nvidia-tesla-t4", nvidiaDriverVersion: "418.40.04",  failed.

Our pipeline backend is Google : genomics.googleapis.com
"jes": {
          "endpointUrl": "https://genomics.googleapis.com/",
          "zone": "us-central1-f",
           ....
        },

job runtimeAttributes:
...
          "preemptible": "1",
          "gpuCount": "1",
          "failOnStderr": "false",
          "bootDiskSizeGb": "70",
          "disks": "local-disk 70 SSD",
          "continueOnReturnCode": "0",
          "gpuType": "nvidia-tesla-t4",
          "nvidiaDriverVersion": "418.40.04",
          "maxRetries": "0",
          "cpu": "8",
          "cpuMin": "1",
          "noAddress": "false",
           "zone": "us-central1-f",
          "memoryMin": "2 GB",
          "memory": "64 GB"

Jobs failed with following message:
 "Task wf_quip_lymphocyte_segmentation_incep_v01052021.quip_lymphocyte_segmentation:NA:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: generic::unknown: installing drivers: container exited with unexpected exit code 1: + COS_KERNEL_INFO_FILENAME=kernel_info\n+ COS_KERNEL_SRC_ARCHIVE=kernel-src.tar.gz\n+ COS_KERNEL_SRC_HEADER=kernel-headers.tgz\n+ TOOLCHAIN_URL_FILENAME=toolchain_url\n+ TOOLCHAIN_ARCHIVE=toolchain.tar.xz\n+ TOOLCHAIN_ENV_FILENAME=toolchain_env\n+ TOOLCHAIN_PKG_DIR=/build/cos-tools\n+ CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk\n+ ROOT_OS_RELEASE=/root/etc/os-release\n+ KERNEL_SRC_DIR=/build/usr/src/linux\n+ KERNEL_SRC_HEADER=/build/usr/src/linux-headers\n+ NVIDIA_DRIVER_VERSION=450.51.06\n+ NVIDIA_DRIVER_MD5SUM=\n+ NVIDIA_INSTALL_DIR_HOST=/var/lib/nvidia\n+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia\n+ ROOT_MOUNT_DIR=/root\n+ CACHE_FILE=/usr/local/nvidia/.cache\n+ LOCK_FILE=/root/tmp/cos_gpu_installer_lock\n+ LOCK_FILE_FD=20\n+ set +x\n[INFO    2021-02-22 23:09:17 UTC] PRELOAD: false\n[INFO    2021-02-22 23:09:17 UTC] Running on COS build id 13310.1209.10\n[INFO    2021-02-22 23:09:17 UTC] Data dependencies (e.g. kernel source) will be fetched from https://storage.googleapis.com/cos-tools/13310.1209.10\n[INFO    2021-02-22 23:09:17 UTC] Getting the kernel source repository path.\n[INFO    2021-02-22 23:09:17 UTC] Obtaining kernel_info file from https://storage.googleapis.com/cos-tools/13310.1209.10/kernel_info\n[INFO    2021-02-22 23:09:19 UTC] Downloading kernel_info file from https://storage.googleapis.com/cos-tools/13310.1209.10/kernel_info\n\nreal\t0m0.072s\nuser\t0m0.013s\nsys\t0m0.006s\n[INFO    2021-02-22 23:09:19 UTC] Checking if this is the only cos-gpu-installer that is running.\n[INFO    2021-02-22 23:09:19 UTC] Checking if third party kernel modules can be installed\n[INFO    2021-02-22 23:09:19 UTC] Checking cached version\n[INFO    2021-02-22 23:09:19 UTC] Cache file /usr/local/nvidia/.cache not found.\n[INFO    2021-02-22 23:09:19 UTC] Did not find cached version, building the drivers...\n[INFO    2021-02-22 23:09:19 UTC] Downloading GPU installer ... \n[INFO    2021-02-22 23:09:19 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/nvidia-cos-project/85/tesla/450_00/450.51.06/NVIDIA-Linux-x86_64-450.51.06_85-13310-1209-10.cos\n[INFO    2021-02-22 23:09:19 UTC] Downloading GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/nvidia-cos-project/85/tesla/450_00/450.51.06/NVIDIA-Linux-x86_64-450.51.06_85-13310-1209-10.cos\n\nreal\t0m1.891s\nuser\t0m0.181s\nsys\t0m0.449s\n[INFO    2021-02-22 23:09:21 UTC] Setting up compilation environment\n[INFO    2021-02-22 23:09:21 UTC] Obtaining toolchain_env file from https://storage.googleapis.com/cos-tools/13310.1209.10/toolchain_env\n[INFO    2021-02-22 23:09:21 UTC] Downloading toolchain_env file from https://storage.googleapis.com/cos-tools/13310.1209.10/toolchain_env\n\nreal\t0m0.042s\nuser\t0m0.014s\nsys\t0m0.003s\n[INFO    2021-02-22 23:09:21 UTC] Found toolchain path file locally\nls: cannot access '/build/cos-tools': No such file or directory\n[INFO    2021-02-22 23:09:21 UTC] /build/cos-tools: \nls: cannot access '/build/cos-tools': No such file or directory\n[INFO    2021-02-22 23:09:21 UTC] Downloading toolchain from https://storage.googleapis.com/chromiumos-sdk/2020/06/x86_64-cros-linux-gnu-2020.06.25.065836.tar.xz\n[INFO    2021-02-22 23:09:21 UTC] Downloading toolchain archive from https://storage.googleapis.com/chromiumos-sdk/2020/06/x86_64-cros-linux-gnu-2020.06.25.065836.tar.xz\ncurl: (16) Error in the HTTP2 framing layer\n\nreal\t0m3.705s\nuser\t0m0.573s\nsys\t0m1.834s\n[ERROR   2021-02-22 23:09:25 UTC] Could not download toolchain archive from https://storage.googleapis.com/chromiumos-sdk/2020/06/x86_64-cros-linux-gnu-2020.06.25.065836.tar.xz, giving up.\n"

What caused those errors? Any recommendations?
Thanks!

**Comment by aednichols** [comment]
This appears to be an issue with Pipelines API and its container-optimized OS ("COS") not having the right drivers for the GPU. You could potentially try [changing the Nvidia driver version](https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#gpucount-gputype-and-nvidiadriverversion) but I think your best bet is asking Google support.
