### ISSUE TITLE
Jobs failed with Unable to complete PAPI request due to system or connection error (PipelinesApiRequestHandler actor termination caught by manager)

### ISSUE THREAD

**Issue by anniepgu** [broadinstitute/cromwell#6203]
###
###
###
###

endpoint-url = "https://genomics.googleapis.com/"
Cromwell version 55

All job submissions stopped working today with errors:
Unable to complete PAPI request due to system or connection error (PipelinesApiRequestHandler actor termination caught by manager)"

Error messages from Cromwell logs:
cromwell.backend.google.pipelines.common.api.PipelinesApiRequestWorker$$anon$1: A batch of PAPI status requests failed. The request manager will retry automatically up to 10 times. The error was: 404 Not Found
POST https://genomics.googleapis.com/batch
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
...

**Comment by aednichols** [comment]
This is not a Cromwell bug. Please follow this incident for details: https://support.terra.bio/hc/en-us/articles/360057183692
