### ISSUE TITLE
workflow output pattern matching incorrectly matching aliased tasks with common prefixes

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#622]
I had two separate calls defined as

call MatrixRotation as RotateGVCF
call MatrixRotation as RotateGVCFIndex

my output block looks like

output {
  RotateGVCF.*
}

and this will produce the outputs of both of the calls.  If I changed the name of RotateGVCFIndex to RotateIndex then only the output of RotateGVCF would be shown as expected.

**Comment by Horneth** [comment]
This is a WDL4s bug https://github.com/broadinstitute/wdl4s/issues/22
