### ISSUE TITLE
error while retrieving metadata for workflow because row count exceeds configured limit

### ISSUE THREAD

**Issue by freeseek** [broadinstitute/cromwell#6236]
After running a job that completed (or so it seems by the files generated ... Cromwell labels it as failed), I tried to retrieve the metadata but I got this error message instead:
```
{
  "status": "error",
  "message": "Metadata for workflow xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx exists in database but cannot be served because row count of 1249471 exceeds configured limit of 1000000."
}
```
I have tried to understand what configuration variable holds this 1000000 row limits, but I could not figure it out. :-( I think it would save users valuable time if they were directed to what to do when these type of very specific errors are recognized. I know this is a little bit more work on the developer side but I would certainly be very grateful ... and I would also stop asking questions. :-)

**Comment by aednichols** [comment]
Hi, you should find what you need in the example conf file: https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/cromwell.examples.conf#L522-L526

**Comment by freeseek** [comment]
A collaborator from DSP had pointed me to increasing the option by changing the variable:
```services.MetadataService.config.metadata-read-row-number-safety-threshold = 1000000```
and then, after Googling it, I did see that example. But I could not find an explanation of that variable in the documentation. :-)
