### ISSUE TITLE
Change 'backendsAllowed' to be additional backends

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#631]
Convert the 'backendsAllowed' to be a set of backends which are added to the default backends (e.g. a concept like "other allowed backends"). The set of all backends cromwell knows about is the union of the default plus this set.

This will prevent a situation where a task is assigned the default backend but the default backend is not allowed

**Comment by cjllanwarne** [comment]
I think this one's out of date. I'm closing but open again if it's still valid.
