### ISSUE TITLE
metadata: when does the hash contains the file paths ?

### ISSUE THREAD

**Issue by wangxuehan** [broadinstitute/cromwell#6316]
cromwell : 47
wdl : version 1.0
SGE

It is found that some tasks can not hit cache, and the common feature of these tasks is that the MD5 value of "call caching"-"hashes"-"input"-"file input bam" contains the path (cromwell workdir) of the file:
```
curl -X GET "http://myserver:8082/api/workflows/v1/f6450b4b-926a-4cfe-a879-c0e3653f8bc2/metadata?expandSubWorkflows=true" -H "accept: application/json" >metadata.json
```
part of metadata.json:
```
"input": {
  "String memory": "5BB45AB74E6536FF29BF9B2272D68AA3",
  "String sample": "C59B185FAE4EAE4F0EDFDE1B62772C72",
->"File inputBam": "5b6a0c7aa65cbfcfe2e85ba8b326e5cd  /TJPROJ6/GB_HUMAN/USER/aicancer/service/cromwell_humanReseq_hw/cromwell-executions/ToSomatic/487f5806-1c45-4d34-b2ca-c1a14af84100/call-Mapping/shard-0/Mapping/35a10f29-4a0a-461c-92ff-7f1d293cd321/call-bamMd5/inputs/1427979241/WESMSI_1.final.bam",
  "Boolean block": [
    "B326B5062B2F0E69046810717534CB09"
  ],
  "Int cpu": "C4CA4238A0B923820DCC509A6F75849B",
  "String workflowDir": "E0EA73CD86E0488226AB05800286E665",
  "Int maxRetries": "C4CA4238A0B923820DCC509A6F75849B",
  "String outputDir": "820E83FAC13C924AC573955CC2836C6B",
  "String sge_queue": "4CD545F87E55F6DB707BFFBA55AB3028"
}
```
The md5 value of bam entered contains the file path, but other tasks do not. 
What kind of settings or file transfer methods will lead to such differences? 
Will md5 value contains the file paths affect hit cache?
My WDL code:
```
version 1.0
import "tasks/mapping.wdl"
workflow Mapping {
    input {
        String sample
        String novoid
        String mappingDir
        String genome
        String referenceFasta
        Boolean removedup
        Array[Comair] cleanPairs
        String? targetbed
        Boolean recal = false
        Boolean block = true
        String tmpdir
        String? sge_queue
        String workflowDir
    }
    String finalBamPath = "${mappingDir}/${sample}.final.bam"
    call mapping.flag_stats as flagStats {
    input:
        sample = sample,
        inputBam = finalBamPath,
        outputDir = mappingDir,
        block = [picardMarkdup.done],
        sge_queue = sge_queue,
        workflowDir = workflowDir
    }
```

Please help me, thanks a lot !

**Comment by aednichols** [comment]
I recommend using the call cache diff endpoint
```
GET ​/api​/workflows​/{version}​/callcaching​/diff
```

> This endpoint returns the hash differences between 2 completed (successfully or not) calls.

**Comment by wangxuehan** [comment]
> I recommend using the call cache diff endpoint
> 
> ```
> GET ​/api​/workflows​/v1/callcaching​/diff
> ```
> 
> > This endpoint returns the hash differences between 2 completed (successfully or not) calls.

Thank you, i will try it

**Comment by wangxuehan** [comment]
I tried the `GET ​/api​/workflows​/v1/callcaching​/diff`, but it didn't  seam to work, and something wrong in Array.....

I compared the "callCaching" of the same task between two workflows, all of them is the same except the red box :
![image](https://user-images.githubusercontent.com/70520563/115682260-dedefc00-a387-11eb-8164-f21830f1c4a6.png)
md5 values are the same, but the following paths are different

Therefore, I guess the reason of cache miss hit is caused by "md5+path"
And Who knows how to remove path from MD5 value ?

I've tried many ways, but I don't know how to get rid of path in MD5 value. 
Who can help me please !

**Comment by wangxuehan** [comment]
Finally, I found out why the MD5 value contains the file path. I Hope it can help others:

### The server config:
`check-sibling-md5 : true`
When true, will check if a sibling file with the same name and the .md5 extension exists, and if it does, use the content of this file as a hash.
So i checked the metadata, i found all of hash with file path records is connecting with md5 task, the task command :
```
command <<<
md5sum ~{inputfile} > ~{inputfile.md5}
>>>
```
: ( that is a stupid mistakes, right?  
1. The `inputfile` is a file with whole path, so the md5 task will generate a hash with path like "b882eaf8272a52d3eea851d74a6b4aec  /path/sample.final.bam", and write to the file `inputfile.md5`. 
2. The cromwell server will find the `inputfile` sbling md5 with the name `inputfile.md5`, which contains hash with path. So the callcaching in metadata records it.
3. The next workflow will not hit cache because the file path are different

**Comment by aednichols** [comment]
Huh, I wonder how that got set to `true` for you. It appears to default to `false` in all the code and documentation I could find.

**Comment by wangxuehan** [comment]
> Huh, I wonder how that got set to `true` for you. It appears to default to `false` in all the code and documentation I could find.

I am just one of the Server user. The admin set the config of cromwell server ,and others submit the jobs to the server, so I met this problem
