### ISSUE TITLE
Batch submission endpoint

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#634]
As a user (FireCloud) I have the use case of wanting to submit a number of workflows (~1000) that are all the same WDL with different inputs.  For example, running the same pipeline on all samples in my cohort.  Currently I have to do this with 1000 separate calls which is inefficient.

I would like a new batch submission endpoint which allows me to submit a single WDL, a single workflowOptions and an array of inputJsons.

The server will take this and create the individual submissions and return an array of workflow ids are in the same order as the submitted jsons (e.g. the first returned id will be for the workflow that uses the first supplied json and so on).

**Comment by ccarrizo** [comment]
We had to solve the same problem some time back. but as we didn't want to modify the engine decided to implement it on the frontend. if it helps, next Monday we can show what we have; else if it will be a change on Cromwell we could make use of it.

**Comment by helgridly** [comment]
To highlight a (hopefully) obvious point: the sooner we can get that list of workflow IDs back, the better. Were you to do the horrendously naive thing and keep the connection open while you process the workflows serially, that'd be no use to us :)

**Comment by kcibul** [comment]
@dvoet @kshakir can you update the description above to reflect what you decided w.r.t. interface (POST vs GET, array of JSONs or a JSON containing the individual input JSONs, etc)
