### ISSUE TITLE
Workflow labels: ingest at submission time

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#635]
As a user, I would like to be able to supply a set of labels (key strings with optional string values) to my workflow at submission time that Cromwell will store for me associated with this workflow.  It should be returned in the workflow metadata.  

The allowable values should follow the same for the Google Pipelines API (since that's a well thought out approach).  See https://cloud.google.com/genomics/reference/rest/v1alpha2/pipelines/run#RunPipelineArgs.FIELDS.labels

This will allow me to group workflows into logical units so I can manage efficiently.  

It will also be queryable #636

It will also be propagated to Google's Pipeline API #1624

**Comment by abaumann** [comment]
oh yes 👍  to this

**Comment by kcibul** [comment]
@cjllanwarne
