### ISSUE TITLE
Execution script not found when running cromwell with docker

### ISSUE THREAD

**Issue by cnizo** [broadinstitute/cromwell#6353]
Hello!

I am running cromwell with docker on macOS (Big Sur v 11.2.3). When executing the following command from a simple WDL:

```

docker run   --cidfile /cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller/execution/docker_cid   -i      --entrypoint /bin/bash   -v /cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller:/cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller:delegated   pegi3s/gatk-4@sha256:8415200fe87b4d4eb295e9decb207727e9f75aad73c860a8d0ffe3385a8eaa7a /cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller/execution/script
```

I get the error: 

```

/bin/bash: /cromwell-executions/VarCallAndTable/5a729547-b927-431f-9793-8a2ac48035ea/call-HaplotypeCaller/execution/script: No such file or directory

```

After some digging, my guess is that the `docker run` command is not mounting the contents of `/cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller`.
For that reason the execution script is not found. Has anyone experieced this? 
Are there any settings I should edit for it to work?

Really appreciate the help!

**Comment by freeseek** [comment]
What happens if you run the docker manually and interactively with the following command?
```
docker run \
  --rm -it \
  --cidfile /cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller/execution/docker_cid \
  -i \
  --entrypoint /bin/bash \
  -v /cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller:/cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller:delegated \
  pegi3s/gatk-4@sha256:8415200fe87b4d4eb295e9decb207727e9f75aad73c860a8d0ffe3385a8eaa7a
```
Can you then find the file `/cromwell-executions/VarCallAndTable/00a1e01d-4341-4ea4-8225-a9fdaab526c1/call-HaplotypeCaller/execution/script` within the docker environment?

**Comment by cnizo** [comment]
Hi! Sorry, I only saw the response today!
I managed to make it work by defining `working_dir: ${PWD}/cromwell` in my cromwell container at `docker-compose.yml`.
I am closing the issue but leaving the comment in case anyone bumps into this.
Thank you!

**Comment by calebthomas259** [comment]
In case it helps anyone else: I had the same error message, but in a different context (I wasn't using docker compose. Instead, I was trying to set up a local backend run using a limited number of CPUs via the `concurrent-job-limit` configuration value, as described on these pages: [1](https://cromwell.readthedocs.io/en/stable/Configuring/), [2](https://cromwell.readthedocs.io/en/stable/backends/Backends/#backend-job-limits), [3](https://github.com/broadinstitute/cromwell/blob/b9b1adef95bea3c74db8534736b61625b6c66ebe/cromwell.example.backends/README.md)).

I ended up fixing the error by changing the value for the `backend.providers.LocalExample.config.submit-docker` option in my configuration file. I.e. initially, I was using the value from the [example config file](https://github.com/broadinstitute/cromwell/blob/b9b1adef95bea3c74db8534736b61625b6c66ebe/cromwell.example.backends/LocalExample.conf), but for some reason this was giving me an error. When I replaced it with an updated version obtained from [this internal cromwell file](https://github.com/broadinstitute/cromwell/blob/b9b1adef95bea3c74db8534736b61625b6c66ebe/core/src/main/resources/reference_local_provider_config.inc.conf), it started working
