### ISSUE TITLE
Cromwell 406 response when submitting wdl

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#638]
We submitted an inputs json that had a google storage path to a file that did not exist.   We recieved a 406 response with no other information.  In the Cromwell server logs there are references to a 404 error from what it seems is Cromwell trying to grab the hash of the file from google.  Is there any way this could be propagated to the response so its clear to the user what file caused the error instead of just a 406 response code?

**Comment by cjllanwarne** [comment]
We now workflows given IDs and they have these sorts of failures reported outside of the submission loop. So, the requested information will now be available from the submitted workflow's metadata.
