### ISSUE TITLE
cromwell ERROR: Finished parsing without consuming all tokens

### ISSUE THREAD

**Issue by GregTD42** [broadinstitute/cromwell#6438]
1: I attempted to use your Jira tracker, it let me log in but told me I don't have permission to see anything or do anything
2: https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team no longer exists, and the support staff respond to questions with "we only answer GATK isues"
3: I am using womtool 65 and Cromwell 62.  I get the same failure in both, which is that if the first line of my file is:

`version development`

As per the [WDL specifications](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#versioning) I get the error:

`ERROR: Finished parsing without consuming all tokens.`

If I do not include that line, then I get this error:

```
Expected rbrace, got Directory.
    Directory	OutputDir
```

Does Cromwell support WDL versions pther than the default?  if so, how do I specify which version to use?

Thank you,
###
###
###
###

**Comment by aednichols** [comment]
A WDL with no version specified is treated as a `draft-2` WDL. Version numbers were introduced with `1.0`.

Most likely what's happening is that your WDL is a valid `draft-2` workflow that needs updating to `1.0`.

Please post the entire WDL.

**Comment by GregTD42** [comment]
The WDL is part of an entire pipeline, that I can't post here

But I can share this:
[WDLTesting.zip](https://github.com/broadinstitute/cromwell/files/6827255/WDLTesting.zip)

```
$ $CROMWELL_HOME/womtool validate WDLTesting/src/wdl/Workflow.wdl 
Failed to import 'WDLTesting/src/wdl/WriteTask.wdl' (reason 1 of 1): ERROR: Unexpected symbol (line 11, col 2) when parsing 'setter'.

Expected equal, got "String".

	String	input2 = "Default"
 ^

$setter = :equal $e -> $1
```

**Comment by GregTD42** [comment]
If you don't want to open the zip:

WDLTesting/src/wdl/Workflow.wdl:
version development

import "WDLTesting/src/wdl/WriteTask.wdl" as Write


workflow TestingWF
{
	call Write.WriteTask as Writer
	{
		input:
			input1 = "Foo"
    }

}

WDLTesting/src/wdl/WriteTask.wdl:
version development

#################################################################################################
##       				This WDL script writes its inputs to stdout				               ##
#################################################################################################


task WriteTask {

	String	input1	# Variable with no default value
	String	input2 = "Default"
	
	command <<<
		echo "input1 = ${input1}"
		echo "input2 = ${input2}"
	>>>
	
    output {
        String	isDone = input2
    }
}

**Comment by aednichols** [comment]
In WDL 1.0 onwards task inputs must be in an `input` block: https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#task-inputs

The following modification validates as expected:

`Workflow.wdl`
```
version development

import "WDLTesting/src/wdl/WriteTask.wdl" as Write


workflow TestingWF
{
    call Write.WriteTask as Writer
    {
        input:
            input1 = "Foo"
    }

}
```

`WriteTask.wdl`
```
version development

#################################################################################################
##       				This WDL script writes its inputs to stdout				               ##
#################################################################################################


task WriteTask {

    input {
        String input1	# Variable with no default value
        String input2 = "Default"
    }
	
    command <<<
        echo "input1 = ${input1}"
        echo "input2 = ${input2}"
    >>>
	
    output {
        String	isDone = input2
    }
}
```

**Comment by GregTD42** [comment]
Thank you
