### ISSUE TITLE
wdl development doesn't import files

### ISSUE THREAD

**Issue by GregTD42** [broadinstitute/cromwell#6441]
Directory structure:

```
WDLTesting
-src
--wdl
---Workflow.wdl
---WriteTask.wdl
---Child
----ChildWF.wdl
----ChildTask.wdl
```

Under draft 2 (which is to say, no version specified), Workflow.wdl has the following import statements:
```
import "WDLTesting/src/wdl/WriteTask.wdl" as Write
import "WDLTesting/src/wdl/Child/ChildWF.wdl" as Child
```
ChildWF.wdl has the following import statement:
`import "WDLTesting/src/wdl/Child/ChildTask.wdl" as Child`

This works correctly.  it works letting things be access from the file system, and it works if we zip up WDLTesting and pass it to Cromwell as --imports

Under version development, this doesn't work.  Workflow.wdl's imports still work, but ChildWF.wdl's do not.  I must trim it down to 
`import "Child/ChildTask.wdl" as Child`
Before it will work.

This completely breaks our pipeline, especially since workflows calling files up and down the tree, and even in other projects that start at the same level as ours.

Why was this horrible breaking change made, and how do we specify an import that works with respect to the --imports .zip?

Thank you

**Comment by aednichols** [comment]
The import behavior in `draft-2` is convenient but is essentially a bug.

Any Unix tool run in the `WDLTesting/src/wdl/Child` directory would similarly report that `WDLTesting/src/wdl/Child/ChildTask.wdl` does not exist. That's because it's actually located at `../../../../WDLTesting/src/wdl/Child/ChildTask.wdl` relative to that directory.

It is acknowledged that many people came to rely on it, which is why fixing it was reserved for a major version. Cromwell does not decide the spec, if you have issues with that please raise them [here](https://github.com/openwdl/wdl).

I do not recommend running a production pipeline on version `development` as it is not yet a shipping version and could be subject to change at any time.

Career pro tip, calling an open source maintainer's work "horrible" is not a winning strategy to get them to help you 😏

**Comment by GregTD42** [comment]
Thank you @aednichols 

1: I understand that it's free, and I'm only owed what I've paid for. :-)

2: A Unix tool running in the `WDLTesting/src/wdl`directory would report that `WDLTesting/src/wdl/Child/ChildWF.wdl` does not exist.  But because it's being called from the main workflow, that still works.  It seems to be that you can say "all file references based off the launching directory work", or  "no file references based off the launching directory work, you have to evaluate the reference based on the location of the file that made the reference".

Saying "sometimes it will work, and sometimes it won't.  We know you've been depending on this behavior, but we're nuking it anyway"?  That, I would say, is rather user unfriendly

3: All that said, that change, making a called workflow behave significantly differently from the starting workflow, was at least easily dealt with. (I wrote a python script to update the import statements.)  But the change that called workflows no longer get passed anything from the JSON file.  Given a choice between adding 10 - 50 parameters to each sub-workflow call, and just sticking with draft-2, we're sticking with draft-2

So, thank you for your time, and good luck going forward

**Comment by aednichols** [comment]
Hello again and thanks for your input. It is a valid observation that changes from `draft-2` are substantial and invasive.

The "draft" aspect of `draft-2` entailed some behaviors that sounded good in the early experimental phases but proved to be problematic or somehow unmaintainable in the engine codebase.

That said `draft-2` is sticking around for the foreseeable future and should provide a stable if no-longer-enhanced platform for your group.

**Comment by geoffjentry** [comment]
@GregTD42 As a third party observer, the thing I'll point out is that the Cromwell team didn't make this decision. They do not own the WDL spec, rather they provide one of the implementations of it.

As an example, I have things I dislike about Java, but if I were to build a JVM I would need to implement the spec as described warts & all.

As @aednichols stated, the proper place to take issue with the WDL spec is [here](https://github.com/openwdl/wdl)

**Comment by aednichols** [comment]
In particular probably this issue: https://github.com/openwdl/wdl/issues/214
