### ISSUE TITLE
local execuation problem

### ISSUE THREAD

**Issue by gudeqing** [broadinstitute/cromwell#6458]
Hi，I have learned that cromwell does not support 【cpu and memory】runtime attributes for local backends（see https://cromwell.readthedocs.io/en/develop/RuntimeAttributes/）.  Thus, when running a workflow locally， How can we avoid concurent jobs that may crash the workflow by running out of memory？ I know that maximum job number can be limited, and some jobs can be parallelized wildly for they require only little resources , however, some jobs should not be paralleized for need of large memory.  So, we need to check available resource before submit a job. 

best wishes!

**Comment by aednichols** [comment]
The best documentation we have is the discussion on this ticket: https://broadworkbench.atlassian.net/browse/CROM-6716

( login requires a free account )

Feel free to reopen if it does not solve your problem.
