### ISSUE TITLE
When cromwell runs a job, it must copy the input files (local backend, cromwell 0.19)

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#646]
Development of WDL scripts would be *much* easier if we did not have to copy input files during execution of a job.  This causes hardships, since the bam files might be quite large.  

I tried modifying ``application.conf`` to eliminate the "copy" localization strategy.  However, this just caused a crash ("unable to localize...").  In other words, hard links and soft links seem to be supported, but do not function.

"Use smaller bam files for testing WDL" is not a good answer, since:

1.  This would require a lot of setup work solely for testing WDL scripts.
2.  This would rule out WDL/cromwell for load testing and automated evaluations, which are run frequently.  We regularly have to process hundreds of bam files for a single evaluation.
3.  We have several auxiliary files that are quite large and these are copied, as well.  Add this to point #1 above, since we would have to strip these down as well.
4.  This would not suss out problems that appear with larger bam files -- a common problem.  
5.  Our tools already run quickly on large files.

Many thanks!

**Comment by LeeTL1220** [comment]
Not using docker
Local backend

**Comment by kshakir** [comment]
aka [DSDEEPB-2898](https://broadinstitute.atlassian.net/browse/DSDEEPB-2898)

**Comment by geoffjentry** [comment]
@LeeTL1220 note #727 which should be merged soon

**Comment by sripakpa** [comment]
Hi Sir/Madam,

I was wondering if anyone can tell me what will be the first released (tagged) version of cromwell that have this issue resolved? I am using cromwell v1.9.3 on local backend (mac labtop), and it seem that this is still an issue in v1.9.3.

Thank you!

**Comment by geoffjentry** [comment]
@sripakpa There's no such thing as `1.9.3` presumably you mean `19.3`. There's only one tagged version after that, `19.4`.

That said there are few people who wouldn't be better served pulling off of develop HEAD at this point, unless someone needs call caching I'd encourage any user to use 0.21 (develop)

**Comment by sripakpa** [comment]
Hi @geoffjentry,

Thank for the quick reply.

Yes, I meant 0.19.3. Will take your suggestion and just use the commit at the HEAD of develop branch for now.

Btw, can you comment on how stable the codebase at HEAD of develop branch is currently? Are you guy close to releasing/tagging 0.21.x?

**Comment by geoffjentry** [comment]
@sripakpa 0.21 is imminent, we're just wrapping up call caching in the new system, which is why that's the one use case not yet satisfied. There's also some bug squashing going on but once call caching is complete we're going to release. 

I've been encouraging people to switch to develop for a month or two now and it's been working out for the most part. It has its own issues which will need to be worked out but it's already superior in every way to 0.19.x (minus the call caching)
