### ISSUE TITLE
Parse WDL Source, get Workflow Descriptor

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#648]
First part of the validation, verify that the submission is a proper workflow.

**Comment by geoffjentry** [comment]
@gauravs90 Is this being actively worked on at the moment (and/or has it actually been started?)

**Comment by gauravs90** [comment]
Waiting for Chris's PR to come in with the WA FSM states.

**Comment by geoffjentry** [comment]
@gauravs90 But is it in progress or no? We were trying to figure out why there were tickets not listed as in progress which were assigned to people.

**Comment by gauravs90** [comment]
Currently, it's not in progress. I began looking at it and realized I need #683 for this to work. Do you want me to bring it back to Need Triage?

**Comment by geoffjentry** [comment]
It's more the pre-assigning we were wondering about. OTOH the board was a giant jumble this morning so we didn't know what was/wasn't actually in flight

**Comment by geoffjentry** [comment]
@gauravs90 Chris' PR merged in. Is this now in progress? If not can I unassign you so someone else can take it?

**Comment by gauravs90** [comment]
Yep..Now in progress.

**Comment by geoffjentry** [comment]
Perfect, thanks!
