### ISSUE TITLE
Create Backend Factory

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#649]
Create Backend Factory (depends on completion of Backend Configs)

**Comment by ruchim** [comment]
Hey @francares, just re-opening the ticket so that when the dependencies related to BackendConfigs and ShadowWorkflowActor are resolved, it can be then be worked on in the future. Hope thats okay!

**Comment by geoffjentry** [comment]
@francares Now that this is back in ready column can we clear the assignment?

**Comment by francares** [comment]
Yes, we can.

**Comment by ruchim** [comment]
👍 done
