### ISSUE TITLE
womtool fails on graph building

### ISSUE THREAD

**Issue by EugeneEA** [broadinstitute/cromwell#6499]
Hi I did try to build DAG for a task from WARP pipeline, and wom failed with an error
https://github.com/broadinstitute/warp/issues/438
Turns out it it no a problem of a pipeline, but possibly a bug in a wom.

Best, Eugene

**Comment by olesya13** [comment]
The issue still persists with wom-73. It fails on /warp/tasks/broad/UnmappedBamToAlignedBam.wdl (https://github.com/broadinstitute/warp/tree/WholeGenomeReprocessing_v3.0.1) but works on other workflows from /warp/tasks/broad

**Comment by EugeneEA** [comment]
@olesya13 it turns out that the problems are caused by lines `if (unmapped_bam_size > cutoff_for_large_rg_in_gb) ` and `unmapped_bam_size <= cutoff_for_large_rg_in_gb`. If you substitute these expression to `true` wom will build the Dag. It seems that the wom cannot process workflow if some there are such expressions which can block execution completely (if one of these two is `false` wfl will fail)

Best, Eugene
