### ISSUE TITLE
Move Backend Specific Validation into constructor

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#651]
Depends upon the Stubbed out backends.

**Comment by geoffjentry** [comment]
@francares Is this actively being worked on and/or has been started already?

**Comment by francares** [comment]
@geoffjentry I will start today with this one.

**Comment by cjllanwarne** [comment]
NB I think this should be renamed to "... into `validate()` on the BackendWorkflowInitializationActor" :)
