### ISSUE TITLE
Implement Workflow Execution using Backend Interface

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#652]

**Comment by gauravs90** [comment]
@cjllanwarne @mcovarr @geoffjentry I would like to take up this ticket next. Do you guys recollect on what's exactly expected of this PR?

**Comment by cjllanwarne** [comment]
@gauravs90 I would say this maybe could be done in smaller chunks. For this first step, maybe just implement enough for a single step workflow to pass through the WorkflowExecutionActor? I think that should be fairly small but will involve ironing out a lot of the issues with the interface.

**Comment by gauravs90** [comment]
Alright. So I'll base this off of #717, and this PR will target to run (hopefully) n number of calls in a workflow (simplistically, a three step workflow should be able to go through completion)
