### ISSUE TITLE
Implement Retryable in Workflow Actor

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#655]
The (edit by Chris: ~~Workflow Actor~~ WorkflowExecutionActor) should take action based on the kind of failure returned by the BE and retry if so indicated

**Comment by cjllanwarne** [comment]
I think this depends on #652 (implement execution)

**Comment by gauravs90** [comment]
@cjllanwarne Does this only require handling the retryable failure in the WorkflowExecutionActor, by re-running the failed call up to a `max` number of retries? Your previous comment somehow indicates this is perhaps more than this.
