### ISSUE TITLE
Recover support for Local PBE

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#666]

**Comment by geoffjentry** [comment]
I think we didn't support this in 0.19 due to impossibility, however w/ the changes that @kshakir is putting in perhaps this is not possible?

**Comment by ruchim** [comment]
Based on the conversation after standup yesterday, this ticket needs more refinement. Currently, recovering a call for the local backend is the same as executing a fresh call. It's possible there are other ways to wire recovery and that question needs to be answered. @kcibul @geoffjentry I'm returning it to the milestone backlog but hopefully something we can discuss at the prioritization today--seems like a technical/PO type of refinement.

**Comment by kcibul** [comment]
cromwell customers aren't asking for this feature, putting back in the backlog
