### ISSUE TITLE
Update Engine to call Metadata Service API

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#668]

**Comment by geoffjentry** [comment]
With an n of 2 I've now heard 2 opposing viewpoints on how this should happen but yet still don't have a good handle on what the actual issue is, technical pros/cons, etc. I'd like to talk about this further before anyone acts on it.

**Comment by cjllanwarne** [comment]
Depends on #782, #783

**Comment by gauravs90** [comment]
Hey @kcibul / @geoffjentry ! Can we add a little more details to this ticket? For instance, what all stuff from the engine do we think should go into the MetadataService? I'd like to take this up but not sure what stuff should we be adding.
