### ISSUE TITLE
is there an oprion to re-run failed workflow?

### ISSUE THREAD

**Issue by EugeneEA** [broadinstitute/cromwell#6752]
Dear cromwell team, I was looking for means to re-submit failed workflow but did not find one, are there such options?

It is a valuable mode, possible use cases:

1) I'm trying to debug a task at the end of the long workflow - currently every small change in a code force me to re-run the whole pipeline to see the results. It would be way easy to manually delete given `call` folder from cromwell working directory `cromwell-execution/piplene/wfID/call-xxx` and resubmit the workflow to server with something like that: `submit --resubmit wfID newimport.zip`

2) my workflow failes on some task due to bug in the code – I’m editing the code and resubmitting it so workflow just continue where it stops

3) I'd like to change parameters of some of the later steps of the pipeline but do not want to waste time on re-running the beginning of the pipeline (which usually has a computationally heavy tasks like mapping, calling, etc)

I have an experience in using Snakemake and have to say that there those problems do not exist as far as I can always re-run desired rules of the pipeline changing Snakemake file or manually deleting given output

Best, Eugene

**Comment by aednichols** [comment]
You can create a new submission with the same inputs and Cromwell will read from call-cache (i.e. skip) tasks it has already done.

https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/
https://support.terra.bio/hc/en-us/articles/360047664872-Call-caching-How-it-works-and-when-to-use-it

**Comment by EugeneEA** [comment]
> You can create a new submission with the same inputs and Cromwell will read from call-cache (i.e. skip) tasks it has already done.
> 
> https://cromwell.readthedocs.io/en/stable/cromwell_features/CallCaching/ https://support.terra.bio/hc/en-us/articles/360047664872-Call-caching-How-it-works-and-when-to-use-it

ah I see, thanks for pointing me here
