### ISSUE TITLE
GCP backend always uses us-central1

### ISSUE THREAD

**Issue by jdidion** [broadinstitute/cromwell#6774]
Here is how I've configured GCP:

```
backend {
  default = "PAPIv2"
  providers {
    PAPIv2 {
      actor-factory = "cromwell.backend.google.pipelines.v2beta.PipelinesApiLifecycleActorFactory"
      config {
        project = "***"
        root = "***"
        genomics {
          auth = "application-default"
          endpoint-url = "https://us-west2-lifesciences.googleapis.com/"
          location = "us-west2"
        }
        filesystems {
          gcs {
            auth = "application-default"
            project = "***"
          }
        }
      }
    }
  }
}
```

And yet the worker instances are running on us-central1. Which also means it's copying data across regions (because my data is in us-west2).

<img width="2017" alt="image" src="https://user-images.githubusercontent.com/125854/171462418-63cdc51b-1f9e-4a9c-90c6-479a36946628.png">

**Comment by aednichols** [comment]
I think what you're running into is that the `endpoint-url` refers to where the Life Sciences / Genomics application _itself_ runs, which is different than where the compute VMs spin up. 

You can try putting `us-west2` in the WDL runtime section, or in the workflow options JSON. Both of those should be readily Googleable in terms of documentation, if you get stuck definitely comment.

> The location you specify is only used to store metadata about the pipeline operation.

[Source.](https://cloud.google.com/life-sciences/docs/concepts/locations#available_locations)

**Comment by aednichols** [comment]
Excellent! Glad to hear it!
