### ISSUE TITLE
Could not find or load main class  cromwell.jar

### ISSUE THREAD

**Issue by JoArrow** [broadinstitute/cromwell#6796]
Hello,

when I try to run my workflow using a config file using

`$ java -Dconfig.file=../config/LSF.conf cromwell.jar cromwell run ../pipelines/bismark_pid.wdl -i ../pipelines/bismark_wgbs_pid.json`

I get the following message
```
Error: Could not find or load main class cromwell.jar
Caused by: java.lang.ClassNotFoundException: cromwell.jar
```

Without specifying a config file, the pipeline runs without any problems. 
I installed Cromwell (version 79) using conda.

I also tried the following:

`$ java -Dconfig.file=../config/LSF.conf cromwell-79.jar run ../pipelines/bismark_pid.wdl -i ../pipelines/bismark_wgbs_pid.json `

```
Error: Could not find or load main class cromwell-79.jar
Caused by: java.lang.ClassNotFoundException: cromwell-79.jar
```

I also checked where the cromwell.jar file is saved in my conda environment and tried the following:

`
java -Dconfig.file=./LSF.conf /path/to/env/share/cromwell/cromwell.jar cromwell run ../pipelines/bismark_pid.wdl -i ../pipelines/bismark_wgbs_pid.json `

This is the config file LSF.config:
```
include required(classpath("application"))

backend {

  # Override the default backend.
  default = LSF

  # The list of providers. Copy paste the contents of a backend provider in this section
  providers {
    LSF {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
	submit = "bsub -J ${job_name} -cwd ${cwd} -o ${out} -e ${err} /usr/bin/env bash ${script}"
        kill = "bkill ${job_id}"
        check-alive = "bjobs ${job_id}"
        job-id-regex = "Job <(\\d+)>.*"
      }
    }
    # Second backend provider would be copy pasted here!

  }
}
```

I have not much experienced with cromwell and would be very grateful for help.

Thank you,
Johannes

**Comment by aednichols** [comment]
The [quick start tutorial](https://cromwell.readthedocs.io/en/stable/tutorials/FiveMinuteIntro/) uses

```
java -jar cromwell-XY.jar [ ... ]
```

so the `-jar` option would be the first thing to try. I also removed the potentially extraneous `cromwell` in `cromwell.jar cromwell run`:

```
java -jar cromwell.jar -Dconfig.file=../config/LSF.conf run ../pipelines/bismark_pid.wdl -i ../pipelines/bismark_wgbs_pid.json
```

If that doesn't work for you, feel free to reopen the issue.
