### ISSUE TITLE
At least a dozen Cromwell configuration links broken (not a copy of #6329)

### ISSUE THREAD

**Issue by aofarrel** [broadinstitute/cromwell#6797]
Several pieces of this repo link to/mention `Cromwell.example.backends/Cromwell.examples.conf`, but that file appears to no longer exist. Cromwell's readthedocs is also affected.

This previously happened in 2021 (https://github.com/broadinstitute/cromwell/pull/6329), so it may be worth hosting Cromwell.examples.conf somewhere more stable if this repo undergoes a lot of reorganization.

Affected pages (might not be exhaustive):
* https://cromwell.readthedocs.io/en/develop/cromwell_features/HogFactors/
* https://github.com/broadinstitute/cromwell/blob/develop/docs/tutorials/ConfigurationFiles.md
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/LocalExample.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/AWS.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/HtCondor.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/LSF.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/PAPIv2.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/README.md
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/SGE.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/TESK.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/TESK.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/singularity.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/singularity.slurm.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/slurm.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/udocker.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/udocker.slurm.conf
* https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/volcano.conf

**Comment by zane529** [comment]
The volcano.conf doesn't work, please remove it.
