### ISSUE TITLE
Cromwell restart issue

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#684]
I restarted Cromwell with one workflow running and one of my tasks failed with this exception: 

2016-04-07 20:32:28,188 cromwell-system-akka.actor.default-dispatcher-20 ERROR - WorkflowActor [UUID(03db4daf)]: Completion work failed for call CollectQualityYieldMetrics:9.
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '27-PairedEndSingleSampleWorkflow.CollectQualityYieldMetrics-metr' for key 'UK_SYM_WORKFLOW_EXECUTION_ID_SCOPE_NAME_ITERATION_IO'

the logs can be found on gotc-staging - 20160407-cromwell.log

**Comment by geoffjentry** [comment]
@jsotobroad would you be amenable to chalking this up to 0.19 and if you see it in the future making a new ticket? If so, can you close? If not, can you give information on how to reproduce this?

**Comment by cjllanwarne** [comment]
Closing this now. The MySQL constraint violation cannot happen again so any other problem will be a separate issue.
