### ISSUE TITLE
Add call caching changes to release notes

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#685]
It would be nice to know when upgrading to a new version of Cromwell if calls cached by the previous version are expected to be usable in the new version.

**Comment by geoffjentry** [comment]
Considering the release and thus the release notes have already happened I'm going to close this even if it wasn't fully satisfied.

@jsotobroad You likely already know this but FWIW the caching is not forward compatible from 0.19 to 0.21 but we expect to be forward compatible from here on out
