### ISSUE TITLE
sbt assembly: build errors "cloud/nio/spi/UnixPath.scala:72:7: `override` modifier required to override concrete member"

### ISSUE THREAD

**Issue by junaruga** [broadinstitute/cromwell#6902]
I executed `sbt assembly` to create the `womtool.jar` following [the document](https://cromwell.readthedocs.io/en/develop/WOMtool/). Below is the log. The full log is [here](https://gist.github.com/junaruga/2264c715606deee88b40de0de4e7a1b0) on the latest develop branch <54fed3e172e2138cd956c0b9663c05a8a5d34dbc>.

```
$ sbt assembly
...
[error] /home/jaruga/git/broadinstitute/cromwell/cloud-nio/cloud-nio-spi/src/main/scala/cloud/nio/spi/UnixPath.scala:72:7: `override` modifier required to override concrete member:
[error] <defaultmethod> def isEmpty(): Boolean (defined in trait CharSequence
[error]   def isEmpty: Boolean = path.isEmpty
[error]       ^
[error] one error found
...
[error] /home/jaruga/git/broadinstitute/cromwell/centaur/src/main/scala/centaur/api/DaemonizedDefaultThreadFactory.scala:17:26: method getSecurityManager in class System is deprecated
[error]   private val s = System.getSecurityManager
[error]                          ^
[error] one error found
...
```

## My environment.

* Fedora Linux 36

```
$ java --version 
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (Red_Hat-17.0.4.0.8-1.fc36) (build 17.0.4+8)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.0.8-1.fc36) (build 17.0.4+8, mixed mode, sharing)

$ scala --version
Scala code runner version 2.13.8 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.

$ sbt --version
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/home/jaruga/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.5/run_2.12-1.5.5.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release

sbt version in this project: 	1.5.5
sbt script version: 1.7.1
```

**Comment by junaruga** [comment]
I just downloaded the `womtool-84.jar` at <https://github.com/broadinstitute/cromwell/releases> I didn't need to build the source.

**Comment by aednichols** [comment]
Cromwell requires Java 11 [0][1] and I see 17 there.

[0] https://cromwell.readthedocs.io/en/stable/Releases/
[1] https://github.com/broadinstitute/cromwell/blob/develop/CHANGELOG.md#60-release-notes

**Comment by junaruga** [comment]
Oh OK. Thanks for the info. I didn't know that. How about adding the Java version check task on top of the build process?
Reference: <https://stackoverflow.com/questions/2591083/getting-java-version-at-runtime>.

**Comment by aednichols** [comment]
Cool idea but it would require our code to actually run, which is a potentially unreachable condition if it does not compile.

**Comment by junaruga** [comment]
Right.  But alternative is to compile the version check task in a difference process. I am not familiar with the Scala. It's like [this source](https://www.scala-sbt.org/1.x/docs/sbt-by-example.html#Create+a+source+file), small code with the `main`.

```
sbt assembly
  => execute new assembly task
      => execute version check task => compile Java
      => execute current assembly task including Java 11 specific code. => compile Java
```

**Comment by aednichols** [comment]
I see, yes, a build stage could work. Feel free to file an issue or PR for this. (I looked briefly and did not figure it out.)
