### ISSUE TITLE
More Cromwells for Better Deployment

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#691]
From Henry --

My comment is a little different than the commenter above. So I will try to provide some context in order to differentiate.

If one looks at Cromwell as being part of a larger application infrastructure/service such as a Genomics Pipeline where sequenced data is constantly being processed through the system or providing a service where users on the Internet can launch workflows "as a Service" - whenever they way.

In these systems, uptime and availability are critical - at all times. Below are several scenarios where I could see running multiple Cromwells would be very beneficial.

High availability:
Having multiple Cromwells running where jobs are "load balanced" between them would allow us to continue operate when there are systems issues or failures with one of the Cromwell instances.

Zero-downtime deployments:
Supporting multiple Cromwells running different versions of the code, could provide the ability to upgrade Cromwell with little or no user impact. Essentially the new version is deployed to a new server, it is started up and at an appropriate time traffic (via a load balancer or proxy maybe) is directed away from the "old version" Cromwell to the new.

Similar to item 2: being able to introduce infrastructure changes (host OS, security patches, host resizing,..) more seamlessly:
If I can support multiple instances of Cromwell, I can build a new instance of the host with all the updates and changes I require - deploy cromwell to the new node and cut over.

A corollary to this request is also the ability to "move" workflows from one Cromwell instance to another. Maybe this is just workflows not in flight or active - but waiting to run. This capability could make it easier to retire older cromwell instances (once multiple cromwell instances support is in place). Some workflows may take days to run, being able to "relocate" these workflows to the "new" cromwell - allows us to decommission "old" cromwells faster.

**Comment by geoffjentry** [comment]
@hjfbynara 

Disagree. This is an implementation specific request, not a request for outside functionality.

**Comment by geoffjentry** [comment]
Sorry for the terseness/curtness - wanted to flesh this out now that I have a real keyboard.

From an IT perspective of how things are managed I'm AOK with whatever, but the cromwell codebase shouldn't be aware that it was part of a true multi-cromwell environment. From that angle, this issue would be a ticket for IT's backlog, not ours.

Once/if we get to a place where it *does* involve code changes to Cromwell itself, that's when I'm going to go back to being outspoken in my support for certain models :)

**Comment by hjfbynara** [comment]
@davidbernick Here is the issue I raised around supporting multiple Cromwells.

**Comment by kcibul** [comment]
hey everyone -- this needs a little whiteboarding, plus taking a step
back.  Definitely important, it's just bigger than  a ticket about how we
need "more cromwells."


-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
