### ISSUE TITLE
Update WorkflowManagerActor to *only* support the ShadowWorkflowActor. Erase olde stylee WorkflowActor

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#692]

**Comment by cjllanwarne** [comment]
Might depend on #688

**Comment by geoffjentry** [comment]
@cjllanwarne Is this something you're actively working on (i.e. is that why it's assigned to you)?

**Comment by cjllanwarne** [comment]
@geoffjentry I've had a look at WMA a bit but this one's blocked on #688... it was what I was going to work on next though.

**Comment by gauravs90** [comment]
@cjllanwarne Is this supposed to bring all the functionality from the old WA to the new Shadow WA and get rid of the 'shadow execution path'?

**Comment by geoffjentry** [comment]
@cjllanwarne Is this now in progress?
