### ISSUE TITLE
cromwell fails to download url input file

### ISSUE THREAD

**Issue by jfroula** [broadinstitute/cromwell#6977]
This seems like a bug.

In my inputs.json, I have an input file that is a URL. Cromwell (v84) fails to pull it when I'm not using "Local" as a backend. The only difference between a working case and failed case is the name of the backend in the cromwell config.  If you just change the name from "Local" to "MyLocal", it will fail.

For example,

this works
```
default = "Local"
  providers
  {
    Local
```

And this fails
```
default = "MyLocal"
  providers
  {
    MyLocal
```

Command to reproduce error

export _JAVA_OPTIONS="--add-opens=java.base/sun.security.util=ALL-UNNAMED"

java -Dconfig.file=cromwell_docker.conf \
-Dbackend.providers.Local.config.dockerRoot=$(pwd)/cromwell-executions \
-Dbackend.providers.Local.config.root=$(pwd)/cromwell-executions \
-jar ~/cromwell/cromwell-84.jar run fq_count.wdl -i fq_count.json

Error:
java.lang.IllegalArgumentException: Could not build the path "https://portal.nersc.gov/cfs/m342/jaws/test_data/sample.fastq". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: MacOSXFileSystem. Failures: 

Required files
[test-files.zip](https://github.com/broadinstitute/cromwell/files/10387814/test-files.zip)

**Comment by jgainerdewar** [comment]
Cromwell supports a number of filesystems and they need to be individually enabled for the engine and each backend. It looks like the `http` filesystem is enabled for your `Local` backend but not `MyLocal`.

**Comment by jfroula** [comment]
So I moved the http{} stanza to the correct place in the cromwell_cori.conf file.

And I changed Local to Mylocal in lines 22 & 26.

I used this command 
```
export _JAVA_OPTIONS="--add-opens=java.base/sun.security.util=ALL-UNNAMED"

java -Dconfig.file=cromwell_docker.conf
-Dbackend.providers.MyLocal.config.dockerRoot=$(pwd)/cromwell-executions
-Dbackend.providers.MyLocal.config.root=$(pwd)/cromwell-executions
-jar ~/cromwell/cromwell-84.jar run fq_count.wdl -i fq_count.json
```
(Note the change from Local to Mylocal)

This command should fail with the "Could not build the path" error.

Would you please try again with this new cromwell_docker.conf file and new command?

[test-files.zip](https://github.com/broadinstitute/cromwell/files/10397528/test-files.zip)

**Comment by jfroula** [comment]
There is something magical about the keyword "Local".  This is my point.

**Comment by jfroula** [comment]
I'm pretty sure this is a bug in cromwell's ability to resolve URLs from input.json files.
