### ISSUE TITLE
Failed job w/o logs

### ISSUE THREAD

**Issue by francois-a** [broadinstitute/cromwell#698]

**Comment by geoffjentry** [comment]
Hi @francois-a - could you provide more detail, how to reproduce, what you were doing, etc?

**Comment by francois-a** [comment]
The following WDL runs to a certain point and then fails (when running the STAR aligner) without writing errors to stdout/stderr (which it does when running out of resources when run locally)

[samtofastq_star_rsem.txt](https://github.com/broadinstitute/cromwell/files/215739/samtofastq_star_rsem.txt)

**Comment by kshakir** [comment]
Note to those trying to reproduce-- the wdl is reported to run fine on the combination of:

1. Local
2. Small inputs

It should reproducibly fail on the combination of:

1. Current JES / Firecloud (cromwell 0.18)
2. Normal (aka large) input files

The JES logs showed that it started localizing, and then four minutes later began delocalizing files. The STAR stderr printed that the program was starting, but there was no other error other message in the stderr nor jes log. AFAIK, there did not seem to be any other current indication via the Firecloud interface as to why the job was exiting prematurely.

**Comment by cjllanwarne** [comment]
This is handled completely differently now, and we haven't heard about this problem recently, so I'm closing as fixed.
