### ISSUE TITLE
wdl glob / Array[File] only seems to grab 1000 elements

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#699]
I tried running a these two glob output commands
`    Array[File] gvcf_list = glob("split_gvcfs/*.gz")`
`    Array[File] gvcf_index_list = glob("split_gvcfs/*.tbi")`
Which should have had 3457 elements in each array.  When I go to the output directory bucket of the above task, I see each glob directory does indeed have 3457 elements but when I go to the symbols table in the Cromwell db the arrays only have 1000 elements.  This causes tasks further down in the workflow to fail because I am expecting an array of 3457 elements but I am only getting 1000.

**Comment by mcovarr** [comment]
The following WDL reproduces the problem with the JES backend, though the magic number is consistently 1899 files.  Local backend does not have this problem.  

```
task make_files {
  command <<<
    mkdir files; for i in {1..5000}; do echo "foo" > files/$i.txt; done
  >>>
  output {
    Array[File] files = glob("files/*.txt")
  }
  runtime {
    docker: "ubuntu:latest"
  }
}

workflow piles_of_files {
  call make_files
}
```

**Comment by mcovarr** [comment]
Nope I take that back, we are getting 1000 files, they're just not ordered the way I first thought they were.

**Comment by mcovarr** [comment]
@scottfrazer and @kshakir
