### ISSUE TITLE
"cwl" & "common-workflow-lanuage" in GitHub keywords

### ISSUE THREAD

**Issue by mr-c** [broadinstitute/cromwell#7016]
Hey-o,

To help guide new people in a good direction, can `cwl` and `common-workflow-language` be removed from the [keywords list for this repo](https://github.com/broadinstitute/cromwell)?

![image](https://user-images.githubusercontent.com/1330696/220963754-a6ad10cd-6a53-4452-8aa0-71239d4dd7d4.png)

Unless the policy to deprecate and remove the CWL support has been reversed...

**Comment by aednichols** [comment]
Good catch, fixed 👍
