### ISSUE TITLE
A pre-empted task took a long time to actually end

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#711]
I ran the single-sample pipeline on the small (20K bam) and one of the BQSR jobs (BaseRecalibrator.8.retry-1) took much longer than it should (8 hours instead of a few minutes) it was then preempted and replaced by retry-1 which, indeed concluded after a few minutes. 

it would be good to know if there are many such instances and if we are being billed for them...

[longBQSR.metadata.txt](https://github.com/broadinstitute/cromwell/files/221526/longBQSR.metadata.txt)

**Comment by cjllanwarne** [comment]
I believe this will be fixed in C21+. Feel free to re-open if it resurfaces.
