### ISSUE TITLE
Large workflow causes metadata endpoint to time out

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#719]
The same workflow that caused #695 and #699 also has a problem when trying to grab the metadata for the workflow.  We always get a `The server was not able to produce a timely response to your request.` response.  This makes it so we cannot see a timing diagram either.

Example workflow in gotc-dev: 1b3418a6-724b-4e1a-81c5-acdd1bdfe0ee

**Comment by ruchim** [comment]
Hey @jsotobroad  -- if you think you need this fix for sometime in the near future then we should label it GreenFriends so it gets the deserved attention. Otherwise, this sounds like a bug--I would consider it a regression as I believe we expect all WF's to produce metadata.

**Comment by jsotobroad** [comment]
Will add the label, I think this problem stems from the same thing that is causing 695 but either way we would like to have this in the near future.  Thanks!

**Comment by geoffjentry** [comment]
@kshakir - now that you've been looking at #695 do you think this is all interrelated? If so I should take this off the ready pile.

**Comment by kshakir** [comment]
This is not the same as #695. #719 is, our workflow metadata response to a massive wdl is a massively slow build of metadata. This metadata includes lots of trips to the database, lots of conversion from DB objects to JSON-friendly objects, and possibly retrieves values that aren't needed depending on the consumer.

In addition to investigating what should be returned by the existing metadata endpoint, we may want two additional metadata builders:

1. For showing timing diagrams -- doesn't need things such as the output paths, etc.
2. For running the existing 3-types of final calls -- doesn't need all the existing metadata, and definitely doesn't need to be created 3x, once per type of final call

**Comment by cjllanwarne** [comment]
@kcibul and I had a discussion about how big the metadata response should be at some point earlier in the year. He convinced me that "all in one" is a good idea, but with the idea that you may want query-style parameters which allow you to request subsets of the total metadata (e.g. `http://cromwell:8080/api/.../metadata?outputs=false&timing=true`)

**Comment by cjllanwarne** [comment]
Also interesting would be finding out at what point the timing diagrams contain so many data points that the browser cannot render it any more!

**Comment by geoffjentry** [comment]
Yeah I was coming here to comment that the all in one (minus the querying) has now seen the fatal flaw. Regardless of the UI (such as it is) I think we have plenty of evidence now that our DB queries need to be targeted to what's actually being requested
