### ISSUE TITLE
OutOfMemoryError in run mode when log output exceeds 2GB

### ISSUE THREAD

**Issue by ehclark** [broadinstitute/cromwell#7217]
The combination of a separate metadata database and -DLOG_LEVEL=DEBUG is causing an out of memory error when the log output exceeds the max size of a byte array.

We are executing Cromwell locally in run mode with a long running workflow (about 24 hrs) that includes several scatter-gather blocks.  We switched to a separate metadata database to address the Java heap problem that occurs with the in-memory database.  We enabled debug logging to try and troubleshoot an unrelated problem.  Most of the log output at the increased level is appears to be from HSQL.

After running for about 8 hrs, the following error appears in the output and Cromwell hangs:
```
Exception in thread "Exec Stream Pumper" java.lang.OutOfMemoryError: Required array length 2147483639 + 39 is too large
	at java.base/jdk.internal.util.ArraysSupport.hugeLength(ArraysSupport.java:649)
	at java.base/jdk.internal.util.ArraysSupport.newLength(ArraysSupport.java:642)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:132)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:92)
	at org.apache.commons.io.output.TeeOutputStream.write(TeeOutputStream.java:68)
	at org.apache.commons.exec.StreamPumper.run(StreamPumper.java:108)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

We are running Cromwell using Dockstore as a wrapper using the following command:
```
dockstore workflow launch --local-entry BiobankScrubWorkflow.wdl --json inputs.json > dockstore.log 2>&1 &
```

At the time the OOME occurs, the size of the dockstore.log file is approx 2147485425 bytes.

Based on the "Saving copy of Cromwell stdout to..." messages at the end of a successful Cromwell run, it would appear that Cromwell is internally buffering the stdout and stderr streams to save at the end of the run.  So when the size of the stdout or stderr exceeds the Java buffer max size, the OOME occurs.

The Cromwell configuration we are using is the default with the exception of uncommenting the `database -> metadata` block and updating the docker run command to mount the local GCloud SDK configuration into the container to enable access to GCP resources.

**Comment by aednichols** [comment]
Per prior user feedback,
> [HSQLDB has got to be the worst performing embedded database designed in the history of mankind.](https://github.com/broadinstitute/cromwell/issues/5271#issuecomment-624458757)

and we do not recommend it, like, at all, unless your use case is tiny.

Likewise, `run` mode is
> [Appropriate for prototyping or demo use on a user's local machine. Features are limited and the web API is not supported.](https://cromwell.readthedocs.io/en/stable/Modes/)

For real workflows – certainly anything running more than 1 hour – the path is `server` mode with a daemon-type relational DB like PostgreSQL or MySQL.
