### ISSUE TITLE
v86 GCPBATCH errors when have multiple zones in the config

### ISSUE THREAD

**Issue by garlandcrow** [broadinstitute/cromwell#7232]
Thought I would check out the new GCPBATCH support in the latest cromwell. Used the [example config](https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/GCPBATCH.conf) for the newly supported GCPBATCH with my projects settings added and it errored because of multiple zones were configured:

```
default-runtime-attributes {
    ...
    zones: ["us-central1-a", "us-central1-b"]
}
```
I changed it to just `["us-central1-a"]` and worked fine and ran until completion so I guess it is how the parser is combining these zones into whatever underlying batch command needs to be executed. (I also tried the value "us-central1-a us-central1-b" as a string instead of an array cause I thought I read somewhere that was supported, but that didn't work either)

Here is the error thrown by cromwell: 

![Screenshot 2023-10-04 at 13 11 01](https://github.com/broadinstitute/cromwell/assets/40811287/9c9cc8d8-8e08-44a3-826d-a0300fc95278)

**Comment by garlandcrow** [comment]
It seems this [line](https://github.com/broadinstitute/cromwell/blob/d967bcdba2cf8d321c34837eceba2b48a62aa42b/supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/util/BatchUtilityConversions.scala#L14)

Is building the zones string like "zones/us-central1-a,uscentral1-b", where the spec according to google [https://cloud.google.com/php/docs/reference/cloud-batch/latest/V1.AllocationPolicy.LocationPolicy](https://cloud.google.com/php/docs/reference/cloud-batch/latest/V1.AllocationPolicy.LocationPolicy) is to have "zones/" before each one.

**Comment by dspeck1** [comment]
Thanks for providing code recommendation!  Submitted PR to update.

**Comment by aednichols** [comment]
PR merged, closing.
