### ISSUE TITLE
java.lang.ClassNotFoundException: languages.cwl.CwlV1_0LanguageFactory error while running Cromwell 85 and 86 jar in OnPrem system

### ISSUE THREAD

**Issue by priyankasebastian** [broadinstitute/cromwell#7247]
I am getting java.lang.ClassNotFoundException: languages.cwl.CwlV1_0LanguageFactory while using Cromwell 85 and 86 jar. 
[cromwell-85.log](https://github.com/broadinstitute/cromwell/files/13271608/cromwell-85.log)
PFA for cromwell.log
Cromwell jar build completes without any errors. While using the jar to start Cromwell on Premise system we get the CWL error (command: nohup java -jar -Dconfig.file=/fastdata/02/genomics/cromwell/reference-84.conf /fastdata/02/genomics/cromwell/cromwell-85-f34251c-SNAP-original.jar server 2>&1 >> cromwell.log &).
https://github.com/broadinstitute/cromwell/releases  notes for Cromwell 85 says: CWL implementation removed :This release removes the cwl top-level artifact. Some nonfunctional references may remain and will be addressed over time. Looks like some references is causing the issue?

**Comment by aednichols** [comment]
Your config most likely needs an update to remove usage of the `languages.cwl.CwlV1_0LanguageFactory` class referenced in the exception.
