### ISSUE TITLE
TMPDIR not being created

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#731]
I run a short bash pipeline like this : for CHROM in `cut -f1 $IN_FILE |grep -Pv '^@'| sort|uniq`; do

But I get this error : sort: cannot create temporary file in ‘/cromwell_root/tmp’: No such file or directory

when running in firecloud.

should I "mkdir -pv /cromwell_root/tmp" first?

I see "export TMPDIR=/cromwell_root/tmp" in the exec.sh on the 3rd line....

I went ahead and issued before the pipeline starts the command "mkdir -pv $TMPDIR" and made the error go away!

Is it normal/expected to need to create TMPDIR ?

**Comment by seandavi** [comment]
I am finding the same issue (using 0.19).  Paul Grosu suggested adding the `mkdir` above line 323:

https://github.com/broadinstitute/cromwell/blob/b2efbba4e3da41834a5f9e25c0c93b84f435e6af/supportedBackends/jes/src/main/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActor.scala#L323

That may not be the best approach, but it appears it would work.  Is this viable?  If so, I can make a pull request.

**Comment by geoffjentry** [comment]
Hi @seandavi - That does seem like it should work. Thinking back in my past I've definitely encountered tools which expect TMPDIR to exist and aren't smart enough to create it themselves. Also in JES there shouldn't be any issues with permissions, etc.

We'd certainly welcome a PR if you're game for it, either (or both) against `0.19_hotfix` or `develop`. On that note, I should point out that a new release (currently `develop`) is imminent and for all but one use case (call caching) we beliee it to be more robust/stable that 0.19. I'd personally recommend people who don't need call caching work with the new system, but I understand that some people aren't comfortable working with code which isn't yet released.

**Comment by seandavi** [comment]
I'll start working with development, then. We don't have anything in
"production" that we cannot break. Thanks for the direction.

**Comment by geoffjentry** [comment]
Cool. Thanks @seandavi - definitely speak up if you have any questions or concerns

**Comment by cjllanwarne** [comment]
Closing this as "believed fixed in 21+". @seandavi , please let us know if it reappears in your testing.
