### ISSUE TITLE
[BUG] regex restriction on GCP Batch custom label values

### ISSUE THREAD

**Issue by bchen4** [broadinstitute/cromwell#7351]
I was trying to label all GCP batch resources using `-o` in the CLI. (according to [this doc](https://github.com/broadinstitute/cromwell/blob/master/docs/wf_options/Google.md) and [this doc](https://github.com/broadinstitute/cromwell/blob/develop/docs/backends/GCPBatch.md) )
My content of options.json is 
```
{"google_labels":{"workflow-run-execution-id":"97fed6c4-6442-4efe-9e73-7b3592a33480"}} 
```
and my command is `java -Dconfig.file=config -jar /app/cromwell.jar run wf.wdl -i input.json -o options.json`

The error I am getting:
<img width="1409" alt="Screen Shot 2024-01-04 at 9 58 25 AM" src="https://github.com/broadinstitute/cromwell/assets/1992953/e559bccf-dd96-4dea-a48a-6649e448a26f">

After adding string prefix to my own uuid as label value, the error was gone and my workflow ran smoothly. However, I do need to pass in the uuid so downstream analysis pipeline can still work. 

Related code reporting error is [here](https://github.com/broadinstitute/cromwell/blob/dbd8a2aca7253cecd852b5b44ff199e35cdb81cd/supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/models/GcpLabel.scala#L65)  and error is produce [here](https://github.com/broadinstitute/cromwell/blob/dbd8a2aca7253cecd852b5b44ff199e35cdb81cd/supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/models/GcpLabel.scala#L77) and [this is the regex definition](https://github.com/broadinstitute/cromwell/blob/dbd8a2aca7253cecd852b5b44ff199e35cdb81cd/supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/models/GcpLabel.scala#L21)

I am wondering can the [code](https://github.com/broadinstitute/cromwell/blob/dbd8a2aca7253cecd852b5b44ff199e35cdb81cd/supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/models/GcpLabel.scala#L77) be updated to only check the key of a label so it aligns with GCP which does not have this restriction on label values? Or use another regex `"[a-z0-9]([-a-z0-9]*[a-z0-9])?"` for label value check?

Cromwell version: I built develop container, and the tag is `87-ee2b10f-SNAP`.
Backend: GCP Batch.

Please let me know if this could be something you guys would accept before I put in PR. Thanks.

**Comment by dspeck1** [comment]
Looks fine to PR.  Google Cloud Batch accepts the label starting with a number.  Had you run this on PAPv2 previously?

**Comment by bchen4** [comment]
> Looks fine to PR. Google Cloud Batch accepts the label starting with a number. Had you run this on PAPv2 previously?

Nope, just Batch. I will submit something soon.

**Comment by bchen4** [comment]
@dspeck1  here is the PR https://github.com/broadinstitute/cromwell/pull/7353

**Comment by AlexITC** [comment]
Given that #7355 was merged, is this issue resolved?

**Comment by aednichols** [comment]
PR merged, closing.
