### ISSUE TITLE
Do not ever want to use an "e" machine on GCP

### ISSUE THREAD

**Issue by GregoryDougherty** [broadinstitute/cromwell#7474]
We are running a wld pipeline on GCP.  Requested 16 CPSs.  we have
        runtime {
          cpuPlatform: "Intel Cascade Lake"
        }
set in the .conf file

Nevertheless, the task was given an e2-standard-16 machine, and took 9 hours to turn a bam into a cram, and another hour to upload the 51 gb ram file

I ran the code again, only change was I used an n2-standard-16
The entire task, including the upload, finished in less than 30 minutes

How do we make it so we never, ever, get an "e" machine?  I downloaded the cromwell code and looked through it, trying to figure out where it is you pick the machine type on GCP, but never found anything that looked like it would pick an e machine.  What am I missing?

The cromwell that assigned the e2-standard-16 was cromwell-87.jar, if that matters

Thank you

**Comment by dspeck1** [comment]
This is with the GCP Batch backend correct?  Machine Type is a parameter in Batch, but not a parameter in Cromwell.  If a machine type is not defined Batch selects the machine type based on the CPU and Memory request.  Setting `cpuPlatform` is the way to not get an e series machine.   Did you get an e series machine with "Intel Cascade Lake" in the configuration?

**Comment by GregoryDougherty** [comment]
Assuming that putting that in the runtime {cpuPlatform: "Intel Cascade Lake"} setting in the Cromwell conf file counts as "in the configuration", then yes.

If we have to hand edit every single one of our WDL task files to put that in a runtime block, not I haven't tried that

**Comment by GregoryDougherty** [comment]
$ gustil cat gs://bucket/path/to/run.stdout | grep standard | grep machine | sort | uniq -c
   1601       machine_type: "e2-standard-2"

No happiness there

**Comment by dspeck1** [comment]
Thanks.  Setting `cpuPlatform`  in the runtime attributes is the only way to avoid scheduling to an e series machines through Cromwell.  GCP Batch is limited to setting cpuPlatform or instance type.  There is no preferred machine family type setting in GCP Batch.  With that said the e series machine should not be that slow.  Performance is supposed to be comparable to N1.   If it repeatable open a support case with GCP.

**Comment by GregoryDougherty** [comment]
"The E2 machine series also contains shared-core machine types that use context- switching to time-share a physical core between vCPUs for multitasking"

Essentially, they are garbage machines that give you 1/2 the CPUs you ask for, and have horrid I/O.  IMO, no one should ever be given one, unless they've explicitly asked for it.  Especially in a bioinformatics environment, where you're going to be reading and writing large files on a regular basis.

Where in the code is the E2 default set?  That's the part I was unable to figure out.  If I could have that, I can fix it, put in a PR, and make our own version that doesn't require us to rewrite all our task files.

Thank you

**Comment by aednichols** [comment]
From the GCP docs, it seemed like Cascade Lake wasn't among the CPU platforms used for E2s.

> Intel Skylake, Broadwell, and Haswell, AMD EPYC Rome and EPYC Milan

https://cloud.google.com/compute/docs/machine-resource#machine_type_comparison

**Comment by aednichols** [comment]
@GregoryDougherty can you try a different CPU platform that similarly excludes E2 based on the matrix linked above?

**Comment by GregoryDougherty** [comment]
I did, no change.

I put "Intel Cascade Lake" in cpuPlatform in the .wdl code's runtime block.  So it gave me an e2-highcpu-16 with an AMD EPYC chip.
Which was moderately faster, but still not nearly as good as an n2-standard-16

So, my question remains: where in the code is teh machine-type actually chosen for GCP Batch?

There has to be something that is saying "yes, use e2". Where is that?  What is the code that makes e2 a possible option, rather than just starting at n2 and going up from there?

because our other choice is to always demand at least 40 CPUs, since that gets us out of e territory.  But that's a really sub-optimal solution

**Comment by mcovarr** [comment]
Fixes for this will be available in the next Cromwell release, no ETA yet. If you need the fixes immediately and are comfortable building from the `develop` branch, that is also an option.

**Comment by GregoryDougherty** [comment]
Thank you

**Comment by GregoryDougherty** [comment]
> Fixes for this will be available in the next Cromwell release, no ETA yet. If you need the fixes immediately and are comfortable building from the `develop` branch, that is also an option.

I built cromwell 88.  Then I ran two large preemptible runs, one with cromwell 87 and the other with 88.

The e2 with standard machines ran faster, and was pre-empted less, than the n1 with custom machines.
11% faster, and 424 preemptions vs 276.

Many of the 424 were preemptions that happened really early in the run process.  So it may be that I just had bad luck with someone kicking off a large non-spot run while my 88 run was going but teh 87 was finished.

But I've been advised that custom machine types are much more likely to be preempted than standard ones.

Would it be possible for you to default to n1 or n2 standard machines, rather than custom ones?

Thank you

**Comment by GregoryDougherty** [comment]
> Fixes for this will be available in the next Cromwell release, no ETA yet. If you need the fixes immediately and are comfortable building from the `develop` branch, that is also an option.

BTW, I really miss the logging you eliminated.  With 87 I see the machine type allocated, with 88 I don't.

Is there some command line option for turning all the logging back on?

Thank you

**Comment by aednichols** [comment]
The problem described in this issue's title should now be resolved. @GregoryDougherty would you be OK closing it and opening new issue(s) with your requested changes?

**Comment by aednichols** [comment]
No, we don't use that feature (Github foisted it on us).

**Comment by GregoryDougherty** [comment]
New version doesn't use e2
