### ISSUE TITLE
Retry Support for JES PBE (Preemptible VMs)

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#749]

**Comment by mcovarr** [comment]
If this ticket is about what I think it is (picking up jobs that were running when Cromwell is restarted), I think this ticket should be "Recover Support".  I believe "retry" describes Cromwell's resilience to transient failures with Google Cloud services.

**Comment by mcovarr** [comment]
Oh nm, it looks like #751 is the Recover ticket.  Is this the preemptibility ticket?

**Comment by kcibul** [comment]
Yes -- exactly.  Our "retry" support for JES PBE is just the preemptibility stuff
