### ISSUE TITLE
Make restarting old workflows configurable

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#755]
When Cromwell comes online it detects if there are any unfinished workflows in the system and will pick those back up.

**Comment by ruchim** [comment]
@geoffjentry is this meant to be a switch in the conf file?

**Comment by geoffjentry** [comment]
@ruchim it doesn't have to be but that'd make the most sense to me

**Comment by ruchim** [comment]
One last question, @geoffjentry --is this a change just for hotfix branch or develop as well?

**Comment by geoffjentry** [comment]
@ruchim Just for develop unless someone asks for it later
