### ISSUE TITLE
Using relative pathnames in the input json file cause files to be copied when cromwell is executing on local backend

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#764]
json input to wdl script:

```
...
  "case_gatk_acnv_workflow.normal_bam_idx": "/crsp/scratch/recapseg/recapseg_validation_sample_bams_EEW_topoff/SM-74NEG.bam.bai",
  "case_gatk_acnv_workflow.jar_file": "gatk-protected.jar",
...
```

In this case gatk-protected.jar (local to the execution command) will be copied into the cromwell-execution dir, but the bam index will not.

**Comment by LeeTL1220** [comment]
Desired behavior would be symlink for both files.

**Comment by scottfrazer** [comment]
Lee, which version of Cromwell?

**Comment by LeeTL1220** [comment]
That custom jar file I got.  Which I believe is between 0.19.2 and 0.19.3...

**Comment by scottfrazer** [comment]
This appears to be fixed on our 'develop' branch
