### ISSUE TITLE
Can time zone be configurable?

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#771]
For GOTC (and presumably all of our google run stuff) the TZ is set to UTC but they'd prefer it to be in eastern

**Comment by kshakir** [comment]
ToL: While in there, maybe someone can stop using the deprecated / Java 7 `JodaTime`, and switch to Java 8's `java.time`:

via http://www.joda.org/joda-time/ :
> Users are now asked to migrate to java.time (JSR-310).

See also:
- http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html
- http://stackoverflow.com/questions/22470150/how-to-get-a-java-time-object-from-a-java-sql-timestamp-without-a-jdbc-4-2-drive
- http://stackoverflow.com/questions/32001716/java-8-convert-localdate-to-zoneddatetime
- etc.

**Comment by kshakir** [comment]
ToL (continued):

In addition to removing usage of the deprecated `JodaTime`, further reading notes that `java.sql.Timestamp` has similar issues to `java.util.Date`. Neither `j.s.T` nor its base `j.u.D` track the timezone that the instant occurred, for example-- 11:15PM... where? Boston, Google East, Google West, China?

With regards to the database/slick, usage of `Timestamp` should eventually replaced with `java.time.OffsetDateTime`. In the meantime, I assume we should be storing all times with "local" `Timestamp`s, relative to the current time on the cromwell server (DST be damned?).

- http://stackoverflow.com/questions/34608650/scala-slick-3-0-implicit-mapping-between-java8-offsetdatetime-and-timestamp
- http://stackoverflow.com/questions/30234594/whats-the-difference-between-java-8-zoneddatetime-and-offsetdatetime

**Comment by cjllanwarne** [comment]
We are now using `java.time.OffsetDateTime`. Closing as believed-fixed
