### ISSUE TITLE
For caching within JES, call files need to be renamed when copied over

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#781]
While using Jes + call caching enabled, if you call on a task with a new name, then when Jes will copy the outputs from the previously performed task but will not rename the files to the new name.

For example, my WDL has a task two, and in the workflow I "call two as four". 
- When I check within the google bucket for call four, all the files are named as "two-stdout.log", "call two-stderr.log". 
- When I check within the google bucket for call two, there are a group of files named call two and a group of files named call four.

It appears that although the appropriate files for call four are created, they aren't moved into the call four directory in google. So when I run the WF, I get this error: 
 "failure": "Item not found: cloud-cromwell-dev/cromwell-executions/cacheWithinWF/c972cace-b423-4c1c-87e4-01356163757f/call-four/four-stdout.log"

Because although the file four-stdout.log actually exists, it exists under the directory call-two instead of call-four.

**Comment by meganshand** [comment]
I've been running into this a lot recently. My current workaround is to add a dummy variable so it will rerun the task, but sometimes I don't know that a task will have identical inputs until it actually runs, therefore making the whole workflow fail.

**Comment by ruchim** [comment]
@meganshand I've confirmed this bug is resolved in release 0.21! I'm closing this issue for that reason.
