### ISSUE TITLE
Implement Metadata REST API against Metadata Service API

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#787]

**Comment by cjllanwarne** [comment]
Depends on #782, #783

**Comment by Horneth** [comment]
Is this expected to also make sense of the response and format it, or is it flat out raw k-> v json ?

**Comment by geoffjentry** [comment]
@Horneth There's a bit of making sense of the response, the doc that @cjllanwarne put together shows the inference model, it's pretty minor though.
