### ISSUE TITLE
Data Migration from existing metadata schema into Metadata Service schema

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#789]
depends on #788 

This is really important for our users so they don't lose all their metadata!

**Comment by mcovarr** [comment]
Depends on #785 (which it is currently prioritized ahead of in Ready for Development), #788 (which is currently in development), and #668 (in review)

**Comment by mcovarr** [comment]
This ticket really can't be taken until the dust completely settles on metadata, which is still a ways off.

**Comment by Horneth** [comment]
@kcibul A few questions about this:
- Should it support in-place DB migration, or DB A to DB B, or both ?
- Is it a separate program that runs independently ? If yes does it still live in the Cromwell repo ? Or a new flag in cromwell (like server, run, migration), ? Is there any "automagic" detection that my DB needs an update when I run cromwell 0.20 on a pre-0.20 DB ?

**Comment by kcibul** [comment]
It should be in-place (e.g. the source and destination tables are in the same database).  

It would be nice to be automagic (e.g. liquibase), but just having a script in the repository to do the upgrade would be fine as well.  It's really just for existing production customers who need to bridge the gap (GOTC/FC)

**Comment by ruchim** [comment]
Working with Henry tomorrow to get these migration changes tested.

**Comment by geoffjentry** [comment]
It'd be fantastic if this could also handle #1336. If not, could you let me know when this is done and I'll do it.
