### ISSUE TITLE
Avoid ConfigFactory.load all over the place

### ISSUE THREAD

**Issue by gauravs90** [broadinstitute/cromwell#796]
One possible solution: We should probably create a trait which loads all the configuration (once per application), and let classes mix it in to avoid doing ConfigFactory.load() at multiple places

**Comment by geoffjentry** [comment]
Implementer - please check out  https://www.trivento.io/creating-settingsactor-configuration-properties-using-akka-extensions/

**Comment by geoffjentry** [comment]
Actually the link I posted (also it's one of the key examples in the Akka docs) might not be so useful as it looks like a lot of the places we're using ConfigFactory.load don't have access to the main actor system

**Comment by Horneth** [comment]
`ConfigFactory.load()` [caches](http://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#load--) the config on the first call and returns the same singleton config until someone calls [invalidateCaches](http://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#invalidateCaches--)

**Comment by mcovarr** [comment]
Yeah that's what I thought.  @kcibul can we close this?

**Comment by geoffjentry** [comment]
I read this as complaining about having all of the separate calls + the logic to dig into the config everywhere, not a complaint about physically loading the config.

That said, having looked at this w/ that lens a few times I never saw a way that'd work everywhere which would be better than doing the above

**Comment by kcibul** [comment]
Works for me @mcovarr -- closing
