### ISSUE TITLE
Cromwell Status sometimes doesn't update correctly

### ISSUE THREAD

**Issue by jrose77** [broadinstitute/cromwell#800]
We've been seeing some instances where the JES Run fails or succeeds, but cromwell either stays stuck in "Starting" or updates to an incorrect status (i.e. "Failed" when the JES Run evidently succeeded). Run into 3 or 4 different iterations of it so far.

**Comment by jrose77** [comment]
To get more specific on this one (as Jose has informed me that the issue of Cromwell status updating is really a collection of different things) what it looks like here is we had a recent slew of connection timeouts when Cromwell tried to talk to the DB, on Saturday morning it appears. Perhaps we need to up the wait time from 5000ms?

**Comment by jrose77** [comment]
Almost certainly the same as issue 737...

**Comment by geoffjentry** [comment]
@kcibul this is likely a very nontrivial fix in 0.19 - can we discuss importance and if it should be queued up for work?

**Comment by kcibul** [comment]
ok, lets defer this one till after 0.20 (it's a robustness problem, not a fire)

**Comment by geoffjentry** [comment]
This is a thing which theoretically shouldn't even be possible in 0.20+, another reason I didn't want to tackle the ticket. 

If you're fine on not patching 0.19, I'd like to move to close this ticket.

**Comment by geoffjentry** [comment]
@kcibul I think we should close this ticket. In theory it shouldn't be possible to happen in 0.20+ - if we do see this behavior we can make a new ticket

**Comment by kcibul** [comment]
closing -- we're not fixing this in 0.19 and this area has been significantly reworked in 0.20 and should not be a problem.
