### ISSUE TITLE
Cromwell Metadata essentially empty; Error

### ISSUE THREAD

**Issue by jrose77** [broadinstitute/cromwell#801]
For Workflow ID: 5541d851-10bb-455d-a6bc-051e85574b74

We're getting nothing back when we try to look at timing or metadata, the metadata curl call returns:

{
  "status": "error",
  "message": "None.get"
}

No clue what's going on here, the cromwell logs don't indicate anything unusual for this workflow. Seemingly it ran normally, just some typical preemption messages.

**Comment by jrose77** [comment]
Workflow efa5fffd-4089-436b-9fc2-ac34558967b7 has this issue as well

**Comment by geoffjentry** [comment]
@kcibul IMO this should be closed - this references Ye Olde Worlde and it's not prioritized

**Comment by kcibul** [comment]
agreed -- if this is still a problem in 0.20+ we can reopen
