### ISSUE TITLE
"Read" Workflow Level Engine Functions (Shared Filesystem)

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#802]
Support reading local file from workflow-level expression:

```
workflow w {
  String x = read_string("/foo/bar/public-object.txt")
}
```

**Comment by kcibul** [comment]
Hmm... is this a security flaw?  Should people even be allowed to do this (or is this configurable?)

Current thinking... it might be ok because if you are running a cromwell with a local docker engine you may very well want to do this.  If you are running cromwell with local docker, and allowing someone to run jobs on your server, they could gain access to any file anyway via their jobs. 

Thoughts?

**Comment by Horneth** [comment]
In the scatter PR I needed to create a "Workflow level WDL functions" (or whatever we want to call it) to evaluate the scatter collection expression, and I gave it the default local filesystem, which effectively makes this supported. 
https://github.com/broadinstitute/cromwell/pull/818/files#diff-04167311d295d2ed1ab92a70830d9a8dR19

Should I remove it until we figure out if this is a potential security flaw ?

**Comment by Horneth** [comment]
Also, on this topic, I don't know much about it but Java has a SecurityManager and Security policies which might (?) be able to restrict to which part of the filesystem cromwell would be able to read from ?
