### ISSUE TITLE
Add basic backend validation for Local PBE config

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#811]

**Comment by kcibul** [comment]
@mcovarr -- can you add more detail about what this is?

**Comment by mcovarr** [comment]
Comments apply to both this and #812: 

Currently there is no format checking of any of the content in the `config {...}` sections for either Local or JES PBE.  The respective backend impls assume the keys are present and the values have the expected shapes.

**Comment by cjllanwarne** [comment]
We currently do have basic backend validation. Closing this on the expectation that we can always have a more specific new ticket if necessary.
