### ISSUE TITLE
Create GCS filesystem(s) in JES initialization actor

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#813]
Create these filesystems in the initialization actor so they might be shared with the other JES actors in the workflow.

**Comment by mcovarr** [comment]
This is likely a specific case of "perform expensive creation of shareable resources only once in the initialization actor and figure out how to share them with the other actors collaborating in the workflow execution".

**Comment by kcibul** [comment]
@mcovarr -- can you describe what we can't do now, that will be possible in the future?  Or is this just an optimization/efficiency item?

**Comment by mcovarr** [comment]
This is an optimization.  Currently we create one filesystem per call when really we only need one per workflow.
