### ISSUE TITLE
Implement workflow logging

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#814]

**Comment by mcovarr** [comment]
Is this 0.20-worthy?  It seems that workflow logs are kind of a big deal and currently we aren't even trying to support them in the New Worlde.

**Comment by geoffjentry** [comment]
@mcovarr I can't imagine this being useful to GOTC w/o workflow logs

**Comment by cjllanwarne** [comment]
Is this ticket related to these workflow options?
```
{
    "workflow_log_dir": "gs://cloud-cromwell-dev/centaur-tests/direct_wf_logs"
    "call_logs_dir": "gs://cloud-cromwell-dev/centaur-tests/direct_call_logs"
    "outputs_path": "gs://cloud-cromwell-dev/centaur-tests/direct_outputs"
} 
```
