### ISSUE TITLE
FileSystems available to the Engine for expression evaluation should be configurable

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#821]
Currently, the file systems available to the engine for functions like read_* are statically defined.  GCS, Local, etc.

This issue is to make that driven by the config file.  The reason this is important is because if you are running a cromwell server and can not disable the "Local Shared Filesystem" from the engine... someone could write a WDL that does a read_ on any file that the cromwell server has access to (e.g. read_lines("./cromwell.conf")... which is bad

**Comment by cjllanwarne** [comment]
FileSystems (and their config) are now backend specific and the local backend can be disabled. I think this one can be closed.
