### ISSUE TITLE
empty glob array when it should contain one item

### ISSUE THREAD

**Issue by dshiga** [broadinstitute/cromwell#828]
The following workflow should produce an output array containing a single string. Instead it produces an empty array. This problem occurs when using the JES backend but not the local backend.

```
task x {
    command {
        echo hello > hello
    }
    output {
        Array[String] a = glob("hello")
    }
    runtime {
        docker: "ubuntu:latest"
    }
}
workflow w {
    call x
}
```

**Comment by scottfrazer** [comment]
This is also a confirmed bug in the `develop` branch

**Comment by kcibul** [comment]
this now works properly in the JES backend
