### ISSUE TITLE
Call caching hits cause Cromwell to lock up (for Joint Genotyping workflow)

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#832]
If you run the workflow described in #820 and then run it a second time which will call cache from the first workflow run, Cromwell will become unresponsive for an unknown amount of time (I usually kill Cromwell after a couple of minutes).  If the first workflow succeeded completely, this second workflow will try to grab the results from the cache for 95 jobs, each with 2 arrays of outputs with 901 elements in each array.  Cromwell becomes unreachable by the swagger page or any APIs.

**Comment by cjllanwarne** [comment]
Verified as working now. However @jsotobroad - your example matrix rotator will need to use `Array[Array[File]]` not `Array[Array[String]]` (on both input and output), otherwise it will never call cache
