### ISSUE TITLE
Runtime attributes not populated in metadata for scattered tasks

### ISSUE THREAD

**Issue by bradtaylor** [broadinstitute/cromwell#835]
For a task that is not part of a scatter block, the /metadata endpoint returns information about the runtime attributes. For example:
```
"runtimeAttributes": {
        "preemptible": "0",
        "failOnStderr": "false",
        "bootDiskSizeGb": "10",
        "disks": "local-disk 400 HDD",
        "continueOnReturnCode": "0",
        "docker": "myorganization/myimage",
        "cpu": "1",
        "zones": "us-central1-b us-central1-c",
        "memory": "7 GB"
      },
```

However, for task shards in a scatter block, this runtimeAttributes object is empty.

I can provide example metadata URLs upon request.

**Comment by cjllanwarne** [comment]
To Cromwell team developer: This ticket should read "Confirm that this is fixed in 21+"

**Comment by cjllanwarne** [comment]
This appears to be fixed in v22
