### ISSUE TITLE
Call caching unbearably slow

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#836]
When you launch a wf for the first time w/ caching on, it can take forever for the cromwell final stuff.

**Comment by jsotobroad** [comment]
The workflow that causes this is the one from #820 .  Basically for each task everything happens quickly as expected until after the equivalent of ``` JES Run [97832d03:SplitGvcfTouch:86]: Status change from Running to Success``` gets printed into the logs.  The time between the JES Run succeeded and the task being persisted to ```Done``` can range anywhere from 8 minutes to over an hour.  This wait is not seen if call caching is turned off in the Cromwell conf.

**Comment by Horneth** [comment]
@jsotobroad I'm pretty sure you've said it at standup, but how many inputs / outputs does this task have typically when this takes so long ?

**Comment by jsotobroad** [comment]
The task has a string and two files as input and two arrays of 901 elements as output.  The workflow runs this task 95 times in the scatter.
