### ISSUE TITLE
nested workflows

### ISSUE THREAD

**Issue by skazakoff** [broadinstitute/cromwell#839]
The spec allows for a workflow to be called from within another workflow. This feature would be tremendously beneficial for when we would like to run a workflow on more than a single sample, but still retain the ability to run a single sample through a single sample workflow. The real benefit would be post-workflow tasks that could be imported to further interrogate the array of single sample workflow outputs. I understand something similar could be achieved using a scatter block. Unfortunately, nested scatter blocks are not functional yet (see [#838](https://github.com/broadinstitute/cromwell/issues/838)). Additionally, a solution that integrates modular workflow definitions would be cleaner, more user friendly, maintainable etc.

```
call namespace.workflow {
  input: foo=bar
}
```

**Comment by cjllanwarne** [comment]
This is being worked on for Q4 2016. Please watch #1532 for progress
