### ISSUE TITLE
What the f1, f2, f3?

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#854]
These files now get left behind on test runs.

**Comment by geoffjentry** [comment]
I thought they always were left behind? I remember complaining about it previously and some folks said they thought that was a feature, not a bug.

**Comment by mcovarr** [comment]
Detritus as a Service

**Comment by geoffjentry** [comment]
@mcovarr You've been on fire lately

**Comment by cjllanwarne** [comment]
+1
