### ISSUE TITLE
Switch JES to use ephemeral pipelines

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#856]
From Dion, regarding how we construct a Pipeline for every Run:

Could you convert that into the ephemeral Run version?   RunPipelineRequest.ephemeral_pipeline instead of pipeline_id. Will save you one RPC call too.

**Comment by mcovarr** [comment]
should there be a hotfix version too?

**Comment by ruchim** [comment]
can I close this ticket and we can make a separate one for Hotfix? I'm also unsure of why the "closes #issue" doesn't seem to be working properly for most tickets.

**Comment by geoffjentry** [comment]
This is done
