### ISSUE TITLE
Investigate sbt-native-publisher for docker stuff

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#857]
Note to PO/scrumlords - I'm not asking for this to be prioritized. I just wanted a reminder for myself.

I believe that sbt-native-publisher w/ the docker plugin could automate some of our docker-y cromwell stuff. Figure out if that's true or not, if so do it and/or write a new ticket

**Comment by kcibul** [comment]
sbt-docker is built on top of sbt-native-publisher and is super nice!

**Comment by geoffjentry** [comment]
The person who filed this ticket is a genius
