### ISSUE TITLE
All metadata values are returned as strings

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#866]
With the new metadata service, all values are returned as JSON strings.  However, the WDL spec says that numbers should be returned where appropriate.  For example, in the 3-step WDL we should (and used to have):
```
outputs": {
  "three_step.cgrep.count": 3
}
```
but we currently have
```
outputs": {
  "three_step.cgrep.count": "3"
}
```
This may require changes to how the metadata is stored which currently persists everything as a string.

**Comment by kcibul** [comment]
See https://github.com/broadinstitute/cromwell#get-apiworkflowsversionidoutputscall

**Comment by kcibul** [comment]
In Tech Talk today, we decided that this should be restricted to storing the types for the json primitive types which include number (which includes integer and floats) and boolean and for all else storing the values as strings (e.g. dates, etc).  

The JSON primitive types are defined here: http://json-schema.org/latest/json-schema-core.html#anchor8

**Comment by geoffjentry** [comment]
So now the metadata service has to understand things like JsObjects?

**Comment by kcibul** [comment]
Jeff and I talked -- no that was just some rationalization as to the choice
of storing types for booleans and numbers and converting all else to a
string representation (and storing those as type 'string')

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org
