### ISSUE TITLE
WorkflowActorTest fails intermittently

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#877]
I noticed that WorkflowActorSpec is a bit flakey, specifically "transition to InitializingWorkflowState with correct call assignments given workflow options".  It fails with "WorkflowFailedState was not equal to InitializingWorkflowState".  I think the problem is that the test set the FSM state, fires a message and then checks the new state.  The FSM when it gets that message transitions to the right state (Initializing) and then transitions to the next state (failed) and sometimes the test misses the initializing.

but all that might be because the runtime options aren't actually valid?  (sge backend) but I'm missing the purpose of that specific setting so I don't want to change it.

**Comment by scottfrazer** [comment]
This test changed a lot since this ticket was initially filed.  I cannot reproduce it.
