### ISSUE TITLE
Circular dependencies in services

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#887]
The engine sub-project currently depends on the services sub-project.

But some services still living in `cromwell.services` depend on engine-specific database code: [[1]](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/engine/src/main/scala/cromwell/services/MetadataServiceActor.scala#L51), [[2]](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/engine/src/main/scala/cromwell/services/KeyValueServiceActor.scala#L51-L56). (NOTE: these links are from a snapshot of develop. As the services continue to become more flushed out, one may find additional engine dependencies have been added.)

Our current way of talking to the database is to use the database singleton. The class itself contains utility methods that receive engine specific classes and map them to the database layer: [[3]](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/engine/src/main/scala/cromwell/engine/db/DataAccess.scala#L58-L61), [[4]](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/engine/src/main/scala/cromwell/engine/db/DataAccess.scala#L156-L157), [[5]](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/engine/src/main/scala/cromwell/engine/db/DataAccess.scala#L577-L578), etc.

The goal of this ticket is to not have any classes in the package `cromwell.services` living in the engine sub-project. It's possible this may be achieved by a number of different ways:

- Move the affected classes to `cromwell.engine.services`
- Talk directly to the [lower database layer](https://github.com/broadinstitute/cromwell/blob/0ff86c409d2e5dac4b766fceb89f47ba3c304f99/database/src/main/scala/cromwell/database/SqlDatabase.scala) that doesn't provide engine utility mappings
- Further separate out `core` code from `engine` _(ExecutionIndex, I'm looking at you)_
- etc.

**Comment by mcovarr** [comment]
Has this been resolved with the recent `services` refactoring?

**Comment by geoffjentry** [comment]
@kshakir is this still a thing?

**Comment by kshakir** [comment]
Looks fixed to me.
