### ISSUE TITLE
JES: Files in output expressions not found

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#891]
The following workflow fails:

This workflow fails:
```
task MakeMeAFile {
    command <<<
      echo FILECONTENT > output.txt
      >>>

    runtime {
      docker: "ubuntu:latest"
      memory: "1 GB"
      preemptible: 3
    }

    output {
        String out = read_string("output.txt")
    }
}

task ReadMeAFile {
    File infile

    command <<<
        cat ${infile}
    >>>

    runtime {
      docker: "ubuntu:latest"
      memory: "1 GB"
      preemptible: 3
    }

    output {
        File out = read_string(stdout())
    }
}

workflow FileMakeAndRead {
    call MakeMeAFile
    call ReadMeAFile { input: infile = MakeMeAFile.out }
}
```

Because:
```
"failures": [
  "Could not find suitable filesystem to parse output.txt"
]
```

**Comment by scottfrazer** [comment]
So it seems that this WDL is wrong but I hesitate to correct it without asking you first... the output of `MakeMeAFile` is a `String` but the input to `ReadMeAFile` is a `File`

**Comment by scottfrazer** [comment]
So I'm getting much different behavior than the ticket describes... basically this WDL file is hanging indefinitely.  The first task finishes on both JES and local backends.  The second behaves in very strange ways.  It loops infinitely on JES and has a localization error on local.  I suspect it might be because of the problem with the WDL file itself (see previous comment)

**Comment by scottfrazer** [comment]
Based on conversation with @mcovarr:

* The above WDL, as is, should fail on the second step.
* It hangs in Running for the local backend
* It *eventually* fails in the JES backend but after far too many retries (takes about 5 minutes worth of retries)

**Comment by scottfrazer** [comment]
From looking at the [metadata of running on JES](https://gist.github.com/scottfrazer/c588cc0053f562166a135e2fbe9d7acc), it actually goes through 4 attempts before failing, each attempt appears to have a 10 retry loop that takes about a minute to complete.
