### ISSUE TITLE
Implement healthcheck status API endpoint

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#898]
Being requested by GAWB, see

https://broadinstitute.atlassian.net/browse/GAWB-323

which also suggests a API based on

https://github.com/Cimpress-MCP/healthcheck.spec

**Comment by geoffjentry** [comment]
Could you comment on the granularity?

Is it "cromwell is alive, hooray!" or some more involved breakdown of various subsystems, e.g. "can't talk to JES right now, the DB is being a poop, but SGE is going swimmingly!"?

**Comment by kcibul** [comment]
This is also now being requested by GOTC so rather than staggering workflows to be submitted every N minutes, they could submit as long as cromwell is healthy

GAWB can also use this in their horizontal scaling work

**Comment by geoffjentry** [comment]
Things I've wanted to know recently in my own spelunking:

- How many workflows are in flight
- How many calls are in flight
- Some sense of the shape of the above, e.g. is it tons of little WFs or one big one

**Comment by cjllanwarne** [comment]
I believe this is fixed by @geoffjentry and the `/engine/{version}/stats` endpoint?
