### ISSUE TITLE
Sort Json parameters

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#900]
When automatically generating a json template, please sort the parameters.

(Lee)

**Comment by kcibul** [comment]
This is part of 'wdltool' (see https://github.com/broadinstitute/wdltool)

**Comment by geoffjentry** [comment]
I'm not sure what Lee (what the heck is his github ID?) is asking for is what wdltool provides. OTOH I have no idea what he's asking for at all really.

**Comment by kcibul** [comment]
when you run 'wdltool inputs' the json that is output is fairly randomly sorted, which makes filling it out a pain in the neck.  just sorting those keys on output would be nice

**Comment by cjllanwarne** [comment]
Closing in Cromwell. See instead the wdltool issue https://github.com/broadinstitute/wdltool/issues/14

**Comment by gudeqing** [comment]
Hi，
 I find the output json of  “ java -jar womtool-59.jar inputs” is still not sorted by parameter names, such as:
```
  "rnaseq_pipeline.fusion.CPU": "Int (optional, default = 8)",
  "rnaseq_pipeline.align.alignIntronMax": "Int (optional, default = 500000)",
  "rnaseq_pipeline.fastp.time_minutes": "Int (optional, default = 10080)",
  "rnaseq_pipeline.align.docker": "String (optional, default = \"STAR2.7.8a:latest\")",
```
best wishes
