### ISSUE TITLE
Cromwell thinks task is running although it has completed

### ISSUE THREAD

**Issue by gbggrant** [broadinstitute/cromwell#904]
We have several cromwell jobs that appear to be running, but are done with a task that should have been recognized as complete.

An example is f86ff9ef-ea1c-47f3-a513-8d6311a27c7b - running on gotc prod
https://cromwell.gotc-prod.broadinstitute.org/api/workflows/v1/f86ff9ef-ea1c-47f3-a513-8d6311a27c7b/metadata
The workflow was launched on May 15 and ran normally until
A task - 'ValidateAggregatedSamFile' was preempted.  A retry was then attempted, and that retry is stuck in status 'Running' although the job appeared to have executed correctly:
see expected/normal output in:
https://console.cloud.google.com/storage/browser/broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/f86ff9ef-ea1c-47f3-a513-8d6311a27c7b/call-ValidateAggregatedSamFile/

Looking at the logs on gotc-cromwell-prod201 (/local/cromwell_logs/20160516-cromwell.log).  It looks like the retried job never switched to 'Initializing' (the log says it was changing the jobs status but the database does not reflect that)
i.e. this line:
2016-05-16 20:17:22,463 cromwell-system-akka.actor.default-dispatcher-22 INFO  - JES Run [UUID(f86ff9ef):ValidateAggregatedSamFile:2]: JES Run ID is operations/EPaL3dnLKhiY9KCP1rC04ekBIJ-ikOmeDSoPcHJvZHVjdGlvblF1ZXVl
2016-05-16 20:17:22,484 cromwell-system-akka.actor.default-dispatcher-17 INFO  - JES Run [UUID(f86ff9ef):ValidateAggregatedSamFile:2]: Status change from - to Initializing

But the database says the job is still 'Running'.

**Comment by gbggrant** [comment]
Upon further review it appears that this was caused by a cromwell restart - but I think this is still a bug, so the play on the field stands as called.

**Comment by kcibul** [comment]
Restarts are being completely revamped as part of 0.20+ so let's see if we can reproduce this there
