### ISSUE TITLE
Tests leak threads and memory

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#906]
When using `TestKit`, there is a [note](https://github.com/akka/akka/blob/v2.3.12/akka-testkit/src/main/scala/akka/testkit/TestKit.scala#L705-L706):

> the ActorSystem passed into the constructor needs to be shutdown, otherwise thread pools and memory will be leaked

We have dozens of specs that use an `ActorSystem`, but recently in PBE specs have not been cleaning up after themselves. It's possible that this is the reason we suddenly need 2GB of memory to run tests.

**Comment by kshakir** [comment]
ToL:

It'd probably be best to slim down and refactor the old engine `cromwell.CromwellTestkitSpec` to a `cromwell.core.CromwellTestKitSpec` and `cromwell.engine.WorkflowTestKitSpec`.

Also, the actor system created in the current `CromwellTestkitSpec` uses a custom configuration. As it doesn't fall back to `ConfigFactory.load()`, it doesn't seem to be support modifying [`akka.test.timefactor`](https://github.com/akka/akka/blob/v2.3.12/akka-testkit/src/main/scala/akka/testkit/TestKit.scala#L712-L714) on the sbt command line.

**Comment by geoffjentry** [comment]
@kshakir Do you have a definition of done here? Or is this a "try as good as you can" sort of thing?
