### ISSUE TITLE
Metadata REST API should be backwards compatible

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#936]
Currently the new metadata API is on V2, it should be V1 and be made to have the same format as V1 (ie no V2)

One specific change is that the current implementation (V2) returns a map of workflow id -> metadata.  This should be flattened (no workflow id) because it is a single workflow REST API.

If there are other differences between the current and former REST api metadata, let's quickly techtalk those differences and the PO will decide

**Comment by Horneth** [comment]
I ran a couple workflows, against 0.19 and against develop (considering the workflow id wrapping issue is resolved).

Here are some differences I found, there might be other that those workflow didn't catch.

- The "Collector" of a scatter is present in the metadata in develop, and wasn't in 0.19. Oddly it doesn't contain its output though : 
```
{
  "attempt": 1,
  "executionStatus": "Done",
  "shardIndex": -1
}
```

- `stdout` and `stderr` are missing (**Local only**)

- `runtimeAttributes` is missing 
Completely missing on local.
On JES, only attributes in the WDL show up, those for which the default value was used are missing.

- `executionEvents` is missing (even if there is none, there is an attribute with an empty list in 0.19)

- `cache`  is missing (**Local only**)
e.g
```
"cache": {
   "allowResultReuse": true
}
```
- `inputs` at the call level is missing if there are no inputs (`"inputs" : {}` was present in 0.19)

- `inputs` at the workflow level is missing if there are no inputs (`"inputs" : {}` was present in 0.19)

- `outputs` at the workflow level is missing if there are no inputs (`"outputs" : {}` was present in 0.19)

- Scatter keys are shown in develop's metadata as a normal call:
```
"w.$scatter_0": [
      {
        "attempt": 1,
        "executionStatus": "Done",
        "shardIndex": -1
      }
    ]
```

- `submission` is missing

- In 0.19, all "first level" (non-shards) calls would appear in the metadata right away, with a `NotStarted` status and some basic available information:
```
"example.gatherUltimateAnalysis": [
      {
        "executionStatus": "NotStarted",
        "shardIndex": -1,
        "outputs": {},
        "runtimeAttributes": {},
        "cache": {
          "allowResultReuse": true
        },
        "inputs": {
          "array": "ultimateAnalysis.out"
        },
        "backend": "JES",
        "attempt": 1,
        "executionEvents": []
      }
    ]
```
In develop, a call appears in the metadata only at runtime

- `backendStatus` has been renamed to `jesOperationStatus` (JES status)

**Comment by Horneth** [comment]
@kcibul Is there anything above that we would want to change or should everything be back as it was in 0.19 ?

**Comment by kcibul** [comment]
I think everything should be as it was in 0.19, unless you find that it's
painful and then let's re-evaluate on a case-by-case basis.  Sound good?

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by Horneth** [comment]
👍
