### ISSUE TITLE
Status REST API should be backwards compatible

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#937]
Currently the new status API is on V2, it should be V1 and be made to have the same format as V1 (ie no V2)

If there are other differences between the current and former REST api metadata, let's quickly techtalk those differences and the PO will decide

**Comment by mcovarr** [comment]
We should get this when #855 / #934 is done

**Comment by mcovarr** [comment]
@kcibul it looks like the Swagger YAML on develop currently defaults to "v2" for the version on the status endpoint (a PR to fix that is forthcoming), but in reality version is ignored and a format that I believe is compatible with v1 is returned in all cases.  Does that seem right to you or do you think there's more to do here?
