### ISSUE TITLE
Add stuck workflow monitor to 0.19_hotfix

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#940]
@abaumann said that they're having a serious issue (due to BBQ) with workflows which have become stuck in non-terminal states. Set up some monitor which runs at a configurable period to look through all non-terminal workflows/calls and make sure that things are actually non-terminal, switching to terminal states as appropriate.

This solution is viewed as a relatively painless (vs fixing it For Real) way of solving the problem, but if one sees an easier way of doing it that's even better.

**Comment by kcibul** [comment]
Since 0.20 should truly fix this, we just want a balance of fast/quick to implement that makes the problem better (even if not completely solved) since spending more time on this will delay 0.20 with the full fix.

**Comment by geoffjentry** [comment]
Looking closer at the specific problem @abaumann reported, it appears to just be workflow level mismatches and aborting - I'll fix just those first and we'll see if the problems are deeper than that
