### ISSUE TITLE
Response timeout does not return Content-Type: `application/json`

### ISSUE THREAD

**Issue by vivster7** [broadinstitute/cromwell#947]
It would be easier to consume errors if they were wrapped in JSON. I believe 400 errors are already represented this way already, but a 500 response timeout returns with Content-Type:`text/plain`.

**Comment by mcovarr** [comment]
@vivster7 is this issue meant for 0.19 hotfix or PBE Cromwell (or both)?

**Comment by vivster7** [comment]
What is PBE Cromwell? This is present in 0.19 hot fix. Unsure about any other version

**Comment by mcovarr** [comment]
Sorry, that's Pluggable BackEnds.  😄
