### ISSUE TITLE
Cache existence of workflows in MetadataServiceActor

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#962]
Given the eventually consistent scheme in place for deriving workflow status, it's likely that a status check soon after workflow submission will fail with a 404 response.  From a UX perspective a bogus 404 error due to eventual consistency feels wrong; a lag in status update is one thing, but Cromwell probably shouldn't disavow the existence of the workflow.

**Comment by geoffjentry** [comment]
I realize now that we were talking past each other at one point last week because I asked something related to this and you said something that made it sound it was all taken care of :)

**Comment by mcovarr** [comment]
All the Centaur tests I've tried fail for this reason.  Can has prioritization?

**Comment by geoffjentry** [comment]
Yeah, I was just noticing this and wondering how @cjllanwarne has been running Centaur against develop
