### ISSUE TITLE
Fix SingleWorkflowRunnerActorSpec test HOTFIX

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#967]
Two tests in the SingleWorkflowRunnerActorSpec  0.19_hotfix have been ignored because the Workflows don't stop running when the test ends. The reason they are ignored is because they break the WorkflowManagerActorSpec tests when workflow restarts are being tested, the WFMA expects 0 wofklows to be restartable but finds that singleWorkflowRunnerActor workflows show up as being "restartable" since they never completed initially.

The test behaviors that have been ignored are: 
"successfully terminate the system on an exception
"successfully warn about unexpected output"

AC: They both require cleanup so that the workflows end up with a terminal state when the test spec end.

**Comment by kcibul** [comment]
hotfix is in the past... 0.20+ is the future ;)
