### ISSUE TITLE
Record last processed summary ID in db

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#978]
As suggested by @cjllanwarne, record the last processed metadata journal ID in the database.  This will allow Cromwell to not spin its wheels processing metadata pointlessly on restarts, as well as give more explicit control if a full summary rebuild is desired (clear WORKFLOW_METADATA_SUMMARY, reset last processed METADATA_JOURNAL id to 0).

**Comment by mcovarr** [comment]
Given @Horneth's metadata migration runs which showed 10 single sample runs correspond to ~400 million metadata records, I'm thinking this is more of a must-have than a Developer's Choice.

**Comment by geoffjentry** [comment]
It also makes me question how long RDBMS is going to work for that bit

**Comment by kcibul** [comment]
based on today's standup, let's get this in sooner rather than later
