### ISSUE TITLE
Feature request: Support multiple input JSONs

### ISSUE THREAD

**Issue by bradtaylor** [broadinstitute/cromwell#982]
We typically have workflow inputs that fall into different categories based on how often they vary.
For example there are inputs that vary according to:
Sample (every time)
Genome build (almost never)
Plexity (rarely, but sometimes)

It would be nice if we could pass multiple workflow jsons to the cromwell server. That would allow us to maintain a static, per-genome build inputs file as well as more dynamic per-run inputs files. The former points to public data and could be distributed among our collaborators when we share our method.

We get around the absence of this feature by munging multiple jsons together on every submission. But this makes things harder to share with others. It's also error prone.

Priority is low. This is a convenience and community-adoption feature- not a blocker.

**Comment by bradtaylor** [comment]
Assigned to @kcibul for backlog prioritization

**Comment by kcibul** [comment]
Also requested by @yfarjoun
