### ISSUE TITLE
Run 1 full sized WGS sample through 0.20

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#993]
Using the script in 

https://github.com/broadinstitute/dsde-pipelines/blob/master/genomes_in_the_cloud/single_sample/test_staging/launch_50_cloud_workflows.sh

as a template, run a single sample (e.g. J464) through cromwell v0.20.  That script currently runs 2 samples, 25x each against a gotc server and using files on the broad filesystem, but it provides a good starting point.

**Comment by cjllanwarne** [comment]
Great Success!
